#include "PresetBuilder.h"
#include "Builders.h"

namespace nacar::presets::detail
{
    // ===============================================================
    //  ATMOSPHERE
    // ===============================================================
    void buildAtmosphere (std::vector<FactoryPreset>& out)
    {
        // Very little source, nearly all Aura, and the output trimmed down
        // rather than the engines turned up: the quietest preset here.
        add (out, Build ("Waiting Room", "ATMOSPHERE", "MINIMAL",
                         "quiet,still,room,bed",
                         "A room with a chair in it and something running two floors down.")
            .at (48, 2, 0.55f, 9.0)
            .chain ("FILTER,SPACE,RETRO,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.40f)
            .v (PID::driftAmount, 0.26f).v (PID::driftRate, 0.04f)
            .v (PID::masterGain, -3.0f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.50f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.08f)
            .v (PID::oscASpread, 0.60f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.20f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, 4.0f)
            .v (PID::subLevel, 0.08f)
            .v (PID::noiseType, ch::nPink).v (PID::noiseLevel, 0.14f)
            .v (PID::bodyAmount, 0.16f).v (PID::densityAmount, 0.18f)
            .v (PID::postSaturation, 0.06f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1500.0f).v (PID::filterResonance, 0.08f)
            .v (PID::filterKeyTrack, 0.30f).v (PID::filterEnvAmount, 0.14f)
            .v (PID::ampAttack, 2.6f).v (PID::ampDecay, 5.0f)
            .v (PID::ampSustain, 0.72f).v (PID::ampRelease, 5.0f)
            .v (PID::ampVelocity, 0.20f)
            .v (PID::macroMemory, 0.30f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.46f).v (PID::memoryWobble, 0.20f)
            .v (PID::memoryDiffusion, 0.36f)
            .v (PID::macroCharacter, 0.20f).v (PID::macroMotion, 0.32f)
            .v (PID::macroWorld, 0.56f).v (PID::macroWeight, 0.16f)
            .v (PID::retroEra, 0.44f).v (PID::retroAge, 0.24f)
            .v (PID::retroDrift, 0.18f).v (PID::retroWear, 0.12f)
            .v (PID::retroTone, -0.24f).v (PID::retroNoise, 0.16f)
            .v (PID::retroMix, 0.54f)
            .v (PID::fxFilterCutoff, 5000.0f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.46f)
            .v (PID::spaceSize, 0.40f).v (PID::spaceDecay, 2.2f)
            .v (PID::spaceFog, 0.44f).v (PID::spaceLight, -0.32f)
            .v (PID::spacePreDelay, 18.0f).v (PID::spaceMix, 0.30f)
            .v (PID::auraSize, 0.50f).v (PID::auraDistance, 0.44f)
            .v (PID::auraFog, 0.52f).v (PID::auraDecay, 0.46f)
            .v (PID::auraLight, -0.28f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.14f)
            .v (PID::patinaNoise, 0.18f).v (PID::patinaWear, 0.20f)
            .v (PID::patinaDrift, 0.24f)
            .v (PID::synthWidth, 1.05f).v (PID::highWidth, 1.10f)
            .v (PID::breathAmount, 0.48f).v (PID::breathSpeed, 0.06f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.04f)
            .v (PID::lfo1Depth, 0.50f)
            .route (srcLfo1, PID::filterCutoff, 0.06f)
            .route (srcBreath, PID::auraDistance, 0.10f));

        // Everything large at once: INFINITE reverb inside a maximum Aura,
        // with Shadow a fifth below.  The biggest thing in the library.
        add (out, Build ("Submerged Cathedral", "ATMOSPHERE", "CINEMATIC",
                         "infinite,huge,shadow,swell",
                         "A cathedral with the water already above the windows.")
            .at (38, 3, 0.78f, 12.0)
            .chain ("FILTER,RETRO,SPACE,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.46f)
            .v (PID::driftAmount, 0.30f).v (PID::driftRate, 0.04f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.64f)
            .v (PID::oscAUnison, 4.0f).v (PID::oscADetune, 0.16f)
            .v (PID::oscASpread, 0.55f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tHollow)
            .v (PID::oscBWtPos, 0.42f).v (PID::oscBLevel, 0.44f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, -7.0f)
            .v (PID::oscCWave, ch::sine).v (PID::oscCLevel, 0.18f)
            .v (PID::oscCOctave, 1.0f).v (PID::oscCSemi, 7.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.34f)
            .v (PID::subHarmonics, 0.24f)
            .v (PID::bodyAmount, 0.50f).v (PID::densityAmount, 0.40f)
            .v (PID::preFilterDrive, 0.20f).v (PID::postSaturation, 0.18f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1600.0f).v (PID::filterResonance, 0.18f)
            .v (PID::filterDrive, 0.26f).v (PID::filterKeyTrack, 0.40f)
            .v (PID::filterEnvAmount, 0.36f)
            .v (PID::ampAttack, 2.0f).v (PID::ampDecay, 6.0f)
            .v (PID::ampSustain, 0.86f).v (PID::ampRelease, 7.0f)
            .v (PID::ampVelocity, 0.30f)
            .v (PID::env2Attack, 4.0f).v (PID::env2Decay, 6.0f)
            .v (PID::env2Sustain, 0.75f)
            .v (PID::macroMemory, 0.48f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.60f).v (PID::memoryWobble, 0.34f)
            .v (PID::memoryDiffusion, 0.56f).v (PID::memoryAsymmetry, 0.32f)
            .v (PID::macroCharacter, 0.40f).v (PID::macroMotion, 0.56f)
            .v (PID::macroWorld, 0.94f).v (PID::macroWeight, 0.44f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.42f)
            .v (PID::weightCompress, 0.38f)
            .v (PID::retroEra, 0.26f).v (PID::retroAge, 0.36f)
            .v (PID::retroDrift, 0.32f).v (PID::retroWear, 0.16f)
            .v (PID::retroTone, -0.32f).v (PID::retroNoise, 0.14f)
            .v (PID::retroMix, 0.58f)
            .v (PID::fxFilterCutoff, 4800.0f).v (PID::fxFilterMotion, 0.20f)
            .v (PID::spaceCharacter, ch::sInfinite).v (PID::spaceDistance, 0.72f)
            .v (PID::spaceSize, 0.95f).v (PID::spaceDecay, 26.0f)
            .v (PID::spaceFog, 0.72f).v (PID::spaceLight, -0.34f)
            .v (PID::spacePreDelay, 100.0f).v (PID::spaceMix, 0.52f)
            .v (PID::shadowOn, 1.0f).v (PID::shadowLength, 0.70f)
            .v (PID::shadowDistance, 0.78f).v (PID::shadowBlur, 0.80f)
            .v (PID::shadowPitch, -7.0f).v (PID::shadowLevel, 0.34f)
            .v (PID::auraSize, 0.92f).v (PID::auraDistance, 0.60f)
            .v (PID::auraFog, 0.72f).v (PID::auraDecay, 0.90f)
            .v (PID::auraLight, -0.26f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.24f)
            .v (PID::patinaNoise, 0.16f).v (PID::patinaWear, 0.30f)
            .v (PID::patinaDrift, 0.34f)
            .v (PID::synthWidth, 1.20f).v (PID::highWidth, 1.30f)
            .v (PID::lowMonoFreq, 165.0f)
            .v (PID::breathAmount, 0.62f).v (PID::breathSpeed, 0.05f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.05f)
            .v (PID::lfo1Depth, 0.65f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.06f)
            .v (PID::lfo2Depth, 0.55f)
            .route (srcLfo1, PID::filterCutoff, 0.10f)
            .route (srcLfo2, PID::shadowPitch, 0.05f)
            .route (srcBreath, PID::auraFog, 0.16f));

        // AIR noise, no oscillator fundamental to speak of, and the width
        // stage pushed - there is nothing down low for it to endanger.
        add (out, Build ("Wind in the Antenna", "ATMOSPHERE", "AIRY",
                         "wind,noise,high,wide",
                         "Air moving over metal, a long way up and nowhere near anybody.")
            .at (64, 2, 0.60f, 9.0)
            .chain ("FILTER,GRAIN,SPACE,RETRO,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.56f)
            .v (PID::driftAmount, 0.40f).v (PID::driftRate, 0.09f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.24f)
            .v (PID::oscAUnison, 3.0f).v (PID::oscADetune, 0.18f)
            .v (PID::oscASpread, 0.55f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tSpectral)
            .v (PID::oscBWtPos, 0.80f).v (PID::oscBLevel, 0.26f)
            .v (PID::oscBOctave, 1.0f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nAir).v (PID::noiseLevel, 0.58f)
            .v (PID::bodyAmount, 0.04f).v (PID::densityAmount, 0.12f)
            .v (PID::postSaturation, 0.06f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 3400.0f).v (PID::filterResonance, 0.30f)
            .v (PID::filterKeyTrack, 0.45f).v (PID::filterEnvAmount, 0.20f)
            .v (PID::ampAttack, 3.0f).v (PID::ampDecay, 6.0f)
            .v (PID::ampSustain, 0.80f).v (PID::ampRelease, 5.0f)
            .v (PID::ampVelocity, 0.22f)
            .v (PID::macroMemory, 0.18f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.22f).v (PID::memoryWobble, 0.26f)
            .v (PID::memoryDiffusion, 0.40f)
            .v (PID::macroCharacter, 0.22f).v (PID::macroMotion, 0.74f)
            .v (PID::macroWorld, 0.50f).v (PID::macroWeight, 0.30f)
            .v (PID::weightMode, ch::wAir).v (PID::weightHarmonics, 0.50f)
            .v (PID::weightCompress, 0.32f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.36f)
            .v (PID::grainSize, 160.0f).v (PID::grainDensity, 18.0f)
            .v (PID::grainPosition, 0.36f).v (PID::grainPitchMode, ch::gOctave)
            .v (PID::grainSpread, 0.38f).v (PID::grainJitter, 0.50f)
            .v (PID::grainDirection, 0.30f).v (PID::grainWindow, ch::wGauss)
            .v (PID::grainMix, 0.32f)
            .v (PID::retroEra, 0.70f).v (PID::retroAge, 0.16f)
            .v (PID::retroDrift, 0.20f).v (PID::retroWear, 0.10f)
            .v (PID::retroTone, 0.24f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.36f)
            .v (PID::fxFilterMode, ch::f2Hp).v (PID::fxFilterCutoff, 420.0f)
            .v (PID::fxFilterRes, 0.12f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.46f)
            .v (PID::spaceSize, 0.84f).v (PID::spaceDecay, 9.0f)
            .v (PID::spaceFog, 0.60f).v (PID::spaceLight, 0.34f)
            .v (PID::spacePreDelay, 40.0f).v (PID::spaceMix, 0.24f)
            .v (PID::auraSize, 0.82f).v (PID::auraDistance, 0.28f)
            .v (PID::auraFog, 0.56f).v (PID::auraDecay, 0.78f)
            .v (PID::auraLight, 0.42f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.28f)
            .v (PID::patinaNoise, 0.22f).v (PID::patinaWear, 0.26f)
            .v (PID::patinaDrift, 0.30f)
            .v (PID::synthWidth, 1.00f).v (PID::highWidth, 1.15f)
            .v (PID::lowMonoFreq, 260.0f)
            .v (PID::breathAmount, 0.76f).v (PID::breathSpeed, 0.16f)
            .v (PID::breathRandom, 0.85f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Rate, 0.13f)
            .v (PID::lfo1Depth, 0.75f)
            .route (srcLfo1, PID::filterCutoff, 0.18f)
            .route (srcBreath, PID::noiseLevel, 0.22f)
            .route (srcMotion, PID::grainJitter, 0.20f));

        // Warm, mid-forward, generation II, and nothing above 6 kHz worth
        // mentioning.  The nostalgic corner of the atmosphere group.
        add (out, Build ("Summer Memory", "ATMOSPHERE", "DREAMY",
                         "warm,soft,hazy,slow",
                         "An afternoon remembered through a window that was open at the time.")
            .at (52, 3, 0.62f, 10.0)
            .chain ("RETRO,FILTER,SPACE,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 10.0f).v (PID::voiceVariation, 0.50f)
            .v (PID::driftAmount, 0.34f).v (PID::driftRate, 0.05f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tSoft)
            .v (PID::oscAWtPos, 0.20f).v (PID::oscALevel, 0.66f)
            .v (PID::oscAUnison, 4.0f).v (PID::oscADetune, 0.18f)
            .v (PID::oscASpread, 0.70f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.36f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, 5.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.24f)
            .v (PID::subHarmonics, 0.18f)
            .v (PID::noiseType, ch::nPink).v (PID::noiseLevel, 0.10f)
            .v (PID::bodyAmount, 0.44f).v (PID::bodyTilt, 0.20f)
            .v (PID::densityAmount, 0.36f)
            .v (PID::preFilterDrive, 0.16f).v (PID::postSaturation, 0.18f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1700.0f).v (PID::filterResonance, 0.10f)
            .v (PID::filterKeyTrack, 0.45f).v (PID::filterEnvAmount, 0.30f)
            .v (PID::ampAttack, 1.8f).v (PID::ampDecay, 5.0f)
            .v (PID::ampSustain, 0.84f).v (PID::ampRelease, 4.4f)
            .v (PID::ampVelocity, 0.30f)
            .v (PID::macroMemory, 0.54f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.68f).v (PID::memoryWobble, 0.44f)
            .v (PID::memoryDiffusion, 0.50f).v (PID::memoryAsymmetry, 0.30f)
            .v (PID::macroCharacter, 0.42f).v (PID::macroMotion, 0.54f)
            .v (PID::macroWorld, 0.48f).v (PID::macroWeight, 0.38f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.36f)
            .v (PID::retroEra, 0.34f).v (PID::retroAge, 0.52f)
            .v (PID::retroDrift, 0.46f).v (PID::retroWear, 0.26f)
            .v (PID::retroTone, -0.36f).v (PID::retroNoise, 0.22f)
            .v (PID::retroMix, 0.86f)
            .v (PID::fxFilterCutoff, 4000.0f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.50f)
            .v (PID::spaceSize, 0.68f).v (PID::spaceDecay, 5.4f)
            .v (PID::spaceFog, 0.62f).v (PID::spaceLight, -0.36f)
            .v (PID::spacePreDelay, 36.0f).v (PID::spaceMix, 0.38f)
            .v (PID::auraSize, 0.68f).v (PID::auraDistance, 0.34f)
            .v (PID::auraFog, 0.64f).v (PID::auraDecay, 0.66f)
            .v (PID::auraLight, -0.32f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.28f)
            .v (PID::patinaNoise, 0.22f).v (PID::patinaWear, 0.34f)
            .v (PID::patinaDrift, 0.36f)
            .v (PID::synthWidth, 1.20f).v (PID::highWidth, 1.15f)
            .v (PID::breathAmount, 0.60f).v (PID::breathSpeed, 0.07f)
            .v (PID::breathShape, 0.26f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.06f)
            .v (PID::lfo1Depth, 0.60f)
            .route (srcLfo1, PID::filterCutoff, 0.08f)
            .route (srcBreath, PID::retroDrift, 0.22f)
            .route (srcMemory, PID::patinaWear, 0.16f));

        // Shadow at its longest with the duplicate pitched down, over a
        // DARK reverb.  The room answers later and lower than you played.
        add (out, Build ("The Empty Room", "ATMOSPHERE", "HAUNTED",
                         "shadow,dark,delay,answer",
                         "An empty room that answers a few seconds late and a fifth down.")
            .at (41, 2, 0.70f, 11.0)
            .chain ("FILTER,RETRO,SPACE,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.48f)
            .v (PID::driftAmount, 0.32f).v (PID::driftRate, 0.05f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.62f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.14f)
            .v (PID::oscASpread, 0.40f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tHollow)
            .v (PID::oscBWtPos, 0.66f).v (PID::oscBLevel, 0.34f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, -11.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.28f)
            .v (PID::subHarmonics, 0.20f)
            .v (PID::noiseType, ch::nDark).v (PID::noiseLevel, 0.16f)
            .v (PID::bodyAmount, 0.42f).v (PID::densityAmount, 0.34f)
            .v (PID::preFilterDrive, 0.16f).v (PID::postSaturation, 0.16f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1150.0f).v (PID::filterResonance, 0.20f)
            .v (PID::filterDrive, 0.22f).v (PID::filterKeyTrack, 0.40f)
            .v (PID::filterEnvAmount, 0.28f)
            .v (PID::ampAttack, 1.2f).v (PID::ampDecay, 4.5f)
            .v (PID::ampSustain, 0.78f).v (PID::ampRelease, 5.5f)
            .v (PID::ampVelocity, 0.32f)
            .v (PID::macroMemory, 0.58f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.64f).v (PID::memoryWobble, 0.46f)
            .v (PID::memoryDiffusion, 0.58f).v (PID::memoryAsymmetry, 0.40f)
            .v (PID::macroCharacter, 0.38f).v (PID::macroMotion, 0.48f)
            .v (PID::macroWorld, 0.70f).v (PID::macroWeight, 0.38f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::retroEra, 0.30f).v (PID::retroAge, 0.44f)
            .v (PID::retroDrift, 0.34f).v (PID::retroWear, 0.28f)
            .v (PID::retroTone, -0.34f).v (PID::retroNoise, 0.18f)
            .v (PID::retroMix, 0.70f)
            .v (PID::fxFilterCutoff, 3600.0f).v (PID::fxFilterMotion, 0.18f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.58f)
            .v (PID::spaceSize, 0.78f).v (PID::spaceDecay, 11.0f)
            .v (PID::spaceFog, 0.68f).v (PID::spaceLight, -0.52f)
            .v (PID::spacePreDelay, 64.0f).v (PID::spaceMix, 0.42f)
            .v (PID::shadowOn, 1.0f).v (PID::shadowLength, 0.86f)
            .v (PID::shadowDistance, 0.74f).v (PID::shadowBlur, 0.78f)
            .v (PID::shadowPitch, -7.0f).v (PID::shadowLevel, 0.46f)
            .v (PID::auraSize, 0.76f).v (PID::auraDistance, 0.52f)
            .v (PID::auraFog, 0.68f).v (PID::auraDecay, 0.74f)
            .v (PID::auraLight, -0.44f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.34f)
            .v (PID::patinaNoise, 0.24f).v (PID::patinaWear, 0.44f)
            .v (PID::patinaDrift, 0.38f)
            .v (PID::synthWidth, 1.10f).v (PID::highWidth, 1.10f)
            .v (PID::lowMonoFreq, 175.0f)
            .v (PID::breathAmount, 0.58f).v (PID::breathSpeed, 0.06f)
            .v (PID::breathRandom, 0.66f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.05f)
            .v (PID::lfo2Depth, 0.60f)
            .route (srcLfo2, PID::shadowLength, 0.18f)
            .route (srcBreath, PID::shadowBlur, 0.16f)
            .route (srcMemory, PID::spaceFog, 0.14f));
    }
}
