#include "PresetBuilder.h"
#include "Builders.h"

namespace nacar::presets::detail
{
    // ===============================================================
    //  ATMOSPHERE
    // ===============================================================
    void buildAtmosphere (std::vector<FactoryPreset>& out)
    {
        // Very little source, nearly all Aura, and the output trimmed down
        // rather than the engines turned up: the quietest preset here.
        add (out, Build ("Waiting Room", "ATMOSPHERE", "MINIMAL",
                         "quiet,still,room,bed",
                         "A room with a chair in it and something running two floors down.")
            .at (48, 2, 0.55f, 9.0)
            .chain ("FILTER,SPACE,RETRO,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.40f)
            .v (PID::driftAmount, 0.26f).v (PID::driftRate, 0.04f)
            .v (PID::masterGain, -3.0f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.50f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.08f)
            .v (PID::oscASpread, 0.60f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.20f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, 4.0f)
            .v (PID::subLevel, 0.08f)
            .v (PID::noiseType, ch::nPink).v (PID::noiseLevel, 0.14f)
            .v (PID::bodyAmount, 0.16f).v (PID::densityAmount, 0.18f)
            .v (PID::postSaturation, 0.06f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1500.0f).v (PID::filterResonance, 0.08f)
            .v (PID::filterKeyTrack, 0.30f).v (PID::filterEnvAmount, 0.14f)
            .v (PID::ampAttack, 2.6f).v (PID::ampDecay, 5.0f)
            .v (PID::ampSustain, 0.72f).v (PID::ampRelease, 5.0f)
            .v (PID::ampVelocity, 0.20f)
            .v (PID::macroMemory, 0.30f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.46f).v (PID::memoryWobble, 0.20f)
            .v (PID::memoryDiffusion, 0.36f)
            .v (PID::macroCharacter, 0.20f).v (PID::macroMotion, 0.32f)
            .v (PID::macroWorld, 0.56f).v (PID::macroWeight, 0.16f)
            .v (PID::retroEra, 0.44f).v (PID::retroAge, 0.24f)
            .v (PID::retroDrift, 0.18f).v (PID::retroWear, 0.12f)
            .v (PID::retroTone, -0.24f).v (PID::retroNoise, 0.16f)
            .v (PID::retroMix, 0.54f)
            .v (PID::fxFilterCutoff, 5000.0f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.46f)
            .v (PID::spaceSize, 0.40f).v (PID::spaceDecay, 2.2f)
            .v (PID::spaceFog, 0.44f).v (PID::spaceLight, -0.32f)
            .v (PID::spacePreDelay, 18.0f).v (PID::spaceMix, 0.30f)
            .v (PID::auraSize, 0.50f).v (PID::auraDistance, 0.44f)
            .v (PID::auraFog, 0.52f).v (PID::auraDecay, 0.46f)
            .v (PID::auraLight, -0.28f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.14f)
            .v (PID::patinaNoise, 0.18f).v (PID::patinaWear, 0.20f)
            .v (PID::patinaDrift, 0.24f)
            .v (PID::synthWidth, 1.05f).v (PID::highWidth, 1.10f)
            .v (PID::breathAmount, 0.48f).v (PID::breathSpeed, 0.06f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.04f)
            .v (PID::lfo1Depth, 0.50f)
            .route (srcLfo1, PID::filterCutoff, 0.06f)
            .route (srcBreath, PID::auraDistance, 0.10f));

        // Everything large at once: INFINITE reverb inside a maximum Aura,
        // with Shadow a fifth below.  The biggest thing in the library.
        add (out, Build ("Submerged Cathedral", "ATMOSPHERE", "CINEMATIC",
                         "infinite,huge,shadow,swell",
                         "A cathedral with the water already above the windows.")
            .at (38, 3, 0.78f, 12.0)
            .chain ("FILTER,RETRO,SPACE,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.46f)
            .v (PID::driftAmount, 0.30f).v (PID::driftRate, 0.04f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.64f)
            .v (PID::oscAUnison, 4.0f).v (PID::oscADetune, 0.16f)
            .v (PID::oscASpread, 0.55f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tHollow)
            .v (PID::oscBWtPos, 0.42f).v (PID::oscBLevel, 0.44f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, -7.0f)
            .v (PID::oscCWave, ch::sine).v (PID::oscCLevel, 0.18f)
            .v (PID::oscCOctave, 1.0f).v (PID::oscCSemi, 7.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.34f)
            .v (PID::subHarmonics, 0.24f)
            .v (PID::bodyAmount, 0.50f).v (PID::densityAmount, 0.40f)
            .v (PID::preFilterDrive, 0.20f).v (PID::postSaturation, 0.18f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1600.0f).v (PID::filterResonance, 0.18f)
            .v (PID::filterDrive, 0.26f).v (PID::filterKeyTrack, 0.40f)
            .v (PID::filterEnvAmount, 0.36f)
            .v (PID::ampAttack, 2.0f).v (PID::ampDecay, 6.0f)
            .v (PID::ampSustain, 0.86f).v (PID::ampRelease, 7.0f)
            .v (PID::ampVelocity, 0.30f)
            .v (PID::env2Attack, 4.0f).v (PID::env2Decay, 6.0f)
            .v (PID::env2Sustain, 0.75f)
            .v (PID::macroMemory, 0.48f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.60f).v (PID::memoryWobble, 0.34f)
            .v (PID::memoryDiffusion, 0.56f).v (PID::memoryAsymmetry, 0.32f)
            .v (PID::macroCharacter, 0.40f).v (PID::macroMotion, 0.56f)
            .v (PID::macroWorld, 0.94f).v (PID::macroWeight, 0.44f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.42f)
            .v (PID::weightCompress, 0.38f)
            .v (PID::retroEra, 0.26f).v (PID::retroAge, 0.36f)
            .v (PID::retroDrift, 0.32f).v (PID::retroWear, 0.16f)
            .v (PID::retroTone, -0.32f).v (PID::retroNoise, 0.14f)
            .v (PID::retroMix, 0.58f)
            .v (PID::fxFilterCutoff, 4800.0f).v (PID::fxFilterMotion, 0.20f)
            .v (PID::spaceCharacter, ch::sInfinite).v (PID::spaceDistance, 0.72f)
            .v (PID::spaceSize, 0.95f).v (PID::spaceDecay, 26.0f)
            .v (PID::spaceFog, 0.72f).v (PID::spaceLight, -0.34f)
            .v (PID::spacePreDelay, 100.0f).v (PID::spaceMix, 0.52f)
            .v (PID::shadowOn, 1.0f).v (PID::shadowLength, 0.70f)
            .v (PID::shadowDistance, 0.78f).v (PID::shadowBlur, 0.80f)
            .v (PID::shadowPitch, -7.0f).v (PID::shadowLevel, 0.34f)
            .v (PID::auraSize, 0.92f).v (PID::auraDistance, 0.60f)
            .v (PID::auraFog, 0.72f).v (PID::auraDecay, 0.90f)
            .v (PID::auraLight, -0.26f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.24f)
            .v (PID::patinaNoise, 0.16f).v (PID::patinaWear, 0.30f)
            .v (PID::patinaDrift, 0.34f)
            .v (PID::synthWidth, 1.20f).v (PID::highWidth, 1.30f)
            .v (PID::lowMonoFreq, 165.0f)
            .v (PID::breathAmount, 0.62f).v (PID::breathSpeed, 0.05f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.05f)
            .v (PID::lfo1Depth, 0.65f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.06f)
            .v (PID::lfo2Depth, 0.55f)
            .route (srcLfo1, PID::filterCutoff, 0.10f)
            .route (srcLfo2, PID::shadowPitch, 0.05f)
            .route (srcBreath, PID::auraFog, 0.16f));

        // AIR noise, no oscillator fundamental to speak of, and the width
        // stage pushed - there is nothing down low for it to endanger.
        add (out, Build ("Wind in the Antenna", "ATMOSPHERE", "AIRY",
                         "wind,noise,high,wide",
                         "Air moving over metal, a long way up and nowhere near anybody.")
            .at (64, 2, 0.60f, 9.0)
            .chain ("FILTER,GRAIN,SPACE,RETRO,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.56f)
            .v (PID::driftAmount, 0.40f).v (PID::driftRate, 0.09f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.24f)
            .v (PID::oscAUnison, 3.0f).v (PID::oscADetune, 0.18f)
            .v (PID::oscASpread, 0.55f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tSpectral)
            .v (PID::oscBWtPos, 0.80f).v (PID::oscBLevel, 0.26f)
            .v (PID::oscBOctave, 1.0f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nAir).v (PID::noiseLevel, 0.58f)
            .v (PID::bodyAmount, 0.04f).v (PID::densityAmount, 0.12f)
            .v (PID::postSaturation, 0.06f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 3400.0f).v (PID::filterResonance, 0.30f)
            .v (PID::filterKeyTrack, 0.45f).v (PID::filterEnvAmount, 0.20f)
            .v (PID::ampAttack, 3.0f).v (PID::ampDecay, 6.0f)
            .v (PID::ampSustain, 0.80f).v (PID::ampRelease, 5.0f)
            .v (PID::ampVelocity, 0.22f)
            .v (PID::macroMemory, 0.18f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.22f).v (PID::memoryWobble, 0.26f)
            .v (PID::memoryDiffusion, 0.40f)
            .v (PID::macroCharacter, 0.22f).v (PID::macroMotion, 0.74f)
            .v (PID::macroWorld, 0.50f).v (PID::macroWeight, 0.30f)
            .v (PID::weightMode, ch::wAir).v (PID::weightHarmonics, 0.50f)
            .v (PID::weightCompress, 0.32f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.36f)
            .v (PID::grainSize, 160.0f).v (PID::grainDensity, 18.0f)
            .v (PID::grainPosition, 0.36f).v (PID::grainPitchMode, ch::gOctave)
            .v (PID::grainSpread, 0.38f).v (PID::grainJitter, 0.50f)
            .v (PID::grainDirection, 0.30f).v (PID::grainWindow, ch::wGauss)
            .v (PID::grainMix, 0.32f)
            .v (PID::retroEra, 0.70f).v (PID::retroAge, 0.16f)
            .v (PID::retroDrift, 0.20f).v (PID::retroWear, 0.10f)
            .v (PID::retroTone, 0.24f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.36f)
            .v (PID::fxFilterMode, ch::f2Hp).v (PID::fxFilterCutoff, 420.0f)
            .v (PID::fxFilterRes, 0.12f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.46f)
            .v (PID::spaceSize, 0.84f).v (PID::spaceDecay, 9.0f)
            .v (PID::spaceFog, 0.60f).v (PID::spaceLight, 0.34f)
            .v (PID::spacePreDelay, 40.0f).v (PID::spaceMix, 0.24f)
            .v (PID::auraSize, 0.82f).v (PID::auraDistance, 0.28f)
            .v (PID::auraFog, 0.56f).v (PID::auraDecay, 0.78f)
            .v (PID::auraLight, 0.42f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.28f)
            .v (PID::patinaNoise, 0.22f).v (PID::patinaWear, 0.26f)
            .v (PID::patinaDrift, 0.30f)
            .v (PID::synthWidth, 1.00f).v (PID::highWidth, 1.15f)
            .v (PID::lowMonoFreq, 260.0f)
            .v (PID::breathAmount, 0.76f).v (PID::breathSpeed, 0.16f)
            .v (PID::breathRandom, 0.85f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Rate, 0.13f)
            .v (PID::lfo1Depth, 0.75f)
            .route (srcLfo1, PID::filterCutoff, 0.18f)
            .route (srcBreath, PID::noiseLevel, 0.22f)
            .route (srcMotion, PID::grainJitter, 0.20f));

        // Warm, mid-forward, generation II, and nothing above 6 kHz worth
        // mentioning.  The nostalgic corner of the atmosphere group.
        add (out, Build ("Summer Memory", "ATMOSPHERE", "DREAMY",
                         "warm,soft,hazy,slow",
                         "An afternoon remembered through a window that was open at the time.")
            .at (52, 3, 0.62f, 10.0)
            .chain ("RETRO,FILTER,SPACE,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 10.0f).v (PID::voiceVariation, 0.50f)
            .v (PID::driftAmount, 0.34f).v (PID::driftRate, 0.05f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tSoft)
            .v (PID::oscAWtPos, 0.20f).v (PID::oscALevel, 0.66f)
            .v (PID::oscAUnison, 4.0f).v (PID::oscADetune, 0.18f)
            .v (PID::oscASpread, 0.70f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.36f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, 5.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.24f)
            .v (PID::subHarmonics, 0.18f)
            .v (PID::noiseType, ch::nPink).v (PID::noiseLevel, 0.10f)
            .v (PID::bodyAmount, 0.44f).v (PID::bodyTilt, 0.20f)
            .v (PID::densityAmount, 0.36f)
            .v (PID::preFilterDrive, 0.16f).v (PID::postSaturation, 0.18f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1700.0f).v (PID::filterResonance, 0.10f)
            .v (PID::filterKeyTrack, 0.45f).v (PID::filterEnvAmount, 0.30f)
            .v (PID::ampAttack, 1.8f).v (PID::ampDecay, 5.0f)
            .v (PID::ampSustain, 0.84f).v (PID::ampRelease, 4.4f)
            .v (PID::ampVelocity, 0.30f)
            .v (PID::macroMemory, 0.54f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.68f).v (PID::memoryWobble, 0.44f)
            .v (PID::memoryDiffusion, 0.50f).v (PID::memoryAsymmetry, 0.30f)
            .v (PID::macroCharacter, 0.42f).v (PID::macroMotion, 0.54f)
            .v (PID::macroWorld, 0.48f).v (PID::macroWeight, 0.38f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.36f)
            .v (PID::retroEra, 0.34f).v (PID::retroAge, 0.52f)
            .v (PID::retroDrift, 0.46f).v (PID::retroWear, 0.26f)
            .v (PID::retroTone, -0.36f).v (PID::retroNoise, 0.22f)
            .v (PID::retroMix, 0.86f)
            .v (PID::fxFilterCutoff, 4000.0f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.50f)
            .v (PID::spaceSize, 0.68f).v (PID::spaceDecay, 5.4f)
            .v (PID::spaceFog, 0.62f).v (PID::spaceLight, -0.36f)
            .v (PID::spacePreDelay, 36.0f).v (PID::spaceMix, 0.38f)
            .v (PID::auraSize, 0.68f).v (PID::auraDistance, 0.34f)
            .v (PID::auraFog, 0.64f).v (PID::auraDecay, 0.66f)
            .v (PID::auraLight, -0.32f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.28f)
            .v (PID::patinaNoise, 0.22f).v (PID::patinaWear, 0.34f)
            .v (PID::patinaDrift, 0.36f)
            .v (PID::synthWidth, 1.20f).v (PID::highWidth, 1.15f)
            .v (PID::breathAmount, 0.60f).v (PID::breathSpeed, 0.07f)
            .v (PID::breathShape, 0.26f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.06f)
            .v (PID::lfo1Depth, 0.60f)
            .route (srcLfo1, PID::filterCutoff, 0.08f)
            .route (srcBreath, PID::retroDrift, 0.22f)
            .route (srcMemory, PID::patinaWear, 0.16f));

        // Shadow at its longest with the duplicate pitched down, over a
        // DARK reverb.  The room answers later and lower than you played.
        add (out, Build ("The Empty Room", "ATMOSPHERE", "HAUNTED",
                         "shadow,dark,delay,answer",
                         "An empty room that answers a few seconds late and a fifth down.")
            .at (41, 2, 0.70f, 11.0)
            .chain ("FILTER,RETRO,SPACE,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.48f)
            .v (PID::driftAmount, 0.32f).v (PID::driftRate, 0.05f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.62f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.14f)
            .v (PID::oscASpread, 0.40f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tHollow)
            .v (PID::oscBWtPos, 0.66f).v (PID::oscBLevel, 0.34f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, -11.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.28f)
            .v (PID::subHarmonics, 0.20f)
            .v (PID::noiseType, ch::nDark).v (PID::noiseLevel, 0.16f)
            .v (PID::bodyAmount, 0.42f).v (PID::densityAmount, 0.34f)
            .v (PID::preFilterDrive, 0.16f).v (PID::postSaturation, 0.16f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1150.0f).v (PID::filterResonance, 0.20f)
            .v (PID::filterDrive, 0.22f).v (PID::filterKeyTrack, 0.40f)
            .v (PID::filterEnvAmount, 0.28f)
            .v (PID::ampAttack, 1.2f).v (PID::ampDecay, 4.5f)
            .v (PID::ampSustain, 0.78f).v (PID::ampRelease, 5.5f)
            .v (PID::ampVelocity, 0.32f)
            .v (PID::macroMemory, 0.58f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.64f).v (PID::memoryWobble, 0.46f)
            .v (PID::memoryDiffusion, 0.58f).v (PID::memoryAsymmetry, 0.40f)
            .v (PID::macroCharacter, 0.38f).v (PID::macroMotion, 0.48f)
            .v (PID::macroWorld, 0.70f).v (PID::macroWeight, 0.38f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::retroEra, 0.30f).v (PID::retroAge, 0.44f)
            .v (PID::retroDrift, 0.34f).v (PID::retroWear, 0.28f)
            .v (PID::retroTone, -0.34f).v (PID::retroNoise, 0.18f)
            .v (PID::retroMix, 0.70f)
            .v (PID::fxFilterCutoff, 3600.0f).v (PID::fxFilterMotion, 0.18f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.58f)
            .v (PID::spaceSize, 0.78f).v (PID::spaceDecay, 11.0f)
            .v (PID::spaceFog, 0.68f).v (PID::spaceLight, -0.52f)
            .v (PID::spacePreDelay, 64.0f).v (PID::spaceMix, 0.42f)
            .v (PID::shadowOn, 1.0f).v (PID::shadowLength, 0.86f)
            .v (PID::shadowDistance, 0.74f).v (PID::shadowBlur, 0.78f)
            .v (PID::shadowPitch, -7.0f).v (PID::shadowLevel, 0.46f)
            .v (PID::auraSize, 0.76f).v (PID::auraDistance, 0.52f)
            .v (PID::auraFog, 0.68f).v (PID::auraDecay, 0.74f)
            .v (PID::auraLight, -0.44f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.34f)
            .v (PID::patinaNoise, 0.24f).v (PID::patinaWear, 0.44f)
            .v (PID::patinaDrift, 0.38f)
            .v (PID::synthWidth, 1.10f).v (PID::highWidth, 1.10f)
            .v (PID::lowMonoFreq, 175.0f)
            .v (PID::breathAmount, 0.58f).v (PID::breathSpeed, 0.06f)
            .v (PID::breathRandom, 0.66f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.05f)
            .v (PID::lfo2Depth, 0.60f)
            .route (srcLfo2, PID::shadowLength, 0.18f)
            .route (srcBreath, PID::shadowBlur, 0.16f)
            .route (srcMemory, PID::spaceFog, 0.14f));

        // ---- NIGHT AND CITY -------------------------------------------
        // The low wet bed with a half-note duck across it.  Sub-led, DARK
        // reverb, and the only preset here that uses Pulse at all.
        add (out, Build ("Madrugada", "ATMOSPHERE", "DARK",
                         "night,low,wet,pulse",
                         "A sub-led bed on a DARK reverb with a half-note duck across it, for the empty bars before the dembow arrives.")
            .at (36, 2, 0.70f, 8.0)
            .chain ("RETRO,CRUSH,FILTER,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.42f)
            .v (PID::driftAmount, 0.28f).v (PID::driftRate, 0.03f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tDark)
            .v (PID::oscAWtPos, 0.28f).v (PID::oscALevel, 0.58f)
            .v (PID::oscAUnison, 3.0f).v (PID::oscADetune, 0.14f)
            .v (PID::oscASpread, 0.45f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.30f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, -6.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.40f)
            .v (PID::subHarmonics, 0.30f)
            .v (PID::noiseType, ch::nDark).v (PID::noiseLevel, 0.12f)
            .v (PID::bodyAmount, 0.46f).v (PID::densityAmount, 0.34f)
            .v (PID::preFilterDrive, 0.18f).v (PID::postSaturation, 0.14f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 620.0f).v (PID::filterResonance, 0.22f)
            .v (PID::filterDrive, 0.24f).v (PID::filterKeyTrack, 0.35f)
            .v (PID::filterEnvAmount, 0.20f)
            .v (PID::ampAttack, 1.4f).v (PID::ampDecay, 5.0f)
            .v (PID::ampSustain, 0.82f).v (PID::ampRelease, 6.0f)
            .v (PID::ampVelocity, 0.24f)
            .v (PID::macroMemory, 0.34f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.58f).v (PID::memoryWobble, 0.28f)
            .v (PID::memoryDiffusion, 0.42f)
            .v (PID::macroCharacter, 0.34f).v (PID::macroMotion, 0.44f)
            .v (PID::macroWorld, 0.66f).v (PID::macroWeight, 0.52f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.46f)
            .v (PID::weightCompress, 0.36f)
            .v (PID::pulseOn, 1.0f).v (PID::pulseSource, ch::pClock)
            .v (PID::pulseDivision, ch::p2).v (PID::pulseDepth, 0.32f)
            .v (PID::pulseAttack, 0.02f).v (PID::pulseRelease, 0.55f)
            .v (PID::pulseSmooth, 0.70f).v (PID::pulseToVolume, 0.55f)
            .v (PID::pulseToFilter, 0.30f).v (PID::pulseToSpace, 0.25f)
            .v (PID::pulseToWidth, 0.15f)
            .v (PID::retroEra, 0.36f).v (PID::retroAge, 0.30f)
            .v (PID::retroDrift, 0.22f).v (PID::retroWear, 0.14f)
            .v (PID::retroTone, -0.30f).v (PID::retroNoise, 0.14f)
            .v (PID::retroMix, 0.50f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.16f)
            .v (PID::crushBits, 12.0f).v (PID::crushRate, 14000.0f)
            .v (PID::crushDrive, 0.12f).v (PID::crushTone, -0.30f)
            .v (PID::crushMix, 0.24f)
            .v (PID::fxFilterCutoff, 3200.0f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.54f)
            .v (PID::spaceSize, 0.72f).v (PID::spaceDecay, 8.0f)
            .v (PID::spaceFog, 0.66f).v (PID::spaceLight, -0.56f)
            .v (PID::spacePreDelay, 46.0f).v (PID::spaceMix, 0.44f)
            .v (PID::auraSize, 0.70f).v (PID::auraDistance, 0.48f)
            .v (PID::auraFog, 0.62f).v (PID::auraDecay, 0.72f)
            .v (PID::auraLight, -0.46f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.32f)
            .v (PID::patinaNoise, 0.18f).v (PID::patinaWear, 0.28f)
            .v (PID::patinaDrift, 0.30f)
            .v (PID::synthWidth, 1.05f).v (PID::highWidth, 1.20f)
            .v (PID::lowMonoFreq, 190.0f)
            .v (PID::breathAmount, 0.52f).v (PID::breathSpeed, 0.05f)
            .v (PID::breathRandom, 0.60f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.03f)
            .v (PID::lfo1Depth, 0.55f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.045f)
            .v (PID::lfo2Depth, 0.50f)
            .route (srcLfo1, PID::filterCutoff, 0.10f)
            .route (srcLfo2, PID::spaceFog, 0.12f)
            .route (srcBreath, PID::auraDistance, 0.12f)
            .route (srcOrganic, PID::oscAWtPos, 0.08f));

        // SPACE sits ahead of RETRO in the chain, so the tape stage ages the
        // reverb as well as the source.  COMB tuned low is the tonal centre.
        add (out, Build ("Calle Sin Nombre", "ATMOSPHERE", "MYSTERIOUS",
                         "street,comb,night,metal",
                         "A low COMB over saw and pink noise with the reverb placed before the tape stage, so the room is aged along with what is in it.")
            .at (40, 2, 0.66f, 8.0)
            .chain ("FILTER,SPACE,CRUSH,RETRO,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.50f)
            .v (PID::driftAmount, 0.30f).v (PID::driftRate, 0.035f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.44f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.10f)
            .v (PID::oscASpread, 0.50f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tHollow)
            .v (PID::oscBWtPos, 0.52f).v (PID::oscBLevel, 0.30f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, 9.0f)
            .v (PID::subLevel, 0.22f).v (PID::subHarmonics, 0.22f)
            .v (PID::noiseType, ch::nPink).v (PID::noiseLevel, 0.24f)
            .v (PID::bodyAmount, 0.30f).v (PID::densityAmount, 0.28f)
            .v (PID::preFilterDrive, 0.14f).v (PID::postSaturation, 0.10f)
            .v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 260.0f).v (PID::filterResonance, 0.44f)
            .v (PID::filterDrive, 0.18f).v (PID::filterKeyTrack, 0.25f)
            .v (PID::filterEnvAmount, 0.18f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Notch)
            .v (PID::filter2Cutoff, 900.0f).v (PID::filter2Res, 0.30f)
            .v (PID::filter2Mix, 0.40f)
            .v (PID::ampAttack, 1.8f).v (PID::ampDecay, 6.0f)
            .v (PID::ampSustain, 0.80f).v (PID::ampRelease, 6.5f)
            .v (PID::ampVelocity, 0.22f)
            .v (PID::macroMemory, 0.40f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.56f).v (PID::memoryWobble, 0.34f)
            .v (PID::memoryDiffusion, 0.48f).v (PID::memoryAsymmetry, 0.34f)
            .v (PID::macroCharacter, 0.36f).v (PID::macroMotion, 0.50f)
            .v (PID::macroWorld, 0.72f).v (PID::macroWeight, 0.34f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.62f)
            .v (PID::spaceSize, 0.52f).v (PID::spaceDecay, 3.6f)
            .v (PID::spaceFog, 0.52f).v (PID::spaceLight, -0.30f)
            .v (PID::spacePreDelay, 120.0f).v (PID::spaceMix, 0.46f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.14f)
            .v (PID::crushBits, 13.0f).v (PID::crushRate, 18000.0f)
            .v (PID::crushTone, -0.20f).v (PID::crushMix, 0.20f)
            .v (PID::retroEra, 0.30f).v (PID::retroAge, 0.40f)
            .v (PID::retroDrift, 0.30f).v (PID::retroWear, 0.22f)
            .v (PID::retroTone, -0.28f).v (PID::retroNoise, 0.20f)
            .v (PID::retroMix, 0.62f)
            .v (PID::fxFilterMode, ch::f2Hp).v (PID::fxFilterCutoff, 120.0f)
            .v (PID::fxFilterRes, 0.10f)
            .v (PID::auraSize, 0.62f).v (PID::auraDistance, 0.56f)
            .v (PID::auraFog, 0.58f).v (PID::auraDecay, 0.62f)
            .v (PID::auraLight, -0.34f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.22f)
            .v (PID::patinaNoise, 0.20f).v (PID::patinaWear, 0.30f)
            .v (PID::patinaDrift, 0.32f)
            .v (PID::synthWidth, 1.15f).v (PID::highWidth, 1.25f)
            .v (PID::lowMonoFreq, 150.0f)
            .v (PID::breathAmount, 0.56f).v (PID::breathSpeed, 0.04f)
            .v (PID::breathRandom, 0.70f).v (PID::breathShape, 0.40f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Rate, 0.035f)
            .v (PID::lfo1Depth, 0.60f)
            .v (PID::lfo2Shape, ch::lfoTri).v (PID::lfo2Rate, 0.02f)
            .v (PID::lfo2Depth, 0.45f)
            .route (srcLfo1, PID::filterCutoff, 0.14f)
            .route (srcLfo2, PID::filter2Cutoff, 0.12f)
            .route (srcBreath, PID::spaceDistance, 0.10f)
            .route (srcOrganic, PID::patinaDrift, 0.14f));

        // CRUSH first: the grit is inside the sound before the filter and
        // the chamber ever see it.  Noise-led, almost no oscillator.
        add (out, Build ("Bajo el Puente", "ATMOSPHERE", "DIRTY",
                         "concrete,noise,low,grit",
                         "Dust noise and a triangle sub quantised to eight bits ahead of the filter, then a chamber, so the grit is in the source and not over the room.")
            .at (38, 1, 0.72f, 7.0)
            .chain ("CRUSH,FILTER,RETRO,SPACE,REWIND,GRAIN")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.36f)
            .v (PID::driftAmount, 0.24f).v (PID::driftRate, 0.06f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.28f)
            .v (PID::oscAOctave, -1.0f)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.16f)
            .v (PID::oscBOctave, -2.0f).v (PID::oscBFine, -4.0f)
            .v (PID::subWave, ch::subTri).v (PID::subLevel, 0.34f)
            .v (PID::subHarmonics, 0.36f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.52f)
            .v (PID::bodyAmount, 0.48f).v (PID::bodyTilt, -0.24f)
            .v (PID::densityAmount, 0.38f)
            .v (PID::preFilterDrive, 0.26f).v (PID::postSaturation, 0.22f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 480.0f).v (PID::filterResonance, 0.26f)
            .v (PID::filterDrive, 0.34f).v (PID::filterKeyTrack, 0.20f)
            .v (PID::filterEnvAmount, 0.16f)
            .v (PID::ampAttack, 0.90f).v (PID::ampDecay, 4.0f)
            .v (PID::ampSustain, 0.78f).v (PID::ampRelease, 4.0f)
            .v (PID::ampVelocity, 0.26f)
            .v (PID::macroMemory, 0.44f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.66f).v (PID::memoryWobble, 0.40f)
            .v (PID::memoryDiffusion, 0.44f).v (PID::memoryAsymmetry, 0.38f)
            .v (PID::macroCharacter, 0.58f).v (PID::macroMotion, 0.40f)
            .v (PID::macroWorld, 0.58f).v (PID::macroWeight, 0.56f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.50f)
            .v (PID::weightCompress, 0.42f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.44f)
            .v (PID::crushBits, 8.0f).v (PID::crushRate, 9000.0f)
            .v (PID::crushJitter, 0.20f).v (PID::crushDrive, 0.30f)
            .v (PID::crushTone, -0.34f).v (PID::crushMix, 0.52f)
            .v (PID::retroEra, 0.22f).v (PID::retroAge, 0.48f)
            .v (PID::retroDrift, 0.26f).v (PID::retroWear, 0.34f)
            .v (PID::retroTone, -0.36f).v (PID::retroNoise, 0.22f)
            .v (PID::retroMix, 0.66f)
            .v (PID::fxFilterCutoff, 2400.0f).v (PID::fxFilterRes, 0.14f)
            .v (PID::fxFilterDrive, 0.18f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.50f)
            .v (PID::spaceSize, 0.60f).v (PID::spaceDecay, 4.2f)
            .v (PID::spaceFog, 0.58f).v (PID::spaceLight, -0.48f)
            .v (PID::spacePreDelay, 28.0f).v (PID::spaceMix, 0.36f)
            .v (PID::auraSize, 0.56f).v (PID::auraDistance, 0.46f)
            .v (PID::auraFog, 0.60f).v (PID::auraDecay, 0.56f)
            .v (PID::auraLight, -0.42f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.36f)
            .v (PID::patinaNoise, 0.30f).v (PID::patinaWear, 0.46f)
            .v (PID::patinaDrift, 0.28f)
            .v (PID::synthWidth, 0.95f).v (PID::highWidth, 1.10f)
            .v (PID::lowMonoFreq, 210.0f)
            .v (PID::breathAmount, 0.44f).v (PID::breathSpeed, 0.08f)
            .v (PID::breathRandom, 0.72f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Rate, 0.06f)
            .v (PID::lfo1Depth, 0.55f)
            .route (srcLfo1, PID::noiseLevel, 0.18f)
            .route (srcBreath, PID::crushRate, 0.14f)
            .route (srcOrganic, PID::filterCutoff, 0.12f)
            .route (srcMotion, PID::patinaWear, 0.12f));

        // REWIND sits second, so the reverb only ever hears material that has
        // already been thrown a bar backwards.  Pre-delay near zero; the
        // depth is all Distance.
        add (out, Build ("Parking Level Four", "ATMOSPHERE", "COLD",
                         "cold,hollow,distant,rewind",
                         "A hollow wavetable through HAZE with the rewind stage reaching a bar back before the DISTANT reverb ever sees it.")
            .at (43, 2, 0.64f, 8.0)
            .chain ("FILTER,REWIND,SPACE,RETRO,CRUSH,GRAIN")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.44f)
            .v (PID::driftAmount, 0.30f).v (PID::driftRate, 0.04f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tHollow)
            .v (PID::oscAWtPos, 0.34f).v (PID::oscALevel, 0.56f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.09f)
            .v (PID::oscASpread, 0.50f)
            .v (PID::oscBWave, ch::square).v (PID::oscBPulseWidth, 0.36f)
            .v (PID::oscBLevel, 0.22f).v (PID::oscBFine, -8.0f)
            .v (PID::subLevel, 0.20f)
            .v (PID::noiseType, ch::nDark).v (PID::noiseLevel, 0.14f)
            .v (PID::bodyAmount, 0.26f).v (PID::densityAmount, 0.24f)
            .v (PID::preFilterDrive, 0.10f).v (PID::postSaturation, 0.08f)
            .v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 950.0f).v (PID::filterResonance, 0.28f)
            .v (PID::filterKeyTrack, 0.30f).v (PID::filterEnvAmount, 0.22f)
            .v (PID::ampAttack, 1.6f).v (PID::ampDecay, 5.5f)
            .v (PID::ampSustain, 0.80f).v (PID::ampRelease, 5.0f)
            .v (PID::ampVelocity, 0.20f)
            .v (PID::macroMemory, 0.36f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.50f).v (PID::memoryWobble, 0.30f)
            .v (PID::memoryDiffusion, 0.46f)
            .v (PID::macroCharacter, 0.28f).v (PID::macroMotion, 0.46f)
            .v (PID::macroWorld, 0.76f).v (PID::macroWeight, 0.30f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::rewindOn, 1.0f).v (PID::rewindMode, ch::rReturn)
            .v (PID::rewindDivision, ch::rw1bar).v (PID::rewindCurve, 0.62f)
            .v (PID::rewindSpeed, 0.75f).v (PID::rewindTail, 0.46f)
            .v (PID::rewindMix, 0.34f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.76f)
            .v (PID::spaceSize, 0.80f).v (PID::spaceDecay, 7.5f)
            .v (PID::spaceFog, 0.62f).v (PID::spaceLight, -0.24f)
            .v (PID::spacePreDelay, 8.0f).v (PID::spaceMix, 0.48f)
            .v (PID::retroEra, 0.50f).v (PID::retroAge, 0.26f)
            .v (PID::retroDrift, 0.20f).v (PID::retroWear, 0.12f)
            .v (PID::retroTone, -0.18f).v (PID::retroNoise, 0.14f)
            .v (PID::retroMix, 0.44f)
            .v (PID::fxFilterMode, ch::f2Hp).v (PID::fxFilterCutoff, 200.0f)
            .v (PID::fxFilterRes, 0.08f)
            .v (PID::auraSize, 0.80f).v (PID::auraDistance, 0.64f)
            .v (PID::auraFog, 0.54f).v (PID::auraDecay, 0.70f)
            .v (PID::auraLight, -0.18f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, -0.06f)
            .v (PID::patinaNoise, 0.16f).v (PID::patinaWear, 0.22f)
            .v (PID::patinaDrift, 0.26f)
            .v (PID::synthWidth, 1.15f).v (PID::highWidth, 1.25f)
            .v (PID::lowMonoFreq, 160.0f)
            .v (PID::breathAmount, 0.50f).v (PID::breathSpeed, 0.05f)
            .v (PID::breathRandom, 0.55f).v (PID::breathShape, 0.62f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.025f)
            .v (PID::lfo1Depth, 0.60f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.07f)
            .v (PID::lfo2Depth, 0.40f)
            .route (srcLfo1, PID::spaceSize, 0.12f)
            .route (srcLfo2, PID::oscAWtPos, 0.16f)
            .route (srcBreath, PID::filterCutoff, 0.14f)
            .route (srcWorld, PID::auraFog, 0.10f));

        // ---- OUTDOOR AND WEATHER --------------------------------------
        // GRAIN ahead of everything, cutting dust noise into short grains
        // at high jitter.  The oscillators only give the grains a pitch.
        add (out, Build ("Lluvia en el Patio", "ATMOSPHERE", "INTIMATE",
                         "rain,grain,noise,close",
                         "Dust noise cut into short irregular grains before the filter and put in a small room, with the oscillators there only to give the grains something tuned to sit on.")
            .at (48, 1, 0.58f, 7.0)
            .chain ("GRAIN,FILTER,SPACE,RETRO,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.56f)
            .v (PID::driftAmount, 0.22f).v (PID::driftRate, 0.10f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.16f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.06f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tOrganic)
            .v (PID::oscBWtPos, 0.44f).v (PID::oscBLevel, 0.14f)
            .v (PID::oscBOctave, 1.0f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.62f)
            .v (PID::bodyAmount, 0.10f).v (PID::densityAmount, 0.16f)
            .v (PID::postSaturation, 0.06f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 2600.0f).v (PID::filterResonance, 0.36f)
            .v (PID::filterKeyTrack, 0.20f).v (PID::filterEnvAmount, 0.12f)
            .v (PID::ampAttack, 0.80f).v (PID::ampDecay, 4.0f)
            .v (PID::ampSustain, 0.82f).v (PID::ampRelease, 3.5f)
            .v (PID::ampVelocity, 0.18f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.62f)
            .v (PID::grainSize, 28.0f).v (PID::grainDensity, 34.0f)
            .v (PID::grainPosition, 0.22f).v (PID::grainPitchMode, ch::gFree)
            .v (PID::grainPitch, 7.0f).v (PID::grainSpread, 0.70f)
            .v (PID::grainJitter, 0.72f).v (PID::grainDirection, 0.24f)
            .v (PID::grainWindow, ch::wPercussive).v (PID::grainFeedback, 0.18f)
            .v (PID::grainMix, 0.58f)
            .v (PID::macroMemory, 0.20f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.30f).v (PID::memoryWobble, 0.18f)
            .v (PID::memoryDiffusion, 0.30f)
            .v (PID::macroCharacter, 0.24f).v (PID::macroMotion, 0.70f)
            .v (PID::macroWorld, 0.44f).v (PID::macroWeight, 0.18f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.36f)
            .v (PID::spaceSize, 0.34f).v (PID::spaceDecay, 1.6f)
            .v (PID::spaceFog, 0.36f).v (PID::spaceLight, -0.10f)
            .v (PID::spacePreDelay, 12.0f).v (PID::spaceMix, 0.34f)
            .v (PID::retroEra, 0.58f).v (PID::retroAge, 0.18f)
            .v (PID::retroDrift, 0.14f).v (PID::retroWear, 0.10f)
            .v (PID::retroTone, 0.10f).v (PID::retroNoise, 0.12f)
            .v (PID::retroMix, 0.30f)
            .v (PID::fxFilterMode, ch::f2Hp).v (PID::fxFilterCutoff, 300.0f)
            .v (PID::fxFilterRes, 0.10f)
            .v (PID::auraSize, 0.44f).v (PID::auraDistance, 0.30f)
            .v (PID::auraFog, 0.42f).v (PID::auraDecay, 0.40f)
            .v (PID::auraLight, -0.06f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.08f)
            .v (PID::patinaNoise, 0.24f).v (PID::patinaWear, 0.18f)
            .v (PID::patinaDrift, 0.22f)
            .v (PID::synthWidth, 1.10f).v (PID::highWidth, 1.20f)
            .v (PID::lowMonoFreq, 220.0f)
            .v (PID::breathAmount, 0.68f).v (PID::breathSpeed, 0.20f)
            .v (PID::breathRandom, 0.88f).v (PID::breathShape, 0.70f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Rate, 0.11f)
            .v (PID::lfo1Depth, 0.70f)
            .v (PID::lfo2Shape, ch::lfoRandom).v (PID::lfo2Rate, 0.09f)
            .v (PID::lfo2Depth, 0.50f)
            .route (srcLfo1, PID::grainDensity, 0.22f)
            .route (srcLfo2, PID::grainPosition, 0.18f)
            .route (srcBreath, PID::filterCutoff, 0.20f)
            .route (srcOrganic, PID::grainJitter, 0.16f));

        // Two LFOs at incommensurate rates - one on cutoff at 17 mHz, one on
        // noise level at 26 mHz - so the swells never coincide twice inside a
        // take.  Pink noise, a steep low-pass and a high-pass under it.
        add (out, Build ("Bajamar", "ATMOSPHERE", "COLD",
                         "sea,noise,swell,slow",
                         "Pink noise through a HAZE low-pass with two unsynchronised LFOs on cutoff and noise level, and long sparse grains across the top.")
            .at (36, 1, 0.62f, 8.0)
            .chain ("FILTER,GRAIN,RETRO,SPACE,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.48f)
            .v (PID::driftAmount, 0.34f).v (PID::driftRate, 0.02f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.20f)
            .v (PID::oscAOctave, -1.0f).v (PID::oscAUnison, 2.0f)
            .v (PID::oscADetune, 0.05f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.10f)
            .v (PID::oscBOctave, -2.0f)
            .v (PID::subLevel, 0.14f)
            .v (PID::noiseType, ch::nPink).v (PID::noiseLevel, 0.66f)
            .v (PID::bodyAmount, 0.20f).v (PID::densityAmount, 0.22f)
            .v (PID::postSaturation, 0.08f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 700.0f).v (PID::filterResonance, 0.34f)
            .v (PID::filterKeyTrack, 0.10f).v (PID::filterEnvAmount, 0.10f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Hp)
            .v (PID::filter2Cutoff, 110.0f).v (PID::filter2Res, 0.08f)
            .v (PID::filter2Mix, 0.70f)
            .v (PID::ampAttack, 2.4f).v (PID::ampDecay, 6.0f)
            .v (PID::ampSustain, 0.86f).v (PID::ampRelease, 6.0f)
            .v (PID::ampVelocity, 0.16f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.24f)
            .v (PID::grainSize, 260.0f).v (PID::grainDensity, 6.0f)
            .v (PID::grainPosition, 0.44f).v (PID::grainSpread, 0.62f)
            .v (PID::grainJitter, 0.44f).v (PID::grainDirection, 0.34f)
            .v (PID::grainWindow, ch::wGauss).v (PID::grainMix, 0.26f)
            .v (PID::macroMemory, 0.22f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.34f).v (PID::memoryWobble, 0.22f)
            .v (PID::memoryDiffusion, 0.38f)
            .v (PID::macroCharacter, 0.26f).v (PID::macroMotion, 0.66f)
            .v (PID::macroWorld, 0.70f).v (PID::macroWeight, 0.34f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.32f)
            .v (PID::retroEra, 0.46f).v (PID::retroAge, 0.22f)
            .v (PID::retroDrift, 0.28f).v (PID::retroWear, 0.12f)
            .v (PID::retroTone, -0.22f).v (PID::retroNoise, 0.16f)
            .v (PID::retroMix, 0.38f)
            .v (PID::fxFilterCutoff, 5600.0f).v (PID::fxFilterMotion, 0.16f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.68f)
            .v (PID::spaceSize, 0.88f).v (PID::spaceDecay, 12.0f)
            .v (PID::spaceFog, 0.70f).v (PID::spaceLight, -0.18f)
            .v (PID::spacePreDelay, 60.0f).v (PID::spaceMix, 0.40f)
            .v (PID::auraSize, 0.86f).v (PID::auraDistance, 0.58f)
            .v (PID::auraFog, 0.66f).v (PID::auraDecay, 0.80f)
            .v (PID::auraLight, -0.12f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.14f)
            .v (PID::patinaNoise, 0.22f).v (PID::patinaWear, 0.20f)
            .v (PID::patinaDrift, 0.34f)
            .v (PID::synthWidth, 1.10f).v (PID::highWidth, 1.20f)
            .v (PID::lowMonoFreq, 180.0f)
            .v (PID::breathAmount, 0.72f).v (PID::breathSpeed, 0.03f)
            .v (PID::breathRandom, 0.60f).v (PID::breathShape, 0.30f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.017f)
            .v (PID::lfo1Depth, 0.80f)
            .v (PID::lfo2Shape, ch::lfoTri).v (PID::lfo2Rate, 0.026f)
            .v (PID::lfo2Depth, 0.65f)
            .route (srcLfo1, PID::filterCutoff, 0.26f)
            .route (srcLfo2, PID::noiseLevel, 0.20f)
            .route (srcBreath, PID::spaceFog, 0.14f)
            .route (srcOrganic, PID::auraLight, 0.12f)
            .route (srcMotion, PID::filter2Cutoff, 0.10f));

        // ---- BRIGHT AND WARM ------------------------------------------
        // Everything tilted up instead of down: Retro tone, Space light,
        // Aura light and Patina tone all positive.  FORMANT on a soft pair.
        add (out, Build ("Campo Abierto", "ATMOSPHERE", "WARM",
                         "open,bright,organic,chamber",
                         "Two organic wavetables through the FORMANT filter into a chamber, with tape, space, aura and patina all tilted bright rather than dark.")
            .at (52, 3, 0.66f, 8.0)
            .chain ("RETRO,FILTER,GRAIN,SPACE,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 10.0f).v (PID::voiceVariation, 0.46f)
            .v (PID::driftAmount, 0.26f).v (PID::driftRate, 0.05f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tOrganic)
            .v (PID::oscAWtPos, 0.30f).v (PID::oscALevel, 0.64f)
            .v (PID::oscAUnison, 4.0f).v (PID::oscADetune, 0.16f)
            .v (PID::oscASpread, 0.70f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tSoft)
            .v (PID::oscBWtPos, 0.18f).v (PID::oscBLevel, 0.40f)
            .v (PID::oscBFine, 6.0f).v (PID::oscBUnison, 2.0f)
            .v (PID::oscBDetune, 0.10f).v (PID::oscBSpread, 0.60f)
            .v (PID::oscCWave, ch::sine).v (PID::oscCLevel, 0.14f)
            .v (PID::oscCOctave, 1.0f).v (PID::oscCSemi, 7.0f)
            .v (PID::subLevel, 0.18f).v (PID::subHarmonics, 0.16f)
            .v (PID::noiseType, ch::nAir).v (PID::noiseLevel, 0.10f)
            .v (PID::bodyAmount, 0.40f).v (PID::bodyTilt, 0.26f)
            .v (PID::densityAmount, 0.38f)
            .v (PID::preFilterDrive, 0.14f).v (PID::postSaturation, 0.16f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 2400.0f).v (PID::filterResonance, 0.24f)
            .v (PID::filterKeyTrack, 0.50f).v (PID::filterEnvAmount, 0.26f)
            .v (PID::ampAttack, 1.4f).v (PID::ampDecay, 5.0f)
            .v (PID::ampSustain, 0.86f).v (PID::ampRelease, 4.5f)
            .v (PID::ampVelocity, 0.28f)
            .v (PID::macroMemory, 0.24f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.34f).v (PID::memoryWobble, 0.20f)
            .v (PID::memoryDiffusion, 0.34f)
            .v (PID::macroCharacter, 0.28f).v (PID::macroMotion, 0.52f)
            .v (PID::macroWorld, 0.60f).v (PID::macroWeight, 0.36f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.34f)
            .v (PID::retroEra, 0.62f).v (PID::retroAge, 0.18f)
            .v (PID::retroDrift, 0.18f).v (PID::retroWear, 0.08f)
            .v (PID::retroTone, 0.22f).v (PID::retroNoise, 0.08f)
            .v (PID::retroMix, 0.34f)
            .v (PID::fxFilterCutoff, 9000.0f).v (PID::fxFilterRes, 0.08f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.22f)
            .v (PID::grainSize, 190.0f).v (PID::grainDensity, 9.0f)
            .v (PID::grainPosition, 0.30f).v (PID::grainPitchMode, ch::gFifth)
            .v (PID::grainSpread, 0.55f).v (PID::grainJitter, 0.36f)
            .v (PID::grainDirection, 0.10f).v (PID::grainMix, 0.22f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.34f)
            .v (PID::spaceSize, 0.64f).v (PID::spaceDecay, 4.6f)
            .v (PID::spaceFog, 0.42f).v (PID::spaceLight, 0.36f)
            .v (PID::spacePreDelay, 30.0f).v (PID::spaceMix, 0.36f)
            .v (PID::auraSize, 0.66f).v (PID::auraDistance, 0.30f)
            .v (PID::auraFog, 0.38f).v (PID::auraDecay, 0.62f)
            .v (PID::auraLight, 0.40f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, 0.16f)
            .v (PID::patinaNoise, 0.10f).v (PID::patinaWear, 0.14f)
            .v (PID::patinaDrift, 0.22f)
            .v (PID::synthWidth, 1.25f).v (PID::highWidth, 1.30f)
            .v (PID::lowMonoFreq, 140.0f)
            .v (PID::breathAmount, 0.54f).v (PID::breathSpeed, 0.06f)
            .v (PID::breathRandom, 0.50f).v (PID::breathShape, 0.35f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.04f)
            .v (PID::lfo1Depth, 0.55f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.028f)
            .v (PID::lfo2Depth, 0.50f)
            .route (srcLfo1, PID::oscAWtPos, 0.14f)
            .route (srcLfo2, PID::filterCutoff, 0.12f)
            .route (srcBreath, PID::oscBWtPos, 0.12f)
            .route (srcWorld, PID::spaceSize, 0.10f));

        // No sub at all and a high-pass at 380 Hz: the whole preset lives
        // above the midrange, so the width stage can be pushed hard.
        add (out, Build ("Claridad de Enero", "ATMOSPHERE", "AIRY",
                         "bright,high,wide,morning",
                         "A spectral wavetable high-passed at 380 Hz with no sub underneath it, set a long way back in a DISTANT reverb tilted bright.")
            .at (55, 3, 0.60f, 8.0)
            .chain ("FILTER,SPACE,GRAIN,RETRO,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.52f)
            .v (PID::driftAmount, 0.28f).v (PID::driftRate, 0.045f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tSpectral)
            .v (PID::oscAWtPos, 0.36f).v (PID::oscALevel, 0.54f)
            .v (PID::oscAUnison, 3.0f).v (PID::oscADetune, 0.12f)
            .v (PID::oscASpread, 0.46f)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.26f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, 4.0f)
            .v (PID::oscCWave, ch::wt).v (PID::oscCWtTable, ch::tSoft)
            .v (PID::oscCLevel, 0.12f).v (PID::oscCOctave, 2.0f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nAir).v (PID::noiseLevel, 0.18f)
            .v (PID::bodyAmount, 0.14f).v (PID::densityAmount, 0.22f)
            .v (PID::postSaturation, 0.08f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::hp)
            .v (PID::filterCutoff, 380.0f).v (PID::filterResonance, 0.16f)
            .v (PID::filterKeyTrack, 0.35f).v (PID::filterEnvAmount, 0.18f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Lp)
            .v (PID::filter2Cutoff, 8000.0f).v (PID::filter2Res, 0.10f)
            .v (PID::filter2Mix, 0.55f)
            .v (PID::ampAttack, 2.2f).v (PID::ampDecay, 6.0f)
            .v (PID::ampSustain, 0.84f).v (PID::ampRelease, 5.5f)
            .v (PID::ampVelocity, 0.20f)
            .v (PID::macroMemory, 0.14f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.20f).v (PID::memoryWobble, 0.14f)
            .v (PID::memoryDiffusion, 0.30f)
            .v (PID::macroCharacter, 0.18f).v (PID::macroMotion, 0.56f)
            .v (PID::macroWorld, 0.66f).v (PID::macroWeight, 0.30f)
            .v (PID::weightMode, ch::wAir).v (PID::weightHarmonics, 0.42f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.70f)
            .v (PID::spaceSize, 0.76f).v (PID::spaceDecay, 6.5f)
            .v (PID::spaceFog, 0.48f).v (PID::spaceLight, 0.52f)
            .v (PID::spacePreDelay, 18.0f).v (PID::spaceMix, 0.18f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.28f)
            .v (PID::grainSize, 140.0f).v (PID::grainDensity, 12.0f)
            .v (PID::grainPosition, 0.26f).v (PID::grainPitchMode, ch::gOctave)
            .v (PID::grainSpread, 0.66f).v (PID::grainJitter, 0.40f)
            .v (PID::grainDirection, 0.18f).v (PID::grainWindow, ch::wTukey)
            .v (PID::grainMix, 0.24f)
            .v (PID::retroEra, 0.76f).v (PID::retroAge, 0.12f)
            .v (PID::retroDrift, 0.14f).v (PID::retroWear, 0.06f)
            .v (PID::retroTone, 0.30f).v (PID::retroNoise, 0.08f)
            .v (PID::retroMix, 0.26f)
            .v (PID::fxFilterCutoff, 14000.0f)
            .v (PID::auraSize, 0.86f).v (PID::auraDistance, 0.64f)
            .v (PID::auraFog, 0.40f).v (PID::auraDecay, 0.80f)
            .v (PID::auraLight, 0.56f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.30f)
            .v (PID::patinaNoise, 0.12f).v (PID::patinaWear, 0.14f)
            .v (PID::patinaDrift, 0.20f)
            .v (PID::synthWidth, 1.30f).v (PID::highWidth, 1.40f)
            .v (PID::lowMonoFreq, 250.0f)
            .v (PID::breathAmount, 0.58f).v (PID::breathSpeed, 0.09f)
            .v (PID::breathRandom, 0.62f).v (PID::breathShape, 0.48f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Rate, 0.05f)
            .v (PID::lfo1Depth, 0.60f)
            .v (PID::lfo2Shape, ch::lfoSine).v (PID::lfo2Rate, 0.019f)
            .v (PID::lfo2Depth, 0.55f)
            .route (srcLfo1, PID::oscAWtPos, 0.18f)
            .route (srcLfo2, PID::auraLight, 0.14f)
            .route (srcBreath, PID::filterCutoff, 0.12f)
            .route (srcOrganic, PID::grainSpread, 0.12f));

        // ---- DRONES AND SUSTAINED BEDS --------------------------------
        // A whole tone between the oscillators with ring modulation across
        // it, used as an excitation into a thirty-second INFINITE tail held
        // at 72% wet: the reverb is the instrument, the synth is the strike.
        add (out, Build ("Cordillera", "ATMOSPHERE", "CINEMATIC",
                         "drone,infinite,ambiguous,huge",
                         "Two oscillators a whole tone apart with ring modulation between them, feeding a thirty-second INFINITE tail held at seventy-two percent wet.")
            .at (36, 2, 0.70f, 8.0)
            .chain ("FILTER,SPACE,RETRO,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.50f)
            .v (PID::driftAmount, 0.36f).v (PID::driftRate, 0.025f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.48f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.12f)
            .v (PID::oscASpread, 0.40f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.42f)
            .v (PID::oscBSemi, 2.0f).v (PID::oscBFine, -12.0f)
            .v (PID::oscRingMod, 0.30f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.26f)
            .v (PID::subHarmonics, 0.24f)
            .v (PID::noiseType, ch::nDark).v (PID::noiseLevel, 0.10f)
            .v (PID::bodyAmount, 0.44f).v (PID::bodyTilt, -0.18f)
            .v (PID::densityAmount, 0.42f)
            .v (PID::preFilterDrive, 0.22f).v (PID::postSaturation, 0.16f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 840.0f).v (PID::filterResonance, 0.30f)
            .v (PID::filterDrive, 0.28f).v (PID::filterKeyTrack, 0.25f)
            .v (PID::filterEnvAmount, 0.18f)
            .v (PID::ampAttack, 2.6f).v (PID::ampDecay, 6.0f)
            .v (PID::ampSustain, 0.60f).v (PID::ampRelease, 8.0f)
            .v (PID::ampVelocity, 0.22f)
            .v (PID::env2Attack, 5.0f).v (PID::env2Decay, 8.0f)
            .v (PID::env2Sustain, 0.70f)
            .v (PID::macroMemory, 0.30f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.48f).v (PID::memoryWobble, 0.30f)
            .v (PID::memoryDiffusion, 0.52f).v (PID::memoryAsymmetry, 0.36f)
            .v (PID::macroCharacter, 0.36f).v (PID::macroMotion, 0.58f)
            .v (PID::macroWorld, 0.96f).v (PID::macroWeight, 0.48f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.40f)
            .v (PID::weightCompress, 0.34f)
            .v (PID::spaceCharacter, ch::sInfinite).v (PID::spaceDistance, 0.66f)
            .v (PID::spaceSize, 0.98f).v (PID::spaceDecay, 30.0f)
            .v (PID::spaceFog, 0.80f).v (PID::spaceLight, -0.14f)
            .v (PID::spacePreDelay, 140.0f).v (PID::spaceMix, 0.72f)
            .v (PID::retroEra, 0.40f).v (PID::retroAge, 0.24f)
            .v (PID::retroDrift, 0.24f).v (PID::retroWear, 0.10f)
            .v (PID::retroTone, -0.16f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.40f)
            .v (PID::fxFilterCutoff, 6200.0f).v (PID::fxFilterMotion, 0.14f)
            .v (PID::auraSize, 0.96f).v (PID::auraDistance, 0.66f)
            .v (PID::auraFog, 0.78f).v (PID::auraDecay, 0.94f)
            .v (PID::auraLight, -0.10f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.12f)
            .v (PID::patinaNoise, 0.14f).v (PID::patinaWear, 0.20f)
            .v (PID::patinaDrift, 0.32f)
            .v (PID::synthWidth, 1.20f).v (PID::highWidth, 1.25f)
            .v (PID::lowMonoFreq, 170.0f)
            .v (PID::breathAmount, 0.64f).v (PID::breathSpeed, 0.03f)
            .v (PID::breathRandom, 0.55f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.015f)
            .v (PID::lfo1Depth, 0.70f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.035f)
            .v (PID::lfo2Depth, 0.55f)
            .route (srcLfo1, PID::oscBFine, 0.10f)
            .route (srcLfo2, PID::spaceLight, 0.12f)
            .route (srcBreath, PID::oscRingMod, 0.14f)
            .route (srcWorld, PID::spaceSize, 0.08f)
            .route (srcOrganic, PID::filterCutoff, 0.10f));

        // One wavetable family used twice, a fifth apart and twelve cents
        // flat, so the root of the drone is never quite settled.  The only
        // preset here with FORMANT in both the voice and the chain.
        add (out, Build ("Vereda Larga", "ATMOSPHERE", "MINIMAL",
                         "drone,vocal,formant,still",
                         "One vocal wavetable held twice, a fifth apart and twelve cents flat, through FORMANT in the voice and FORMANT again in the chain.")
            .at (41, 2, 0.60f, 8.0)
            .chain ("RETRO,FILTER,SPACE,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.40f)
            .v (PID::driftAmount, 0.32f).v (PID::driftRate, 0.02f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tVocal)
            .v (PID::oscAWtPos, 0.24f).v (PID::oscALevel, 0.58f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.07f)
            .v (PID::oscASpread, 0.45f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tVocal)
            .v (PID::oscBWtPos, 0.62f).v (PID::oscBLevel, 0.36f)
            .v (PID::oscBSemi, 7.0f).v (PID::oscBFine, -12.0f)
            .v (PID::subLevel, 0.22f).v (PID::subHarmonics, 0.18f)
            .v (PID::noiseType, ch::nTexture).v (PID::noiseLevel, 0.12f)
            .v (PID::bodyAmount, 0.32f).v (PID::densityAmount, 0.30f)
            .v (PID::preFilterDrive, 0.12f).v (PID::postSaturation, 0.10f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 700.0f).v (PID::filterResonance, 0.34f)
            .v (PID::filterKeyTrack, 0.15f).v (PID::filterEnvAmount, 0.12f)
            .v (PID::ampAttack, 2.8f).v (PID::ampDecay, 7.0f)
            .v (PID::ampSustain, 0.88f).v (PID::ampRelease, 7.0f)
            .v (PID::ampVelocity, 0.14f)
            .v (PID::macroMemory, 0.28f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.52f).v (PID::memoryWobble, 0.26f)
            .v (PID::memoryDiffusion, 0.44f)
            .v (PID::macroCharacter, 0.30f).v (PID::macroMotion, 0.38f)
            .v (PID::macroWorld, 0.62f).v (PID::macroWeight, 0.34f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::retroEra, 0.34f).v (PID::retroAge, 0.32f)
            .v (PID::retroDrift, 0.24f).v (PID::retroWear, 0.16f)
            .v (PID::retroTone, -0.26f).v (PID::retroNoise, 0.16f)
            .v (PID::retroMix, 0.52f)
            .v (PID::fxFilterMode, ch::f2Formant).v (PID::fxFilterCutoff, 1100.0f)
            .v (PID::fxFilterRes, 0.18f).v (PID::fxFilterMorph, 0.30f)
            .v (PID::fxFilterMix, 0.55f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.52f)
            .v (PID::spaceSize, 0.66f).v (PID::spaceDecay, 9.0f)
            .v (PID::spaceFog, 0.60f).v (PID::spaceLight, -0.50f)
            .v (PID::spacePreDelay, 34.0f).v (PID::spaceMix, 0.40f)
            .v (PID::auraSize, 0.68f).v (PID::auraDistance, 0.48f)
            .v (PID::auraFog, 0.58f).v (PID::auraDecay, 0.76f)
            .v (PID::auraLight, -0.40f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.26f)
            .v (PID::patinaNoise, 0.18f).v (PID::patinaWear, 0.26f)
            .v (PID::patinaDrift, 0.30f)
            .v (PID::synthWidth, 1.10f).v (PID::highWidth, 1.10f)
            .v (PID::lowMonoFreq, 155.0f)
            .v (PID::breathAmount, 0.50f).v (PID::breathSpeed, 0.025f)
            .v (PID::breathRandom, 0.45f).v (PID::breathShape, 0.55f)
            .v (PID::lfo1Shape, ch::lfoTri).v (PID::lfo1Rate, 0.012f)
            .v (PID::lfo1Depth, 0.65f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.04f)
            .v (PID::lfo2Depth, 0.45f)
            .route (srcLfo1, PID::oscBWtPos, 0.16f)
            .route (srcLfo2, PID::fxFilterCutoff, 0.14f)
            .route (srcBreath, PID::oscBFine, 0.10f)
            .route (srcMemory, PID::patinaDrift, 0.12f));

        // ---- GRANULAR CLOUDS ------------------------------------------
        // GRAIN is the atmosphere generator and SPACE is only the room it
        // stands in: 320 ms grains at seven a second with half the output
        // fed back into the buffer, mix at 74%.
        add (out, Build ("Polvo en el Aire", "ATMOSPHERE", "DREAMY",
                         "granular,cloud,soft,drift",
                         "Long sparse grains with half their output fed back into the buffer, mixed at seventy-four percent, with the chamber behind them only supplying the room.")
            .at (50, 2, 0.62f, 8.0)
            .chain ("FILTER,GRAIN,SPACE,CRUSH,RETRO,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.54f)
            .v (PID::driftAmount, 0.28f).v (PID::driftRate, 0.06f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tSoft)
            .v (PID::oscAWtPos, 0.22f).v (PID::oscALevel, 0.46f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.10f)
            .v (PID::oscASpread, 0.55f)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.22f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, -5.0f)
            .v (PID::subLevel, 0.12f)
            .v (PID::noiseType, ch::nAir).v (PID::noiseLevel, 0.12f)
            .v (PID::bodyAmount, 0.22f).v (PID::densityAmount, 0.26f)
            .v (PID::postSaturation, 0.10f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1900.0f).v (PID::filterResonance, 0.26f)
            .v (PID::filterKeyTrack, 0.40f).v (PID::filterEnvAmount, 0.20f)
            .v (PID::ampAttack, 1.0f).v (PID::ampDecay, 4.0f)
            .v (PID::ampSustain, 0.70f).v (PID::ampRelease, 4.0f)
            .v (PID::ampVelocity, 0.24f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.78f)
            .v (PID::grainSize, 320.0f).v (PID::grainDensity, 7.0f)
            .v (PID::grainPosition, 0.52f).v (PID::grainPitchMode, ch::gFifth)
            .v (PID::grainSpread, 0.82f).v (PID::grainJitter, 0.60f)
            .v (PID::grainDirection, 0.40f).v (PID::grainWindow, ch::wGauss)
            .v (PID::grainFeedback, 0.52f).v (PID::grainMix, 0.74f)
            .v (PID::macroMemory, 0.26f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.40f).v (PID::memoryWobble, 0.28f)
            .v (PID::memoryDiffusion, 0.46f)
            .v (PID::macroCharacter, 0.24f).v (PID::macroMotion, 0.68f)
            .v (PID::macroWorld, 0.62f).v (PID::macroWeight, 0.26f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.44f)
            .v (PID::spaceSize, 0.70f).v (PID::spaceDecay, 5.0f)
            .v (PID::spaceFog, 0.56f).v (PID::spaceLight, 0.12f)
            .v (PID::spacePreDelay, 24.0f).v (PID::spaceMix, 0.34f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.18f)
            .v (PID::crushBits, 11.0f).v (PID::crushRate, 20000.0f)
            .v (PID::crushJitter, 0.12f).v (PID::crushTone, 0.10f)
            .v (PID::crushMix, 0.22f)
            .v (PID::retroEra, 0.66f).v (PID::retroAge, 0.16f)
            .v (PID::retroDrift, 0.22f).v (PID::retroWear, 0.10f)
            .v (PID::retroTone, 0.14f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.30f)
            .v (PID::fxFilterCutoff, 7500.0f).v (PID::fxFilterRes, 0.10f)
            .v (PID::auraSize, 0.72f).v (PID::auraDistance, 0.42f)
            .v (PID::auraFog, 0.52f).v (PID::auraDecay, 0.66f)
            .v (PID::auraLight, 0.10f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, 0.04f)
            .v (PID::patinaNoise, 0.16f).v (PID::patinaWear, 0.18f)
            .v (PID::patinaDrift, 0.26f)
            .v (PID::synthWidth, 1.20f).v (PID::highWidth, 1.25f)
            .v (PID::lowMonoFreq, 200.0f)
            .v (PID::breathAmount, 0.66f).v (PID::breathSpeed, 0.07f)
            .v (PID::breathRandom, 0.75f).v (PID::breathShape, 0.42f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Rate, 0.033f)
            .v (PID::lfo1Depth, 0.65f)
            .v (PID::lfo2Shape, ch::lfoSine).v (PID::lfo2Rate, 0.021f)
            .v (PID::lfo2Depth, 0.55f)
            .route (srcLfo1, PID::grainPosition, 0.24f)
            .route (srcLfo2, PID::grainSize, 0.18f)
            .route (srcBreath, PID::grainDirection, 0.16f)
            .route (srcOrganic, PID::grainScatter, 0.12f)
            .route (srcMotion, PID::auraFog, 0.10f));

        // GRAIN runs first in the chain, so it granulates the raw voice and
        // throws the result into a 22-second INFINITE tail before anything
        // filters it.  The COMB in the voice is the only tuned stage left.
        add (out, Build ("Plaza a las Seis", "ATMOSPHERE", "LUSH",
                         "granular,infinite,comb,wide",
                         "Grains taken from the raw voice and thrown into a twenty-two second INFINITE tail before the chain filter ever sees them, with a keytracked COMB as the only tuned stage.")
            .at (45, 3, 0.64f, 8.0)
            .chain ("GRAIN,SPACE,FILTER,RETRO,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.58f)
            .v (PID::driftAmount, 0.30f).v (PID::driftRate, 0.05f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tMetal)
            .v (PID::oscAWtPos, 0.40f).v (PID::oscALevel, 0.44f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.12f)
            .v (PID::oscASpread, 0.60f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.28f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, 8.0f)
            .v (PID::subLevel, 0.16f)
            .v (PID::noiseType, ch::nTexture).v (PID::noiseLevel, 0.18f)
            .v (PID::bodyAmount, 0.28f).v (PID::densityAmount, 0.32f)
            .v (PID::postSaturation, 0.12f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 520.0f).v (PID::filterResonance, 0.46f)
            .v (PID::filterDrive, 0.20f).v (PID::filterKeyTrack, 0.60f)
            .v (PID::filterEnvAmount, 0.24f)
            .v (PID::ampAttack, 1.2f).v (PID::ampDecay, 4.5f)
            .v (PID::ampSustain, 0.74f).v (PID::ampRelease, 5.0f)
            .v (PID::ampVelocity, 0.26f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.70f)
            .v (PID::grainSize, 95.0f).v (PID::grainDensity, 26.0f)
            .v (PID::grainPosition, 0.38f).v (PID::grainPitchMode, ch::gOctave)
            .v (PID::grainSpread, 0.78f).v (PID::grainJitter, 0.66f)
            .v (PID::grainDirection, 0.28f).v (PID::grainWindow, ch::wTukey)
            .v (PID::grainFeedback, 0.38f).v (PID::grainMix, 0.66f)
            .v (PID::macroMemory, 0.32f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.44f).v (PID::memoryWobble, 0.32f)
            .v (PID::memoryDiffusion, 0.50f).v (PID::memoryAsymmetry, 0.30f)
            .v (PID::macroCharacter, 0.30f).v (PID::macroMotion, 0.72f)
            .v (PID::macroWorld, 0.88f).v (PID::macroWeight, 0.28f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::spaceCharacter, ch::sInfinite).v (PID::spaceDistance, 0.56f)
            .v (PID::spaceSize, 0.92f).v (PID::spaceDecay, 22.0f)
            .v (PID::spaceFog, 0.76f).v (PID::spaceLight, -0.08f)
            .v (PID::spacePreDelay, 70.0f).v (PID::spaceMix, 0.56f)
            .v (PID::retroEra, 0.48f).v (PID::retroAge, 0.22f)
            .v (PID::retroDrift, 0.26f).v (PID::retroWear, 0.14f)
            .v (PID::retroTone, -0.10f).v (PID::retroNoise, 0.14f)
            .v (PID::retroMix, 0.40f)
            .v (PID::fxFilterCutoff, 6800.0f).v (PID::fxFilterMotion, 0.22f)
            .v (PID::auraSize, 0.90f).v (PID::auraDistance, 0.52f)
            .v (PID::auraFog, 0.70f).v (PID::auraDecay, 0.86f)
            .v (PID::auraLight, -0.06f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.08f)
            .v (PID::patinaNoise, 0.18f).v (PID::patinaWear, 0.22f)
            .v (PID::patinaDrift, 0.30f)
            .v (PID::synthWidth, 1.25f).v (PID::highWidth, 1.30f)
            .v (PID::lowMonoFreq, 165.0f)
            .v (PID::breathAmount, 0.70f).v (PID::breathSpeed, 0.045f)
            .v (PID::breathRandom, 0.80f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Rate, 0.028f)
            .v (PID::lfo1Depth, 0.70f)
            .v (PID::lfo2Shape, ch::lfoTri).v (PID::lfo2Rate, 0.016f)
            .v (PID::lfo2Depth, 0.60f)
            .route (srcLfo1, PID::grainDensity, 0.20f)
            .route (srcLfo2, PID::filterCutoff, 0.16f)
            .route (srcBreath, PID::grainSpread, 0.14f)
            .route (srcOrganic, PID::spaceFog, 0.12f)
            .route (srcWorld, PID::auraSize, 0.08f));

        // ---- BROKEN AND HAUNTED ---------------------------------------
        // Generation IV, six bits, and CRUSH before RETRO, so the tape stage
        // is playing back something that was already broken when it arrived.
        add (out, Build ("Sala de Calderas", "ATMOSPHERE", "BROKEN",
                         "degraded,crushed,machine,low",
                         "Generation IV memory quantised to six bits with the tape stage after the crusher, so the room at the end is reverberating something already broken.")
            .at (39, 2, 0.68f, 7.0)
            .chain ("CRUSH,RETRO,FILTER,GRAIN,SPACE,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 5.0f).v (PID::voiceVariation, 0.62f)
            .v (PID::driftAmount, 0.40f).v (PID::driftRate, 0.07f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tAsym)
            .v (PID::oscAWtPos, 0.56f).v (PID::oscALevel, 0.52f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.18f)
            .v (PID::oscASpread, 0.40f)
            .v (PID::oscBWave, ch::square).v (PID::oscBPulseWidth, 0.28f)
            .v (PID::oscBLevel, 0.26f).v (PID::oscBOctave, -1.0f)
            .v (PID::oscBFine, -14.0f)
            .v (PID::subWave, ch::subSquare).v (PID::subLevel, 0.24f)
            .v (PID::subHarmonics, 0.30f)
            .v (PID::noiseType, ch::nDigital).v (PID::noiseLevel, 0.20f)
            .v (PID::bodyAmount, 0.38f).v (PID::bodyTilt, -0.30f)
            .v (PID::densityAmount, 0.34f)
            .v (PID::preFilterDrive, 0.28f).v (PID::postSaturation, 0.24f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 380.0f).v (PID::filterResonance, 0.52f)
            .v (PID::filterDrive, 0.30f).v (PID::filterKeyTrack, 0.30f)
            .v (PID::filterEnvAmount, 0.22f)
            .v (PID::ampAttack, 0.70f).v (PID::ampDecay, 3.5f)
            .v (PID::ampSustain, 0.72f).v (PID::ampRelease, 4.5f)
            .v (PID::ampVelocity, 0.30f)
            .v (PID::macroMemory, 0.78f).v (PID::memoryGen, ch::genIV)
            .v (PID::memoryBandwidth, 0.82f).v (PID::memoryWobble, 0.66f)
            .v (PID::memoryDiffusion, 0.62f).v (PID::memoryAsymmetry, 0.58f)
            .v (PID::macroCharacter, 0.66f).v (PID::macroMotion, 0.50f)
            .v (PID::macroWorld, 0.60f).v (PID::macroWeight, 0.42f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.44f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.58f)
            .v (PID::crushBits, 6.0f).v (PID::crushRate, 6000.0f)
            .v (PID::crushJitter, 0.34f).v (PID::crushDrive, 0.36f)
            .v (PID::crushTone, -0.28f).v (PID::crushMix, 0.62f)
            .v (PID::retroEra, 0.18f).v (PID::retroAge, 0.62f)
            .v (PID::retroDrift, 0.48f).v (PID::retroWear, 0.52f)
            .v (PID::retroTone, -0.40f).v (PID::retroNoise, 0.30f)
            .v (PID::retroMix, 0.78f)
            .v (PID::fxFilterMode, ch::f2Bp).v (PID::fxFilterCutoff, 1400.0f)
            .v (PID::fxFilterRes, 0.26f).v (PID::fxFilterDrive, 0.20f)
            .v (PID::fxFilterMorph, 0.20f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.40f)
            .v (PID::grainSize, 55.0f).v (PID::grainDensity, 16.0f)
            .v (PID::grainPosition, 0.60f).v (PID::grainPitchMode, ch::gChromatic)
            .v (PID::grainSpread, 0.50f).v (PID::grainJitter, 0.70f)
            .v (PID::grainDirection, 0.46f).v (PID::grainWindow, ch::wExpo)
            .v (PID::grainMix, 0.34f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.60f)
            .v (PID::spaceSize, 0.68f).v (PID::spaceDecay, 10.0f)
            .v (PID::spaceFog, 0.72f).v (PID::spaceLight, -0.62f)
            .v (PID::spacePreDelay, 52.0f).v (PID::spaceMix, 0.44f)
            .v (PID::auraSize, 0.64f).v (PID::auraDistance, 0.54f)
            .v (PID::auraFog, 0.70f).v (PID::auraDecay, 0.72f)
            .v (PID::auraLight, -0.54f)
            .v (PID::patinaProfile, ch::pCustom).v (PID::patinaTone, -0.42f)
            .v (PID::patinaNoise, 0.36f).v (PID::patinaWear, 0.58f)
            .v (PID::patinaDrift, 0.46f)
            .v (PID::synthWidth, 1.05f).v (PID::highWidth, 1.05f)
            .v (PID::lowMonoFreq, 185.0f)
            .v (PID::breathAmount, 0.46f).v (PID::breathSpeed, 0.09f)
            .v (PID::breathRandom, 0.90f).v (PID::breathShape, 0.80f)
            .v (PID::lfo1Shape, ch::lfoRandom).v (PID::lfo1Rate, 0.08f)
            .v (PID::lfo1Depth, 0.55f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.03f)
            .v (PID::lfo2Depth, 0.60f)
            .route (srcLfo1, PID::crushBits, 0.18f)
            .route (srcLfo2, PID::filterCutoff, 0.14f)
            .route (srcMemory, PID::retroWear, 0.18f)
            .route (srcOrganic, PID::grainPosition, 0.16f)
            .route (srcBreath, PID::memoryWobble, 0.12f));

        // REWIND first and GRAIN last: a short struck excitation is thrown
        // backwards at half speed before anything else touches it, and the
        // grain stage at the end scatters the tail, not the source.
        add (out, Build ("Faro Abandonado", "ATMOSPHERE", "HAUNTED",
                         "reverse,metal,shadow,tail",
                         "A short metallic excitation reversed at half speed at the head of the chain, aged, put in a room at three-quarters wet, then granulated at the very end.")
            .at (44, 1, 0.72f, 8.0)
            .chain ("REWIND,CRUSH,FILTER,RETRO,SPACE,GRAIN")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.56f)
            .v (PID::driftAmount, 0.34f).v (PID::driftRate, 0.08f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tMetal)
            .v (PID::oscAWtPos, 0.68f).v (PID::oscALevel, 0.56f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.16f)
            .v (PID::oscASpread, 0.50f)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.24f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, 11.0f)
            .v (PID::subLevel, 0.18f)
            .v (PID::noiseType, ch::nTexture).v (PID::noiseLevel, 0.24f)
            .v (PID::noiseAttackOnly, 0.55f)
            .v (PID::bodyAmount, 0.34f).v (PID::densityAmount, 0.30f)
            .v (PID::preFilterDrive, 0.18f).v (PID::postSaturation, 0.16f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 1300.0f).v (PID::filterResonance, 0.40f)
            .v (PID::filterKeyTrack, 0.45f).v (PID::filterEnvAmount, 0.34f)
            .v (PID::ampAttack, 0.06f).v (PID::ampDecay, 2.2f)
            .v (PID::ampSustain, 0.42f).v (PID::ampRelease, 4.0f)
            .v (PID::ampVelocity, 0.34f)
            .v (PID::env1Attack, 0.004f).v (PID::env1Decay, 1.2f)
            .v (PID::env1Sustain, 0.20f).v (PID::env1Release, 2.0f)
            .v (PID::rewindOn, 1.0f).v (PID::rewindMode, ch::rReverse)
            .v (PID::rewindDivision, ch::rw2).v (PID::rewindCurve, 0.70f)
            .v (PID::rewindSpeed, 0.50f).v (PID::rewindTail, 0.62f)
            .v (PID::rewindMix, 0.56f)
            .v (PID::macroMemory, 0.62f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.70f).v (PID::memoryWobble, 0.54f)
            .v (PID::memoryDiffusion, 0.60f).v (PID::memoryAsymmetry, 0.46f)
            .v (PID::macroCharacter, 0.48f).v (PID::macroMotion, 0.56f)
            .v (PID::macroWorld, 0.78f).v (PID::macroWeight, 0.30f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.26f)
            .v (PID::crushBits, 10.0f).v (PID::crushRate, 11000.0f)
            .v (PID::crushJitter, 0.22f).v (PID::crushTone, -0.22f)
            .v (PID::crushMix, 0.36f)
            .v (PID::fxFilterMode, ch::f2Notch).v (PID::fxFilterCutoff, 2000.0f)
            .v (PID::fxFilterRes, 0.20f).v (PID::fxFilterMorph, 0.25f)
            .v (PID::retroEra, 0.24f).v (PID::retroAge, 0.52f)
            .v (PID::retroDrift, 0.42f).v (PID::retroWear, 0.36f)
            .v (PID::retroTone, -0.30f).v (PID::retroNoise, 0.24f)
            .v (PID::retroMix, 0.68f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.58f)
            .v (PID::spaceSize, 0.56f).v (PID::spaceDecay, 6.0f)
            .v (PID::spaceFog, 0.64f).v (PID::spaceLight, -0.36f)
            .v (PID::spacePreDelay, 90.0f).v (PID::spaceMix, 0.74f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.46f)
            .v (PID::grainSize, 220.0f).v (PID::grainDensity, 8.0f)
            .v (PID::grainPosition, 0.66f).v (PID::grainPitchMode, ch::gOctave)
            .v (PID::grainSpread, 0.72f).v (PID::grainJitter, 0.58f)
            .v (PID::grainDirection, 0.52f).v (PID::grainWindow, ch::wExpo)
            .v (PID::grainFeedback, 0.30f).v (PID::grainMix, 0.42f)
            .v (PID::shadowOn, 1.0f).v (PID::shadowLength, 0.62f)
            .v (PID::shadowDistance, 0.70f).v (PID::shadowBlur, 0.72f)
            .v (PID::shadowPitch, -12.0f).v (PID::shadowLevel, 0.38f)
            .v (PID::auraSize, 0.70f).v (PID::auraDistance, 0.60f)
            .v (PID::auraFog, 0.66f).v (PID::auraDecay, 0.80f)
            .v (PID::auraLight, -0.30f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.30f)
            .v (PID::patinaNoise, 0.28f).v (PID::patinaWear, 0.42f)
            .v (PID::patinaDrift, 0.40f)
            .v (PID::synthWidth, 1.15f).v (PID::highWidth, 1.20f)
            .v (PID::lowMonoFreq, 175.0f)
            .v (PID::breathAmount, 0.60f).v (PID::breathSpeed, 0.05f)
            .v (PID::breathRandom, 0.78f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Rate, 0.037f)
            .v (PID::lfo1Depth, 0.60f)
            .v (PID::lfo2Shape, ch::lfoSine).v (PID::lfo2Rate, 0.022f)
            .v (PID::lfo2Depth, 0.50f)
            .route (srcLfo1, PID::grainPosition, 0.20f)
            .route (srcLfo2, PID::shadowBlur, 0.14f)
            .route (srcBreath, PID::spaceFog, 0.14f)
            .route (srcMemory, PID::retroDrift, 0.16f)
            .route (srcOrganic, PID::filterCutoff, 0.12f));

        // The slowest thing in the file: the cutoff LFO runs at 11 mHz, a
        // cycle of roughly a minute and a half, against a smooth-random LFO
        // at 32 mHz on the wavetable, so nothing repeats inside a take.
        add (out, Build ("Amanecer en la Autopista", "ATMOSPHERE", "NOSTALGIC",
                         "dawn,wide,slow,warm",
                         "Five detuned saws through MASS with the cutoff on an eleven-millihertz LFO and an eighteen-second INFINITE tail tilted slightly bright.")
            .at (48, 3, 0.68f, 8.0)
            .chain ("RETRO,FILTER,GRAIN,SPACE,REWIND,CRUSH")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 10.0f).v (PID::voiceVariation, 0.48f)
            .v (PID::driftAmount, 0.30f).v (PID::driftRate, 0.035f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.58f)
            .v (PID::oscAUnison, 5.0f).v (PID::oscADetune, 0.20f)
            .v (PID::oscASpread, 0.72f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tSoft)
            .v (PID::oscBWtPos, 0.26f).v (PID::oscBLevel, 0.38f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, 7.0f)
            .v (PID::oscCWave, ch::sine).v (PID::oscCLevel, 0.12f)
            .v (PID::oscCOctave, 1.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.28f)
            .v (PID::subHarmonics, 0.22f)
            .v (PID::noiseType, ch::nPink).v (PID::noiseLevel, 0.10f)
            .v (PID::bodyAmount, 0.42f).v (PID::bodyTilt, 0.18f)
            .v (PID::densityAmount, 0.40f)
            .v (PID::preFilterDrive, 0.18f).v (PID::postSaturation, 0.18f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1250.0f).v (PID::filterResonance, 0.18f)
            .v (PID::filterDrive, 0.22f).v (PID::filterKeyTrack, 0.45f)
            .v (PID::filterEnvAmount, 0.34f)
            .v (PID::ampAttack, 2.0f).v (PID::ampDecay, 6.0f)
            .v (PID::ampSustain, 0.86f).v (PID::ampRelease, 6.0f)
            .v (PID::ampVelocity, 0.26f)
            .v (PID::env2Attack, 6.0f).v (PID::env2Decay, 8.0f)
            .v (PID::env2Sustain, 0.80f)
            .v (PID::macroMemory, 0.38f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.56f).v (PID::memoryWobble, 0.32f)
            .v (PID::memoryDiffusion, 0.48f).v (PID::memoryAsymmetry, 0.28f)
            .v (PID::macroCharacter, 0.34f).v (PID::macroMotion, 0.50f)
            .v (PID::macroWorld, 0.84f).v (PID::macroWeight, 0.44f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.38f)
            .v (PID::weightCompress, 0.30f)
            .v (PID::retroEra, 0.40f).v (PID::retroAge, 0.34f)
            .v (PID::retroDrift, 0.30f).v (PID::retroWear, 0.18f)
            .v (PID::retroTone, -0.12f).v (PID::retroNoise, 0.16f)
            .v (PID::retroMix, 0.60f)
            .v (PID::fxFilterCutoff, 8200.0f).v (PID::fxFilterRes, 0.08f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.26f)
            .v (PID::grainSize, 230.0f).v (PID::grainDensity, 6.5f)
            .v (PID::grainPosition, 0.34f).v (PID::grainPitchMode, ch::gOctave)
            .v (PID::grainSpread, 0.60f).v (PID::grainJitter, 0.38f)
            .v (PID::grainDirection, 0.14f).v (PID::grainMix, 0.20f)
            .v (PID::spaceCharacter, ch::sInfinite).v (PID::spaceDistance, 0.50f)
            .v (PID::spaceSize, 0.90f).v (PID::spaceDecay, 18.0f)
            .v (PID::spaceFog, 0.66f).v (PID::spaceLight, 0.22f)
            .v (PID::spacePreDelay, 55.0f).v (PID::spaceMix, 0.50f)
            .v (PID::auraSize, 0.88f).v (PID::auraDistance, 0.44f)
            .v (PID::auraFog, 0.56f).v (PID::auraDecay, 0.88f)
            .v (PID::auraLight, 0.26f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.10f)
            .v (PID::patinaNoise, 0.14f).v (PID::patinaWear, 0.24f)
            .v (PID::patinaDrift, 0.28f)
            .v (PID::synthWidth, 1.25f).v (PID::highWidth, 1.30f)
            .v (PID::lowMonoFreq, 150.0f)
            .v (PID::breathAmount, 0.56f).v (PID::breathSpeed, 0.04f)
            .v (PID::breathRandom, 0.58f).v (PID::breathShape, 0.38f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.011f)
            .v (PID::lfo1Depth, 0.75f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.032f)
            .v (PID::lfo2Depth, 0.50f)
            .route (srcLfo1, PID::filterCutoff, 0.22f)
            .route (srcLfo2, PID::oscBWtPos, 0.14f)
            .route (srcBreath, PID::spaceLight, 0.10f)
            .route (srcWorld, PID::auraSize, 0.08f)
            .route (srcOrganic, PID::oscADetune, 0.10f));
    }
}
