#include "PresetBuilder.h"
#include "Builders.h"

namespace nacar::presets::detail
{
    // ===============================================================
    //  BASS
    //
    //  Everything in this group and the next keeps its image narrow on
    //  purpose: no unison spread worth the name, the low-mono crossover
    //  raised, Grain out of the chain and Shadow off.  A bass that is wide
    //  on a monitor is a bass that partially cancels on a club system.
    // ===============================================================
    void buildBass (std::vector<FactoryPreset>& out)
    {
        // Two saws nine cents apart is the Reese interval; MASS pulls the
        // detune in and the ladder does the rest.
        add (out, Build ("Tunnel Reese", "BASS", "DARK",
                         "reese,mono,ladder,deep",
                         "The Reese that lives under a motorway, moving slowly.")
            .at (33, 1, 1.0f, 4.0)
            .chain ("FILTER,RETRO,CRUSH,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.04f).v (PID::voiceVariation, 0.14f)
            .v (PID::driftAmount, 0.14f).v (PID::driftRate, 0.08f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.82f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.08f)
            .v (PID::oscASpread, 0.20f)
            .v (PID::oscBWave, ch::saw).v (PID::oscBLevel, 0.78f)
            .v (PID::oscBFine, 9.0f).v (PID::oscBSpread, 0.20f)
            .v (PID::oscCWave, ch::wt).v (PID::oscCWtTable, ch::tDark)
            .v (PID::oscCLevel, 0.16f).v (PID::oscCOctave, 0.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.55f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.30f)
            .v (PID::bodyAmount, 0.62f).v (PID::bodyTilt, -0.14f)
            .v (PID::densityAmount, 0.52f)
            .v (PID::preFilterDrive, 0.30f).v (PID::postSaturation, 0.22f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 780.0f).v (PID::filterResonance, 0.22f)
            .v (PID::filterDrive, 0.40f).v (PID::filterKeyTrack, 0.30f)
            .v (PID::filterEnvAmount, 0.30f).v (PID::filterVelAmount, 0.30f)
            .v (PID::ampAttack, 0.004f).v (PID::ampDecay, 1.2f)
            .v (PID::ampSustain, 0.88f).v (PID::ampRelease, 0.22f)
            .v (PID::ampVelocity, 0.40f)
            .v (PID::env1Decay, 0.22f).v (PID::env1Sustain, 0.25f)
            .v (PID::macroMemory, 0.26f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.46f).v (PID::memoryWobble, 0.18f)
            .v (PID::memoryDiffusion, 0.24f).v (PID::memoryAsymmetry, 0.10f)
            .v (PID::macroCharacter, 0.46f).v (PID::macroMotion, 0.26f)
            .v (PID::macroWorld, 0.18f).v (PID::macroWeight, 0.56f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.52f)
            .v (PID::weightCompress, 0.40f)
            .v (PID::retroEra, 0.30f).v (PID::retroAge, 0.30f)
            .v (PID::retroDrift, 0.10f).v (PID::retroWear, 0.08f)
            .v (PID::retroTone, -0.30f).v (PID::retroNoise, 0.08f)
            .v (PID::retroMix, 0.45f)
            .v (PID::fxFilterCutoff, 3200.0f).v (PID::fxFilterDrive, 0.18f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.16f)
            .v (PID::spaceSize, 0.28f).v (PID::spaceDecay, 1.0f)
            .v (PID::spaceFog, 0.30f).v (PID::spaceLight, -0.50f)
            .v (PID::spaceMix, 0.10f)
            .v (PID::auraSize, 0.24f).v (PID::auraDistance, 0.12f)
            .v (PID::auraFog, 0.34f).v (PID::auraDecay, 0.22f)
            .v (PID::auraLight, -0.40f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.24f)
            .v (PID::patinaNoise, 0.10f).v (PID::patinaWear, 0.20f)
            .v (PID::patinaDrift, 0.14f)
            .v (PID::synthWidth, 0.70f).v (PID::highWidth, 0.90f)
            .v (PID::lowMonoFreq, 220.0f)
            .v (PID::breathAmount, 0.22f).v (PID::breathSpeed, 0.14f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.20f)
            .v (PID::lfo1Depth, 0.45f)
            .route (srcLfo1, PID::filterCutoff, 0.06f)
            .route (srcTouch, PID::filterCutoff, 0.16f));

        // Triangle plus a soft-square sub through the ACETATE end of Retro,
        // and the compressor inside Weight doing the holding.
        add (out, Build ("Tape Bass", "BASS", "WARM",
                         "upright,tape,round,soft",
                         "An upright bass off a mono tape, felt more than heard.")
            .at (36, 1, 0.86f, 4.0)
            .chain ("RETRO,FILTER,SPACE,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.05f).v (PID::voiceVariation, 0.22f)
            .v (PID::driftAmount, 0.26f).v (PID::driftRate, 0.11f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.80f)
            .v (PID::oscBWave, ch::saw).v (PID::oscBLevel, 0.26f)
            .v (PID::oscBFine, -6.0f)
            .v (PID::subWave, ch::subSquare).v (PID::subLevel, 0.48f)
            .v (PID::subHarmonics, 0.44f)
            .v (PID::noiseType, ch::nTexture).v (PID::noiseLevel, 0.10f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.70f).v (PID::bodyTilt, 0.26f)
            .v (PID::densityAmount, 0.44f)
            .v (PID::preFilterDrive, 0.22f).v (PID::postSaturation, 0.24f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 620.0f).v (PID::filterResonance, 0.12f)
            .v (PID::filterDrive, 0.26f).v (PID::filterKeyTrack, 0.40f)
            .v (PID::filterEnvAmount, 0.36f).v (PID::filterVelAmount, 0.45f)
            .v (PID::ampAttack, 0.006f).v (PID::ampDecay, 1.6f)
            .v (PID::ampSustain, 0.55f).v (PID::ampRelease, 0.30f)
            .v (PID::ampVelocity, 0.62f)
            .v (PID::env1Decay, 0.20f).v (PID::env1Sustain, 0.10f)
            .v (PID::macroMemory, 0.44f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.60f).v (PID::memoryWobble, 0.26f)
            .v (PID::memoryDiffusion, 0.22f).v (PID::memoryAsymmetry, 0.08f)
            .v (PID::macroCharacter, 0.44f).v (PID::macroMotion, 0.28f)
            .v (PID::macroWorld, 0.20f).v (PID::macroWeight, 0.50f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.44f)
            .v (PID::weightCompress, 0.48f)
            .v (PID::retroEra, 0.12f).v (PID::retroAge, 0.50f)
            .v (PID::retroDrift, 0.24f).v (PID::retroWear, 0.20f)
            .v (PID::retroTone, -0.40f).v (PID::retroNoise, 0.16f)
            .v (PID::retroMix, 0.80f)
            .v (PID::fxFilterCutoff, 2600.0f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.18f)
            .v (PID::spaceSize, 0.22f).v (PID::spaceDecay, 0.8f)
            .v (PID::spaceFog, 0.26f).v (PID::spaceLight, -0.50f)
            .v (PID::spaceMix, 0.12f)
            .v (PID::auraSize, 0.22f).v (PID::auraDistance, 0.14f)
            .v (PID::auraFog, 0.40f).v (PID::auraDecay, 0.20f)
            .v (PID::auraLight, -0.44f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.32f)
            .v (PID::patinaNoise, 0.18f).v (PID::patinaWear, 0.26f)
            .v (PID::patinaDrift, 0.18f)
            .v (PID::synthWidth, 0.60f).v (PID::highWidth, 0.80f)
            .v (PID::lowMonoFreq, 240.0f)
            .v (PID::breathAmount, 0.28f).v (PID::breathSpeed, 0.13f)
            .route (srcBreath, PID::filterCutoff, 0.05f)
            .route (srcMemory, PID::retroAge, 0.18f));

        // High ladder resonance, a fast filter envelope and constant-rate
        // glide.  The acid corner - and it is mono by construction.
        add (out, Build ("Rusted Acid", "BASS", "DIRTY",
                         "acid,resonance,glide,squelch",
                         "A 303 that was left outside, with the resonance still working.")
            .at (36, 1, 1.0f, 4.0)
            .chain ("FILTER,CRUSH,RETRO,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::legato).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.055f).v (PID::glideMode, 1.0f)
            .v (PID::voiceVariation, 0.16f).v (PID::driftAmount, 0.18f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.86f)
            .v (PID::oscAUnison, 1.0f)
            .v (PID::oscBWave, ch::square).v (PID::oscBLevel, 0.22f)
            .v (PID::oscBPulseWidth, 0.42f).v (PID::oscBFine, 4.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.34f)
            .v (PID::subHarmonics, 0.36f)
            .v (PID::bodyAmount, 0.46f).v (PID::densityAmount, 0.30f)
            .v (PID::preFilterDrive, 0.48f).v (PID::postSaturation, 0.34f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 420.0f).v (PID::filterResonance, 0.74f)
            .v (PID::filterDrive, 0.52f).v (PID::filterKeyTrack, 0.45f)
            .v (PID::filterEnvAmount, 0.72f).v (PID::filterVelAmount, 0.60f)
            .v (PID::ampAttack, 0.002f).v (PID::ampDecay, 0.9f)
            .v (PID::ampSustain, 0.60f).v (PID::ampRelease, 0.18f)
            .v (PID::ampVelocity, 0.55f)
            .v (PID::env1Attack, 0.0008f).v (PID::env1Decay, 0.30f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.12f)
            .v (PID::macroMemory, 0.30f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.50f).v (PID::memoryWobble, 0.34f)
            .v (PID::memoryAsymmetry, 0.12f)
            .v (PID::macroCharacter, 0.68f).v (PID::macroMotion, 0.34f)
            .v (PID::macroWorld, 0.26f).v (PID::macroWeight, 0.44f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.50f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.30f)
            .v (PID::crushBits, 10.0f).v (PID::crushRate, 20000.0f)
            .v (PID::crushJitter, 0.10f).v (PID::crushDrive, 0.30f)
            .v (PID::crushMix, 0.38f)
            .v (PID::retroEra, 0.56f).v (PID::retroAge, 0.48f)
            .v (PID::retroDrift, 0.20f).v (PID::retroWear, 0.30f)
            .v (PID::retroTone, -0.16f).v (PID::retroNoise, 0.18f)
            .v (PID::retroMix, 0.70f)
            .v (PID::fxFilterCutoff, 4800.0f).v (PID::fxFilterRes, 0.24f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.20f)
            .v (PID::spaceSize, 0.26f).v (PID::spaceDecay, 1.2f)
            .v (PID::spaceFog, 0.28f).v (PID::spaceLight, -0.20f)
            .v (PID::spaceMix, 0.14f)
            .v (PID::auraSize, 0.26f).v (PID::auraDistance, 0.14f)
            .v (PID::auraFog, 0.30f).v (PID::auraDecay, 0.24f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.14f)
            .v (PID::patinaNoise, 0.22f).v (PID::patinaWear, 0.44f)
            .v (PID::patinaDrift, 0.22f)
            .v (PID::synthWidth, 0.65f).v (PID::highWidth, 0.85f)
            .v (PID::lowMonoFreq, 230.0f)
            .v (PID::breathAmount, 0.24f)
            .v (PID::pulseOn, 1.0f).v (PID::pulseSource, ch::pClock)
            .v (PID::pulseDivision, ch::p8).v (PID::pulseDepth, 0.30f)
            .v (PID::pulseAttack, 0.003f).v (PID::pulseRelease, 0.12f)
            .v (PID::pulseSmooth, 0.30f).v (PID::pulseToVolume, 0.55f)
            .v (PID::pulseToFilter, 0.40f).v (PID::pulseToSpace, 0.40f)
            .v (PID::pulseToWidth, 0.0f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Rate, 0.9f)
            .v (PID::lfo1Depth, 0.55f)
            .route (srcLfo1, PID::filterCutoff, 0.12f)
            .route (srcTouch, PID::filterResonance, 0.18f));

        // MIRAGE and the DARK DIGITAL table: a clean, modern, narrow bass
        // with almost no Memory on it at all, so the library has a dry one.
        add (out, Build ("Glass Bass", "BASS", "COLD",
                         "wavetable,clean,tight,modern",
                         "A bass with no history, which in this instrument is a decision.")
            .at (36, 1, 0.94f, 3.5)
            .chain ("FILTER,CRUSH,SPACE,RETRO,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::voiceVariation, 0.10f).v (PID::driftAmount, 0.05f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tDark)
            .v (PID::oscAWtPos, 0.30f).v (PID::oscALevel, 0.78f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tHollow)
            .v (PID::oscBWtPos, 0.58f).v (PID::oscBLevel, 0.40f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBPhase, ch::phaseReset)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.52f)
            .v (PID::subHarmonics, 0.22f)
            .v (PID::bodyAmount, 0.34f).v (PID::densityAmount, 0.26f)
            .v (PID::preFilterDrive, 0.14f).v (PID::postSaturation, 0.10f)
            .v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1700.0f).v (PID::filterResonance, 0.14f)
            .v (PID::filterKeyTrack, 0.35f).v (PID::filterEnvAmount, 0.42f)
            .v (PID::filterVelAmount, 0.40f)
            .v (PID::ampAttack, 0.001f).v (PID::ampDecay, 0.7f)
            .v (PID::ampSustain, 0.72f).v (PID::ampRelease, 0.14f)
            .v (PID::ampVelocity, 0.45f)
            .v (PID::env1Attack, 0.0006f).v (PID::env1Decay, 0.16f)
            .v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.06f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.10f).v (PID::memoryWobble, 0.04f)
            .v (PID::macroCharacter, 0.18f).v (PID::macroMotion, 0.16f)
            .v (PID::macroWorld, 0.14f).v (PID::macroWeight, 0.52f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.58f)
            .v (PID::weightCompress, 0.36f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.16f)
            .v (PID::crushBits, 15.0f).v (PID::crushRate, 32000.0f)
            .v (PID::crushTone, 0.10f).v (PID::crushMix, 0.28f)
            .v (PID::retroOn, 0.0f)
            .v (PID::fxFilterCutoff, 6000.0f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.14f)
            .v (PID::spaceSize, 0.20f).v (PID::spaceDecay, 0.6f)
            .v (PID::spaceFog, 0.18f).v (PID::spaceLight, 0.10f)
            .v (PID::spaceMix, 0.08f)
            .v (PID::auraSize, 0.20f).v (PID::auraDistance, 0.10f)
            .v (PID::auraFog, 0.20f).v (PID::auraDecay, 0.18f)
            .v (PID::auraLight, 0.14f)
            .v (PID::patinaOn, 0.0f)
            .v (PID::synthWidth, 0.72f).v (PID::highWidth, 0.95f)
            .v (PID::lowMonoFreq, 250.0f)
            .v (PID::breathOn, 0.0f).v (PID::breathAmount, 0.0f)
            .v (PID::lfo1Shape, ch::lfoTri).v (PID::lfo1Rate, 0.30f)
            .v (PID::lfo1Depth, 0.40f)
            .route (srcLfo1, PID::oscAWtPos, 0.18f)
            .route (srcWheel, PID::filterCutoff, 0.25f));
    }
}
