#include "PresetBuilder.h"
#include "Builders.h"

namespace nacar::presets::detail
{
    // ===============================================================
    //  BELLS
    // ===============================================================
    void buildBells (std::vector<FactoryPreset>& out)
    {
        // Seven of these are struck PM bells, and the index envelope - mod
        // envelope 2 into pmEnvAmount - is most of what separates them from
        // each other: depth and decay are per preset, longest on the tubular
        // bell and shortest on the glass one.  Envelope 1 stays on the filter,
        // so the index collapses on its own clock rather than the cutoff's.
        // Left out deliberately: the four COMB-excited bells, which have no
        // index at all; the four FORMANT bells, where envelope 2 is already
        // the vowel sweep; Harbour Bell, which is FM and not PM; and Novena,
        // whose PM is a fixed edge on a wavetable rather than a strike.

        // Audio-rate FM at a deliberately inharmonic ratio, which is what
        // makes a bell a bell.  The decay is long and the filter tracks.
        add (out, Build ("Harbour Bell", "BELLS", "MYSTERIOUS",
                         "fm,inharmonic,long decay,distant",
                         "A buoy bell heard across water, ringing at nobody in particular.")
            .at (55, 1, 0.75f, 7.0)
            .chain ("FILTER,RETRO,SPACE,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.34f)
            .v (PID::driftAmount, 0.20f).v (PID::driftRate, 0.08f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.84f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.0f)
            .v (PID::oscBSemi, 5.0f).v (PID::oscBFine, 23.0f)
            .v (PID::oscBOctave, 1.0f)
            .v (PID::oscFmAmount, 0.46f)
            .v (PID::oscCWave, ch::sine).v (PID::oscCLevel, 0.16f)
            .v (PID::oscCOctave, 2.0f).v (PID::oscCSemi, 3.0f)
            .v (PID::oscCFine, -18.0f).v (PID::oscCPan, 0.35f)
            .v (PID::subLevel, 0.10f)
            .v (PID::bodyAmount, 0.20f).v (PID::densityAmount, 0.18f)
            .v (PID::postSaturation, 0.08f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 5200.0f).v (PID::filterResonance, 0.12f)
            .v (PID::filterKeyTrack, 0.95f).v (PID::filterEnvAmount, 0.40f)
            .v (PID::filterVelAmount, 0.50f)
            .v (PID::ampAttack, 0.0015f).v (PID::ampDecay, 6.0f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 3.2f)
            .v (PID::ampVelocity, 0.62f)
            .v (PID::env1Attack, 0.001f).v (PID::env1Decay, 1.4f)
            .v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.30f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.42f).v (PID::memoryWobble, 0.30f)
            .v (PID::memoryDiffusion, 0.44f)
            .v (PID::macroCharacter, 0.24f).v (PID::macroMotion, 0.40f)
            .v (PID::macroWorld, 0.72f).v (PID::macroWeight, 0.24f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::retroEra, 0.48f).v (PID::retroAge, 0.24f)
            .v (PID::retroDrift, 0.26f).v (PID::retroWear, 0.12f)
            .v (PID::retroTone, -0.14f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.46f)
            .v (PID::fxFilterCutoff, 9000.0f).v (PID::fxFilterMotion, 0.18f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.66f)
            .v (PID::spaceSize, 0.78f).v (PID::spaceDecay, 8.0f)
            .v (PID::spaceFog, 0.54f).v (PID::spaceLight, -0.16f)
            .v (PID::spacePreDelay, 12.0f).v (PID::spaceMix, 0.42f)
            .v (PID::auraSize, 0.72f).v (PID::auraDistance, 0.50f)
            .v (PID::auraFog, 0.50f).v (PID::auraDecay, 0.66f)
            .v (PID::auraLight, -0.10f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.10f)
            .v (PID::patinaNoise, 0.12f).v (PID::patinaWear, 0.26f)
            .v (PID::patinaDrift, 0.30f)
            .v (PID::synthWidth, 1.15f).v (PID::highWidth, 1.25f)
            .v (PID::breathAmount, 0.44f).v (PID::breathSpeed, 0.12f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.16f)
            .v (PID::lfo1Depth, 0.55f)
            .route (srcLfo1, PID::oscFmAmount, 0.12f)
            .route (srcBreath, PID::spaceDistance, 0.14f)
            .route (srcWheel, PID::oscFmAmount, 0.30f));

        // Generation IV plus the highest wobble in the library.  The
        // instability IS the preset; the oscillator underneath is plain.
        add (out, Build ("Broken Music Box", "BELLS", "HAUNTED",
                         "music box,wobble,generation iv,small",
                         "A music box with a bent comb, running down for the last time.")
            .at (72, 1, 0.68f, 5.0)
            .chain ("CRUSH,RETRO,FILTER,GRAIN,SPACE,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::masterGain, 11.0f)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.60f)
            .v (PID::driftAmount, 0.44f).v (PID::driftRate, 0.34f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.90f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.22f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBSemi, 7.0f)
            .v (PID::oscBFine, 27.0f)
            .v (PID::oscRingMod, 0.26f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.12f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.14f).v (PID::densityAmount, 0.14f)
            .v (PID::postSaturation, 0.10f)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 2400.0f).v (PID::filterResonance, 0.42f)
            .v (PID::filterKeyTrack, 1.0f).v (PID::filterEnvAmount, 0.34f)
            .v (PID::ampAttack, 0.0008f).v (PID::ampDecay, 2.2f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 1.4f)
            .v (PID::ampVelocity, 0.58f)
            .v (PID::env1Decay, 0.35f).v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.68f).v (PID::memoryGen, ch::genIV)
            .v (PID::memoryBandwidth, 0.78f).v (PID::memoryWobble, 0.88f)
            .v (PID::memoryDiffusion, 0.52f).v (PID::memoryAsymmetry, 0.58f)
            .v (PID::macroCharacter, 0.52f).v (PID::macroMotion, 0.72f)
            .v (PID::macroWorld, 0.42f).v (PID::macroWeight, 0.18f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.30f)
            .v (PID::crushBits, 8.0f).v (PID::crushRate, 12000.0f)
            .v (PID::crushJitter, 0.42f).v (PID::crushTone, -0.14f)
            .v (PID::crushMix, 0.44f)
            .v (PID::retroEra, 0.34f).v (PID::retroAge, 0.62f)
            .v (PID::retroDrift, 0.66f).v (PID::retroWear, 0.52f)
            .v (PID::retroTone, -0.18f).v (PID::retroNoise, 0.24f)
            .v (PID::retroMix, 0.88f)
            .v (PID::fxFilterCutoff, 6400.0f).v (PID::fxFilterRes, 0.16f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.48f)
            .v (PID::spaceSize, 0.44f).v (PID::spaceDecay, 3.4f)
            .v (PID::spaceFog, 0.58f).v (PID::spaceLight, -0.40f)
            .v (PID::spaceMix, 0.34f)
            .v (PID::auraSize, 0.48f).v (PID::auraDistance, 0.38f)
            .v (PID::auraFog, 0.62f).v (PID::auraDecay, 0.48f)
            .v (PID::auraLight, -0.26f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.22f)
            .v (PID::patinaNoise, 0.28f).v (PID::patinaWear, 0.52f)
            .v (PID::patinaDrift, 0.46f)
            .v (PID::breathAmount, 0.62f).v (PID::breathSpeed, 0.40f)
            .v (PID::breathRandom, 0.82f).v (PID::breathShape, 0.72f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.38f)
            .v (PID::lfo2Depth, 0.70f)
            .route (srcLfo2, PID::oscBFine, 0.10f)
            .route (srcBreath, PID::memoryWobble, 0.24f)
            .route (srcOrganic, PID::crushJitter, 0.20f));

        // The brightest preset in the library: METALLIC high, AIR weight,
        // CHROME surface, and nothing below 200 Hz to get in the way.
        add (out, Build ("Chrome Glockenspiel", "BELLS", "AIRY",
                         "metallic,bright,air,short",
                         "Struck metal with all the weight taken out and only the shine left.")
            .at (79, 1, 0.80f, 3.0)
            .chain ("FILTER,SPACE,RETRO,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 12.0f).v (PID::voiceVariation, 0.24f)
            .v (PID::driftAmount, 0.08f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tMetal)
            .v (PID::oscAWtPos, 0.18f).v (PID::oscALevel, 0.66f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.34f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBSemi, 4.0f)
            .v (PID::oscBPan, -0.12f)
            .v (PID::oscCWave, ch::sine).v (PID::oscCLevel, 0.12f)
            .v (PID::oscCOctave, 2.0f).v (PID::oscCPan, 0.14f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nAir).v (PID::noiseLevel, 0.12f)
            .v (PID::noiseAttackOnly, 0.85f)
            .v (PID::bodyAmount, 0.06f).v (PID::densityAmount, 0.08f)
            .v (PID::postSaturation, 0.06f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::hp)
            .v (PID::filterCutoff, 300.0f).v (PID::filterResonance, 0.08f)
            .v (PID::filterKeyTrack, 0.30f).v (PID::filterEnvAmount, 0.0f)
            .v (PID::filterVelAmount, 0.20f)
            .v (PID::ampAttack, 0.0006f).v (PID::ampDecay, 1.4f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.9f)
            .v (PID::ampVelocity, 0.72f)
            .v (PID::macroMemory, 0.10f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.14f).v (PID::memoryWobble, 0.10f)
            .v (PID::macroCharacter, 0.14f).v (PID::macroMotion, 0.24f)
            .v (PID::macroWorld, 0.56f).v (PID::macroWeight, 0.34f)
            .v (PID::weightMode, ch::wAir).v (PID::weightHarmonics, 0.56f)
            .v (PID::weightCompress, 0.30f)
            .v (PID::retroEra, 0.94f).v (PID::retroAge, 0.08f)
            .v (PID::retroDrift, 0.06f).v (PID::retroWear, 0.04f)
            .v (PID::retroTone, 0.30f).v (PID::retroNoise, 0.04f)
            .v (PID::retroMix, 0.30f)
            .v (PID::fxFilterCutoff, 17000.0f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.40f)
            .v (PID::spaceSize, 0.62f).v (PID::spaceDecay, 4.4f)
            .v (PID::spaceFog, 0.34f).v (PID::spaceLight, 0.52f)
            .v (PID::spacePreDelay, 30.0f).v (PID::spaceMix, 0.26f)
            .v (PID::auraSize, 0.58f).v (PID::auraDistance, 0.24f)
            .v (PID::auraFog, 0.30f).v (PID::auraDecay, 0.52f)
            .v (PID::auraLight, 0.56f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.34f)
            .v (PID::patinaNoise, 0.10f).v (PID::patinaWear, 0.18f)
            .v (PID::patinaDrift, 0.12f)
            .v (PID::synthWidth, 1.00f).v (PID::highWidth, 1.20f)
            .v (PID::lowMonoFreq, 250.0f)
            .v (PID::breathAmount, 0.24f).v (PID::breathSpeed, 0.30f)
            .v (PID::lfo1Shape, ch::lfoTri).v (PID::lfo1Rate, 0.42f)
            .v (PID::lfo1Depth, 0.40f)
            .route (srcLfo1, PID::oscAWtPos, 0.18f)
            .route (srcBreath, PID::auraLight, 0.12f));

        // Ring modulation between two detuned saws, INFINITE space and the
        // longest decay in the library.  This is the cinematic corner.
        add (out, Build ("Distant Church Bells", "BELLS", "CINEMATIC",
                         "ring mod,infinite,huge,slow",
                         "Bells from a town you are driving away from, in a reverb with no end.")
            .at (43, 2, 0.90f, 11.0)
            .chain ("FILTER,RETRO,GRAIN,SPACE,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.40f)
            .v (PID::driftAmount, 0.24f).v (PID::driftRate, 0.05f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.72f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.10f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.24f)
            .v (PID::oscBSemi, 6.0f).v (PID::oscBFine, 17.0f)
            .v (PID::oscRingMod, 0.52f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.30f)
            .v (PID::subHarmonics, 0.26f)
            .v (PID::bodyAmount, 0.48f).v (PID::densityAmount, 0.30f)
            .v (PID::preFilterDrive, 0.18f).v (PID::postSaturation, 0.18f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 2800.0f).v (PID::filterResonance, 0.22f)
            .v (PID::filterDrive, 0.28f).v (PID::filterKeyTrack, 0.70f)
            .v (PID::filterEnvAmount, 0.48f).v (PID::filterVelAmount, 0.50f)
            .v (PID::ampAttack, 0.004f).v (PID::ampDecay, 9.0f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 7.0f)
            .v (PID::ampVelocity, 0.60f)
            .v (PID::env1Attack, 0.002f).v (PID::env1Decay, 2.6f)
            .v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.36f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.52f).v (PID::memoryWobble, 0.34f)
            .v (PID::memoryDiffusion, 0.50f).v (PID::memoryAsymmetry, 0.30f)
            .v (PID::macroCharacter, 0.42f).v (PID::macroMotion, 0.44f)
            .v (PID::macroWorld, 0.88f).v (PID::macroWeight, 0.46f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.40f)
            .v (PID::weightCompress, 0.36f)
            .v (PID::retroEra, 0.24f).v (PID::retroAge, 0.34f)
            .v (PID::retroDrift, 0.30f).v (PID::retroWear, 0.18f)
            .v (PID::retroTone, -0.28f).v (PID::retroNoise, 0.14f)
            .v (PID::retroMix, 0.62f)
            .v (PID::fxFilterCutoff, 5800.0f).v (PID::fxFilterMotion, 0.24f)
            .v (PID::spaceCharacter, ch::sInfinite).v (PID::spaceDistance, 0.70f)
            .v (PID::spaceSize, 0.92f).v (PID::spaceDecay, 22.0f)
            .v (PID::spaceFog, 0.66f).v (PID::spaceLight, -0.24f)
            .v (PID::spacePreDelay, 80.0f).v (PID::spaceMix, 0.50f)
            .v (PID::shadowOn, 1.0f).v (PID::shadowLength, 0.60f)
            .v (PID::shadowDistance, 0.72f).v (PID::shadowBlur, 0.66f)
            .v (PID::shadowPitch, -12.0f).v (PID::shadowLevel, 0.30f)
            .v (PID::auraSize, 0.86f).v (PID::auraDistance, 0.56f)
            .v (PID::auraFog, 0.58f).v (PID::auraDecay, 0.84f)
            .v (PID::auraLight, -0.18f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.20f)
            .v (PID::patinaNoise, 0.16f).v (PID::patinaWear, 0.30f)
            .v (PID::patinaDrift, 0.28f)
            .v (PID::synthWidth, 1.20f).v (PID::highWidth, 1.30f)
            .v (PID::lowMonoFreq, 160.0f)
            .v (PID::breathAmount, 0.50f).v (PID::breathSpeed, 0.06f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.07f)
            .v (PID::lfo1Depth, 0.60f)
            .route (srcLfo1, PID::oscRingMod, 0.14f)
            .route (srcBreath, PID::shadowPitch, 0.06f)
            .route (srcWorld, PID::spaceSize, 0.12f));

        // PM at a sharp fourth two octaves up, so the modulator is not a whole
        // multiple of the carrier.  Mod envelope 2 owns the index and takes the
        // longest decay in the file, because a tubular bell keeps its edge for
        // a while.  The tail is in SPACE, not in the release.
        add (out, Build ("Campana de Torre", "BELLS", "DARK",
                         "pm,tubular,long tail,dark",
                         "Phase modulation at a sharp fourth into the MASS ladder, with mod envelope 2 carrying the index from 0.80 at the strike down to a 0.22 floor over 1.6 seconds and the whole tail living in an INFINITE reverb rather than in the amp release.")
            .at (60, 1, 0.85f, 4.0)
            .chain ("RETRO,FILTER,SPACE,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::masterGain, -2.0f)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.36f)
            .v (PID::driftAmount, 0.18f).v (PID::driftRate, 0.06f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.86f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.0f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBSemi, 5.0f)
            .v (PID::oscBFine, 14.0f)
            .v (PID::oscPmAmount, 0.22f).v (PID::pmEnvAmount, 0.58f)
            .v (PID::oscCWave, ch::sine).v (PID::oscCLevel, 0.14f)
            .v (PID::oscCOctave, 2.0f).v (PID::oscCSemi, 10.0f)
            .v (PID::oscCFine, -22.0f).v (PID::oscCPan, 0.30f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.18f)
            .v (PID::subHarmonics, 0.20f)
            .v (PID::bodyAmount, 0.42f).v (PID::bodyTilt, -0.30f)
            .v (PID::densityAmount, 0.22f)
            .v (PID::preFilterDrive, 0.12f).v (PID::postSaturation, 0.14f)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 3200.0f).v (PID::filterResonance, 0.18f)
            .v (PID::filterDrive, 0.24f).v (PID::filterKeyTrack, 0.85f)
            .v (PID::filterEnvAmount, 0.34f).v (PID::filterVelAmount, 0.45f)
            .v (PID::ampAttack, 0.002f).v (PID::ampDecay, 7.5f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 2.4f)
            .v (PID::ampVelocity, 0.60f)
            .v (PID::env1Attack, 0.001f).v (PID::env1Decay, 1.8f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.9f)
            .v (PID::env2Attack, 0.0012f).v (PID::env2Decay, 1.60f)
            .v (PID::env2Sustain, 0.0f)
            .v (PID::macroMemory, 0.26f).v (PID::memoryBandwidth, 0.46f)
            .v (PID::memoryWobble, 0.24f).v (PID::memoryDiffusion, 0.40f)
            .v (PID::macroMotion, 0.30f).v (PID::macroWorld, 0.82f)
            .v (PID::macroWeight, 0.40f).v (PID::weightMode, ch::wBody)
            .v (PID::weightHarmonics, 0.38f)
            .v (PID::retroEra, 0.30f).v (PID::retroAge, 0.26f)
            .v (PID::retroDrift, 0.20f).v (PID::retroWear, 0.10f)
            .v (PID::retroTone, -0.24f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.45f)
            .v (PID::fxFilterCutoff, 7200.0f).v (PID::fxFilterRes, 0.10f)
            .v (PID::spaceCharacter, ch::sInfinite).v (PID::spaceDistance, 0.62f)
            .v (PID::spaceSize, 0.88f).v (PID::spaceDecay, 18.0f)
            .v (PID::spaceFog, 0.62f).v (PID::spaceLight, -0.30f)
            .v (PID::spacePreDelay, 40.0f).v (PID::spaceMix, 0.48f)
            .v (PID::auraSize, 0.78f).v (PID::auraDistance, 0.46f)
            .v (PID::auraFog, 0.48f).v (PID::auraDecay, 0.72f)
            .v (PID::auraLight, -0.22f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.16f)
            .v (PID::patinaNoise, 0.12f).v (PID::patinaWear, 0.24f)
            .v (PID::patinaDrift, 0.22f)
            .v (PID::synthWidth, 1.10f).v (PID::highWidth, 1.22f)
            .v (PID::lowMonoFreq, 150.0f)
            .v (PID::breathAmount, 0.38f).v (PID::breathSpeed, 0.08f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.09f)
            .v (PID::lfo1Depth, 0.50f)
            .route (srcLfo1, PID::oscPmAmount, 0.10f)
            .route (srcBreath, PID::filterCutoff, 0.10f)
            .route (srcWheel, PID::oscPmAmount, 0.28f));

        // Method two: a dark noise burst struck into the COMB model, which is
        // key-tracked so the body is tuned to the note.  No PM anywhere.
        add (out, Build ("Iron Temple", "BELLS", "COLD",
                         "comb,struck,noise burst,temple",
                         "A DARK noise burst struck into the COMB filter at full key tracking, with an LP creative filter behind it and a six-second amp release doing the ringing.")
            .at (62, 1, 0.90f, 4.0)
            .chain ("CRUSH,FILTER,RETRO,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::masterGain, -3.0f)
            .v (PID::polyphony, 6.0f).v (PID::driftAmount, 0.16f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.30f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBLevel, 0.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.22f)
            .v (PID::subHarmonics, 0.24f)
            .v (PID::noiseType, ch::nDark).v (PID::noiseLevel, 0.72f)
            .v (PID::noiseAttackOnly, 0.94f)
            .v (PID::bodyAmount, 0.50f).v (PID::bodyTilt, -0.20f)
            .v (PID::densityAmount, 0.30f).v (PID::preFilterDrive, 0.20f)
            .v (PID::postSaturation, 0.16f).v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 262.0f).v (PID::filterResonance, 0.86f)
            .v (PID::filterDrive, 0.22f).v (PID::filterKeyTrack, 1.0f)
            .v (PID::filterEnvAmount, 0.15f).v (PID::filterVelAmount, 0.30f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Lp)
            .v (PID::filter2Cutoff, 3600.0f).v (PID::filter2Res, 0.18f)
            .v (PID::filter2Mix, 0.60f)
            .v (PID::ampAttack, 0.0008f).v (PID::ampDecay, 5.0f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 6.5f)
            .v (PID::env1Decay, 0.90f).v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.18f).v (PID::memoryBandwidth, 0.44f)
            .v (PID::macroCharacter, 0.34f).v (PID::macroMotion, 0.22f)
            .v (PID::macroWorld, 0.70f).v (PID::macroWeight, 0.44f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.42f)
            .v (PID::weightCompress, 0.32f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.16f)
            .v (PID::crushBits, 14.0f).v (PID::crushRate, 18000.0f)
            .v (PID::crushDrive, 0.14f).v (PID::crushTone, -0.20f)
            .v (PID::crushMix, 0.26f)
            .v (PID::retroEra, 0.22f).v (PID::retroAge, 0.20f)
            .v (PID::retroDrift, 0.14f).v (PID::retroWear, 0.08f)
            .v (PID::retroTone, -0.30f).v (PID::retroNoise, 0.08f)
            .v (PID::retroMix, 0.38f)
            .v (PID::fxFilterCutoff, 6000.0f).v (PID::fxFilterRes, 0.14f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.55f)
            .v (PID::spaceSize, 0.74f).v (PID::spaceDecay, 9.0f)
            .v (PID::spaceFog, 0.58f).v (PID::spaceLight, -0.44f)
            .v (PID::spacePreDelay, 28.0f).v (PID::spaceMix, 0.40f)
            .v (PID::auraSize, 0.66f).v (PID::auraDistance, 0.42f)
            .v (PID::auraFog, 0.52f).v (PID::auraDecay, 0.60f)
            .v (PID::auraLight, -0.30f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.26f)
            .v (PID::patinaNoise, 0.14f).v (PID::patinaWear, 0.34f)
            .v (PID::patinaDrift, 0.18f)
            .v (PID::synthWidth, 1.05f).v (PID::lowMonoFreq, 170.0f)
            .v (PID::breathAmount, 0.26f).v (PID::breathSpeed, 0.10f)
            .route (srcBreath, PID::filterResonance, 0.08f)
            .route (srcWheel, PID::filter2Cutoff, 0.30f)
            .route (srcTouch, PID::spaceMix, 0.22f));

        // GRAIN sits before SPACE, so the room is built out of the grains
        // rather than the strike.  The ratio is a sharp minor third, two up,
        // and mod envelope 2 pulls the index back inside a second, so most of
        // what the granulator is given is already the plainer tone.
        add (out, Build ("Procesion", "BELLS", "CINEMATIC",
                         "pm,ceremonial,granular,slow",
                         "An inharmonic PM bell whose index falls from 0.76 to 0.16 in under a second on mod envelope 2, granulated first and reverberated after, for a ceremonial line that arrives already diffused.")
            .at (65, 2, 0.80f, 4.0)
            .chain ("RETRO,FILTER,GRAIN,SPACE,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::masterGain, -2.0f)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.42f)
            .v (PID::driftAmount, 0.22f).v (PID::driftRate, 0.07f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.80f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.0f)
            .v (PID::oscBOctave, 2.0f).v (PID::oscBSemi, 3.0f)
            .v (PID::oscBFine, 41.0f)
            .v (PID::oscPmAmount, 0.16f).v (PID::pmEnvAmount, 0.60f)
            .v (PID::oscCWave, ch::tri).v (PID::oscCLevel, 0.10f)
            .v (PID::oscCOctave, 1.0f).v (PID::oscCSemi, 7.0f)
            .v (PID::oscCPan, -0.28f)
            .v (PID::subLevel, 0.08f)
            .v (PID::noiseType, ch::nTexture).v (PID::noiseLevel, 0.10f)
            .v (PID::noiseAttackOnly, 0.70f)
            .v (PID::bodyAmount, 0.26f).v (PID::densityAmount, 0.20f)
            .v (PID::postSaturation, 0.10f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 4400.0f).v (PID::filterResonance, 0.20f)
            .v (PID::filterKeyTrack, 0.80f).v (PID::filterEnvAmount, 0.30f)
            .v (PID::filterVelAmount, 0.45f)
            .v (PID::ampAttack, 0.003f).v (PID::ampDecay, 3.4f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 1.6f)
            .v (PID::env1Attack, 0.001f).v (PID::env1Decay, 1.1f)
            .v (PID::env1Sustain, 0.0f)
            .v (PID::env2Attack, 0.001f).v (PID::env2Decay, 0.90f)
            .v (PID::env2Sustain, 0.0f)
            .v (PID::macroMemory, 0.34f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.52f).v (PID::memoryWobble, 0.30f)
            .v (PID::memoryDiffusion, 0.48f)
            .v (PID::macroMotion, 0.48f).v (PID::macroWorld, 0.86f)
            .v (PID::macroWeight, 0.26f).v (PID::weightMode, ch::wAir)
            .v (PID::retroEra, 0.36f).v (PID::retroAge, 0.30f)
            .v (PID::retroDrift, 0.24f).v (PID::retroTone, -0.20f)
            .v (PID::retroNoise, 0.12f).v (PID::retroMix, 0.52f)
            .v (PID::fxFilterCutoff, 8200.0f).v (PID::fxFilterMotion, 0.16f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.46f)
            .v (PID::grainSize, 150.0f).v (PID::grainDensity, 9.0f)
            .v (PID::grainPosition, 0.40f).v (PID::grainPitchMode, ch::gFifth)
            .v (PID::grainSpread, 0.68f).v (PID::grainJitter, 0.40f)
            .v (PID::grainDirection, 0.22f).v (PID::grainWindow, ch::wGauss)
            .v (PID::grainFeedback, 0.24f).v (PID::grainMix, 0.42f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.68f)
            .v (PID::spaceSize, 0.84f).v (PID::spaceDecay, 12.0f)
            .v (PID::spaceFog, 0.64f).v (PID::spaceLight, -0.18f)
            .v (PID::spacePreDelay, 55.0f).v (PID::spaceMix, 0.14f)
            .v (PID::auraSize, 0.92f).v (PID::auraDistance, 0.62f)
            .v (PID::auraFog, 0.54f).v (PID::auraDecay, 0.86f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.12f)
            .v (PID::patinaNoise, 0.16f).v (PID::patinaWear, 0.28f)
            .v (PID::patinaDrift, 0.26f)
            .v (PID::synthWidth, 1.18f).v (PID::highWidth, 1.28f)
            .v (PID::breathAmount, 0.46f).v (PID::breathSpeed, 0.09f)
            .v (PID::breathShape, 0.40f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.12f)
            .v (PID::lfo2Depth, 0.55f)
            .route (srcLfo2, PID::grainPosition, 0.22f)
            .route (srcBreath, PID::oscPmAmount, 0.12f)
            .route (srcWorld, PID::spaceSize, 0.14f)
            .route (srcWheel, PID::grainMix, 0.25f));

        // Method three: FORMANT with key tracking almost off, so the
        // resonances stay where they are however high you play.
        add (out, Build ("Crystal Vespers", "BELLS", "AIRY",
                         "formant,spectral,glass,air",
                         "A SPECTRAL wavetable through the FORMANT filter at 0.05 key tracking, so the resonances sit at fixed frequencies, and the length comes from AURA rather than from the reverb.")
            .at (72, 1, 0.78f, 3.0)
            .chain ("FILTER,CRUSH,SPACE,RETRO,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::masterGain, 2.0f)
            .v (PID::polyphony, 12.0f).v (PID::voiceVariation, 0.22f)
            .v (PID::driftAmount, 0.10f).v (PID::driftRate, 0.20f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tSpectral)
            .v (PID::oscAWtPos, 0.34f).v (PID::oscALevel, 0.62f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tMetal)
            .v (PID::oscBWtPos, 0.20f).v (PID::oscBLevel, 0.24f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBSemi, 2.0f)
            .v (PID::oscBFine, -18.0f).v (PID::oscBPan, 0.22f)
            .v (PID::oscCWave, ch::sine).v (PID::oscCLevel, 0.10f)
            .v (PID::oscCOctave, 2.0f).v (PID::oscCPan, -0.20f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nAir).v (PID::noiseLevel, 0.14f)
            .v (PID::noiseAttackOnly, 0.80f)
            .v (PID::bodyAmount, 0.10f).v (PID::densityAmount, 0.12f)
            .v (PID::preFilterDrive, 0.06f).v (PID::postSaturation, 0.06f)
            .v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 2600.0f).v (PID::filterResonance, 0.30f)
            .v (PID::filterKeyTrack, 0.05f).v (PID::filterEnvAmount, 0.20f)
            .v (PID::filterVelAmount, 0.30f)
            .v (PID::ampAttack, 0.0006f).v (PID::ampDecay, 1.1f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.8f)
            .v (PID::ampVelocity, 0.70f)
            .v (PID::macroMemory, 0.08f).v (PID::memoryBandwidth, 0.12f)
            .v (PID::macroCharacter, 0.16f).v (PID::macroMotion, 0.28f)
            .v (PID::macroWorld, 0.60f).v (PID::macroWeight, 0.30f)
            .v (PID::weightMode, ch::wAir).v (PID::weightHarmonics, 0.48f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.12f)
            .v (PID::crushBits, 16.0f).v (PID::crushRate, 30000.0f)
            .v (PID::crushTone, 0.24f).v (PID::crushMix, 0.20f)
            .v (PID::retroEra, 0.88f).v (PID::retroAge, 0.06f)
            .v (PID::retroDrift, 0.05f).v (PID::retroWear, 0.03f)
            .v (PID::retroTone, 0.26f).v (PID::retroNoise, 0.03f)
            .v (PID::retroMix, 0.24f)
            .v (PID::fxFilterCutoff, 16000.0f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.30f)
            .v (PID::spaceSize, 0.50f).v (PID::spaceDecay, 2.6f)
            .v (PID::spaceFog, 0.28f).v (PID::spaceLight, 0.48f)
            .v (PID::spacePreDelay, 18.0f).v (PID::spaceMix, 0.22f)
            .v (PID::auraSize, 0.74f).v (PID::auraDistance, 0.30f)
            .v (PID::auraFog, 0.26f).v (PID::auraDecay, 0.86f)
            .v (PID::auraLight, 0.60f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.30f)
            .v (PID::patinaNoise, 0.06f).v (PID::patinaWear, 0.10f)
            .v (PID::patinaDrift, 0.10f)
            .v (PID::synthWidth, 1.05f).v (PID::highWidth, 1.35f)
            .v (PID::lowMonoFreq, 300.0f)
            .v (PID::breathAmount, 0.20f).v (PID::breathSpeed, 0.34f)
            .v (PID::lfo1Shape, ch::lfoTri).v (PID::lfo1Rate, 0.50f)
            .v (PID::lfo1Depth, 0.45f)
            .route (srcLfo1, PID::oscAWtPos, 0.20f)
            .route (srcBreath, PID::auraLight, 0.12f)
            .route (srcTouch, PID::oscBWtPos, 0.30f));

        // A glass bell: PM at seven and a half times the carrier, high-passed
        // hard so there is air and no body, and the grains taken from the room.
        // The deepest index envelope in the file and by far the shortest, at
        // 0.12 s: glass gives its edge up almost as soon as it is struck.
        add (out, Build ("Vitral", "BELLS", "COLD",
                         "pm,glass,bright,high",
                         "PM at a ratio just off a major seventh two octaves up with mod envelope 2 collapsing the index in 0.12 seconds, high-passed at 420 Hz with a band-pass creative filter on top, for the highest line in an arrangement.")
            .at (71, 1, 0.82f, 3.0)
            .chain ("FILTER,SPACE,GRAIN,RETRO,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::masterGain, 3.0f)
            .v (PID::polyphony, 10.0f).v (PID::voiceVariation, 0.26f)
            .v (PID::driftAmount, 0.12f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.70f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.0f)
            .v (PID::oscBOctave, 2.0f).v (PID::oscBSemi, 11.0f)
            .v (PID::oscBFine, -9.0f)
            .v (PID::oscPmAmount, 0.10f).v (PID::pmEnvAmount, 0.74f)
            .v (PID::oscCWave, ch::sine).v (PID::oscCLevel, 0.12f)
            .v (PID::oscCOctave, 3.0f).v (PID::oscCSemi, 4.0f)
            .v (PID::oscCFine, 12.0f).v (PID::oscCPan, 0.30f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nAir).v (PID::noiseLevel, 0.10f)
            .v (PID::noiseAttackOnly, 0.90f)
            .v (PID::bodyAmount, 0.08f).v (PID::densityAmount, 0.10f)
            .v (PID::postSaturation, 0.05f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::hp)
            .v (PID::filterCutoff, 420.0f).v (PID::filterResonance, 0.10f)
            .v (PID::filterKeyTrack, 0.25f).v (PID::filterEnvAmount, 0.0f)
            .v (PID::filterVelAmount, 0.18f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Bp)
            .v (PID::filter2Cutoff, 5200.0f).v (PID::filter2Res, 0.34f)
            .v (PID::filter2Mix, 0.40f)
            .v (PID::ampAttack, 0.0005f).v (PID::ampDecay, 1.6f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 1.0f)
            .v (PID::ampVelocity, 0.75f)
            .v (PID::env2Attack, 0.0006f).v (PID::env2Decay, 0.12f)
            .v (PID::env2Sustain, 0.0f)
            .v (PID::macroMemory, 0.06f).v (PID::memoryBandwidth, 0.10f)
            .v (PID::macroCharacter, 0.12f).v (PID::macroMotion, 0.20f)
            .v (PID::macroWorld, 0.62f).v (PID::macroWeight, 0.28f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::retroEra, 0.92f).v (PID::retroAge, 0.05f)
            .v (PID::retroDrift, 0.04f).v (PID::retroTone, 0.34f)
            .v (PID::retroNoise, 0.03f).v (PID::retroMix, 0.20f)
            .v (PID::fxFilterCutoff, 18000.0f).v (PID::fxFilterRes, 0.08f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.30f)
            .v (PID::grainSize, 40.0f).v (PID::grainDensity, 22.0f)
            .v (PID::grainPosition, 0.24f).v (PID::grainPitchMode, ch::gOctave)
            .v (PID::grainSpread, 0.80f).v (PID::grainJitter, 0.24f)
            .v (PID::grainDirection, 0.10f).v (PID::grainWindow, ch::wTukey)
            .v (PID::grainMix, 0.26f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.34f)
            .v (PID::spaceSize, 0.58f).v (PID::spaceDecay, 3.6f)
            .v (PID::spaceFog, 0.30f).v (PID::spaceLight, 0.56f)
            .v (PID::spacePreDelay, 24.0f).v (PID::spaceMix, 0.30f)
            .v (PID::auraSize, 0.60f).v (PID::auraDistance, 0.26f)
            .v (PID::auraFog, 0.24f).v (PID::auraDecay, 0.50f)
            .v (PID::auraLight, 0.52f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.36f)
            .v (PID::patinaNoise, 0.05f).v (PID::patinaWear, 0.08f)
            .v (PID::patinaDrift, 0.08f)
            .v (PID::synthWidth, 1.12f).v (PID::highWidth, 1.40f)
            .v (PID::lowMonoFreq, 320.0f)
            .v (PID::breathAmount, 0.18f).v (PID::breathSpeed, 0.28f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.70f)
            .v (PID::lfo1Depth, 0.35f)
            .route (srcLfo1, PID::oscCFine, 0.06f)
            .route (srcBreath, PID::oscPmAmount, 0.08f)
            .route (srcWheel, PID::filter2Cutoff, 0.35f));

        // COMB again, but excited by an AIR burst and left to the granulator:
        // what rings on here is the grain feedback, not the filter.
        add (out, Build ("Copa Vacia", "BELLS", "MINIMAL",
                         "comb,bowl,noise burst,granular",
                         "An AIR noise burst into a key-tracked COMB, with the grain feedback at 0.58 carrying the sound after the filter has stopped.")
            .at (67, 1, 0.70f, 3.5)
            .chain ("FILTER,GRAIN,SPACE,CRUSH,RETRO,REWIND")
            .v (PID::masterGain, 2.0f)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.34f)
            .v (PID::driftAmount, 0.14f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.18f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBLevel, 0.0f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nAir).v (PID::noiseLevel, 0.66f)
            .v (PID::noiseAttackOnly, 0.98f)
            .v (PID::bodyAmount, 0.16f).v (PID::densityAmount, 0.14f)
            .v (PID::preFilterDrive, 0.08f).v (PID::postSaturation, 0.06f)
            .v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 1480.0f).v (PID::filterResonance, 0.74f)
            .v (PID::filterDrive, 0.10f).v (PID::filterKeyTrack, 1.0f)
            .v (PID::filterEnvAmount, 0.22f).v (PID::filterVelAmount, 0.28f)
            .v (PID::ampAttack, 0.0008f).v (PID::ampDecay, 2.4f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 1.8f)
            .v (PID::env1Decay, 0.50f).v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.12f)
            .v (PID::macroCharacter, 0.18f).v (PID::macroMotion, 0.30f)
            .v (PID::macroWorld, 0.58f).v (PID::macroWeight, 0.22f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.52f)
            .v (PID::grainSize, 60.0f).v (PID::grainDensity, 18.0f)
            .v (PID::grainPosition, 0.22f).v (PID::grainSpread, 0.72f)
            .v (PID::grainJitter, 0.36f).v (PID::grainDirection, 0.18f)
            .v (PID::grainWindow, ch::wExpo).v (PID::grainFeedback, 0.58f)
            .v (PID::grainMix, 0.44f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.30f)
            .v (PID::spaceSize, 0.44f).v (PID::spaceDecay, 2.2f)
            .v (PID::spaceFog, 0.30f).v (PID::spaceLight, 0.20f)
            .v (PID::spacePreDelay, 14.0f).v (PID::spaceMix, 0.24f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.10f)
            .v (PID::crushBits, 15.0f).v (PID::crushRate, 26000.0f)
            .v (PID::crushMix, 0.18f)
            .v (PID::retroEra, 0.66f).v (PID::retroAge, 0.12f)
            .v (PID::retroDrift, 0.10f).v (PID::retroTone, 0.12f)
            .v (PID::retroNoise, 0.05f).v (PID::retroMix, 0.26f)
            .v (PID::fxFilterCutoff, 13000.0f)
            .v (PID::auraSize, 0.56f).v (PID::auraDistance, 0.30f)
            .v (PID::auraFog, 0.34f).v (PID::auraDecay, 0.48f)
            .v (PID::auraLight, 0.26f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, 0.10f)
            .v (PID::patinaNoise, 0.08f).v (PID::patinaWear, 0.14f)
            .v (PID::patinaDrift, 0.12f)
            .v (PID::synthWidth, 1.08f).v (PID::highWidth, 1.25f)
            .v (PID::lowMonoFreq, 240.0f)
            .v (PID::breathAmount, 0.30f).v (PID::breathSpeed, 0.18f)
            .route (srcBreath, PID::grainPosition, 0.18f)
            .route (srcOrganic, PID::filterCutoff, 0.10f)
            .route (srcWheel, PID::grainFeedback, 0.25f));

        // Small, mechanical and wound up: Generation III Memory and a worn
        // medium are the preset; the PM bell under them is tiny on purpose,
        // and so is its index envelope - 0.49 at the strike, gone in 0.2 s.
        add (out, Build ("Caja de Laton", "BELLS", "NOSTALGIC",
                         "music box,pm,retro,mechanical",
                         "A small PM bell at a detuned tenth carrying the shallowest index envelope in the file, run through a worn medium and Generation III Memory, for a wound mechanism rather than a struck bell.")
            .at (72, 1, 0.66f, 3.0)
            .chain ("RETRO,CRUSH,FILTER,SPACE,REWIND,GRAIN")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::masterGain, 4.0f)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.48f)
            .v (PID::driftAmount, 0.30f).v (PID::driftRate, 0.28f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.82f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.0f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBSemi, 4.0f)
            .v (PID::oscBFine, 26.0f)
            .v (PID::oscPmAmount, 0.09f).v (PID::pmEnvAmount, 0.40f)
            .v (PID::oscCWave, ch::tri).v (PID::oscCLevel, 0.08f)
            .v (PID::oscCOctave, 2.0f).v (PID::oscCSemi, 3.0f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.16f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.14f).v (PID::densityAmount, 0.12f)
            .v (PID::postSaturation, 0.10f)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 2100.0f).v (PID::filterResonance, 0.34f)
            .v (PID::filterDrive, 0.16f).v (PID::filterKeyTrack, 1.0f)
            .v (PID::filterEnvAmount, 0.20f).v (PID::filterVelAmount, 0.40f)
            .v (PID::ampAttack, 0.0006f).v (PID::ampDecay, 1.5f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.70f)
            .v (PID::ampVelocity, 0.62f)
            .v (PID::env1Decay, 0.25f).v (PID::env1Sustain, 0.0f)
            .v (PID::env2Attack, 0.0008f).v (PID::env2Decay, 0.20f)
            .v (PID::env2Sustain, 0.0f)
            .v (PID::macroMemory, 0.58f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.70f).v (PID::memoryWobble, 0.62f)
            .v (PID::memoryDiffusion, 0.40f).v (PID::memoryAsymmetry, 0.44f)
            .v (PID::macroCharacter, 0.44f).v (PID::macroMotion, 0.56f)
            .v (PID::macroWorld, 0.38f).v (PID::macroWeight, 0.18f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.24f)
            .v (PID::crushBits, 10.0f).v (PID::crushRate, 16000.0f)
            .v (PID::crushJitter, 0.26f).v (PID::crushTone, -0.10f)
            .v (PID::crushMix, 0.34f)
            .v (PID::retroEra, 0.26f).v (PID::retroAge, 0.54f)
            .v (PID::retroDrift, 0.52f).v (PID::retroWear, 0.38f)
            .v (PID::retroTone, -0.12f).v (PID::retroNoise, 0.20f)
            .v (PID::retroMix, 0.80f)
            .v (PID::fxFilterCutoff, 7000.0f).v (PID::fxFilterRes, 0.14f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.36f)
            .v (PID::spaceSize, 0.36f).v (PID::spaceDecay, 1.8f)
            .v (PID::spaceFog, 0.42f).v (PID::spaceLight, -0.10f)
            .v (PID::spacePreDelay, 10.0f).v (PID::spaceMix, 0.24f)
            .v (PID::auraSize, 0.40f).v (PID::auraDistance, 0.32f)
            .v (PID::auraFog, 0.46f).v (PID::auraDecay, 0.38f)
            .v (PID::auraLight, -0.10f)
            .v (PID::patinaTone, -0.16f).v (PID::patinaNoise, 0.24f)
            .v (PID::patinaWear, 0.44f).v (PID::patinaDrift, 0.36f)
            .v (PID::synthWidth, 0.95f).v (PID::lowMonoFreq, 220.0f)
            .v (PID::breathAmount, 0.50f).v (PID::breathSpeed, 0.34f)
            .v (PID::breathRandom, 0.66f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.42f)
            .v (PID::lfo2Depth, 0.60f)
            .route (srcLfo2, PID::oscAFine, 0.08f)
            .route (srcBreath, PID::memoryWobble, 0.20f)
            .route (srcMemory, PID::filterCutoff, -0.12f));

        // Celeste-adjacent: METALLIC wavetable, FORMANT bank nearly fixed, and
        // the length handed to Memory instead of to the release.
        add (out, Build ("Wound Celeste", "BELLS", "INTIMATE",
                         "celeste,formant,metallic,memory",
                         "A METALLIC wavetable ring-modulated with a detuned fifth through the FORMANT filter at 0.12 key tracking, with Generation II Memory doing the work the release usually does.")
            .at (69, 2, 0.60f, 3.0)
            .chain ("RETRO,FILTER,CRUSH,GRAIN,SPACE,REWIND")
            .v (PID::masterGain, 2.0f)
            .v (PID::polyphony, 10.0f).v (PID::voiceVariation, 0.36f)
            .v (PID::driftAmount, 0.26f).v (PID::driftRate, 0.18f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tMetal)
            .v (PID::oscAWtPos, 0.42f).v (PID::oscALevel, 0.68f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.20f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBSemi, 7.0f)
            .v (PID::oscBFine, -14.0f).v (PID::oscBPan, -0.18f)
            .v (PID::oscRingMod, 0.14f)
            .v (PID::subLevel, 0.06f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.12f)
            .v (PID::noiseAttackOnly, 0.92f)
            .v (PID::bodyAmount, 0.20f).v (PID::bodyTilt, 0.24f)
            .v (PID::densityAmount, 0.18f).v (PID::postSaturation, 0.10f)
            .v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 1800.0f).v (PID::filterResonance, 0.26f)
            .v (PID::filterKeyTrack, 0.12f).v (PID::filterEnvAmount, 0.28f)
            .v (PID::filterVelAmount, 0.42f)
            .v (PID::ampAttack, 0.0008f).v (PID::ampDecay, 2.0f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 1.1f)
            .v (PID::ampVelocity, 0.66f)
            .v (PID::macroMemory, 0.62f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.64f).v (PID::memoryWobble, 0.44f)
            .v (PID::memoryDiffusion, 0.56f).v (PID::memoryAsymmetry, 0.38f)
            .v (PID::macroCharacter, 0.36f).v (PID::macroMotion, 0.42f)
            .v (PID::macroWorld, 0.46f).v (PID::macroWeight, 0.24f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.14f)
            .v (PID::crushBits, 11.0f).v (PID::crushRate, 20000.0f)
            .v (PID::crushTone, -0.06f).v (PID::crushMix, 0.22f)
            .v (PID::retroEra, 0.38f).v (PID::retroAge, 0.40f)
            .v (PID::retroDrift, 0.34f).v (PID::retroWear, 0.22f)
            .v (PID::retroTone, -0.14f).v (PID::retroNoise, 0.16f)
            .v (PID::retroMix, 0.62f)
            .v (PID::fxFilterCutoff, 8600.0f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.26f)
            .v (PID::grainSize, 120.0f).v (PID::grainDensity, 7.0f)
            .v (PID::grainPosition, 0.34f).v (PID::grainPitchMode, ch::gOctave)
            .v (PID::grainSpread, 0.50f).v (PID::grainJitter, 0.22f)
            .v (PID::grainMix, 0.24f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.38f)
            .v (PID::spaceSize, 0.42f).v (PID::spaceDecay, 2.4f)
            .v (PID::spaceFog, 0.40f).v (PID::spaceLight, -0.04f)
            .v (PID::spacePreDelay, 16.0f).v (PID::spaceMix, 0.26f)
            .v (PID::auraSize, 0.48f).v (PID::auraDistance, 0.34f)
            .v (PID::auraFog, 0.42f).v (PID::auraDecay, 0.44f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.06f)
            .v (PID::patinaNoise, 0.18f).v (PID::patinaWear, 0.28f)
            .v (PID::patinaDrift, 0.24f)
            .v (PID::synthWidth, 1.02f).v (PID::lowMonoFreq, 200.0f)
            .v (PID::breathAmount, 0.42f).v (PID::breathSpeed, 0.20f)
            .route (srcMemory, PID::oscAWtPos, 0.18f)
            .route (srcBreath, PID::oscBFine, 0.08f)
            .route (srcWheel, PID::macroMemory, 0.30f));

        // A struck bowl: pink-noise excitation into a low COMB at partial key
        // tracking, with a FORMANT creative filter behind it and a 26-second
        // reverb doing the decay.
        add (out, Build ("Cuenco de Bronce", "BELLS", "MYSTERIOUS",
                         "comb,bowl,formant,long",
                         "A pink-noise strike into a COMB tuned below the note at 0.60 key tracking, with a FORMANT creative filter behind it and the decay held by a 26-second INFINITE reverb.")
            .at (60, 1, 0.88f, 4.0)
            .chain ("FILTER,SPACE,CRUSH,GRAIN,RETRO,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::masterGain, -3.0f)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.40f)
            .v (PID::driftAmount, 0.20f).v (PID::driftRate, 0.05f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.24f)
            .v (PID::oscAFine, -12.0f).v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.14f)
            .v (PID::oscBSemi, -5.0f).v (PID::oscBFine, 31.0f)
            .v (PID::oscRingMod, 0.22f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.24f)
            .v (PID::subHarmonics, 0.28f)
            .v (PID::noiseLevel, 0.60f).v (PID::noiseAttackOnly, 0.90f)
            .v (PID::bodyAmount, 0.54f).v (PID::bodyTilt, -0.34f)
            .v (PID::densityAmount, 0.32f).v (PID::preFilterDrive, 0.22f)
            .v (PID::postSaturation, 0.18f).v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 196.0f).v (PID::filterResonance, 0.80f)
            .v (PID::filterDrive, 0.26f).v (PID::filterKeyTrack, 0.60f)
            .v (PID::filterEnvAmount, 0.20f).v (PID::filterVelAmount, 0.30f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Formant)
            .v (PID::filter2Cutoff, 900.0f).v (PID::filter2Res, 0.36f)
            .v (PID::filter2Mix, 0.45f)
            .v (PID::ampAttack, 0.001f).v (PID::ampDecay, 8.0f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 5.0f)
            .v (PID::env1Decay, 1.2f).v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.24f).v (PID::memoryBandwidth, 0.48f)
            .v (PID::memoryDiffusion, 0.46f)
            .v (PID::macroCharacter, 0.40f).v (PID::macroMotion, 0.34f)
            .v (PID::macroWorld, 0.90f).v (PID::macroWeight, 0.48f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.44f)
            .v (PID::weightCompress, 0.34f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.12f)
            .v (PID::crushBits, 13.0f).v (PID::crushRate, 15000.0f)
            .v (PID::crushTone, -0.22f).v (PID::crushMix, 0.22f)
            .v (PID::retroEra, 0.20f).v (PID::retroAge, 0.28f)
            .v (PID::retroDrift, 0.18f).v (PID::retroTone, -0.34f)
            .v (PID::retroNoise, 0.12f).v (PID::retroMix, 0.44f)
            .v (PID::fxFilterCutoff, 5200.0f).v (PID::fxFilterRes, 0.16f)
            .v (PID::fxFilterMotion, 0.14f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.24f)
            .v (PID::grainSize, 260.0f).v (PID::grainDensity, 5.0f)
            .v (PID::grainPosition, 0.48f).v (PID::grainPitchMode, ch::gFifth)
            .v (PID::grainSpread, 0.60f).v (PID::grainJitter, 0.34f)
            .v (PID::grainDirection, 0.28f).v (PID::grainWindow, ch::wGauss)
            .v (PID::grainMix, 0.22f)
            .v (PID::spaceCharacter, ch::sInfinite).v (PID::spaceDistance, 0.72f)
            .v (PID::spaceSize, 0.94f).v (PID::spaceDecay, 26.0f)
            .v (PID::spaceFog, 0.70f).v (PID::spaceLight, -0.36f)
            .v (PID::spacePreDelay, 60.0f).v (PID::spaceMix, 0.50f)
            .v (PID::shadowOn, 1.0f).v (PID::shadowLength, 0.52f)
            .v (PID::shadowDistance, 0.68f).v (PID::shadowBlur, 0.58f)
            .v (PID::shadowPitch, -7.0f).v (PID::shadowLevel, 0.26f)
            .v (PID::auraSize, 0.84f).v (PID::auraDistance, 0.54f)
            .v (PID::auraFog, 0.60f).v (PID::auraDecay, 0.80f)
            .v (PID::auraLight, -0.28f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.24f)
            .v (PID::patinaNoise, 0.16f).v (PID::patinaWear, 0.32f)
            .v (PID::patinaDrift, 0.26f)
            .v (PID::synthWidth, 1.10f).v (PID::lowMonoFreq, 150.0f)
            .v (PID::breathAmount, 0.40f).v (PID::breathSpeed, 0.05f)
            .route (srcBreath, PID::filterCutoff, 0.08f)
            .route (srcWorld, PID::spaceSize, 0.16f)
            .route (srcOrganic, PID::shadowPitch, 0.05f)
            .route (srcTouch, PID::filterResonance, 0.12f));

        // Struck metal with the COMB in the creative slot instead of the
        // primary one, and the grains crushed before they reach the filter.
        add (out, Build ("Ritual Gong", "BELLS", "AGGRESSIVE",
                         "gong,noise,comb,metal",
                         "A white-noise strike and a ring-modulated pair through MASS with a COMB creative filter, granulated and crushed ahead of the filter rather than after it.")
            .at (60, 1, 0.95f, 4.0)
            .chain ("CRUSH,GRAIN,FILTER,SPACE,RETRO,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::masterGain, -5.0f)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.44f)
            .v (PID::driftAmount, 0.24f).v (PID::driftRate, 0.06f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.40f)
            .v (PID::oscAFine, 9.0f).v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::square).v (PID::oscBLevel, 0.18f)
            .v (PID::oscBSemi, -6.0f).v (PID::oscBFine, -23.0f)
            .v (PID::oscBPan, 0.20f)
            .v (PID::oscRingMod, 0.46f)
            .v (PID::subWave, ch::subTri).v (PID::subLevel, 0.20f)
            .v (PID::subHarmonics, 0.30f)
            .v (PID::noiseType, ch::nWhite).v (PID::noiseLevel, 0.55f)
            .v (PID::noiseAttackOnly, 0.86f)
            .v (PID::bodyAmount, 0.56f).v (PID::bodyTilt, 0.28f)
            .v (PID::densityAmount, 0.36f).v (PID::preFilterDrive, 0.30f)
            .v (PID::postSaturation, 0.24f).v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 2400.0f).v (PID::filterResonance, 0.30f)
            .v (PID::filterDrive, 0.36f).v (PID::filterKeyTrack, 0.40f)
            .v (PID::filterEnvAmount, 0.52f).v (PID::filterVelAmount, 0.46f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Comb)
            .v (PID::filter2Cutoff, 330.0f).v (PID::filter2Res, 0.62f)
            .v (PID::ampAttack, 0.0012f).v (PID::ampDecay, 6.5f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 4.0f)
            .v (PID::ampVelocity, 0.50f)
            .v (PID::env1Attack, 0.0008f).v (PID::env1Decay, 1.6f)
            .v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.28f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.56f).v (PID::memoryWobble, 0.32f)
            .v (PID::memoryDiffusion, 0.42f)
            .v (PID::macroCharacter, 0.54f).v (PID::macroMotion, 0.40f)
            .v (PID::macroWorld, 0.80f).v (PID::macroWeight, 0.50f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.46f)
            .v (PID::weightCompress, 0.38f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.34f)
            .v (PID::crushBits, 9.0f).v (PID::crushRate, 13000.0f)
            .v (PID::crushJitter, 0.20f).v (PID::crushDrive, 0.28f)
            .v (PID::crushTone, -0.12f).v (PID::crushMix, 0.40f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.44f)
            .v (PID::grainSize, 190.0f).v (PID::grainDensity, 11.0f)
            .v (PID::grainPosition, 0.36f).v (PID::grainPitchMode, ch::gThird)
            .v (PID::grainSpread, 0.62f).v (PID::grainJitter, 0.42f)
            .v (PID::grainDirection, 0.30f).v (PID::grainWindow, ch::wPercussive)
            .v (PID::grainFeedback, 0.42f).v (PID::grainMix, 0.38f)
            .v (PID::retroEra, 0.28f).v (PID::retroAge, 0.34f)
            .v (PID::retroDrift, 0.22f).v (PID::retroWear, 0.20f)
            .v (PID::retroTone, -0.26f).v (PID::retroNoise, 0.14f)
            .v (PID::retroMix, 0.50f)
            .v (PID::fxFilterCutoff, 6400.0f).v (PID::fxFilterRes, 0.18f)
            .v (PID::fxFilterMotion, 0.22f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.60f)
            .v (PID::spaceSize, 0.86f).v (PID::spaceDecay, 14.0f)
            .v (PID::spaceFog, 0.68f).v (PID::spaceLight, -0.34f)
            .v (PID::spacePreDelay, 45.0f).v (PID::spaceMix, 0.44f)
            .v (PID::auraSize, 0.82f).v (PID::auraDistance, 0.50f)
            .v (PID::auraFog, 0.58f).v (PID::auraDecay, 0.76f)
            .v (PID::auraLight, -0.24f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.20f)
            .v (PID::patinaNoise, 0.18f).v (PID::patinaWear, 0.38f)
            .v (PID::patinaDrift, 0.30f)
            .v (PID::synthWidth, 1.14f).v (PID::lowMonoFreq, 160.0f)
            .v (PID::breathAmount, 0.48f).v (PID::breathSpeed, 0.07f)
            .v (PID::lfo1Shape, ch::lfoRandom).v (PID::lfo1Rate, 0.20f)
            .v (PID::lfo1Depth, 0.50f)
            .route (srcLfo1, PID::filter2Cutoff, 0.14f)
            .route (srcBreath, PID::oscRingMod, 0.10f)
            .route (srcWorld, PID::grainScatter, 0.18f)
            .route (srcTouch, PID::preFilterDrive, 0.25f));

        // GRAIN runs first, so the filter and the room are working on grains
        // from the start.  The tail is SHADOW, a nineteenth below and blurred.
        add (out, Build ("Scrap Tower", "BELLS", "DIRTY",
                         "formant,metal,shadow,struck",
                         "METALLIC against ASYMMETRIC wavetables, ring-modulated into a FORMANT bank that ignores the keyboard, with the tail carried by a blurred SHADOW a twelfth below.")
            .at (64, 1, 0.90f, 3.5)
            .chain ("GRAIN,FILTER,RETRO,SPACE,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::masterGain, -2.0f)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.46f)
            .v (PID::driftAmount, 0.28f).v (PID::driftRate, 0.22f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tMetal)
            .v (PID::oscAWtPos, 0.66f).v (PID::oscALevel, 0.74f)
            .v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tAsym)
            .v (PID::oscBWtPos, 0.38f).v (PID::oscBLevel, 0.30f)
            .v (PID::oscBSemi, -3.0f).v (PID::oscBFine, 37.0f)
            .v (PID::oscBPan, -0.24f)
            .v (PID::oscRingMod, 0.34f)
            .v (PID::subLevel, 0.08f)
            .v (PID::noiseType, ch::nDigital).v (PID::noiseLevel, 0.22f)
            .v (PID::noiseAttackOnly, 0.88f)
            .v (PID::bodyAmount, 0.34f).v (PID::bodyTilt, 0.40f)
            .v (PID::densityAmount, 0.26f).v (PID::preFilterDrive, 0.28f)
            .v (PID::postSaturation, 0.22f).v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 1400.0f).v (PID::filterResonance, 0.40f)
            .v (PID::filterDrive, 0.24f).v (PID::filterKeyTrack, 0.08f)
            .v (PID::filterEnvAmount, 0.34f).v (PID::filterVelAmount, 0.44f)
            .v (PID::ampAttack, 0.0007f).v (PID::ampDecay, 2.8f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 1.2f)
            .v (PID::ampVelocity, 0.68f)
            .v (PID::env1Decay, 0.60f).v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.30f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.60f).v (PID::memoryWobble, 0.40f)
            .v (PID::memoryAsymmetry, 0.48f)
            .v (PID::macroCharacter, 0.58f).v (PID::macroMotion, 0.46f)
            .v (PID::macroWorld, 0.52f).v (PID::macroWeight, 0.30f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.36f)
            .v (PID::grainSize, 25.0f).v (PID::grainDensity, 30.0f)
            .v (PID::grainPosition, 0.18f).v (PID::grainPitchMode, ch::gChromatic)
            .v (PID::grainSpread, 0.66f).v (PID::grainJitter, 0.46f)
            .v (PID::grainDirection, 0.24f).v (PID::grainWindow, ch::wPercussive)
            .v (PID::grainMix, 0.30f)
            .v (PID::retroEra, 0.44f).v (PID::retroAge, 0.36f)
            .v (PID::retroDrift, 0.26f).v (PID::retroWear, 0.30f)
            .v (PID::retroTone, -0.08f).v (PID::retroNoise, 0.18f)
            .v (PID::retroMix, 0.56f)
            .v (PID::fxFilterCutoff, 9800.0f).v (PID::fxFilterRes, 0.20f)
            .v (PID::fxFilterMotion, 0.26f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.26f)
            .v (PID::crushBits, 8.0f).v (PID::crushRate, 11000.0f)
            .v (PID::crushJitter, 0.30f).v (PID::crushTone, 0.06f)
            .v (PID::crushMix, 0.30f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.42f)
            .v (PID::spaceSize, 0.50f).v (PID::spaceDecay, 2.8f)
            .v (PID::spaceFog, 0.38f).v (PID::spaceLight, 0.10f)
            .v (PID::spacePreDelay, 20.0f).v (PID::spaceMix, 0.26f)
            .v (PID::shadowOn, 1.0f).v (PID::shadowLength, 0.66f)
            .v (PID::shadowDistance, 0.62f).v (PID::shadowBlur, 0.72f)
            .v (PID::shadowPitch, -19.0f).v (PID::shadowLevel, 0.44f)
            .v (PID::auraSize, 0.54f).v (PID::auraDistance, 0.36f)
            .v (PID::auraFog, 0.40f).v (PID::auraDecay, 0.42f)
            .v (PID::patinaProfile, ch::pCustom).v (PID::patinaTone, 0.14f)
            .v (PID::patinaNoise, 0.22f).v (PID::patinaWear, 0.46f)
            .v (PID::patinaDrift, 0.34f)
            .v (PID::synthWidth, 1.16f).v (PID::highWidth, 1.30f)
            .v (PID::lowMonoFreq, 190.0f)
            .v (PID::breathAmount, 0.52f).v (PID::breathSpeed, 0.30f)
            .v (PID::breathRandom, 0.70f)
            .route (srcOrganic, PID::oscAWtPos, 0.24f)
            .route (srcBreath, PID::shadowPitch, 0.06f)
            .route (srcWheel, PID::oscRingMod, 0.30f)
            .route (srcTouch, PID::shadowLevel, 0.20f));

        // Urbano: small PM bell, REWIND set to an eighth IN FRONT of the
        // reverb, so the repeat happens before the room rather than inside it.
        // The index envelope is a third of a second, short enough that only
        // the strike itself reaches REWIND with the full index in it.
        add (out, Build ("Campanita de Marzo", "BELLS", "ROMANTIC",
                         "urbano,pm,repeat,top line",
                         "A small PM bell with a stacked fifth on the aux oscillator, a third-of-a-second index envelope on mod envelope 2 and REWIND at an eighth ahead of the reverb, built to carry a minor top line over an empty mix.")
            .at (67, 1, 0.80f, 3.5)
            .chain ("FILTER,REWIND,SPACE,RETRO,GRAIN,CRUSH")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::masterGain, 1.0f)
            .v (PID::polyphony, 8.0f).v (PID::driftAmount, 0.18f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.84f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.0f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBSemi, 3.0f)
            .v (PID::oscBFine, 19.0f)
            .v (PID::oscPmAmount, 0.15f).v (PID::pmEnvAmount, 0.50f)
            .v (PID::oscCWave, ch::sine).v (PID::oscCLevel, 0.14f)
            .v (PID::oscCOctave, 1.0f).v (PID::oscCSemi, 7.0f)
            .v (PID::oscCPan, 0.26f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.12f)
            .v (PID::subHarmonics, 0.18f)
            .v (PID::bodyAmount, 0.22f).v (PID::densityAmount, 0.20f)
            .v (PID::postSaturation, 0.10f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 5600.0f).v (PID::filterResonance, 0.16f)
            .v (PID::filterDrive, 0.14f).v (PID::filterKeyTrack, 0.90f)
            .v (PID::filterEnvAmount, 0.28f).v (PID::filterVelAmount, 0.48f)
            .v (PID::ampAttack, 0.0008f).v (PID::ampDecay, 1.8f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.90f)
            .v (PID::ampVelocity, 0.64f)
            .v (PID::env1Attack, 0.001f).v (PID::env1Decay, 0.55f)
            .v (PID::env1Sustain, 0.0f)
            .v (PID::env2Attack, 0.0008f).v (PID::env2Decay, 0.32f)
            .v (PID::env2Sustain, 0.0f)
            .v (PID::macroMemory, 0.20f).v (PID::memoryBandwidth, 0.34f)
            .v (PID::memoryWobble, 0.22f)
            .v (PID::macroCharacter, 0.24f).v (PID::macroMotion, 0.34f)
            .v (PID::macroWorld, 0.66f).v (PID::macroWeight, 0.26f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::rewindOn, 1.0f).v (PID::rewindMode, ch::rReturn)
            .v (PID::rewindDivision, ch::rw8).v (PID::rewindCurve, 0.44f)
            .v (PID::rewindTail, 0.52f).v (PID::rewindMix, 0.34f)
            .v (PID::retroEra, 0.52f).v (PID::retroAge, 0.18f)
            .v (PID::retroDrift, 0.16f).v (PID::retroWear, 0.08f)
            .v (PID::retroTone, -0.06f).v (PID::retroNoise, 0.08f)
            .v (PID::retroMix, 0.34f)
            .v (PID::fxFilterCutoff, 11000.0f).v (PID::fxFilterRes, 0.10f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.46f)
            .v (PID::spaceSize, 0.66f).v (PID::spaceDecay, 5.0f)
            .v (PID::spaceFog, 0.44f).v (PID::spaceLight, 0.10f)
            .v (PID::spacePreDelay, 34.0f).v (PID::spaceMix, 0.36f)
            .v (PID::auraSize, 0.64f).v (PID::auraDistance, 0.38f)
            .v (PID::auraFog, 0.36f).v (PID::auraDecay, 0.58f)
            .v (PID::auraLight, 0.12f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, 0.04f)
            .v (PID::patinaNoise, 0.10f).v (PID::patinaWear, 0.16f)
            .v (PID::patinaDrift, 0.16f)
            .v (PID::synthWidth, 1.10f).v (PID::highWidth, 1.28f)
            .v (PID::lowMonoFreq, 180.0f)
            .v (PID::breathAmount, 0.32f).v (PID::breathSpeed, 0.16f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.24f)
            .v (PID::lfo1Depth, 0.40f)
            .route (srcLfo1, PID::oscPmAmount, 0.10f)
            .route (srcBreath, PID::spaceMix, 0.10f)
            .route (srcWheel, PID::rewindMix, 0.28f)
            .route (srcTouch, PID::oscPmAmount, 0.20f));

        // The same urbano idea with the order reversed: SPACE first and REWIND
        // after it, so the repeats carry the tail with them.  The index
        // envelope is six-tenths of a second, nearly twice its sibling's.
        add (out, Build ("Luna de Nacar", "BELLS", "DREAMY",
                         "urbano,pm,wet,repeat",
                         "PM at pi times the carrier over a fifth-stacked aux oscillator, its index falling over six-tenths of a second on mod envelope 2, reverberated first and rewound after, so each repeat brings its own room with it.")
            .at (70, 3, 0.75f, 4.0)
            .chain ("FILTER,SPACE,REWIND,RETRO,CRUSH,GRAIN")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::masterGain, 1.0f)
            .v (PID::polyphony, 10.0f).v (PID::voiceVariation, 0.34f)
            .v (PID::driftAmount, 0.22f).v (PID::driftRate, 0.14f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.78f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.10f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBSemi, 8.0f)
            .v (PID::oscBFine, -21.0f)
            .v (PID::oscPmAmount, 0.18f).v (PID::pmEnvAmount, 0.56f)
            .v (PID::oscCWave, ch::sine).v (PID::oscCLevel, 0.16f)
            .v (PID::oscCOctave, 2.0f).v (PID::oscCSemi, 7.0f)
            .v (PID::oscCFine, 6.0f).v (PID::oscCPan, -0.30f)
            .v (PID::subLevel, 0.10f)
            .v (PID::noiseType, ch::nAir).v (PID::noiseLevel, 0.08f)
            .v (PID::noiseAttackOnly, 0.90f)
            .v (PID::bodyAmount, 0.18f).v (PID::densityAmount, 0.22f)
            .v (PID::postSaturation, 0.08f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 6200.0f).v (PID::filterResonance, 0.18f)
            .v (PID::filterKeyTrack, 0.85f).v (PID::filterEnvAmount, 0.30f)
            .v (PID::filterVelAmount, 0.40f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Bp)
            .v (PID::filter2Cutoff, 3200.0f).v (PID::filter2Res, 0.28f)
            .v (PID::filter2Mix, 0.32f)
            .v (PID::ampAttack, 0.001f).v (PID::ampDecay, 2.6f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 1.4f)
            .v (PID::ampVelocity, 0.60f)
            .v (PID::env1Attack, 0.001f).v (PID::env1Decay, 0.80f)
            .v (PID::env1Sustain, 0.0f)
            .v (PID::env2Attack, 0.001f).v (PID::env2Decay, 0.60f)
            .v (PID::env2Sustain, 0.0f)
            .v (PID::macroMemory, 0.26f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.44f).v (PID::memoryWobble, 0.30f)
            .v (PID::memoryDiffusion, 0.46f)
            .v (PID::macroCharacter, 0.26f).v (PID::macroMotion, 0.42f)
            .v (PID::macroWorld, 0.76f).v (PID::macroWeight, 0.24f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::retroEra, 0.56f).v (PID::retroAge, 0.22f)
            .v (PID::retroDrift, 0.22f).v (PID::retroWear, 0.10f)
            .v (PID::retroTone, -0.04f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.40f)
            .v (PID::fxFilterCutoff, 12500.0f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.64f)
            .v (PID::spaceSize, 0.80f).v (PID::spaceDecay, 7.5f)
            .v (PID::spaceFog, 0.56f).v (PID::spaceLight, 0.04f)
            .v (PID::spacePreDelay, 95.0f).v (PID::spaceMix, 0.32f)
            .v (PID::rewindOn, 1.0f).v (PID::rewindMode, ch::rReverse)
            .v (PID::rewindDivision, ch::rw4).v (PID::rewindCurve, 0.60f)
            .v (PID::rewindSpeed, 0.80f).v (PID::rewindTail, 0.46f)
            .v (PID::rewindMix, 0.30f)
            .v (PID::auraSize, 0.84f).v (PID::auraDistance, 0.56f)
            .v (PID::auraFog, 0.44f).v (PID::auraDecay, 0.78f)
            .v (PID::auraLight, 0.08f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.04f)
            .v (PID::patinaNoise, 0.12f).v (PID::patinaWear, 0.20f)
            .v (PID::patinaDrift, 0.22f)
            .v (PID::synthWidth, 1.18f).v (PID::highWidth, 1.32f)
            .v (PID::lowMonoFreq, 170.0f)
            .v (PID::breathAmount, 0.44f).v (PID::breathSpeed, 0.13f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.18f)
            .v (PID::lfo2Depth, 0.50f)
            .route (srcLfo2, PID::filter2Cutoff, 0.18f)
            .route (srcBreath, PID::oscPmAmount, 0.10f)
            .route (srcWheel, PID::spaceMix, 0.24f)
            .route (srcWorld, PID::auraSize, 0.12f));

        // Urbano built the third way: a SPECTRAL wavetable behind a FORMANT
        // creative filter, tuned enough to play a melody.  AURA holds the end.
        add (out, Build ("Novena", "BELLS", "MYSTERIOUS",
                         "urbano,formant,spectral,repeat",
                         "A SPECTRAL wavetable with a light PM edge behind a FORMANT creative filter, with the repeat from REWIND and the length from AURA rather than the reverb.")
            .at (69, 2, 0.72f, 3.5)
            .chain ("RETRO,FILTER,REWIND,SPACE,GRAIN,CRUSH")
            .v (PID::masterGain, 1.0f)
            .v (PID::polyphony, 10.0f).v (PID::voiceVariation, 0.32f)
            .v (PID::driftAmount, 0.20f).v (PID::driftRate, 0.16f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tSpectral)
            .v (PID::oscAWtPos, 0.48f).v (PID::oscALevel, 0.70f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.18f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBSemi, 3.0f)
            .v (PID::oscBFine, 11.0f).v (PID::oscBPan, 0.20f)
            .v (PID::oscPmAmount, 0.14f)
            .v (PID::subLevel, 0.08f)
            .v (PID::noiseType, ch::nTexture).v (PID::noiseLevel, 0.10f)
            .v (PID::noiseAttackOnly, 0.80f)
            .v (PID::bodyAmount, 0.22f).v (PID::densityAmount, 0.20f)
            .v (PID::postSaturation, 0.09f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 7000.0f).v (PID::filterResonance, 0.20f)
            .v (PID::filterKeyTrack, 0.75f).v (PID::filterEnvAmount, 0.38f)
            .v (PID::filterVelAmount, 0.42f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Formant)
            .v (PID::filter2Cutoff, 1500.0f).v (PID::filter2Res, 0.34f)
            .v (PID::filter2Mix, 0.44f)
            .v (PID::ampAttack, 0.0009f).v (PID::ampDecay, 2.2f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 1.0f)
            .v (PID::ampVelocity, 0.62f)
            .v (PID::macroMemory, 0.24f).v (PID::memoryBandwidth, 0.40f)
            .v (PID::memoryWobble, 0.26f)
            .v (PID::macroCharacter, 0.28f).v (PID::macroMotion, 0.38f)
            .v (PID::macroWorld, 0.70f).v (PID::macroWeight, 0.26f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::retroEra, 0.60f).v (PID::retroAge, 0.20f)
            .v (PID::retroDrift, 0.18f).v (PID::retroTone, -0.06f)
            .v (PID::retroNoise, 0.09f).v (PID::retroMix, 0.36f)
            .v (PID::fxFilterCutoff, 11500.0f).v (PID::fxFilterMorph, 0.24f)
            .v (PID::rewindOn, 1.0f).v (PID::rewindMode, ch::rDive)
            .v (PID::rewindDivision, ch::rw8).v (PID::rewindCurve, 0.52f)
            .v (PID::rewindSpeed, 1.20f).v (PID::rewindTail, 0.50f)
            .v (PID::rewindMix, 0.32f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.50f)
            .v (PID::spaceSize, 0.68f).v (PID::spaceDecay, 5.6f)
            .v (PID::spaceFog, 0.46f).v (PID::spaceLight, 0.06f)
            .v (PID::spacePreDelay, 40.0f).v (PID::spaceMix, 0.34f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.22f)
            .v (PID::grainSize, 95.0f).v (PID::grainDensity, 12.0f)
            .v (PID::grainPosition, 0.28f).v (PID::grainPitchMode, ch::gScale)
            .v (PID::grainSpread, 0.58f).v (PID::grainJitter, 0.26f)
            .v (PID::grainWindow, ch::wTukey).v (PID::grainMix, 0.20f)
            .v (PID::auraSize, 0.80f).v (PID::auraDistance, 0.44f)
            .v (PID::auraFog, 0.42f).v (PID::auraDecay, 0.88f)
            .v (PID::auraLight, 0.14f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, 0.02f)
            .v (PID::patinaNoise, 0.12f).v (PID::patinaWear, 0.18f)
            .v (PID::patinaDrift, 0.18f)
            .v (PID::synthWidth, 1.12f).v (PID::highWidth, 1.26f)
            .v (PID::lowMonoFreq, 185.0f)
            .v (PID::breathAmount, 0.36f).v (PID::breathSpeed, 0.15f)
            .route (srcBreath, PID::filter2Cutoff, 0.14f)
            .route (srcWheel, PID::rewindTail, 0.26f)
            .route (srcTouch, PID::auraDecay, 0.20f)
            .route (srcOrganic, PID::oscAWtPos, 0.12f));

        // The haunted end: a carrier pulled a quarter-tone flat, a NOTCH with
        // a negative filter envelope of its own, an index envelope that stops
        // just short of zero so the bell never entirely settles, and SPACE last
        // in the chain so the reverb gets everything the crusher and the
        // granulator have already done.
        add (out, Build ("Torre Sin Hora", "BELLS", "HAUNTED",
                         "pm,detuned,broken,notch",
                         "A PM bell with the carrier pulled a quarter-tone flat and an index envelope that settles onto a small residue rather than onto nothing, read through a NOTCH with a negative filter envelope and a COMB behind it, with REWIND stalling the transport before the reverb finally gets it.")
            .at (61, 2, 0.70f, 4.0)
            .chain ("CRUSH,GRAIN,FILTER,RETRO,REWIND,SPACE")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::masterGain, -2.0f)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.66f)
            .v (PID::driftAmount, 0.52f).v (PID::driftRate, 0.30f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.80f)
            .v (PID::oscAFine, -24.0f).v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.0f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBSemi, 6.0f)
            .v (PID::oscBFine, 44.0f)
            .v (PID::oscPmAmount, 0.22f).v (PID::pmEnvAmount, 0.52f)
            .v (PID::oscCWave, ch::tri).v (PID::oscCLevel, 0.18f)
            .v (PID::oscCOctave, 0.0f).v (PID::oscCSemi, 1.0f)
            .v (PID::oscCFine, 27.0f).v (PID::oscCPan, 0.34f)
            .v (PID::subLevel, 0.10f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.18f)
            .v (PID::noiseAttackOnly, 0.60f)
            .v (PID::bodyAmount, 0.30f).v (PID::bodyTilt, -0.18f)
            .v (PID::densityAmount, 0.24f).v (PID::preFilterDrive, 0.20f)
            .v (PID::postSaturation, 0.16f).v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::notch)
            .v (PID::filterCutoff, 1750.0f).v (PID::filterResonance, 0.46f)
            .v (PID::filterKeyTrack, 0.55f).v (PID::filterEnvAmount, -0.40f)
            .v (PID::filterVelAmount, 0.30f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Comb)
            .v (PID::filter2Cutoff, 470.0f).v (PID::filter2Res, 0.58f)
            .v (PID::filter2Mix, 0.48f)
            .v (PID::ampAttack, 0.0015f).v (PID::ampDecay, 4.5f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 2.8f)
            .v (PID::ampVelocity, 0.50f)
            .v (PID::env1Attack, 0.004f).v (PID::env1Decay, 1.3f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 1.0f)
            .v (PID::env2Attack, 0.002f).v (PID::env2Decay, 0.75f)
            .v (PID::env2Sustain, 0.05f)
            .v (PID::macroMemory, 0.64f).v (PID::memoryGen, ch::genIV)
            .v (PID::memoryBandwidth, 0.74f).v (PID::memoryWobble, 0.80f)
            .v (PID::memoryDiffusion, 0.62f).v (PID::memoryAsymmetry, 0.66f)
            .v (PID::macroCharacter, 0.56f).v (PID::macroMotion, 0.74f)
            .v (PID::macroWorld, 0.68f).v (PID::macroWeight, 0.22f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.28f)
            .v (PID::crushBits, 7.0f).v (PID::crushRate, 9500.0f)
            .v (PID::crushJitter, 0.48f).v (PID::crushTone, -0.18f)
            .v (PID::crushMix, 0.36f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.50f)
            .v (PID::grainSize, 210.0f).v (PID::grainDensity, 6.0f)
            .v (PID::grainPosition, 0.56f).v (PID::grainPitchMode, ch::gFree)
            .v (PID::grainPitch, -5.0f).v (PID::grainSpread, 0.70f)
            .v (PID::grainJitter, 0.52f).v (PID::grainDirection, 0.44f)
            .v (PID::grainWindow, ch::wExpo).v (PID::grainFeedback, 0.36f)
            .v (PID::grainMix, 0.40f)
            .v (PID::retroEra, 0.18f).v (PID::retroAge, 0.66f)
            .v (PID::retroDrift, 0.62f).v (PID::retroWear, 0.56f)
            .v (PID::retroTone, -0.24f).v (PID::retroNoise, 0.26f)
            .v (PID::retroMix, 0.78f)
            .v (PID::fxFilterCutoff, 5000.0f).v (PID::fxFilterRes, 0.22f)
            .v (PID::fxFilterMotion, 0.30f)
            .v (PID::rewindOn, 1.0f).v (PID::rewindMode, ch::rStop)
            .v (PID::rewindDivision, ch::rw2).v (PID::rewindCurve, 0.70f)
            .v (PID::rewindSpeed, 0.50f).v (PID::rewindTail, 0.60f)
            .v (PID::rewindMix, 0.44f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.66f)
            .v (PID::spaceSize, 0.82f).v (PID::spaceDecay, 13.0f)
            .v (PID::spaceFog, 0.72f).v (PID::spaceLight, -0.46f)
            .v (PID::spacePreDelay, 70.0f).v (PID::spaceMix, 0.46f)
            .v (PID::auraSize, 0.72f).v (PID::auraDistance, 0.52f)
            .v (PID::auraFog, 0.64f).v (PID::auraDecay, 0.70f)
            .v (PID::auraLight, -0.34f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.30f)
            .v (PID::patinaNoise, 0.26f).v (PID::patinaWear, 0.54f)
            .v (PID::patinaDrift, 0.48f)
            .v (PID::synthWidth, 1.20f).v (PID::lowMonoFreq, 165.0f)
            .v (PID::breathAmount, 0.64f).v (PID::breathSpeed, 0.26f)
            .v (PID::breathRandom, 0.78f).v (PID::breathShape, 0.66f)
            .v (PID::lfo2Shape, ch::lfoRandom).v (PID::lfo2Rate, 0.30f)
            .v (PID::lfo2Depth, 0.65f)
            .route (srcLfo2, PID::oscAFine, 0.12f)
            .route (srcBreath, PID::filter2Cutoff, 0.20f)
            .route (srcOrganic, PID::memoryWobble, 0.22f)
            .route (srcWheel, PID::oscPmAmount, 0.34f));

        // Digital: two wavetable families against each other, granulated
        // before anything else in the chain touches them, and resolved by a
        // FORMANT bank that does not follow the keyboard at all.
        add (out, Build ("Incensario", "BELLS", "BROKEN",
                         "spectral,digital,formant,granular",
                         "SPECTRAL against METALLIC wavetables with ring modulation and a little hard sync, granulated first and resolved by a FORMANT bank at zero key tracking.")
            .at (66, 1, 0.76f, 3.5)
            .chain ("GRAIN,CRUSH,FILTER,SPACE,RETRO,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.40f)
            .v (PID::driftAmount, 0.16f).v (PID::driftRate, 0.24f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tSpectral)
            .v (PID::oscAWtPos, 0.72f).v (PID::oscALevel, 0.64f)
            .v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tMetal)
            .v (PID::oscBWtPos, 0.56f).v (PID::oscBLevel, 0.34f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBSemi, -1.0f)
            .v (PID::oscBFine, 43.0f).v (PID::oscBPan, 0.28f)
            .v (PID::oscRingMod, 0.30f).v (PID::oscSync, 0.18f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nDigital).v (PID::noiseLevel, 0.20f)
            .v (PID::noiseAttackOnly, 0.75f)
            .v (PID::bodyAmount, 0.16f).v (PID::bodyTilt, 0.36f)
            .v (PID::densityAmount, 0.20f).v (PID::preFilterDrive, 0.14f)
            .v (PID::postSaturation, 0.14f).v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 2200.0f).v (PID::filterResonance, 0.36f)
            .v (PID::filterKeyTrack, 0.0f).v (PID::filterEnvAmount, 0.30f)
            .v (PID::filterVelAmount, 0.36f)
            .v (PID::ampAttack, 0.0006f).v (PID::ampDecay, 2.0f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 1.3f)
            .v (PID::ampVelocity, 0.66f)
            .v (PID::env1Decay, 0.45f).v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.34f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.58f).v (PID::memoryWobble, 0.46f)
            .v (PID::memoryDiffusion, 0.54f).v (PID::memoryAsymmetry, 0.50f)
            .v (PID::macroCharacter, 0.46f).v (PID::macroMotion, 0.52f)
            .v (PID::macroWorld, 0.58f).v (PID::macroWeight, 0.20f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.62f)
            .v (PID::grainSize, 18.0f).v (PID::grainDensity, 42.0f)
            .v (PID::grainPosition, 0.26f).v (PID::grainPitchMode, ch::gChromatic)
            .v (PID::grainSpread, 0.78f).v (PID::grainJitter, 0.50f)
            .v (PID::grainDirection, 0.34f).v (PID::grainWindow, ch::wPercussive)
            .v (PID::grainFeedback, 0.30f).v (PID::grainMix, 0.48f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.22f)
            .v (PID::crushBits, 6.0f).v (PID::crushRate, 14000.0f)
            .v (PID::crushJitter, 0.18f).v (PID::crushTone, 0.10f)
            .v (PID::crushMix, 0.28f)
            .v (PID::fxFilterCutoff, 10500.0f).v (PID::fxFilterRes, 0.16f)
            .v (PID::fxFilterMorph, 0.40f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.54f)
            .v (PID::spaceSize, 0.64f).v (PID::spaceDecay, 6.0f)
            .v (PID::spaceFog, 0.50f).v (PID::spaceLight, 0.16f)
            .v (PID::spacePreDelay, 26.0f).v (PID::spaceMix, 0.34f)
            .v (PID::retroEra, 0.74f).v (PID::retroAge, 0.24f)
            .v (PID::retroDrift, 0.18f).v (PID::retroWear, 0.16f)
            .v (PID::retroTone, 0.08f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.38f)
            .v (PID::auraSize, 0.68f).v (PID::auraDistance, 0.40f)
            .v (PID::auraFog, 0.46f).v (PID::auraDecay, 0.74f)
            .v (PID::auraLight, 0.24f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.20f)
            .v (PID::patinaNoise, 0.12f).v (PID::patinaWear, 0.22f)
            .v (PID::patinaDrift, 0.20f)
            .v (PID::synthWidth, 1.16f).v (PID::highWidth, 1.34f)
            .v (PID::lowMonoFreq, 210.0f)
            .v (PID::breathAmount, 0.40f).v (PID::breathSpeed, 0.32f)
            .v (PID::breathShape, 0.62f)
            .v (PID::lfo1Shape, ch::lfoRandom).v (PID::lfo1Rate, 3.20f)
            .v (PID::lfo1Depth, 0.45f)
            .route (srcLfo1, PID::oscAWtPos, 0.20f)
            .route (srcOrganic, PID::grainPosition, 0.24f)
            .route (srcWheel, PID::oscRingMod, 0.28f)
            .route (srcBreath, PID::fxFilterMorph, 0.16f));
    }
}
