#include "PresetBuilder.h"
#include "Builders.h"

namespace nacar::presets::detail
{
    // ===============================================================
    //  BELLS
    // ===============================================================
    void buildBells (std::vector<FactoryPreset>& out)
    {
        // Audio-rate FM at a deliberately inharmonic ratio, which is what
        // makes a bell a bell.  The decay is long and the filter tracks.
        add (out, Build ("Harbour Bell", "BELLS", "MYSTERIOUS",
                         "fm,inharmonic,long decay,distant",
                         "A buoy bell heard across water, ringing at nobody in particular.")
            .at (55, 1, 0.75f, 7.0)
            .chain ("FILTER,RETRO,SPACE,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.34f)
            .v (PID::driftAmount, 0.20f).v (PID::driftRate, 0.08f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.84f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.0f)
            .v (PID::oscBSemi, 5.0f).v (PID::oscBFine, 23.0f)
            .v (PID::oscBOctave, 1.0f)
            .v (PID::oscFmAmount, 0.46f)
            .v (PID::oscCWave, ch::sine).v (PID::oscCLevel, 0.16f)
            .v (PID::oscCOctave, 2.0f).v (PID::oscCSemi, 3.0f)
            .v (PID::oscCFine, -18.0f).v (PID::oscCPan, 0.35f)
            .v (PID::subLevel, 0.10f)
            .v (PID::bodyAmount, 0.20f).v (PID::densityAmount, 0.18f)
            .v (PID::postSaturation, 0.08f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 5200.0f).v (PID::filterResonance, 0.12f)
            .v (PID::filterKeyTrack, 0.95f).v (PID::filterEnvAmount, 0.40f)
            .v (PID::filterVelAmount, 0.50f)
            .v (PID::ampAttack, 0.0015f).v (PID::ampDecay, 6.0f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 3.2f)
            .v (PID::ampVelocity, 0.62f)
            .v (PID::env1Attack, 0.001f).v (PID::env1Decay, 1.4f)
            .v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.30f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.42f).v (PID::memoryWobble, 0.30f)
            .v (PID::memoryDiffusion, 0.44f)
            .v (PID::macroCharacter, 0.24f).v (PID::macroMotion, 0.40f)
            .v (PID::macroWorld, 0.72f).v (PID::macroWeight, 0.24f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::retroEra, 0.48f).v (PID::retroAge, 0.24f)
            .v (PID::retroDrift, 0.26f).v (PID::retroWear, 0.12f)
            .v (PID::retroTone, -0.14f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.46f)
            .v (PID::fxFilterCutoff, 9000.0f).v (PID::fxFilterMotion, 0.18f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.66f)
            .v (PID::spaceSize, 0.78f).v (PID::spaceDecay, 8.0f)
            .v (PID::spaceFog, 0.54f).v (PID::spaceLight, -0.16f)
            .v (PID::spacePreDelay, 12.0f).v (PID::spaceMix, 0.42f)
            .v (PID::auraSize, 0.72f).v (PID::auraDistance, 0.50f)
            .v (PID::auraFog, 0.50f).v (PID::auraDecay, 0.66f)
            .v (PID::auraLight, -0.10f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.10f)
            .v (PID::patinaNoise, 0.12f).v (PID::patinaWear, 0.26f)
            .v (PID::patinaDrift, 0.30f)
            .v (PID::synthWidth, 1.15f).v (PID::highWidth, 1.25f)
            .v (PID::breathAmount, 0.44f).v (PID::breathSpeed, 0.12f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.16f)
            .v (PID::lfo1Depth, 0.55f)
            .route (srcLfo1, PID::oscFmAmount, 0.12f)
            .route (srcBreath, PID::spaceDistance, 0.14f)
            .route (srcWheel, PID::oscFmAmount, 0.30f));

        // Generation IV plus the highest wobble in the library.  The
        // instability IS the preset; the oscillator underneath is plain.
        add (out, Build ("Broken Music Box", "BELLS", "HAUNTED",
                         "music box,wobble,generation iv,small",
                         "A music box with a bent comb, running down for the last time.")
            .at (72, 1, 0.68f, 5.0)
            .chain ("CRUSH,RETRO,FILTER,GRAIN,SPACE,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::masterGain, 11.0f)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.60f)
            .v (PID::driftAmount, 0.44f).v (PID::driftRate, 0.34f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.90f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.22f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBSemi, 7.0f)
            .v (PID::oscBFine, 27.0f)
            .v (PID::oscRingMod, 0.26f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.12f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.14f).v (PID::densityAmount, 0.14f)
            .v (PID::postSaturation, 0.10f)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 2400.0f).v (PID::filterResonance, 0.42f)
            .v (PID::filterKeyTrack, 1.0f).v (PID::filterEnvAmount, 0.34f)
            .v (PID::ampAttack, 0.0008f).v (PID::ampDecay, 2.2f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 1.4f)
            .v (PID::ampVelocity, 0.58f)
            .v (PID::env1Decay, 0.35f).v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.68f).v (PID::memoryGen, ch::genIV)
            .v (PID::memoryBandwidth, 0.78f).v (PID::memoryWobble, 0.88f)
            .v (PID::memoryDiffusion, 0.52f).v (PID::memoryAsymmetry, 0.58f)
            .v (PID::macroCharacter, 0.52f).v (PID::macroMotion, 0.72f)
            .v (PID::macroWorld, 0.42f).v (PID::macroWeight, 0.18f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.30f)
            .v (PID::crushBits, 8.0f).v (PID::crushRate, 12000.0f)
            .v (PID::crushJitter, 0.42f).v (PID::crushTone, -0.14f)
            .v (PID::crushMix, 0.44f)
            .v (PID::retroEra, 0.34f).v (PID::retroAge, 0.62f)
            .v (PID::retroDrift, 0.66f).v (PID::retroWear, 0.52f)
            .v (PID::retroTone, -0.18f).v (PID::retroNoise, 0.24f)
            .v (PID::retroMix, 0.88f)
            .v (PID::fxFilterCutoff, 6400.0f).v (PID::fxFilterRes, 0.16f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.48f)
            .v (PID::spaceSize, 0.44f).v (PID::spaceDecay, 3.4f)
            .v (PID::spaceFog, 0.58f).v (PID::spaceLight, -0.40f)
            .v (PID::spaceMix, 0.34f)
            .v (PID::auraSize, 0.48f).v (PID::auraDistance, 0.38f)
            .v (PID::auraFog, 0.62f).v (PID::auraDecay, 0.48f)
            .v (PID::auraLight, -0.26f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.22f)
            .v (PID::patinaNoise, 0.28f).v (PID::patinaWear, 0.52f)
            .v (PID::patinaDrift, 0.46f)
            .v (PID::breathAmount, 0.62f).v (PID::breathSpeed, 0.40f)
            .v (PID::breathRandom, 0.82f).v (PID::breathShape, 0.72f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.38f)
            .v (PID::lfo2Depth, 0.70f)
            .route (srcLfo2, PID::oscBFine, 0.10f)
            .route (srcBreath, PID::memoryWobble, 0.24f)
            .route (srcOrganic, PID::crushJitter, 0.20f));

        // The brightest preset in the library: METALLIC high, AIR weight,
        // CHROME surface, and nothing below 200 Hz to get in the way.
        add (out, Build ("Chrome Glockenspiel", "BELLS", "AIRY",
                         "metallic,bright,air,short",
                         "Struck metal with all the weight taken out and only the shine left.")
            .at (79, 1, 0.80f, 3.0)
            .chain ("FILTER,SPACE,RETRO,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 12.0f).v (PID::voiceVariation, 0.24f)
            .v (PID::driftAmount, 0.08f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tMetal)
            .v (PID::oscAWtPos, 0.18f).v (PID::oscALevel, 0.66f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.34f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBSemi, 4.0f)
            .v (PID::oscBPan, -0.12f)
            .v (PID::oscCWave, ch::sine).v (PID::oscCLevel, 0.12f)
            .v (PID::oscCOctave, 2.0f).v (PID::oscCPan, 0.14f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nAir).v (PID::noiseLevel, 0.12f)
            .v (PID::noiseAttackOnly, 0.85f)
            .v (PID::bodyAmount, 0.06f).v (PID::densityAmount, 0.08f)
            .v (PID::postSaturation, 0.06f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::hp)
            .v (PID::filterCutoff, 300.0f).v (PID::filterResonance, 0.08f)
            .v (PID::filterKeyTrack, 0.30f).v (PID::filterEnvAmount, 0.0f)
            .v (PID::filterVelAmount, 0.20f)
            .v (PID::ampAttack, 0.0006f).v (PID::ampDecay, 1.4f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.9f)
            .v (PID::ampVelocity, 0.72f)
            .v (PID::macroMemory, 0.10f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.14f).v (PID::memoryWobble, 0.10f)
            .v (PID::macroCharacter, 0.14f).v (PID::macroMotion, 0.24f)
            .v (PID::macroWorld, 0.56f).v (PID::macroWeight, 0.34f)
            .v (PID::weightMode, ch::wAir).v (PID::weightHarmonics, 0.56f)
            .v (PID::weightCompress, 0.30f)
            .v (PID::retroEra, 0.94f).v (PID::retroAge, 0.08f)
            .v (PID::retroDrift, 0.06f).v (PID::retroWear, 0.04f)
            .v (PID::retroTone, 0.30f).v (PID::retroNoise, 0.04f)
            .v (PID::retroMix, 0.30f)
            .v (PID::fxFilterCutoff, 17000.0f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.40f)
            .v (PID::spaceSize, 0.62f).v (PID::spaceDecay, 4.4f)
            .v (PID::spaceFog, 0.34f).v (PID::spaceLight, 0.52f)
            .v (PID::spacePreDelay, 30.0f).v (PID::spaceMix, 0.26f)
            .v (PID::auraSize, 0.58f).v (PID::auraDistance, 0.24f)
            .v (PID::auraFog, 0.30f).v (PID::auraDecay, 0.52f)
            .v (PID::auraLight, 0.56f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.34f)
            .v (PID::patinaNoise, 0.10f).v (PID::patinaWear, 0.18f)
            .v (PID::patinaDrift, 0.12f)
            .v (PID::synthWidth, 1.00f).v (PID::highWidth, 1.20f)
            .v (PID::lowMonoFreq, 250.0f)
            .v (PID::breathAmount, 0.24f).v (PID::breathSpeed, 0.30f)
            .v (PID::lfo1Shape, ch::lfoTri).v (PID::lfo1Rate, 0.42f)
            .v (PID::lfo1Depth, 0.40f)
            .route (srcLfo1, PID::oscAWtPos, 0.18f)
            .route (srcBreath, PID::auraLight, 0.12f));

        // Ring modulation between two detuned saws, INFINITE space and the
        // longest decay in the library.  This is the cinematic corner.
        add (out, Build ("Distant Church Bells", "BELLS", "CINEMATIC",
                         "ring mod,infinite,huge,slow",
                         "Bells from a town you are driving away from, in a reverb with no end.")
            .at (43, 2, 0.90f, 11.0)
            .chain ("FILTER,RETRO,GRAIN,SPACE,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.40f)
            .v (PID::driftAmount, 0.24f).v (PID::driftRate, 0.05f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.72f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.10f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.24f)
            .v (PID::oscBSemi, 6.0f).v (PID::oscBFine, 17.0f)
            .v (PID::oscRingMod, 0.52f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.30f)
            .v (PID::subHarmonics, 0.26f)
            .v (PID::bodyAmount, 0.48f).v (PID::densityAmount, 0.30f)
            .v (PID::preFilterDrive, 0.18f).v (PID::postSaturation, 0.18f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 2800.0f).v (PID::filterResonance, 0.22f)
            .v (PID::filterDrive, 0.28f).v (PID::filterKeyTrack, 0.70f)
            .v (PID::filterEnvAmount, 0.48f).v (PID::filterVelAmount, 0.50f)
            .v (PID::ampAttack, 0.004f).v (PID::ampDecay, 9.0f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 7.0f)
            .v (PID::ampVelocity, 0.60f)
            .v (PID::env1Attack, 0.002f).v (PID::env1Decay, 2.6f)
            .v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.36f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.52f).v (PID::memoryWobble, 0.34f)
            .v (PID::memoryDiffusion, 0.50f).v (PID::memoryAsymmetry, 0.30f)
            .v (PID::macroCharacter, 0.42f).v (PID::macroMotion, 0.44f)
            .v (PID::macroWorld, 0.88f).v (PID::macroWeight, 0.46f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.40f)
            .v (PID::weightCompress, 0.36f)
            .v (PID::retroEra, 0.24f).v (PID::retroAge, 0.34f)
            .v (PID::retroDrift, 0.30f).v (PID::retroWear, 0.18f)
            .v (PID::retroTone, -0.28f).v (PID::retroNoise, 0.14f)
            .v (PID::retroMix, 0.62f)
            .v (PID::fxFilterCutoff, 5800.0f).v (PID::fxFilterMotion, 0.24f)
            .v (PID::spaceCharacter, ch::sInfinite).v (PID::spaceDistance, 0.70f)
            .v (PID::spaceSize, 0.92f).v (PID::spaceDecay, 22.0f)
            .v (PID::spaceFog, 0.66f).v (PID::spaceLight, -0.24f)
            .v (PID::spacePreDelay, 80.0f).v (PID::spaceMix, 0.50f)
            .v (PID::shadowOn, 1.0f).v (PID::shadowLength, 0.60f)
            .v (PID::shadowDistance, 0.72f).v (PID::shadowBlur, 0.66f)
            .v (PID::shadowPitch, -12.0f).v (PID::shadowLevel, 0.30f)
            .v (PID::auraSize, 0.86f).v (PID::auraDistance, 0.56f)
            .v (PID::auraFog, 0.58f).v (PID::auraDecay, 0.84f)
            .v (PID::auraLight, -0.18f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.20f)
            .v (PID::patinaNoise, 0.16f).v (PID::patinaWear, 0.30f)
            .v (PID::patinaDrift, 0.28f)
            .v (PID::synthWidth, 1.20f).v (PID::highWidth, 1.30f)
            .v (PID::lowMonoFreq, 160.0f)
            .v (PID::breathAmount, 0.50f).v (PID::breathSpeed, 0.06f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.07f)
            .v (PID::lfo1Depth, 0.60f)
            .route (srcLfo1, PID::oscRingMod, 0.14f)
            .route (srcBreath, PID::shadowPitch, 0.06f)
            .route (srcWorld, PID::spaceSize, 0.12f));
    }
}
