#include "PresetBuilder.h"
#include "Builders.h"

namespace nacar::presets::detail
{
    // ===============================================================
    //  DRUMS
    //
    //  There is no pitch envelope in the parameter list, so the fall that
    //  makes a kick a kick is made with the MASS ladder instead: a high
    //  resonance peak swept down by mod envelope 1 is a pitched thump, and
    //  it is the honest way to get one out of the controls that exist.
    // ===============================================================
    void buildDrums (std::vector<FactoryPreset>& out)
    {
        add (out, Build ("Cardboard Kick", "DRUMS", "MINIMAL",
                         "kick,sub,short,dry",
                         "A kick with a box round it, all weight and no click.")
            .at (36, 1, 1.0f, 1.6)
            .chain ("FILTER,RETRO,CRUSH,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::voiceVariation, 0.08f).v (PID::driftAmount, 0.02f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.80f)
            .v (PID::oscAOctave, -1.0f).v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscAPhaseOffset, 0.25f)
            .v (PID::oscBLevel, 0.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.50f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.38f)
            .v (PID::noiseType, ch::nDark).v (PID::noiseLevel, 0.16f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.60f).v (PID::densityAmount, 0.10f)
            .v (PID::preFilterDrive, 0.26f).v (PID::postSaturation, 0.20f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 120.0f).v (PID::filterResonance, 0.58f)
            .v (PID::filterDrive, 0.34f).v (PID::filterKeyTrack, 0.0f)
            .v (PID::filterEnvAmount, 0.62f).v (PID::filterVelAmount, 0.40f)
            .v (PID::ampAttack, 0.0008f).v (PID::ampDecay, 0.38f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.12f)
            .v (PID::ampVelocity, 0.55f)
            .v (PID::env1Attack, 0.0006f).v (PID::env1Decay, 0.055f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.04f)
            .v (PID::macroMemory, 0.14f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.30f).v (PID::memoryWobble, 0.04f)
            .v (PID::memoryAsymmetry, 0.0f)
            .v (PID::macroCharacter, 0.34f).v (PID::macroMotion, 0.08f)
            .v (PID::macroWorld, 0.10f).v (PID::macroWeight, 0.66f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.60f)
            .v (PID::weightCompress, 0.36f)
            .v (PID::retroEra, 0.44f).v (PID::retroAge, 0.24f)
            .v (PID::retroDrift, 0.04f).v (PID::retroWear, 0.06f)
            .v (PID::retroTone, -0.26f).v (PID::retroNoise, 0.06f)
            .v (PID::retroMix, 0.45f)
            .v (PID::fxFilterCutoff, 2400.0f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.12f)
            .v (PID::spaceSize, 0.16f).v (PID::spaceDecay, 0.4f)
            .v (PID::spaceFog, 0.16f).v (PID::spaceLight, -0.40f)
            .v (PID::spacePreDelay, 4.0f).v (PID::spaceMix, 0.08f)
            .v (PID::auraSize, 0.14f).v (PID::auraDistance, 0.08f)
            .v (PID::auraFog, 0.20f).v (PID::auraDecay, 0.10f)
            .v (PID::auraLight, -0.34f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.16f)
            .v (PID::patinaNoise, 0.06f).v (PID::patinaWear, 0.12f)
            .v (PID::synthWidth, 0.40f).v (PID::highWidth, 0.70f)
            .v (PID::lowMonoFreq, 300.0f)
            .v (PID::breathOn, 0.0f).v (PID::breathAmount, 0.0f)
            .route (srcTouch, PID::filterCutoff, 0.10f));

        add (out, Build ("Tape Snare", "DRUMS", "DIRTY",
                         "snare,noise,crush,room",
                         "A snare that was printed hot and has been played since.")
            .at (38, 1, 1.0f, 1.8)
            .chain ("CRUSH,RETRO,FILTER,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::masterGain, 10.0f)
            .v (PID::voiceMode, ch::poly).v (PID::polyphony, 4.0f)
            .v (PID::voiceVariation, 0.30f).v (PID::driftAmount, 0.06f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.52f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.22f)
            .v (PID::oscBSemi, 6.0f).v (PID::oscBFine, 18.0f)
            .v (PID::oscRingMod, 0.22f)
            .v (PID::subLevel, 0.14f).v (PID::subHarmonics, 0.30f)
            .v (PID::noiseType, ch::nWhite).v (PID::noiseLevel, 0.84f)
            .v (PID::noiseAttackOnly, 0.35f)
            .v (PID::bodyAmount, 0.40f).v (PID::densityAmount, 0.20f)
            .v (PID::preFilterDrive, 0.38f).v (PID::postSaturation, 0.34f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 1900.0f).v (PID::filterResonance, 0.24f)
            .v (PID::filterKeyTrack, 0.20f).v (PID::filterEnvAmount, 0.44f)
            .v (PID::filterVelAmount, 0.50f)
            .v (PID::ampAttack, 0.0006f).v (PID::ampDecay, 0.30f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.20f)
            .v (PID::ampVelocity, 0.62f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.09f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.06f)
            .v (PID::macroMemory, 0.36f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.52f).v (PID::memoryWobble, 0.10f)
            .v (PID::memoryAsymmetry, 0.24f)
            .v (PID::macroCharacter, 0.64f).v (PID::macroMotion, 0.16f)
            .v (PID::macroWorld, 0.32f).v (PID::macroWeight, 0.36f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.40f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.40f)
            .v (PID::crushBits, 10.0f).v (PID::crushRate, 18000.0f)
            .v (PID::crushJitter, 0.12f).v (PID::crushDrive, 0.30f)
            .v (PID::crushTone, 0.10f).v (PID::crushMix, 0.50f)
            .v (PID::retroEra, 0.36f).v (PID::retroAge, 0.56f)
            .v (PID::retroDrift, 0.10f).v (PID::retroWear, 0.30f)
            .v (PID::retroTone, -0.12f).v (PID::retroNoise, 0.18f)
            .v (PID::retroMix, 0.76f)
            .v (PID::fxFilterCutoff, 8500.0f).v (PID::fxFilterRes, 0.14f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.30f)
            .v (PID::spaceSize, 0.34f).v (PID::spaceDecay, 1.1f)
            .v (PID::spaceFog, 0.30f).v (PID::spaceLight, -0.10f)
            .v (PID::spacePreDelay, 8.0f).v (PID::spaceMix, 0.24f)
            .v (PID::auraSize, 0.28f).v (PID::auraDistance, 0.18f)
            .v (PID::auraFog, 0.30f).v (PID::auraDecay, 0.22f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.10f)
            .v (PID::patinaNoise, 0.18f).v (PID::patinaWear, 0.32f)
            .v (PID::synthWidth, 0.95f).v (PID::highWidth, 1.10f)
            .v (PID::breathAmount, 0.14f)
            .route (srcOrganic, PID::filterCutoff, 0.10f));

        add (out, Build ("Concrete Tom", "DRUMS", "DARK",
                         "tom,low,thud,dark",
                         "A floor tom in a stairwell, hit once and left alone.")
            .at (41, 1, 1.0f, 2.2)
            .chain ("FILTER,RETRO,SPACE,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::poly).v (PID::polyphony, 4.0f)
            .v (PID::voiceVariation, 0.22f).v (PID::driftAmount, 0.08f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.76f)
            .v (PID::oscAPhase, ch::phaseReset).v (PID::oscAPhaseOffset, 0.25f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.30f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, -12.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.40f)
            .v (PID::subHarmonics, 0.30f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.26f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.64f).v (PID::bodyTilt, -0.20f)
            .v (PID::densityAmount, 0.22f)
            .v (PID::preFilterDrive, 0.30f).v (PID::postSaturation, 0.24f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 380.0f).v (PID::filterResonance, 0.44f)
            .v (PID::filterDrive, 0.30f).v (PID::filterKeyTrack, 0.30f)
            .v (PID::filterEnvAmount, 0.50f).v (PID::filterVelAmount, 0.50f)
            .v (PID::ampAttack, 0.0008f).v (PID::ampDecay, 0.90f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.34f)
            .v (PID::ampVelocity, 0.58f)
            .v (PID::env1Attack, 0.0006f).v (PID::env1Decay, 0.13f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.08f)
            .v (PID::macroMemory, 0.30f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.56f).v (PID::memoryWobble, 0.08f)
            .v (PID::memoryAsymmetry, 0.12f)
            .v (PID::macroCharacter, 0.48f).v (PID::macroMotion, 0.14f)
            .v (PID::macroWorld, 0.36f).v (PID::macroWeight, 0.52f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.44f)
            .v (PID::weightCompress, 0.34f)
            .v (PID::retroEra, 0.22f).v (PID::retroAge, 0.42f)
            .v (PID::retroDrift, 0.08f).v (PID::retroWear, 0.16f)
            .v (PID::retroTone, -0.36f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.64f)
            .v (PID::fxFilterCutoff, 2000.0f).v (PID::fxFilterDrive, 0.16f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.36f)
            .v (PID::spaceSize, 0.44f).v (PID::spaceDecay, 2.0f)
            .v (PID::spaceFog, 0.40f).v (PID::spaceLight, -0.50f)
            .v (PID::spacePreDelay, 10.0f).v (PID::spaceMix, 0.22f)
            .v (PID::auraSize, 0.34f).v (PID::auraDistance, 0.20f)
            .v (PID::auraFog, 0.36f).v (PID::auraDecay, 0.26f)
            .v (PID::auraLight, -0.40f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.30f)
            .v (PID::patinaNoise, 0.14f).v (PID::patinaWear, 0.30f)
            .v (PID::synthWidth, 0.80f).v (PID::highWidth, 0.90f)
            .v (PID::lowMonoFreq, 240.0f)
            .v (PID::breathAmount, 0.12f)
            .route (srcTouch, PID::bodyAmount, 0.12f));

        add (out, Build ("Glass Hat", "DRUMS", "COLD",
                         "hat,bright,tight,metal",
                         "A hi-hat made of something that was never a cymbal.")
            .at (66, 1, 0.92f, 1.2)
            .chain ("FILTER,CRUSH,SPACE,RETRO,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::voiceMode, ch::poly).v (PID::polyphony, 6.0f)
            .v (PID::voiceVariation, 0.26f).v (PID::driftAmount, 0.04f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tMetal)
            .v (PID::oscAWtPos, 0.80f).v (PID::oscALevel, 0.34f)
            .v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::square).v (PID::oscBLevel, 0.20f)
            .v (PID::oscBPulseWidth, 0.18f).v (PID::oscBSemi, 11.0f)
            .v (PID::oscRingMod, 0.40f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nWhite).v (PID::noiseLevel, 0.58f)
            .v (PID::noiseAttackOnly, 0.20f)
            .v (PID::bodyAmount, 0.02f).v (PID::densityAmount, 0.06f)
            .v (PID::postSaturation, 0.10f).v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::hp)
            .v (PID::filterCutoff, 5200.0f).v (PID::filterResonance, 0.22f)
            .v (PID::filterKeyTrack, 0.30f).v (PID::filterEnvAmount, 0.20f)
            .v (PID::filterVelAmount, 0.40f)
            .v (PID::ampAttack, 0.0005f).v (PID::ampDecay, 0.13f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.07f)
            .v (PID::ampVelocity, 0.66f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.05f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.03f)
            .v (PID::macroMemory, 0.10f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.16f).v (PID::memoryWobble, 0.04f)
            .v (PID::macroCharacter, 0.30f).v (PID::macroMotion, 0.14f)
            .v (PID::macroWorld, 0.30f).v (PID::macroWeight, 0.24f)
            .v (PID::weightMode, ch::wAir).v (PID::weightHarmonics, 0.52f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.30f)
            .v (PID::crushBits, 11.0f).v (PID::crushRate, 24000.0f)
            .v (PID::crushTone, 0.28f).v (PID::crushMix, 0.44f)
            .v (PID::retroEra, 0.92f).v (PID::retroAge, 0.10f)
            .v (PID::retroDrift, 0.04f).v (PID::retroWear, 0.04f)
            .v (PID::retroTone, 0.28f).v (PID::retroNoise, 0.04f)
            .v (PID::retroMix, 0.30f)
            .v (PID::fxFilterMode, ch::f2Hp).v (PID::fxFilterCutoff, 3200.0f)
            .v (PID::fxFilterRes, 0.10f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.24f)
            .v (PID::spaceSize, 0.22f).v (PID::spaceDecay, 0.7f)
            .v (PID::spaceFog, 0.18f).v (PID::spaceLight, 0.46f)
            .v (PID::spacePreDelay, 5.0f).v (PID::spaceMix, 0.18f)
            .v (PID::auraSize, 0.20f).v (PID::auraDistance, 0.12f)
            .v (PID::auraFog, 0.18f).v (PID::auraDecay, 0.14f)
            .v (PID::auraLight, 0.48f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.32f)
            .v (PID::patinaNoise, 0.08f).v (PID::patinaWear, 0.16f)
            .v (PID::synthWidth, 1.15f).v (PID::highWidth, 1.30f)
            .v (PID::lowMonoFreq, 300.0f)
            .v (PID::breathAmount, 0.10f)
            .route (srcOrganic, PID::oscAWtPos, 0.20f));
    }
}
