#include "PresetBuilder.h"
#include "Builders.h"

namespace nacar::presets::detail
{
    // ===============================================================
    //  DRUMS
    //
    //  There is no pitch envelope in the parameter list, so the fall that
    //  makes a kick a kick is made with the MASS ladder instead: a high
    //  resonance peak swept down by mod envelope 1 is a pitched thump, and
    //  it is the honest way to get one out of the controls that exist.
    // ===============================================================
    void buildDrums (std::vector<FactoryPreset>& out)
    {
        add (out, Build ("Cardboard Kick", "DRUMS", "MINIMAL",
                         "kick,sub,short,dry",
                         "A kick with a box round it, all weight and no click.")
            .at (36, 1, 1.0f, 1.6)
            .chain ("FILTER,RETRO,CRUSH,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::voiceVariation, 0.08f).v (PID::driftAmount, 0.02f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.80f)
            .v (PID::oscAOctave, -1.0f).v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscAPhaseOffset, 0.25f)
            .v (PID::oscBLevel, 0.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.50f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.38f)
            .v (PID::noiseType, ch::nDark).v (PID::noiseLevel, 0.16f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.60f).v (PID::densityAmount, 0.10f)
            .v (PID::preFilterDrive, 0.26f).v (PID::postSaturation, 0.20f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 120.0f).v (PID::filterResonance, 0.58f)
            .v (PID::filterDrive, 0.34f).v (PID::filterKeyTrack, 0.0f)
            .v (PID::filterEnvAmount, 0.62f).v (PID::filterVelAmount, 0.40f)
            .v (PID::ampAttack, 0.0008f).v (PID::ampDecay, 0.38f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.12f)
            .v (PID::ampVelocity, 0.55f)
            .v (PID::env1Attack, 0.0006f).v (PID::env1Decay, 0.055f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.04f)
            .v (PID::macroMemory, 0.14f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.30f).v (PID::memoryWobble, 0.04f)
            .v (PID::memoryAsymmetry, 0.0f)
            .v (PID::macroCharacter, 0.34f).v (PID::macroMotion, 0.08f)
            .v (PID::macroWorld, 0.10f).v (PID::macroWeight, 0.66f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.60f)
            .v (PID::weightCompress, 0.36f)
            .v (PID::retroEra, 0.44f).v (PID::retroAge, 0.24f)
            .v (PID::retroDrift, 0.04f).v (PID::retroWear, 0.06f)
            .v (PID::retroTone, -0.26f).v (PID::retroNoise, 0.06f)
            .v (PID::retroMix, 0.45f)
            .v (PID::fxFilterCutoff, 2400.0f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.12f)
            .v (PID::spaceSize, 0.16f).v (PID::spaceDecay, 0.4f)
            .v (PID::spaceFog, 0.16f).v (PID::spaceLight, -0.40f)
            .v (PID::spacePreDelay, 4.0f).v (PID::spaceMix, 0.08f)
            .v (PID::auraSize, 0.14f).v (PID::auraDistance, 0.08f)
            .v (PID::auraFog, 0.20f).v (PID::auraDecay, 0.10f)
            .v (PID::auraLight, -0.34f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.16f)
            .v (PID::patinaNoise, 0.06f).v (PID::patinaWear, 0.12f)
            .v (PID::synthWidth, 0.40f).v (PID::highWidth, 0.70f)
            .v (PID::lowMonoFreq, 300.0f)
            .v (PID::breathOn, 0.0f).v (PID::breathAmount, 0.0f)
            .route (srcTouch, PID::filterCutoff, 0.10f));

        add (out, Build ("Tape Snare", "DRUMS", "DIRTY",
                         "snare,noise,crush,room",
                         "A snare that was printed hot and has been played since.")
            .at (38, 1, 1.0f, 1.8)
            .chain ("CRUSH,RETRO,FILTER,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::masterGain, 10.0f)
            .v (PID::voiceMode, ch::poly).v (PID::polyphony, 4.0f)
            .v (PID::voiceVariation, 0.30f).v (PID::driftAmount, 0.06f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.52f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.22f)
            .v (PID::oscBSemi, 6.0f).v (PID::oscBFine, 18.0f)
            .v (PID::oscRingMod, 0.22f)
            .v (PID::subLevel, 0.14f).v (PID::subHarmonics, 0.30f)
            .v (PID::noiseType, ch::nWhite).v (PID::noiseLevel, 0.84f)
            .v (PID::noiseAttackOnly, 0.35f)
            .v (PID::bodyAmount, 0.40f).v (PID::densityAmount, 0.20f)
            .v (PID::preFilterDrive, 0.38f).v (PID::postSaturation, 0.34f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 1900.0f).v (PID::filterResonance, 0.24f)
            .v (PID::filterKeyTrack, 0.20f).v (PID::filterEnvAmount, 0.44f)
            .v (PID::filterVelAmount, 0.50f)
            .v (PID::ampAttack, 0.0006f).v (PID::ampDecay, 0.30f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.20f)
            .v (PID::ampVelocity, 0.62f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.09f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.06f)
            .v (PID::macroMemory, 0.36f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.52f).v (PID::memoryWobble, 0.10f)
            .v (PID::memoryAsymmetry, 0.24f)
            .v (PID::macroCharacter, 0.64f).v (PID::macroMotion, 0.16f)
            .v (PID::macroWorld, 0.32f).v (PID::macroWeight, 0.36f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.40f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.40f)
            .v (PID::crushBits, 10.0f).v (PID::crushRate, 18000.0f)
            .v (PID::crushJitter, 0.12f).v (PID::crushDrive, 0.30f)
            .v (PID::crushTone, 0.10f).v (PID::crushMix, 0.50f)
            .v (PID::retroEra, 0.36f).v (PID::retroAge, 0.56f)
            .v (PID::retroDrift, 0.10f).v (PID::retroWear, 0.30f)
            .v (PID::retroTone, -0.12f).v (PID::retroNoise, 0.18f)
            .v (PID::retroMix, 0.76f)
            .v (PID::fxFilterCutoff, 8500.0f).v (PID::fxFilterRes, 0.14f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.30f)
            .v (PID::spaceSize, 0.34f).v (PID::spaceDecay, 1.1f)
            .v (PID::spaceFog, 0.30f).v (PID::spaceLight, -0.10f)
            .v (PID::spacePreDelay, 8.0f).v (PID::spaceMix, 0.24f)
            .v (PID::auraSize, 0.28f).v (PID::auraDistance, 0.18f)
            .v (PID::auraFog, 0.30f).v (PID::auraDecay, 0.22f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.10f)
            .v (PID::patinaNoise, 0.18f).v (PID::patinaWear, 0.32f)
            .v (PID::synthWidth, 0.95f).v (PID::highWidth, 1.10f)
            .v (PID::breathAmount, 0.14f)
            .route (srcOrganic, PID::filterCutoff, 0.10f));

        add (out, Build ("Concrete Tom", "DRUMS", "DARK",
                         "tom,low,thud,dark",
                         "A floor tom in a stairwell, hit once and left alone.")
            .at (41, 1, 1.0f, 2.2)
            .chain ("FILTER,RETRO,SPACE,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::poly).v (PID::polyphony, 4.0f)
            .v (PID::voiceVariation, 0.22f).v (PID::driftAmount, 0.08f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.76f)
            .v (PID::oscAPhase, ch::phaseReset).v (PID::oscAPhaseOffset, 0.25f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.30f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, -12.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.40f)
            .v (PID::subHarmonics, 0.30f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.26f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.64f).v (PID::bodyTilt, -0.20f)
            .v (PID::densityAmount, 0.22f)
            .v (PID::preFilterDrive, 0.30f).v (PID::postSaturation, 0.24f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 380.0f).v (PID::filterResonance, 0.44f)
            .v (PID::filterDrive, 0.30f).v (PID::filterKeyTrack, 0.30f)
            .v (PID::filterEnvAmount, 0.50f).v (PID::filterVelAmount, 0.50f)
            .v (PID::ampAttack, 0.0008f).v (PID::ampDecay, 0.90f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.34f)
            .v (PID::ampVelocity, 0.58f)
            .v (PID::env1Attack, 0.0006f).v (PID::env1Decay, 0.13f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.08f)
            .v (PID::macroMemory, 0.30f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.56f).v (PID::memoryWobble, 0.08f)
            .v (PID::memoryAsymmetry, 0.12f)
            .v (PID::macroCharacter, 0.48f).v (PID::macroMotion, 0.14f)
            .v (PID::macroWorld, 0.36f).v (PID::macroWeight, 0.52f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.44f)
            .v (PID::weightCompress, 0.34f)
            .v (PID::retroEra, 0.22f).v (PID::retroAge, 0.42f)
            .v (PID::retroDrift, 0.08f).v (PID::retroWear, 0.16f)
            .v (PID::retroTone, -0.36f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.64f)
            .v (PID::fxFilterCutoff, 2000.0f).v (PID::fxFilterDrive, 0.16f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.36f)
            .v (PID::spaceSize, 0.44f).v (PID::spaceDecay, 2.0f)
            .v (PID::spaceFog, 0.40f).v (PID::spaceLight, -0.50f)
            .v (PID::spacePreDelay, 10.0f).v (PID::spaceMix, 0.22f)
            .v (PID::auraSize, 0.34f).v (PID::auraDistance, 0.20f)
            .v (PID::auraFog, 0.36f).v (PID::auraDecay, 0.26f)
            .v (PID::auraLight, -0.40f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.30f)
            .v (PID::patinaNoise, 0.14f).v (PID::patinaWear, 0.30f)
            .v (PID::synthWidth, 0.80f).v (PID::highWidth, 0.90f)
            .v (PID::lowMonoFreq, 240.0f)
            .v (PID::breathAmount, 0.12f)
            .route (srcTouch, PID::bodyAmount, 0.12f));

        add (out, Build ("Glass Hat", "DRUMS", "COLD",
                         "hat,bright,tight,metal",
                         "A hi-hat made of something that was never a cymbal.")
            .at (66, 1, 0.92f, 1.2)
            .chain ("FILTER,CRUSH,SPACE,RETRO,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::voiceMode, ch::poly).v (PID::polyphony, 6.0f)
            .v (PID::voiceVariation, 0.26f).v (PID::driftAmount, 0.04f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tMetal)
            .v (PID::oscAWtPos, 0.80f).v (PID::oscALevel, 0.34f)
            .v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::square).v (PID::oscBLevel, 0.20f)
            .v (PID::oscBPulseWidth, 0.18f).v (PID::oscBSemi, 11.0f)
            .v (PID::oscRingMod, 0.40f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nWhite).v (PID::noiseLevel, 0.58f)
            .v (PID::noiseAttackOnly, 0.20f)
            .v (PID::bodyAmount, 0.02f).v (PID::densityAmount, 0.06f)
            .v (PID::postSaturation, 0.10f).v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::hp)
            .v (PID::filterCutoff, 5200.0f).v (PID::filterResonance, 0.22f)
            .v (PID::filterKeyTrack, 0.30f).v (PID::filterEnvAmount, 0.20f)
            .v (PID::filterVelAmount, 0.40f)
            .v (PID::ampAttack, 0.0005f).v (PID::ampDecay, 0.13f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.07f)
            .v (PID::ampVelocity, 0.66f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.05f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.03f)
            .v (PID::macroMemory, 0.10f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.16f).v (PID::memoryWobble, 0.04f)
            .v (PID::macroCharacter, 0.30f).v (PID::macroMotion, 0.14f)
            .v (PID::macroWorld, 0.30f).v (PID::macroWeight, 0.24f)
            .v (PID::weightMode, ch::wAir).v (PID::weightHarmonics, 0.52f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.30f)
            .v (PID::crushBits, 11.0f).v (PID::crushRate, 24000.0f)
            .v (PID::crushTone, 0.28f).v (PID::crushMix, 0.44f)
            .v (PID::retroEra, 0.92f).v (PID::retroAge, 0.10f)
            .v (PID::retroDrift, 0.04f).v (PID::retroWear, 0.04f)
            .v (PID::retroTone, 0.28f).v (PID::retroNoise, 0.04f)
            .v (PID::retroMix, 0.30f)
            .v (PID::fxFilterMode, ch::f2Hp).v (PID::fxFilterCutoff, 3200.0f)
            .v (PID::fxFilterRes, 0.10f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.24f)
            .v (PID::spaceSize, 0.22f).v (PID::spaceDecay, 0.7f)
            .v (PID::spaceFog, 0.18f).v (PID::spaceLight, 0.46f)
            .v (PID::spacePreDelay, 5.0f).v (PID::spaceMix, 0.18f)
            .v (PID::auraSize, 0.20f).v (PID::auraDistance, 0.12f)
            .v (PID::auraFog, 0.18f).v (PID::auraDecay, 0.14f)
            .v (PID::auraLight, 0.48f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.32f)
            .v (PID::patinaNoise, 0.08f).v (PID::patinaWear, 0.16f)
            .v (PID::synthWidth, 1.15f).v (PID::highWidth, 1.30f)
            .v (PID::lowMonoFreq, 300.0f)
            .v (PID::breathAmount, 0.10f)
            .route (srcOrganic, PID::oscAWtPos, 0.20f));

        // -- Kicks.  The fall is the resonant MASS peak swept by env 1; how
        //    deep and how fast is most of what separates these four. -------

        add (out, Build ("Long Hammer", "DRUMS", "DARK",
                         "kick,808,long,sub",
                         "A sine an octave down under the MASS ladder, swept by env 1, with 1.6 seconds of amp decay under it.")
            .at (36, 1, 1.0f, 2.5)
            .chain ("RETRO,FILTER,CRUSH,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::masterGain, -2.0f)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::voiceVariation, 0.05f).v (PID::driftAmount, 0.02f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.82f)
            .v (PID::oscAOctave, -1.0f).v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscAPhaseOffset, 0.25f)
            .v (PID::oscBLevel, 0.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.62f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.42f)
            .v (PID::noiseType, ch::nDark).v (PID::noiseLevel, 0.10f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.52f).v (PID::densityAmount, 0.12f)
            .v (PID::preFilterDrive, 0.18f).v (PID::postSaturation, 0.14f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 90.0f).v (PID::filterResonance, 0.50f)
            .v (PID::filterDrive, 0.22f).v (PID::filterKeyTrack, 0.0f)
            .v (PID::filterEnvAmount, 0.55f).v (PID::filterVelAmount, 0.30f)
            .v (PID::ampAttack, 0.001f).v (PID::ampDecay, 1.60f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.45f)
            .v (PID::ampVelocity, 0.45f)
            .v (PID::env1Attack, 0.0006f).v (PID::env1Decay, 0.070f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.05f)
            .v (PID::macroMemory, 0.10f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.24f).v (PID::memoryWobble, 0.03f)
            .v (PID::memoryAsymmetry, 0.0f)
            .v (PID::macroCharacter, 0.26f).v (PID::macroMotion, 0.05f)
            .v (PID::macroWorld, 0.08f).v (PID::macroWeight, 0.72f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.66f)
            .v (PID::weightCompress, 0.42f)
            .v (PID::retroEra, 0.50f).v (PID::retroAge, 0.18f)
            .v (PID::retroDrift, 0.03f).v (PID::retroWear, 0.04f)
            .v (PID::retroTone, -0.30f).v (PID::retroNoise, 0.05f)
            .v (PID::retroMix, 0.35f)
            .v (PID::fxFilterMode, ch::f2Lp).v (PID::fxFilterCutoff, 1800.0f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.08f)
            .v (PID::spaceSize, 0.12f).v (PID::spaceDecay, 0.35f)
            .v (PID::spaceFog, 0.12f).v (PID::spaceLight, -0.50f)
            .v (PID::spacePreDelay, 3.0f).v (PID::spaceMix, 0.05f)
            .v (PID::auraSize, 0.10f).v (PID::auraDistance, 0.06f)
            .v (PID::auraFog, 0.14f).v (PID::auraDecay, 0.08f)
            .v (PID::auraLight, -0.40f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.20f)
            .v (PID::patinaNoise, 0.04f).v (PID::patinaWear, 0.08f)
            .v (PID::synthWidth, 0.25f).v (PID::highWidth, 0.60f)
            .v (PID::lowMonoFreq, 360.0f)
            .v (PID::breathOn, 0.0f).v (PID::breathAmount, 0.0f)
            .route (srcTouch, PID::filterCutoff, 0.08f));

        add (out, Build ("Mano Cerrada", "DRUMS", "AGGRESSIVE",
                         "kick,punch,short,hard",
                         "A short kick: the deepest ladder sweep in the file, 220 ms of amp decay, and WEIGHT in SUB doing the rest.")
            .at (36, 1, 1.0f, 1.5)
            .chain ("FILTER,CRUSH,RETRO,GRAIN,SPACE,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::masterGain, -3.0f)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::voiceVariation, 0.06f).v (PID::driftAmount, 0.02f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.86f)
            .v (PID::oscAOctave, -1.0f).v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscAPhaseOffset, 0.25f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.16f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, 0.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.48f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.46f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.20f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.46f).v (PID::bodyTilt, 0.20f)
            .v (PID::densityAmount, 0.14f)
            .v (PID::preFilterDrive, 0.40f).v (PID::postSaturation, 0.30f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 140.0f).v (PID::filterResonance, 0.70f)
            .v (PID::filterDrive, 0.42f).v (PID::filterKeyTrack, 0.0f)
            .v (PID::filterEnvAmount, 0.82f).v (PID::filterVelAmount, 0.45f)
            .v (PID::ampAttack, 0.0006f).v (PID::ampDecay, 0.22f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.09f)
            .v (PID::ampVelocity, 0.60f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.030f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.02f)
            .v (PID::macroMemory, 0.08f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.20f).v (PID::memoryWobble, 0.02f)
            .v (PID::macroCharacter, 0.44f).v (PID::macroMotion, 0.06f)
            .v (PID::macroWorld, 0.08f).v (PID::macroWeight, 0.70f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.72f)
            .v (PID::weightCompress, 0.50f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.18f)
            .v (PID::crushBits, 14.0f).v (PID::crushRate, 30000.0f)
            .v (PID::crushDrive, 0.26f).v (PID::crushTone, 0.12f)
            .v (PID::crushMix, 0.25f)
            .v (PID::retroEra, 0.60f).v (PID::retroAge, 0.12f)
            .v (PID::retroDrift, 0.02f).v (PID::retroWear, 0.03f)
            .v (PID::retroTone, -0.18f).v (PID::retroNoise, 0.03f)
            .v (PID::retroMix, 0.30f)
            .v (PID::fxFilterCutoff, 3000.0f).v (PID::fxFilterDrive, 0.18f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.06f)
            .v (PID::spaceSize, 0.10f).v (PID::spaceDecay, 0.30f)
            .v (PID::spaceFog, 0.10f).v (PID::spaceLight, -0.35f)
            .v (PID::spacePreDelay, 2.0f).v (PID::spaceMix, 0.04f)
            .v (PID::auraSize, 0.08f).v (PID::auraDistance, 0.05f)
            .v (PID::auraFog, 0.12f).v (PID::auraDecay, 0.06f)
            .v (PID::auraLight, -0.30f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.12f)
            .v (PID::patinaNoise, 0.03f).v (PID::patinaWear, 0.06f)
            .v (PID::synthWidth, 0.20f).v (PID::highWidth, 0.55f)
            .v (PID::lowMonoFreq, 380.0f)
            .v (PID::breathOn, 0.0f).v (PID::breathAmount, 0.0f)
            .route (srcTouch, PID::preFilterDrive, 0.10f));

        add (out, Build ("Golpe Seco", "DRUMS", "MINIMAL",
                         "kick,reggaeton,dry,sub",
                         "A dry kick built to sit on top of a separate sub: the body shuts in 25 ms and the sub oscillator two octaves down is left running.")
            .at (36, 1, 1.0f, 1.8)
            .chain ("FILTER,RETRO,SPACE,CRUSH,REWIND,GRAIN")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::masterGain, -2.5f)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::voiceVariation, 0.04f).v (PID::driftAmount, 0.02f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.70f)
            .v (PID::oscAOctave, -1.0f).v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscAPhaseOffset, 0.25f)
            .v (PID::oscBLevel, 0.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.72f)
            .v (PID::subOctave, ch::subMinus2).v (PID::subHarmonics, 0.30f)
            .v (PID::noiseType, ch::nDark).v (PID::noiseLevel, 0.14f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.40f).v (PID::densityAmount, 0.10f)
            .v (PID::preFilterDrive, 0.24f).v (PID::postSaturation, 0.18f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 70.0f).v (PID::filterResonance, 0.34f)
            .v (PID::filterDrive, 0.20f).v (PID::filterKeyTrack, 0.0f)
            .v (PID::filterEnvAmount, 0.70f).v (PID::filterVelAmount, 0.35f)
            .v (PID::ampAttack, 0.0007f).v (PID::ampDecay, 0.50f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.14f)
            .v (PID::ampVelocity, 0.50f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.025f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.02f)
            .v (PID::macroMemory, 0.06f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.18f).v (PID::memoryWobble, 0.02f)
            .v (PID::macroCharacter, 0.22f).v (PID::macroMotion, 0.04f)
            .v (PID::macroWorld, 0.06f).v (PID::macroWeight, 0.78f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.58f)
            .v (PID::weightCompress, 0.46f)
            .v (PID::retroEra, 0.34f).v (PID::retroAge, 0.10f)
            .v (PID::retroDrift, 0.02f).v (PID::retroWear, 0.02f)
            .v (PID::retroTone, -0.22f).v (PID::retroNoise, 0.02f)
            .v (PID::retroMix, 0.22f)
            .v (PID::fxFilterMode, ch::f2Lp).v (PID::fxFilterCutoff, 1200.0f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.05f)
            .v (PID::spaceSize, 0.08f).v (PID::spaceDecay, 0.25f)
            .v (PID::spaceFog, 0.08f).v (PID::spaceLight, -0.55f)
            .v (PID::spacePreDelay, 2.0f).v (PID::spaceMix, 0.03f)
            .v (PID::auraSize, 0.06f).v (PID::auraDistance, 0.04f)
            .v (PID::auraFog, 0.10f).v (PID::auraDecay, 0.05f)
            .v (PID::auraLight, -0.45f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.24f)
            .v (PID::patinaNoise, 0.02f).v (PID::patinaWear, 0.05f)
            .v (PID::synthWidth, 0.15f).v (PID::highWidth, 0.50f)
            .v (PID::lowMonoFreq, 400.0f)
            .v (PID::breathOn, 0.0f).v (PID::breathAmount, 0.0f)
            .route (srcWheel, PID::subLevel, 0.12f));

        add (out, Build ("Diesel Piston", "DRUMS", "DIRTY",
                         "kick,drive,saturated,harmonics",
                         "A kick whose harmonics come from drive rather than from the oscillator: phase modulation, filter drive and EDGE saturation stacked on one sine.")
            .at (36, 1, 1.0f, 1.8)
            .chain ("CRUSH,FILTER,RETRO,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::masterGain, -4.0f)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::voiceVariation, 0.10f).v (PID::driftAmount, 0.04f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.80f)
            .v (PID::oscAOctave, -1.0f).v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscAPhaseOffset, 0.20f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.22f)
            .v (PID::oscBFine, -8.0f)
            .v (PID::oscPmAmount, 0.18f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.44f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.52f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.12f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.58f).v (PID::bodyTilt, 0.32f)
            .v (PID::densityAmount, 0.26f)
            .v (PID::preFilterDrive, 0.72f).v (PID::postSaturation, 0.52f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 180.0f).v (PID::filterResonance, 0.46f)
            .v (PID::filterDrive, 0.62f).v (PID::filterKeyTrack, 0.0f)
            .v (PID::filterEnvAmount, 0.60f).v (PID::filterVelAmount, 0.42f)
            .v (PID::ampAttack, 0.0008f).v (PID::ampDecay, 0.55f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.18f)
            .v (PID::ampVelocity, 0.52f)
            .v (PID::env1Attack, 0.0006f).v (PID::env1Decay, 0.045f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.03f)
            .v (PID::macroMemory, 0.24f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.46f).v (PID::memoryWobble, 0.06f)
            .v (PID::memoryAsymmetry, 0.10f)
            .v (PID::macroCharacter, 0.74f).v (PID::macroMotion, 0.10f)
            .v (PID::macroWorld, 0.14f).v (PID::macroWeight, 0.62f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.78f)
            .v (PID::weightCompress, 0.40f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.34f)
            .v (PID::crushBits, 9.0f).v (PID::crushRate, 14000.0f)
            .v (PID::crushJitter, 0.06f).v (PID::crushDrive, 0.42f)
            .v (PID::crushTone, -0.10f).v (PID::crushMix, 0.34f)
            .v (PID::retroEra, 0.28f).v (PID::retroAge, 0.40f)
            .v (PID::retroDrift, 0.06f).v (PID::retroWear, 0.14f)
            .v (PID::retroTone, -0.20f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.55f)
            .v (PID::fxFilterCutoff, 2600.0f).v (PID::fxFilterDrive, 0.30f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.14f)
            .v (PID::spaceSize, 0.18f).v (PID::spaceDecay, 0.50f)
            .v (PID::spaceFog, 0.18f).v (PID::spaceLight, -0.40f)
            .v (PID::spacePreDelay, 5.0f).v (PID::spaceMix, 0.08f)
            .v (PID::auraSize, 0.16f).v (PID::auraDistance, 0.10f)
            .v (PID::auraFog, 0.20f).v (PID::auraDecay, 0.12f)
            .v (PID::auraLight, -0.30f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.14f)
            .v (PID::patinaNoise, 0.08f).v (PID::patinaWear, 0.20f)
            .v (PID::synthWidth, 0.35f).v (PID::highWidth, 0.75f)
            .v (PID::lowMonoFreq, 320.0f)
            .v (PID::breathAmount, 0.06f)
            .route (srcTouch, PID::postSaturation, 0.14f)
            .route (srcOrganic, PID::preFilterDrive, 0.08f));

        // -- Snares.  A tuned body plus a noise layer; the noise carries
        //    the length and the body carries the tuning. -----------------

        add (out, Build ("Hammered Tin", "DRUMS", "DIRTY",
                         "snare,noise,bright,metal",
                         "A snare body tuned up a minor third with ring modulation on it and white noise carrying the length.")
            .at (38, 1, 1.0f, 1.8)
            .chain ("FILTER,SPACE,RETRO,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::voiceMode, ch::poly).v (PID::polyphony, 4.0f)
            .v (PID::voiceVariation, 0.28f).v (PID::driftAmount, 0.05f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.46f)
            .v (PID::oscASemi, 3.0f).v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.26f)
            .v (PID::oscBSemi, 10.0f).v (PID::oscBFine, 22.0f)
            .v (PID::oscRingMod, 0.34f)
            .v (PID::subLevel, 0.10f).v (PID::subHarmonics, 0.24f)
            .v (PID::noiseType, ch::nWhite).v (PID::noiseLevel, 0.78f)
            .v (PID::noiseAttackOnly, 0.25f)
            .v (PID::bodyAmount, 0.34f).v (PID::densityAmount, 0.18f)
            .v (PID::preFilterDrive, 0.30f).v (PID::postSaturation, 0.26f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 2600.0f).v (PID::filterResonance, 0.30f)
            .v (PID::filterDrive, 0.18f).v (PID::filterKeyTrack, 0.25f)
            .v (PID::filterEnvAmount, 0.40f).v (PID::filterVelAmount, 0.48f)
            .v (PID::ampAttack, 0.0006f).v (PID::ampDecay, 0.26f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.16f)
            .v (PID::ampVelocity, 0.60f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.06f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.04f)
            .v (PID::macroMemory, 0.22f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.42f).v (PID::memoryWobble, 0.07f)
            .v (PID::memoryAsymmetry, 0.18f)
            .v (PID::macroCharacter, 0.52f).v (PID::macroMotion, 0.14f)
            .v (PID::macroWorld, 0.30f).v (PID::macroWeight, 0.32f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.38f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.22f)
            .v (PID::crushBits, 12.0f).v (PID::crushRate, 26000.0f)
            .v (PID::crushTone, 0.16f).v (PID::crushMix, 0.34f)
            .v (PID::retroEra, 0.46f).v (PID::retroAge, 0.34f)
            .v (PID::retroDrift, 0.06f).v (PID::retroWear, 0.14f)
            .v (PID::retroTone, 0.04f).v (PID::retroNoise, 0.12f)
            .v (PID::retroMix, 0.55f)
            .v (PID::fxFilterMode, ch::f2Hp).v (PID::fxFilterCutoff, 260.0f)
            .v (PID::fxFilterRes, 0.10f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.26f)
            .v (PID::spaceSize, 0.28f).v (PID::spaceDecay, 0.90f)
            .v (PID::spaceFog, 0.26f).v (PID::spaceLight, 0.05f)
            .v (PID::spacePreDelay, 7.0f).v (PID::spaceMix, 0.20f)
            .v (PID::auraSize, 0.24f).v (PID::auraDistance, 0.16f)
            .v (PID::auraFog, 0.26f).v (PID::auraDecay, 0.18f)
            .v (PID::auraLight, 0.10f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.18f)
            .v (PID::patinaNoise, 0.12f).v (PID::patinaWear, 0.20f)
            .v (PID::synthWidth, 1.05f).v (PID::highWidth, 1.25f)
            .v (PID::lowMonoFreq, 260.0f)
            .v (PID::breathAmount, 0.10f)
            .route (srcOrganic, PID::filterCutoff, 0.12f)
            .route (srcTouch, PID::noiseLevel, 0.10f));

        add (out, Build ("Trampa de Alambre", "DRUMS", "COLD",
                         "snare,wire,long,noise",
                         "A long snare in which the wires are an AIR noise bed through a second band-pass, the tuned body kept under it.")
            .at (40, 1, 0.95f, 2.2)
            .chain ("RETRO,FILTER,SPACE,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::voiceMode, ch::poly).v (PID::polyphony, 4.0f)
            .v (PID::voiceVariation, 0.24f).v (PID::driftAmount, 0.04f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.34f)
            .v (PID::oscASemi, -2.0f).v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.18f)
            .v (PID::oscBSemi, 5.0f)
            .v (PID::subLevel, 0.08f)
            .v (PID::noiseType, ch::nAir).v (PID::noiseLevel, 0.86f)
            .v (PID::noiseAttackOnly, 0.10f)
            .v (PID::bodyAmount, 0.24f).v (PID::densityAmount, 0.16f)
            .v (PID::preFilterDrive, 0.16f).v (PID::postSaturation, 0.14f)
            .v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::hp)
            .v (PID::filterCutoff, 420.0f).v (PID::filterResonance, 0.20f)
            .v (PID::filterKeyTrack, 0.15f).v (PID::filterEnvAmount, 0.26f)
            .v (PID::filterVelAmount, 0.40f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Bp)
            .v (PID::filter2Cutoff, 3400.0f).v (PID::filter2Res, 0.36f)
            .v (PID::filter2Mix, 0.55f)
            .v (PID::ampAttack, 0.0008f).v (PID::ampDecay, 0.42f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.26f)
            .v (PID::ampVelocity, 0.58f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.08f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.05f)
            .v (PID::macroMemory, 0.18f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.38f).v (PID::memoryWobble, 0.06f)
            .v (PID::memoryAsymmetry, 0.20f)
            .v (PID::macroCharacter, 0.36f).v (PID::macroMotion, 0.18f)
            .v (PID::macroWorld, 0.38f).v (PID::macroWeight, 0.26f)
            .v (PID::weightMode, ch::wAir).v (PID::weightHarmonics, 0.34f)
            .v (PID::retroEra, 0.40f).v (PID::retroAge, 0.26f)
            .v (PID::retroDrift, 0.05f).v (PID::retroWear, 0.10f)
            .v (PID::retroTone, 0.10f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.48f)
            .v (PID::fxFilterMode, ch::f2Hp).v (PID::fxFilterCutoff, 300.0f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.34f)
            .v (PID::spaceSize, 0.38f).v (PID::spaceDecay, 1.40f)
            .v (PID::spaceFog, 0.34f).v (PID::spaceLight, 0.12f)
            .v (PID::spacePreDelay, 12.0f).v (PID::spaceMix, 0.26f)
            .v (PID::auraSize, 0.32f).v (PID::auraDistance, 0.22f)
            .v (PID::auraFog, 0.30f).v (PID::auraDecay, 0.24f)
            .v (PID::auraLight, 0.16f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, 0.06f)
            .v (PID::patinaNoise, 0.14f).v (PID::patinaWear, 0.22f)
            .v (PID::synthWidth, 1.10f).v (PID::highWidth, 1.30f)
            .v (PID::lowMonoFreq, 280.0f)
            .v (PID::breathAmount, 0.14f)
            .route (srcBreath, PID::filter2Cutoff, 0.14f)
            .route (srcOrganic, PID::noiseLevel, 0.08f));

        add (out, Build ("Tabla de Pino", "DRUMS", "WARM",
                         "snare,wood,body,pm",
                         "A snare body tuned down a fourth with a HOLLOW wavetable phase-modulating it, pink noise across the middle of the decay.")
            .at (38, 1, 1.0f, 1.8)
            .chain ("FILTER,RETRO,CRUSH,SPACE,REWIND,GRAIN")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::poly).v (PID::polyphony, 4.0f)
            .v (PID::voiceVariation, 0.20f).v (PID::driftAmount, 0.05f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.56f)
            .v (PID::oscASemi, -5.0f).v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscAPhaseOffset, 0.10f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tHollow)
            .v (PID::oscBWtPos, 0.35f).v (PID::oscBLevel, 0.30f)
            .v (PID::oscBSemi, 7.0f)
            .v (PID::oscPmAmount, 0.34f)
            .v (PID::subLevel, 0.16f).v (PID::subHarmonics, 0.28f)
            .v (PID::noiseType, ch::nPink).v (PID::noiseLevel, 0.52f)
            .v (PID::noiseAttackOnly, 0.45f)
            .v (PID::bodyAmount, 0.52f).v (PID::bodyTilt, -0.18f)
            .v (PID::densityAmount, 0.22f)
            .v (PID::preFilterDrive, 0.24f).v (PID::postSaturation, 0.20f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 1100.0f).v (PID::filterResonance, 0.34f)
            .v (PID::filterDrive, 0.24f).v (PID::filterKeyTrack, 0.30f)
            .v (PID::filterEnvAmount, 0.46f).v (PID::filterVelAmount, 0.46f)
            .v (PID::ampAttack, 0.0006f).v (PID::ampDecay, 0.24f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.14f)
            .v (PID::ampVelocity, 0.58f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.05f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.035f)
            .v (PID::macroMemory, 0.26f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.50f).v (PID::memoryWobble, 0.08f)
            .v (PID::memoryAsymmetry, 0.14f)
            .v (PID::macroCharacter, 0.46f).v (PID::macroMotion, 0.12f)
            .v (PID::macroWorld, 0.26f).v (PID::macroWeight, 0.40f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.44f)
            .v (PID::weightCompress, 0.30f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.16f)
            .v (PID::crushBits, 13.0f).v (PID::crushRate, 28000.0f)
            .v (PID::crushMix, 0.22f)
            .v (PID::retroEra, 0.30f).v (PID::retroAge, 0.36f)
            .v (PID::retroDrift, 0.06f).v (PID::retroWear, 0.12f)
            .v (PID::retroTone, -0.16f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.58f)
            .v (PID::fxFilterCutoff, 7000.0f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.22f)
            .v (PID::spaceSize, 0.26f).v (PID::spaceDecay, 0.80f)
            .v (PID::spaceFog, 0.24f).v (PID::spaceLight, -0.12f)
            .v (PID::spacePreDelay, 8.0f).v (PID::spaceMix, 0.18f)
            .v (PID::auraSize, 0.22f).v (PID::auraDistance, 0.14f)
            .v (PID::auraFog, 0.26f).v (PID::auraDecay, 0.16f)
            .v (PID::auraLight, -0.10f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.08f)
            .v (PID::patinaNoise, 0.12f).v (PID::patinaWear, 0.24f)
            .v (PID::synthWidth, 0.90f).v (PID::highWidth, 1.05f)
            .v (PID::lowMonoFreq, 250.0f)
            .v (PID::breathAmount, 0.10f)
            .route (srcTouch, PID::oscPmAmount, 0.12f));

        // -- Claps.  Noise through a band-pass; the several-hands quality
        //    is the attack shape and a short room, not one envelope. -----

        add (out, Build ("Palmas de Sala", "DRUMS", "INTIMATE",
                         "clap,noise,room,hands",
                         "Noise only, through the FORMANT band-pass, with a 12 ms attack, high voice variation and a small room instead of a second envelope.")
            .at (39, 1, 0.95f, 1.8)
            .chain ("FILTER,SPACE,RETRO,CRUSH,REWIND,GRAIN")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::voiceMode, ch::poly).v (PID::polyphony, 6.0f)
            .v (PID::voiceVariation, 0.40f).v (PID::driftAmount, 0.06f)
            .v (PID::oscALevel, 0.0f).v (PID::oscBLevel, 0.0f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nWhite).v (PID::noiseLevel, 0.92f)
            .v (PID::noiseAttackOnly, 0.0f)
            .v (PID::bodyAmount, 0.14f).v (PID::densityAmount, 0.24f)
            .v (PID::preFilterDrive, 0.20f).v (PID::postSaturation, 0.18f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 1500.0f).v (PID::filterResonance, 0.46f)
            .v (PID::filterDrive, 0.16f).v (PID::filterKeyTrack, 0.10f)
            .v (PID::filterEnvAmount, 0.34f).v (PID::filterVelAmount, 0.42f)
            .v (PID::ampAttack, 0.012f).v (PID::ampDecay, 0.20f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.13f)
            .v (PID::ampVelocity, 0.55f)
            .v (PID::env1Attack, 0.0008f).v (PID::env1Decay, 0.045f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.03f)
            .v (PID::macroMemory, 0.20f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.40f).v (PID::memoryWobble, 0.05f)
            .v (PID::memoryAsymmetry, 0.22f)
            .v (PID::macroCharacter, 0.42f).v (PID::macroMotion, 0.16f)
            .v (PID::macroWorld, 0.34f).v (PID::macroWeight, 0.22f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.30f)
            .v (PID::retroEra, 0.38f).v (PID::retroAge, 0.28f)
            .v (PID::retroDrift, 0.05f).v (PID::retroWear, 0.10f)
            .v (PID::retroTone, 0.06f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.46f)
            .v (PID::fxFilterMode, ch::f2Hp).v (PID::fxFilterCutoff, 340.0f)
            .v (PID::fxFilterRes, 0.08f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.30f)
            .v (PID::spaceSize, 0.22f).v (PID::spaceDecay, 0.55f)
            .v (PID::spaceFog, 0.30f).v (PID::spaceLight, 0.02f)
            .v (PID::spacePreDelay, 9.0f).v (PID::spaceMix, 0.28f)
            .v (PID::auraSize, 0.22f).v (PID::auraDistance, 0.20f)
            .v (PID::auraFog, 0.28f).v (PID::auraDecay, 0.16f)
            .v (PID::auraLight, 0.06f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, 0.0f)
            .v (PID::patinaNoise, 0.12f).v (PID::patinaWear, 0.18f)
            .v (PID::synthWidth, 1.10f).v (PID::highWidth, 1.25f)
            .v (PID::lowMonoFreq, 300.0f)
            .v (PID::breathAmount, 0.12f)
            .route (srcOrganic, PID::filterCutoff, 0.16f)
            .route (srcTouch, PID::spaceMix, 0.10f));

        add (out, Build ("Six Hands", "DRUMS", "COLD",
                         "clap,wide,comb,grain",
                         "A clap made of digital noise, a comb at 74 Hz and percussive grains, spread wide and collapsed to centre below 320 Hz.")
            .at (39, 1, 0.90f, 2.0)
            .chain ("FILTER,GRAIN,SPACE,RETRO,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::voiceMode, ch::poly).v (PID::polyphony, 8.0f)
            .v (PID::voiceVariation, 0.46f).v (PID::driftAmount, 0.05f)
            .v (PID::oscALevel, 0.0f).v (PID::oscBLevel, 0.0f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nDigital).v (PID::noiseLevel, 0.88f)
            .v (PID::noiseAttackOnly, 0.0f)
            .v (PID::bodyAmount, 0.10f).v (PID::densityAmount, 0.20f)
            .v (PID::preFilterDrive, 0.14f).v (PID::postSaturation, 0.12f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 1900.0f).v (PID::filterResonance, 0.40f)
            .v (PID::filterKeyTrack, 0.08f).v (PID::filterEnvAmount, 0.30f)
            .v (PID::filterVelAmount, 0.40f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Comb)
            .v (PID::filter2Cutoff, 74.0f).v (PID::filter2Res, 0.52f)
            .v (PID::filter2Mix, 0.46f)
            .v (PID::ampAttack, 0.008f).v (PID::ampDecay, 0.24f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.18f)
            .v (PID::ampVelocity, 0.50f)
            .v (PID::env1Attack, 0.0008f).v (PID::env1Decay, 0.04f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.03f)
            .v (PID::macroMemory, 0.16f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.34f).v (PID::memoryWobble, 0.06f)
            .v (PID::memoryAsymmetry, 0.30f)
            .v (PID::macroCharacter, 0.36f).v (PID::macroMotion, 0.22f)
            .v (PID::macroWorld, 0.42f).v (PID::macroWeight, 0.20f)
            .v (PID::weightMode, ch::wAir).v (PID::weightHarmonics, 0.28f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.28f)
            .v (PID::grainSize, 22.0f).v (PID::grainDensity, 34.0f)
            .v (PID::grainPosition, 0.10f).v (PID::grainPitchMode, ch::gRoot)
            .v (PID::grainSpread, 0.72f).v (PID::grainJitter, 0.42f)
            .v (PID::grainDirection, 0.0f).v (PID::grainWindow, ch::wPercussive)
            .v (PID::grainMix, 0.30f)
            .v (PID::retroEra, 0.66f).v (PID::retroAge, 0.16f)
            .v (PID::retroDrift, 0.04f).v (PID::retroWear, 0.06f)
            .v (PID::retroTone, 0.20f).v (PID::retroNoise, 0.06f)
            .v (PID::retroMix, 0.30f)
            .v (PID::fxFilterMode, ch::f2Hp).v (PID::fxFilterCutoff, 400.0f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.32f)
            .v (PID::spaceSize, 0.30f).v (PID::spaceDecay, 0.90f)
            .v (PID::spaceFog, 0.34f).v (PID::spaceLight, 0.18f)
            .v (PID::spacePreDelay, 14.0f).v (PID::spaceMix, 0.24f)
            .v (PID::auraSize, 0.28f).v (PID::auraDistance, 0.20f)
            .v (PID::auraFog, 0.26f).v (PID::auraDecay, 0.20f)
            .v (PID::auraLight, 0.24f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.22f)
            .v (PID::patinaNoise, 0.08f).v (PID::patinaWear, 0.14f)
            .v (PID::synthWidth, 1.35f).v (PID::highWidth, 1.50f)
            .v (PID::lowMonoFreq, 320.0f)
            .v (PID::lfo1Shape, ch::lfoRandom).v (PID::lfo1Rate, 6.0f)
            .v (PID::lfo1Depth, 0.35f)
            .v (PID::breathAmount, 0.12f)
            .route (srcLfo1, PID::grainPosition, 0.12f)
            .route (srcOrganic, PID::grainJitter, 0.16f));

        // -- Rimshots and sidesticks.  Very short, very tuned. -----------

        add (out, Build ("Aro de Acero", "DRUMS", "AGGRESSIVE",
                         "rimshot,short,tuned,transient",
                         "A rimshot: a narrow pulse and a sine ring-modulated through the COMB filter, 55 ms of amp decay and no sub at all.")
            .at (37, 1, 1.0f, 1.5)
            .chain ("FILTER,CRUSH,SPACE,RETRO,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::voiceMode, ch::poly).v (PID::polyphony, 4.0f)
            .v (PID::voiceVariation, 0.18f).v (PID::driftAmount, 0.03f)
            .v (PID::oscAWave, ch::square).v (PID::oscALevel, 0.42f)
            .v (PID::oscAPulseWidth, 0.12f).v (PID::oscASemi, 7.0f)
            .v (PID::oscAPhase, ch::phaseReset).v (PID::oscAPhaseOffset, 0.0f)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.30f)
            .v (PID::oscBSemi, -5.0f).v (PID::oscBFine, 14.0f)
            .v (PID::oscRingMod, 0.52f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.30f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.16f).v (PID::densityAmount, 0.10f)
            .v (PID::preFilterDrive, 0.26f).v (PID::postSaturation, 0.22f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 1800.0f).v (PID::filterResonance, 0.56f)
            .v (PID::filterDrive, 0.22f).v (PID::filterKeyTrack, 0.60f)
            .v (PID::filterEnvAmount, 0.52f).v (PID::filterVelAmount, 0.45f)
            .v (PID::ampAttack, 0.0005f).v (PID::ampDecay, 0.055f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.035f)
            .v (PID::ampVelocity, 0.62f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.012f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.01f)
            .v (PID::macroMemory, 0.10f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.22f).v (PID::memoryWobble, 0.03f)
            .v (PID::macroCharacter, 0.40f).v (PID::macroMotion, 0.08f)
            .v (PID::macroWorld, 0.20f).v (PID::macroWeight, 0.24f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.32f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.26f)
            .v (PID::crushBits, 11.0f).v (PID::crushRate, 24000.0f)
            .v (PID::crushDrive, 0.22f).v (PID::crushTone, 0.22f)
            .v (PID::crushMix, 0.36f)
            .v (PID::retroEra, 0.72f).v (PID::retroAge, 0.12f)
            .v (PID::retroDrift, 0.03f).v (PID::retroWear, 0.04f)
            .v (PID::retroTone, 0.18f).v (PID::retroNoise, 0.04f)
            .v (PID::retroMix, 0.28f)
            .v (PID::fxFilterMode, ch::f2Hp).v (PID::fxFilterCutoff, 500.0f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.18f)
            .v (PID::spaceSize, 0.16f).v (PID::spaceDecay, 0.40f)
            .v (PID::spaceFog, 0.16f).v (PID::spaceLight, 0.22f)
            .v (PID::spacePreDelay, 4.0f).v (PID::spaceMix, 0.12f)
            .v (PID::auraSize, 0.16f).v (PID::auraDistance, 0.10f)
            .v (PID::auraFog, 0.16f).v (PID::auraDecay, 0.10f)
            .v (PID::auraLight, 0.26f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.26f)
            .v (PID::patinaNoise, 0.05f).v (PID::patinaWear, 0.10f)
            .v (PID::synthWidth, 0.95f).v (PID::highWidth, 1.15f)
            .v (PID::lowMonoFreq, 300.0f)
            .v (PID::breathOn, 0.0f).v (PID::breathAmount, 0.0f)
            .route (srcTouch, PID::filterCutoff, 0.12f));

        add (out, Build ("Nail Head", "DRUMS", "MINIMAL",
                         "sidestick,click,short,dry",
                         "A sidestick: a triangle an octave up through a resonant MASS band-pass at 80 percent key track, 35 ms long, no sub.")
            .at (37, 1, 0.85f, 1.5)
            .chain ("FILTER,RETRO,SPACE,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::poly).v (PID::polyphony, 4.0f)
            .v (PID::voiceVariation, 0.14f).v (PID::driftAmount, 0.02f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.50f)
            .v (PID::oscASemi, 12.0f).v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscAPhaseOffset, 0.0f)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.22f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBSemi, 3.0f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.22f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.12f).v (PID::densityAmount, 0.08f)
            .v (PID::preFilterDrive, 0.18f).v (PID::postSaturation, 0.12f)
            .v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 2400.0f).v (PID::filterResonance, 0.62f)
            .v (PID::filterDrive, 0.18f).v (PID::filterKeyTrack, 0.80f)
            .v (PID::filterEnvAmount, 0.58f).v (PID::filterVelAmount, 0.40f)
            .v (PID::ampAttack, 0.0005f).v (PID::ampDecay, 0.035f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.025f)
            .v (PID::ampVelocity, 0.58f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.008f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.006f)
            .v (PID::macroMemory, 0.08f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.18f).v (PID::memoryWobble, 0.02f)
            .v (PID::macroCharacter, 0.24f).v (PID::macroMotion, 0.06f)
            .v (PID::macroWorld, 0.16f).v (PID::macroWeight, 0.18f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.26f)
            .v (PID::retroEra, 0.42f).v (PID::retroAge, 0.14f)
            .v (PID::retroDrift, 0.02f).v (PID::retroWear, 0.04f)
            .v (PID::retroTone, -0.06f).v (PID::retroNoise, 0.04f)
            .v (PID::retroMix, 0.26f)
            .v (PID::fxFilterMode, ch::f2Hp).v (PID::fxFilterCutoff, 380.0f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.16f)
            .v (PID::spaceSize, 0.12f).v (PID::spaceDecay, 0.30f)
            .v (PID::spaceFog, 0.14f).v (PID::spaceLight, 0.0f)
            .v (PID::spacePreDelay, 3.0f).v (PID::spaceMix, 0.10f)
            .v (PID::auraSize, 0.12f).v (PID::auraDistance, 0.08f)
            .v (PID::auraFog, 0.14f).v (PID::auraDecay, 0.08f)
            .v (PID::auraLight, 0.0f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.04f)
            .v (PID::patinaNoise, 0.04f).v (PID::patinaWear, 0.08f)
            .v (PID::synthWidth, 0.75f).v (PID::highWidth, 0.95f)
            .v (PID::lowMonoFreq, 300.0f)
            .v (PID::breathOn, 0.0f).v (PID::breathAmount, 0.0f)
            .route (srcWheel, PID::filterCutoff, 0.10f));

        // -- Hats and cymbals.  High-passed noise and the METALLIC table;
        //    the open and closed pair differ in decay, not in recipe. ----

        add (out, Build ("Pressed Foil", "DRUMS", "COLD",
                         "hat,closed,noise,tight",
                         "A closed hat: white noise and the METALLIC table high-passed at 7.2 kHz, the transient made by a negative filter envelope.")
            .at (42, 1, 0.90f, 1.5)
            .chain ("FILTER,CRUSH,RETRO,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::voiceMode, ch::poly).v (PID::polyphony, 6.0f)
            .v (PID::voiceVariation, 0.22f).v (PID::driftAmount, 0.03f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tMetal)
            .v (PID::oscAWtPos, 0.62f).v (PID::oscALevel, 0.22f)
            .v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBLevel, 0.0f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nWhite).v (PID::noiseLevel, 0.72f)
            .v (PID::noiseAttackOnly, 0.30f)
            .v (PID::bodyAmount, 0.04f).v (PID::densityAmount, 0.06f)
            .v (PID::postSaturation, 0.10f).v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::hp)
            .v (PID::filterCutoff, 7200.0f).v (PID::filterResonance, 0.18f)
            .v (PID::filterKeyTrack, 0.20f).v (PID::filterEnvAmount, -0.30f)
            .v (PID::filterVelAmount, 0.45f)
            .v (PID::ampAttack, 0.0005f).v (PID::ampDecay, 0.075f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.04f)
            .v (PID::ampVelocity, 0.66f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.018f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.012f)
            .v (PID::macroMemory, 0.08f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.14f).v (PID::memoryWobble, 0.03f)
            .v (PID::macroCharacter, 0.28f).v (PID::macroMotion, 0.10f)
            .v (PID::macroWorld, 0.22f).v (PID::macroWeight, 0.20f)
            .v (PID::weightMode, ch::wAir).v (PID::weightHarmonics, 0.46f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.24f)
            .v (PID::crushBits, 12.0f).v (PID::crushRate, 28000.0f)
            .v (PID::crushTone, 0.30f).v (PID::crushMix, 0.34f)
            .v (PID::retroEra, 0.86f).v (PID::retroAge, 0.08f)
            .v (PID::retroDrift, 0.03f).v (PID::retroWear, 0.03f)
            .v (PID::retroTone, 0.26f).v (PID::retroNoise, 0.03f)
            .v (PID::retroMix, 0.24f)
            .v (PID::fxFilterMode, ch::f2Hp).v (PID::fxFilterCutoff, 4200.0f)
            .v (PID::fxFilterRes, 0.08f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.18f)
            .v (PID::spaceSize, 0.16f).v (PID::spaceDecay, 0.40f)
            .v (PID::spaceFog, 0.14f).v (PID::spaceLight, 0.44f)
            .v (PID::spacePreDelay, 4.0f).v (PID::spaceMix, 0.12f)
            .v (PID::auraSize, 0.16f).v (PID::auraDistance, 0.10f)
            .v (PID::auraFog, 0.14f).v (PID::auraDecay, 0.10f)
            .v (PID::auraLight, 0.44f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.34f)
            .v (PID::patinaNoise, 0.06f).v (PID::patinaWear, 0.12f)
            .v (PID::synthWidth, 1.10f).v (PID::highWidth, 1.35f)
            .v (PID::lowMonoFreq, 320.0f)
            .v (PID::breathAmount, 0.08f)
            .route (srcOrganic, PID::filterCutoff, 0.10f));

        add (out, Build ("Loose Foil", "DRUMS", "DIRTY",
                         "hat,open,long,metal",
                         "The open version of the same recipe: METALLIC table and a 5.2 kHz high-pass, 620 ms of decay, crushed before the chain filter.")
            .at (46, 1, 0.90f, 2.2)
            .chain ("CRUSH,FILTER,SPACE,RETRO,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::voiceMode, ch::poly).v (PID::polyphony, 6.0f)
            .v (PID::voiceVariation, 0.30f).v (PID::driftAmount, 0.05f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tMetal)
            .v (PID::oscAWtPos, 0.34f).v (PID::oscALevel, 0.34f)
            .v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::square).v (PID::oscBLevel, 0.18f)
            .v (PID::oscBPulseWidth, 0.26f).v (PID::oscBSemi, 8.0f)
            .v (PID::oscRingMod, 0.30f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nAir).v (PID::noiseLevel, 0.66f)
            .v (PID::noiseAttackOnly, 0.10f)
            .v (PID::bodyAmount, 0.06f).v (PID::densityAmount, 0.12f)
            .v (PID::preFilterDrive, 0.14f).v (PID::postSaturation, 0.16f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::hp)
            .v (PID::filterCutoff, 5200.0f).v (PID::filterResonance, 0.24f)
            .v (PID::filterKeyTrack, 0.25f).v (PID::filterEnvAmount, 0.22f)
            .v (PID::filterVelAmount, 0.42f)
            .v (PID::ampAttack, 0.0006f).v (PID::ampDecay, 0.62f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.32f)
            .v (PID::ampVelocity, 0.60f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.045f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.03f)
            .v (PID::macroMemory, 0.18f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.30f).v (PID::memoryWobble, 0.06f)
            .v (PID::memoryAsymmetry, 0.22f)
            .v (PID::macroCharacter, 0.44f).v (PID::macroMotion, 0.18f)
            .v (PID::macroWorld, 0.30f).v (PID::macroWeight, 0.22f)
            .v (PID::weightMode, ch::wAir).v (PID::weightHarmonics, 0.48f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.34f)
            .v (PID::crushBits, 10.0f).v (PID::crushRate, 20000.0f)
            .v (PID::crushJitter, 0.08f).v (PID::crushDrive, 0.24f)
            .v (PID::crushTone, 0.24f).v (PID::crushMix, 0.42f)
            .v (PID::retroEra, 0.62f).v (PID::retroAge, 0.30f)
            .v (PID::retroDrift, 0.06f).v (PID::retroWear, 0.12f)
            .v (PID::retroTone, 0.18f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.44f)
            .v (PID::fxFilterMode, ch::f2Hp).v (PID::fxFilterCutoff, 3000.0f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.24f)
            .v (PID::spaceSize, 0.26f).v (PID::spaceDecay, 0.80f)
            .v (PID::spaceFog, 0.22f).v (PID::spaceLight, 0.40f)
            .v (PID::spacePreDelay, 6.0f).v (PID::spaceMix, 0.16f)
            .v (PID::auraSize, 0.22f).v (PID::auraDistance, 0.14f)
            .v (PID::auraFog, 0.18f).v (PID::auraDecay, 0.16f)
            .v (PID::auraLight, 0.40f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.28f)
            .v (PID::patinaNoise, 0.10f).v (PID::patinaWear, 0.20f)
            .v (PID::synthWidth, 1.20f).v (PID::highWidth, 1.40f)
            .v (PID::lowMonoFreq, 320.0f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 3.5f)
            .v (PID::lfo2Depth, 0.30f)
            .v (PID::breathAmount, 0.12f)
            .route (srcOrganic, PID::oscAWtPos, 0.22f)
            .route (srcLfo2, PID::filterCutoff, 0.08f));

        add (out, Build ("Platillo de Bronce", "DRUMS", "HAUNTED",
                         "cymbal,metal,ring,long",
                         "A cymbal from two wavetables ring-modulated at 62 percent, grains laid over the tail, nothing asked of the low end.")
            .at (45, 1, 0.88f, 2.5)
            .chain ("FILTER,SPACE,GRAIN,RETRO,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::voiceMode, ch::poly).v (PID::polyphony, 6.0f)
            .v (PID::voiceVariation, 0.34f).v (PID::driftAmount, 0.06f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tMetal)
            .v (PID::oscAWtPos, 0.18f).v (PID::oscALevel, 0.46f)
            .v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tSpectral)
            .v (PID::oscBWtPos, 0.66f).v (PID::oscBLevel, 0.30f)
            .v (PID::oscBSemi, 11.0f).v (PID::oscBFine, -26.0f)
            .v (PID::oscRingMod, 0.62f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nDigital).v (PID::noiseLevel, 0.34f)
            .v (PID::noiseAttackOnly, 0.15f)
            .v (PID::bodyAmount, 0.08f).v (PID::densityAmount, 0.18f)
            .v (PID::postSaturation, 0.14f).v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 3800.0f).v (PID::filterResonance, 0.38f)
            .v (PID::filterKeyTrack, 0.30f).v (PID::filterEnvAmount, 0.28f)
            .v (PID::filterVelAmount, 0.38f)
            .v (PID::ampAttack, 0.0008f).v (PID::ampDecay, 1.30f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.70f)
            .v (PID::ampVelocity, 0.55f)
            .v (PID::env1Attack, 0.0006f).v (PID::env1Decay, 0.09f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.06f)
            .v (PID::macroMemory, 0.24f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.34f).v (PID::memoryWobble, 0.08f)
            .v (PID::memoryAsymmetry, 0.30f)
            .v (PID::macroCharacter, 0.40f).v (PID::macroMotion, 0.26f)
            .v (PID::macroWorld, 0.46f).v (PID::macroWeight, 0.20f)
            .v (PID::weightMode, ch::wAir).v (PID::weightHarmonics, 0.42f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.22f)
            .v (PID::grainSize, 40.0f).v (PID::grainDensity, 20.0f)
            .v (PID::grainPosition, 0.20f).v (PID::grainPitchMode, ch::gOctave)
            .v (PID::grainSpread, 0.70f).v (PID::grainJitter, 0.36f)
            .v (PID::grainDirection, 0.10f).v (PID::grainWindow, ch::wExpo)
            .v (PID::grainMix, 0.24f)
            .v (PID::retroEra, 0.70f).v (PID::retroAge, 0.22f)
            .v (PID::retroDrift, 0.06f).v (PID::retroWear, 0.08f)
            .v (PID::retroTone, 0.22f).v (PID::retroNoise, 0.08f)
            .v (PID::retroMix, 0.32f)
            .v (PID::fxFilterMode, ch::f2Hp).v (PID::fxFilterCutoff, 2200.0f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.40f)
            .v (PID::spaceSize, 0.46f).v (PID::spaceDecay, 2.40f)
            .v (PID::spaceFog, 0.40f).v (PID::spaceLight, 0.34f)
            .v (PID::spacePreDelay, 16.0f).v (PID::spaceMix, 0.30f)
            .v (PID::auraSize, 0.42f).v (PID::auraDistance, 0.28f)
            .v (PID::auraFog, 0.34f).v (PID::auraDecay, 0.34f)
            .v (PID::auraLight, 0.38f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.30f)
            .v (PID::patinaNoise, 0.10f).v (PID::patinaWear, 0.18f)
            .v (PID::synthWidth, 1.30f).v (PID::highWidth, 1.45f)
            .v (PID::lowMonoFreq, 300.0f)
            .v (PID::breathAmount, 0.16f)
            .route (srcBreath, PID::oscBWtPos, 0.20f)
            .route (srcOrganic, PID::oscRingMod, 0.10f));

        // -- Toms.  A sweep shallower than a kick's, over a longer body. --

        add (out, Build ("Tambor de Aceite", "DRUMS", "CINEMATIC",
                         "tom,low,body,long",
                         "A floor tom with a sweep shallower than any kick in this file and a body that runs past a second, in a chamber.")
            .at (43, 1, 1.0f, 2.5)
            .chain ("FILTER,RETRO,SPACE,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::poly).v (PID::polyphony, 4.0f)
            .v (PID::voiceVariation, 0.24f).v (PID::driftAmount, 0.07f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.74f)
            .v (PID::oscAPhase, ch::phaseReset).v (PID::oscAPhaseOffset, 0.25f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.28f)
            .v (PID::oscBSemi, 7.0f).v (PID::oscBFine, -16.0f)
            .v (PID::subWave, ch::subTri).v (PID::subLevel, 0.34f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.32f)
            .v (PID::noiseType, ch::nDark).v (PID::noiseLevel, 0.22f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.66f).v (PID::bodyTilt, -0.26f)
            .v (PID::densityAmount, 0.26f)
            .v (PID::preFilterDrive, 0.26f).v (PID::postSaturation, 0.22f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 520.0f).v (PID::filterResonance, 0.38f)
            .v (PID::filterDrive, 0.26f).v (PID::filterKeyTrack, 0.45f)
            .v (PID::filterEnvAmount, 0.34f).v (PID::filterVelAmount, 0.48f)
            .v (PID::ampAttack, 0.001f).v (PID::ampDecay, 1.10f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.42f)
            .v (PID::ampVelocity, 0.56f)
            .v (PID::env1Attack, 0.0008f).v (PID::env1Decay, 0.16f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.10f)
            .v (PID::macroMemory, 0.28f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.52f).v (PID::memoryWobble, 0.08f)
            .v (PID::memoryAsymmetry, 0.16f)
            .v (PID::macroCharacter, 0.44f).v (PID::macroMotion, 0.16f)
            .v (PID::macroWorld, 0.42f).v (PID::macroWeight, 0.54f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.46f)
            .v (PID::weightCompress, 0.32f)
            .v (PID::retroEra, 0.26f).v (PID::retroAge, 0.36f)
            .v (PID::retroDrift, 0.07f).v (PID::retroWear, 0.14f)
            .v (PID::retroTone, -0.30f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.58f)
            .v (PID::fxFilterCutoff, 2800.0f).v (PID::fxFilterDrive, 0.14f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.40f)
            .v (PID::spaceSize, 0.50f).v (PID::spaceDecay, 2.20f)
            .v (PID::spaceFog, 0.40f).v (PID::spaceLight, -0.34f)
            .v (PID::spacePreDelay, 14.0f).v (PID::spaceMix, 0.24f)
            .v (PID::auraSize, 0.40f).v (PID::auraDistance, 0.24f)
            .v (PID::auraFog, 0.36f).v (PID::auraDecay, 0.30f)
            .v (PID::auraLight, -0.30f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.22f)
            .v (PID::patinaNoise, 0.12f).v (PID::patinaWear, 0.26f)
            .v (PID::synthWidth, 0.85f).v (PID::highWidth, 1.00f)
            .v (PID::lowMonoFreq, 250.0f)
            .v (PID::breathAmount, 0.12f)
            .route (srcTouch, PID::filterCutoff, 0.12f)
            .route (srcOrganic, PID::oscBFine, 0.08f));

        add (out, Build ("Golpe Hueco", "DRUMS", "NOSTALGIC",
                         "tom,hollow,comb,mid",
                         "A mid tom through the COMB filter at full key tracking, a HOLLOW wavetable under the sine and RETRO ahead of everything.")
            .at (47, 1, 0.95f, 2.2)
            .chain ("RETRO,FILTER,CRUSH,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::voiceMode, ch::poly).v (PID::polyphony, 4.0f)
            .v (PID::voiceVariation, 0.26f).v (PID::driftAmount, 0.06f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.66f)
            .v (PID::oscAPhase, ch::phaseReset).v (PID::oscAPhaseOffset, 0.25f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tHollow)
            .v (PID::oscBWtPos, 0.44f).v (PID::oscBLevel, 0.32f)
            .v (PID::oscBSemi, 5.0f)
            .v (PID::subLevel, 0.22f).v (PID::subHarmonics, 0.26f)
            .v (PID::noiseType, ch::nPink).v (PID::noiseLevel, 0.20f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.54f).v (PID::bodyTilt, -0.10f)
            .v (PID::densityAmount, 0.24f)
            .v (PID::preFilterDrive, 0.22f).v (PID::postSaturation, 0.18f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 760.0f).v (PID::filterResonance, 0.48f)
            .v (PID::filterDrive, 0.20f).v (PID::filterKeyTrack, 1.0f)
            .v (PID::filterEnvAmount, 0.36f).v (PID::filterVelAmount, 0.46f)
            .v (PID::ampAttack, 0.0009f).v (PID::ampDecay, 0.78f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.30f)
            .v (PID::ampVelocity, 0.56f)
            .v (PID::env1Attack, 0.0007f).v (PID::env1Decay, 0.12f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.08f)
            .v (PID::macroMemory, 0.32f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.56f).v (PID::memoryWobble, 0.10f)
            .v (PID::memoryAsymmetry, 0.18f)
            .v (PID::macroCharacter, 0.42f).v (PID::macroMotion, 0.18f)
            .v (PID::macroWorld, 0.36f).v (PID::macroWeight, 0.44f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.40f)
            .v (PID::weightCompress, 0.28f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.20f)
            .v (PID::crushBits, 12.0f).v (PID::crushRate, 24000.0f)
            .v (PID::crushTone, -0.06f).v (PID::crushMix, 0.28f)
            .v (PID::retroEra, 0.24f).v (PID::retroAge, 0.44f)
            .v (PID::retroDrift, 0.10f).v (PID::retroWear, 0.18f)
            .v (PID::retroTone, -0.24f).v (PID::retroNoise, 0.14f)
            .v (PID::retroMix, 0.62f)
            .v (PID::fxFilterCutoff, 4200.0f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.34f)
            .v (PID::spaceSize, 0.40f).v (PID::spaceDecay, 1.60f)
            .v (PID::spaceFog, 0.34f).v (PID::spaceLight, -0.16f)
            .v (PID::spacePreDelay, 11.0f).v (PID::spaceMix, 0.22f)
            .v (PID::auraSize, 0.34f).v (PID::auraDistance, 0.22f)
            .v (PID::auraFog, 0.32f).v (PID::auraDecay, 0.26f)
            .v (PID::auraLight, -0.14f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.16f)
            .v (PID::patinaNoise, 0.14f).v (PID::patinaWear, 0.28f)
            .v (PID::synthWidth, 0.90f).v (PID::highWidth, 1.05f)
            .v (PID::lowMonoFreq, 240.0f)
            .v (PID::breathAmount, 0.14f)
            .route (srcBreath, PID::oscBWtPos, 0.16f));

        // -- Processed and broken.  The chain order is the instrument. ----

        add (out, Build ("Lija Gruesa", "DRUMS", "BROKEN",
                         "broken,crush,lofi,kick",
                         "A clean kick sent into CRUSH first at seven bits and 9 kHz, then aged and comb-filtered after the fact.")
            .at (36, 1, 1.0f, 2.0)
            .chain ("CRUSH,RETRO,FILTER,GRAIN,SPACE,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::masterGain, -3.0f)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::voiceVariation, 0.12f).v (PID::driftAmount, 0.04f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.74f)
            .v (PID::oscAOctave, -1.0f).v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscAPhaseOffset, 0.25f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.18f)
            .v (PID::oscBSemi, 3.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.40f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.36f)
            .v (PID::noiseType, ch::nDigital).v (PID::noiseLevel, 0.24f)
            .v (PID::noiseAttackOnly, 0.80f)
            .v (PID::bodyAmount, 0.40f).v (PID::densityAmount, 0.18f)
            .v (PID::preFilterDrive, 0.28f).v (PID::postSaturation, 0.22f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 300.0f).v (PID::filterResonance, 0.44f)
            .v (PID::filterDrive, 0.28f).v (PID::filterKeyTrack, 0.0f)
            .v (PID::filterEnvAmount, 0.58f).v (PID::filterVelAmount, 0.40f)
            .v (PID::ampAttack, 0.0008f).v (PID::ampDecay, 0.46f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.20f)
            .v (PID::ampVelocity, 0.52f)
            .v (PID::env1Attack, 0.0006f).v (PID::env1Decay, 0.04f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.03f)
            .v (PID::macroMemory, 0.58f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.72f).v (PID::memoryWobble, 0.20f)
            .v (PID::memoryDiffusion, 0.40f).v (PID::memoryAsymmetry, 0.34f)
            .v (PID::macroCharacter, 0.70f).v (PID::macroMotion, 0.20f)
            .v (PID::macroWorld, 0.24f).v (PID::macroWeight, 0.58f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.62f)
            .v (PID::weightCompress, 0.38f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.62f)
            .v (PID::crushBits, 7.0f).v (PID::crushRate, 9000.0f)
            .v (PID::crushJitter, 0.20f).v (PID::crushDrive, 0.38f)
            .v (PID::crushTone, -0.16f).v (PID::crushMix, 0.66f)
            .v (PID::retroEra, 0.18f).v (PID::retroAge, 0.62f)
            .v (PID::retroDrift, 0.16f).v (PID::retroWear, 0.36f)
            .v (PID::retroTone, -0.28f).v (PID::retroNoise, 0.22f)
            .v (PID::retroMix, 0.78f)
            .v (PID::fxFilterMode, ch::f2Lp).v (PID::fxFilterCutoff, 3400.0f)
            .v (PID::fxFilterRes, 0.16f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.18f)
            .v (PID::grainSize, 55.0f).v (PID::grainDensity, 12.0f)
            .v (PID::grainPosition, 0.12f).v (PID::grainPitchMode, ch::gRoot)
            .v (PID::grainSpread, 0.30f).v (PID::grainJitter, 0.30f)
            .v (PID::grainDirection, 0.0f).v (PID::grainWindow, ch::wPercussive)
            .v (PID::grainMix, 0.16f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.26f)
            .v (PID::spaceSize, 0.24f).v (PID::spaceDecay, 0.80f)
            .v (PID::spaceFog, 0.30f).v (PID::spaceLight, -0.48f)
            .v (PID::spacePreDelay, 6.0f).v (PID::spaceMix, 0.12f)
            .v (PID::auraSize, 0.22f).v (PID::auraDistance, 0.16f)
            .v (PID::auraFog, 0.30f).v (PID::auraDecay, 0.16f)
            .v (PID::auraLight, -0.40f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.26f)
            .v (PID::patinaNoise, 0.20f).v (PID::patinaWear, 0.38f)
            .v (PID::synthWidth, 0.45f).v (PID::highWidth, 0.85f)
            .v (PID::lowMonoFreq, 340.0f)
            .v (PID::breathAmount, 0.08f)
            .route (srcMemory, PID::crushRate, -0.18f)
            .route (srcOrganic, PID::crushJitter, 0.12f));

        add (out, Build ("Cinta Quemada", "DRUMS", "HAUNTED",
                         "broken,tape,memory,snare",
                         "A snare at the fourth generation of copy: RETRO and SPACE before CRUSH and GRAIN, with REWIND diving at the end of the chain.")
            .at (40, 1, 0.95f, 2.5)
            .chain ("RETRO,SPACE,CRUSH,GRAIN,FILTER,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::voiceMode, ch::poly).v (PID::polyphony, 4.0f)
            .v (PID::voiceVariation, 0.34f).v (PID::driftAmount, 0.10f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.40f)
            .v (PID::oscASemi, -3.0f).v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.22f)
            .v (PID::oscBSemi, 8.0f).v (PID::oscBFine, 20.0f)
            .v (PID::oscRingMod, 0.24f)
            .v (PID::subLevel, 0.12f).v (PID::subHarmonics, 0.22f)
            .v (PID::noiseType, ch::nTexture).v (PID::noiseLevel, 0.70f)
            .v (PID::noiseAttackOnly, 0.18f)
            .v (PID::bodyAmount, 0.30f).v (PID::densityAmount, 0.22f)
            .v (PID::preFilterDrive, 0.22f).v (PID::postSaturation, 0.20f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 3200.0f).v (PID::filterResonance, 0.28f)
            .v (PID::filterDrive, 0.20f).v (PID::filterKeyTrack, 0.25f)
            .v (PID::filterEnvAmount, 0.32f).v (PID::filterVelAmount, 0.40f)
            .v (PID::ampAttack, 0.0015f).v (PID::ampDecay, 0.55f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.35f)
            .v (PID::ampVelocity, 0.54f)
            .v (PID::env1Attack, 0.0008f).v (PID::env1Decay, 0.07f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.05f)
            .v (PID::macroMemory, 0.78f).v (PID::memoryGen, ch::genIV)
            .v (PID::memoryBandwidth, 0.82f).v (PID::memoryWobble, 0.34f)
            .v (PID::memoryDiffusion, 0.52f).v (PID::memoryAsymmetry, 0.44f)
            .v (PID::macroCharacter, 0.66f).v (PID::macroMotion, 0.34f)
            .v (PID::macroWorld, 0.48f).v (PID::macroWeight, 0.30f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.36f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.30f)
            .v (PID::crushBits, 9.0f).v (PID::crushRate, 12000.0f)
            .v (PID::crushJitter, 0.16f).v (PID::crushDrive, 0.20f)
            .v (PID::crushTone, -0.20f).v (PID::crushMix, 0.40f)
            .v (PID::retroEra, 0.12f).v (PID::retroAge, 0.78f)
            .v (PID::retroDrift, 0.34f).v (PID::retroWear, 0.48f)
            .v (PID::retroTone, -0.34f).v (PID::retroNoise, 0.30f)
            .v (PID::retroMix, 0.88f)
            .v (PID::fxFilterMode, ch::f2Lp).v (PID::fxFilterCutoff, 5200.0f)
            .v (PID::fxFilterDrive, 0.12f)
            .v (PID::rewindOn, 1.0f).v (PID::rewindMode, ch::rDive)
            .v (PID::rewindDivision, ch::rw16).v (PID::rewindSync, 1.0f)
            .v (PID::rewindCurve, 0.60f).v (PID::rewindSpeed, 0.70f)
            .v (PID::rewindTail, 0.34f).v (PID::rewindMix, 0.34f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.30f)
            .v (PID::grainSize, 70.0f).v (PID::grainDensity, 16.0f)
            .v (PID::grainPosition, 0.24f).v (PID::grainPitchMode, ch::gRoot)
            .v (PID::grainSpread, 0.50f).v (PID::grainJitter, 0.44f)
            .v (PID::grainDirection, 0.22f).v (PID::grainWindow, ch::wTukey)
            .v (PID::grainFeedback, 0.12f).v (PID::grainMix, 0.26f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.48f)
            .v (PID::spaceSize, 0.42f).v (PID::spaceDecay, 1.80f)
            .v (PID::spaceFog, 0.46f).v (PID::spaceLight, -0.28f)
            .v (PID::spacePreDelay, 18.0f).v (PID::spaceMix, 0.30f)
            .v (PID::auraSize, 0.40f).v (PID::auraDistance, 0.34f)
            .v (PID::auraFog, 0.44f).v (PID::auraDecay, 0.32f)
            .v (PID::auraLight, -0.22f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.28f)
            .v (PID::patinaNoise, 0.26f).v (PID::patinaWear, 0.44f)
            .v (PID::patinaDrift, 0.30f)
            .v (PID::synthWidth, 1.05f).v (PID::highWidth, 1.15f)
            .v (PID::lowMonoFreq, 280.0f)
            .v (PID::breathAmount, 0.20f).v (PID::breathSpeed, 0.40f)
            .route (srcMemory, PID::filterCutoff, -0.20f)
            .route (srcBreath, PID::retroDrift, 0.16f)
            .route (srcOrganic, PID::grainPosition, 0.14f));
    }
}
