#include "PresetBuilder.h"
#include "Builders.h"

namespace nacar::presets::detail
{
    // ===============================================================
    //  KEYS
    // ===============================================================
    void buildKeys (std::vector<FactoryPreset>& out)
    {
        // A sine carrier phase-modulated by a sine at 2:1 is the tine; the
        // second generation of Memory is the cassette it was dubbed onto.
        add (out, Build ("Cassette Rhodes", "KEYS", "NOSTALGIC",
                         "rhodes,tape,tine,generation ii",
                         "An electric piano dubbed to cassette twice, tine and all.")
            .at (52, 3, 0.80f, 4.5)
            .chain ("RETRO,FILTER,CRUSH,SPACE,REWIND,GRAIN")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::masterGain, -3.5f)
            .v (PID::polyphony, 12.0f)
            .v (PID::voiceVariation, 0.34f)
            .v (PID::driftAmount, 0.20f).v (PID::driftRate, 0.09f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.70f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.0f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, 4.0f)
            .v (PID::oscPmAmount, 0.34f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.15f)
            .v (PID::subHarmonics, 0.10f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.06f)
            .v (PID::noiseAttackOnly, 0.85f)
            .v (PID::bodyAmount, 0.44f).v (PID::bodyTilt, 0.22f)
            .v (PID::densityAmount, 0.16f)
            .v (PID::preFilterDrive, 0.12f)
            .v (PID::postSaturation, 0.14f).v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 4200.0f).v (PID::filterResonance, 0.10f)
            .v (PID::filterDrive, 0.18f).v (PID::filterKeyTrack, 0.75f)
            .v (PID::filterEnvAmount, 0.34f).v (PID::filterVelAmount, 0.58f)
            .v (PID::ampAttack, 0.003f).v (PID::ampDecay, 2.6f)
            .v (PID::ampSustain, 0.20f).v (PID::ampRelease, 1.1f)
            .v (PID::ampVelocity, 0.72f)
            .v (PID::env1Attack, 0.001f).v (PID::env1Decay, 0.42f)
            .v (PID::env1Sustain, 0.04f).v (PID::env1Release, 0.30f)
            .v (PID::macroMemory, 0.38f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.58f).v (PID::memoryWobble, 0.30f)
            .v (PID::memoryDiffusion, 0.24f).v (PID::memoryAsymmetry, 0.30f)
            .v (PID::macroCharacter, 0.34f).v (PID::macroMotion, 0.30f)
            .v (PID::macroWorld, 0.30f)
            .v (PID::macroWeight, 0.32f).v (PID::weightMode, ch::wBody)
            .v (PID::weightHarmonics, 0.34f).v (PID::weightCompress, 0.30f)
            .v (PID::retroEra, 0.62f).v (PID::retroAge, 0.42f)
            .v (PID::retroDrift, 0.30f).v (PID::retroWear, 0.22f)
            .v (PID::retroTone, -0.22f).v (PID::retroNoise, 0.16f)
            .v (PID::retroMix, 0.85f)
            .v (PID::fxFilterCutoff, 9000.0f).v (PID::fxFilterRes, 0.08f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.30f)
            .v (PID::spaceSize, 0.42f).v (PID::spaceDecay, 2.1f)
            .v (PID::spaceFog, 0.34f).v (PID::spaceLight, -0.26f)
            .v (PID::spacePreDelay, 26.0f).v (PID::spaceMix, 0.22f)
            .v (PID::auraSize, 0.40f).v (PID::auraDistance, 0.24f)
            .v (PID::auraFog, 0.38f).v (PID::auraDecay, 0.34f)
            .v (PID::auraLight, -0.16f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.16f)
            .v (PID::patinaNoise, 0.14f).v (PID::patinaWear, 0.28f)
            .v (PID::patinaDrift, 0.24f)
            .v (PID::breathAmount, 0.30f).v (PID::breathSpeed, 0.17f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.26f)
            .v (PID::lfo1Depth, 0.55f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.12f)
            .v (PID::lfo2Depth, 0.42f)
            .v (PID::modWheelDepth, 0.55f).v (PID::vibratoDepth, 0.10f)
            .route (srcLfo1, PID::filterCutoff, 0.05f)
            .route (srcLfo2, PID::retroDrift, 0.28f)
            .route (srcBreath, PID::patinaNoise, 0.12f));

        // The COMB filter model on a struck body: the tone is in the comb,
        // not in the oscillator, which is why the oscillator is nearly a
        // sine and the second filter is doing the work.
        add (out, Build ("Salt Water Piano", "KEYS", "INTIMATE",
                         "comb,struck,close,soft",
                         "A small upright with the lid down, played in a damp room.")
            .at (55, 3, 0.62f, 5.0)
            .chain ("FILTER,RETRO,SPACE,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 14.0f)
            .v (PID::voiceVariation, 0.46f)
            .v (PID::driftAmount, 0.30f).v (PID::driftRate, 0.07f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.72f)
            .v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tOrganic)
            .v (PID::oscBWtPos, 0.22f).v (PID::oscBLevel, 0.34f)
            .v (PID::oscBFine, -6.0f).v (PID::oscBPan, 0.18f)
            .v (PID::subLevel, 0.14f).v (PID::subHarmonics, 0.22f)
            .v (PID::noiseType, ch::nTexture).v (PID::noiseLevel, 0.12f)
            .v (PID::noiseAttackOnly, 0.92f)
            .v (PID::bodyAmount, 0.38f).v (PID::densityAmount, 0.30f)
            .v (PID::preFilterDrive, 0.08f).v (PID::postSaturation, 0.10f)
            .v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 620.0f).v (PID::filterResonance, 0.42f)
            .v (PID::filterKeyTrack, 1.0f).v (PID::filterEnvAmount, 0.18f)
            .v (PID::filterVelAmount, 0.40f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Lp)
            .v (PID::filter2Cutoff, 3400.0f).v (PID::filter2Res, 0.12f)
            .v (PID::filter2Mix, 0.70f)
            .v (PID::ampAttack, 0.002f).v (PID::ampDecay, 3.4f)
            .v (PID::ampSustain, 0.14f).v (PID::ampRelease, 2.2f)
            .v (PID::ampVelocity, 0.66f)
            .v (PID::env1Attack, 0.0008f).v (PID::env1Decay, 0.60f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.40f)
            .v (PID::macroMemory, 0.30f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.44f).v (PID::memoryWobble, 0.42f)
            .v (PID::memoryDiffusion, 0.46f).v (PID::memoryAsymmetry, 0.20f)
            .v (PID::macroCharacter, 0.22f).v (PID::macroMotion, 0.42f)
            .v (PID::macroWorld, 0.28f).v (PID::macroWeight, 0.26f)
            .v (PID::retroEra, 0.30f).v (PID::retroAge, 0.24f)
            .v (PID::retroDrift, 0.34f).v (PID::retroWear, 0.14f)
            .v (PID::retroNoise, 0.08f).v (PID::retroMix, 0.55f)
            .v (PID::fxFilterCutoff, 7200.0f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.22f)
            .v (PID::spaceSize, 0.30f).v (PID::spaceDecay, 1.4f)
            .v (PID::spaceFog, 0.28f).v (PID::spacePreDelay, 14.0f)
            .v (PID::spaceMix, 0.24f)
            .v (PID::auraSize, 0.34f).v (PID::auraDistance, 0.20f)
            .v (PID::auraFog, 0.46f).v (PID::auraDecay, 0.30f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.06f)
            .v (PID::patinaNoise, 0.10f).v (PID::patinaWear, 0.20f)
            .v (PID::synthWidth, 0.90f).v (PID::highWidth, 1.05f)
            .v (PID::breathAmount, 0.44f).v (PID::breathSpeed, 0.14f)
            .v (PID::breathShape, 0.30f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.09f)
            .v (PID::lfo2Depth, 0.60f)
            .route (srcBreath, PID::filterCutoff, 0.07f)
            .route (srcLfo2, PID::oscBWtPos, 0.30f)
            .route (srcWheel, PID::filter2Cutoff, 0.22f));

        // A 1985 preset key: one pulse oscillator, a converter grid, and an
        // ageing profile that is bright rather than warm.
        add (out, Build ("Winter Casio", "KEYS", "COLD",
                         "digital,8-bit,brittle,chrome",
                         "A cheap digital keyboard with its converter showing.")
            .at (60, 3, 0.85f, 3.5)
            .chain ("CRUSH,RETRO,FILTER,SPACE,REWIND,GRAIN")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::masterGain, -8.0f)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.12f)
            .v (PID::driftAmount, 0.06f)
            .v (PID::oscAWave, ch::square).v (PID::oscALevel, 0.44f)
            .v (PID::oscAPulseWidth, 0.28f).v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::square).v (PID::oscBLevel, 0.24f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBPulseWidth, 0.72f)
            .v (PID::oscBFine, 0.0f).v (PID::oscBPhase, ch::phaseReset)
            .v (PID::oscCWave, ch::sine).v (PID::oscCLevel, 0.10f)
            .v (PID::oscCOctave, 2.0f)
            .v (PID::subLevel, 0.0f)
            .v (PID::bodyAmount, 0.12f).v (PID::densityAmount, 0.10f)
            .v (PID::preFilterDrive, 0.05f).v (PID::postSaturation, 0.06f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 9500.0f).v (PID::filterResonance, 0.08f)
            .v (PID::filterKeyTrack, 0.50f).v (PID::filterEnvAmount, 0.20f)
            .v (PID::ampAttack, 0.001f).v (PID::ampDecay, 1.6f)
            .v (PID::ampSustain, 0.38f).v (PID::ampRelease, 0.30f)
            .v (PID::ampVelocity, 0.30f)
            .v (PID::macroMemory, 0.16f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.30f).v (PID::memoryWobble, 0.10f)
            .v (PID::macroCharacter, 0.28f).v (PID::macroMotion, 0.14f)
            .v (PID::macroWorld, 0.24f).v (PID::macroWeight, 0.18f)
            .v (PID::weightMode, ch::wAir).v (PID::weightHarmonics, 0.42f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.42f)
            .v (PID::crushBits, 9.0f).v (PID::crushRate, 19000.0f)
            .v (PID::crushJitter, 0.06f).v (PID::crushDrive, 0.16f)
            .v (PID::crushTone, 0.22f).v (PID::crushMix, 0.72f)
            .v (PID::retroEra, 0.88f).v (PID::retroAge, 0.18f)
            .v (PID::retroDrift, 0.10f).v (PID::retroWear, 0.10f)
            .v (PID::retroTone, 0.12f).v (PID::retroNoise, 0.08f)
            .v (PID::retroMix, 0.70f)
            .v (PID::fxFilterCutoff, 13500.0f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.26f)
            .v (PID::spaceSize, 0.28f).v (PID::spaceDecay, 1.1f)
            .v (PID::spaceFog, 0.20f).v (PID::spaceLight, 0.32f)
            .v (PID::spacePreDelay, 12.0f).v (PID::spaceMix, 0.20f)
            .v (PID::auraSize, 0.26f).v (PID::auraDistance, 0.16f)
            .v (PID::auraFog, 0.22f).v (PID::auraDecay, 0.24f)
            .v (PID::auraLight, 0.34f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.20f)
            .v (PID::patinaNoise, 0.12f).v (PID::patinaWear, 0.16f)
            .v (PID::patinaDrift, 0.08f)
            .v (PID::breathAmount, 0.12f)
            .v (PID::lfo1Shape, ch::lfoTri).v (PID::lfo1Rate, 0.55f)
            .v (PID::lfo1Depth, 0.50f)
            .route (srcLfo1, PID::oscAPulseWidth, 0.16f)
            .route (srcOrganic, PID::crushRate, -0.12f));

        // MASS, driven, with the medium a long way past its best: the
        // saturation is in the voice and the damage is in Retro.
        add (out, Build ("Drowned Wurlitzer", "KEYS", "DIRTY",
                         "reed,overdrive,tremolo,worn",
                         "A reed piano pushed through an amplifier that gave up years ago.")
            .at (50, 3, 0.95f, 4.0)
            .chain ("RETRO,FILTER,CRUSH,GRAIN,SPACE,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 10.0f).v (PID::voiceVariation, 0.40f)
            .v (PID::driftAmount, 0.34f).v (PID::driftRate, 0.16f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.80f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.12f)
            .v (PID::oscASpread, 0.25f)
            .v (PID::oscBWave, ch::square).v (PID::oscBLevel, 0.30f)
            .v (PID::oscBPulseWidth, 0.34f).v (PID::oscBFine, -9.0f)
            .v (PID::oscRingMod, 0.14f)
            .v (PID::subWave, ch::subTri).v (PID::subLevel, 0.30f)
            .v (PID::subHarmonics, 0.34f)
            .v (PID::bodyAmount, 0.62f).v (PID::bodyTilt, -0.28f)
            .v (PID::densityAmount, 0.42f)
            .v (PID::preFilterDrive, 0.52f)
            .v (PID::postSaturation, 0.38f).v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 2600.0f).v (PID::filterResonance, 0.24f)
            .v (PID::filterDrive, 0.46f).v (PID::filterKeyTrack, 0.60f)
            .v (PID::filterEnvAmount, 0.42f).v (PID::filterVelAmount, 0.55f)
            .v (PID::ampAttack, 0.004f).v (PID::ampDecay, 2.0f)
            .v (PID::ampSustain, 0.34f).v (PID::ampRelease, 0.70f)
            .v (PID::ampVelocity, 0.68f)
            .v (PID::env1Decay, 0.30f).v (PID::env1Sustain, 0.10f)
            .v (PID::macroMemory, 0.46f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.66f).v (PID::memoryWobble, 0.48f)
            .v (PID::memoryDiffusion, 0.30f).v (PID::memoryAsymmetry, 0.42f)
            .v (PID::macroCharacter, 0.64f).v (PID::macroMotion, 0.46f)
            .v (PID::macroWorld, 0.26f).v (PID::macroWeight, 0.44f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.46f)
            .v (PID::weightCompress, 0.38f)
            .v (PID::retroEra, 0.20f).v (PID::retroAge, 0.62f)
            .v (PID::retroDrift, 0.46f).v (PID::retroWear, 0.44f)
            .v (PID::retroTone, -0.34f).v (PID::retroNoise, 0.26f)
            .v (PID::retroMix, 1.0f)
            .v (PID::fxFilterCutoff, 5200.0f).v (PID::fxFilterRes, 0.18f)
            .v (PID::fxFilterDrive, 0.26f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.34f)
            .v (PID::spaceSize, 0.36f).v (PID::spaceDecay, 1.8f)
            .v (PID::spaceFog, 0.44f).v (PID::spaceLight, -0.44f)
            .v (PID::spaceMix, 0.24f)
            .v (PID::auraSize, 0.36f).v (PID::auraDistance, 0.24f)
            .v (PID::auraFog, 0.52f).v (PID::auraDecay, 0.36f)
            .v (PID::auraLight, -0.30f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.30f)
            .v (PID::patinaNoise, 0.24f).v (PID::patinaWear, 0.46f)
            .v (PID::patinaDrift, 0.34f)
            .v (PID::breathAmount, 0.40f).v (PID::breathSpeed, 0.30f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 5.4f)
            .v (PID::lfo1Depth, 0.42f)
            .route (srcLfo1, PID::masterGain, 0.05f)
            .route (srcBreath, PID::filterCutoff, 0.06f)
            .route (srcTouch, PID::preFilterDrive, 0.25f));

        // Additive-ish: three sines an octave apart and a sub, swelled by
        // the amp envelope rather than by a filter.
        add (out, Build ("Tide Organ", "KEYS", "LUSH",
                         "organ,drawbar,swell,wide",
                         "Three sines and a sub, breathing in and out like a tide.")
            .at (48, 4, 0.72f, 6.0)
            .chain ("FILTER,SPACE,RETRO,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 16.0f).v (PID::voiceVariation, 0.30f)
            .v (PID::driftAmount, 0.24f).v (PID::driftRate, 0.05f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.70f)
            .v (PID::oscAUnison, 3.0f).v (PID::oscADetune, 0.10f)
            .v (PID::oscASpread, 0.62f).v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.44f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, 5.0f)
            .v (PID::oscBPan, -0.24f)
            .v (PID::oscCWave, ch::sine).v (PID::oscCLevel, 0.26f)
            .v (PID::oscCOctave, 1.0f).v (PID::oscCSemi, 7.0f)
            .v (PID::oscCPan, 0.28f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.34f)
            .v (PID::subHarmonics, 0.18f)
            .v (PID::bodyAmount, 0.30f).v (PID::densityAmount, 0.34f)
            .v (PID::preFilterDrive, 0.10f).v (PID::postSaturation, 0.14f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 5600.0f).v (PID::filterResonance, 0.06f)
            .v (PID::filterKeyTrack, 0.40f).v (PID::filterEnvAmount, 0.22f)
            .v (PID::filterVelAmount, 0.20f)
            .v (PID::ampAttack, 0.30f).v (PID::ampDecay, 1.2f)
            .v (PID::ampSustain, 0.92f).v (PID::ampRelease, 1.4f)
            .v (PID::ampVelocity, 0.28f)
            .v (PID::env2Attack, 2.4f).v (PID::env2Decay, 3.0f)
            .v (PID::env2Sustain, 0.80f)
            .v (PID::macroMemory, 0.26f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.36f).v (PID::memoryWobble, 0.28f)
            .v (PID::memoryDiffusion, 0.42f)
            .v (PID::macroCharacter, 0.24f).v (PID::macroMotion, 0.52f)
            .v (PID::macroWorld, 0.62f).v (PID::macroWeight, 0.36f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::retroEra, 0.44f).v (PID::retroAge, 0.22f)
            .v (PID::retroDrift, 0.28f).v (PID::retroWear, 0.10f)
            .v (PID::retroNoise, 0.08f).v (PID::retroMix, 0.48f)
            .v (PID::fxFilterCutoff, 10500.0f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.44f)
            .v (PID::spaceSize, 0.68f).v (PID::spaceDecay, 4.6f)
            .v (PID::spaceFog, 0.50f).v (PID::spaceLight, -0.14f)
            .v (PID::spacePreDelay, 34.0f).v (PID::spaceMix, 0.36f)
            .v (PID::auraSize, 0.62f).v (PID::auraDistance, 0.40f)
            .v (PID::auraFog, 0.52f).v (PID::auraDecay, 0.58f)
            .v (PID::auraLight, -0.08f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaNoise, 0.10f)
            .v (PID::patinaWear, 0.18f).v (PID::patinaDrift, 0.26f)
            .v (PID::synthWidth, 1.25f).v (PID::highWidth, 1.35f)
            .v (PID::breathAmount, 0.52f).v (PID::breathSpeed, 0.11f)
            .v (PID::breathShape, 0.24f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.18f)
            .v (PID::lfo1Depth, 0.60f)
            .v (PID::lfo2Shape, ch::lfoTri).v (PID::lfo2Rate, 0.33f)
            .v (PID::lfo2Depth, 0.45f)
            .route (srcLfo1, PID::oscBFine, 0.03f)
            .route (srcLfo2, PID::spaceSize, 0.10f)
            .route (srcBreath, PID::auraFog, 0.16f));
    }
}
