#include "PresetBuilder.h"
#include "Builders.h"

namespace nacar::presets::detail
{
    // ===============================================================
    //  LEADS
    // ===============================================================
    void buildLeads (std::vector<FactoryPreset>& out)
    {
        // Hard sync, which the oscillator band-limits with a second
        // time-domain BLEP, plus five-voice unison.  LEGATO with glide.
        add (out, Build ("Neon Siren", "LEADS", "AGGRESSIVE",
                         "sync,unison,legato,bright",
                         "A synced lead that screams when you push the wheel and not before.")
            .at (64, 1, 1.0f, 4.0)
            .chain ("FILTER,RETRO,CRUSH,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::voiceMode, ch::legato).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.09f).v (PID::voiceVariation, 0.20f)
            .v (PID::driftAmount, 0.16f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.80f)
            .v (PID::oscAUnison, 5.0f).v (PID::oscADetune, 0.18f)
            .v (PID::oscASpread, 0.70f)
            .v (PID::oscBWave, ch::saw).v (PID::oscBLevel, 0.0f)
            .v (PID::oscBSemi, -5.0f)
            .v (PID::oscSync, 0.46f)
            .v (PID::subLevel, 0.16f)
            .v (PID::bodyAmount, 0.24f).v (PID::densityAmount, 0.22f)
            .v (PID::preFilterDrive, 0.34f).v (PID::postSaturation, 0.26f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 5600.0f).v (PID::filterResonance, 0.30f)
            .v (PID::filterDrive, 0.30f).v (PID::filterKeyTrack, 0.55f)
            .v (PID::filterEnvAmount, 0.40f).v (PID::filterVelAmount, 0.45f)
            .v (PID::ampAttack, 0.012f).v (PID::ampDecay, 0.6f)
            .v (PID::ampSustain, 0.88f).v (PID::ampRelease, 0.35f)
            .v (PID::ampVelocity, 0.45f)
            .v (PID::env1Attack, 0.004f).v (PID::env1Decay, 0.24f)
            .v (PID::env1Sustain, 0.35f)
            .v (PID::macroMemory, 0.18f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.26f).v (PID::memoryWobble, 0.20f)
            .v (PID::macroCharacter, 0.54f).v (PID::macroMotion, 0.34f)
            .v (PID::macroWorld, 0.36f).v (PID::macroWeight, 0.30f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.20f)
            .v (PID::crushBits, 14.0f).v (PID::crushRate, 30000.0f)
            .v (PID::crushDrive, 0.30f).v (PID::crushTone, 0.16f)
            .v (PID::crushMix, 0.34f)
            .v (PID::retroEra, 0.74f).v (PID::retroAge, 0.20f)
            .v (PID::retroDrift, 0.14f).v (PID::retroWear, 0.08f)
            .v (PID::retroTone, 0.10f).v (PID::retroNoise, 0.08f)
            .v (PID::retroMix, 0.44f)
            .v (PID::fxFilterCutoff, 11000.0f).v (PID::fxFilterRes, 0.20f)
            .v (PID::fxFilterDrive, 0.22f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.24f)
            .v (PID::spaceSize, 0.36f).v (PID::spaceDecay, 1.6f)
            .v (PID::spaceFog, 0.30f).v (PID::spaceLight, 0.20f)
            .v (PID::spacePreDelay, 18.0f).v (PID::spaceMix, 0.22f)
            .v (PID::auraSize, 0.36f).v (PID::auraDistance, 0.20f)
            .v (PID::auraFog, 0.28f).v (PID::auraDecay, 0.34f)
            .v (PID::auraLight, 0.22f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.16f)
            .v (PID::patinaNoise, 0.10f).v (PID::patinaWear, 0.18f)
            .v (PID::synthWidth, 1.10f).v (PID::highWidth, 1.20f)
            .v (PID::breathAmount, 0.24f).v (PID::breathSpeed, 0.35f)
            .v (PID::modWheelDepth, 0.85f).v (PID::vibratoDepth, 0.30f)
            .v (PID::vibratoRate, 5.6f).v (PID::aftertouchDepth, 0.60f)
            .v (PID::lfo1Shape, ch::lfoTri).v (PID::lfo1Rate, 4.8f)
            .v (PID::lfo1Depth, 0.35f)
            .route (srcWheel, PID::oscSync, 0.40f)
            .route (srcTouch, PID::filterCutoff, 0.22f)
            .route (srcLfo1, PID::filterCutoff, 0.04f));

        // Breath noise gated to the attack, a sine body, and the vibrato
        // under the mod wheel.  Almost no harmonics: the noise is the tone.
        add (out, Build ("Ash Flute", "LEADS", "INTIMATE",
                         "breath,mono,soft,noise",
                         "A wooden flute played too quietly to be certain it is there.")
            .at (67, 1, 0.58f, 5.0)
            .chain ("FILTER,RETRO,SPACE,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::masterGain, 10.0f)
            .v (PID::voiceMode, ch::legato).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.06f).v (PID::voiceVariation, 0.30f)
            .v (PID::driftAmount, 0.30f).v (PID::driftRate, 0.20f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.86f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.34f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, 8.0f)
            .v (PID::subLevel, 0.10f)
            .v (PID::noiseType, ch::nAir).v (PID::noiseLevel, 0.42f)
            .v (PID::noiseAttackOnly, 0.30f)
            .v (PID::bodyAmount, 0.24f).v (PID::densityAmount, 0.18f)
            .v (PID::postSaturation, 0.08f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 1500.0f).v (PID::filterResonance, 0.28f)
            .v (PID::filterKeyTrack, 1.0f).v (PID::filterEnvAmount, 0.26f)
            .v (PID::filterVelAmount, 0.50f)
            .v (PID::ampAttack, 0.07f).v (PID::ampDecay, 1.0f)
            .v (PID::ampSustain, 0.82f).v (PID::ampRelease, 0.55f)
            .v (PID::ampVelocity, 0.70f)
            .v (PID::env1Attack, 0.02f).v (PID::env1Decay, 0.30f)
            .v (PID::env1Sustain, 0.20f)
            .v (PID::macroMemory, 0.28f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.40f).v (PID::memoryWobble, 0.36f)
            .v (PID::memoryDiffusion, 0.34f)
            .v (PID::macroCharacter, 0.22f).v (PID::macroMotion, 0.56f)
            .v (PID::macroWorld, 0.48f).v (PID::macroWeight, 0.20f)
            .v (PID::weightMode, ch::wAir).v (PID::weightHarmonics, 0.38f)
            .v (PID::retroEra, 0.40f).v (PID::retroAge, 0.26f)
            .v (PID::retroDrift, 0.32f).v (PID::retroWear, 0.12f)
            .v (PID::retroTone, -0.16f).v (PID::retroNoise, 0.14f)
            .v (PID::retroMix, 0.50f)
            .v (PID::fxFilterCutoff, 8000.0f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.38f)
            .v (PID::spaceSize, 0.50f).v (PID::spaceDecay, 3.0f)
            .v (PID::spaceFog, 0.44f).v (PID::spaceLight, -0.12f)
            .v (PID::spacePreDelay, 24.0f).v (PID::spaceMix, 0.32f)
            .v (PID::auraSize, 0.52f).v (PID::auraDistance, 0.32f)
            .v (PID::auraFog, 0.44f).v (PID::auraDecay, 0.44f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaNoise, 0.14f)
            .v (PID::patinaWear, 0.20f).v (PID::patinaDrift, 0.28f)
            .v (PID::breathOn, 1.0f).v (PID::breathAmount, 0.70f)
            .v (PID::breathSpeed, 0.45f).v (PID::breathRandom, 0.60f)
            .v (PID::breathShape, 0.28f)
            .v (PID::modWheelDepth, 0.80f).v (PID::vibratoDepth, 0.42f)
            .v (PID::vibratoRate, 4.6f).v (PID::aftertouchDepth, 0.55f)
            .route (srcBreath, PID::noiseLevel, 0.16f)
            .route (srcBreath, PID::filterCutoff, 0.09f)
            .route (srcTouch, PID::noiseLevel, 0.18f));

        // MASS into its own ladder with drive in the feedback path, then
        // Crush before the filter FX.  The dirtiest lead in the set.
        add (out, Build ("Molten Lead", "LEADS", "AGGRESSIVE",
                         "mass,drive,mono,crush",
                         "A mono lead with the ladder driven until the resonance gets fat.")
            .at (59, 1, 1.0f, 4.0)
            .chain ("CRUSH,FILTER,RETRO,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.03f).v (PID::voiceVariation, 0.18f)
            .v (PID::driftAmount, 0.20f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.84f)
            .v (PID::oscAUnison, 3.0f).v (PID::oscADetune, 0.16f)
            .v (PID::oscASpread, 0.35f)
            .v (PID::oscBWave, ch::square).v (PID::oscBLevel, 0.46f)
            .v (PID::oscBPulseWidth, 0.36f).v (PID::oscBOctave, -1.0f)
            .v (PID::oscBFine, -8.0f)
            .v (PID::subWave, ch::subSquare).v (PID::subLevel, 0.30f)
            .v (PID::subHarmonics, 0.40f)
            .v (PID::bodyAmount, 0.56f).v (PID::bodyTilt, -0.22f)
            .v (PID::densityAmount, 0.44f)
            .v (PID::preFilterDrive, 0.62f).v (PID::postSaturation, 0.44f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 3200.0f).v (PID::filterResonance, 0.42f)
            .v (PID::filterDrive, 0.62f).v (PID::filterKeyTrack, 0.50f)
            .v (PID::filterEnvAmount, 0.46f).v (PID::filterVelAmount, 0.40f)
            .v (PID::ampAttack, 0.006f).v (PID::ampDecay, 0.5f)
            .v (PID::ampSustain, 0.90f).v (PID::ampRelease, 0.28f)
            .v (PID::ampVelocity, 0.40f)
            .v (PID::env1Decay, 0.18f).v (PID::env1Sustain, 0.30f)
            .v (PID::macroMemory, 0.22f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.44f).v (PID::memoryWobble, 0.22f)
            .v (PID::macroCharacter, 0.76f).v (PID::macroMotion, 0.30f)
            .v (PID::macroWorld, 0.24f).v (PID::macroWeight, 0.50f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.48f)
            .v (PID::weightCompress, 0.44f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.38f)
            .v (PID::crushBits, 11.0f).v (PID::crushRate, 17000.0f)
            .v (PID::crushJitter, 0.14f).v (PID::crushDrive, 0.42f)
            .v (PID::crushTone, -0.10f).v (PID::crushMix, 0.46f)
            .v (PID::retroEra, 0.28f).v (PID::retroAge, 0.44f)
            .v (PID::retroDrift, 0.18f).v (PID::retroWear, 0.24f)
            .v (PID::retroTone, -0.24f).v (PID::retroNoise, 0.16f)
            .v (PID::retroMix, 0.60f)
            .v (PID::fxFilterCutoff, 6400.0f).v (PID::fxFilterRes, 0.22f)
            .v (PID::fxFilterDrive, 0.30f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.22f)
            .v (PID::spaceSize, 0.34f).v (PID::spaceDecay, 1.5f)
            .v (PID::spaceFog, 0.38f).v (PID::spaceLight, -0.34f)
            .v (PID::spaceMix, 0.18f)
            .v (PID::auraSize, 0.32f).v (PID::auraDistance, 0.18f)
            .v (PID::auraFog, 0.36f).v (PID::auraDecay, 0.30f)
            .v (PID::auraLight, -0.24f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.26f)
            .v (PID::patinaNoise, 0.20f).v (PID::patinaWear, 0.40f)
            .v (PID::synthWidth, 0.90f).v (PID::lowMonoFreq, 160.0f)
            .v (PID::breathAmount, 0.26f)
            .v (PID::modWheelDepth, 0.70f).v (PID::vibratoDepth, 0.24f)
            .v (PID::aftertouchDepth, 0.70f)
            .v (PID::lfo1Shape, ch::lfoSquare).v (PID::lfo1Rate, 6.2f)
            .v (PID::lfo1Depth, 0.30f)
            .route (srcTouch, PID::filterResonance, 0.25f)
            .route (srcLfo1, PID::crushAmount, 0.12f)
            .route (srcWheel, PID::filterCutoff, 0.20f));

        // The FORMANT model with FX filter MOTION travelling through the
        // vowels: a lead that talks without a vocoder anywhere near it.
        add (out, Build ("Satellite Voice", "LEADS", "MYSTERIOUS",
                         "formant,vowel,motion,talking",
                         "A voice coming through a relay that is not quite tuned in.")
            .at (62, 1, 0.82f, 5.5)
            .chain ("FILTER,GRAIN,RETRO,SPACE,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::masterGain, 9.0f)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.12f).v (PID::glideMode, 1.0f)
            .v (PID::voiceVariation, 0.34f)
            .v (PID::driftAmount, 0.34f).v (PID::driftRate, 0.24f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.88f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.12f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tVocal)
            .v (PID::oscBWtPos, 0.44f).v (PID::oscBLevel, 0.54f)
            .v (PID::oscBFine, -11.0f)
            .v (PID::subLevel, 0.12f)
            .v (PID::noiseType, ch::nDigital).v (PID::noiseLevel, 0.10f)
            .v (PID::bodyAmount, 0.22f).v (PID::densityAmount, 0.26f)
            .v (PID::preFilterDrive, 0.18f).v (PID::postSaturation, 0.14f)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 900.0f).v (PID::filterResonance, 0.54f)
            .v (PID::filterKeyTrack, 0.22f).v (PID::filterEnvAmount, 0.30f)
            .v (PID::ampAttack, 0.03f).v (PID::ampDecay, 0.9f)
            .v (PID::ampSustain, 0.84f).v (PID::ampRelease, 0.60f)
            .v (PID::ampVelocity, 0.50f)
            .v (PID::macroMemory, 0.34f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.50f).v (PID::memoryWobble, 0.40f)
            .v (PID::memoryDiffusion, 0.36f).v (PID::memoryAsymmetry, 0.34f)
            .v (PID::macroCharacter, 0.40f).v (PID::macroMotion, 0.66f)
            .v (PID::macroWorld, 0.52f).v (PID::macroWeight, 0.24f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.24f)
            .v (PID::grainSize, 60.0f).v (PID::grainDensity, 26.0f)
            .v (PID::grainPosition, 0.14f).v (PID::grainPitchMode, ch::gRoot)
            .v (PID::grainSpread, 0.40f).v (PID::grainJitter, 0.40f)
            .v (PID::grainDirection, 0.0f).v (PID::grainWindow, ch::wTukey)
            .v (PID::grainMix, 0.26f)
            .v (PID::retroEra, 0.68f).v (PID::retroAge, 0.34f)
            .v (PID::retroDrift, 0.30f).v (PID::retroWear, 0.30f)
            .v (PID::retroTone, -0.08f).v (PID::retroNoise, 0.20f)
            .v (PID::retroMix, 0.66f)
            .v (PID::fxFilterMode, ch::f2Formant).v (PID::fxFilterCutoff, 1200.0f)
            .v (PID::fxFilterRes, 0.30f).v (PID::fxFilterMotion, 0.62f)
            .v (PID::fxFilterMix, 0.45f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.54f)
            .v (PID::spaceSize, 0.56f).v (PID::spaceDecay, 3.6f)
            .v (PID::spaceFog, 0.50f).v (PID::spaceLight, -0.12f)
            .v (PID::spaceMix, 0.34f)
            .v (PID::auraSize, 0.54f).v (PID::auraDistance, 0.40f)
            .v (PID::auraFog, 0.50f).v (PID::auraDecay, 0.46f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.06f)
            .v (PID::patinaNoise, 0.18f).v (PID::patinaWear, 0.32f)
            .v (PID::patinaDrift, 0.34f)
            .v (PID::breathAmount, 0.58f).v (PID::breathSpeed, 0.36f)
            .v (PID::breathShape, 0.56f)
            .v (PID::modWheelDepth, 0.75f).v (PID::vibratoDepth, 0.22f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Rate, 0.70f)
            .v (PID::lfo1Depth, 0.60f)
            .route (srcLfo1, PID::filterCutoff, 0.16f)
            .route (srcBreath, PID::oscBWtPos, 0.26f)
            .route (srcWheel, PID::fxFilterCutoff, 0.24f));
    }
}
