#include "PresetBuilder.h"
#include "Builders.h"

namespace nacar::presets::detail
{
    // ===============================================================
    //  PADS
    // ===============================================================
    void buildPads (std::vector<FactoryPreset>& out)
    {
        // The default session already names this one.  Wide HAZE unison
        // under a dark chamber, with Aura carrying most of the size.
        add (out, Build ("Niebla en la Ciudad", "PADS", "MYSTERIOUS",
                         "unison,fog,slow,wide",
                         "A city seen from a window that has not been cleaned in years.")
            .at (45, 4, 0.70f, 7.0)
            .chain ("RETRO,FILTER,SPACE,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 16.0f).v (PID::voiceVariation, 0.52f)
            .v (PID::driftAmount, 0.42f).v (PID::driftRate, 0.06f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.68f)
            .v (PID::oscAUnison, 5.0f).v (PID::oscADetune, 0.30f)
            .v (PID::oscASpread, 0.80f).v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tHollow)
            .v (PID::oscBWtPos, 0.30f).v (PID::oscBLevel, 0.46f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBUnison, 3.0f)
            .v (PID::oscBDetune, 0.20f).v (PID::oscBSpread, 0.55f)
            .v (PID::subLevel, 0.22f).v (PID::subHarmonics, 0.16f)
            .v (PID::noiseType, ch::nDark).v (PID::noiseLevel, 0.07f)
            .v (PID::bodyAmount, 0.34f).v (PID::densityAmount, 0.40f)
            .v (PID::preFilterDrive, 0.14f).v (PID::postSaturation, 0.14f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1900.0f).v (PID::filterResonance, 0.14f)
            .v (PID::filterKeyTrack, 0.42f).v (PID::filterEnvAmount, 0.30f)
            .v (PID::filterVelAmount, 0.24f)
            .v (PID::ampAttack, 0.85f).v (PID::ampDecay, 3.0f)
            .v (PID::ampSustain, 0.82f).v (PID::ampRelease, 3.4f)
            .v (PID::ampVelocity, 0.35f)
            .v (PID::env1Attack, 1.4f).v (PID::env1Decay, 4.0f)
            .v (PID::env1Sustain, 0.55f)
            .v (PID::macroMemory, 0.42f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.56f).v (PID::memoryWobble, 0.38f)
            .v (PID::memoryDiffusion, 0.52f).v (PID::memoryAsymmetry, 0.34f)
            .v (PID::macroCharacter, 0.36f).v (PID::macroMotion, 0.56f)
            .v (PID::macroWorld, 0.66f).v (PID::macroWeight, 0.30f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::retroEra, 0.52f).v (PID::retroAge, 0.34f)
            .v (PID::retroDrift, 0.34f).v (PID::retroWear, 0.18f)
            .v (PID::retroTone, -0.26f).v (PID::retroNoise, 0.14f)
            .v (PID::retroMix, 0.72f)
            .v (PID::fxFilterCutoff, 6200.0f).v (PID::fxFilterMotion, 0.22f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.48f)
            .v (PID::spaceSize, 0.72f).v (PID::spaceDecay, 6.5f)
            .v (PID::spaceFog, 0.58f).v (PID::spaceLight, -0.34f)
            .v (PID::spacePreDelay, 42.0f).v (PID::spaceMix, 0.38f)
            .v (PID::auraSize, 0.66f).v (PID::auraDistance, 0.44f)
            .v (PID::auraFog, 0.60f).v (PID::auraDecay, 0.62f)
            .v (PID::auraLight, -0.24f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.18f)
            .v (PID::patinaNoise, 0.16f).v (PID::patinaWear, 0.30f)
            .v (PID::patinaDrift, 0.32f)
            .v (PID::synthWidth, 1.25f).v (PID::highWidth, 1.30f)
            .v (PID::lowMonoFreq, 150.0f)
            .v (PID::breathAmount, 0.56f).v (PID::breathSpeed, 0.10f)
            .v (PID::breathRandom, 0.60f).v (PID::breathShape, 0.34f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.09f)
            .v (PID::lfo1Depth, 0.65f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.07f)
            .v (PID::lfo2Depth, 0.55f)
            .route (srcLfo1, PID::filterCutoff, 0.09f)
            .route (srcLfo2, PID::oscBWtPos, 0.34f)
            .route (srcBreath, PID::spaceFog, 0.18f));

        // Memory generation IV, which is four copies in series, under a
        // VOCAL wavetable: the choir is the artefact, not the source.
        add (out, Build ("Fourth Generation Choir", "PADS", "HAUNTED",
                         "choir,generation iv,dropouts,vocal",
                         "A choir copied four times, by which point the room is singing too.")
            .at (43, 4, 0.66f, 8.0)
            .chain ("SPACE,RETRO,FILTER,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::masterGain, 5.0f)
            .v (PID::polyphony, 12.0f).v (PID::voiceVariation, 0.64f)
            .v (PID::driftAmount, 0.46f).v (PID::driftRate, 0.05f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tVocal)
            .v (PID::oscAWtPos, 0.36f).v (PID::oscALevel, 0.88f)
            .v (PID::oscAUnison, 4.0f).v (PID::oscADetune, 0.26f)
            .v (PID::oscASpread, 0.55f).v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tVocal)
            .v (PID::oscBWtPos, 0.68f).v (PID::oscBLevel, 0.40f)
            .v (PID::oscBSemi, 7.0f).v (PID::oscBFine, -8.0f)
            .v (PID::oscBUnison, 2.0f).v (PID::oscBSpread, 0.60f)
            .v (PID::subLevel, 0.12f)
            .v (PID::noiseType, ch::nTexture).v (PID::noiseLevel, 0.06f)
            .v (PID::bodyAmount, 0.24f).v (PID::densityAmount, 0.34f)
            .v (PID::postSaturation, 0.10f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 780.0f).v (PID::filterResonance, 0.30f)
            .v (PID::filterKeyTrack, 0.18f).v (PID::filterEnvAmount, 0.24f)
            .v (PID::ampAttack, 1.4f).v (PID::ampDecay, 4.0f)
            .v (PID::ampSustain, 0.78f).v (PID::ampRelease, 5.0f)
            .v (PID::ampVelocity, 0.30f)
            .v (PID::macroMemory, 0.64f).v (PID::memoryGen, ch::genIV)
            .v (PID::memoryBandwidth, 0.72f).v (PID::memoryWobble, 0.58f)
            .v (PID::memoryDiffusion, 0.66f).v (PID::memoryAsymmetry, 0.46f)
            .v (PID::macroCharacter, 0.44f).v (PID::macroMotion, 0.62f)
            .v (PID::macroWorld, 0.74f).v (PID::macroWeight, 0.22f)
            .v (PID::weightMode, ch::wAir).v (PID::weightHarmonics, 0.40f)
            .v (PID::retroEra, 0.36f).v (PID::retroAge, 0.48f)
            .v (PID::retroDrift, 0.40f).v (PID::retroWear, 0.32f)
            .v (PID::retroTone, -0.20f).v (PID::retroNoise, 0.18f)
            .v (PID::retroMix, 0.66f)
            .v (PID::fxFilterMode, ch::f2Bp).v (PID::fxFilterCutoff, 1600.0f)
            .v (PID::fxFilterRes, 0.22f).v (PID::fxFilterMorph, 0.30f)
            .v (PID::fxFilterMotion, 0.34f).v (PID::fxFilterMix, 0.45f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.62f)
            .v (PID::spaceSize, 0.80f).v (PID::spaceDecay, 9.0f)
            .v (PID::spaceFog, 0.70f).v (PID::spaceLight, -0.30f)
            .v (PID::spacePreDelay, 18.0f).v (PID::spaceMix, 0.46f)
            .v (PID::shadowOn, 1.0f).v (PID::shadowLength, 0.34f)
            .v (PID::shadowDistance, 0.68f).v (PID::shadowBlur, 0.72f)
            .v (PID::shadowPitch, 12.0f).v (PID::shadowLevel, 0.28f)
            .v (PID::auraSize, 0.74f).v (PID::auraDistance, 0.52f)
            .v (PID::auraFog, 0.70f).v (PID::auraDecay, 0.72f)
            .v (PID::auraLight, -0.20f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.24f)
            .v (PID::patinaNoise, 0.22f).v (PID::patinaWear, 0.42f)
            .v (PID::patinaDrift, 0.40f)
            .v (PID::synthWidth, 1.08f).v (PID::highWidth, 1.15f)
            .v (PID::breathAmount, 0.66f).v (PID::breathSpeed, 0.08f)
            .v (PID::breathRandom, 0.72f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.06f)
            .v (PID::lfo2Depth, 0.70f)
            .route (srcLfo2, PID::oscAWtPos, 0.30f)
            .route (srcBreath, PID::filterCutoff, 0.12f)
            .route (srcMotion, PID::shadowBlur, 0.20f));

        // MIRAGE with the ORGANIC family and a real second filter: the
        // widest patch in the set, and the one that leans on Shadow.
        add (out, Build ("Greenhouse", "PADS", "LUSH",
                         "organic,wide,shimmer,shadow",
                         "Something growing under glass, warm and a little too humid.")
            .at (47, 4, 0.72f, 8.0)
            .chain ("FILTER,RETRO,GRAIN,SPACE,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 16.0f).v (PID::voiceVariation, 0.44f)
            .v (PID::driftAmount, 0.30f).v (PID::driftRate, 0.08f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tOrganic)
            .v (PID::oscAWtPos, 0.24f).v (PID::oscALevel, 0.74f)
            .v (PID::oscAUnison, 6.0f).v (PID::oscADetune, 0.24f)
            .v (PID::oscASpread, 0.92f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tSoft)
            .v (PID::oscBWtPos, 0.52f).v (PID::oscBLevel, 0.42f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, 11.0f)
            .v (PID::oscBUnison, 3.0f).v (PID::oscBSpread, 0.75f)
            .v (PID::oscCWave, ch::sine).v (PID::oscCLevel, 0.14f)
            .v (PID::oscCOctave, 2.0f).v (PID::oscCSemi, 7.0f)
            .v (PID::subLevel, 0.18f)
            .v (PID::bodyAmount, 0.28f).v (PID::densityAmount, 0.30f)
            .v (PID::postSaturation, 0.12f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 3400.0f).v (PID::filterResonance, 0.12f)
            .v (PID::filterKeyTrack, 0.55f).v (PID::filterEnvAmount, 0.44f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Notch)
            .v (PID::filter2Cutoff, 1200.0f).v (PID::filter2Res, 0.34f)
            .v (PID::filter2Mix, 0.42f)
            .v (PID::ampAttack, 1.1f).v (PID::ampDecay, 3.6f)
            .v (PID::ampSustain, 0.86f).v (PID::ampRelease, 4.2f)
            .v (PID::env1Attack, 2.0f).v (PID::env1Decay, 5.0f)
            .v (PID::env1Sustain, 0.62f)
            .v (PID::macroMemory, 0.28f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.34f).v (PID::memoryDiffusion, 0.46f)
            .v (PID::macroCharacter, 0.24f).v (PID::macroMotion, 0.64f)
            .v (PID::macroWorld, 0.70f).v (PID::macroWeight, 0.28f)
            .v (PID::retroEra, 0.46f).v (PID::retroAge, 0.18f)
            .v (PID::retroDrift, 0.30f).v (PID::retroWear, 0.08f)
            .v (PID::retroNoise, 0.06f).v (PID::retroMix, 0.42f)
            .v (PID::fxFilterCutoff, 12000.0f).v (PID::fxFilterMotion, 0.30f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.42f)
            .v (PID::spaceSize, 0.76f).v (PID::spaceDecay, 7.0f)
            .v (PID::spaceFog, 0.48f).v (PID::spaceLight, 0.10f)
            .v (PID::spacePreDelay, 46.0f).v (PID::spaceMix, 0.40f)
            .v (PID::shadowOn, 1.0f).v (PID::shadowLength, 0.52f)
            .v (PID::shadowDistance, 0.50f).v (PID::shadowBlur, 0.62f)
            .v (PID::shadowPitch, 19.0f).v (PID::shadowLevel, 0.24f)
            .v (PID::auraSize, 0.70f).v (PID::auraDistance, 0.38f)
            .v (PID::auraFog, 0.46f).v (PID::auraDecay, 0.66f)
            .v (PID::auraLight, 0.18f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, 0.06f)
            .v (PID::patinaNoise, 0.08f).v (PID::patinaWear, 0.16f)
            .v (PID::patinaDrift, 0.30f)
            .v (PID::synthWidth, 1.40f).v (PID::highWidth, 1.45f)
            .v (PID::breathAmount, 0.62f).v (PID::breathSpeed, 0.13f)
            .v (PID::breathShape, 0.22f)
            .v (PID::lfo1Shape, ch::lfoTri).v (PID::lfo1Rate, 0.14f)
            .v (PID::lfo1Depth, 0.70f)
            .v (PID::lfo2Shape, ch::lfoSine).v (PID::lfo2Rate, 0.21f)
            .v (PID::lfo2Depth, 0.50f)
            .route (srcLfo1, PID::oscAWtPos, 0.36f)
            .route (srcLfo2, PID::oscBWtPos, -0.28f)
            .route (srcBreath, PID::shadowLevel, 0.14f));

        // High-passed, noise-forward, INFINITE tail: a pad with no low end
        // at all, which is why the low-mono guard has nothing to protect.
        add (out, Build ("Cold Storage", "PADS", "COLD",
                         "high-pass,infinite,air,still",
                         "A room that is only ever cold, with the compressor humming somewhere.")
            .at (52, 4, 0.60f, 9.0)
            .chain ("FILTER,SPACE,GRAIN,RETRO,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 14.0f).v (PID::voiceVariation, 0.38f)
            .v (PID::driftAmount, 0.18f).v (PID::driftRate, 0.04f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.52f)
            .v (PID::oscAUnison, 4.0f).v (PID::oscADetune, 0.16f)
            .v (PID::oscASpread, 0.60f).v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tSpectral)
            .v (PID::oscBWtPos, 0.62f).v (PID::oscBLevel, 0.44f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBSpread, 0.50f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nAir).v (PID::noiseLevel, 0.20f)
            .v (PID::bodyAmount, 0.08f).v (PID::densityAmount, 0.18f)
            .v (PID::preFilterDrive, 0.04f).v (PID::postSaturation, 0.05f)
            .v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::hp)
            .v (PID::filterCutoff, 420.0f).v (PID::filterResonance, 0.18f)
            .v (PID::filterKeyTrack, 0.25f).v (PID::filterEnvAmount, -0.20f)
            .v (PID::ampAttack, 2.2f).v (PID::ampDecay, 5.0f)
            .v (PID::ampSustain, 0.84f).v (PID::ampRelease, 6.0f)
            .v (PID::ampVelocity, 0.24f)
            .v (PID::macroMemory, 0.20f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.24f).v (PID::memoryWobble, 0.18f)
            .v (PID::macroCharacter, 0.16f).v (PID::macroMotion, 0.36f)
            .v (PID::macroWorld, 0.56f).v (PID::macroWeight, 0.30f)
            .v (PID::weightMode, ch::wAir).v (PID::weightHarmonics, 0.52f)
            .v (PID::weightCompress, 0.34f)
            .v (PID::retroEra, 0.72f).v (PID::retroAge, 0.14f)
            .v (PID::retroDrift, 0.12f).v (PID::retroWear, 0.06f)
            .v (PID::retroTone, 0.22f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.34f)
            .v (PID::fxFilterMode, ch::f2Hp).v (PID::fxFilterCutoff, 260.0f)
            .v (PID::fxFilterRes, 0.10f)
            .v (PID::spaceCharacter, ch::sInfinite).v (PID::spaceDistance, 0.58f)
            .v (PID::spaceSize, 0.88f).v (PID::spaceDecay, 18.0f)
            .v (PID::spaceFog, 0.62f).v (PID::spaceLight, 0.16f)
            .v (PID::spacePreDelay, 60.0f).v (PID::spaceMix, 0.34f)
            .v (PID::auraSize, 0.80f).v (PID::auraDistance, 0.34f)
            .v (PID::auraFog, 0.54f).v (PID::auraDecay, 0.80f)
            .v (PID::auraLight, 0.30f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.24f)
            .v (PID::patinaNoise, 0.16f).v (PID::patinaWear, 0.22f)
            .v (PID::patinaDrift, 0.14f)
            .v (PID::synthWidth, 1.05f).v (PID::highWidth, 1.20f)
            .v (PID::lowMonoFreq, 200.0f)
            .v (PID::breathAmount, 0.40f).v (PID::breathSpeed, 0.07f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.05f)
            .v (PID::lfo1Depth, 0.60f)
            .route (srcLfo1, PID::fxFilterCutoff, 0.14f)
            .route (srcBreath, PID::noiseLevel, 0.10f)
            .route (srcWorld, PID::auraFog, 0.15f));

        // MASS with the low mids intact and almost no top: the warmest,
        // narrowest pad in the library, and the one Weight matters most to.
        add (out, Build ("Worn Velvet", "PADS", "ROMANTIC",
                         "warm,narrow,low-mid,close",
                         "A heavy curtain in a small room, and the song behind it.")
            .at (41, 4, 0.68f, 7.0)
            .chain ("RETRO,FILTER,SPACE,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 12.0f).v (PID::voiceVariation, 0.26f)
            .v (PID::driftAmount, 0.22f).v (PID::driftRate, 0.06f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.74f)
            .v (PID::oscAUnison, 4.0f).v (PID::oscADetune, 0.14f)
            .v (PID::oscASpread, 0.42f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.50f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, -5.0f)
            .v (PID::subWave, ch::subTri).v (PID::subLevel, 0.42f)
            .v (PID::subHarmonics, 0.30f)
            .v (PID::bodyAmount, 0.58f).v (PID::bodyTilt, -0.20f)
            .v (PID::densityAmount, 0.52f)
            .v (PID::preFilterDrive, 0.22f).v (PID::postSaturation, 0.22f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1250.0f).v (PID::filterResonance, 0.16f)
            .v (PID::filterDrive, 0.30f).v (PID::filterKeyTrack, 0.45f)
            .v (PID::filterEnvAmount, 0.28f).v (PID::filterVelAmount, 0.30f)
            .v (PID::ampAttack, 0.55f).v (PID::ampDecay, 2.6f)
            .v (PID::ampSustain, 0.88f).v (PID::ampRelease, 2.6f)
            .v (PID::macroMemory, 0.48f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.62f).v (PID::memoryWobble, 0.32f)
            .v (PID::memoryDiffusion, 0.38f).v (PID::memoryAsymmetry, 0.18f)
            .v (PID::macroCharacter, 0.40f).v (PID::macroMotion, 0.30f)
            .v (PID::macroWorld, 0.30f).v (PID::macroWeight, 0.56f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.44f)
            .v (PID::weightCompress, 0.42f)
            .v (PID::retroEra, 0.18f).v (PID::retroAge, 0.40f)
            .v (PID::retroDrift, 0.26f).v (PID::retroWear, 0.16f)
            .v (PID::retroTone, -0.40f).v (PID::retroNoise, 0.14f)
            .v (PID::retroMix, 0.80f)
            .v (PID::fxFilterCutoff, 4200.0f).v (PID::fxFilterDrive, 0.16f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.26f)
            .v (PID::spaceSize, 0.38f).v (PID::spaceDecay, 2.0f)
            .v (PID::spaceFog, 0.42f).v (PID::spaceLight, -0.48f)
            .v (PID::spacePreDelay, 20.0f).v (PID::spaceMix, 0.22f)
            .v (PID::auraSize, 0.38f).v (PID::auraDistance, 0.22f)
            .v (PID::auraFog, 0.50f).v (PID::auraDecay, 0.40f)
            .v (PID::auraLight, -0.40f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.28f)
            .v (PID::patinaNoise, 0.18f).v (PID::patinaWear, 0.30f)
            .v (PID::patinaDrift, 0.22f)
            .v (PID::synthWidth, 0.80f).v (PID::highWidth, 0.85f)
            .v (PID::lowMonoFreq, 170.0f)
            .v (PID::breathAmount, 0.34f).v (PID::breathSpeed, 0.09f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.12f)
            .v (PID::lfo1Depth, 0.48f)
            .route (srcLfo1, PID::filterCutoff, 0.06f)
            .route (srcBreath, PID::densityAmount, 0.12f)
            .route (srcTouch, PID::filterCutoff, 0.18f));

        // The one pad where Grain is in the chain and doing the work: the
        // sound is re-read out of its own recent history.
        add (out, Build ("Endless Tape", "PADS", "DREAMY",
                         "granular,loop,drifting,soft",
                         "A loop that was never spliced, coming round again slightly changed.")
            .at (50, 3, 0.64f, 9.0)
            .chain ("RETRO,GRAIN,FILTER,SPACE,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 10.0f).v (PID::voiceVariation, 0.48f)
            .v (PID::driftAmount, 0.34f).v (PID::driftRate, 0.05f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tSoft)
            .v (PID::oscAWtPos, 0.40f).v (PID::oscALevel, 0.66f)
            .v (PID::oscAUnison, 3.0f).v (PID::oscADetune, 0.20f)
            .v (PID::oscASpread, 0.66f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.34f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, 9.0f)
            .v (PID::subLevel, 0.16f)
            .v (PID::bodyAmount, 0.26f).v (PID::densityAmount, 0.24f)
            .v (PID::postSaturation, 0.10f)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 2600.0f).v (PID::filterResonance, 0.10f)
            .v (PID::filterKeyTrack, 0.40f).v (PID::filterEnvAmount, 0.26f)
            .v (PID::ampAttack, 1.6f).v (PID::ampDecay, 4.0f)
            .v (PID::ampSustain, 0.80f).v (PID::ampRelease, 4.6f)
            .v (PID::macroMemory, 0.52f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.60f).v (PID::memoryWobble, 0.52f)
            .v (PID::memoryDiffusion, 0.56f).v (PID::memoryAsymmetry, 0.36f)
            .v (PID::macroCharacter, 0.34f).v (PID::macroMotion, 0.58f)
            .v (PID::macroWorld, 0.62f).v (PID::macroWeight, 0.26f)
            .v (PID::retroEra, 0.40f).v (PID::retroAge, 0.44f)
            .v (PID::retroDrift, 0.48f).v (PID::retroWear, 0.22f)
            .v (PID::retroTone, -0.24f).v (PID::retroNoise, 0.16f)
            .v (PID::retroMix, 0.70f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.30f)
            .v (PID::grainSize, 210.0f).v (PID::grainDensity, 11.0f)
            .v (PID::grainPosition, 0.42f).v (PID::grainPitchMode, ch::gRoot)
            .v (PID::grainSpread, 0.70f).v (PID::grainJitter, 0.34f)
            .v (PID::grainDirection, 0.22f).v (PID::grainWindow, ch::wGauss)
            .v (PID::grainFeedback, 0.24f).v (PID::grainMix, 0.46f)
            .v (PID::fxFilterCutoff, 5400.0f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.52f)
            .v (PID::spaceSize, 0.70f).v (PID::spaceDecay, 6.0f)
            .v (PID::spaceFog, 0.60f).v (PID::spaceLight, -0.18f)
            .v (PID::spacePreDelay, 28.0f).v (PID::spaceMix, 0.36f)
            .v (PID::auraSize, 0.64f).v (PID::auraDistance, 0.42f)
            .v (PID::auraFog, 0.66f).v (PID::auraDecay, 0.60f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.12f)
            .v (PID::patinaNoise, 0.14f).v (PID::patinaWear, 0.34f)
            .v (PID::patinaDrift, 0.36f)
            .v (PID::synthWidth, 1.20f).v (PID::highWidth, 1.25f)
            .v (PID::breathAmount, 0.58f).v (PID::breathSpeed, 0.09f)
            .v (PID::breathRandom, 0.66f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.08f)
            .v (PID::lfo2Depth, 0.65f)
            .route (srcLfo2, PID::grainPosition, 0.40f)
            .route (srcBreath, PID::grainSize, 0.22f)
            .route (srcMotion, PID::grainJitter, 0.18f));
    }
}
