#include "PresetBuilder.h"
#include "Builders.h"

namespace nacar::presets::detail
{
    // ===============================================================
    //  PERCUSSION
    // ===============================================================
    void buildPercussion (std::vector<FactoryPreset>& out)
    {
        add (out, Build ("Found Metal", "PERCUSSION", "BROKEN",
                         "ring mod,inharmonic,struck,scrap",
                         "Something metal picked up off the floor and hit with something else.")
            .at (58, 1, 0.95f, 2.5)
            .chain ("FILTER,CRUSH,RETRO,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::masterGain, 8.0f)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.58f)
            .v (PID::driftAmount, 0.12f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tMetal)
            .v (PID::oscAWtPos, 0.54f).v (PID::oscALevel, 0.68f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::square).v (PID::oscBLevel, 0.20f)
            .v (PID::oscBSemi, 3.0f).v (PID::oscBFine, 31.0f)
            .v (PID::oscBPulseWidth, 0.22f)
            .v (PID::oscRingMod, 0.58f).v (PID::oscPmAmount, 0.18f)
            .v (PID::subLevel, 0.10f)
            .v (PID::noiseType, ch::nDigital).v (PID::noiseLevel, 0.22f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.18f).v (PID::densityAmount, 0.14f)
            .v (PID::preFilterDrive, 0.28f).v (PID::postSaturation, 0.22f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 2800.0f).v (PID::filterResonance, 0.34f)
            .v (PID::filterKeyTrack, 0.70f).v (PID::filterEnvAmount, 0.48f)
            .v (PID::filterVelAmount, 0.60f)
            .v (PID::ampAttack, 0.0005f).v (PID::ampDecay, 0.70f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.34f)
            .v (PID::ampVelocity, 0.72f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.08f)
            .v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.44f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.48f).v (PID::memoryWobble, 0.30f)
            .v (PID::memoryAsymmetry, 0.46f)
            .v (PID::macroCharacter, 0.58f).v (PID::macroMotion, 0.30f)
            .v (PID::macroWorld, 0.28f).v (PID::macroWeight, 0.26f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.38f)
            .v (PID::crushBits, 9.0f).v (PID::crushRate, 16000.0f)
            .v (PID::crushJitter, 0.30f).v (PID::crushMix, 0.48f)
            .v (PID::retroEra, 0.78f).v (PID::retroAge, 0.40f)
            .v (PID::retroDrift, 0.16f).v (PID::retroWear, 0.38f)
            .v (PID::retroNoise, 0.16f).v (PID::retroMix, 0.62f)
            .v (PID::fxFilterCutoff, 9500.0f).v (PID::fxFilterRes, 0.20f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.36f)
            .v (PID::spaceSize, 0.40f).v (PID::spaceDecay, 2.2f)
            .v (PID::spaceFog, 0.36f).v (PID::spaceLight, 0.12f)
            .v (PID::spaceMix, 0.22f)
            .v (PID::auraSize, 0.38f).v (PID::auraDistance, 0.26f)
            .v (PID::auraFog, 0.36f).v (PID::auraDecay, 0.34f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.14f)
            .v (PID::patinaNoise, 0.16f).v (PID::patinaWear, 0.34f)
            .v (PID::synthWidth, 1.00f).v (PID::highWidth, 1.12f)
            .v (PID::breathAmount, 0.30f).v (PID::breathSpeed, 0.50f)
            .route (srcOrganic, PID::oscRingMod, 0.22f)
            .route (srcBreath, PID::oscAWtPos, 0.20f));

        add (out, Build ("Driftwood", "PERCUSSION", "MINIMAL",
                         "wood,comb,dry,block",
                         "A piece of wood that has been in the sea, struck once.")
            .at (62, 1, 0.86f, 1.6)
            .chain ("FILTER,RETRO,SPACE,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.44f)
            .v (PID::driftAmount, 0.10f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.34f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBLevel, 0.0f)
            .v (PID::subLevel, 0.10f).v (PID::subHarmonics, 0.30f)
            .v (PID::noiseType, ch::nTexture).v (PID::noiseLevel, 0.60f)
            .v (PID::noiseAttackOnly, 0.85f)
            .v (PID::bodyAmount, 0.44f).v (PID::bodyTilt, 0.24f)
            .v (PID::densityAmount, 0.16f)
            .v (PID::preFilterDrive, 0.16f).v (PID::postSaturation, 0.14f)
            .v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1050.0f).v (PID::filterResonance, 0.56f)
            .v (PID::filterKeyTrack, 1.0f).v (PID::filterEnvAmount, 0.24f)
            .v (PID::filterVelAmount, 0.50f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Lp)
            .v (PID::filter2Cutoff, 4200.0f).v (PID::filter2Res, 0.10f)
            .v (PID::filter2Mix, 0.60f)
            .v (PID::ampAttack, 0.0005f).v (PID::ampDecay, 0.42f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.20f)
            .v (PID::ampVelocity, 0.70f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.06f)
            .v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.22f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.38f).v (PID::memoryWobble, 0.14f)
            .v (PID::macroCharacter, 0.32f).v (PID::macroMotion, 0.22f)
            .v (PID::macroWorld, 0.24f).v (PID::macroWeight, 0.34f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::retroEra, 0.28f).v (PID::retroAge, 0.30f)
            .v (PID::retroDrift, 0.12f).v (PID::retroWear, 0.14f)
            .v (PID::retroTone, -0.22f).v (PID::retroNoise, 0.12f)
            .v (PID::retroMix, 0.52f)
            .v (PID::fxFilterCutoff, 6000.0f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.22f)
            .v (PID::spaceSize, 0.20f).v (PID::spaceDecay, 0.6f)
            .v (PID::spaceFog, 0.20f).v (PID::spaceLight, -0.18f)
            .v (PID::spaceMix, 0.16f)
            .v (PID::auraSize, 0.22f).v (PID::auraDistance, 0.14f)
            .v (PID::auraFog, 0.26f).v (PID::auraDecay, 0.16f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.08f)
            .v (PID::patinaNoise, 0.10f).v (PID::patinaWear, 0.20f)
            .v (PID::synthWidth, 0.90f)
            .v (PID::breathAmount, 0.22f).v (PID::breathSpeed, 0.40f)
            .route (srcOrganic, PID::filterCutoff, 0.08f));

        add (out, Build ("Rust Bell", "PERCUSSION", "DIRTY",
                         "metal,decay,generation iii,struck",
                         "A bell that has been outside so long the ring has gone brown.")
            .at (53, 1, 0.90f, 4.0)
            .chain ("RETRO,FILTER,CRUSH,GRAIN,SPACE,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.46f)
            .v (PID::driftAmount, 0.26f).v (PID::driftRate, 0.18f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tAsym)
            .v (PID::oscAWtPos, 0.36f).v (PID::oscALevel, 0.72f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.26f)
            .v (PID::oscBSemi, 8.0f).v (PID::oscBFine, 26.0f)
            .v (PID::oscRingMod, 0.34f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.10f)
            .v (PID::subHarmonics, 0.24f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.18f)
            .v (PID::noiseAttackOnly, 0.90f)
            .v (PID::bodyAmount, 0.24f).v (PID::densityAmount, 0.26f)
            .v (PID::preFilterDrive, 0.34f).v (PID::postSaturation, 0.30f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 4600.0f).v (PID::filterResonance, 0.30f)
            .v (PID::filterDrive, 0.36f).v (PID::filterKeyTrack, 0.80f)
            .v (PID::filterEnvAmount, 0.44f).v (PID::filterVelAmount, 0.55f)
            .v (PID::ampAttack, 0.0008f).v (PID::ampDecay, 2.8f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 1.4f)
            .v (PID::ampVelocity, 0.66f)
            .v (PID::env1Attack, 0.0006f).v (PID::env1Decay, 0.30f)
            .v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.60f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.62f).v (PID::memoryWobble, 0.46f)
            .v (PID::memoryDiffusion, 0.40f).v (PID::memoryAsymmetry, 0.48f)
            .v (PID::macroCharacter, 0.62f).v (PID::macroMotion, 0.40f)
            .v (PID::macroWorld, 0.42f).v (PID::macroWeight, 0.34f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.26f)
            .v (PID::crushBits, 11.0f).v (PID::crushRate, 19000.0f)
            .v (PID::crushJitter, 0.20f).v (PID::crushMix, 0.38f)
            .v (PID::retroEra, 0.18f).v (PID::retroAge, 0.66f)
            .v (PID::retroDrift, 0.34f).v (PID::retroWear, 0.44f)
            .v (PID::retroTone, -0.06f).v (PID::retroNoise, 0.24f)
            .v (PID::retroMix, 0.88f)
            .v (PID::fxFilterCutoff, 6800.0f).v (PID::fxFilterRes, 0.16f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.40f)
            .v (PID::spaceSize, 0.52f).v (PID::spaceDecay, 3.4f)
            .v (PID::spaceFog, 0.46f).v (PID::spaceLight, -0.24f)
            .v (PID::spaceMix, 0.30f)
            .v (PID::auraSize, 0.46f).v (PID::auraDistance, 0.30f)
            .v (PID::auraFog, 0.46f).v (PID::auraDecay, 0.44f)
            .v (PID::auraLight, -0.18f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.02f)
            .v (PID::patinaNoise, 0.24f).v (PID::patinaWear, 0.48f)
            .v (PID::patinaDrift, 0.30f)
            .v (PID::synthWidth, 1.05f).v (PID::highWidth, 1.15f)
            .v (PID::breathAmount, 0.40f).v (PID::breathSpeed, 0.30f)
            .route (srcBreath, PID::oscAWtPos, 0.22f)
            .route (srcOrganic, PID::filterCutoff, 0.12f));
    }
}
