#include "PresetBuilder.h"
#include "Builders.h"

namespace nacar::presets::detail
{
    // ===============================================================
    //  PERCUSSION
    // ===============================================================
    void buildPercussion (std::vector<FactoryPreset>& out)
    {
        add (out, Build ("Found Metal", "PERCUSSION", "BROKEN",
                         "ring mod,inharmonic,struck,scrap",
                         "Something metal picked up off the floor and hit with something else.")
            .at (58, 1, 0.95f, 2.5)
            .chain ("FILTER,CRUSH,RETRO,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::masterGain, 8.0f)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.58f)
            .v (PID::driftAmount, 0.12f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tMetal)
            .v (PID::oscAWtPos, 0.54f).v (PID::oscALevel, 0.68f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::square).v (PID::oscBLevel, 0.20f)
            .v (PID::oscBSemi, 3.0f).v (PID::oscBFine, 31.0f)
            .v (PID::oscBPulseWidth, 0.22f)
            .v (PID::oscRingMod, 0.58f).v (PID::oscPmAmount, 0.18f)
            .v (PID::subLevel, 0.10f)
            .v (PID::noiseType, ch::nDigital).v (PID::noiseLevel, 0.22f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.18f).v (PID::densityAmount, 0.14f)
            .v (PID::preFilterDrive, 0.28f).v (PID::postSaturation, 0.22f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 2800.0f).v (PID::filterResonance, 0.34f)
            .v (PID::filterKeyTrack, 0.70f).v (PID::filterEnvAmount, 0.48f)
            .v (PID::filterVelAmount, 0.60f)
            .v (PID::ampAttack, 0.0005f).v (PID::ampDecay, 0.70f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.34f)
            .v (PID::ampVelocity, 0.72f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.08f)
            .v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.44f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.48f).v (PID::memoryWobble, 0.30f)
            .v (PID::memoryAsymmetry, 0.46f)
            .v (PID::macroCharacter, 0.58f).v (PID::macroMotion, 0.30f)
            .v (PID::macroWorld, 0.28f).v (PID::macroWeight, 0.26f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.38f)
            .v (PID::crushBits, 9.0f).v (PID::crushRate, 16000.0f)
            .v (PID::crushJitter, 0.30f).v (PID::crushMix, 0.48f)
            .v (PID::retroEra, 0.78f).v (PID::retroAge, 0.40f)
            .v (PID::retroDrift, 0.16f).v (PID::retroWear, 0.38f)
            .v (PID::retroNoise, 0.16f).v (PID::retroMix, 0.62f)
            .v (PID::fxFilterCutoff, 9500.0f).v (PID::fxFilterRes, 0.20f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.36f)
            .v (PID::spaceSize, 0.40f).v (PID::spaceDecay, 2.2f)
            .v (PID::spaceFog, 0.36f).v (PID::spaceLight, 0.12f)
            .v (PID::spaceMix, 0.22f)
            .v (PID::auraSize, 0.38f).v (PID::auraDistance, 0.26f)
            .v (PID::auraFog, 0.36f).v (PID::auraDecay, 0.34f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.14f)
            .v (PID::patinaNoise, 0.16f).v (PID::patinaWear, 0.34f)
            .v (PID::synthWidth, 1.00f).v (PID::highWidth, 1.12f)
            .v (PID::breathAmount, 0.30f).v (PID::breathSpeed, 0.50f)
            .route (srcOrganic, PID::oscRingMod, 0.22f)
            .route (srcBreath, PID::oscAWtPos, 0.20f));

        add (out, Build ("Driftwood", "PERCUSSION", "MINIMAL",
                         "wood,comb,dry,block",
                         "A piece of wood that has been in the sea, struck once.")
            .at (62, 1, 0.86f, 1.6)
            .chain ("FILTER,RETRO,SPACE,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.44f)
            .v (PID::driftAmount, 0.10f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.34f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBLevel, 0.0f)
            .v (PID::subLevel, 0.10f).v (PID::subHarmonics, 0.30f)
            .v (PID::noiseType, ch::nTexture).v (PID::noiseLevel, 0.60f)
            .v (PID::noiseAttackOnly, 0.85f)
            .v (PID::bodyAmount, 0.44f).v (PID::bodyTilt, 0.24f)
            .v (PID::densityAmount, 0.16f)
            .v (PID::preFilterDrive, 0.16f).v (PID::postSaturation, 0.14f)
            .v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1050.0f).v (PID::filterResonance, 0.56f)
            .v (PID::filterKeyTrack, 1.0f).v (PID::filterEnvAmount, 0.24f)
            .v (PID::filterVelAmount, 0.50f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Lp)
            .v (PID::filter2Cutoff, 4200.0f).v (PID::filter2Res, 0.10f)
            .v (PID::filter2Mix, 0.60f)
            .v (PID::ampAttack, 0.0005f).v (PID::ampDecay, 0.42f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.20f)
            .v (PID::ampVelocity, 0.70f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.06f)
            .v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.22f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.38f).v (PID::memoryWobble, 0.14f)
            .v (PID::macroCharacter, 0.32f).v (PID::macroMotion, 0.22f)
            .v (PID::macroWorld, 0.24f).v (PID::macroWeight, 0.34f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::retroEra, 0.28f).v (PID::retroAge, 0.30f)
            .v (PID::retroDrift, 0.12f).v (PID::retroWear, 0.14f)
            .v (PID::retroTone, -0.22f).v (PID::retroNoise, 0.12f)
            .v (PID::retroMix, 0.52f)
            .v (PID::fxFilterCutoff, 6000.0f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.22f)
            .v (PID::spaceSize, 0.20f).v (PID::spaceDecay, 0.6f)
            .v (PID::spaceFog, 0.20f).v (PID::spaceLight, -0.18f)
            .v (PID::spaceMix, 0.16f)
            .v (PID::auraSize, 0.22f).v (PID::auraDistance, 0.14f)
            .v (PID::auraFog, 0.26f).v (PID::auraDecay, 0.16f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.08f)
            .v (PID::patinaNoise, 0.10f).v (PID::patinaWear, 0.20f)
            .v (PID::synthWidth, 0.90f)
            .v (PID::breathAmount, 0.22f).v (PID::breathSpeed, 0.40f)
            .route (srcOrganic, PID::filterCutoff, 0.08f));

        add (out, Build ("Rust Bell", "PERCUSSION", "DIRTY",
                         "metal,decay,generation iii,struck",
                         "A bell that has been outside so long the ring has gone brown.")
            .at (53, 1, 0.90f, 4.0)
            .chain ("RETRO,FILTER,CRUSH,GRAIN,SPACE,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.46f)
            .v (PID::driftAmount, 0.26f).v (PID::driftRate, 0.18f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tAsym)
            .v (PID::oscAWtPos, 0.36f).v (PID::oscALevel, 0.72f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.26f)
            .v (PID::oscBSemi, 8.0f).v (PID::oscBFine, 26.0f)
            .v (PID::oscRingMod, 0.34f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.10f)
            .v (PID::subHarmonics, 0.24f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.18f)
            .v (PID::noiseAttackOnly, 0.90f)
            .v (PID::bodyAmount, 0.24f).v (PID::densityAmount, 0.26f)
            .v (PID::preFilterDrive, 0.34f).v (PID::postSaturation, 0.30f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 4600.0f).v (PID::filterResonance, 0.30f)
            .v (PID::filterDrive, 0.36f).v (PID::filterKeyTrack, 0.80f)
            .v (PID::filterEnvAmount, 0.44f).v (PID::filterVelAmount, 0.55f)
            .v (PID::ampAttack, 0.0008f).v (PID::ampDecay, 2.8f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 1.4f)
            .v (PID::ampVelocity, 0.66f)
            .v (PID::env1Attack, 0.0006f).v (PID::env1Decay, 0.30f)
            .v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.60f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.62f).v (PID::memoryWobble, 0.46f)
            .v (PID::memoryDiffusion, 0.40f).v (PID::memoryAsymmetry, 0.48f)
            .v (PID::macroCharacter, 0.62f).v (PID::macroMotion, 0.40f)
            .v (PID::macroWorld, 0.42f).v (PID::macroWeight, 0.34f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.26f)
            .v (PID::crushBits, 11.0f).v (PID::crushRate, 19000.0f)
            .v (PID::crushJitter, 0.20f).v (PID::crushMix, 0.38f)
            .v (PID::retroEra, 0.18f).v (PID::retroAge, 0.66f)
            .v (PID::retroDrift, 0.34f).v (PID::retroWear, 0.44f)
            .v (PID::retroTone, -0.06f).v (PID::retroNoise, 0.24f)
            .v (PID::retroMix, 0.88f)
            .v (PID::fxFilterCutoff, 6800.0f).v (PID::fxFilterRes, 0.16f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.40f)
            .v (PID::spaceSize, 0.52f).v (PID::spaceDecay, 3.4f)
            .v (PID::spaceFog, 0.46f).v (PID::spaceLight, -0.24f)
            .v (PID::spaceMix, 0.30f)
            .v (PID::auraSize, 0.46f).v (PID::auraDistance, 0.30f)
            .v (PID::auraFog, 0.46f).v (PID::auraDecay, 0.44f)
            .v (PID::auraLight, -0.18f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.02f)
            .v (PID::patinaNoise, 0.24f).v (PID::patinaWear, 0.48f)
            .v (PID::patinaDrift, 0.30f)
            .v (PID::synthWidth, 1.05f).v (PID::highWidth, 1.15f)
            .v (PID::breathAmount, 0.40f).v (PID::breathSpeed, 0.30f)
            .route (srcBreath, PID::oscAWtPos, 0.22f)
            .route (srcOrganic, PID::filterCutoff, 0.12f));

        // -- the hand-played Latin layer ---------------------------------
        //  The pitch fall that makes a struck membrane read as a membrane is
        //  made here by `pitch_env_amt`: mod envelope 2 into oscillator pitch,
        //  in semitones, POSITIVE so the note starts above and falls onto the
        //  key that was pressed.  Envelope 2 defaults slow, so every preset
        //  that asks for it sets its own shape - attack half a millisecond,
        //  decay in the tens of milliseconds, no sustain - because this
        //  category is over inside its first fifty.  Depths stay in the two to
        //  eight semitone range a hand drum bends over; two octaves is a kick,
        //  not a skin.  `pm_env_amt` is the same envelope into the PM index,
        //  for the struck metal and clay whose inharmonic edge goes before
        //  their body does.  ENV 1 is left to `filter_env_amt` alone, which is
        //  now the attack brightness of the hit and nothing else: where it was
        //  standing in for the fall it has been cut back to what the
        //  brightness needs on its own.

        add (out, Build ("Quinto Abierto", "PERCUSSION", "WARM",
                         "conga,skin,open,hand",
                         "Built the way an open conga tone is built: a triangle body under a pink-noise slap, with mod envelope 2 dropping the pitch five semitones onto the note across the first thirty milliseconds.")
            .at (50, 1, 0.92f, 1.8)
            .chain ("FILTER,RETRO,CRUSH,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::masterGain, 4.0f)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.26f)
            .v (PID::driftAmount, 0.06f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.72f)
            .v (PID::oscAPhase, ch::phaseReset).v (PID::oscAPhaseOffset, 0.12f)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.24f)
            .v (PID::oscBSemi, 7.0f).v (PID::oscBFine, 9.0f)
            .v (PID::oscBPhase, ch::phaseReset)
            .v (PID::pitchEnvAmount, 5.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.16f)
            .v (PID::subHarmonics, 0.28f)
            .v (PID::noiseType, ch::nPink).v (PID::noiseLevel, 0.34f)
            .v (PID::noiseAttackOnly, 0.95f)
            .v (PID::bodyAmount, 0.54f).v (PID::bodyTilt, 0.18f)
            .v (PID::densityAmount, 0.18f)
            .v (PID::preFilterDrive, 0.20f).v (PID::postSaturation, 0.16f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 420.0f).v (PID::filterResonance, 0.52f)
            .v (PID::filterDrive, 0.26f).v (PID::filterKeyTrack, 1.0f)
            .v (PID::filterEnvAmount, 0.30f).v (PID::filterVelAmount, 0.52f)
            .v (PID::ampAttack, 0.0008f).v (PID::ampDecay, 0.30f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.10f)
            .v (PID::ampVelocity, 0.62f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.028f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.03f)
            .v (PID::env2Attack, 0.0005f).v (PID::env2Decay, 0.030f)
            .v (PID::env2Sustain, 0.0f).v (PID::env2Release, 0.03f)
            .v (PID::macroMemory, 0.16f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.32f).v (PID::memoryWobble, 0.06f)
            .v (PID::macroCharacter, 0.34f).v (PID::macroMotion, 0.14f)
            .v (PID::macroWorld, 0.22f).v (PID::macroWeight, 0.44f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.42f)
            .v (PID::retroEra, 0.34f).v (PID::retroAge, 0.22f)
            .v (PID::retroDrift, 0.05f).v (PID::retroWear, 0.08f)
            .v (PID::retroTone, -0.18f).v (PID::retroNoise, 0.07f)
            .v (PID::retroMix, 0.42f)
            .v (PID::fxFilterCutoff, 7200.0f).v (PID::fxFilterRes, 0.10f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.18f)
            .v (PID::spaceSize, 0.22f).v (PID::spaceDecay, 0.5f)
            .v (PID::spaceFog, 0.22f).v (PID::spaceLight, -0.22f)
            .v (PID::spacePreDelay, 6.0f).v (PID::spaceMix, 0.14f)
            .v (PID::auraSize, 0.20f).v (PID::auraDistance, 0.14f)
            .v (PID::auraFog, 0.24f).v (PID::auraDecay, 0.16f)
            .v (PID::auraLight, -0.20f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.12f)
            .v (PID::patinaNoise, 0.08f).v (PID::patinaWear, 0.14f)
            .v (PID::synthWidth, 0.70f).v (PID::highWidth, 0.85f)
            .v (PID::lowMonoFreq, 200.0f)
            .v (PID::breathAmount, 0.16f).v (PID::breathSpeed, 0.60f)
            .route (srcOrganic, PID::filterCutoff, 0.06f)
            .route (srcTouch, PID::filterCutoff, 0.12f));

        add (out, Build ("Tumbao Cerrado", "PERCUSSION", "INTIMATE",
                         "conga,muted,comb,hand",
                         "The muted stroke of the same drum: the body cut to seventy-five milliseconds, a COMB primary filter standing in for a hand left on the head, and four semitones of mod envelope 2 into pitch over the first twelve milliseconds.")
            .at (43, 1, 0.80f, 1.5)
            .chain ("RETRO,FILTER,CRUSH,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::masterGain, 5.0f)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.22f)
            .v (PID::driftAmount, 0.04f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.58f)
            .v (PID::oscAPhase, ch::phaseReset).v (PID::oscAPhaseOffset, 0.20f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.18f)
            .v (PID::oscBSemi, 5.0f).v (PID::oscBFine, -14.0f)
            .v (PID::pitchEnvAmount, 4.0f)
            .v (PID::subLevel, 0.12f).v (PID::subHarmonics, 0.22f)
            .v (PID::noiseType, ch::nDark).v (PID::noiseLevel, 0.26f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.48f).v (PID::bodyTilt, -0.20f)
            .v (PID::densityAmount, 0.12f)
            .v (PID::preFilterDrive, 0.14f).v (PID::postSaturation, 0.10f)
            .v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 620.0f).v (PID::filterResonance, 0.44f)
            .v (PID::filterKeyTrack, 1.0f).v (PID::filterEnvAmount, 0.22f)
            .v (PID::filterVelAmount, 0.45f)
            .v (PID::ampAttack, 0.0006f).v (PID::ampDecay, 0.075f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.05f)
            .v (PID::ampVelocity, 0.58f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.018f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.02f)
            .v (PID::env2Attack, 0.0005f).v (PID::env2Decay, 0.012f)
            .v (PID::env2Sustain, 0.0f).v (PID::env2Release, 0.02f)
            .v (PID::macroMemory, 0.12f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.28f)
            .v (PID::macroCharacter, 0.26f).v (PID::macroMotion, 0.10f)
            .v (PID::macroWorld, 0.14f).v (PID::macroWeight, 0.38f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::retroEra, 0.30f).v (PID::retroAge, 0.18f)
            .v (PID::retroDrift, 0.04f).v (PID::retroWear, 0.06f)
            .v (PID::retroTone, -0.24f).v (PID::retroNoise, 0.05f)
            .v (PID::retroMix, 0.36f)
            .v (PID::fxFilterCutoff, 5200.0f).v (PID::fxFilterRes, 0.08f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.10f)
            .v (PID::spaceSize, 0.14f).v (PID::spaceDecay, 0.3f)
            .v (PID::spaceFog, 0.14f).v (PID::spaceLight, -0.34f)
            .v (PID::spacePreDelay, 3.0f).v (PID::spaceMix, 0.07f)
            .v (PID::auraSize, 0.12f).v (PID::auraDistance, 0.08f)
            .v (PID::auraFog, 0.18f).v (PID::auraDecay, 0.08f)
            .v (PID::auraLight, -0.28f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.16f)
            .v (PID::patinaNoise, 0.05f).v (PID::patinaWear, 0.10f)
            .v (PID::synthWidth, 0.55f).v (PID::highWidth, 0.70f)
            .v (PID::lowMonoFreq, 220.0f)
            .v (PID::breathAmount, 0.10f).v (PID::breathSpeed, 0.50f)
            .route (srcTouch, PID::filterCutoff, 0.10f));

        add (out, Build ("Bongó de Palma", "PERCUSSION", "AGGRESSIVE",
                         "bongo,slap,hand,street",
                         "The slap articulation: a white-noise crack band-passed through the HAZE filter over a short high membrane, the membrane given three semitones of mod envelope 2 into pitch, high-passed clear of the body and finished inside ninety milliseconds.")
            .at (52, 1, 1.0f, 1.5)
            .chain ("CRUSH,FILTER,RETRO,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::masterGain, 3.0f)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.30f)
            .v (PID::driftAmount, 0.05f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.44f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::square).v (PID::oscBLevel, 0.16f)
            .v (PID::oscBSemi, 11.0f).v (PID::oscBFine, 24.0f)
            .v (PID::oscBPulseWidth, 0.35f)
            .v (PID::oscRingMod, 0.18f)
            .v (PID::pitchEnvAmount, 3.0f)
            .v (PID::subLevel, 0.06f)
            .v (PID::noiseType, ch::nWhite).v (PID::noiseLevel, 0.78f)
            .v (PID::noiseAttackOnly, 0.80f)
            .v (PID::bodyAmount, 0.26f).v (PID::densityAmount, 0.14f)
            .v (PID::preFilterDrive, 0.34f).v (PID::postSaturation, 0.28f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 2600.0f).v (PID::filterResonance, 0.30f)
            .v (PID::filterKeyTrack, 0.55f).v (PID::filterEnvAmount, 0.60f)
            .v (PID::filterVelAmount, 0.62f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Hp)
            .v (PID::filter2Cutoff, 380.0f).v (PID::filter2Res, 0.12f)
            .v (PID::filter2Mix, 0.70f)
            .v (PID::ampAttack, 0.0005f).v (PID::ampDecay, 0.085f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.05f)
            .v (PID::ampVelocity, 0.70f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.014f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.02f)
            .v (PID::env2Attack, 0.0005f).v (PID::env2Decay, 0.010f)
            .v (PID::env2Sustain, 0.0f).v (PID::env2Release, 0.02f)
            .v (PID::macroMemory, 0.18f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.40f).v (PID::memoryWobble, 0.06f)
            .v (PID::macroCharacter, 0.52f).v (PID::macroMotion, 0.12f)
            .v (PID::macroWorld, 0.20f).v (PID::macroWeight, 0.28f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.30f)
            .v (PID::crushBits, 11.0f).v (PID::crushRate, 24000.0f)
            .v (PID::crushDrive, 0.26f).v (PID::crushTone, 0.16f)
            .v (PID::crushMix, 0.40f)
            .v (PID::retroEra, 0.40f).v (PID::retroAge, 0.26f)
            .v (PID::retroDrift, 0.05f).v (PID::retroWear, 0.10f)
            .v (PID::retroTone, -0.04f).v (PID::retroNoise, 0.08f)
            .v (PID::retroMix, 0.46f)
            .v (PID::fxFilterCutoff, 11000.0f).v (PID::fxFilterRes, 0.12f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.16f)
            .v (PID::spaceSize, 0.18f).v (PID::spaceDecay, 0.4f)
            .v (PID::spaceFog, 0.18f).v (PID::spaceLight, 0.06f)
            .v (PID::spacePreDelay, 5.0f).v (PID::spaceMix, 0.12f)
            .v (PID::auraSize, 0.18f).v (PID::auraDistance, 0.10f)
            .v (PID::auraFog, 0.20f).v (PID::auraDecay, 0.12f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, 0.04f)
            .v (PID::patinaNoise, 0.08f).v (PID::patinaWear, 0.16f)
            .v (PID::synthWidth, 0.85f).v (PID::highWidth, 1.05f)
            .v (PID::breathAmount, 0.12f).v (PID::breathSpeed, 0.80f)
            .route (srcOrganic, PID::filterCutoff, 0.08f)
            .route (srcWheel, PID::crushAmount, 0.20f));

        add (out, Build ("Campana de Barrio", "PERCUSSION", "COLD",
                         "cowbell,metal,dembow,street",
                         "Two pulse waves a tritone apart with phase modulation between them whose index is opened by mod envelope 2 and back to its resting depth inside forty milliseconds, band-passed and then high-passed clear of the body, which is how a cowbell is built.")
            .at (48, 1, 1.0f, 1.5)
            .chain ("FILTER,CRUSH,SPACE,RETRO,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::masterGain, 1.0f)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.14f)
            .v (PID::driftAmount, 0.03f)
            .v (PID::oscAWave, ch::square).v (PID::oscALevel, 0.66f)
            .v (PID::oscAOctave, 2.0f).v (PID::oscAPulseWidth, 0.38f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::square).v (PID::oscBLevel, 0.52f)
            .v (PID::oscBOctave, 2.0f).v (PID::oscBSemi, 6.0f)
            .v (PID::oscBFine, 8.0f).v (PID::oscBPulseWidth, 0.46f)
            .v (PID::oscBPhase, ch::phaseReset)
            .v (PID::oscPmAmount, 0.10f).v (PID::pmEnvAmount, 0.16f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nDigital).v (PID::noiseLevel, 0.10f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.14f).v (PID::bodyTilt, 0.30f)
            .v (PID::densityAmount, 0.10f)
            .v (PID::preFilterDrive, 0.30f).v (PID::postSaturation, 0.24f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 1500.0f).v (PID::filterResonance, 0.22f)
            .v (PID::filterKeyTrack, 0.35f).v (PID::filterEnvAmount, 0.30f)
            .v (PID::filterVelAmount, 0.40f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Hp)
            .v (PID::filter2Cutoff, 520.0f).v (PID::filter2Res, 0.10f)
            .v (PID::filter2Mix, 0.80f)
            .v (PID::ampAttack, 0.0005f).v (PID::ampDecay, 0.16f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.07f)
            .v (PID::ampVelocity, 0.55f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.012f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.02f)
            .v (PID::env2Attack, 0.0005f).v (PID::env2Decay, 0.040f)
            .v (PID::env2Sustain, 0.0f).v (PID::env2Release, 0.04f)
            .v (PID::macroMemory, 0.20f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.44f).v (PID::memoryWobble, 0.05f)
            .v (PID::macroCharacter, 0.50f).v (PID::macroMotion, 0.08f)
            .v (PID::macroWorld, 0.18f).v (PID::macroWeight, 0.20f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.34f)
            .v (PID::crushBits, 10.0f).v (PID::crushRate, 26000.0f)
            .v (PID::crushJitter, 0.06f).v (PID::crushDrive, 0.24f)
            .v (PID::crushTone, 0.18f).v (PID::crushMix, 0.46f)
            .v (PID::retroEra, 0.52f).v (PID::retroAge, 0.20f)
            .v (PID::retroDrift, 0.04f).v (PID::retroWear, 0.08f)
            .v (PID::retroTone, 0.06f).v (PID::retroNoise, 0.07f)
            .v (PID::retroMix, 0.40f)
            .v (PID::fxFilterCutoff, 12000.0f).v (PID::fxFilterRes, 0.10f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.14f)
            .v (PID::spaceSize, 0.16f).v (PID::spaceDecay, 0.4f)
            .v (PID::spaceFog, 0.16f).v (PID::spaceLight, 0.10f)
            .v (PID::spacePreDelay, 4.0f).v (PID::spaceMix, 0.10f)
            .v (PID::auraSize, 0.16f).v (PID::auraDistance, 0.10f)
            .v (PID::auraFog, 0.16f).v (PID::auraDecay, 0.10f)
            .v (PID::auraLight, 0.08f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.10f)
            .v (PID::patinaNoise, 0.06f).v (PID::patinaWear, 0.14f)
            .v (PID::synthWidth, 0.75f).v (PID::highWidth, 0.95f)
            .v (PID::lowMonoFreq, 180.0f)
            .v (PID::breathOn, 0.0f).v (PID::breathAmount, 0.0f)
            .route (srcWheel, PID::filterCutoff, 0.14f)
            .route (srcOrganic, PID::oscBFine, 0.06f));


        add (out, Build ("Timbal de Lata", "PERCUSSION", "DIRTY",
                         "timbale,metal,shell,struck",
                         "A METALLIC wavetable struck at a fixed phase and high-passed through the MASS ladder, with a COMB second filter in place of a shallow steel shell and two semitones of mod envelope 2 into pitch on the strike.")
            .at (51, 1, 0.95f, 2.0)
            .chain ("RETRO,CRUSH,FILTER,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::masterGain, 2.0f)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.28f)
            .v (PID::driftAmount, 0.08f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tMetal)
            .v (PID::oscAWtPos, 0.28f).v (PID::oscALevel, 0.70f)
            .v (PID::oscAOctave, 1.0f).v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.22f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBSemi, 3.0f)
            .v (PID::oscBFine, 17.0f)
            .v (PID::oscRingMod, 0.16f)
            .v (PID::pitchEnvAmount, 2.0f)
            .v (PID::subLevel, 0.08f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.30f)
            .v (PID::noiseAttackOnly, 0.92f)
            .v (PID::bodyAmount, 0.22f).v (PID::bodyTilt, 0.28f)
            .v (PID::densityAmount, 0.18f)
            .v (PID::preFilterDrive, 0.32f).v (PID::postSaturation, 0.26f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::hp)
            .v (PID::filterCutoff, 340.0f).v (PID::filterResonance, 0.26f)
            .v (PID::filterDrive, 0.30f).v (PID::filterKeyTrack, 0.60f)
            .v (PID::filterEnvAmount, -0.42f).v (PID::filterVelAmount, 0.50f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Comb)
            .v (PID::filter2Cutoff, 1800.0f).v (PID::filter2Res, 0.42f)
            .v (PID::filter2Mix, 0.45f)
            .v (PID::ampAttack, 0.0005f).v (PID::ampDecay, 0.24f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.14f)
            .v (PID::ampVelocity, 0.64f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.022f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.03f)
            .v (PID::env2Attack, 0.0005f).v (PID::env2Decay, 0.012f)
            .v (PID::env2Sustain, 0.0f).v (PID::env2Release, 0.02f)
            .v (PID::macroMemory, 0.30f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.50f).v (PID::memoryWobble, 0.12f)
            .v (PID::memoryAsymmetry, 0.22f)
            .v (PID::macroCharacter, 0.58f).v (PID::macroMotion, 0.14f)
            .v (PID::macroWorld, 0.26f).v (PID::macroWeight, 0.24f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.24f)
            .v (PID::crushBits, 12.0f).v (PID::crushRate, 21000.0f)
            .v (PID::crushDrive, 0.22f).v (PID::crushMix, 0.36f)
            .v (PID::retroEra, 0.30f).v (PID::retroAge, 0.44f)
            .v (PID::retroDrift, 0.08f).v (PID::retroWear, 0.22f)
            .v (PID::retroTone, -0.06f).v (PID::retroNoise, 0.14f)
            .v (PID::retroMix, 0.66f)
            .v (PID::fxFilterCutoff, 10500.0f).v (PID::fxFilterRes, 0.14f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.24f)
            .v (PID::spaceSize, 0.30f).v (PID::spaceDecay, 0.9f)
            .v (PID::spaceFog, 0.26f).v (PID::spaceLight, 0.04f)
            .v (PID::spacePreDelay, 9.0f).v (PID::spaceMix, 0.18f)
            .v (PID::auraSize, 0.26f).v (PID::auraDistance, 0.16f)
            .v (PID::auraFog, 0.26f).v (PID::auraDecay, 0.18f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, 0.02f)
            .v (PID::patinaNoise, 0.12f).v (PID::patinaWear, 0.26f)
            .v (PID::synthWidth, 0.95f).v (PID::highWidth, 1.10f)
            .v (PID::breathAmount, 0.18f).v (PID::breathSpeed, 0.50f)
            .route (srcBreath, PID::oscAWtPos, 0.14f)
            .route (srcOrganic, PID::filter2Cutoff, 0.10f));

        add (out, Build ("Cáscara", "PERCUSSION", "MINIMAL",
                         "shell,stick,comb,short",
                         "The stick on the shell rather than on the head: a COMB primary filter rung by a dust-noise transient, with barely any tuned body under it.")
            .at (46, 1, 0.88f, 1.5)
            .chain ("FILTER,SPACE,CRUSH,RETRO,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::masterGain, 6.0f)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.24f)
            .v (PID::driftAmount, 0.04f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tHollow)
            .v (PID::oscAWtPos, 0.62f).v (PID::oscALevel, 0.30f)
            .v (PID::oscAOctave, 1.0f).v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBLevel, 0.0f)
            .v (PID::subLevel, 0.04f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.66f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.18f).v (PID::bodyTilt, 0.34f)
            .v (PID::densityAmount, 0.08f)
            .v (PID::preFilterDrive, 0.18f).v (PID::postSaturation, 0.14f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 2400.0f).v (PID::filterResonance, 0.66f)
            .v (PID::filterKeyTrack, 1.0f).v (PID::filterEnvAmount, 0.26f)
            .v (PID::filterVelAmount, 0.44f)
            .v (PID::ampAttack, 0.0005f).v (PID::ampDecay, 0.055f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.04f)
            .v (PID::ampVelocity, 0.66f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.008f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.01f)
            .v (PID::macroMemory, 0.10f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.26f)
            .v (PID::macroCharacter, 0.30f).v (PID::macroMotion, 0.10f)
            .v (PID::macroWorld, 0.16f).v (PID::macroWeight, 0.18f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::retroEra, 0.26f).v (PID::retroAge, 0.16f)
            .v (PID::retroDrift, 0.03f).v (PID::retroWear, 0.06f)
            .v (PID::retroTone, -0.02f).v (PID::retroNoise, 0.05f)
            .v (PID::retroMix, 0.30f)
            .v (PID::fxFilterCutoff, 13000.0f).v (PID::fxFilterRes, 0.08f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.12f)
            .v (PID::spaceSize, 0.14f).v (PID::spaceDecay, 0.3f)
            .v (PID::spaceFog, 0.14f).v (PID::spacePreDelay, 3.0f)
            .v (PID::spaceMix, 0.09f)
            .v (PID::auraSize, 0.14f).v (PID::auraDistance, 0.08f)
            .v (PID::auraFog, 0.16f).v (PID::auraDecay, 0.08f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaNoise, 0.05f)
            .v (PID::patinaWear, 0.10f)
            .v (PID::synthWidth, 0.80f).v (PID::highWidth, 0.95f)
            .v (PID::breathAmount, 0.10f).v (PID::breathSpeed, 0.70f)
            .route (srcOrganic, PID::filterCutoff, 0.10f));

        add (out, Build ("Semilla Seca", "PERCUSSION", "NOSTALGIC",
                         "maraca,seeds,noise,hand",
                         "Seeds in a gourd: pink noise confined to the attack, band-passed high and high-passed clear of the low mid, with a small tuned shell underneath for the gourd.")
            .at (47, 1, 0.86f, 1.5)
            .chain ("RETRO,FILTER,SPACE,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::masterGain, 6.0f)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.34f)
            .v (PID::driftAmount, 0.06f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.12f)
            .v (PID::oscAOctave, 1.0f).v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBLevel, 0.0f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nPink).v (PID::noiseLevel, 0.90f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.20f).v (PID::bodyTilt, 0.24f)
            .v (PID::densityAmount, 0.10f)
            .v (PID::preFilterDrive, 0.12f).v (PID::postSaturation, 0.12f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 5200.0f).v (PID::filterResonance, 0.34f)
            .v (PID::filterKeyTrack, 0.25f).v (PID::filterEnvAmount, 0.38f)
            .v (PID::filterVelAmount, 0.48f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Hp)
            .v (PID::filter2Cutoff, 1400.0f).v (PID::filter2Res, 0.08f)
            .v (PID::filter2Mix, 0.85f)
            .v (PID::ampAttack, 0.0006f).v (PID::ampDecay, 0.040f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.03f)
            .v (PID::ampVelocity, 0.60f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.010f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.01f)
            .v (PID::macroMemory, 0.24f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.46f).v (PID::memoryWobble, 0.08f)
            .v (PID::macroCharacter, 0.36f).v (PID::macroMotion, 0.16f)
            .v (PID::macroWorld, 0.20f).v (PID::macroWeight, 0.14f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::retroEra, 0.36f).v (PID::retroAge, 0.34f)
            .v (PID::retroDrift, 0.06f).v (PID::retroWear, 0.12f)
            .v (PID::retroTone, -0.10f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.52f)
            .v (PID::fxFilterCutoff, 14000.0f).v (PID::fxFilterRes, 0.06f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.16f)
            .v (PID::spaceSize, 0.18f).v (PID::spaceDecay, 0.4f)
            .v (PID::spaceFog, 0.20f).v (PID::spaceLight, -0.04f)
            .v (PID::spacePreDelay, 5.0f).v (PID::spaceMix, 0.12f)
            .v (PID::auraSize, 0.18f).v (PID::auraDistance, 0.12f)
            .v (PID::auraFog, 0.20f).v (PID::auraDecay, 0.10f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.06f)
            .v (PID::patinaNoise, 0.10f).v (PID::patinaWear, 0.18f)
            .v (PID::synthWidth, 0.90f).v (PID::highWidth, 1.10f)
            .v (PID::breathAmount, 0.20f).v (PID::breathSpeed, 0.90f)
            .route (srcOrganic, PID::filterCutoff, 0.14f)
            .route (srcBreath, PID::noiseLevel, 0.10f));

        add (out, Build ("Arena en la Mano", "PERCUSSION", "AIRY",
                         "shaker,air,noise,short",
                         "A finer shaker than the maraca: AIR noise alone through a FORMANT primary filter, forty milliseconds long, with no tuned oscillator running at all.")
            .at (49, 1, 0.78f, 1.5)
            .chain ("SPACE,FILTER,RETRO,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::masterGain, 5.0f)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.38f)
            .v (PID::oscALevel, 0.0f).v (PID::oscBLevel, 0.0f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nAir).v (PID::noiseLevel, 1.0f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.10f).v (PID::densityAmount, 0.06f)
            .v (PID::preFilterDrive, 0.08f).v (PID::postSaturation, 0.08f)
            .v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 6800.0f).v (PID::filterResonance, 0.30f)
            .v (PID::filterKeyTrack, 0.30f).v (PID::filterEnvAmount, 0.30f)
            .v (PID::filterVelAmount, 0.44f)
            .v (PID::ampAttack, 0.0005f).v (PID::ampDecay, 0.030f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.025f)
            .v (PID::ampVelocity, 0.52f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.007f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.01f)
            // Deliberately no pitch or PM envelope, and envelope 2 left at
            // its slow default: no oscillator runs here at all, so there is
            // nothing to bend or to modulate, and the only thing envelope 2
            // still reaches is the FORMANT vowel, which is meant to sit near
            // its dark end for the whole forty milliseconds rather than sweep.
            .v (PID::macroMemory, 0.14f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.34f)
            .v (PID::macroCharacter, 0.24f).v (PID::macroMotion, 0.20f)
            .v (PID::macroWorld, 0.24f).v (PID::macroWeight, 0.10f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::retroEra, 0.44f).v (PID::retroAge, 0.18f)
            .v (PID::retroDrift, 0.05f).v (PID::retroWear, 0.06f)
            .v (PID::retroTone, 0.10f).v (PID::retroNoise, 0.06f)
            .v (PID::retroMix, 0.34f)
            .v (PID::fxFilterCutoff, 15000.0f).v (PID::fxFilterRes, 0.05f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.20f)
            .v (PID::spaceSize, 0.20f).v (PID::spaceDecay, 0.5f)
            .v (PID::spaceFog, 0.24f).v (PID::spaceLight, 0.14f)
            .v (PID::spacePreDelay, 6.0f).v (PID::spaceMix, 0.14f)
            .v (PID::auraSize, 0.22f).v (PID::auraDistance, 0.16f)
            .v (PID::auraFog, 0.20f).v (PID::auraDecay, 0.12f)
            .v (PID::auraLight, 0.16f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, 0.12f)
            .v (PID::patinaNoise, 0.08f).v (PID::patinaWear, 0.10f)
            .v (PID::synthWidth, 1.05f).v (PID::highWidth, 1.25f)
            .v (PID::breathAmount, 0.24f).v (PID::breathSpeed, 1.20f)
            .route (srcOrganic, PID::filterCutoff, 0.16f)
            .route (srcBreath, PID::fxFilterCutoff, 0.10f));

        add (out, Build ("Güiro Rayado", "PERCUSSION", "DARK",
                         "guiro,scrape,lfo,wood",
                         "A scrape rather than a hit: a TEXTURE noise band held open for a third of a second and re-articulated by a 22 Hz saw LFO into the chain filter, so the envelope is a run of teeth instead of one transient.")
            .at (45, 1, 0.84f, 2.0)
            .chain ("FILTER,CRUSH,SPACE,GRAIN,RETRO,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::masterGain, 4.0f)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.30f)
            .v (PID::driftAmount, 0.08f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tOrganic)
            .v (PID::oscAWtPos, 0.40f).v (PID::oscALevel, 0.18f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBLevel, 0.0f)
            .v (PID::subLevel, 0.05f)
            .v (PID::noiseType, ch::nTexture).v (PID::noiseLevel, 0.82f)
            .v (PID::noiseAttackOnly, 0.25f)
            .v (PID::bodyAmount, 0.34f).v (PID::bodyTilt, -0.12f)
            .v (PID::densityAmount, 0.14f)
            .v (PID::preFilterDrive, 0.20f).v (PID::postSaturation, 0.18f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 1900.0f).v (PID::filterResonance, 0.58f)
            .v (PID::filterKeyTrack, 0.80f).v (PID::filterEnvAmount, 0.22f)
            .v (PID::filterVelAmount, 0.40f)
            .v (PID::ampAttack, 0.004f).v (PID::ampDecay, 0.34f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.08f)
            .v (PID::ampVelocity, 0.50f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.020f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.02f)
            .v (PID::lfo1Shape, ch::lfoSawDown).v (PID::lfo1Rate, 22.0f)
            .v (PID::lfo1Depth, 0.85f)
            .v (PID::lfo2Shape, ch::lfoRandom).v (PID::lfo2Rate, 14.0f)
            .v (PID::lfo2Depth, 0.40f)
            .v (PID::macroMemory, 0.18f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.40f).v (PID::memoryWobble, 0.10f)
            .v (PID::macroCharacter, 0.44f).v (PID::macroMotion, 0.46f)
            .v (PID::macroWorld, 0.22f).v (PID::macroWeight, 0.22f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.20f)
            .v (PID::crushBits, 12.0f).v (PID::crushRate, 20000.0f)
            .v (PID::crushDrive, 0.18f).v (PID::crushMix, 0.30f)
            .v (PID::retroEra, 0.32f).v (PID::retroAge, 0.28f)
            .v (PID::retroDrift, 0.08f).v (PID::retroWear, 0.14f)
            .v (PID::retroTone, -0.16f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.46f)
            .v (PID::fxFilterMode, ch::f2Bp).v (PID::fxFilterCutoff, 3200.0f)
            .v (PID::fxFilterRes, 0.40f).v (PID::fxFilterDrive, 0.16f)
            .v (PID::fxFilterMotion, 0.30f).v (PID::fxFilterMix, 0.85f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.18f)
            .v (PID::spaceSize, 0.20f).v (PID::spaceDecay, 0.5f)
            .v (PID::spaceFog, 0.22f).v (PID::spaceLight, -0.20f)
            .v (PID::spacePreDelay, 5.0f).v (PID::spaceMix, 0.12f)
            .v (PID::auraSize, 0.20f).v (PID::auraDistance, 0.12f)
            .v (PID::auraFog, 0.24f).v (PID::auraDecay, 0.14f)
            .v (PID::auraLight, -0.16f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.14f)
            .v (PID::patinaNoise, 0.10f).v (PID::patinaWear, 0.18f)
            .v (PID::synthWidth, 0.85f).v (PID::highWidth, 0.95f)
            .v (PID::breathAmount, 0.26f).v (PID::breathSpeed, 1.40f)
            .route (srcLfo1, PID::fxFilterCutoff, 0.55f)
            .route (srcLfo1, PID::noiseLevel, 0.30f)
            .route (srcLfo2, PID::filterCutoff, 0.14f));

        add (out, Build ("Dos Palos", "PERCUSSION", "MINIMAL",
                         "clave,wood,transient,dembow",
                         "Two sticks: a triangle body three octaves up at a fixed start phase, thirty-five milliseconds long, with the MASS ladder resonating just above the fundamental, two semitones of mod envelope 2 into pitch on the strike, and almost nothing after the transient.")
            .at (52, 1, 1.0f, 1.5)
            .chain ("FILTER,RETRO,SPACE,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::masterGain, 3.0f)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.12f)
            .v (PID::driftAmount, 0.02f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.78f)
            .v (PID::oscAOctave, 3.0f).v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscAPhaseOffset, 0.25f)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.26f)
            .v (PID::oscBOctave, 3.0f).v (PID::oscBSemi, 9.0f)
            .v (PID::oscBFine, -12.0f).v (PID::oscBPhase, ch::phaseReset)
            .v (PID::pitchEnvAmount, 2.0f)
            .v (PID::subLevel, 0.06f).v (PID::subHarmonics, 0.20f)
            .v (PID::noiseType, ch::nWhite).v (PID::noiseLevel, 0.16f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.34f).v (PID::bodyTilt, 0.42f)
            .v (PID::densityAmount, 0.10f)
            .v (PID::preFilterDrive, 0.22f).v (PID::postSaturation, 0.18f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 2200.0f).v (PID::filterResonance, 0.60f)
            .v (PID::filterDrive, 0.24f).v (PID::filterKeyTrack, 1.0f)
            .v (PID::filterEnvAmount, 0.34f).v (PID::filterVelAmount, 0.40f)
            .v (PID::ampAttack, 0.0005f).v (PID::ampDecay, 0.035f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.03f)
            .v (PID::ampVelocity, 0.50f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.006f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.01f)
            .v (PID::env2Attack, 0.0005f).v (PID::env2Decay, 0.006f)
            .v (PID::env2Sustain, 0.0f).v (PID::env2Release, 0.01f)
            .v (PID::macroMemory, 0.10f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.24f)
            .v (PID::macroCharacter, 0.28f).v (PID::macroMotion, 0.06f)
            .v (PID::macroWorld, 0.16f).v (PID::macroWeight, 0.26f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::retroEra, 0.30f).v (PID::retroAge, 0.14f)
            .v (PID::retroDrift, 0.03f).v (PID::retroWear, 0.04f)
            .v (PID::retroTone, -0.08f).v (PID::retroNoise, 0.04f)
            .v (PID::retroMix, 0.30f)
            .v (PID::fxFilterCutoff, 9000.0f).v (PID::fxFilterRes, 0.08f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.14f)
            .v (PID::spaceSize, 0.16f).v (PID::spaceDecay, 0.35f)
            .v (PID::spaceFog, 0.16f).v (PID::spaceLight, -0.06f)
            .v (PID::spacePreDelay, 4.0f).v (PID::spaceMix, 0.10f)
            .v (PID::auraSize, 0.16f).v (PID::auraDistance, 0.10f)
            .v (PID::auraFog, 0.16f).v (PID::auraDecay, 0.08f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.06f)
            .v (PID::patinaNoise, 0.04f).v (PID::patinaWear, 0.08f)
            .v (PID::synthWidth, 0.60f).v (PID::highWidth, 0.80f)
            .v (PID::lowMonoFreq, 160.0f)
            .v (PID::breathOn, 0.0f).v (PID::breathAmount, 0.0f)
            .route (srcTouch, PID::filterCutoff, 0.10f));

        add (out, Build ("Madera Hueca", "PERCUSSION", "WARM",
                         "woodblock,hollow,comb,wood",
                         "The HOLLOW wavetable through a COMB filter tracking the note at 1.0, which is how a block with a slot cut in it is built, fifty milliseconds of it, and two semitones of mod envelope 2 into pitch on the strike.")
            .at (50, 1, 0.92f, 1.5)
            .chain ("RETRO,FILTER,GRAIN,SPACE,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::masterGain, 3.0f)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.20f)
            .v (PID::driftAmount, 0.05f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tHollow)
            .v (PID::oscAWtPos, 0.30f).v (PID::oscALevel, 0.66f)
            .v (PID::oscAOctave, 2.0f).v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.20f)
            .v (PID::oscBOctave, 2.0f).v (PID::oscBSemi, 7.0f)
            .v (PID::oscBFine, 6.0f)
            .v (PID::pitchEnvAmount, 2.0f)
            .v (PID::subLevel, 0.08f).v (PID::subHarmonics, 0.18f)
            .v (PID::noiseType, ch::nTexture).v (PID::noiseLevel, 0.30f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.42f).v (PID::bodyTilt, 0.30f)
            .v (PID::densityAmount, 0.14f)
            .v (PID::preFilterDrive, 0.18f).v (PID::postSaturation, 0.16f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1600.0f).v (PID::filterResonance, 0.62f)
            .v (PID::filterKeyTrack, 1.0f).v (PID::filterEnvAmount, 0.30f)
            .v (PID::filterVelAmount, 0.46f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Bp)
            .v (PID::filter2Cutoff, 3600.0f).v (PID::filter2Res, 0.22f)
            .v (PID::filter2Mix, 0.40f)
            .v (PID::ampAttack, 0.0006f).v (PID::ampDecay, 0.048f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.04f)
            .v (PID::ampVelocity, 0.58f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.009f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.012f)
            .v (PID::env2Attack, 0.0005f).v (PID::env2Decay, 0.008f)
            .v (PID::env2Sustain, 0.0f).v (PID::env2Release, 0.012f)
            .v (PID::macroMemory, 0.16f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.30f).v (PID::memoryWobble, 0.06f)
            .v (PID::macroCharacter, 0.32f).v (PID::macroMotion, 0.12f)
            .v (PID::macroWorld, 0.18f).v (PID::macroWeight, 0.30f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::retroEra, 0.26f).v (PID::retroAge, 0.24f)
            .v (PID::retroDrift, 0.05f).v (PID::retroWear, 0.08f)
            .v (PID::retroTone, -0.12f).v (PID::retroNoise, 0.06f)
            .v (PID::retroMix, 0.40f)
            .v (PID::fxFilterCutoff, 8000.0f).v (PID::fxFilterRes, 0.10f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.16f)
            .v (PID::spaceSize, 0.18f).v (PID::spaceDecay, 0.4f)
            .v (PID::spaceFog, 0.18f).v (PID::spaceLight, -0.10f)
            .v (PID::spacePreDelay, 5.0f).v (PID::spaceMix, 0.12f)
            .v (PID::auraSize, 0.18f).v (PID::auraDistance, 0.10f)
            .v (PID::auraFog, 0.18f).v (PID::auraDecay, 0.10f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.10f)
            .v (PID::patinaNoise, 0.06f).v (PID::patinaWear, 0.12f)
            .v (PID::synthWidth, 0.70f).v (PID::highWidth, 0.85f)
            .v (PID::breathAmount, 0.14f).v (PID::breathSpeed, 0.60f)
            .route (srcBreath, PID::oscAWtPos, 0.12f));

        add (out, Build ("Pandereta de Plena", "PERCUSSION", "DREAMY",
                         "tambourine,jingles,metal,layered",
                         "Two layers of short metallic noise - a METALLIC wavetable ring-modulated against a SPECTRAL one, over DIGITAL noise - high-passed and given a release three times its decay so the jingles outlast the hit.")
            .at (52, 1, 0.90f, 2.5)
            .chain ("FILTER,RETRO,SPACE,CRUSH,REWIND,GRAIN")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::masterGain, 3.0f)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.42f)
            .v (PID::driftAmount, 0.10f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tMetal)
            .v (PID::oscAWtPos, 0.74f).v (PID::oscALevel, 0.34f)
            .v (PID::oscAOctave, 2.0f).v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tSpectral)
            .v (PID::oscBWtPos, 0.58f).v (PID::oscBLevel, 0.22f)
            .v (PID::oscBOctave, 2.0f).v (PID::oscBSemi, 6.0f)
            .v (PID::oscBFine, 23.0f).v (PID::oscBPhase, ch::phaseRandom)
            .v (PID::oscRingMod, 0.28f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nDigital).v (PID::noiseLevel, 0.60f)
            .v (PID::noiseAttackOnly, 0.55f)
            .v (PID::bodyAmount, 0.16f).v (PID::bodyTilt, 0.36f)
            .v (PID::densityAmount, 0.22f)
            .v (PID::preFilterDrive, 0.16f).v (PID::postSaturation, 0.16f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::hp)
            .v (PID::filterCutoff, 1800.0f).v (PID::filterResonance, 0.18f)
            .v (PID::filterKeyTrack, 0.40f).v (PID::filterEnvAmount, 0.34f)
            .v (PID::filterVelAmount, 0.42f)
            .v (PID::ampAttack, 0.0006f).v (PID::ampDecay, 0.22f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.30f)
            .v (PID::ampVelocity, 0.56f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.016f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.03f)
            .v (PID::macroMemory, 0.22f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.42f).v (PID::memoryWobble, 0.10f)
            .v (PID::memoryAsymmetry, 0.34f)
            .v (PID::macroCharacter, 0.40f).v (PID::macroMotion, 0.30f)
            .v (PID::macroWorld, 0.34f).v (PID::macroWeight, 0.14f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::retroEra, 0.46f).v (PID::retroAge, 0.26f)
            .v (PID::retroDrift, 0.08f).v (PID::retroWear, 0.10f)
            .v (PID::retroTone, 0.12f).v (PID::retroNoise, 0.09f)
            .v (PID::retroMix, 0.44f)
            .v (PID::fxFilterCutoff, 15500.0f).v (PID::fxFilterRes, 0.08f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.30f)
            .v (PID::spaceSize, 0.34f).v (PID::spaceDecay, 1.2f)
            .v (PID::spaceFog, 0.34f).v (PID::spaceLight, 0.22f)
            .v (PID::spacePreDelay, 12.0f).v (PID::spaceMix, 0.24f)
            .v (PID::auraSize, 0.32f).v (PID::auraDistance, 0.22f)
            .v (PID::auraFog, 0.28f).v (PID::auraDecay, 0.26f)
            .v (PID::auraLight, 0.20f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.14f)
            .v (PID::patinaNoise, 0.10f).v (PID::patinaWear, 0.16f)
            .v (PID::synthWidth, 1.20f).v (PID::highWidth, 1.35f)
            .v (PID::breathAmount, 0.26f).v (PID::breathSpeed, 1.00f)
            .route (srcOrganic, PID::oscBFine, 0.12f)
            .route (srcBreath, PID::oscAWtPos, 0.18f));

        add (out, Build ("Marco y Piel", "PERCUSSION", "CINEMATIC",
                         "frame drum,skin,low,hand",
                         "A wide frame with a skin over it: a sine body an octave down beside a triangle sub, DARK noise on the attack, and mod envelope 2 dropping the pitch seven semitones onto the note over thirty-five milliseconds.")
            .at (38, 1, 0.94f, 2.5)
            .chain ("RETRO,FILTER,SPACE,REWIND,CRUSH,GRAIN")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::masterGain, 1.0f)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.24f)
            .v (PID::driftAmount, 0.07f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.80f)
            .v (PID::oscAOctave, -1.0f).v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscAPhaseOffset, 0.25f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.20f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBSemi, 5.0f)
            .v (PID::oscBFine, -9.0f)
            .v (PID::pitchEnvAmount, 7.0f)
            .v (PID::subWave, ch::subTri).v (PID::subLevel, 0.34f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.36f)
            .v (PID::noiseType, ch::nDark).v (PID::noiseLevel, 0.30f)
            .v (PID::noiseAttackOnly, 0.95f)
            .v (PID::bodyAmount, 0.66f).v (PID::bodyTilt, -0.14f)
            .v (PID::densityAmount, 0.20f)
            .v (PID::preFilterDrive, 0.26f).v (PID::postSaturation, 0.22f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 260.0f).v (PID::filterResonance, 0.48f)
            .v (PID::filterDrive, 0.30f).v (PID::filterKeyTrack, 0.85f)
            .v (PID::filterEnvAmount, 0.28f).v (PID::filterVelAmount, 0.48f)
            .v (PID::ampAttack, 0.0010f).v (PID::ampDecay, 0.38f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.22f)
            .v (PID::ampVelocity, 0.60f)
            .v (PID::env1Attack, 0.0008f).v (PID::env1Decay, 0.020f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.03f)
            .v (PID::env2Attack, 0.0005f).v (PID::env2Decay, 0.035f)
            .v (PID::env2Sustain, 0.0f).v (PID::env2Release, 0.04f)
            .v (PID::macroMemory, 0.26f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.44f).v (PID::memoryWobble, 0.10f)
            .v (PID::macroCharacter, 0.38f).v (PID::macroMotion, 0.18f)
            .v (PID::macroWorld, 0.40f).v (PID::macroWeight, 0.56f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.48f)
            .v (PID::weightCompress, 0.30f)
            .v (PID::retroEra, 0.30f).v (PID::retroAge, 0.28f)
            .v (PID::retroDrift, 0.06f).v (PID::retroWear, 0.10f)
            .v (PID::retroTone, -0.24f).v (PID::retroNoise, 0.08f)
            .v (PID::retroMix, 0.44f)
            .v (PID::fxFilterCutoff, 5200.0f).v (PID::fxFilterRes, 0.10f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.34f)
            .v (PID::spaceSize, 0.44f).v (PID::spaceDecay, 1.6f)
            .v (PID::spaceFog, 0.40f).v (PID::spaceLight, -0.34f)
            .v (PID::spacePreDelay, 16.0f).v (PID::spaceMix, 0.22f)
            .v (PID::auraSize, 0.40f).v (PID::auraDistance, 0.26f)
            .v (PID::auraFog, 0.36f).v (PID::auraDecay, 0.30f)
            .v (PID::auraLight, -0.26f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.20f)
            .v (PID::patinaNoise, 0.10f).v (PID::patinaWear, 0.18f)
            .v (PID::synthWidth, 0.75f).v (PID::highWidth, 0.90f)
            .v (PID::lowMonoFreq, 260.0f)
            .v (PID::breathAmount, 0.18f).v (PID::breathSpeed, 0.40f)
            .route (srcTouch, PID::filterCutoff, 0.14f)
            .route (srcOrganic, PID::oscBFine, 0.06f));

        add (out, Build ("Copa de Barro", "PERCUSSION", "MYSTERIOUS",
                         "goblet,clay,skin,hand",
                         "A clay goblet under a skin: an ASYMMETRIC wavetable body seven semitones above the note at the strike, phase modulation from a detuned sine whose index falls away with it inside twenty-five milliseconds, a FORMANT primary filter for the throat of the shell, and the room crushed after it rather than before.")
            .at (44, 1, 0.90f, 2.0)
            .chain ("FILTER,SPACE,RETRO,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::masterGain, 2.0f)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.32f)
            .v (PID::driftAmount, 0.09f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tAsym)
            .v (PID::oscAWtPos, 0.44f).v (PID::oscALevel, 0.62f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.24f)
            .v (PID::oscBSemi, 4.0f).v (PID::oscBFine, 13.0f)
            .v (PID::oscPmAmount, 0.22f)
            .v (PID::pitchEnvAmount, 7.0f).v (PID::pmEnvAmount, 0.18f)
            .v (PID::subLevel, 0.14f).v (PID::subHarmonics, 0.26f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.40f)
            .v (PID::noiseAttackOnly, 0.88f)
            .v (PID::bodyAmount, 0.50f).v (PID::bodyTilt, 0.10f)
            .v (PID::densityAmount, 0.18f)
            .v (PID::preFilterDrive, 0.22f).v (PID::postSaturation, 0.18f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 900.0f).v (PID::filterResonance, 0.42f)
            .v (PID::filterKeyTrack, 0.90f).v (PID::filterEnvAmount, 0.26f)
            .v (PID::filterVelAmount, 0.50f)
            .v (PID::ampAttack, 0.0008f).v (PID::ampDecay, 0.26f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.12f)
            .v (PID::ampVelocity, 0.62f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.024f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.03f)
            // Envelope 2 drives three things in this preset: the pitch fall,
            // the PM index and - the primary filter being FORMANT - the vowel
            // morph.  Made percussive it carries the vowel across the strike
            // and settles back, which is the shape a struck shell wants; left
            // at its slow default it would have parked the vowel near U and
            // given the other two a swell instead of a transient.
            .v (PID::env2Attack, 0.0005f).v (PID::env2Decay, 0.025f)
            .v (PID::env2Sustain, 0.0f).v (PID::env2Release, 0.03f)
            .v (PID::macroMemory, 0.28f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.46f).v (PID::memoryWobble, 0.14f)
            .v (PID::memoryDiffusion, 0.22f)
            .v (PID::macroCharacter, 0.42f).v (PID::macroMotion, 0.24f)
            .v (PID::macroWorld, 0.36f).v (PID::macroWeight, 0.38f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.22f)
            .v (PID::crushBits, 12.0f).v (PID::crushRate, 22000.0f)
            .v (PID::crushJitter, 0.08f).v (PID::crushDrive, 0.16f)
            .v (PID::crushTone, -0.10f).v (PID::crushMix, 0.30f)
            .v (PID::retroEra, 0.34f).v (PID::retroAge, 0.32f)
            .v (PID::retroDrift, 0.10f).v (PID::retroWear, 0.14f)
            .v (PID::retroTone, -0.14f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.50f)
            .v (PID::fxFilterCutoff, 8800.0f).v (PID::fxFilterRes, 0.12f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.30f)
            .v (PID::spaceSize, 0.36f).v (PID::spaceDecay, 1.3f)
            .v (PID::spaceFog, 0.34f).v (PID::spaceLight, -0.12f)
            .v (PID::spacePreDelay, 11.0f).v (PID::spaceMix, 0.22f)
            .v (PID::auraSize, 0.34f).v (PID::auraDistance, 0.22f)
            .v (PID::auraFog, 0.32f).v (PID::auraDecay, 0.24f)
            .v (PID::auraLight, -0.10f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.06f)
            .v (PID::patinaNoise, 0.12f).v (PID::patinaWear, 0.22f)
            .v (PID::synthWidth, 0.90f).v (PID::highWidth, 1.05f)
            .v (PID::breathAmount, 0.24f).v (PID::breathSpeed, 0.70f)
            .route (srcBreath, PID::oscAWtPos, 0.16f)
            .route (srcOrganic, PID::filterCutoff, 0.10f));

        add (out, Build ("Sampler de Esquina", "PERCUSSION", "BROKEN",
                         "crush,memory,sampled,street",
                         "A clean hand hit - five semitones of mod envelope 2 into pitch, landing on the note in twenty-five milliseconds - put in a room, granulated, and only then sampled badly: nine bits at a 12 kHz clock with jitter on it, Memory on generation IV, and the chain filter last.")
            .at (41, 1, 0.95f, 2.5)
            .chain ("SPACE,GRAIN,CRUSH,RETRO,FILTER,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.40f)
            .v (PID::driftAmount, 0.14f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.66f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::square).v (PID::oscBLevel, 0.22f)
            .v (PID::oscBSemi, 6.0f).v (PID::oscBFine, 18.0f)
            .v (PID::oscBPulseWidth, 0.30f)
            .v (PID::oscRingMod, 0.20f)
            .v (PID::pitchEnvAmount, 5.0f)
            .v (PID::subLevel, 0.12f).v (PID::subHarmonics, 0.24f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.34f)
            .v (PID::noiseAttackOnly, 0.90f)
            .v (PID::bodyAmount, 0.38f).v (PID::densityAmount, 0.20f)
            .v (PID::preFilterDrive, 0.28f).v (PID::postSaturation, 0.26f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1400.0f).v (PID::filterResonance, 0.40f)
            .v (PID::filterDrive, 0.32f).v (PID::filterKeyTrack, 0.70f)
            .v (PID::filterEnvAmount, 0.36f).v (PID::filterVelAmount, 0.50f)
            .v (PID::ampAttack, 0.0008f).v (PID::ampDecay, 0.28f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.16f)
            .v (PID::ampVelocity, 0.64f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.026f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.03f)
            .v (PID::env2Attack, 0.0005f).v (PID::env2Decay, 0.025f)
            .v (PID::env2Sustain, 0.0f).v (PID::env2Release, 0.03f)
            .v (PID::macroMemory, 0.78f).v (PID::memoryGen, ch::genIV)
            .v (PID::memoryBandwidth, 0.70f).v (PID::memoryWobble, 0.54f)
            .v (PID::memoryDiffusion, 0.44f).v (PID::memoryAsymmetry, 0.50f)
            .v (PID::macroCharacter, 0.70f).v (PID::macroMotion, 0.36f)
            .v (PID::macroWorld, 0.30f).v (PID::macroWeight, 0.30f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.62f)
            .v (PID::crushBits, 9.0f).v (PID::crushRate, 12000.0f)
            .v (PID::crushJitter, 0.38f).v (PID::crushDrive, 0.34f)
            .v (PID::crushTone, -0.08f).v (PID::crushMix, 0.72f)
            .v (PID::retroEra, 0.84f).v (PID::retroAge, 0.62f)
            .v (PID::retroDrift, 0.30f).v (PID::retroWear, 0.46f)
            .v (PID::retroTone, -0.10f).v (PID::retroNoise, 0.22f)
            .v (PID::retroMix, 0.82f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.30f)
            .v (PID::grainSize, 34.0f).v (PID::grainDensity, 26.0f)
            .v (PID::grainPosition, 0.10f).v (PID::grainWindow, ch::wPercussive)
            .v (PID::grainSpread, 0.40f).v (PID::grainJitter, 0.30f)
            .v (PID::grainDirection, 0.10f).v (PID::grainMix, 0.26f)
            .v (PID::fxFilterCutoff, 6200.0f).v (PID::fxFilterRes, 0.16f)
            .v (PID::fxFilterDrive, 0.14f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.28f)
            .v (PID::spaceSize, 0.30f).v (PID::spaceDecay, 0.9f)
            .v (PID::spaceFog, 0.28f).v (PID::spaceLight, -0.16f)
            .v (PID::spacePreDelay, 9.0f).v (PID::spaceMix, 0.26f)
            .v (PID::auraSize, 0.28f).v (PID::auraDistance, 0.20f)
            .v (PID::auraFog, 0.34f).v (PID::auraDecay, 0.22f)
            .v (PID::auraLight, -0.20f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.12f)
            .v (PID::patinaNoise, 0.22f).v (PID::patinaWear, 0.44f)
            .v (PID::patinaDrift, 0.26f)
            .v (PID::synthWidth, 0.95f).v (PID::highWidth, 1.00f)
            .v (PID::breathAmount, 0.22f).v (PID::breathSpeed, 0.60f)
            .route (srcMemory, PID::crushRate, -0.20f)
            .route (srcOrganic, PID::crushJitter, 0.14f)
            .route (srcBreath, PID::filterCutoff, 0.10f));
    }
}
