#include "PresetBuilder.h"
#include "Builders.h"

namespace nacar::presets::detail
{
    // ===============================================================
    //  PLUCKS
    // ===============================================================
    void buildPlucks (std::vector<FactoryPreset>& out)
    {
        // A struck sine with a metallic wavetable stacked two octaves up
        // and a comb in the creative filter slot for the tine of the tine.
        add (out, Build ("Tin Kalimba", "PLUCKS", "INTIMATE",
                         "thumb piano,short,comb,close",
                         "A thumb piano made of biscuit tin, played very close to the microphone.")
            .at (60, 1, 0.78f, 3.0)
            .chain ("FILTER,RETRO,SPACE,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 12.0f).v (PID::voiceVariation, 0.48f)
            .v (PID::driftAmount, 0.14f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.80f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tMetal)
            .v (PID::oscBWtPos, 0.30f).v (PID::oscBLevel, 0.26f)
            .v (PID::oscBOctave, 2.0f).v (PID::oscBFine, 14.0f)
            .v (PID::subLevel, 0.20f).v (PID::subHarmonics, 0.28f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.16f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.40f).v (PID::densityAmount, 0.20f)
            .v (PID::postSaturation, 0.14f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 3800.0f).v (PID::filterResonance, 0.16f)
            .v (PID::filterKeyTrack, 0.90f).v (PID::filterEnvAmount, 0.52f)
            .v (PID::filterVelAmount, 0.60f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Comb)
            .v (PID::filter2Cutoff, 900.0f).v (PID::filter2Res, 0.40f)
            .v (PID::filter2Mix, 0.34f)
            .v (PID::ampAttack, 0.0008f).v (PID::ampDecay, 1.1f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.55f)
            .v (PID::ampVelocity, 0.70f)
            .v (PID::env1Attack, 0.0006f).v (PID::env1Decay, 0.16f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.14f)
            .v (PID::macroMemory, 0.24f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.40f).v (PID::memoryWobble, 0.22f)
            .v (PID::macroCharacter, 0.30f).v (PID::macroMotion, 0.26f)
            .v (PID::macroWorld, 0.28f).v (PID::macroWeight, 0.30f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::retroEra, 0.54f).v (PID::retroAge, 0.26f)
            .v (PID::retroDrift, 0.18f).v (PID::retroWear, 0.14f)
            .v (PID::retroNoise, 0.12f).v (PID::retroMix, 0.58f)
            .v (PID::fxFilterCutoff, 9800.0f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.20f)
            .v (PID::spaceSize, 0.24f).v (PID::spaceDecay, 0.9f)
            .v (PID::spaceFog, 0.22f).v (PID::spacePreDelay, 9.0f)
            .v (PID::spaceMix, 0.20f)
            .v (PID::auraSize, 0.30f).v (PID::auraDistance, 0.18f)
            .v (PID::auraFog, 0.34f).v (PID::auraDecay, 0.26f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaNoise, 0.14f)
            .v (PID::patinaWear, 0.22f)
            .v (PID::breathAmount, 0.28f).v (PID::breathSpeed, 0.24f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.20f)
            .v (PID::lfo2Depth, 0.40f)
            .route (srcLfo2, PID::filter2Cutoff, 0.16f)
            .route (srcBreath, PID::oscBWtPos, 0.18f));

        // Generation III brings dropouts and a spectral hole, and Rewind is
        // armed on the quarter so the note sometimes plays itself backwards.
        add (out, Build ("Broken Harp", "PLUCKS", "BROKEN",
                         "rewind,dropouts,generation iii,reverse",
                         "A harp on a tape that keeps snagging, and occasionally runs backwards.")
            .at (57, 1, 0.82f, 4.0)
            .chain ("RETRO,CRUSH,REWIND,FILTER,GRAIN,SPACE")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 10.0f).v (PID::voiceVariation, 0.56f)
            .v (PID::driftAmount, 0.36f).v (PID::driftRate, 0.22f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.78f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::saw).v (PID::oscBLevel, 0.30f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, -14.0f)
            .v (PID::oscBPan, 0.30f)
            .v (PID::subLevel, 0.14f)
            .v (PID::noiseType, ch::nDigital).v (PID::noiseLevel, 0.10f)
            .v (PID::noiseAttackOnly, 0.95f)
            .v (PID::bodyAmount, 0.30f).v (PID::densityAmount, 0.24f)
            .v (PID::preFilterDrive, 0.20f).v (PID::postSaturation, 0.16f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 3000.0f).v (PID::filterResonance, 0.26f)
            .v (PID::filterKeyTrack, 0.80f).v (PID::filterEnvAmount, 0.58f)
            .v (PID::filterVelAmount, 0.55f)
            .v (PID::ampAttack, 0.0012f).v (PID::ampDecay, 1.6f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.9f)
            .v (PID::ampVelocity, 0.62f)
            .v (PID::env1Decay, 0.22f).v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.62f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.64f).v (PID::memoryWobble, 0.62f)
            .v (PID::memoryDiffusion, 0.44f).v (PID::memoryAsymmetry, 0.52f)
            .v (PID::macroCharacter, 0.48f).v (PID::macroMotion, 0.54f)
            .v (PID::macroWorld, 0.44f).v (PID::macroWeight, 0.24f)
            .v (PID::retroEra, 0.80f).v (PID::retroAge, 0.52f)
            .v (PID::retroDrift, 0.54f).v (PID::retroWear, 0.48f)
            .v (PID::retroTone, -0.10f).v (PID::retroNoise, 0.22f)
            .v (PID::retroMix, 0.86f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.34f)
            .v (PID::crushBits, 10.0f).v (PID::crushRate, 14000.0f)
            .v (PID::crushJitter, 0.34f).v (PID::crushDrive, 0.18f)
            .v (PID::crushMix, 0.48f)
            .v (PID::rewindOn, 1.0f).v (PID::rewindMode, ch::rReverse)
            .v (PID::rewindDivision, ch::rw4).v (PID::rewindSync, 1.0f)
            .v (PID::rewindCurve, 0.62f).v (PID::rewindSpeed, 1.0f)
            .v (PID::rewindTail, 0.38f).v (PID::rewindMix, 0.40f)
            .v (PID::fxFilterCutoff, 7000.0f).v (PID::fxFilterRes, 0.14f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.38f)
            .v (PID::spaceSize, 0.48f).v (PID::spaceDecay, 2.6f)
            .v (PID::spaceFog, 0.46f).v (PID::spaceLight, -0.22f)
            .v (PID::spaceMix, 0.28f)
            .v (PID::auraSize, 0.46f).v (PID::auraDistance, 0.32f)
            .v (PID::auraFog, 0.52f).v (PID::auraDecay, 0.42f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.16f)
            .v (PID::patinaNoise, 0.24f).v (PID::patinaWear, 0.48f)
            .v (PID::patinaDrift, 0.38f)
            .v (PID::breathAmount, 0.46f).v (PID::breathSpeed, 0.34f)
            .v (PID::breathRandom, 0.76f).v (PID::breathShape, 0.66f)
            .v (PID::lfo2Shape, ch::lfoRandom).v (PID::lfo2Rate, 1.6f)
            .v (PID::lfo2Depth, 0.50f)
            .route (srcLfo2, PID::crushRate, -0.22f)
            .route (srcOrganic, PID::filterCutoff, 0.10f)
            .route (srcBreath, PID::memoryWobble, 0.20f));

        // METALLIC at a high frame, no sub, a notch in the creative filter
        // and CHROME on the surface: bright, hard, and short.
        add (out, Build ("Glass Pizzicato", "PLUCKS", "COLD",
                         "metallic,bright,notch,chrome",
                         "A string section plucked with something that was never meant to touch strings.")
            .at (64, 1, 0.88f, 2.5)
            .chain ("FILTER,CRUSH,RETRO,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::masterGain, 4.0f)
            .v (PID::polyphony, 14.0f).v (PID::voiceVariation, 0.30f)
            .v (PID::driftAmount, 0.10f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tMetal)
            .v (PID::oscAWtPos, 0.42f).v (PID::oscALevel, 0.84f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.08f)
            .v (PID::oscASpread, 0.55f).v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tSpectral)
            .v (PID::oscBWtPos, 0.70f).v (PID::oscBLevel, 0.24f)
            .v (PID::oscBOctave, 1.0f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nWhite).v (PID::noiseLevel, 0.14f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.10f).v (PID::densityAmount, 0.12f)
            .v (PID::postSaturation, 0.08f).v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 7000.0f).v (PID::filterResonance, 0.20f)
            .v (PID::filterKeyTrack, 1.0f).v (PID::filterEnvAmount, 0.44f)
            .v (PID::filterVelAmount, 0.66f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Notch)
            .v (PID::filter2Cutoff, 2600.0f).v (PID::filter2Res, 0.44f)
            .v (PID::filter2Mix, 0.52f)
            .v (PID::ampAttack, 0.0006f).v (PID::ampDecay, 0.85f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.40f)
            .v (PID::ampVelocity, 0.74f)
            .v (PID::env1Decay, 0.12f).v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.14f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.20f).v (PID::memoryWobble, 0.12f)
            .v (PID::macroCharacter, 0.20f).v (PID::macroMotion, 0.22f)
            .v (PID::macroWorld, 0.46f).v (PID::macroWeight, 0.26f)
            .v (PID::weightMode, ch::wAir).v (PID::weightHarmonics, 0.48f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.22f)
            .v (PID::crushBits, 13.0f).v (PID::crushRate, 26000.0f)
            .v (PID::crushTone, 0.30f).v (PID::crushMix, 0.40f)
            .v (PID::retroEra, 0.92f).v (PID::retroAge, 0.12f)
            .v (PID::retroDrift, 0.08f).v (PID::retroWear, 0.06f)
            .v (PID::retroTone, 0.26f).v (PID::retroNoise, 0.06f)
            .v (PID::retroMix, 0.40f)
            .v (PID::fxFilterCutoff, 15000.0f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.36f)
            .v (PID::spaceSize, 0.52f).v (PID::spaceDecay, 3.0f)
            .v (PID::spaceFog, 0.30f).v (PID::spaceLight, 0.40f)
            .v (PID::spacePreDelay, 16.0f).v (PID::spaceMix, 0.30f)
            .v (PID::auraSize, 0.44f).v (PID::auraDistance, 0.28f)
            .v (PID::auraFog, 0.30f).v (PID::auraDecay, 0.38f)
            .v (PID::auraLight, 0.44f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.28f)
            .v (PID::patinaNoise, 0.12f).v (PID::patinaWear, 0.20f)
            .v (PID::synthWidth, 1.15f).v (PID::highWidth, 1.35f)
            .v (PID::breathAmount, 0.20f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.34f)
            .v (PID::lfo1Depth, 0.45f)
            .route (srcLfo1, PID::filter2Cutoff, 0.20f)
            .route (srcWheel, PID::oscAWtPos, 0.30f));

        // MASS, no wavetable anywhere, a slow body-heavy pluck with the
        // ACETATE end of Retro: the oldest-sounding decision in the set.
        add (out, Build ("Old Nylon", "PLUCKS", "NOSTALGIC",
                         "nylon,acetate,soft,body",
                         "A nylon-string guitar off a 78, with the shellac still on it.")
            .at (52, 1, 0.70f, 3.5)
            .chain ("RETRO,FILTER,SPACE,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 10.0f).v (PID::voiceVariation, 0.36f)
            .v (PID::driftAmount, 0.26f).v (PID::driftRate, 0.13f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.82f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::saw).v (PID::oscBLevel, 0.28f)
            .v (PID::oscBFine, 6.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.26f)
            .v (PID::subHarmonics, 0.34f)
            .v (PID::noiseType, ch::nTexture).v (PID::noiseLevel, 0.14f)
            .v (PID::noiseAttackOnly, 0.90f)
            .v (PID::bodyAmount, 0.66f).v (PID::bodyTilt, 0.30f)
            .v (PID::densityAmount, 0.36f)
            .v (PID::preFilterDrive, 0.16f).v (PID::postSaturation, 0.20f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 2000.0f).v (PID::filterResonance, 0.18f)
            .v (PID::filterDrive, 0.26f).v (PID::filterKeyTrack, 0.85f)
            .v (PID::filterEnvAmount, 0.46f).v (PID::filterVelAmount, 0.52f)
            .v (PID::ampAttack, 0.002f).v (PID::ampDecay, 1.9f)
            .v (PID::ampSustain, 0.05f).v (PID::ampRelease, 0.9f)
            .v (PID::ampVelocity, 0.66f)
            .v (PID::env1Decay, 0.28f).v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.50f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.70f).v (PID::memoryWobble, 0.44f)
            .v (PID::memoryDiffusion, 0.30f).v (PID::memoryAsymmetry, 0.26f)
            .v (PID::macroCharacter, 0.46f).v (PID::macroMotion, 0.36f)
            .v (PID::macroWorld, 0.30f).v (PID::macroWeight, 0.42f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.40f)
            .v (PID::retroEra, 0.06f).v (PID::retroAge, 0.58f)
            .v (PID::retroDrift, 0.40f).v (PID::retroWear, 0.38f)
            .v (PID::retroTone, -0.36f).v (PID::retroNoise, 0.28f)
            .v (PID::retroMix, 0.92f)
            .v (PID::fxFilterCutoff, 4600.0f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.28f)
            .v (PID::spaceSize, 0.32f).v (PID::spaceDecay, 1.3f)
            .v (PID::spaceFog, 0.36f).v (PID::spaceLight, -0.44f)
            .v (PID::spaceMix, 0.22f)
            .v (PID::auraSize, 0.34f).v (PID::auraDistance, 0.22f)
            .v (PID::auraFog, 0.44f).v (PID::auraDecay, 0.30f)
            .v (PID::auraLight, -0.32f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.30f)
            .v (PID::patinaNoise, 0.26f).v (PID::patinaWear, 0.38f)
            .v (PID::patinaDrift, 0.26f)
            .v (PID::synthWidth, 0.85f)
            .v (PID::breathAmount, 0.36f).v (PID::breathSpeed, 0.20f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.22f)
            .v (PID::lfo1Depth, 0.50f)
            .route (srcLfo1, PID::retroDrift, 0.20f)
            .route (srcBreath, PID::bodyAmount, 0.12f));
    }
}
