#include "PresetBuilder.h"
#include "Builders.h"

namespace nacar::presets::detail
{
    // ===============================================================
    //  SEQUENCES
    //
    //  NACAR has no arpeggiator and no step sequencer, so "sequence" here
    //  means a patch whose movement is locked to the host: a tempo-synced
    //  LFO into the matrix, Pulse on the grid, or Rewind re-arming on a
    //  division.  Hold one note and the bar does the rest.
    // ===============================================================
    void buildSequences (std::vector<FactoryPreset>& out)
    {
        // Pulse on the sixteenth into volume, brightness, wetness and
        // width at once - section 83's four-destination duck - with a
        // synced square LFO gating the cutoff against it.
        add (out, Build ("Midnight Pulse", "SEQUENCES", "DARK",
                         "pulse,1/16,sidechain,gate",
                         "One held note turned into a bar by the pulse engine alone.")
            .at (40, 2, 0.86f, 6.0)
            .chain ("FILTER,RETRO,CRUSH,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.22f)
            .v (PID::driftAmount, 0.16f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.72f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.12f)
            .v (PID::oscASpread, 0.35f)
            .v (PID::oscBWave, ch::square).v (PID::oscBLevel, 0.34f)
            .v (PID::oscBPulseWidth, 0.30f).v (PID::oscBOctave, -1.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.40f)
            .v (PID::subHarmonics, 0.30f)
            .v (PID::bodyAmount, 0.52f).v (PID::densityAmount, 0.34f)
            .v (PID::preFilterDrive, 0.32f).v (PID::postSaturation, 0.24f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1400.0f).v (PID::filterResonance, 0.34f)
            .v (PID::filterDrive, 0.34f).v (PID::filterKeyTrack, 0.40f)
            .v (PID::filterEnvAmount, 0.30f).v (PID::filterVelAmount, 0.35f)
            .v (PID::ampAttack, 0.006f).v (PID::ampDecay, 1.0f)
            .v (PID::ampSustain, 0.86f).v (PID::ampRelease, 0.30f)
            .v (PID::macroMemory, 0.32f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.52f).v (PID::memoryWobble, 0.22f)
            .v (PID::memoryAsymmetry, 0.20f)
            .v (PID::macroCharacter, 0.50f).v (PID::macroMotion, 0.30f)
            .v (PID::macroWorld, 0.34f).v (PID::macroWeight, 0.48f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.48f)
            .v (PID::weightCompress, 0.38f)
            .v (PID::pulseOn, 1.0f).v (PID::pulseSource, ch::pClock)
            .v (PID::pulseDivision, ch::p16).v (PID::pulseDepth, 0.72f)
            .v (PID::pulseAttack, 0.0015f).v (PID::pulseRelease, 0.16f)
            .v (PID::pulseSmooth, 0.28f)
            .v (PID::pulseToVolume, 0.88f).v (PID::pulseToFilter, 0.55f)
            .v (PID::pulseToSpace, 0.50f).v (PID::pulseToWidth, 0.35f)
            .v (PID::pulseToMemory, 0.25f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.22f)
            .v (PID::crushBits, 12.0f).v (PID::crushRate, 22000.0f)
            .v (PID::crushMix, 0.32f)
            .v (PID::retroEra, 0.42f).v (PID::retroAge, 0.34f)
            .v (PID::retroDrift, 0.16f).v (PID::retroWear, 0.18f)
            .v (PID::retroTone, -0.24f).v (PID::retroNoise, 0.12f)
            .v (PID::retroMix, 0.58f)
            .v (PID::fxFilterCutoff, 5200.0f).v (PID::fxFilterRes, 0.18f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.34f)
            .v (PID::spaceSize, 0.48f).v (PID::spaceDecay, 3.0f)
            .v (PID::spaceFog, 0.44f).v (PID::spaceLight, -0.36f)
            .v (PID::spacePreDelay, 22.0f).v (PID::spaceMix, 0.30f)
            .v (PID::auraSize, 0.42f).v (PID::auraDistance, 0.28f)
            .v (PID::auraFog, 0.42f).v (PID::auraDecay, 0.36f)
            .v (PID::auraLight, -0.30f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.20f)
            .v (PID::patinaNoise, 0.14f).v (PID::patinaWear, 0.26f)
            .v (PID::synthWidth, 1.00f).v (PID::highWidth, 1.10f)
            .v (PID::lowMonoFreq, 200.0f)
            .v (PID::breathAmount, 0.24f)
            .v (PID::lfo1Shape, ch::lfoSquare).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d16).v (PID::lfo1Depth, 0.60f)
            .v (PID::lfo2Shape, ch::lfoTri).v (PID::lfo2Sync, 1.0f)
            .v (PID::lfo2Division, ch::d1).v (PID::lfo2Depth, 0.50f)
            .route (srcLfo1, PID::filterCutoff, 0.12f)
            .route (srcLfo2, PID::filterResonance, 0.14f));

        // The plainest tempo patch: a synced triangle LFO on the eighth
        // opening a short pluck, and almost nothing else moving.
        add (out, Build ("Hourglass", "SEQUENCES", "MINIMAL",
                         "1/8,synced,pluck,clean",
                         "A short note and a filter that opens on the eighth, and that is all.")
            .at (57, 2, 0.74f, 6.0)
            .chain ("FILTER,SPACE,RETRO,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.24f)
            .v (PID::driftAmount, 0.10f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tSoft)
            .v (PID::oscAWtPos, 0.34f).v (PID::oscALevel, 0.70f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.26f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, 3.0f)
            .v (PID::subLevel, 0.20f).v (PID::subHarmonics, 0.16f)
            .v (PID::bodyAmount, 0.24f).v (PID::densityAmount, 0.18f)
            .v (PID::postSaturation, 0.10f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 2200.0f).v (PID::filterResonance, 0.28f)
            .v (PID::filterKeyTrack, 0.60f).v (PID::filterEnvAmount, 0.40f)
            .v (PID::filterVelAmount, 0.45f)
            .v (PID::ampAttack, 0.001f).v (PID::ampDecay, 0.70f)
            .v (PID::ampSustain, 0.10f).v (PID::ampRelease, 0.45f)
            .v (PID::ampVelocity, 0.60f)
            .v (PID::env1Decay, 0.16f).v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.20f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.30f).v (PID::memoryWobble, 0.16f)
            .v (PID::macroCharacter, 0.24f).v (PID::macroMotion, 0.28f)
            .v (PID::macroWorld, 0.44f).v (PID::macroWeight, 0.28f)
            .v (PID::retroEra, 0.62f).v (PID::retroAge, 0.18f)
            .v (PID::retroDrift, 0.14f).v (PID::retroWear, 0.08f)
            .v (PID::retroNoise, 0.08f).v (PID::retroMix, 0.40f)
            .v (PID::fxFilterCutoff, 9000.0f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.34f)
            .v (PID::spaceSize, 0.48f).v (PID::spaceDecay, 2.6f)
            .v (PID::spaceFog, 0.32f).v (PID::spaceLight, 0.06f)
            .v (PID::spacePreDelay, 24.0f).v (PID::spaceMix, 0.28f)
            .v (PID::auraSize, 0.44f).v (PID::auraDistance, 0.26f)
            .v (PID::auraFog, 0.30f).v (PID::auraDecay, 0.36f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaNoise, 0.08f)
            .v (PID::patinaWear, 0.14f).v (PID::patinaDrift, 0.16f)
            .v (PID::synthWidth, 1.10f).v (PID::highWidth, 1.15f)
            .v (PID::breathAmount, 0.26f).v (PID::breathSpeed, 0.18f)
            .v (PID::lfo1Shape, ch::lfoTri).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d8).v (PID::lfo1Depth, 0.70f)
            .v (PID::lfo2Shape, ch::lfoSine).v (PID::lfo2Sync, 1.0f)
            .v (PID::lfo2Division, ch::d2bar).v (PID::lfo2Depth, 0.45f)
            .route (srcLfo1, PID::filterCutoff, 0.16f)
            .route (srcLfo2, PID::oscAWtPos, 0.22f));

        // Rewind in RETURN mode re-arms on the bar and lands back exactly
        // on realtime, with a slow grain cloud reading the same history.
        add (out, Build ("Tape Loop", "SEQUENCES", "NOSTALGIC",
                         "rewind,1 bar,loop,tape",
                         "A one-bar loop that jumps back on the barline and catches up by the end of it.")
            .at (48, 3, 0.72f, 8.0)
            .chain ("RETRO,REWIND,GRAIN,FILTER,SPACE,CRUSH")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.40f)
            .v (PID::driftAmount, 0.28f).v (PID::driftRate, 0.10f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.66f)
            .v (PID::oscAUnison, 3.0f).v (PID::oscADetune, 0.18f)
            .v (PID::oscASpread, 0.62f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tOrganic)
            .v (PID::oscBWtPos, 0.40f).v (PID::oscBLevel, 0.36f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, 8.0f)
            .v (PID::subLevel, 0.22f).v (PID::subHarmonics, 0.18f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.10f)
            .v (PID::bodyAmount, 0.38f).v (PID::densityAmount, 0.30f)
            .v (PID::preFilterDrive, 0.18f).v (PID::postSaturation, 0.18f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 2800.0f).v (PID::filterResonance, 0.16f)
            .v (PID::filterKeyTrack, 0.50f).v (PID::filterEnvAmount, 0.34f)
            .v (PID::ampAttack, 0.15f).v (PID::ampDecay, 2.2f)
            .v (PID::ampSustain, 0.70f).v (PID::ampRelease, 1.6f)
            .v (PID::ampVelocity, 0.45f)
            .v (PID::macroMemory, 0.50f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.62f).v (PID::memoryWobble, 0.44f)
            .v (PID::memoryDiffusion, 0.40f).v (PID::memoryAsymmetry, 0.34f)
            .v (PID::macroCharacter, 0.44f).v (PID::macroMotion, 0.52f)
            .v (PID::macroWorld, 0.48f).v (PID::macroWeight, 0.34f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::rewindOn, 1.0f).v (PID::rewindMode, ch::rReturn)
            .v (PID::rewindDivision, ch::rw1bar).v (PID::rewindSync, 1.0f)
            .v (PID::rewindCurve, 0.35f).v (PID::rewindSpeed, 1.0f)
            .v (PID::rewindTail, 0.30f).v (PID::rewindMix, 0.55f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.28f)
            .v (PID::grainSize, 130.0f).v (PID::grainDensity, 16.0f)
            .v (PID::grainPosition, 0.50f).v (PID::grainPitchMode, ch::gOctave)
            .v (PID::grainSpread, 0.62f).v (PID::grainJitter, 0.30f)
            .v (PID::grainDirection, 0.20f).v (PID::grainWindow, ch::wHann)
            .v (PID::grainFeedback, 0.20f).v (PID::grainMix, 0.34f)
            .v (PID::retroEra, 0.38f).v (PID::retroAge, 0.48f)
            .v (PID::retroDrift, 0.44f).v (PID::retroWear, 0.28f)
            .v (PID::retroTone, -0.28f).v (PID::retroNoise, 0.20f)
            .v (PID::retroMix, 0.84f)
            .v (PID::fxFilterCutoff, 6000.0f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.44f)
            .v (PID::spaceSize, 0.60f).v (PID::spaceDecay, 4.0f)
            .v (PID::spaceFog, 0.52f).v (PID::spaceLight, -0.22f)
            .v (PID::spacePreDelay, 30.0f).v (PID::spaceMix, 0.32f)
            .v (PID::auraSize, 0.58f).v (PID::auraDistance, 0.36f)
            .v (PID::auraFog, 0.54f).v (PID::auraDecay, 0.52f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.22f)
            .v (PID::patinaNoise, 0.20f).v (PID::patinaWear, 0.34f)
            .v (PID::patinaDrift, 0.30f)
            .v (PID::synthWidth, 1.15f).v (PID::highWidth, 1.20f)
            .v (PID::breathAmount, 0.48f).v (PID::breathSpeed, 0.12f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d1).v (PID::lfo1Depth, 0.55f)
            .route (srcLfo1, PID::grainPosition, 0.30f)
            .route (srcBreath, PID::retroDrift, 0.20f));

        // A synced saw-down LFO on the sixteenth into cutoff, with grain
        // pitches drawn from the SCALE tier: the notes come from the cloud.
        add (out, Build ("Ghost Arpeggio", "SEQUENCES", "HAUNTED",
                         "1/16,granular,scale,falling",
                         "An arpeggio nobody played, assembled out of one held chord.")
            .at (50, 3, 0.72f, 8.0)
            .chain ("FILTER,GRAIN,RETRO,SPACE,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.44f)
            .v (PID::driftAmount, 0.26f).v (PID::driftRate, 0.14f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tHollow)
            .v (PID::oscAWtPos, 0.44f).v (PID::oscALevel, 0.68f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.14f)
            .v (PID::oscASpread, 0.58f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.30f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, -9.0f)
            .v (PID::subLevel, 0.14f)
            .v (PID::noiseType, ch::nTexture).v (PID::noiseLevel, 0.08f)
            .v (PID::bodyAmount, 0.24f).v (PID::densityAmount, 0.22f)
            .v (PID::preFilterDrive, 0.14f).v (PID::postSaturation, 0.14f)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 2400.0f).v (PID::filterResonance, 0.36f)
            .v (PID::filterKeyTrack, 0.45f).v (PID::filterEnvAmount, 0.30f)
            .v (PID::ampAttack, 0.35f).v (PID::ampDecay, 2.6f)
            .v (PID::ampSustain, 0.74f).v (PID::ampRelease, 2.4f)
            .v (PID::ampVelocity, 0.40f)
            .v (PID::macroMemory, 0.46f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.54f).v (PID::memoryWobble, 0.40f)
            .v (PID::memoryDiffusion, 0.52f).v (PID::memoryAsymmetry, 0.38f)
            .v (PID::macroCharacter, 0.36f).v (PID::macroMotion, 0.66f)
            .v (PID::macroWorld, 0.56f).v (PID::macroWeight, 0.26f)
            .v (PID::macroAlter, 0.28f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.66f)
            .v (PID::grainSize, 70.0f).v (PID::grainDensity, 30.0f)
            .v (PID::grainPosition, 0.28f).v (PID::grainPitchMode, ch::gScale)
            .v (PID::grainSpread, 0.78f).v (PID::grainJitter, 0.44f)
            .v (PID::grainDirection, 0.24f).v (PID::grainWindow, ch::wHann)
            .v (PID::grainFeedback, 0.30f).v (PID::grainMix, 0.56f)
            .v (PID::harmonyMode, ch::hColour).v (PID::scaleType, ch::scMinor)
            .v (PID::retroEra, 0.60f).v (PID::retroAge, 0.38f)
            .v (PID::retroDrift, 0.32f).v (PID::retroWear, 0.26f)
            .v (PID::retroTone, -0.16f).v (PID::retroNoise, 0.16f)
            .v (PID::retroMix, 0.64f)
            .v (PID::fxFilterCutoff, 7400.0f).v (PID::fxFilterRes, 0.20f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.56f)
            .v (PID::spaceSize, 0.68f).v (PID::spaceDecay, 5.5f)
            .v (PID::spaceFog, 0.56f).v (PID::spaceLight, -0.16f)
            .v (PID::spacePreDelay, 26.0f).v (PID::spaceMix, 0.40f)
            .v (PID::auraSize, 0.64f).v (PID::auraDistance, 0.42f)
            .v (PID::auraFog, 0.58f).v (PID::auraDecay, 0.58f)
            .v (PID::auraLight, -0.14f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.10f)
            .v (PID::patinaNoise, 0.18f).v (PID::patinaWear, 0.34f)
            .v (PID::patinaDrift, 0.38f)
            .v (PID::synthWidth, 1.25f).v (PID::highWidth, 1.30f)
            .v (PID::breathAmount, 0.56f).v (PID::breathSpeed, 0.24f)
            .v (PID::breathRandom, 0.70f)
            .v (PID::lfo1Shape, ch::lfoSawDown).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d16).v (PID::lfo1Depth, 0.65f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Sync, 1.0f)
            .v (PID::lfo2Division, ch::d2).v (PID::lfo2Depth, 0.55f)
            .route (srcLfo1, PID::filterCutoff, 0.18f)
            .route (srcLfo2, PID::grainPosition, 0.34f)
            .route (srcBreath, PID::grainSize, 0.20f));

        // ---------------------------------------------------------------
        //  DEMBOW-ADJACENT: the pulse engine on the grid, with a synced LFO
        //  on a dotted or triplet division crossing it rather than doubling
        //  it.  Pulse's named divisions stop at 1/16, 1/8, 1/4 and 1/2, so
        //  the swing here always comes from the LFO side.
        // ---------------------------------------------------------------

        // Clock pulse on the sixteenth into level, brightness, width and
        // wetness; LFO 1 squares the cutoff on the dotted eighth, which
        // lands three times where the pulse lands four.
        add (out, Build ("Dembow de Hierro", "SEQUENCES", "DARK",
                         "pulse,1/16,urbano,gate",
                         "A saw and a narrow pulse ducked on every sixteenth by the clock, with the cutoff squared on the dotted eighth across it.")
            .at (48, 2, 0.88f, 7.0)
            .chain ("CRUSH,FILTER,RETRO,SPACE,REWIND,GRAIN")
            .v (PID::masterGain, -1.5f)
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.20f)
            .v (PID::driftAmount, 0.14f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.70f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.14f)
            .v (PID::oscASpread, 0.30f).v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::square).v (PID::oscBLevel, 0.38f)
            .v (PID::oscBPulseWidth, 0.28f).v (PID::oscBOctave, -1.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.38f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.34f)
            .v (PID::bodyAmount, 0.48f).v (PID::densityAmount, 0.30f)
            .v (PID::preFilterDrive, 0.30f).v (PID::postSaturation, 0.22f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1200.0f).v (PID::filterResonance, 0.38f)
            .v (PID::filterDrive, 0.32f).v (PID::filterKeyTrack, 0.45f)
            .v (PID::filterEnvAmount, 0.42f).v (PID::filterVelAmount, 0.30f)
            .v (PID::ampAttack, 0.002f).v (PID::ampDecay, 0.45f)
            .v (PID::ampSustain, 0.50f).v (PID::ampRelease, 0.16f)
            .v (PID::ampVelocity, 0.55f)
            .v (PID::env1Decay, 0.10f).v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.26f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.48f).v (PID::memoryWobble, 0.18f)
            .v (PID::macroCharacter, 0.46f).v (PID::macroMotion, 0.24f)
            .v (PID::macroWorld, 0.30f).v (PID::macroWeight, 0.52f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.50f)
            .v (PID::weightCompress, 0.36f)
            .v (PID::pulseOn, 1.0f).v (PID::pulseSource, ch::pClock)
            .v (PID::pulseDivision, ch::p16).v (PID::pulseDepth, 0.78f)
            .v (PID::pulseAttack, 0.001f).v (PID::pulseRelease, 0.075f)
            .v (PID::pulseSmooth, 0.22f)
            .v (PID::pulseToVolume, 0.92f).v (PID::pulseToFilter, 0.60f)
            .v (PID::pulseToSpace, 0.45f).v (PID::pulseToWidth, 0.40f)
            .v (PID::pulseToMemory, 0.18f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.28f)
            .v (PID::crushBits, 10.0f).v (PID::crushRate, 18000.0f)
            .v (PID::crushDrive, 0.25f).v (PID::crushMix, 0.35f)
            .v (PID::retroEra, 0.40f).v (PID::retroAge, 0.30f)
            .v (PID::retroDrift, 0.14f).v (PID::retroWear, 0.16f)
            .v (PID::retroTone, -0.25f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.55f)
            .v (PID::fxFilterCutoff, 5600.0f).v (PID::fxFilterRes, 0.16f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.30f)
            .v (PID::spaceSize, 0.44f).v (PID::spaceDecay, 2.4f)
            .v (PID::spaceFog, 0.42f).v (PID::spaceLight, -0.38f)
            .v (PID::spacePreDelay, 18.0f).v (PID::spaceMix, 0.24f)
            .v (PID::auraSize, 0.38f).v (PID::auraDistance, 0.24f)
            .v (PID::auraFog, 0.40f).v (PID::auraDecay, 0.32f)
            .v (PID::auraLight, -0.32f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.22f)
            .v (PID::patinaNoise, 0.12f).v (PID::patinaWear, 0.24f)
            .v (PID::synthWidth, 0.95f).v (PID::highWidth, 1.10f)
            .v (PID::lowMonoFreq, 190.0f)
            .v (PID::breathAmount, 0.18f)
            .v (PID::lfo1Shape, ch::lfoSquare).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d8dot).v (PID::lfo1Depth, 0.65f)
            .v (PID::lfo2Shape, ch::lfoTri).v (PID::lfo2Sync, 1.0f)
            .v (PID::lfo2Division, ch::d2).v (PID::lfo2Depth, 0.45f)
            .route (srcLfo1, PID::filterCutoff, 0.16f)
            .route (srcLfo2, PID::oscBPulseWidth, 0.18f));

        // Pulse on the eighth, with the two chain filters moving on a dotted
        // eighth and a dotted quarter - two periods that do not divide each
        // other, so the pattern takes several bars to come back round.
        add (out, Build ("Trafico Nocturno", "SEQUENCES", "DARK",
                         "pulse,1/8,dotted,comb",
                         "A vocal wavetable ducked on the eighth, read through a comb filter that moves on the dotted quarter.")
            .at (50, 2, 0.82f, 7.0)
            .chain ("FILTER,CRUSH,RETRO,GRAIN,SPACE,REWIND")
            .v (PID::masterGain, -1.0f)
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.28f)
            .v (PID::driftAmount, 0.20f).v (PID::driftRate, 0.16f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tVocal)
            .v (PID::oscAWtPos, 0.38f).v (PID::oscALevel, 0.68f)
            .v (PID::oscBWave, ch::saw).v (PID::oscBLevel, 0.34f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, 6.0f)
            .v (PID::subLevel, 0.28f).v (PID::subHarmonics, 0.24f)
            .v (PID::bodyAmount, 0.36f).v (PID::densityAmount, 0.28f)
            .v (PID::preFilterDrive, 0.22f).v (PID::postSaturation, 0.16f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1600.0f).v (PID::filterResonance, 0.30f)
            .v (PID::filterKeyTrack, 0.50f).v (PID::filterEnvAmount, 0.34f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Comb)
            .v (PID::filter2Cutoff, 900.0f).v (PID::filter2Res, 0.36f)
            .v (PID::filter2Mix, 0.40f)
            .v (PID::ampAttack, 0.004f).v (PID::ampDecay, 0.80f)
            .v (PID::ampSustain, 0.62f).v (PID::ampRelease, 0.35f)
            .v (PID::macroMemory, 0.34f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.54f).v (PID::memoryWobble, 0.26f)
            .v (PID::macroCharacter, 0.40f).v (PID::macroMotion, 0.34f)
            .v (PID::macroWorld, 0.38f).v (PID::macroWeight, 0.40f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::pulseOn, 1.0f).v (PID::pulseSource, ch::pClock)
            .v (PID::pulseDivision, ch::p8).v (PID::pulseDepth, 0.70f)
            .v (PID::pulseAttack, 0.0015f).v (PID::pulseRelease, 0.14f)
            .v (PID::pulseSmooth, 0.30f)
            .v (PID::pulseToVolume, 0.86f).v (PID::pulseToFilter, 0.52f)
            .v (PID::pulseToSpace, 0.48f).v (PID::pulseToWidth, 0.32f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.20f)
            .v (PID::crushBits, 12.0f).v (PID::crushRate, 16000.0f)
            .v (PID::crushTone, -0.20f).v (PID::crushMix, 0.30f)
            .v (PID::retroEra, 0.50f).v (PID::retroAge, 0.34f)
            .v (PID::retroDrift, 0.22f).v (PID::retroWear, 0.20f)
            .v (PID::retroTone, -0.30f).v (PID::retroNoise, 0.14f)
            .v (PID::retroMix, 0.62f)
            .v (PID::fxFilterCutoff, 4800.0f).v (PID::fxFilterRes, 0.22f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.38f)
            .v (PID::spaceSize, 0.50f).v (PID::spaceDecay, 3.4f)
            .v (PID::spaceFog, 0.48f).v (PID::spaceLight, -0.34f)
            .v (PID::spacePreDelay, 26.0f).v (PID::spaceMix, 0.30f)
            .v (PID::auraSize, 0.46f).v (PID::auraDistance, 0.32f)
            .v (PID::auraFog, 0.46f).v (PID::auraDecay, 0.40f)
            .v (PID::auraLight, -0.26f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.26f)
            .v (PID::patinaNoise, 0.16f).v (PID::patinaWear, 0.28f)
            .v (PID::patinaDrift, 0.22f)
            .v (PID::synthWidth, 1.05f).v (PID::highWidth, 1.18f)
            .v (PID::lowMonoFreq, 170.0f)
            .v (PID::breathAmount, 0.26f).v (PID::breathSpeed, 0.16f)
            .v (PID::lfo1Shape, ch::lfoSawDown).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d8dot).v (PID::lfo1Depth, 0.70f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Sync, 1.0f)
            .v (PID::lfo2Division, ch::d4dot).v (PID::lfo2Depth, 0.50f)
            .route (srcLfo1, PID::fxFilterCutoff, 0.20f)
            .route (srcLfo2, PID::filter2Cutoff, 0.22f)
            .route (srcPulse, PID::oscAWtPos, -0.14f));

        // The sparse version of the same idea: one hollow wavetable, a comb
        // filter, a sixteenth-note duck and an eighth-triplet square on the
        // cutoff.  Nothing else is switched on.
        add (out, Build ("Semaforo", "SEQUENCES", "MINIMAL",
                         "pulse,1/16,triplet,sparse",
                         "One hollow wavetable through the COMB filter, ducked on the sixteenth and gated on the eighth triplet.")
            .at (55, 1, 0.76f, 6.0)
            .chain ("FILTER,RETRO,SPACE,CRUSH,REWIND,GRAIN")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.18f)
            .v (PID::driftAmount, 0.10f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tHollow)
            .v (PID::oscAWtPos, 0.30f).v (PID::oscALevel, 0.72f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.24f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, -4.0f)
            .v (PID::subLevel, 0.16f).v (PID::subHarmonics, 0.12f)
            .v (PID::bodyAmount, 0.22f).v (PID::densityAmount, 0.16f)
            .v (PID::postSaturation, 0.10f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 2600.0f).v (PID::filterResonance, 0.22f)
            .v (PID::filterKeyTrack, 0.65f).v (PID::filterEnvAmount, 0.28f)
            .v (PID::ampAttack, 0.0015f).v (PID::ampDecay, 0.55f)
            .v (PID::ampSustain, 0.48f).v (PID::ampRelease, 0.22f)
            .v (PID::ampVelocity, 0.50f)
            .v (PID::env1Decay, 0.12f).v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.16f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.30f)
            .v (PID::macroCharacter, 0.22f).v (PID::macroMotion, 0.22f)
            .v (PID::macroWorld, 0.32f).v (PID::macroWeight, 0.26f)
            .v (PID::pulseOn, 1.0f).v (PID::pulseSource, ch::pClock)
            .v (PID::pulseDivision, ch::p16).v (PID::pulseDepth, 0.66f)
            .v (PID::pulseAttack, 0.0012f).v (PID::pulseRelease, 0.070f)
            .v (PID::pulseSmooth, 0.24f)
            .v (PID::pulseToVolume, 0.85f).v (PID::pulseToFilter, 0.30f)
            .v (PID::pulseToSpace, 0.35f).v (PID::pulseToWidth, 0.30f)
            .v (PID::retroEra, 0.56f).v (PID::retroAge, 0.16f)
            .v (PID::retroDrift, 0.10f).v (PID::retroWear, 0.06f)
            .v (PID::retroNoise, 0.06f).v (PID::retroMix, 0.34f)
            .v (PID::fxFilterCutoff, 8200.0f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.26f)
            .v (PID::spaceSize, 0.36f).v (PID::spaceDecay, 1.8f)
            .v (PID::spaceFog, 0.26f).v (PID::spaceLight, 0.04f)
            .v (PID::spacePreDelay, 14.0f).v (PID::spaceMix, 0.22f)
            .v (PID::auraSize, 0.32f).v (PID::auraDistance, 0.20f)
            .v (PID::auraFog, 0.24f).v (PID::auraDecay, 0.28f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaNoise, 0.06f)
            .v (PID::patinaWear, 0.10f)
            .v (PID::synthWidth, 1.00f).v (PID::highWidth, 1.12f)
            .v (PID::breathAmount, 0.14f)
            .v (PID::lfo1Shape, ch::lfoSquare).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d8t).v (PID::lfo1Depth, 0.60f)
            .v (PID::lfo2Shape, ch::lfoSine).v (PID::lfo2Sync, 1.0f)
            .v (PID::lfo2Division, ch::d1).v (PID::lfo2Depth, 0.40f)
            .route (srcLfo1, PID::filterCutoff, 0.14f)
            .route (srcLfo2, PID::oscAWtPos, 0.20f));

        // The dirty end of the grid: pulse on the eighth for the duck, and a
        // square LFO on the sixteenth stepping the crusher's sample rate, so
        // every other duck arrives through a coarser converter.
        add (out, Build ("Third Rail", "SEQUENCES", "DIRTY",
                         "pulse,1/8,crush,urbano",
                         "A driven saw ducked on the eighth, with the crusher's sample rate stepped on the sixteenth underneath it.")
            .at (49, 2, 0.90f, 7.0)
            .chain ("RETRO,CRUSH,FILTER,SPACE,GRAIN,REWIND")
            .v (PID::masterGain, -2.5f)
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::poly).v (PID::polyphony, 5.0f)
            .v (PID::voiceVariation, 0.24f).v (PID::driftAmount, 0.18f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.74f)
            .v (PID::oscAUnison, 3.0f).v (PID::oscADetune, 0.20f)
            .v (PID::oscASpread, 0.28f)
            .v (PID::oscBWave, ch::square).v (PID::oscBLevel, 0.30f)
            .v (PID::oscBPulseWidth, 0.18f).v (PID::oscBOctave, -1.0f)
            .v (PID::oscRingMod, 0.12f)
            .v (PID::subWave, ch::subSquare).v (PID::subLevel, 0.34f)
            .v (PID::subHarmonics, 0.40f)
            .v (PID::bodyAmount, 0.44f).v (PID::bodyTilt, 0.24f)
            .v (PID::densityAmount, 0.32f)
            .v (PID::preFilterDrive, 0.46f).v (PID::postSaturation, 0.30f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1500.0f).v (PID::filterResonance, 0.30f)
            .v (PID::filterDrive, 0.45f).v (PID::filterKeyTrack, 0.40f)
            .v (PID::filterEnvAmount, 0.36f)
            .v (PID::ampAttack, 0.0018f).v (PID::ampDecay, 0.60f)
            .v (PID::ampSustain, 0.56f).v (PID::ampRelease, 0.18f)
            .v (PID::ampVelocity, 0.60f)
            .v (PID::env1Decay, 0.14f).v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.30f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.58f).v (PID::memoryWobble, 0.24f)
            .v (PID::macroCharacter, 0.64f).v (PID::macroMotion, 0.28f)
            .v (PID::macroWorld, 0.26f).v (PID::macroWeight, 0.50f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.54f)
            .v (PID::pulseOn, 1.0f).v (PID::pulseSource, ch::pClock)
            .v (PID::pulseDivision, ch::p8).v (PID::pulseDepth, 0.80f)
            .v (PID::pulseAttack, 0.0008f).v (PID::pulseRelease, 0.13f)
            .v (PID::pulseSmooth, 0.15f)
            .v (PID::pulseToVolume, 0.90f).v (PID::pulseToFilter, 0.58f)
            .v (PID::pulseToSpace, 0.40f).v (PID::pulseToWidth, 0.36f)
            .v (PID::pulseToMemory, 0.30f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.45f)
            .v (PID::crushBits, 8.0f).v (PID::crushRate, 9000.0f)
            .v (PID::crushJitter, 0.20f).v (PID::crushDrive, 0.35f)
            .v (PID::crushTone, -0.12f).v (PID::crushMix, 0.62f)
            .v (PID::retroEra, 0.30f).v (PID::retroAge, 0.40f)
            .v (PID::retroDrift, 0.18f).v (PID::retroWear, 0.26f)
            .v (PID::retroTone, -0.20f).v (PID::retroNoise, 0.16f)
            .v (PID::retroMix, 0.70f)
            .v (PID::fxFilterCutoff, 4200.0f).v (PID::fxFilterRes, 0.24f)
            .v (PID::fxFilterDrive, 0.26f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.24f)
            .v (PID::spaceSize, 0.34f).v (PID::spaceDecay, 1.6f)
            .v (PID::spaceFog, 0.36f).v (PID::spaceLight, -0.30f)
            .v (PID::spacePreDelay, 12.0f).v (PID::spaceMix, 0.20f)
            .v (PID::auraSize, 0.30f).v (PID::auraDistance, 0.18f)
            .v (PID::auraFog, 0.34f).v (PID::auraDecay, 0.26f)
            .v (PID::auraLight, -0.24f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, -0.08f)
            .v (PID::patinaNoise, 0.18f).v (PID::patinaWear, 0.32f)
            .v (PID::synthWidth, 0.90f).v (PID::highWidth, 1.05f)
            .v (PID::lowMonoFreq, 210.0f)
            .v (PID::breathAmount, 0.16f)
            .v (PID::lfo1Shape, ch::lfoSquare).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d16).v (PID::lfo1Depth, 0.75f)
            .v (PID::lfo2Shape, ch::lfoSawUp).v (PID::lfo2Sync, 1.0f)
            .v (PID::lfo2Division, ch::d4t).v (PID::lfo2Depth, 0.50f)
            .route (srcLfo1, PID::crushRate, -0.30f)
            .route (srcLfo2, PID::filterCutoff, 0.14f));

        // ---------------------------------------------------------------
        //  ARPEGGIO-ADJACENT: a fast synced LFO re-tunes an oscillator or
        //  re-opens the filter once per division, against a short envelope.
        //  The pitch steps are continuous semitone offsets, not scale
        //  degrees - the matrix writes a float, not a note number.
        // ---------------------------------------------------------------

        // A sample-and-hold LFO on the sixteenth retunes oscillator B, and a
        // saw-down LFO on the eighth closes the resonant filter after each
        // step, so a held note articulates twice per beat.
        add (out, Build ("Escapement", "SEQUENCES", "COLD",
                         "1/16,stepped,pitch,clock",
                         "A sample-and-hold LFO steps oscillator B's tuning every sixteenth against a filter that recloses on the eighth.")
            .at (57, 1, 0.78f, 7.0)
            .chain ("FILTER,SPACE,CRUSH,RETRO,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::voiceMode, ch::mono).v (PID::glideTime, 0.0f)
            .v (PID::voiceVariation, 0.16f).v (PID::driftAmount, 0.08f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tSpectral)
            .v (PID::oscAWtPos, 0.30f).v (PID::oscALevel, 0.66f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.34f)
            .v (PID::oscBFine, 0.0f).v (PID::oscBPhase, ch::phaseReset)
            .v (PID::subLevel, 0.14f)
            .v (PID::bodyAmount, 0.20f).v (PID::densityAmount, 0.18f)
            .v (PID::postSaturation, 0.12f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 3000.0f).v (PID::filterResonance, 0.42f)
            .v (PID::filterKeyTrack, 0.70f).v (PID::filterEnvAmount, 0.50f)
            .v (PID::filterVelAmount, 0.40f)
            .v (PID::ampAttack, 0.001f).v (PID::ampDecay, 0.35f)
            .v (PID::ampSustain, 0.42f).v (PID::ampRelease, 0.22f)
            .v (PID::env1Attack, 0.001f).v (PID::env1Decay, 0.09f)
            .v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.14f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.26f)
            .v (PID::macroCharacter, 0.20f).v (PID::macroMotion, 0.30f)
            .v (PID::macroWorld, 0.36f).v (PID::macroWeight, 0.22f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::retroEra, 0.68f).v (PID::retroAge, 0.12f)
            .v (PID::retroDrift, 0.08f).v (PID::retroNoise, 0.06f)
            .v (PID::retroMix, 0.30f)
            .v (PID::fxFilterCutoff, 9600.0f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.36f)
            .v (PID::spaceSize, 0.46f).v (PID::spaceDecay, 2.8f)
            .v (PID::spaceFog, 0.30f).v (PID::spaceLight, 0.12f)
            .v (PID::spacePreDelay, 28.0f).v (PID::spaceMix, 0.30f)
            .v (PID::auraSize, 0.44f).v (PID::auraDistance, 0.28f)
            .v (PID::auraFog, 0.26f).v (PID::auraDecay, 0.34f)
            .v (PID::auraLight, 0.14f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.06f)
            .v (PID::patinaNoise, 0.06f).v (PID::patinaWear, 0.10f)
            .v (PID::synthWidth, 1.12f).v (PID::highWidth, 1.22f)
            .v (PID::breathAmount, 0.14f)
            .v (PID::lfo1Shape, ch::lfoRandom).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d16).v (PID::lfo1Depth, 0.85f)
            .v (PID::lfo2Shape, ch::lfoSawDown).v (PID::lfo2Sync, 1.0f)
            .v (PID::lfo2Division, ch::d8).v (PID::lfo2Depth, 0.70f)
            .route (srcLfo1, PID::oscBSemi, 0.26f)
            .route (srcLfo2, PID::filterCutoff, 0.20f));

        // The same trick on the eighth triplet, played back through a worn
        // medium: the step pattern repeats every three eighths while the
        // filter square repeats every sixteenth.
        add (out, Build ("Ticker Tape", "SEQUENCES", "NOSTALGIC",
                         "triplet,stepped,tape,arp",
                         "Oscillator B retuned on the eighth triplet and the cutoff squared on the sixteenth, run through a heavily worn medium.")
            .at (60, 1, 0.72f, 7.0)
            .chain ("RETRO,FILTER,CRUSH,SPACE,REWIND,GRAIN")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.34f)
            .v (PID::driftAmount, 0.26f).v (PID::driftRate, 0.20f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.62f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tMetal)
            .v (PID::oscBWtPos, 0.26f).v (PID::oscBLevel, 0.30f)
            .v (PID::oscBOctave, 1.0f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.08f)
            .v (PID::noiseAttackOnly, 0.55f)
            .v (PID::subLevel, 0.12f)
            .v (PID::bodyAmount, 0.26f).v (PID::densityAmount, 0.20f)
            .v (PID::postSaturation, 0.14f).v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 2800.0f).v (PID::filterResonance, 0.30f)
            .v (PID::filterKeyTrack, 0.55f).v (PID::filterEnvAmount, 0.38f)
            .v (PID::ampAttack, 0.0012f).v (PID::ampDecay, 0.40f)
            .v (PID::ampSustain, 0.46f).v (PID::ampRelease, 0.28f)
            .v (PID::env1Decay, 0.10f).v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.48f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.64f).v (PID::memoryWobble, 0.42f)
            .v (PID::memoryDiffusion, 0.34f).v (PID::memoryAsymmetry, 0.30f)
            .v (PID::macroCharacter, 0.42f).v (PID::macroMotion, 0.40f)
            .v (PID::macroWorld, 0.36f).v (PID::macroWeight, 0.24f)
            .v (PID::retroEra, 0.72f).v (PID::retroAge, 0.44f)
            .v (PID::retroDrift, 0.36f).v (PID::retroWear, 0.30f)
            .v (PID::retroTone, -0.18f).v (PID::retroNoise, 0.22f)
            .v (PID::retroMix, 0.80f)
            .v (PID::fxFilterCutoff, 6400.0f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.32f)
            .v (PID::spaceSize, 0.40f).v (PID::spaceDecay, 2.0f)
            .v (PID::spaceFog, 0.34f).v (PID::spaceLight, -0.10f)
            .v (PID::spacePreDelay, 20.0f).v (PID::spaceMix, 0.26f)
            .v (PID::auraSize, 0.36f).v (PID::auraDistance, 0.24f)
            .v (PID::auraFog, 0.32f).v (PID::auraDecay, 0.30f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.18f)
            .v (PID::patinaNoise, 0.22f).v (PID::patinaWear, 0.36f)
            .v (PID::patinaDrift, 0.28f)
            .v (PID::synthWidth, 1.05f).v (PID::highWidth, 1.14f)
            .v (PID::breathAmount, 0.30f).v (PID::breathSpeed, 0.20f)
            .v (PID::lfo1Shape, ch::lfoRandom).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d8t).v (PID::lfo1Depth, 0.80f)
            .v (PID::lfo2Shape, ch::lfoSquare).v (PID::lfo2Sync, 1.0f)
            .v (PID::lfo2Division, ch::d16).v (PID::lfo2Depth, 0.65f)
            .route (srcLfo1, PID::oscBSemi, 0.22f)
            .route (srcLfo2, PID::filterCutoff, 0.15f)
            .route (srcBreath, PID::retroDrift, 0.18f));

        // A rising ramp rather than a step: the saw-up LFO walks oscillator A
        // up through a whole tone across each eighth and drops back, with a
        // held random LFO moving the formant filter on the quarter.
        add (out, Build ("Escalera Mecanica", "SEQUENCES", "DREAMY",
                         "1/8,ramp,formant,rising",
                         "Oscillator A ramped upward across every eighth by a synced saw LFO, read through a formant filter stepped on the quarter.")
            .at (52, 2, 0.70f, 8.0)
            .chain ("FILTER,GRAIN,SPACE,RETRO,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.36f)
            .v (PID::driftAmount, 0.22f).v (PID::driftRate, 0.14f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tAsym)
            .v (PID::oscAWtPos, 0.42f).v (PID::oscALevel, 0.64f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.16f)
            .v (PID::oscASpread, 0.56f)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.28f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, 5.0f)
            .v (PID::subLevel, 0.16f)
            .v (PID::bodyAmount, 0.28f).v (PID::densityAmount, 0.24f)
            .v (PID::postSaturation, 0.12f)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 900.0f).v (PID::filterResonance, 0.35f)
            .v (PID::filterKeyTrack, 0.30f).v (PID::filterEnvAmount, 0.26f)
            .v (PID::ampAttack, 0.02f).v (PID::ampDecay, 1.2f)
            .v (PID::ampSustain, 0.58f).v (PID::ampRelease, 0.80f)
            .v (PID::macroMemory, 0.28f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.44f).v (PID::memoryWobble, 0.30f)
            .v (PID::macroCharacter, 0.28f).v (PID::macroMotion, 0.54f)
            .v (PID::macroWorld, 0.52f).v (PID::macroWeight, 0.24f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.35f)
            .v (PID::grainSize, 90.0f).v (PID::grainDensity, 18.0f)
            .v (PID::grainPosition, 0.30f).v (PID::grainPitchMode, ch::gFifth)
            .v (PID::grainSpread, 0.68f).v (PID::grainJitter, 0.26f)
            .v (PID::grainDirection, 0.12f).v (PID::grainWindow, ch::wTukey)
            .v (PID::grainMix, 0.34f)
            .v (PID::retroEra, 0.58f).v (PID::retroAge, 0.24f)
            .v (PID::retroDrift, 0.20f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.44f)
            .v (PID::fxFilterCutoff, 8600.0f).v (PID::fxFilterRes, 0.14f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.52f)
            .v (PID::spaceSize, 0.64f).v (PID::spaceDecay, 4.6f)
            .v (PID::spaceFog, 0.50f).v (PID::spaceLight, -0.08f)
            .v (PID::spacePreDelay, 34.0f).v (PID::spaceMix, 0.38f)
            .v (PID::auraSize, 0.60f).v (PID::auraDistance, 0.38f)
            .v (PID::auraFog, 0.48f).v (PID::auraDecay, 0.50f)
            .v (PID::auraLight, 0.08f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.06f)
            .v (PID::patinaNoise, 0.12f).v (PID::patinaWear, 0.20f)
            .v (PID::patinaDrift, 0.26f)
            .v (PID::synthWidth, 1.20f).v (PID::highWidth, 1.26f)
            .v (PID::breathAmount, 0.36f).v (PID::breathSpeed, 0.22f)
            .v (PID::lfo1Shape, ch::lfoSawUp).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d8).v (PID::lfo1Depth, 0.70f)
            .v (PID::lfo2Shape, ch::lfoRandom).v (PID::lfo2Sync, 1.0f)
            .v (PID::lfo2Division, ch::d4).v (PID::lfo2Depth, 0.60f)
            .route (srcLfo1, PID::oscASemi, 0.08f)
            .route (srcLfo2, PID::filterCutoff, 0.18f)
            .route (srcBreath, PID::grainPosition, 0.16f));

        // ---------------------------------------------------------------
        //  GATED PADS: the source is sustained and the pulse engine is the
        //  only thing that makes it rhythmic.  Nothing is plucked here.
        // ---------------------------------------------------------------

        // A four-voice unison saw pad with a one-second attack, chopped on
        // the sixteenth by all four pulse destinations at once.
        add (out, Build ("Turbina", "SEQUENCES", "LUSH",
                         "gated,pad,1/16,pulse",
                         "A slow unison pad with no transient of its own, made rhythmic only by a sixteenth-note pulse into level, brightness, width and wetness.")
            .at (48, 2, 0.74f, 8.0)
            .chain ("FILTER,SPACE,RETRO,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 10.0f).v (PID::voiceVariation, 0.40f)
            .v (PID::driftAmount, 0.30f).v (PID::driftRate, 0.09f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.62f)
            .v (PID::oscAUnison, 4.0f).v (PID::oscADetune, 0.24f)
            .v (PID::oscASpread, 0.70f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tSoft)
            .v (PID::oscBWtPos, 0.36f).v (PID::oscBLevel, 0.40f)
            .v (PID::oscBFine, -7.0f)
            .v (PID::subLevel, 0.20f).v (PID::subHarmonics, 0.16f)
            .v (PID::bodyAmount, 0.34f).v (PID::densityAmount, 0.38f)
            .v (PID::postSaturation, 0.14f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 3400.0f).v (PID::filterResonance, 0.18f)
            .v (PID::filterKeyTrack, 0.35f).v (PID::filterEnvAmount, 0.20f)
            .v (PID::ampAttack, 0.90f).v (PID::ampDecay, 3.0f)
            .v (PID::ampSustain, 0.88f).v (PID::ampRelease, 2.2f)
            .v (PID::ampVelocity, 0.30f)
            .v (PID::env2Attack, 1.6f).v (PID::env2Decay, 3.0f)
            .v (PID::macroMemory, 0.30f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.46f).v (PID::memoryWobble, 0.24f)
            .v (PID::macroCharacter, 0.30f).v (PID::macroMotion, 0.46f)
            .v (PID::macroWorld, 0.56f).v (PID::macroWeight, 0.34f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::pulseOn, 1.0f).v (PID::pulseSource, ch::pClock)
            .v (PID::pulseDivision, ch::p16).v (PID::pulseDepth, 0.85f)
            .v (PID::pulseAttack, 0.0012f).v (PID::pulseRelease, 0.085f)
            .v (PID::pulseSmooth, 0.35f)
            .v (PID::pulseToVolume, 0.95f).v (PID::pulseToFilter, 0.45f)
            .v (PID::pulseToSpace, 0.55f).v (PID::pulseToWidth, 0.45f)
            .v (PID::pulseToMemory, 0.20f)
            .v (PID::retroEra, 0.46f).v (PID::retroAge, 0.22f)
            .v (PID::retroDrift, 0.18f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.42f)
            .v (PID::fxFilterCutoff, 9000.0f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.44f)
            .v (PID::spaceSize, 0.62f).v (PID::spaceDecay, 5.0f)
            .v (PID::spaceFog, 0.48f).v (PID::spaceLight, -0.10f)
            .v (PID::spacePreDelay, 30.0f).v (PID::spaceMix, 0.42f)
            .v (PID::auraSize, 0.62f).v (PID::auraDistance, 0.36f)
            .v (PID::auraFog, 0.44f).v (PID::auraDecay, 0.52f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.06f)
            .v (PID::patinaNoise, 0.10f).v (PID::patinaWear, 0.16f)
            .v (PID::synthWidth, 1.26f).v (PID::highWidth, 1.30f)
            .v (PID::lowMonoFreq, 150.0f)
            .v (PID::breathAmount, 0.34f).v (PID::breathSpeed, 0.14f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d2bar).v (PID::lfo1Depth, 0.50f)
            .v (PID::lfo2Shape, ch::lfoTri).v (PID::lfo2Sync, 1.0f)
            .v (PID::lfo2Division, ch::d4dot).v (PID::lfo2Depth, 0.40f)
            .route (srcLfo1, PID::oscBWtPos, 0.24f)
            .route (srcLfo2, PID::filterCutoff, 0.10f));

        // The half-time version: the same idea on the half note, with a long
        // pulse release so the gate is a slow breath rather than a chop.
        add (out, Build ("Motor al Ralenti", "SEQUENCES", "CINEMATIC",
                         "gated,half-time,1/2,pulse",
                         "A dark sustained bed on the MASS filter opened once per half note by a slow pulse release, with the reverb ducking with it.")
            .at (48, 2, 0.68f, 8.0)
            .chain ("RETRO,FILTER,SPACE,GRAIN,REWIND,CRUSH")
            .v (PID::masterGain, -1.0f)
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.38f)
            .v (PID::driftAmount, 0.34f).v (PID::driftRate, 0.06f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.60f)
            .v (PID::oscAUnison, 3.0f).v (PID::oscADetune, 0.18f)
            .v (PID::oscASpread, 0.48f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.42f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, 9.0f)
            .v (PID::subWave, ch::subTri).v (PID::subLevel, 0.36f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.26f)
            .v (PID::noiseType, ch::nDark).v (PID::noiseLevel, 0.06f)
            .v (PID::bodyAmount, 0.46f).v (PID::densityAmount, 0.34f)
            .v (PID::preFilterDrive, 0.20f).v (PID::postSaturation, 0.18f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 900.0f).v (PID::filterResonance, 0.22f)
            .v (PID::filterDrive, 0.26f).v (PID::filterKeyTrack, 0.30f)
            .v (PID::filterEnvAmount, 0.24f)
            .v (PID::ampAttack, 1.40f).v (PID::ampDecay, 4.0f)
            .v (PID::ampSustain, 0.85f).v (PID::ampRelease, 3.0f)
            .v (PID::ampVelocity, 0.24f)
            .v (PID::env2Attack, 2.4f).v (PID::env2Decay, 5.0f)
            .v (PID::macroMemory, 0.42f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.60f).v (PID::memoryWobble, 0.28f)
            .v (PID::memoryDiffusion, 0.38f)
            .v (PID::macroCharacter, 0.36f).v (PID::macroMotion, 0.34f)
            .v (PID::macroWorld, 0.58f).v (PID::macroWeight, 0.50f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.42f)
            .v (PID::weightCompress, 0.30f)
            .v (PID::pulseOn, 1.0f).v (PID::pulseSource, ch::pClock)
            .v (PID::pulseDivision, ch::p2).v (PID::pulseDepth, 0.72f)
            .v (PID::pulseAttack, 0.020f).v (PID::pulseRelease, 0.75f)
            .v (PID::pulseSmooth, 0.62f)
            .v (PID::pulseToVolume, 0.80f).v (PID::pulseToFilter, 0.55f)
            .v (PID::pulseToSpace, 0.60f).v (PID::pulseToWidth, 0.40f)
            .v (PID::pulseToMemory, 0.30f)
            .v (PID::retroEra, 0.34f).v (PID::retroAge, 0.36f)
            .v (PID::retroDrift, 0.26f).v (PID::retroWear, 0.20f)
            .v (PID::retroTone, -0.34f).v (PID::retroNoise, 0.14f)
            .v (PID::retroMix, 0.66f)
            .v (PID::fxFilterCutoff, 4000.0f).v (PID::fxFilterRes, 0.10f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.52f)
            .v (PID::spaceSize, 0.70f).v (PID::spaceDecay, 7.0f)
            .v (PID::spaceFog, 0.56f).v (PID::spaceLight, -0.44f)
            .v (PID::spacePreDelay, 44.0f).v (PID::spaceMix, 0.40f)
            .v (PID::auraSize, 0.68f).v (PID::auraDistance, 0.44f)
            .v (PID::auraFog, 0.56f).v (PID::auraDecay, 0.60f)
            .v (PID::auraLight, -0.36f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.30f)
            .v (PID::patinaNoise, 0.16f).v (PID::patinaWear, 0.24f)
            .v (PID::patinaDrift, 0.24f)
            .v (PID::synthWidth, 1.10f).v (PID::highWidth, 1.16f)
            .v (PID::lowMonoFreq, 180.0f)
            .v (PID::breathAmount, 0.40f).v (PID::breathSpeed, 0.08f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d1).v (PID::lfo1Depth, 0.50f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Sync, 1.0f)
            .v (PID::lfo2Division, ch::d2bar).v (PID::lfo2Depth, 0.45f)
            .route (srcLfo1, PID::filterCutoff, 0.12f)
            .route (srcLfo2, PID::spaceMix, 0.14f));

        // ---------------------------------------------------------------
        //  GRANULAR SEQUENCES: the grain read position is the sequence.  A
        //  synced LFO on grain_position moves where in the history buffer
        //  each grain is taken from, once per division.
        // ---------------------------------------------------------------

        // Sample-and-hold on the sixteenth jumps the grain read position, and
        // a square on the quarter switches grain length between two values,
        // so the train changes character every beat.
        add (out, Build ("Cinta Transportadora", "SEQUENCES", "BROKEN",
                         "granular,1/16,position,stepped",
                         "A percussive grain train whose read position jumps every sixteenth and whose grain length switches on the quarter.")
            .at (50, 2, 0.76f, 8.0)
            .chain ("CRUSH,GRAIN,FILTER,RETRO,SPACE,REWIND")
            .v (PID::masterGain, -1.5f)
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.30f)
            .v (PID::driftAmount, 0.18f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tDark)
            .v (PID::oscAWtPos, 0.48f).v (PID::oscALevel, 0.66f)
            .v (PID::oscBWave, ch::square).v (PID::oscBLevel, 0.26f)
            .v (PID::oscBPulseWidth, 0.36f).v (PID::oscBOctave, -1.0f)
            .v (PID::subLevel, 0.22f).v (PID::subHarmonics, 0.20f)
            .v (PID::bodyAmount, 0.30f).v (PID::densityAmount, 0.26f)
            .v (PID::preFilterDrive, 0.20f).v (PID::postSaturation, 0.16f)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 1800.0f).v (PID::filterResonance, 0.28f)
            .v (PID::filterKeyTrack, 0.40f)
            .v (PID::ampAttack, 0.05f).v (PID::ampDecay, 1.6f)
            .v (PID::ampSustain, 0.72f).v (PID::ampRelease, 0.60f)
            .v (PID::macroMemory, 0.38f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.56f).v (PID::memoryWobble, 0.30f)
            .v (PID::macroCharacter, 0.48f).v (PID::macroMotion, 0.58f)
            .v (PID::macroWorld, 0.42f).v (PID::macroWeight, 0.32f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.72f)
            .v (PID::grainSize, 55.0f).v (PID::grainDensity, 34.0f)
            .v (PID::grainPosition, 0.35f).v (PID::grainPitchMode, ch::gRoot)
            .v (PID::grainSpread, 0.66f).v (PID::grainJitter, 0.18f)
            .v (PID::grainDirection, 0.10f).v (PID::grainWindow, ch::wPercussive)
            .v (PID::grainFeedback, 0.22f).v (PID::grainMix, 0.62f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.30f)
            .v (PID::crushBits, 11.0f).v (PID::crushRate, 14000.0f)
            .v (PID::crushMix, 0.40f)
            .v (PID::retroEra, 0.44f).v (PID::retroAge, 0.32f)
            .v (PID::retroDrift, 0.18f).v (PID::retroWear, 0.24f)
            .v (PID::retroTone, -0.20f).v (PID::retroNoise, 0.14f)
            .v (PID::retroMix, 0.56f)
            .v (PID::fxFilterCutoff, 6800.0f).v (PID::fxFilterRes, 0.18f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.30f)
            .v (PID::spaceSize, 0.42f).v (PID::spaceDecay, 2.2f)
            .v (PID::spaceFog, 0.38f).v (PID::spaceLight, -0.12f)
            .v (PID::spacePreDelay, 16.0f).v (PID::spaceMix, 0.26f)
            .v (PID::auraSize, 0.40f).v (PID::auraDistance, 0.26f)
            .v (PID::auraFog, 0.36f).v (PID::auraDecay, 0.34f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, -0.04f)
            .v (PID::patinaNoise, 0.16f).v (PID::patinaWear, 0.30f)
            .v (PID::synthWidth, 1.08f).v (PID::highWidth, 1.16f)
            .v (PID::breathAmount, 0.24f)
            .v (PID::lfo1Shape, ch::lfoRandom).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d16).v (PID::lfo1Depth, 0.90f)
            .v (PID::lfo2Shape, ch::lfoSquare).v (PID::lfo2Sync, 1.0f)
            .v (PID::lfo2Division, ch::d4).v (PID::lfo2Depth, 0.60f)
            .route (srcLfo1, PID::grainPosition, 0.45f)
            .route (srcLfo2, PID::grainSize, 0.30f));

        // Three periods that never line up: the read position sweeps across a
        // quarter triplet, the grain count rises and falls on the eighth, and
        // the pulse engine accents the plain quarter underneath both.
        add (out, Build ("Flywheel", "SEQUENCES", "MYSTERIOUS",
                         "granular,triplet,position,pulse",
                         "Grain read position swept on the quarter triplet and grain density moved on the eighth, over a quarter-note pulse into brightness and wetness.")
            .at (53, 2, 0.72f, 8.0)
            .chain ("GRAIN,FILTER,RETRO,SPACE,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.42f)
            .v (PID::driftAmount, 0.28f).v (PID::driftRate, 0.11f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tOrganic)
            .v (PID::oscAWtPos, 0.36f).v (PID::oscALevel, 0.64f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.16f)
            .v (PID::oscASpread, 0.60f)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.30f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, -6.0f)
            .v (PID::noiseType, ch::nTexture).v (PID::noiseLevel, 0.07f)
            .v (PID::subLevel, 0.16f)
            .v (PID::bodyAmount, 0.26f).v (PID::densityAmount, 0.24f)
            .v (PID::postSaturation, 0.12f)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 1100.0f).v (PID::filterResonance, 0.30f)
            .v (PID::filterKeyTrack, 0.28f)
            .v (PID::ampAttack, 0.30f).v (PID::ampDecay, 2.4f)
            .v (PID::ampSustain, 0.76f).v (PID::ampRelease, 1.8f)
            .v (PID::macroMemory, 0.40f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.52f).v (PID::memoryWobble, 0.34f)
            .v (PID::memoryDiffusion, 0.46f).v (PID::memoryAsymmetry, 0.32f)
            .v (PID::macroCharacter, 0.32f).v (PID::macroMotion, 0.62f)
            .v (PID::macroWorld, 0.58f).v (PID::macroWeight, 0.26f)
            .v (PID::macroAlter, 0.22f)
            .v (PID::pulseOn, 1.0f).v (PID::pulseSource, ch::pClock)
            .v (PID::pulseDivision, ch::p4).v (PID::pulseDepth, 0.55f)
            .v (PID::pulseAttack, 0.008f).v (PID::pulseRelease, 0.32f)
            .v (PID::pulseSmooth, 0.50f)
            .v (PID::pulseToVolume, 0.35f).v (PID::pulseToFilter, 0.62f)
            .v (PID::pulseToSpace, 0.58f).v (PID::pulseToWidth, 0.40f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.66f)
            .v (PID::grainSize, 120.0f).v (PID::grainDensity, 20.0f)
            .v (PID::grainPosition, 0.40f).v (PID::grainPitchMode, ch::gFifth)
            .v (PID::grainSpread, 0.74f).v (PID::grainJitter, 0.34f)
            .v (PID::grainDirection, 0.28f).v (PID::grainWindow, ch::wGauss)
            .v (PID::grainFeedback, 0.30f).v (PID::grainMix, 0.58f)
            .v (PID::retroEra, 0.54f).v (PID::retroAge, 0.30f)
            .v (PID::retroDrift, 0.26f).v (PID::retroWear, 0.18f)
            .v (PID::retroTone, -0.14f).v (PID::retroNoise, 0.14f)
            .v (PID::retroMix, 0.52f)
            .v (PID::fxFilterCutoff, 7800.0f).v (PID::fxFilterRes, 0.16f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.54f)
            .v (PID::spaceSize, 0.66f).v (PID::spaceDecay, 5.2f)
            .v (PID::spaceFog, 0.54f).v (PID::spaceLight, -0.18f)
            .v (PID::spacePreDelay, 32.0f).v (PID::spaceMix, 0.36f)
            .v (PID::auraSize, 0.62f).v (PID::auraDistance, 0.40f)
            .v (PID::auraFog, 0.52f).v (PID::auraDecay, 0.54f)
            .v (PID::auraLight, -0.10f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.08f)
            .v (PID::patinaNoise, 0.16f).v (PID::patinaWear, 0.28f)
            .v (PID::patinaDrift, 0.32f)
            .v (PID::synthWidth, 1.22f).v (PID::highWidth, 1.28f)
            .v (PID::breathAmount, 0.44f).v (PID::breathSpeed, 0.18f)
            .v (PID::breathRandom, 0.60f)
            .v (PID::lfo1Shape, ch::lfoSawUp).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d4t).v (PID::lfo1Depth, 0.80f)
            .v (PID::lfo2Shape, ch::lfoTri).v (PID::lfo2Sync, 1.0f)
            .v (PID::lfo2Division, ch::d8).v (PID::lfo2Depth, 0.55f)
            .route (srcLfo1, PID::grainPosition, 0.40f)
            .route (srcLfo2, PID::grainDensity, 0.25f)
            .route (srcBreath, PID::grainJitter, 0.18f));

        // ---------------------------------------------------------------
        //  REWIND SEQUENCES: rewind_sync locks the window to the host, and
        //  the engine re-arms on every crossing of its division, so the
        //  gesture itself is the rhythm.  One preset per transport.
        // ---------------------------------------------------------------

        // REVERSE, re-armed every eighth: the playhead digs backwards out of
        // the present at one and a half times speed and is cut off by the
        // next trigger before it gets far.
        add (out, Build ("Marcha Atras", "SEQUENCES", "BROKEN",
                         "rewind,reverse,1/8,stutter",
                         "Rewind in REVERSE re-armed on every eighth, so each half-beat of the held note is dug backwards out of the history buffer.")
            .at (48, 2, 0.80f, 7.0)
            .chain ("REWIND,FILTER,RETRO,CRUSH,SPACE,GRAIN")
            .v (PID::masterGain, -1.0f)
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.26f)
            .v (PID::driftAmount, 0.16f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.68f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.15f)
            .v (PID::oscASpread, 0.34f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tAsym)
            .v (PID::oscBWtPos, 0.30f).v (PID::oscBLevel, 0.32f)
            .v (PID::oscBOctave, -1.0f)
            .v (PID::subLevel, 0.30f).v (PID::subHarmonics, 0.28f)
            .v (PID::bodyAmount, 0.40f).v (PID::densityAmount, 0.28f)
            .v (PID::preFilterDrive, 0.26f).v (PID::postSaturation, 0.20f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 2000.0f).v (PID::filterResonance, 0.26f)
            .v (PID::filterDrive, 0.28f).v (PID::filterKeyTrack, 0.45f)
            .v (PID::ampAttack, 0.010f).v (PID::ampDecay, 1.2f)
            .v (PID::ampSustain, 0.70f).v (PID::ampRelease, 0.40f)
            .v (PID::macroMemory, 0.36f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.50f).v (PID::memoryWobble, 0.28f)
            .v (PID::macroCharacter, 0.44f).v (PID::macroMotion, 0.42f)
            .v (PID::macroWorld, 0.34f).v (PID::macroWeight, 0.44f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::rewindOn, 1.0f).v (PID::rewindMode, ch::rReverse)
            .v (PID::rewindDivision, ch::rw8).v (PID::rewindSync, 1.0f)
            .v (PID::rewindLength, 0.25f).v (PID::rewindCurve, 0.40f)
            .v (PID::rewindSpeed, 1.6f).v (PID::rewindTail, 0.25f)
            .v (PID::rewindMix, 0.72f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.22f)
            .v (PID::crushBits, 11.0f).v (PID::crushRate, 17000.0f)
            .v (PID::crushMix, 0.32f)
            .v (PID::retroEra, 0.42f).v (PID::retroAge, 0.34f)
            .v (PID::retroDrift, 0.22f).v (PID::retroWear, 0.22f)
            .v (PID::retroTone, -0.22f).v (PID::retroNoise, 0.14f)
            .v (PID::retroMix, 0.60f)
            .v (PID::fxFilterCutoff, 5800.0f).v (PID::fxFilterRes, 0.16f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.32f)
            .v (PID::spaceSize, 0.44f).v (PID::spaceDecay, 2.6f)
            .v (PID::spaceFog, 0.40f).v (PID::spaceLight, -0.24f)
            .v (PID::spacePreDelay, 18.0f).v (PID::spaceMix, 0.26f)
            .v (PID::auraSize, 0.42f).v (PID::auraDistance, 0.28f)
            .v (PID::auraFog, 0.40f).v (PID::auraDecay, 0.36f)
            .v (PID::auraLight, -0.20f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.16f)
            .v (PID::patinaNoise, 0.14f).v (PID::patinaWear, 0.26f)
            .v (PID::synthWidth, 1.02f).v (PID::highWidth, 1.12f)
            .v (PID::lowMonoFreq, 170.0f)
            .v (PID::breathAmount, 0.22f)
            .v (PID::lfo1Shape, ch::lfoSquare).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d8).v (PID::lfo1Depth, 0.55f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Sync, 1.0f)
            .v (PID::lfo2Division, ch::d1).v (PID::lfo2Depth, 0.45f)
            .route (srcLfo1, PID::filterCutoff, 0.12f)
            .route (srcLfo2, PID::rewindSpeed, 0.16f));

        // STOP, re-armed on the half note: the transport decelerates to a
        // standstill once every two beats and is released by the next
        // trigger.  Half-time by construction.
        add (out, Build ("Freno de Mano", "SEQUENCES", "COLD",
                         "rewind,stop,half-time,tape",
                         "Rewind in STOP on the half note, so a sustained note is brought to a standstill and let go again twice a bar.")
            .at (48, 2, 0.72f, 8.0)
            .chain ("RETRO,REWIND,FILTER,SPACE,CRUSH,GRAIN")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.34f)
            .v (PID::driftAmount, 0.24f).v (PID::driftRate, 0.08f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tSoft)
            .v (PID::oscAWtPos, 0.28f).v (PID::oscALevel, 0.66f)
            .v (PID::oscAUnison, 3.0f).v (PID::oscADetune, 0.16f)
            .v (PID::oscASpread, 0.54f)
            .v (PID::oscBWave, ch::saw).v (PID::oscBLevel, 0.30f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, 7.0f)
            .v (PID::subLevel, 0.24f).v (PID::subHarmonics, 0.18f)
            .v (PID::bodyAmount, 0.32f).v (PID::densityAmount, 0.30f)
            .v (PID::postSaturation, 0.14f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 2600.0f).v (PID::filterResonance, 0.20f)
            .v (PID::filterKeyTrack, 0.42f).v (PID::filterEnvAmount, 0.26f)
            .v (PID::ampAttack, 0.50f).v (PID::ampDecay, 3.0f)
            .v (PID::ampSustain, 0.82f).v (PID::ampRelease, 1.8f)
            .v (PID::ampVelocity, 0.30f)
            .v (PID::macroMemory, 0.44f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.58f).v (PID::memoryWobble, 0.36f)
            .v (PID::memoryDiffusion, 0.34f)
            .v (PID::macroCharacter, 0.34f).v (PID::macroMotion, 0.38f)
            .v (PID::macroWorld, 0.50f).v (PID::macroWeight, 0.32f)
            .v (PID::rewindOn, 1.0f).v (PID::rewindMode, ch::rStop)
            .v (PID::rewindDivision, ch::rw2).v (PID::rewindSync, 1.0f)
            .v (PID::rewindLength, 1.00f).v (PID::rewindCurve, 0.30f)
            .v (PID::rewindSpeed, 1.0f).v (PID::rewindTail, 0.45f)
            .v (PID::rewindMix, 0.66f)
            .v (PID::retroEra, 0.36f).v (PID::retroAge, 0.42f)
            .v (PID::retroDrift, 0.40f).v (PID::retroWear, 0.26f)
            .v (PID::retroTone, -0.32f).v (PID::retroNoise, 0.18f)
            .v (PID::retroMix, 0.78f)
            .v (PID::fxFilterCutoff, 6600.0f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.46f)
            .v (PID::spaceSize, 0.62f).v (PID::spaceDecay, 4.4f)
            .v (PID::spaceFog, 0.52f).v (PID::spaceLight, -0.26f)
            .v (PID::spacePreDelay, 36.0f).v (PID::spaceMix, 0.34f)
            .v (PID::auraSize, 0.58f).v (PID::auraDistance, 0.38f)
            .v (PID::auraFog, 0.50f).v (PID::auraDecay, 0.50f)
            .v (PID::auraLight, -0.22f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.24f)
            .v (PID::patinaNoise, 0.18f).v (PID::patinaWear, 0.30f)
            .v (PID::patinaDrift, 0.30f)
            .v (PID::synthWidth, 1.14f).v (PID::highWidth, 1.20f)
            .v (PID::breathAmount, 0.38f).v (PID::breathSpeed, 0.10f)
            .v (PID::lfo1Shape, ch::lfoTri).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d2).v (PID::lfo1Depth, 0.55f)
            .v (PID::lfo2Shape, ch::lfoSine).v (PID::lfo2Sync, 1.0f)
            .v (PID::lfo2Division, ch::d2bar).v (PID::lfo2Depth, 0.40f)
            .route (srcLfo1, PID::filterCutoff, 0.14f)
            .route (srcLfo2, PID::oscAWtPos, 0.20f));

        // DIVE, re-armed on the quarter: the transport falls three octaves
        // across each beat instead of halting, and the next trigger catches
        // it on the way down.
        add (out, Build ("Caida Libre", "SEQUENCES", "HAUNTED",
                         "rewind,dive,1/4,falling",
                         "Rewind in DIVE re-armed every quarter, so the held note falls away once a beat and is caught again by the next trigger.")
            .at (55, 2, 0.70f, 8.0)
            .chain ("FILTER,REWIND,GRAIN,SPACE,RETRO,CRUSH")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.40f)
            .v (PID::driftAmount, 0.26f).v (PID::driftRate, 0.13f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tVocal)
            .v (PID::oscAWtPos, 0.52f).v (PID::oscALevel, 0.62f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.12f)
            .v (PID::oscASpread, 0.62f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.28f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, -8.0f)
            .v (PID::noiseType, ch::nAir).v (PID::noiseLevel, 0.07f)
            .v (PID::subLevel, 0.14f)
            .v (PID::bodyAmount, 0.24f).v (PID::densityAmount, 0.22f)
            .v (PID::postSaturation, 0.12f)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 1300.0f).v (PID::filterResonance, 0.34f)
            .v (PID::filterKeyTrack, 0.32f).v (PID::filterEnvAmount, 0.28f)
            .v (PID::ampAttack, 0.25f).v (PID::ampDecay, 2.6f)
            .v (PID::ampSustain, 0.78f).v (PID::ampRelease, 2.0f)
            .v (PID::macroMemory, 0.46f).v (PID::memoryGen, ch::genIV)
            .v (PID::memoryBandwidth, 0.62f).v (PID::memoryWobble, 0.44f)
            .v (PID::memoryDiffusion, 0.48f).v (PID::memoryAsymmetry, 0.36f)
            .v (PID::macroCharacter, 0.38f).v (PID::macroMotion, 0.60f)
            .v (PID::macroWorld, 0.60f).v (PID::macroWeight, 0.24f)
            .v (PID::rewindOn, 1.0f).v (PID::rewindMode, ch::rDive)
            .v (PID::rewindDivision, ch::rw4).v (PID::rewindSync, 1.0f)
            .v (PID::rewindLength, 0.50f).v (PID::rewindCurve, 0.55f)
            .v (PID::rewindSpeed, 1.0f).v (PID::rewindTail, 0.38f)
            .v (PID::rewindMix, 0.70f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.32f)
            .v (PID::grainSize, 150.0f).v (PID::grainDensity, 12.0f)
            .v (PID::grainPosition, 0.44f).v (PID::grainPitchMode, ch::gOctave)
            .v (PID::grainSpread, 0.70f).v (PID::grainJitter, 0.36f)
            .v (PID::grainDirection, 0.30f).v (PID::grainWindow, ch::wExpo)
            .v (PID::grainFeedback, 0.24f).v (PID::grainMix, 0.36f)
            .v (PID::retroEra, 0.62f).v (PID::retroAge, 0.36f)
            .v (PID::retroDrift, 0.30f).v (PID::retroWear, 0.24f)
            .v (PID::retroTone, -0.18f).v (PID::retroNoise, 0.16f)
            .v (PID::retroMix, 0.58f)
            .v (PID::fxFilterCutoff, 7200.0f).v (PID::fxFilterRes, 0.18f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.58f)
            .v (PID::spaceSize, 0.70f).v (PID::spaceDecay, 6.0f)
            .v (PID::spaceFog, 0.58f).v (PID::spaceLight, -0.20f)
            .v (PID::spacePreDelay, 38.0f).v (PID::spaceMix, 0.40f)
            .v (PID::auraSize, 0.66f).v (PID::auraDistance, 0.44f)
            .v (PID::auraFog, 0.56f).v (PID::auraDecay, 0.58f)
            .v (PID::auraLight, -0.16f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.12f)
            .v (PID::patinaNoise, 0.18f).v (PID::patinaWear, 0.32f)
            .v (PID::patinaDrift, 0.34f)
            .v (PID::synthWidth, 1.24f).v (PID::highWidth, 1.28f)
            .v (PID::breathAmount, 0.46f).v (PID::breathSpeed, 0.16f)
            .v (PID::breathRandom, 0.58f)
            .v (PID::lfo1Shape, ch::lfoSawDown).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d4).v (PID::lfo1Depth, 0.60f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Sync, 1.0f)
            .v (PID::lfo2Division, ch::d1).v (PID::lfo2Depth, 0.50f)
            .route (srcLfo1, PID::filterCutoff, 0.16f)
            .route (srcLfo2, PID::grainPosition, 0.28f));

        // RETURN on the sixteenth with SPEED well above realtime: the tap
        // closes the gap before the window is out and jumps back again,
        // which is the transport's own documented stutter.
        add (out, Build ("Rotonda", "SEQUENCES", "NOSTALGIC",
                         "rewind,return,1/16,stutter",
                         "Rewind in RETURN on the sixteenth at two and a half times speed, which re-jumps inside its own window rather than repeating once.")
            .at (52, 2, 0.78f, 7.0)
            .chain ("CRUSH,REWIND,RETRO,FILTER,GRAIN,SPACE")
            .v (PID::masterGain, -1.5f)
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.28f)
            .v (PID::driftAmount, 0.20f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tOrganic)
            .v (PID::oscAWtPos, 0.34f).v (PID::oscALevel, 0.66f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::square).v (PID::oscBLevel, 0.28f)
            .v (PID::oscBPulseWidth, 0.40f).v (PID::oscBOctave, -1.0f)
            .v (PID::subLevel, 0.26f).v (PID::subHarmonics, 0.22f)
            .v (PID::bodyAmount, 0.34f).v (PID::densityAmount, 0.26f)
            .v (PID::preFilterDrive, 0.18f).v (PID::postSaturation, 0.16f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 2200.0f).v (PID::filterResonance, 0.26f)
            .v (PID::filterKeyTrack, 0.48f).v (PID::filterEnvAmount, 0.30f)
            .v (PID::ampAttack, 0.006f).v (PID::ampDecay, 1.0f)
            .v (PID::ampSustain, 0.66f).v (PID::ampRelease, 0.42f)
            .v (PID::macroMemory, 0.42f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.56f).v (PID::memoryWobble, 0.34f)
            .v (PID::memoryAsymmetry, 0.28f)
            .v (PID::macroCharacter, 0.40f).v (PID::macroMotion, 0.44f)
            .v (PID::macroWorld, 0.40f).v (PID::macroWeight, 0.36f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::rewindOn, 1.0f).v (PID::rewindMode, ch::rReturn)
            .v (PID::rewindDivision, ch::rw16).v (PID::rewindSync, 1.0f)
            .v (PID::rewindLength, 0.12f).v (PID::rewindCurve, 0.30f)
            .v (PID::rewindSpeed, 2.4f).v (PID::rewindTail, 0.20f)
            .v (PID::rewindMix, 0.78f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.26f)
            .v (PID::crushBits, 10.0f).v (PID::crushRate, 15000.0f)
            .v (PID::crushDrive, 0.22f).v (PID::crushMix, 0.38f)
            .v (PID::retroEra, 0.48f).v (PID::retroAge, 0.40f)
            .v (PID::retroDrift, 0.28f).v (PID::retroWear, 0.26f)
            .v (PID::retroTone, -0.26f).v (PID::retroNoise, 0.18f)
            .v (PID::retroMix, 0.70f)
            .v (PID::fxFilterCutoff, 6200.0f).v (PID::fxFilterRes, 0.18f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.36f)
            .v (PID::spaceSize, 0.50f).v (PID::spaceDecay, 3.2f)
            .v (PID::spaceFog, 0.44f).v (PID::spaceLight, -0.18f)
            .v (PID::spacePreDelay, 24.0f).v (PID::spaceMix, 0.30f)
            .v (PID::auraSize, 0.48f).v (PID::auraDistance, 0.30f)
            .v (PID::auraFog, 0.44f).v (PID::auraDecay, 0.42f)
            .v (PID::auraLight, -0.14f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.20f)
            .v (PID::patinaNoise, 0.16f).v (PID::patinaWear, 0.28f)
            .v (PID::patinaDrift, 0.26f)
            .v (PID::synthWidth, 1.08f).v (PID::highWidth, 1.18f)
            .v (PID::lowMonoFreq, 160.0f)
            .v (PID::breathAmount, 0.28f).v (PID::breathSpeed, 0.14f)
            .v (PID::lfo1Shape, ch::lfoSquare).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d4dot).v (PID::lfo1Depth, 0.60f)
            .v (PID::lfo2Shape, ch::lfoTri).v (PID::lfo2Sync, 1.0f)
            .v (PID::lfo2Division, ch::d1).v (PID::lfo2Depth, 0.45f)
            .route (srcLfo1, PID::filterCutoff, 0.15f)
            .route (srcLfo2, PID::rewindMix, 0.18f));

        // ---------------------------------------------------------------
        //  FILTER SEQUENCES: the note never changes.  A synced LFO on the
        //  cutoff is the entire pattern.
        // ---------------------------------------------------------------

        // A square on the sixteenth taking the MASS filter from nearly shut
        // to wide open and back, with the resonance falling on the dotted
        // eighth so no two steps have the same edge.
        add (out, Build ("Camshaft", "SEQUENCES", "AGGRESSIVE",
                         "filter,1/16,square,static",
                         "One static detuned saw note with a square LFO driving the MASS cutoff across most of its range on every sixteenth.")
            .at (48, 1, 0.88f, 7.0)
            .chain ("FILTER,CRUSH,RETRO,REWIND,SPACE,GRAIN")
            .v (PID::masterGain, -2.0f)
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::mono).v (PID::glideTime, 0.0f)
            .v (PID::voiceVariation, 0.18f).v (PID::driftAmount, 0.12f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.74f)
            .v (PID::oscAUnison, 3.0f).v (PID::oscADetune, 0.20f)
            .v (PID::oscASpread, 0.32f)
            .v (PID::oscBWave, ch::saw).v (PID::oscBLevel, 0.44f)
            .v (PID::oscBFine, -12.0f).v (PID::oscBOctave, -1.0f)
            .v (PID::subWave, ch::subSquare).v (PID::subLevel, 0.30f)
            .v (PID::subHarmonics, 0.36f)
            .v (PID::bodyAmount, 0.42f).v (PID::bodyTilt, 0.18f)
            .v (PID::densityAmount, 0.30f)
            .v (PID::preFilterDrive, 0.40f).v (PID::postSaturation, 0.26f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 700.0f).v (PID::filterResonance, 0.52f)
            .v (PID::filterDrive, 0.48f).v (PID::filterKeyTrack, 0.20f)
            .v (PID::filterEnvAmount, 0.20f).v (PID::filterVelAmount, 0.25f)
            .v (PID::ampAttack, 0.006f).v (PID::ampDecay, 3.0f)
            .v (PID::ampSustain, 0.92f).v (PID::ampRelease, 0.50f)
            .v (PID::ampVelocity, 0.35f)
            .v (PID::macroMemory, 0.24f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.40f)
            .v (PID::macroCharacter, 0.58f).v (PID::macroMotion, 0.26f)
            .v (PID::macroWorld, 0.24f).v (PID::macroWeight, 0.46f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.44f)
            .v (PID::weightCompress, 0.34f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.24f)
            .v (PID::crushBits, 12.0f).v (PID::crushRate, 20000.0f)
            .v (PID::crushDrive, 0.28f).v (PID::crushMix, 0.30f)
            .v (PID::retroEra, 0.28f).v (PID::retroAge, 0.24f)
            .v (PID::retroDrift, 0.12f).v (PID::retroWear, 0.14f)
            .v (PID::retroTone, -0.16f).v (PID::retroNoise, 0.08f)
            .v (PID::retroMix, 0.46f)
            .v (PID::fxFilterCutoff, 5000.0f).v (PID::fxFilterRes, 0.20f)
            .v (PID::fxFilterDrive, 0.22f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.22f)
            .v (PID::spaceSize, 0.32f).v (PID::spaceDecay, 1.4f)
            .v (PID::spaceFog, 0.30f).v (PID::spaceLight, -0.20f)
            .v (PID::spacePreDelay, 10.0f).v (PID::spaceMix, 0.18f)
            .v (PID::auraSize, 0.28f).v (PID::auraDistance, 0.16f)
            .v (PID::auraFog, 0.30f).v (PID::auraDecay, 0.24f)
            .v (PID::auraLight, -0.18f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, -0.02f)
            .v (PID::patinaNoise, 0.10f).v (PID::patinaWear, 0.18f)
            .v (PID::synthWidth, 0.92f).v (PID::highWidth, 1.06f)
            .v (PID::lowMonoFreq, 220.0f)
            .v (PID::breathAmount, 0.12f)
            .v (PID::lfo1Shape, ch::lfoSquare).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d16).v (PID::lfo1Depth, 0.95f)
            .v (PID::lfo2Shape, ch::lfoSawDown).v (PID::lfo2Sync, 1.0f)
            .v (PID::lfo2Division, ch::d8dot).v (PID::lfo2Depth, 0.60f)
            .route (srcLfo1, PID::filterCutoff, 0.34f)
            .route (srcLfo2, PID::filterResonance, 0.20f));

        // The quiet filter sequence: a triangle on the eighth sweeps a notch
        // through a sustained chord, and a half-note sine moves the chain
        // filter behind it.  The oscillators never change.
        add (out, Build ("Wiper Blade", "SEQUENCES", "MINIMAL",
                         "filter,1/8,notch,sweep",
                         "A sustained pair of wavetables with a notch swept on the eighth by LFO 1 and the chain filter drifting on the half note.")
            .at (50, 2, 0.70f, 7.0)
            .chain ("RETRO,SPACE,FILTER,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.26f)
            .v (PID::driftAmount, 0.16f).v (PID::driftRate, 0.10f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tSoft)
            .v (PID::oscAWtPos, 0.22f).v (PID::oscALevel, 0.66f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.12f)
            .v (PID::oscASpread, 0.46f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tHollow)
            .v (PID::oscBWtPos, 0.44f).v (PID::oscBLevel, 0.34f)
            .v (PID::oscBFine, 4.0f)
            .v (PID::subLevel, 0.18f).v (PID::subHarmonics, 0.14f)
            .v (PID::bodyAmount, 0.26f).v (PID::densityAmount, 0.24f)
            .v (PID::postSaturation, 0.10f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 4200.0f).v (PID::filterResonance, 0.14f)
            .v (PID::filterKeyTrack, 0.38f).v (PID::filterEnvAmount, 0.18f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Notch)
            .v (PID::filter2Cutoff, 1100.0f).v (PID::filter2Res, 0.45f)
            .v (PID::filter2Mix, 0.65f)
            .v (PID::ampAttack, 0.30f).v (PID::ampDecay, 2.4f)
            .v (PID::ampSustain, 0.85f).v (PID::ampRelease, 1.4f)
            .v (PID::ampVelocity, 0.28f)
            .v (PID::macroMemory, 0.22f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.36f).v (PID::memoryWobble, 0.18f)
            .v (PID::macroCharacter, 0.26f).v (PID::macroMotion, 0.36f)
            .v (PID::macroWorld, 0.46f).v (PID::macroWeight, 0.28f)
            .v (PID::retroEra, 0.52f).v (PID::retroAge, 0.20f)
            .v (PID::retroDrift, 0.16f).v (PID::retroWear, 0.10f)
            .v (PID::retroTone, -0.12f).v (PID::retroNoise, 0.08f)
            .v (PID::retroMix, 0.40f)
            .v (PID::fxFilterCutoff, 7600.0f).v (PID::fxFilterRes, 0.16f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.38f)
            .v (PID::spaceSize, 0.52f).v (PID::spaceDecay, 3.4f)
            .v (PID::spaceFog, 0.38f).v (PID::spaceLight, -0.04f)
            .v (PID::spacePreDelay, 28.0f).v (PID::spaceMix, 0.30f)
            .v (PID::auraSize, 0.50f).v (PID::auraDistance, 0.30f)
            .v (PID::auraFog, 0.36f).v (PID::auraDecay, 0.42f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.08f)
            .v (PID::patinaNoise, 0.08f).v (PID::patinaWear, 0.14f)
            .v (PID::patinaDrift, 0.18f)
            .v (PID::synthWidth, 1.12f).v (PID::highWidth, 1.18f)
            .v (PID::breathAmount, 0.22f).v (PID::breathSpeed, 0.12f)
            .v (PID::lfo1Shape, ch::lfoTri).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d8).v (PID::lfo1Depth, 0.80f)
            .v (PID::lfo2Shape, ch::lfoSine).v (PID::lfo2Sync, 1.0f)
            .v (PID::lfo2Division, ch::d2).v (PID::lfo2Depth, 0.50f)
            .route (srcLfo1, PID::filter2Cutoff, 0.28f)
            .route (srcLfo2, PID::fxFilterCutoff, 0.16f));

        // ---------------------------------------------------------------
        //  THE SLOW END OF THE CATEGORY.
        // ---------------------------------------------------------------

        // Everything here is on the half note or longer: the pulse opens
        // once every two beats, a whole-note LFO walks the grain position
        // and a two-bar LFO moves the cutoff under it.
        add (out, Build ("Tren de Carga", "SEQUENCES", "CINEMATIC",
                         "half-time,1/2,granular,slow",
                         "A half-note pulse and a whole-note grain position over a long infinite-character tail, with nothing in the patch faster than two beats.")
            .at (48, 2, 0.74f, 8.0)
            .chain ("GRAIN,RETRO,FILTER,CRUSH,SPACE,REWIND")
            .v (PID::masterGain, -2.0f)
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.44f)
            .v (PID::driftAmount, 0.32f).v (PID::driftRate, 0.05f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.60f)
            .v (PID::oscAUnison, 4.0f).v (PID::oscADetune, 0.22f)
            .v (PID::oscASpread, 0.58f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tDark)
            .v (PID::oscBWtPos, 0.30f).v (PID::oscBLevel, 0.40f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, 10.0f)
            .v (PID::oscCWave, ch::sine).v (PID::oscCLevel, 0.14f)
            .v (PID::oscCOctave, 1.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.34f)
            .v (PID::subOctave, ch::subMinus2).v (PID::subHarmonics, 0.30f)
            .v (PID::noiseType, ch::nDark).v (PID::noiseLevel, 0.05f)
            .v (PID::bodyAmount, 0.44f).v (PID::densityAmount, 0.36f)
            .v (PID::preFilterDrive, 0.22f).v (PID::postSaturation, 0.18f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1100.0f).v (PID::filterResonance, 0.18f)
            .v (PID::filterDrive, 0.24f).v (PID::filterKeyTrack, 0.30f)
            .v (PID::filterEnvAmount, 0.22f)
            .v (PID::ampAttack, 1.80f).v (PID::ampDecay, 6.0f)
            .v (PID::ampSustain, 0.80f).v (PID::ampRelease, 4.0f)
            .v (PID::ampVelocity, 0.22f)
            .v (PID::env2Attack, 3.0f).v (PID::env2Decay, 6.0f)
            .v (PID::macroMemory, 0.50f).v (PID::memoryGen, ch::genIV)
            .v (PID::memoryBandwidth, 0.66f).v (PID::memoryWobble, 0.30f)
            .v (PID::memoryDiffusion, 0.44f).v (PID::memoryAsymmetry, 0.30f)
            .v (PID::macroCharacter, 0.40f).v (PID::macroMotion, 0.42f)
            .v (PID::macroWorld, 0.70f).v (PID::macroWeight, 0.52f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.46f)
            .v (PID::weightCompress, 0.32f)
            .v (PID::pulseOn, 1.0f).v (PID::pulseSource, ch::pClock)
            .v (PID::pulseDivision, ch::p2).v (PID::pulseDepth, 0.62f)
            .v (PID::pulseAttack, 0.030f).v (PID::pulseRelease, 0.85f)
            .v (PID::pulseSmooth, 0.70f)
            .v (PID::pulseToVolume, 0.70f).v (PID::pulseToFilter, 0.60f)
            .v (PID::pulseToSpace, 0.65f).v (PID::pulseToWidth, 0.35f)
            .v (PID::pulseToMemory, 0.35f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.40f)
            .v (PID::grainSize, 200.0f).v (PID::grainDensity, 9.0f)
            .v (PID::grainPosition, 0.45f).v (PID::grainPitchMode, ch::gOctave)
            .v (PID::grainSpread, 0.64f).v (PID::grainJitter, 0.28f)
            .v (PID::grainDirection, 0.18f).v (PID::grainWindow, ch::wGauss)
            .v (PID::grainFeedback, 0.26f).v (PID::grainMix, 0.38f)
            .v (PID::retroEra, 0.32f).v (PID::retroAge, 0.38f)
            .v (PID::retroDrift, 0.30f).v (PID::retroWear, 0.22f)
            .v (PID::retroTone, -0.36f).v (PID::retroNoise, 0.16f)
            .v (PID::retroMix, 0.68f)
            .v (PID::fxFilterCutoff, 4600.0f).v (PID::fxFilterRes, 0.12f)
            .v (PID::spaceCharacter, ch::sInfinite).v (PID::spaceDistance, 0.60f)
            .v (PID::spaceSize, 0.78f).v (PID::spaceDecay, 9.0f)
            .v (PID::spaceFog, 0.62f).v (PID::spaceLight, -0.40f)
            .v (PID::spacePreDelay, 50.0f).v (PID::spaceMix, 0.44f)
            .v (PID::auraSize, 0.74f).v (PID::auraDistance, 0.48f)
            .v (PID::auraFog, 0.60f).v (PID::auraDecay, 0.66f)
            .v (PID::auraLight, -0.34f)
            .v (PID::shadowOn, 1.0f).v (PID::shadowLength, 0.52f)
            .v (PID::shadowDistance, 0.62f).v (PID::shadowBlur, 0.58f)
            .v (PID::shadowPitch, -12.0f).v (PID::shadowLevel, 0.24f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.30f)
            .v (PID::patinaNoise, 0.16f).v (PID::patinaWear, 0.26f)
            .v (PID::patinaDrift, 0.28f)
            .v (PID::synthWidth, 1.18f).v (PID::highWidth, 1.24f)
            .v (PID::lowMonoFreq, 200.0f)
            .v (PID::breathAmount, 0.42f).v (PID::breathSpeed, 0.06f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d1).v (PID::lfo1Depth, 0.55f)
            .v (PID::lfo2Shape, ch::lfoSine).v (PID::lfo2Sync, 1.0f)
            .v (PID::lfo2Division, ch::d2bar).v (PID::lfo2Depth, 0.45f)
            .route (srcLfo1, PID::grainPosition, 0.30f)
            .route (srcLfo2, PID::filterCutoff, 0.14f)
            .route (srcPulse, PID::grainDensity, -0.18f));
    }
}
