#include "PresetBuilder.h"
#include "Builders.h"

namespace nacar::presets::detail
{
    // ===============================================================
    //  SEQUENCES
    //
    //  NACAR has no arpeggiator and no step sequencer, so "sequence" here
    //  means a patch whose movement is locked to the host: a tempo-synced
    //  LFO into the matrix, Pulse on the grid, or Rewind re-arming on a
    //  division.  Hold one note and the bar does the rest.
    // ===============================================================
    void buildSequences (std::vector<FactoryPreset>& out)
    {
        // Pulse on the sixteenth into volume, brightness, wetness and
        // width at once - section 83's four-destination duck - with a
        // synced square LFO gating the cutoff against it.
        add (out, Build ("Midnight Pulse", "SEQUENCES", "DARK",
                         "pulse,1/16,sidechain,gate",
                         "One held note turned into a bar by the pulse engine alone.")
            .at (40, 2, 0.86f, 6.0)
            .chain ("FILTER,RETRO,CRUSH,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.22f)
            .v (PID::driftAmount, 0.16f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.72f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.12f)
            .v (PID::oscASpread, 0.35f)
            .v (PID::oscBWave, ch::square).v (PID::oscBLevel, 0.34f)
            .v (PID::oscBPulseWidth, 0.30f).v (PID::oscBOctave, -1.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.40f)
            .v (PID::subHarmonics, 0.30f)
            .v (PID::bodyAmount, 0.52f).v (PID::densityAmount, 0.34f)
            .v (PID::preFilterDrive, 0.32f).v (PID::postSaturation, 0.24f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1400.0f).v (PID::filterResonance, 0.34f)
            .v (PID::filterDrive, 0.34f).v (PID::filterKeyTrack, 0.40f)
            .v (PID::filterEnvAmount, 0.30f).v (PID::filterVelAmount, 0.35f)
            .v (PID::ampAttack, 0.006f).v (PID::ampDecay, 1.0f)
            .v (PID::ampSustain, 0.86f).v (PID::ampRelease, 0.30f)
            .v (PID::macroMemory, 0.32f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.52f).v (PID::memoryWobble, 0.22f)
            .v (PID::memoryAsymmetry, 0.20f)
            .v (PID::macroCharacter, 0.50f).v (PID::macroMotion, 0.30f)
            .v (PID::macroWorld, 0.34f).v (PID::macroWeight, 0.48f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.48f)
            .v (PID::weightCompress, 0.38f)
            .v (PID::pulseOn, 1.0f).v (PID::pulseSource, ch::pClock)
            .v (PID::pulseDivision, ch::p16).v (PID::pulseDepth, 0.72f)
            .v (PID::pulseAttack, 0.0015f).v (PID::pulseRelease, 0.16f)
            .v (PID::pulseSmooth, 0.28f)
            .v (PID::pulseToVolume, 0.88f).v (PID::pulseToFilter, 0.55f)
            .v (PID::pulseToSpace, 0.50f).v (PID::pulseToWidth, 0.35f)
            .v (PID::pulseToMemory, 0.25f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.22f)
            .v (PID::crushBits, 12.0f).v (PID::crushRate, 22000.0f)
            .v (PID::crushMix, 0.32f)
            .v (PID::retroEra, 0.42f).v (PID::retroAge, 0.34f)
            .v (PID::retroDrift, 0.16f).v (PID::retroWear, 0.18f)
            .v (PID::retroTone, -0.24f).v (PID::retroNoise, 0.12f)
            .v (PID::retroMix, 0.58f)
            .v (PID::fxFilterCutoff, 5200.0f).v (PID::fxFilterRes, 0.18f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.34f)
            .v (PID::spaceSize, 0.48f).v (PID::spaceDecay, 3.0f)
            .v (PID::spaceFog, 0.44f).v (PID::spaceLight, -0.36f)
            .v (PID::spacePreDelay, 22.0f).v (PID::spaceMix, 0.30f)
            .v (PID::auraSize, 0.42f).v (PID::auraDistance, 0.28f)
            .v (PID::auraFog, 0.42f).v (PID::auraDecay, 0.36f)
            .v (PID::auraLight, -0.30f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.20f)
            .v (PID::patinaNoise, 0.14f).v (PID::patinaWear, 0.26f)
            .v (PID::synthWidth, 1.00f).v (PID::highWidth, 1.10f)
            .v (PID::lowMonoFreq, 200.0f)
            .v (PID::breathAmount, 0.24f)
            .v (PID::lfo1Shape, ch::lfoSquare).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d16).v (PID::lfo1Depth, 0.60f)
            .v (PID::lfo2Shape, ch::lfoTri).v (PID::lfo2Sync, 1.0f)
            .v (PID::lfo2Division, ch::d1).v (PID::lfo2Depth, 0.50f)
            .route (srcLfo1, PID::filterCutoff, 0.12f)
            .route (srcLfo2, PID::filterResonance, 0.14f));

        // The plainest tempo patch: a synced triangle LFO on the eighth
        // opening a short pluck, and almost nothing else moving.
        add (out, Build ("Hourglass", "SEQUENCES", "MINIMAL",
                         "1/8,synced,pluck,clean",
                         "A short note and a filter that opens on the eighth, and that is all.")
            .at (57, 2, 0.74f, 6.0)
            .chain ("FILTER,SPACE,RETRO,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.24f)
            .v (PID::driftAmount, 0.10f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tSoft)
            .v (PID::oscAWtPos, 0.34f).v (PID::oscALevel, 0.70f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.26f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, 3.0f)
            .v (PID::subLevel, 0.20f).v (PID::subHarmonics, 0.16f)
            .v (PID::bodyAmount, 0.24f).v (PID::densityAmount, 0.18f)
            .v (PID::postSaturation, 0.10f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 2200.0f).v (PID::filterResonance, 0.28f)
            .v (PID::filterKeyTrack, 0.60f).v (PID::filterEnvAmount, 0.40f)
            .v (PID::filterVelAmount, 0.45f)
            .v (PID::ampAttack, 0.001f).v (PID::ampDecay, 0.70f)
            .v (PID::ampSustain, 0.10f).v (PID::ampRelease, 0.45f)
            .v (PID::ampVelocity, 0.60f)
            .v (PID::env1Decay, 0.16f).v (PID::env1Sustain, 0.0f)
            .v (PID::macroMemory, 0.20f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.30f).v (PID::memoryWobble, 0.16f)
            .v (PID::macroCharacter, 0.24f).v (PID::macroMotion, 0.28f)
            .v (PID::macroWorld, 0.44f).v (PID::macroWeight, 0.28f)
            .v (PID::retroEra, 0.62f).v (PID::retroAge, 0.18f)
            .v (PID::retroDrift, 0.14f).v (PID::retroWear, 0.08f)
            .v (PID::retroNoise, 0.08f).v (PID::retroMix, 0.40f)
            .v (PID::fxFilterCutoff, 9000.0f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.34f)
            .v (PID::spaceSize, 0.48f).v (PID::spaceDecay, 2.6f)
            .v (PID::spaceFog, 0.32f).v (PID::spaceLight, 0.06f)
            .v (PID::spacePreDelay, 24.0f).v (PID::spaceMix, 0.28f)
            .v (PID::auraSize, 0.44f).v (PID::auraDistance, 0.26f)
            .v (PID::auraFog, 0.30f).v (PID::auraDecay, 0.36f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaNoise, 0.08f)
            .v (PID::patinaWear, 0.14f).v (PID::patinaDrift, 0.16f)
            .v (PID::synthWidth, 1.10f).v (PID::highWidth, 1.15f)
            .v (PID::breathAmount, 0.26f).v (PID::breathSpeed, 0.18f)
            .v (PID::lfo1Shape, ch::lfoTri).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d8).v (PID::lfo1Depth, 0.70f)
            .v (PID::lfo2Shape, ch::lfoSine).v (PID::lfo2Sync, 1.0f)
            .v (PID::lfo2Division, ch::d2bar).v (PID::lfo2Depth, 0.45f)
            .route (srcLfo1, PID::filterCutoff, 0.16f)
            .route (srcLfo2, PID::oscAWtPos, 0.22f));

        // Rewind in RETURN mode re-arms on the bar and lands back exactly
        // on realtime, with a slow grain cloud reading the same history.
        add (out, Build ("Tape Loop", "SEQUENCES", "NOSTALGIC",
                         "rewind,1 bar,loop,tape",
                         "A one-bar loop that jumps back on the barline and catches up by the end of it.")
            .at (48, 3, 0.72f, 8.0)
            .chain ("RETRO,REWIND,GRAIN,FILTER,SPACE,CRUSH")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.40f)
            .v (PID::driftAmount, 0.28f).v (PID::driftRate, 0.10f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.66f)
            .v (PID::oscAUnison, 3.0f).v (PID::oscADetune, 0.18f)
            .v (PID::oscASpread, 0.62f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tOrganic)
            .v (PID::oscBWtPos, 0.40f).v (PID::oscBLevel, 0.36f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, 8.0f)
            .v (PID::subLevel, 0.22f).v (PID::subHarmonics, 0.18f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.10f)
            .v (PID::bodyAmount, 0.38f).v (PID::densityAmount, 0.30f)
            .v (PID::preFilterDrive, 0.18f).v (PID::postSaturation, 0.18f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 2800.0f).v (PID::filterResonance, 0.16f)
            .v (PID::filterKeyTrack, 0.50f).v (PID::filterEnvAmount, 0.34f)
            .v (PID::ampAttack, 0.15f).v (PID::ampDecay, 2.2f)
            .v (PID::ampSustain, 0.70f).v (PID::ampRelease, 1.6f)
            .v (PID::ampVelocity, 0.45f)
            .v (PID::macroMemory, 0.50f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.62f).v (PID::memoryWobble, 0.44f)
            .v (PID::memoryDiffusion, 0.40f).v (PID::memoryAsymmetry, 0.34f)
            .v (PID::macroCharacter, 0.44f).v (PID::macroMotion, 0.52f)
            .v (PID::macroWorld, 0.48f).v (PID::macroWeight, 0.34f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::rewindOn, 1.0f).v (PID::rewindMode, ch::rReturn)
            .v (PID::rewindDivision, ch::rw1bar).v (PID::rewindSync, 1.0f)
            .v (PID::rewindCurve, 0.35f).v (PID::rewindSpeed, 1.0f)
            .v (PID::rewindTail, 0.30f).v (PID::rewindMix, 0.55f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.28f)
            .v (PID::grainSize, 130.0f).v (PID::grainDensity, 16.0f)
            .v (PID::grainPosition, 0.50f).v (PID::grainPitchMode, ch::gOctave)
            .v (PID::grainSpread, 0.62f).v (PID::grainJitter, 0.30f)
            .v (PID::grainDirection, 0.20f).v (PID::grainWindow, ch::wHann)
            .v (PID::grainFeedback, 0.20f).v (PID::grainMix, 0.34f)
            .v (PID::retroEra, 0.38f).v (PID::retroAge, 0.48f)
            .v (PID::retroDrift, 0.44f).v (PID::retroWear, 0.28f)
            .v (PID::retroTone, -0.28f).v (PID::retroNoise, 0.20f)
            .v (PID::retroMix, 0.84f)
            .v (PID::fxFilterCutoff, 6000.0f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.44f)
            .v (PID::spaceSize, 0.60f).v (PID::spaceDecay, 4.0f)
            .v (PID::spaceFog, 0.52f).v (PID::spaceLight, -0.22f)
            .v (PID::spacePreDelay, 30.0f).v (PID::spaceMix, 0.32f)
            .v (PID::auraSize, 0.58f).v (PID::auraDistance, 0.36f)
            .v (PID::auraFog, 0.54f).v (PID::auraDecay, 0.52f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.22f)
            .v (PID::patinaNoise, 0.20f).v (PID::patinaWear, 0.34f)
            .v (PID::patinaDrift, 0.30f)
            .v (PID::synthWidth, 1.15f).v (PID::highWidth, 1.20f)
            .v (PID::breathAmount, 0.48f).v (PID::breathSpeed, 0.12f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d1).v (PID::lfo1Depth, 0.55f)
            .route (srcLfo1, PID::grainPosition, 0.30f)
            .route (srcBreath, PID::retroDrift, 0.20f));

        // A synced saw-down LFO on the sixteenth into cutoff, with grain
        // pitches drawn from the SCALE tier: the notes come from the cloud.
        add (out, Build ("Ghost Arpeggio", "SEQUENCES", "HAUNTED",
                         "1/16,granular,scale,falling",
                         "An arpeggio nobody played, assembled out of one held chord.")
            .at (50, 3, 0.72f, 8.0)
            .chain ("FILTER,GRAIN,RETRO,SPACE,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.44f)
            .v (PID::driftAmount, 0.26f).v (PID::driftRate, 0.14f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tHollow)
            .v (PID::oscAWtPos, 0.44f).v (PID::oscALevel, 0.68f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.14f)
            .v (PID::oscASpread, 0.58f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.30f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, -9.0f)
            .v (PID::subLevel, 0.14f)
            .v (PID::noiseType, ch::nTexture).v (PID::noiseLevel, 0.08f)
            .v (PID::bodyAmount, 0.24f).v (PID::densityAmount, 0.22f)
            .v (PID::preFilterDrive, 0.14f).v (PID::postSaturation, 0.14f)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 2400.0f).v (PID::filterResonance, 0.36f)
            .v (PID::filterKeyTrack, 0.45f).v (PID::filterEnvAmount, 0.30f)
            .v (PID::ampAttack, 0.35f).v (PID::ampDecay, 2.6f)
            .v (PID::ampSustain, 0.74f).v (PID::ampRelease, 2.4f)
            .v (PID::ampVelocity, 0.40f)
            .v (PID::macroMemory, 0.46f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.54f).v (PID::memoryWobble, 0.40f)
            .v (PID::memoryDiffusion, 0.52f).v (PID::memoryAsymmetry, 0.38f)
            .v (PID::macroCharacter, 0.36f).v (PID::macroMotion, 0.66f)
            .v (PID::macroWorld, 0.56f).v (PID::macroWeight, 0.26f)
            .v (PID::macroAlter, 0.28f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.66f)
            .v (PID::grainSize, 70.0f).v (PID::grainDensity, 30.0f)
            .v (PID::grainPosition, 0.28f).v (PID::grainPitchMode, ch::gScale)
            .v (PID::grainSpread, 0.78f).v (PID::grainJitter, 0.44f)
            .v (PID::grainDirection, 0.24f).v (PID::grainWindow, ch::wHann)
            .v (PID::grainFeedback, 0.30f).v (PID::grainMix, 0.56f)
            .v (PID::harmonyMode, 1.0f).v (PID::scaleType, 2.0f)
            .v (PID::retroEra, 0.60f).v (PID::retroAge, 0.38f)
            .v (PID::retroDrift, 0.32f).v (PID::retroWear, 0.26f)
            .v (PID::retroTone, -0.16f).v (PID::retroNoise, 0.16f)
            .v (PID::retroMix, 0.64f)
            .v (PID::fxFilterCutoff, 7400.0f).v (PID::fxFilterRes, 0.20f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.56f)
            .v (PID::spaceSize, 0.68f).v (PID::spaceDecay, 5.5f)
            .v (PID::spaceFog, 0.56f).v (PID::spaceLight, -0.16f)
            .v (PID::spacePreDelay, 26.0f).v (PID::spaceMix, 0.40f)
            .v (PID::auraSize, 0.64f).v (PID::auraDistance, 0.42f)
            .v (PID::auraFog, 0.58f).v (PID::auraDecay, 0.58f)
            .v (PID::auraLight, -0.14f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.10f)
            .v (PID::patinaNoise, 0.18f).v (PID::patinaWear, 0.34f)
            .v (PID::patinaDrift, 0.38f)
            .v (PID::synthWidth, 1.25f).v (PID::highWidth, 1.30f)
            .v (PID::breathAmount, 0.56f).v (PID::breathSpeed, 0.24f)
            .v (PID::breathRandom, 0.70f)
            .v (PID::lfo1Shape, ch::lfoSawDown).v (PID::lfo1Sync, 1.0f)
            .v (PID::lfo1Division, ch::d16).v (PID::lfo1Depth, 0.65f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Sync, 1.0f)
            .v (PID::lfo2Division, ch::d2).v (PID::lfo2Depth, 0.55f)
            .route (srcLfo1, PID::filterCutoff, 0.18f)
            .route (srcLfo2, PID::grainPosition, 0.34f)
            .route (srcBreath, PID::grainSize, 0.20f));
    }
}
