#include "PresetBuilder.h"
#include "Builders.h"

namespace nacar::presets::detail
{
    // ===============================================================
    //  SUB
    // ===============================================================
    void buildSub (std::vector<FactoryPreset>& out)
    {
        // The plainest thing in the library, and it is supposed to be:
        // one sine, one sub, Weight in SUB mode generating the harmonics
        // that let a phone speaker infer what it cannot reproduce.
        add (out, Build ("Foundation", "SUB", "MINIMAL",
                         "sine,clean,mono,harmonics",
                         "One sine and the harmonics that make it audible on a phone.")
            .at (29, 1, 0.92f, 4.0)
            .chain ("FILTER,SPACE,RETRO,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.02f)
            .v (PID::voiceVariation, 0.05f).v (PID::driftAmount, 0.04f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.82f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBLevel, 0.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.60f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.34f)
            .v (PID::bodyAmount, 0.30f).v (PID::densityAmount, 0.10f)
            .v (PID::preFilterDrive, 0.10f).v (PID::postSaturation, 0.08f)
            .v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 400.0f).v (PID::filterResonance, 0.06f)
            .v (PID::filterDrive, 0.14f).v (PID::filterKeyTrack, 0.20f)
            .v (PID::filterEnvAmount, 0.12f).v (PID::filterVelAmount, 0.20f)
            .v (PID::ampAttack, 0.008f).v (PID::ampDecay, 1.4f)
            .v (PID::ampSustain, 0.92f).v (PID::ampRelease, 0.20f)
            .v (PID::ampVelocity, 0.35f)
            .v (PID::macroMemory, 0.10f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.16f).v (PID::memoryWobble, 0.06f)
            .v (PID::memoryAsymmetry, 0.0f)
            .v (PID::macroCharacter, 0.16f).v (PID::macroMotion, 0.10f)
            .v (PID::macroWorld, 0.08f).v (PID::macroWeight, 0.64f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.62f)
            .v (PID::weightCompress, 0.42f)
            .v (PID::retroEra, 0.34f).v (PID::retroAge, 0.14f)
            .v (PID::retroDrift, 0.04f).v (PID::retroWear, 0.02f)
            .v (PID::retroTone, -0.20f).v (PID::retroNoise, 0.04f)
            .v (PID::retroMix, 0.25f)
            .v (PID::fxFilterCutoff, 1400.0f)
            .v (PID::spaceOn, 0.0f)
            .v (PID::auraSize, 0.14f).v (PID::auraDistance, 0.06f)
            .v (PID::auraFog, 0.16f).v (PID::auraDecay, 0.12f)
            .v (PID::auraLight, -0.30f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.10f)
            .v (PID::patinaNoise, 0.04f).v (PID::patinaWear, 0.08f)
            .v (PID::patinaDrift, 0.06f)
            .v (PID::synthWidth, 0.40f).v (PID::highWidth, 0.60f)
            .v (PID::lowMonoFreq, 320.0f)
            .v (PID::breathAmount, 0.10f).v (PID::breathSpeed, 0.08f)
            .route (srcBreath, PID::filterCutoff, 0.03f));

        // The same band from the other direction: a soft square sub with
        // Memory on it, so the bottom has a history rather than a spec.
        add (out, Build ("Tectonic Plate", "SUB", "DARK",
                         "deep,slow,memory,pressure",
                         "A sub with three generations of tape under it, moving like geology.")
            .at (26, 1, 0.95f, 6.0)
            .chain ("RETRO,FILTER,SPACE,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.14f)
            .v (PID::voiceVariation, 0.12f).v (PID::driftAmount, 0.16f)
            .v (PID::driftRate, 0.04f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.76f)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.30f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, -4.0f)
            .v (PID::subWave, ch::subSquare).v (PID::subLevel, 0.62f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.48f)
            .v (PID::bodyAmount, 0.74f).v (PID::bodyTilt, -0.30f)
            .v (PID::densityAmount, 0.40f)
            .v (PID::preFilterDrive, 0.26f).v (PID::postSaturation, 0.20f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 300.0f).v (PID::filterResonance, 0.16f)
            .v (PID::filterDrive, 0.34f).v (PID::filterKeyTrack, 0.15f)
            .v (PID::filterEnvAmount, 0.20f).v (PID::filterVelAmount, 0.20f)
            .v (PID::ampAttack, 0.05f).v (PID::ampDecay, 3.0f)
            .v (PID::ampSustain, 0.90f).v (PID::ampRelease, 1.1f)
            .v (PID::ampVelocity, 0.30f)
            .v (PID::macroMemory, 0.56f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.74f).v (PID::memoryWobble, 0.24f)
            .v (PID::memoryDiffusion, 0.30f).v (PID::memoryAsymmetry, 0.06f)
            .v (PID::macroCharacter, 0.48f).v (PID::macroMotion, 0.22f)
            .v (PID::macroWorld, 0.24f).v (PID::macroWeight, 0.70f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.56f)
            .v (PID::weightCompress, 0.46f)
            .v (PID::retroEra, 0.10f).v (PID::retroAge, 0.52f)
            .v (PID::retroDrift, 0.16f).v (PID::retroWear, 0.14f)
            .v (PID::retroTone, -0.46f).v (PID::retroNoise, 0.14f)
            .v (PID::retroMix, 0.70f)
            .v (PID::fxFilterCutoff, 1100.0f).v (PID::fxFilterDrive, 0.14f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.22f)
            .v (PID::spaceSize, 0.34f).v (PID::spaceDecay, 2.4f)
            .v (PID::spaceFog, 0.44f).v (PID::spaceLight, -0.60f)
            .v (PID::spaceMix, 0.10f)
            .v (PID::auraSize, 0.30f).v (PID::auraDistance, 0.14f)
            .v (PID::auraFog, 0.44f).v (PID::auraDecay, 0.30f)
            .v (PID::auraLight, -0.50f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.40f)
            .v (PID::patinaNoise, 0.14f).v (PID::patinaWear, 0.34f)
            .v (PID::patinaDrift, 0.20f)
            .v (PID::synthWidth, 0.45f).v (PID::highWidth, 0.70f)
            .v (PID::lowMonoFreq, 300.0f)
            .v (PID::breathAmount, 0.30f).v (PID::breathSpeed, 0.05f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.06f)
            .v (PID::lfo1Depth, 0.50f)
            .route (srcLfo1, PID::filterCutoff, 0.05f)
            .route (srcBreath, PID::memoryBandwidth, 0.12f));

        // A finger-noise attack and a body-heavy sub: the one in the group
        // that has a transient at all.
        add (out, Build ("Upright Sub", "SUB", "WARM",
                         "acoustic,finger,round,short",
                         "A sub with a finger on the string at the start of every note.")
            .at (31, 1, 0.88f, 4.0)
            .chain ("FILTER,RETRO,SPACE,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::voiceVariation, 0.18f).v (PID::driftAmount, 0.18f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.80f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.22f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, 5.0f)
            .v (PID::subWave, ch::subTri).v (PID::subLevel, 0.56f)
            .v (PID::subHarmonics, 0.40f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.20f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.68f).v (PID::bodyTilt, 0.24f)
            .v (PID::densityAmount, 0.34f)
            .v (PID::preFilterDrive, 0.18f).v (PID::postSaturation, 0.18f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 520.0f).v (PID::filterResonance, 0.10f)
            .v (PID::filterDrive, 0.20f).v (PID::filterKeyTrack, 0.30f)
            .v (PID::filterEnvAmount, 0.48f).v (PID::filterVelAmount, 0.55f)
            .v (PID::ampAttack, 0.003f).v (PID::ampDecay, 1.1f)
            .v (PID::ampSustain, 0.48f).v (PID::ampRelease, 0.26f)
            .v (PID::ampVelocity, 0.66f)
            .v (PID::env1Attack, 0.0008f).v (PID::env1Decay, 0.14f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.10f)
            .v (PID::macroMemory, 0.32f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.56f).v (PID::memoryWobble, 0.20f)
            .v (PID::memoryAsymmetry, 0.06f)
            .v (PID::macroCharacter, 0.38f).v (PID::macroMotion, 0.24f)
            .v (PID::macroWorld, 0.22f).v (PID::macroWeight, 0.58f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.50f)
            .v (PID::weightCompress, 0.44f)
            .v (PID::retroEra, 0.22f).v (PID::retroAge, 0.38f)
            .v (PID::retroDrift, 0.18f).v (PID::retroWear, 0.12f)
            .v (PID::retroTone, -0.34f).v (PID::retroNoise, 0.12f)
            .v (PID::retroMix, 0.62f)
            .v (PID::fxFilterCutoff, 2200.0f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.20f)
            .v (PID::spaceSize, 0.24f).v (PID::spaceDecay, 0.9f)
            .v (PID::spaceFog, 0.24f).v (PID::spaceLight, -0.42f)
            .v (PID::spaceMix, 0.12f)
            .v (PID::auraSize, 0.20f).v (PID::auraDistance, 0.12f)
            .v (PID::auraFog, 0.30f).v (PID::auraDecay, 0.18f)
            .v (PID::auraLight, -0.36f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.26f)
            .v (PID::patinaNoise, 0.12f).v (PID::patinaWear, 0.22f)
            .v (PID::synthWidth, 0.55f).v (PID::highWidth, 0.80f)
            .v (PID::lowMonoFreq, 280.0f)
            .v (PID::breathAmount, 0.24f).v (PID::breathSpeed, 0.12f)
            .route (srcBreath, PID::bodyAmount, 0.10f)
            .route (srcTouch, PID::filterCutoff, 0.12f));
    }
}
