#include "PresetBuilder.h"
#include "Builders.h"

namespace nacar::presets::detail
{
    // ===============================================================
    //  SUB
    // ===============================================================
    void buildSub (std::vector<FactoryPreset>& out)
    {
        // The plainest thing in the library, and it is supposed to be:
        // one sine, one sub, Weight in SUB mode generating the harmonics
        // that let a phone speaker infer what it cannot reproduce.
        add (out, Build ("Foundation", "SUB", "MINIMAL",
                         "sine,clean,mono,harmonics",
                         "One sine and the harmonics that make it audible on a phone.")
            .at (29, 1, 0.92f, 4.0)
            .chain ("FILTER,SPACE,RETRO,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.02f)
            .v (PID::voiceVariation, 0.05f).v (PID::driftAmount, 0.04f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.82f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBLevel, 0.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.60f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.34f)
            .v (PID::bodyAmount, 0.30f).v (PID::densityAmount, 0.10f)
            .v (PID::preFilterDrive, 0.10f).v (PID::postSaturation, 0.08f)
            .v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 400.0f).v (PID::filterResonance, 0.06f)
            .v (PID::filterDrive, 0.14f).v (PID::filterKeyTrack, 0.20f)
            .v (PID::filterEnvAmount, 0.12f).v (PID::filterVelAmount, 0.20f)
            .v (PID::ampAttack, 0.008f).v (PID::ampDecay, 1.4f)
            .v (PID::ampSustain, 0.92f).v (PID::ampRelease, 0.20f)
            .v (PID::ampVelocity, 0.35f)
            .v (PID::macroMemory, 0.10f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.16f).v (PID::memoryWobble, 0.06f)
            .v (PID::memoryAsymmetry, 0.0f)
            .v (PID::macroCharacter, 0.16f).v (PID::macroMotion, 0.10f)
            .v (PID::macroWorld, 0.08f).v (PID::macroWeight, 0.64f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.62f)
            .v (PID::weightCompress, 0.42f)
            .v (PID::retroEra, 0.34f).v (PID::retroAge, 0.14f)
            .v (PID::retroDrift, 0.04f).v (PID::retroWear, 0.02f)
            .v (PID::retroTone, -0.20f).v (PID::retroNoise, 0.04f)
            .v (PID::retroMix, 0.25f)
            .v (PID::fxFilterCutoff, 1400.0f)
            .v (PID::spaceOn, 0.0f)
            .v (PID::auraSize, 0.14f).v (PID::auraDistance, 0.06f)
            .v (PID::auraFog, 0.16f).v (PID::auraDecay, 0.12f)
            .v (PID::auraLight, -0.30f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.10f)
            .v (PID::patinaNoise, 0.04f).v (PID::patinaWear, 0.08f)
            .v (PID::patinaDrift, 0.06f)
            .v (PID::synthWidth, 0.40f).v (PID::highWidth, 0.60f)
            .v (PID::lowMonoFreq, 320.0f)
            .v (PID::breathAmount, 0.10f).v (PID::breathSpeed, 0.08f)
            .route (srcBreath, PID::filterCutoff, 0.03f));

        // The same band from the other direction: a soft square sub with
        // Memory on it, so the bottom has a history rather than a spec.
        add (out, Build ("Tectonic Plate", "SUB", "DARK",
                         "deep,slow,memory,pressure",
                         "A sub with three generations of tape under it, moving like geology.")
            .at (26, 1, 0.95f, 6.0)
            .chain ("RETRO,FILTER,SPACE,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.14f)
            .v (PID::voiceVariation, 0.12f).v (PID::driftAmount, 0.16f)
            .v (PID::driftRate, 0.04f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.76f)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.30f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, -4.0f)
            .v (PID::subWave, ch::subSquare).v (PID::subLevel, 0.62f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.48f)
            .v (PID::bodyAmount, 0.74f).v (PID::bodyTilt, -0.30f)
            .v (PID::densityAmount, 0.40f)
            .v (PID::preFilterDrive, 0.26f).v (PID::postSaturation, 0.20f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 300.0f).v (PID::filterResonance, 0.16f)
            .v (PID::filterDrive, 0.34f).v (PID::filterKeyTrack, 0.15f)
            .v (PID::filterEnvAmount, 0.20f).v (PID::filterVelAmount, 0.20f)
            .v (PID::ampAttack, 0.05f).v (PID::ampDecay, 3.0f)
            .v (PID::ampSustain, 0.90f).v (PID::ampRelease, 1.1f)
            .v (PID::ampVelocity, 0.30f)
            .v (PID::macroMemory, 0.56f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.74f).v (PID::memoryWobble, 0.24f)
            .v (PID::memoryDiffusion, 0.30f).v (PID::memoryAsymmetry, 0.06f)
            .v (PID::macroCharacter, 0.48f).v (PID::macroMotion, 0.22f)
            .v (PID::macroWorld, 0.24f).v (PID::macroWeight, 0.70f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.56f)
            .v (PID::weightCompress, 0.46f)
            .v (PID::retroEra, 0.10f).v (PID::retroAge, 0.52f)
            .v (PID::retroDrift, 0.16f).v (PID::retroWear, 0.14f)
            .v (PID::retroTone, -0.46f).v (PID::retroNoise, 0.14f)
            .v (PID::retroMix, 0.70f)
            .v (PID::fxFilterCutoff, 1100.0f).v (PID::fxFilterDrive, 0.14f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.22f)
            .v (PID::spaceSize, 0.34f).v (PID::spaceDecay, 2.4f)
            .v (PID::spaceFog, 0.44f).v (PID::spaceLight, -0.60f)
            .v (PID::spaceMix, 0.10f)
            .v (PID::auraSize, 0.30f).v (PID::auraDistance, 0.14f)
            .v (PID::auraFog, 0.44f).v (PID::auraDecay, 0.30f)
            .v (PID::auraLight, -0.50f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.40f)
            .v (PID::patinaNoise, 0.14f).v (PID::patinaWear, 0.34f)
            .v (PID::patinaDrift, 0.20f)
            .v (PID::synthWidth, 0.45f).v (PID::highWidth, 0.70f)
            .v (PID::lowMonoFreq, 300.0f)
            .v (PID::breathAmount, 0.30f).v (PID::breathSpeed, 0.05f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.06f)
            .v (PID::lfo1Depth, 0.50f)
            .route (srcLfo1, PID::filterCutoff, 0.05f)
            .route (srcBreath, PID::memoryBandwidth, 0.12f));

        // A finger-noise attack and a body-heavy sub: the one in the group
        // that has a transient at all.
        add (out, Build ("Upright Sub", "SUB", "WARM",
                         "acoustic,finger,round,short",
                         "A sub with a finger on the string at the start of every note.")
            .at (31, 1, 0.88f, 4.0)
            .chain ("FILTER,RETRO,SPACE,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::voiceVariation, 0.18f).v (PID::driftAmount, 0.18f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.80f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.22f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, 5.0f)
            .v (PID::subWave, ch::subTri).v (PID::subLevel, 0.56f)
            .v (PID::subHarmonics, 0.40f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.20f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.68f).v (PID::bodyTilt, 0.24f)
            .v (PID::densityAmount, 0.34f)
            .v (PID::preFilterDrive, 0.18f).v (PID::postSaturation, 0.18f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 520.0f).v (PID::filterResonance, 0.10f)
            .v (PID::filterDrive, 0.20f).v (PID::filterKeyTrack, 0.30f)
            .v (PID::filterEnvAmount, 0.48f).v (PID::filterVelAmount, 0.55f)
            .v (PID::ampAttack, 0.003f).v (PID::ampDecay, 1.1f)
            .v (PID::ampSustain, 0.48f).v (PID::ampRelease, 0.26f)
            .v (PID::ampVelocity, 0.66f)
            .v (PID::env1Attack, 0.0008f).v (PID::env1Decay, 0.14f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.10f)
            .v (PID::macroMemory, 0.32f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.56f).v (PID::memoryWobble, 0.20f)
            .v (PID::memoryAsymmetry, 0.06f)
            .v (PID::macroCharacter, 0.38f).v (PID::macroMotion, 0.24f)
            .v (PID::macroWorld, 0.22f).v (PID::macroWeight, 0.58f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.50f)
            .v (PID::weightCompress, 0.44f)
            .v (PID::retroEra, 0.22f).v (PID::retroAge, 0.38f)
            .v (PID::retroDrift, 0.18f).v (PID::retroWear, 0.12f)
            .v (PID::retroTone, -0.34f).v (PID::retroNoise, 0.12f)
            .v (PID::retroMix, 0.62f)
            .v (PID::fxFilterCutoff, 2200.0f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.20f)
            .v (PID::spaceSize, 0.24f).v (PID::spaceDecay, 0.9f)
            .v (PID::spaceFog, 0.24f).v (PID::spaceLight, -0.42f)
            .v (PID::spaceMix, 0.12f)
            .v (PID::auraSize, 0.20f).v (PID::auraDistance, 0.12f)
            .v (PID::auraFog, 0.30f).v (PID::auraDecay, 0.18f)
            .v (PID::auraLight, -0.36f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.26f)
            .v (PID::patinaNoise, 0.12f).v (PID::patinaWear, 0.22f)
            .v (PID::synthWidth, 0.55f).v (PID::highWidth, 0.80f)
            .v (PID::lowMonoFreq, 280.0f)
            .v (PID::breathAmount, 0.24f).v (PID::breathSpeed, 0.12f)
            .route (srcBreath, PID::bodyAmount, 0.10f)
            .route (srcTouch, PID::filterCutoff, 0.12f));

        // ---------------------------------------------------------------
        //  Everything below keeps the fundamental in the centre by
        //  construction: no oscillator is panned, no unison spread sits on
        //  an oscillator that carries the root, Shadow stays off, Grain
        //  stays out of the audible chain, Memory asymmetry - which is per
        //  channel ageing, so per channel decorrelation - is held at zero,
        //  and the low-mono crossover is raised well above where a sub
        //  lives.  Width, where there is any, is bought above 300 Hz.
        // ---------------------------------------------------------------

        // The workhorse: one sine, a long decay towards silence, and the
        // harmonics coming entirely from DENSE saturation and the drive in
        // front of the ladder.  Envelope 2 puts ten semitones into the pitch
        // and takes them back over a tenth of a second, so the note starts
        // above itself and settles onto the key.  The glide that is left is
        // the legato join between notes, which is the only job it still has.
        add (out, Build ("Gravedad", "SUB", "DARK",
                         "808,saturated,drop,long",
                         "A sine driven into DENSE saturation with a ten-semitone pitch envelope on the attack and a three-second decay.")
            .at (28, 1, 0.98f, 4.0)
            .chain ("FILTER,CRUSH,RETRO,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::legato).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.03f)
            .v (PID::voiceVariation, 0.06f).v (PID::driftAmount, 0.05f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.86f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBLevel, 0.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.52f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.38f)
            .v (PID::bodyAmount, 0.44f).v (PID::bodyTilt, -0.10f)
            .v (PID::densityAmount, 0.35f)
            .v (PID::preFilterDrive, 0.38f).v (PID::postSaturation, 0.44f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 340.0f).v (PID::filterResonance, 0.10f)
            .v (PID::filterDrive, 0.36f).v (PID::filterKeyTrack, 0.18f)
            .v (PID::filterEnvAmount, 0.18f).v (PID::filterVelAmount, 0.30f)
            .v (PID::ampAttack, 0.004f).v (PID::ampDecay, 3.2f)
            .v (PID::ampSustain, 0.18f).v (PID::ampRelease, 0.60f)
            .v (PID::ampVelocity, 0.38f)
            .v (PID::env1Attack, 0.0008f).v (PID::env1Decay, 0.09f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.08f)
            .v (PID::pitchEnvAmount, 10.0f)
            .v (PID::env2Attack, 0.0005f).v (PID::env2Decay, 0.10f)
            .v (PID::env2Sustain, 0.0f)
            .v (PID::macroMemory, 0.14f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.24f).v (PID::memoryWobble, 0.06f)
            .v (PID::memoryAsymmetry, 0.0f)
            .v (PID::macroCharacter, 0.42f).v (PID::macroMotion, 0.10f)
            .v (PID::macroWorld, 0.08f).v (PID::macroWeight, 0.72f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.70f)
            .v (PID::weightCompress, 0.52f)
            .v (PID::retroEra, 0.30f).v (PID::retroAge, 0.16f)
            .v (PID::retroDrift, 0.05f).v (PID::retroWear, 0.03f)
            .v (PID::retroTone, -0.24f).v (PID::retroNoise, 0.05f)
            .v (PID::retroMix, 0.30f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.14f)
            .v (PID::crushBits, 14.0f).v (PID::crushRate, 26000.0f)
            .v (PID::crushDrive, 0.24f).v (PID::crushTone, -0.30f)
            .v (PID::crushMix, 0.30f)
            .v (PID::fxFilterCutoff, 1600.0f).v (PID::fxFilterDrive, 0.12f)
            .v (PID::spaceOn, 0.0f)
            .v (PID::auraSize, 0.12f).v (PID::auraDistance, 0.05f)
            .v (PID::auraFog, 0.14f).v (PID::auraDecay, 0.10f)
            .v (PID::auraLight, -0.34f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.14f)
            .v (PID::patinaNoise, 0.04f).v (PID::patinaWear, 0.08f)
            .v (PID::patinaDrift, 0.05f)
            .v (PID::synthWidth, 0.35f).v (PID::highWidth, 0.55f)
            .v (PID::lowMonoFreq, 340.0f)
            .v (PID::breathAmount, 0.08f).v (PID::breathSpeed, 0.06f)
            .v (PID::masterGain, -3.0f)
            .route (srcTouch, PID::preFilterDrive, 0.18f)
            .route (srcWheel, PID::filterCutoff, 0.20f));

        // The same idea with the drive backed off and the decay stretched to
        // five seconds, so the pitch envelope is shallow and slow to match:
        // six semitones given back over a fifth of a second.  The third of a
        // second of portamento stays, because on this one the glide is the
        // note-to-note gesture and not a stand-in for the attack.  HAZE
        // instead of the ladder, so the top of the note stays where the
        // saturation put it.
        add (out, Build ("Plomada", "SUB", "MINIMAL",
                         "808,glide,drop,soft",
                         "A sine with a six-semitone pitch envelope, a third of a second of portamento between notes and a five-second decay, through HAZE.")
            .at (26, 1, 0.94f, 4.0)
            .chain ("RETRO,SPACE,FILTER,CRUSH,REWIND,GRAIN")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::legato).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.34f)
            .v (PID::voiceVariation, 0.08f).v (PID::driftAmount, 0.08f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.84f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.14f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, 0.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.50f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.26f)
            .v (PID::bodyAmount, 0.34f).v (PID::densityAmount, 0.27f)
            .v (PID::preFilterDrive, 0.20f).v (PID::postSaturation, 0.26f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 520.0f).v (PID::filterResonance, 0.08f)
            .v (PID::filterDrive, 0.16f).v (PID::filterKeyTrack, 0.25f)
            .v (PID::filterEnvAmount, 0.20f).v (PID::filterVelAmount, 0.24f)
            .v (PID::ampAttack, 0.006f).v (PID::ampDecay, 5.0f)
            .v (PID::ampSustain, 0.12f).v (PID::ampRelease, 0.90f)
            .v (PID::ampVelocity, 0.34f)
            .v (PID::env1Attack, 0.002f).v (PID::env1Decay, 0.30f)
            .v (PID::env1Sustain, 0.0f)
            .v (PID::pitchEnvAmount, 6.0f)
            .v (PID::env2Attack, 0.0005f).v (PID::env2Decay, 0.20f)
            .v (PID::env2Sustain, 0.0f)
            .v (PID::macroMemory, 0.18f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.30f).v (PID::memoryWobble, 0.08f)
            .v (PID::memoryAsymmetry, 0.0f)
            .v (PID::macroCharacter, 0.28f).v (PID::macroMotion, 0.12f)
            .v (PID::macroWorld, 0.12f).v (PID::macroWeight, 0.66f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.54f)
            .v (PID::weightCompress, 0.40f)
            .v (PID::retroEra, 0.26f).v (PID::retroAge, 0.20f)
            .v (PID::retroDrift, 0.08f).v (PID::retroWear, 0.04f)
            .v (PID::retroTone, -0.28f).v (PID::retroNoise, 0.06f)
            .v (PID::retroMix, 0.36f)
            .v (PID::fxFilterCutoff, 1900.0f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.10f)
            .v (PID::spaceSize, 0.18f).v (PID::spaceDecay, 0.70f)
            .v (PID::spaceFog, 0.20f).v (PID::spaceLight, -0.60f)
            .v (PID::spacePreDelay, 12.0f).v (PID::spaceMix, 0.07f)
            .v (PID::auraSize, 0.14f).v (PID::auraDistance, 0.06f)
            .v (PID::auraFog, 0.18f).v (PID::auraDecay, 0.14f)
            .v (PID::auraLight, -0.30f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.16f)
            .v (PID::patinaNoise, 0.05f).v (PID::patinaWear, 0.10f)
            .v (PID::patinaDrift, 0.06f)
            .v (PID::synthWidth, 0.40f).v (PID::highWidth, 0.60f)
            .v (PID::lowMonoFreq, 330.0f)
            .v (PID::breathAmount, 0.12f).v (PID::breathSpeed, 0.05f)
            .v (PID::masterGain, -2.0f)
            .route (srcBreath, PID::filterCutoff, 0.04f)
            .route (srcWheel, PID::glideTime, 0.30f));

        // The hard end of the same family.  Drive in front of the ladder,
        // EDGE saturation behind it and the quantiser first in the chain, so
        // the harmonics are made before anything gets to smooth them, and
        // eighteen semitones of pitch envelope over fifty-five milliseconds
        // to arrive with.  No glide at all now: the twenty milliseconds it
        // carried were only there to bend the note into place.
        add (out, Build ("Peso Muerto", "SUB", "AGGRESSIVE",
                         "808,drop,edge,crushed",
                         "A sine with an eighteen-semitone pitch envelope, pushed through drive, EDGE saturation and a nine-bit quantiser placed first in the chain.")
            .at (24, 1, 1.0f, 3.0)
            .chain ("CRUSH,FILTER,RETRO,SPACE,REWIND,GRAIN")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::voiceVariation, 0.06f).v (PID::driftAmount, 0.06f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.88f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBLevel, 0.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.46f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.55f)
            .v (PID::bodyAmount, 0.56f).v (PID::bodyTilt, 0.18f)
            .v (PID::densityAmount, 0.49f)
            .v (PID::preFilterDrive, 0.66f).v (PID::postSaturation, 0.58f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 420.0f).v (PID::filterResonance, 0.14f)
            .v (PID::filterDrive, 0.58f).v (PID::filterKeyTrack, 0.20f)
            .v (PID::filterEnvAmount, 0.22f).v (PID::filterVelAmount, 0.35f)
            .v (PID::ampAttack, 0.002f).v (PID::ampDecay, 2.0f)
            .v (PID::ampSustain, 0.10f).v (PID::ampRelease, 0.35f)
            .v (PID::ampVelocity, 0.45f)
            .v (PID::env1Attack, 0.0006f).v (PID::env1Decay, 0.07f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.06f)
            .v (PID::pitchEnvAmount, 18.0f)
            .v (PID::env2Attack, 0.0005f).v (PID::env2Decay, 0.055f)
            .v (PID::env2Sustain, 0.0f)
            .v (PID::macroMemory, 0.10f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.18f).v (PID::memoryWobble, 0.04f)
            .v (PID::memoryAsymmetry, 0.0f)
            .v (PID::macroCharacter, 0.66f).v (PID::macroMotion, 0.08f)
            .v (PID::macroWorld, 0.06f).v (PID::macroWeight, 0.78f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.80f)
            .v (PID::weightCompress, 0.64f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.34f)
            .v (PID::crushBits, 9.0f).v (PID::crushRate, 14000.0f)
            .v (PID::crushDrive, 0.40f).v (PID::crushTone, -0.42f)
            .v (PID::crushMix, 0.45f)
            .v (PID::retroEra, 0.22f).v (PID::retroAge, 0.22f)
            .v (PID::retroDrift, 0.04f).v (PID::retroWear, 0.04f)
            .v (PID::retroTone, -0.30f).v (PID::retroNoise, 0.06f)
            .v (PID::retroMix, 0.34f)
            .v (PID::fxFilterMode, ch::f2Lp).v (PID::fxFilterCutoff, 1800.0f)
            .v (PID::fxFilterDrive, 0.22f)
            .v (PID::spaceOn, 0.0f)
            .v (PID::auraSize, 0.10f).v (PID::auraDistance, 0.04f)
            .v (PID::auraFog, 0.12f).v (PID::auraDecay, 0.08f)
            .v (PID::auraLight, -0.20f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, -0.10f)
            .v (PID::patinaNoise, 0.05f).v (PID::patinaWear, 0.10f)
            .v (PID::patinaDrift, 0.04f)
            .v (PID::synthWidth, 0.30f).v (PID::highWidth, 0.50f)
            .v (PID::lowMonoFreq, 360.0f)
            .v (PID::breathAmount, 0.06f).v (PID::breathSpeed, 0.08f)
            .v (PID::masterGain, -5.0f)
            .route (srcTouch, PID::postSaturation, 0.24f)
            .route (srcWheel, PID::crushAmount, 0.25f));

        // Seven seconds of decay to nothing, almost no drive, and a notch
        // at 220 Hz so the fundamental and the octave above it stop sharing
        // the same space.  The one in the group that is all tail, so its
        // pitch envelope is the shallowest and the slowest of the five: five
        // semitones given back over three tenths of a second.  It never had
        // a glide and does not need one.
        add (out, Build ("Lastre", "SUB", "COLD",
                         "drop,long,notch,clean",
                         "A sine with a five-semitone pitch envelope, a seven-second decay to silence and a notch at 220 Hz separating the fundamental from its octave.")
            .at (26, 1, 0.90f, 4.0)
            .chain ("FILTER,SPACE,CRUSH,RETRO,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::voiceVariation, 0.05f).v (PID::driftAmount, 0.06f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.80f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBLevel, 0.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.56f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.20f)
            .v (PID::bodyAmount, 0.28f).v (PID::densityAmount, 0.21f)
            .v (PID::preFilterDrive, 0.14f).v (PID::postSaturation, 0.30f)
            .v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 280.0f).v (PID::filterResonance, 0.05f)
            .v (PID::filterDrive, 0.12f).v (PID::filterKeyTrack, 0.10f)
            .v (PID::filterEnvAmount, 0.08f).v (PID::filterVelAmount, 0.18f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Notch)
            .v (PID::filter2Cutoff, 220.0f).v (PID::filter2Res, 0.30f)
            .v (PID::filter2Mix, 0.35f)
            .v (PID::ampAttack, 0.010f).v (PID::ampDecay, 7.0f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 1.40f)
            .v (PID::ampVelocity, 0.30f)
            .v (PID::env1Decay, 0.50f).v (PID::env1Sustain, 0.0f)
            .v (PID::pitchEnvAmount, 5.0f)
            .v (PID::env2Attack, 0.0005f).v (PID::env2Decay, 0.30f)
            .v (PID::env2Sustain, 0.0f)
            .v (PID::macroMemory, 0.22f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.40f).v (PID::memoryWobble, 0.10f)
            .v (PID::memoryDiffusion, 0.12f).v (PID::memoryAsymmetry, 0.0f)
            .v (PID::macroCharacter, 0.24f).v (PID::macroMotion, 0.14f)
            .v (PID::macroWorld, 0.14f).v (PID::macroWeight, 0.60f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.46f)
            .v (PID::weightCompress, 0.34f)
            .v (PID::retroEra, 0.32f).v (PID::retroAge, 0.18f)
            .v (PID::retroDrift, 0.06f).v (PID::retroWear, 0.03f)
            .v (PID::retroTone, -0.32f).v (PID::retroNoise, 0.05f)
            .v (PID::retroMix, 0.28f)
            .v (PID::fxFilterCutoff, 1500.0f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.14f)
            .v (PID::spaceSize, 0.22f).v (PID::spaceDecay, 1.20f)
            .v (PID::spaceFog, 0.30f).v (PID::spaceLight, -0.70f)
            .v (PID::spacePreDelay, 30.0f).v (PID::spaceMix, 0.08f)
            .v (PID::auraSize, 0.18f).v (PID::auraDistance, 0.08f)
            .v (PID::auraFog, 0.22f).v (PID::auraDecay, 0.20f)
            .v (PID::auraLight, -0.44f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.20f)
            .v (PID::patinaNoise, 0.05f).v (PID::patinaWear, 0.10f)
            .v (PID::patinaDrift, 0.06f)
            .v (PID::synthWidth, 0.36f).v (PID::highWidth, 0.55f)
            .v (PID::lowMonoFreq, 320.0f)
            .v (PID::breathAmount, 0.10f).v (PID::breathSpeed, 0.04f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.08f)
            .v (PID::lfo1Depth, 0.40f)
            .v (PID::masterGain, -1.5f)
            .route (srcBreath, PID::filterCutoff, 0.03f)
            .route (srcLfo1, PID::weightHarmonics, 0.10f));

        // The clean one.  MIRAGE, no drive worth the name, Retro off,
        // Patina off, Breath off, Space off: a sine, a sub under it and a
        // little Weight, for arrangements where something else carries the
        // tone and this only holds the bottom.
        add (out, Build ("Nivel del Mar", "SUB", "MINIMAL",
                         "sine,clean,support,dry",
                         "A bare sine and sub with every colouration stage switched off, for when the sub is only support.")
            .at (31, 1, 0.85f, 3.0)
            .chain ("FILTER,RETRO,CRUSH,SPACE,REWIND,GRAIN")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::voiceVariation, 0.02f).v (PID::driftAmount, 0.02f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.90f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBLevel, 0.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.44f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.12f)
            .v (PID::bodyAmount, 0.18f).v (PID::densityAmount, 0.08f)
            .v (PID::preFilterDrive, 0.0f).v (PID::postSaturation, 0.02f)
            .v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 900.0f).v (PID::filterResonance, 0.0f)
            .v (PID::filterDrive, 0.0f).v (PID::filterKeyTrack, 0.30f)
            .v (PID::filterEnvAmount, 0.0f).v (PID::filterVelAmount, 0.10f)
            .v (PID::ampAttack, 0.012f).v (PID::ampDecay, 1.80f)
            .v (PID::ampSustain, 0.86f).v (PID::ampRelease, 0.30f)
            .v (PID::ampVelocity, 0.25f)
            .v (PID::macroMemory, 0.0f).v (PID::memoryBandwidth, 0.0f)
            .v (PID::memoryWobble, 0.0f).v (PID::memoryAsymmetry, 0.0f)
            .v (PID::macroCharacter, 0.05f).v (PID::macroMotion, 0.04f)
            .v (PID::macroWorld, 0.04f).v (PID::macroWeight, 0.40f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.18f)
            .v (PID::weightCompress, 0.22f)
            .v (PID::retroOn, 0.0f)
            .v (PID::fxFilterCutoff, 4000.0f)
            .v (PID::spaceOn, 0.0f)
            .v (PID::auraSize, 0.08f).v (PID::auraDistance, 0.04f)
            .v (PID::auraFog, 0.06f).v (PID::auraDecay, 0.06f)
            .v (PID::auraLight, -0.10f)
            .v (PID::patinaOn, 0.0f)
            .v (PID::breathOn, 0.0f).v (PID::breathAmount, 0.0f)
            .v (PID::synthWidth, 0.25f).v (PID::highWidth, 0.40f)
            .v (PID::lowMonoFreq, 400.0f)
            .route (srcWheel, PID::filterCutoff, 0.15f));

        // The other clean one, and the only polyphonic thing in the
        // category: a soft attack, a triangle an octave up at low level for
        // pitch, and a chamber placed first so the reverb is what the
        // filter then trims rather than the other way round.
        add (out, Build ("Cota Cero", "SUB", "INTIMATE",
                         "sine,poly,soft,support",
                         "A four-voice sine sub with a triangle an octave above it and a chamber ahead of the filter.")
            .at (36, 1, 0.80f, 3.0)
            .chain ("SPACE,FILTER,RETRO,CRUSH,GRAIN,REWIND")
            .v (PID::polyphony, 4.0f)
            .v (PID::voiceVariation, 0.12f).v (PID::driftAmount, 0.10f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.78f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.10f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, 0.0f)
            .v (PID::subWave, ch::subTri).v (PID::subLevel, 0.40f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.18f)
            .v (PID::bodyAmount, 0.26f).v (PID::densityAmount, 0.14f)
            .v (PID::preFilterDrive, 0.06f).v (PID::postSaturation, 0.10f)
            .v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 700.0f).v (PID::filterResonance, 0.04f)
            .v (PID::filterDrive, 0.05f).v (PID::filterKeyTrack, 0.35f)
            .v (PID::filterEnvAmount, 0.12f).v (PID::filterVelAmount, 0.20f)
            .v (PID::ampAttack, 0.020f).v (PID::ampDecay, 1.60f)
            .v (PID::ampSustain, 0.82f).v (PID::ampRelease, 0.45f)
            .v (PID::ampVelocity, 0.40f)
            .v (PID::macroMemory, 0.08f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.14f).v (PID::memoryWobble, 0.04f)
            .v (PID::memoryAsymmetry, 0.0f)
            .v (PID::macroCharacter, 0.18f).v (PID::macroMotion, 0.16f)
            .v (PID::macroWorld, 0.16f).v (PID::macroWeight, 0.42f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.26f)
            .v (PID::weightCompress, 0.28f)
            .v (PID::retroEra, 0.44f).v (PID::retroAge, 0.08f)
            .v (PID::retroDrift, 0.03f).v (PID::retroWear, 0.02f)
            .v (PID::retroTone, -0.12f).v (PID::retroNoise, 0.03f)
            .v (PID::retroMix, 0.18f)
            .v (PID::fxFilterCutoff, 3400.0f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.12f)
            .v (PID::spaceSize, 0.20f).v (PID::spaceDecay, 0.90f)
            .v (PID::spaceFog, 0.18f).v (PID::spaceLight, -0.40f)
            .v (PID::spacePreDelay, 16.0f).v (PID::spaceMix, 0.06f)
            .v (PID::auraSize, 0.16f).v (PID::auraDistance, 0.08f)
            .v (PID::auraFog, 0.16f).v (PID::auraDecay, 0.14f)
            .v (PID::auraLight, -0.18f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.06f)
            .v (PID::patinaNoise, 0.03f).v (PID::patinaWear, 0.05f)
            .v (PID::patinaDrift, 0.04f)
            .v (PID::synthWidth, 0.45f).v (PID::highWidth, 0.70f)
            .v (PID::lowMonoFreq, 300.0f)
            .v (PID::breathAmount, 0.14f).v (PID::breathSpeed, 0.09f)
            .route (srcBreath, PID::oscBLevel, 0.06f));

        // WEIGHT in SUB mode doing the work it was built for: harmonics at
        // 0.88 and the compressor inside it at 0.72, with a soft-square sub
        // and drive on both sides of the ladder feeding it.
        add (out, Build ("Lecho de Roca", "SUB", "DIRTY",
                         "weight,drive,square,harmonics",
                         "A soft-square sub through drive on both sides of the ladder into WEIGHT at its SUB setting.")
            .at (29, 1, 0.96f, 3.5)
            .chain ("CRUSH,RETRO,FILTER,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.03f)
            .v (PID::voiceVariation, 0.10f).v (PID::driftAmount, 0.12f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.80f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.22f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, 0.0f)
            .v (PID::subWave, ch::subSquare).v (PID::subLevel, 0.54f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.62f)
            .v (PID::bodyAmount, 0.66f).v (PID::bodyTilt, -0.20f)
            .v (PID::densityAmount, 0.50f)
            .v (PID::preFilterDrive, 0.52f).v (PID::postSaturation, 0.46f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 380.0f).v (PID::filterResonance, 0.18f)
            .v (PID::filterDrive, 0.46f).v (PID::filterKeyTrack, 0.16f)
            .v (PID::filterEnvAmount, 0.26f).v (PID::filterVelAmount, 0.28f)
            .v (PID::ampAttack, 0.005f).v (PID::ampDecay, 2.40f)
            .v (PID::ampSustain, 0.74f).v (PID::ampRelease, 0.40f)
            .v (PID::ampVelocity, 0.36f)
            .v (PID::env1Decay, 0.16f).v (PID::env1Sustain, 0.10f)
            .v (PID::macroMemory, 0.20f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.34f).v (PID::memoryWobble, 0.10f)
            .v (PID::memoryAsymmetry, 0.0f)
            .v (PID::macroCharacter, 0.62f).v (PID::macroMotion, 0.16f)
            .v (PID::macroWorld, 0.10f).v (PID::macroWeight, 0.86f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.88f)
            .v (PID::weightCompress, 0.72f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.22f)
            .v (PID::crushBits, 11.0f).v (PID::crushRate, 18000.0f)
            .v (PID::crushDrive, 0.30f).v (PID::crushTone, -0.36f)
            .v (PID::crushMix, 0.34f)
            .v (PID::retroEra, 0.18f).v (PID::retroAge, 0.34f)
            .v (PID::retroDrift, 0.10f).v (PID::retroWear, 0.08f)
            .v (PID::retroTone, -0.38f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.52f)
            .v (PID::fxFilterMode, ch::f2Lp).v (PID::fxFilterCutoff, 1500.0f)
            .v (PID::fxFilterDrive, 0.20f)
            .v (PID::spaceOn, 0.0f)
            .v (PID::auraSize, 0.14f).v (PID::auraDistance, 0.06f)
            .v (PID::auraFog, 0.20f).v (PID::auraDecay, 0.12f)
            .v (PID::auraLight, -0.40f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.30f)
            .v (PID::patinaNoise, 0.10f).v (PID::patinaWear, 0.20f)
            .v (PID::patinaDrift, 0.10f)
            .v (PID::synthWidth, 0.32f).v (PID::highWidth, 0.55f)
            .v (PID::lowMonoFreq, 360.0f)
            .v (PID::breathAmount, 0.16f).v (PID::breathSpeed, 0.08f)
            .v (PID::masterGain, -4.0f)
            .route (srcTouch, PID::weightHarmonics, 0.20f)
            .route (srcWheel, PID::preFilterDrive, 0.22f)
            .route (srcBreath, PID::bodyAmount, 0.08f));

        // Harmonics from phase modulation instead of from a waveshaper:
        // oscillator B sits an octave up at zero level and modulates A's
        // phase, so the series it adds is above the fundamental by
        // construction and stays exactly where the fundamental is in the
        // image.  EDGE saturation and a twelve-bit floor behind it.
        add (out, Build ("Basalto", "SUB", "COLD",
                         "pm,harmonics,hard,cold",
                         "Phase modulation at a 2:1 ratio makes the harmonic series above a sine fundamental, with EDGE saturation behind it.")
            .at (28, 1, 0.92f, 3.5)
            .chain ("RETRO,CRUSH,SPACE,FILTER,GRAIN,REWIND")
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.04f)
            .v (PID::voiceVariation, 0.08f).v (PID::driftAmount, 0.08f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.84f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.0f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, 0.0f)
            .v (PID::oscBPhase, ch::phaseReset)
            .v (PID::oscPmAmount, 0.30f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.48f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.22f)
            .v (PID::bodyAmount, 0.38f).v (PID::densityAmount, 0.28f)
            .v (PID::preFilterDrive, 0.16f).v (PID::postSaturation, 0.18f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 640.0f).v (PID::filterResonance, 0.26f)
            .v (PID::filterDrive, 0.20f).v (PID::filterKeyTrack, 0.22f)
            .v (PID::filterEnvAmount, 0.30f).v (PID::filterVelAmount, 0.25f)
            .v (PID::ampAttack, 0.004f).v (PID::ampDecay, 2.60f)
            .v (PID::ampSustain, 0.62f).v (PID::ampRelease, 0.45f)
            .v (PID::ampVelocity, 0.38f)
            .v (PID::env1Attack, 0.001f).v (PID::env1Decay, 0.18f)
            .v (PID::env1Sustain, 0.05f)
            .v (PID::macroMemory, 0.16f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.26f).v (PID::memoryWobble, 0.06f)
            .v (PID::memoryAsymmetry, 0.0f)
            .v (PID::macroCharacter, 0.44f).v (PID::macroMotion, 0.14f)
            .v (PID::macroWorld, 0.12f).v (PID::macroWeight, 0.58f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.44f)
            .v (PID::weightCompress, 0.38f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.18f)
            .v (PID::crushBits, 12.0f).v (PID::crushRate, 20000.0f)
            .v (PID::crushDrive, 0.16f).v (PID::crushTone, -0.20f)
            .v (PID::crushMix, 0.24f)
            .v (PID::retroEra, 0.52f).v (PID::retroAge, 0.18f)
            .v (PID::retroDrift, 0.05f).v (PID::retroWear, 0.04f)
            .v (PID::retroTone, -0.20f).v (PID::retroNoise, 0.05f)
            .v (PID::retroMix, 0.30f)
            .v (PID::fxFilterCutoff, 2800.0f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.12f)
            .v (PID::spaceSize, 0.20f).v (PID::spaceDecay, 1.00f)
            .v (PID::spaceFog, 0.30f).v (PID::spaceLight, -0.70f)
            .v (PID::spacePreDelay, 18.0f).v (PID::spaceMix, 0.08f)
            .v (PID::auraSize, 0.16f).v (PID::auraDistance, 0.08f)
            .v (PID::auraFog, 0.20f).v (PID::auraDecay, 0.14f)
            .v (PID::auraLight, -0.26f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, -0.12f)
            .v (PID::patinaNoise, 0.05f).v (PID::patinaWear, 0.10f)
            .v (PID::patinaDrift, 0.08f)
            .v (PID::synthWidth, 0.34f).v (PID::highWidth, 0.60f)
            .v (PID::lowMonoFreq, 350.0f)
            .v (PID::breathAmount, 0.14f).v (PID::breathSpeed, 0.10f)
            .v (PID::masterGain, -2.0f)
            .route (srcWheel, PID::oscPmAmount, 0.28f)
            .route (srcBreath, PID::filterCutoff, 0.04f));

        // The COMB model as the primary filter, tuned to 1.4 kHz with key
        // tracking off, so its first feature is two decades above the
        // fundamental and it colours only what the drive and the quantiser
        // added.  The one structural oddity in the group.
        add (out, Build ("Fondo de Grava", "SUB", "DIRTY",
                         "comb,crushed,drive,rough",
                         "A driven sub through the COMB filter at 1.4 kHz with key tracking off, so the comb only touches the harmonics.")
            .at (33, 1, 0.90f, 3.0)
            .chain ("FILTER,CRUSH,SPACE,RETRO,REWIND,GRAIN")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.02f)
            .v (PID::voiceVariation, 0.12f).v (PID::driftAmount, 0.10f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.80f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::saw).v (PID::oscBLevel, 0.16f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, 0.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.52f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.44f)
            .v (PID::bodyAmount, 0.50f).v (PID::bodyTilt, 0.10f)
            .v (PID::densityAmount, 0.36f)
            .v (PID::preFilterDrive, 0.44f).v (PID::postSaturation, 0.34f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1400.0f).v (PID::filterResonance, 0.22f)
            .v (PID::filterDrive, 0.24f).v (PID::filterKeyTrack, 0.0f)
            .v (PID::filterEnvAmount, 0.10f).v (PID::filterVelAmount, 0.15f)
            .v (PID::ampAttack, 0.003f).v (PID::ampDecay, 1.90f)
            .v (PID::ampSustain, 0.70f).v (PID::ampRelease, 0.35f)
            .v (PID::ampVelocity, 0.42f)
            .v (PID::env1Decay, 0.20f).v (PID::env1Sustain, 0.15f)
            .v (PID::macroMemory, 0.18f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.30f).v (PID::memoryWobble, 0.08f)
            .v (PID::memoryAsymmetry, 0.0f)
            .v (PID::macroCharacter, 0.56f).v (PID::macroMotion, 0.18f)
            .v (PID::macroWorld, 0.12f).v (PID::macroWeight, 0.74f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.72f)
            .v (PID::weightCompress, 0.56f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.26f)
            .v (PID::crushBits, 10.0f).v (PID::crushRate, 16000.0f)
            .v (PID::crushDrive, 0.28f).v (PID::crushTone, -0.30f)
            .v (PID::crushMix, 0.38f)
            .v (PID::retroEra, 0.20f).v (PID::retroAge, 0.30f)
            .v (PID::retroDrift, 0.09f).v (PID::retroWear, 0.07f)
            .v (PID::retroTone, -0.34f).v (PID::retroNoise, 0.09f)
            .v (PID::retroMix, 0.46f)
            .v (PID::fxFilterMode, ch::f2Lp).v (PID::fxFilterCutoff, 2000.0f)
            .v (PID::fxFilterDrive, 0.16f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.10f)
            .v (PID::spaceSize, 0.16f).v (PID::spaceDecay, 0.60f)
            .v (PID::spaceFog, 0.20f).v (PID::spaceLight, -0.55f)
            .v (PID::spacePreDelay, 10.0f).v (PID::spaceMix, 0.06f)
            .v (PID::auraSize, 0.14f).v (PID::auraDistance, 0.06f)
            .v (PID::auraFog, 0.18f).v (PID::auraDecay, 0.12f)
            .v (PID::auraLight, -0.34f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.26f)
            .v (PID::patinaNoise, 0.09f).v (PID::patinaWear, 0.18f)
            .v (PID::patinaDrift, 0.10f)
            .v (PID::synthWidth, 0.38f).v (PID::highWidth, 0.62f)
            .v (PID::lowMonoFreq, 340.0f)
            .v (PID::breathAmount, 0.18f).v (PID::breathSpeed, 0.12f)
            .v (PID::masterGain, -3.5f)
            .route (srcTouch, PID::filterCutoff, 0.18f)
            .route (srcOrganic, PID::filterResonance, 0.08f));

        // The Minimoog reading: two triangles seven cents apart, both at
        // the root and both dead centre, a saw an octave up for edge, and
        // the ladder run with enough resonance and internal drive to
        // thicken rather than to whistle.
        add (out, Build ("Abismo", "SUB", "DARK",
                         "minimoog,ladder,resonance,mono",
                         "Two triangles seven cents apart into the MASS ladder at high resonance and drive, both oscillators centred.")
            .at (28, 1, 0.98f, 3.5)
            .chain ("FILTER,RETRO,CRUSH,GRAIN,SPACE,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.035f)
            .v (PID::voiceVariation, 0.22f).v (PID::driftAmount, 0.28f)
            .v (PID::driftRate, 0.09f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.82f)
            .v (PID::oscAPhase, ch::phaseFree)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.46f)
            .v (PID::oscBOctave, 0.0f).v (PID::oscBFine, -7.0f)
            .v (PID::oscBPhase, ch::phaseFree)
            .v (PID::oscCWave, ch::saw).v (PID::oscCLevel, 0.10f)
            .v (PID::oscCOctave, 1.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.46f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.30f)
            .v (PID::bodyAmount, 0.62f).v (PID::bodyTilt, -0.12f)
            .v (PID::densityAmount, 0.46f)
            .v (PID::preFilterDrive, 0.40f).v (PID::postSaturation, 0.26f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 460.0f).v (PID::filterResonance, 0.44f)
            .v (PID::filterDrive, 0.54f).v (PID::filterKeyTrack, 0.30f)
            .v (PID::filterEnvAmount, 0.38f).v (PID::filterVelAmount, 0.40f)
            .v (PID::ampAttack, 0.004f).v (PID::ampDecay, 1.50f)
            .v (PID::ampSustain, 0.80f).v (PID::ampRelease, 0.28f)
            .v (PID::ampVelocity, 0.42f)
            .v (PID::env1Attack, 0.001f).v (PID::env1Decay, 0.25f)
            .v (PID::env1Sustain, 0.20f).v (PID::env1Release, 0.20f)
            .v (PID::macroMemory, 0.20f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.32f).v (PID::memoryWobble, 0.12f)
            .v (PID::memoryAsymmetry, 0.0f)
            .v (PID::macroCharacter, 0.50f).v (PID::macroMotion, 0.28f)
            .v (PID::macroWorld, 0.10f).v (PID::macroWeight, 0.62f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.50f)
            .v (PID::weightCompress, 0.42f)
            .v (PID::retroEra, 0.16f).v (PID::retroAge, 0.26f)
            .v (PID::retroDrift, 0.12f).v (PID::retroWear, 0.06f)
            .v (PID::retroTone, -0.30f).v (PID::retroNoise, 0.08f)
            .v (PID::retroMix, 0.42f)
            .v (PID::fxFilterCutoff, 2400.0f).v (PID::fxFilterDrive, 0.14f)
            .v (PID::spaceOn, 0.0f)
            .v (PID::auraSize, 0.18f).v (PID::auraDistance, 0.08f)
            .v (PID::auraFog, 0.24f).v (PID::auraDecay, 0.16f)
            .v (PID::auraLight, -0.36f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.22f)
            .v (PID::patinaNoise, 0.08f).v (PID::patinaWear, 0.16f)
            .v (PID::patinaDrift, 0.12f)
            .v (PID::synthWidth, 0.42f).v (PID::highWidth, 0.65f)
            .v (PID::lowMonoFreq, 300.0f)
            .v (PID::breathAmount, 0.20f).v (PID::breathSpeed, 0.11f)
            .v (PID::masterGain, -2.5f)
            .route (srcBreath, PID::filterCutoff, 0.05f)
            .route (srcTouch, PID::filterResonance, 0.14f)
            .route (srcWheel, PID::filterCutoff, 0.22f));

        // The legato sibling: a saw at the root taken down to 300 Hz by a
        // resonant ladder, so all the harmonic content is the ladder's own
        // nonlinearity rather than the oscillator's, and a fifth of a
        // second of glide holding a line together.
        add (out, Build ("Talud Continental", "SUB", "MYSTERIOUS",
                         "legato,glide,ladder,saw",
                         "A saw filtered to 300 Hz by a resonant MASS ladder, with a fifth of a second of legato glide.")
            .at (31, 1, 0.90f, 4.0)
            .chain ("RETRO,FILTER,CRUSH,SPACE,REWIND,GRAIN")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::legato).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.20f)
            .v (PID::voiceVariation, 0.26f).v (PID::driftAmount, 0.30f)
            .v (PID::driftRate, 0.07f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.68f)
            .v (PID::oscAPhase, ch::phaseFree)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.40f)
            .v (PID::oscBOctave, 0.0f).v (PID::oscBFine, 6.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.50f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.34f)
            .v (PID::bodyAmount, 0.58f).v (PID::bodyTilt, -0.24f)
            .v (PID::densityAmount, 0.42f)
            .v (PID::preFilterDrive, 0.34f).v (PID::postSaturation, 0.22f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 300.0f).v (PID::filterResonance, 0.52f)
            .v (PID::filterDrive, 0.46f).v (PID::filterKeyTrack, 0.22f)
            .v (PID::filterEnvAmount, 0.44f).v (PID::filterVelAmount, 0.30f)
            .v (PID::ampAttack, 0.020f).v (PID::ampDecay, 2.20f)
            .v (PID::ampSustain, 0.78f).v (PID::ampRelease, 0.55f)
            .v (PID::ampVelocity, 0.34f)
            .v (PID::env1Attack, 0.004f).v (PID::env1Decay, 0.60f)
            .v (PID::env1Sustain, 0.15f)
            .v (PID::macroMemory, 0.30f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.48f).v (PID::memoryWobble, 0.16f)
            .v (PID::memoryDiffusion, 0.14f).v (PID::memoryAsymmetry, 0.02f)
            .v (PID::macroCharacter, 0.46f).v (PID::macroMotion, 0.30f)
            .v (PID::macroWorld, 0.20f).v (PID::macroWeight, 0.64f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.48f)
            .v (PID::weightCompress, 0.44f)
            .v (PID::retroEra, 0.14f).v (PID::retroAge, 0.36f)
            .v (PID::retroDrift, 0.14f).v (PID::retroWear, 0.09f)
            .v (PID::retroTone, -0.42f).v (PID::retroNoise, 0.11f)
            .v (PID::retroMix, 0.58f)
            .v (PID::fxFilterMode, ch::f2Lp).v (PID::fxFilterCutoff, 1300.0f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.16f)
            .v (PID::spaceSize, 0.26f).v (PID::spaceDecay, 1.60f)
            .v (PID::spaceFog, 0.38f).v (PID::spaceLight, -0.66f)
            .v (PID::spacePreDelay, 26.0f).v (PID::spaceMix, 0.10f)
            .v (PID::auraSize, 0.24f).v (PID::auraDistance, 0.12f)
            .v (PID::auraFog, 0.34f).v (PID::auraDecay, 0.24f)
            .v (PID::auraLight, -0.48f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.34f)
            .v (PID::patinaNoise, 0.12f).v (PID::patinaWear, 0.24f)
            .v (PID::patinaDrift, 0.14f)
            .v (PID::synthWidth, 0.46f).v (PID::highWidth, 0.70f)
            .v (PID::lowMonoFreq, 290.0f)
            .v (PID::breathAmount, 0.26f).v (PID::breathSpeed, 0.07f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.09f)
            .v (PID::lfo1Depth, 0.40f)
            .route (srcLfo1, PID::filterCutoff, 0.05f)
            .route (srcBreath, PID::oscBFine, 0.04f)
            .route (srcTouch, PID::filterCutoff, 0.14f));

        // A hybrid: the sine holds the fundamental and a soft-harmonic
        // wavetable sits a twelfth above it, which is the interval that
        // tells a small speaker what the note is.  A little formant on the
        // creative filter colours the upper element only.
        add (out, Build ("Quinta Sumergida", "SUB", "MYSTERIOUS",
                         "hybrid,twelfth,wavetable,formant",
                         "A sine fundamental with a soft-harmonic wavetable a twelfth above it, coloured by a low-mix formant stage.")
            .at (29, 1, 0.90f, 3.5)
            .chain ("FILTER,SPACE,CRUSH,REWIND,RETRO,GRAIN")
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.06f)
            .v (PID::voiceVariation, 0.14f).v (PID::driftAmount, 0.16f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.82f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tSoft)
            .v (PID::oscBWtPos, 0.20f).v (PID::oscBLevel, 0.20f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBSemi, 7.0f)
            .v (PID::oscBFine, 0.0f)
            .v (PID::oscCWave, ch::sine).v (PID::oscCLevel, 0.12f)
            .v (PID::oscCOctave, 1.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.52f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.28f)
            .v (PID::bodyAmount, 0.44f).v (PID::bodyTilt, 0.16f)
            .v (PID::densityAmount, 0.30f)
            .v (PID::preFilterDrive, 0.18f).v (PID::postSaturation, 0.20f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 820.0f).v (PID::filterResonance, 0.20f)
            .v (PID::filterDrive, 0.16f).v (PID::filterKeyTrack, 0.40f)
            .v (PID::filterEnvAmount, 0.28f).v (PID::filterVelAmount, 0.30f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Formant)
            .v (PID::filter2Cutoff, 520.0f).v (PID::filter2Res, 0.28f)
            .v (PID::filter2Mix, 0.22f)
            .v (PID::ampAttack, 0.008f).v (PID::ampDecay, 2.00f)
            .v (PID::ampSustain, 0.72f).v (PID::ampRelease, 0.40f)
            .v (PID::ampVelocity, 0.40f)
            .v (PID::env1Decay, 0.30f).v (PID::env1Sustain, 0.20f)
            .v (PID::macroMemory, 0.24f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.42f).v (PID::memoryWobble, 0.14f)
            .v (PID::memoryDiffusion, 0.16f).v (PID::memoryAsymmetry, 0.0f)
            .v (PID::macroCharacter, 0.36f).v (PID::macroMotion, 0.26f)
            .v (PID::macroWorld, 0.20f).v (PID::macroWeight, 0.56f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.40f)
            .v (PID::weightCompress, 0.36f)
            .v (PID::retroEra, 0.36f).v (PID::retroAge, 0.24f)
            .v (PID::retroDrift, 0.10f).v (PID::retroWear, 0.06f)
            .v (PID::retroTone, -0.26f).v (PID::retroNoise, 0.08f)
            .v (PID::retroMix, 0.40f)
            .v (PID::fxFilterCutoff, 3000.0f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.16f)
            .v (PID::spaceSize, 0.24f).v (PID::spaceDecay, 1.30f)
            .v (PID::spaceFog, 0.32f).v (PID::spaceLight, -0.50f)
            .v (PID::spacePreDelay, 24.0f).v (PID::spaceMix, 0.10f)
            .v (PID::auraSize, 0.22f).v (PID::auraDistance, 0.10f)
            .v (PID::auraFog, 0.28f).v (PID::auraDecay, 0.20f)
            .v (PID::auraLight, -0.30f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.18f)
            .v (PID::patinaNoise, 0.08f).v (PID::patinaWear, 0.14f)
            .v (PID::patinaDrift, 0.10f)
            .v (PID::synthWidth, 0.50f).v (PID::highWidth, 0.85f)
            .v (PID::lowMonoFreq, 300.0f)
            .v (PID::breathAmount, 0.22f).v (PID::breathSpeed, 0.10f)
            .route (srcBreath, PID::oscBWtPos, 0.14f)
            .route (srcWheel, PID::oscBLevel, 0.25f)
            .route (srcTouch, PID::filter2Mix, 0.12f));

        // The other hybrid, and the ring modulator used the one way it is
        // safe down here: B is an exact octave above A, so the product is
        // the fundamental and its third harmonic and nothing underneath.
        // WEIGHT moves to BODY because the octave is what needs the help.
        add (out, Build ("Doble Fondo", "SUB", "WARM",
                         "hybrid,ringmod,octave,body",
                         "Ring modulation at an exact octave adds a third harmonic over the sine, with WEIGHT set to BODY.")
            .at (33, 1, 0.88f, 3.5)
            .chain ("RETRO,FILTER,SPACE,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.03f)
            .v (PID::voiceVariation, 0.16f).v (PID::driftAmount, 0.18f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.80f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.28f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, 0.0f)
            .v (PID::oscBPhase, ch::phaseReset)
            .v (PID::oscRingMod, 0.18f)
            .v (PID::oscCWave, ch::tri).v (PID::oscCLevel, 0.14f)
            .v (PID::oscCOctave, 1.0f)
            .v (PID::subWave, ch::subTri).v (PID::subLevel, 0.46f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.32f)
            .v (PID::bodyAmount, 0.72f).v (PID::bodyTilt, 0.30f)
            .v (PID::densityAmount, 0.40f)
            .v (PID::preFilterDrive, 0.22f).v (PID::postSaturation, 0.24f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 560.0f).v (PID::filterResonance, 0.12f)
            .v (PID::filterDrive, 0.24f).v (PID::filterKeyTrack, 0.45f)
            .v (PID::filterEnvAmount, 0.30f).v (PID::filterVelAmount, 0.42f)
            .v (PID::ampAttack, 0.006f).v (PID::ampDecay, 1.70f)
            .v (PID::ampSustain, 0.66f).v (PID::ampRelease, 0.35f)
            .v (PID::ampVelocity, 0.52f)
            .v (PID::env1Decay, 0.22f).v (PID::env1Sustain, 0.12f)
            .v (PID::macroMemory, 0.26f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.44f).v (PID::memoryWobble, 0.16f)
            .v (PID::memoryAsymmetry, 0.02f)
            .v (PID::macroCharacter, 0.40f).v (PID::macroMotion, 0.24f)
            .v (PID::macroWorld, 0.18f).v (PID::macroWeight, 0.54f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.46f)
            .v (PID::weightCompress, 0.40f)
            .v (PID::retroEra, 0.20f).v (PID::retroAge, 0.28f)
            .v (PID::retroDrift, 0.12f).v (PID::retroWear, 0.07f)
            .v (PID::retroTone, -0.30f).v (PID::retroNoise, 0.09f)
            .v (PID::retroMix, 0.50f)
            .v (PID::fxFilterMode, ch::f2Lp).v (PID::fxFilterCutoff, 2600.0f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.14f)
            .v (PID::spaceSize, 0.20f).v (PID::spaceDecay, 0.80f)
            .v (PID::spaceFog, 0.22f).v (PID::spaceLight, -0.46f)
            .v (PID::spacePreDelay, 14.0f).v (PID::spaceMix, 0.09f)
            .v (PID::auraSize, 0.20f).v (PID::auraDistance, 0.10f)
            .v (PID::auraFog, 0.26f).v (PID::auraDecay, 0.18f)
            .v (PID::auraLight, -0.32f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.22f)
            .v (PID::patinaNoise, 0.08f).v (PID::patinaWear, 0.16f)
            .v (PID::patinaDrift, 0.10f)
            .v (PID::synthWidth, 0.52f).v (PID::highWidth, 0.82f)
            .v (PID::lowMonoFreq, 290.0f)
            .v (PID::breathAmount, 0.20f).v (PID::breathSpeed, 0.12f)
            .route (srcBreath, PID::oscRingMod, 0.08f)
            .route (srcTouch, PID::oscCLevel, 0.18f));

        // A third of a second and gone: sustain at zero, a dark noise burst
        // confined to the attack, and fourteen semitones of pitch envelope
        // given back over forty-five milliseconds, which is where the knock
        // comes from.  The envelope on the cutoff is backed off to match -
        // it shapes brightness now rather than standing in for a fall.  For
        // low end that has to leave room between the notes.
        add (out, Build ("Pisada", "SUB", "MINIMAL",
                         "pluck,short,drop,gated",
                         "A sub with the amplitude sustain at zero, a 340 ms decay, a fourteen-semitone pitch envelope and a noise burst confined to the attack.")
            .at (31, 1, 0.95f, 2.5)
            .chain ("FILTER,CRUSH,REWIND,RETRO,SPACE,GRAIN")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::voiceVariation, 0.10f).v (PID::driftAmount, 0.08f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.84f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBLevel, 0.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.50f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.42f)
            .v (PID::noiseType, ch::nDark).v (PID::noiseLevel, 0.14f)
            .v (PID::noiseAttackOnly, 1.0f)
            .v (PID::bodyAmount, 0.40f).v (PID::densityAmount, 0.29f)
            .v (PID::preFilterDrive, 0.28f).v (PID::postSaturation, 0.24f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 480.0f).v (PID::filterResonance, 0.20f)
            .v (PID::filterDrive, 0.30f).v (PID::filterKeyTrack, 0.30f)
            .v (PID::filterEnvAmount, 0.40f).v (PID::filterVelAmount, 0.50f)
            .v (PID::ampAttack, 0.001f).v (PID::ampDecay, 0.34f)
            .v (PID::ampSustain, 0.0f).v (PID::ampRelease, 0.10f)
            .v (PID::ampVelocity, 0.72f)
            .v (PID::env1Attack, 0.0005f).v (PID::env1Decay, 0.05f)
            .v (PID::env1Sustain, 0.0f).v (PID::env1Release, 0.04f)
            .v (PID::pitchEnvAmount, 14.0f)
            .v (PID::env2Attack, 0.0005f).v (PID::env2Decay, 0.045f)
            .v (PID::env2Sustain, 0.0f)
            .v (PID::macroMemory, 0.12f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.20f).v (PID::memoryWobble, 0.05f)
            .v (PID::memoryAsymmetry, 0.0f)
            .v (PID::macroCharacter, 0.38f).v (PID::macroMotion, 0.12f)
            .v (PID::macroWorld, 0.06f).v (PID::macroWeight, 0.68f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.60f)
            .v (PID::weightCompress, 0.50f)
            .v (PID::retroEra, 0.28f).v (PID::retroAge, 0.14f)
            .v (PID::retroDrift, 0.04f).v (PID::retroWear, 0.03f)
            .v (PID::retroTone, -0.22f).v (PID::retroNoise, 0.04f)
            .v (PID::retroMix, 0.28f)
            .v (PID::fxFilterCutoff, 2200.0f).v (PID::fxFilterDrive, 0.10f)
            .v (PID::spaceOn, 0.0f)
            .v (PID::auraSize, 0.10f).v (PID::auraDistance, 0.04f)
            .v (PID::auraFog, 0.12f).v (PID::auraDecay, 0.08f)
            .v (PID::auraLight, -0.24f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.14f)
            .v (PID::patinaNoise, 0.04f).v (PID::patinaWear, 0.08f)
            .v (PID::patinaDrift, 0.04f)
            .v (PID::synthWidth, 0.34f).v (PID::highWidth, 0.58f)
            .v (PID::lowMonoFreq, 350.0f)
            .v (PID::breathAmount, 0.10f).v (PID::breathSpeed, 0.14f)
            .v (PID::masterGain, -2.0f)
            .route (srcTouch, PID::ampDecay, 0.16f)
            .route (srcWheel, PID::filterCutoff, 0.18f));

        // The gate is PULSE rather than the amplitude envelope: a held
        // note, eighth notes off the host clock, and the duck taken almost
        // entirely on level.  Pulse also narrows and dries on every hit,
        // which is the right direction for this band.
        add (out, Build ("Compuerta", "SUB", "COLD",
                         "gated,pulse,eighths,clock",
                         "A held sub chopped into eighth notes by PULSE, ducking level, brightness, width and wetness together.")
            .at (26, 1, 0.94f, 4.0)
            .chain ("CRUSH,FILTER,SPACE,RETRO,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.02f)
            .v (PID::voiceVariation, 0.08f).v (PID::driftAmount, 0.08f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.84f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscBLevel, 0.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.52f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.36f)
            .v (PID::bodyAmount, 0.42f).v (PID::densityAmount, 0.30f)
            .v (PID::preFilterDrive, 0.30f).v (PID::postSaturation, 0.28f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 520.0f).v (PID::filterResonance, 0.14f)
            .v (PID::filterDrive, 0.24f).v (PID::filterKeyTrack, 0.20f)
            .v (PID::filterEnvAmount, 0.16f).v (PID::filterVelAmount, 0.20f)
            .v (PID::ampAttack, 0.004f).v (PID::ampDecay, 3.00f)
            .v (PID::ampSustain, 0.86f).v (PID::ampRelease, 0.30f)
            .v (PID::ampVelocity, 0.30f)
            .v (PID::pulseOn, 1.0f).v (PID::pulseSource, ch::pClock)
            .v (PID::pulseDivision, ch::p8).v (PID::pulseDepth, 0.72f)
            .v (PID::pulseAttack, 0.002f).v (PID::pulseRelease, 0.16f)
            .v (PID::pulseSmooth, 0.35f).v (PID::pulseToVolume, 0.95f)
            .v (PID::pulseToFilter, 0.30f).v (PID::pulseToSpace, 0.20f)
            .v (PID::pulseToWidth, 0.30f).v (PID::pulseToMemory, 0.0f)
            .v (PID::macroMemory, 0.14f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.22f).v (PID::memoryWobble, 0.06f)
            .v (PID::memoryAsymmetry, 0.0f)
            .v (PID::macroCharacter, 0.40f).v (PID::macroMotion, 0.18f)
            .v (PID::macroWorld, 0.10f).v (PID::macroWeight, 0.70f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.58f)
            .v (PID::weightCompress, 0.54f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.16f)
            .v (PID::crushBits, 12.0f).v (PID::crushRate, 21000.0f)
            .v (PID::crushDrive, 0.18f).v (PID::crushTone, -0.24f)
            .v (PID::crushMix, 0.26f)
            .v (PID::retroEra, 0.24f).v (PID::retroAge, 0.18f)
            .v (PID::retroDrift, 0.06f).v (PID::retroWear, 0.04f)
            .v (PID::retroTone, -0.26f).v (PID::retroNoise, 0.06f)
            .v (PID::retroMix, 0.32f)
            .v (PID::fxFilterCutoff, 2000.0f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.10f)
            .v (PID::spaceSize, 0.14f).v (PID::spaceDecay, 0.50f)
            .v (PID::spaceFog, 0.18f).v (PID::spaceLight, -0.60f)
            .v (PID::spacePreDelay, 8.0f).v (PID::spaceMix, 0.05f)
            .v (PID::auraSize, 0.12f).v (PID::auraDistance, 0.06f)
            .v (PID::auraFog, 0.16f).v (PID::auraDecay, 0.10f)
            .v (PID::auraLight, -0.30f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, -0.16f)
            .v (PID::patinaNoise, 0.05f).v (PID::patinaWear, 0.10f)
            .v (PID::patinaDrift, 0.06f)
            .v (PID::synthWidth, 0.32f).v (PID::highWidth, 0.54f)
            .v (PID::lowMonoFreq, 360.0f)
            .v (PID::breathAmount, 0.12f).v (PID::breathSpeed, 0.10f)
            .v (PID::masterGain, -2.0f)
            .route (srcPulse, PID::filterCutoff, -0.20f)
            .route (srcWheel, PID::pulseDepth, 0.30f));

        // The width technique done the only way it is allowed down here.
        // Oscillator A carries the root with its spread at zero; all four
        // unison voices and all the detune live on a wavetable two octaves
        // up, and the low-mono crossover is at the top of its range, so
        // everything under 400 Hz is collapsed to the centre before it
        // leaves the synth.
        add (out, Build ("Marea Baja", "SUB", "DREAMY",
                         "wide,unison,wavetable,crossover",
                         "Width bought two octaves up from a four-voice unison wavetable, with the low-mono crossover at 400 Hz.")
            .at (33, 1, 0.86f, 4.0)
            .chain ("SPACE,RETRO,FILTER,CRUSH,GRAIN,REWIND")
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.05f)
            .v (PID::voiceVariation, 0.16f).v (PID::driftAmount, 0.18f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.82f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscAUnison, 1.0f).v (PID::oscASpread, 0.0f)
            .v (PID::oscAPan, 0.0f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tSpectral)
            .v (PID::oscBWtPos, 0.30f).v (PID::oscBLevel, 0.22f)
            .v (PID::oscBOctave, 2.0f).v (PID::oscBFine, 8.0f)
            .v (PID::oscBUnison, 4.0f).v (PID::oscBDetune, 0.24f)
            .v (PID::oscBSpread, 0.85f).v (PID::oscBPan, 0.0f)
            .v (PID::oscCWave, ch::sine).v (PID::oscCLevel, 0.10f)
            .v (PID::oscCOctave, 1.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.50f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.26f)
            .v (PID::bodyAmount, 0.36f).v (PID::densityAmount, 0.28f)
            .v (PID::preFilterDrive, 0.14f).v (PID::postSaturation, 0.16f)
            .v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1100.0f).v (PID::filterResonance, 0.14f)
            .v (PID::filterDrive, 0.12f).v (PID::filterKeyTrack, 0.45f)
            .v (PID::filterEnvAmount, 0.24f).v (PID::filterVelAmount, 0.26f)
            .v (PID::ampAttack, 0.030f).v (PID::ampDecay, 2.40f)
            .v (PID::ampSustain, 0.78f).v (PID::ampRelease, 0.70f)
            .v (PID::ampVelocity, 0.36f)
            .v (PID::env1Decay, 0.40f).v (PID::env1Sustain, 0.25f)
            .v (PID::macroMemory, 0.20f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.36f).v (PID::memoryWobble, 0.12f)
            .v (PID::memoryDiffusion, 0.14f).v (PID::memoryAsymmetry, 0.0f)
            .v (PID::macroCharacter, 0.32f).v (PID::macroMotion, 0.30f)
            .v (PID::macroWorld, 0.26f).v (PID::macroWeight, 0.50f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.36f)
            .v (PID::weightCompress, 0.34f)
            .v (PID::retroEra, 0.40f).v (PID::retroAge, 0.20f)
            .v (PID::retroDrift, 0.08f).v (PID::retroWear, 0.05f)
            .v (PID::retroTone, -0.20f).v (PID::retroNoise, 0.06f)
            .v (PID::retroMix, 0.34f)
            .v (PID::fxFilterCutoff, 5000.0f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.22f)
            .v (PID::spaceSize, 0.34f).v (PID::spaceDecay, 2.00f)
            .v (PID::spaceFog, 0.42f).v (PID::spaceLight, -0.30f)
            .v (PID::spacePreDelay, 34.0f).v (PID::spaceMix, 0.12f)
            .v (PID::auraSize, 0.26f).v (PID::auraDistance, 0.14f)
            .v (PID::auraFog, 0.30f).v (PID::auraDecay, 0.24f)
            .v (PID::auraLight, -0.16f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.10f)
            .v (PID::patinaNoise, 0.07f).v (PID::patinaWear, 0.12f)
            .v (PID::patinaDrift, 0.10f)
            .v (PID::synthWidth, 0.90f).v (PID::highWidth, 1.60f)
            .v (PID::lowMonoFreq, 400.0f)
            .v (PID::breathAmount, 0.24f).v (PID::breathSpeed, 0.10f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.14f)
            .v (PID::lfo2Depth, 0.50f)
            .route (srcLfo2, PID::oscBWtPos, 0.20f)
            .route (srcBreath, PID::oscBDetune, 0.10f)
            .route (srcWheel, PID::highWidth, 0.20f));

        // The same rule, a different mechanism: nothing is detuned or
        // panned at all.  The fundamental is a phase-modulated sine, a
        // hollow wavetable sits two octaves up, and the width comes from
        // the HIGH WIDTH stage plus a comb on the creative filter, both of
        // which act above where the crossover has already collapsed.
        add (out, Build ("Corriente de Fondo", "SUB", "MYSTERIOUS",
                         "wide,pm,comb,crossover",
                         "A phase-modulated sine kept centred, with all the width taken above a 380 Hz mono crossover by HIGH WIDTH and a comb stage.")
            .at (29, 1, 0.90f, 4.0)
            .chain ("FILTER,SPACE,RETRO,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::legato).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.10f)
            .v (PID::voiceVariation, 0.14f).v (PID::driftAmount, 0.16f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.84f)
            .v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscAUnison, 1.0f).v (PID::oscASpread, 0.0f)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.0f)
            .v (PID::oscBOctave, 2.0f).v (PID::oscBFine, 0.0f)
            .v (PID::oscBPhase, ch::phaseReset)
            .v (PID::oscPmAmount, 0.22f)
            .v (PID::oscCWave, ch::wt).v (PID::oscCWtTable, ch::tHollow)
            .v (PID::oscCLevel, 0.18f).v (PID::oscCOctave, 2.0f)
            .v (PID::oscCPan, 0.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.50f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.30f)
            .v (PID::bodyAmount, 0.40f).v (PID::bodyTilt, -0.08f)
            .v (PID::densityAmount, 0.32f)
            .v (PID::preFilterDrive, 0.20f).v (PID::postSaturation, 0.22f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 620.0f).v (PID::filterResonance, 0.18f)
            .v (PID::filterDrive, 0.22f).v (PID::filterKeyTrack, 0.40f)
            .v (PID::filterEnvAmount, 0.26f).v (PID::filterVelAmount, 0.24f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Comb)
            .v (PID::filter2Cutoff, 1800.0f).v (PID::filter2Res, 0.30f)
            .v (PID::filter2Mix, 0.26f)
            .v (PID::ampAttack, 0.014f).v (PID::ampDecay, 2.80f)
            .v (PID::ampSustain, 0.74f).v (PID::ampRelease, 0.80f)
            .v (PID::ampVelocity, 0.34f)
            .v (PID::env1Decay, 0.45f).v (PID::env1Sustain, 0.20f)
            .v (PID::macroMemory, 0.28f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.46f).v (PID::memoryWobble, 0.14f)
            .v (PID::memoryDiffusion, 0.18f).v (PID::memoryAsymmetry, 0.0f)
            .v (PID::macroCharacter, 0.38f).v (PID::macroMotion, 0.26f)
            .v (PID::macroWorld, 0.24f).v (PID::macroWeight, 0.60f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.48f)
            .v (PID::weightCompress, 0.40f)
            .v (PID::retroEra, 0.30f).v (PID::retroAge, 0.26f)
            .v (PID::retroDrift, 0.10f).v (PID::retroWear, 0.06f)
            .v (PID::retroTone, -0.28f).v (PID::retroNoise, 0.08f)
            .v (PID::retroMix, 0.42f)
            .v (PID::fxFilterCutoff, 4200.0f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.20f)
            .v (PID::spaceSize, 0.30f).v (PID::spaceDecay, 1.80f)
            .v (PID::spaceFog, 0.40f).v (PID::spaceLight, -0.44f)
            .v (PID::spacePreDelay, 28.0f).v (PID::spaceMix, 0.11f)
            .v (PID::auraSize, 0.24f).v (PID::auraDistance, 0.12f)
            .v (PID::auraFog, 0.30f).v (PID::auraDecay, 0.22f)
            .v (PID::auraLight, -0.28f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.18f)
            .v (PID::patinaNoise, 0.08f).v (PID::patinaWear, 0.14f)
            .v (PID::patinaDrift, 0.10f)
            .v (PID::synthWidth, 0.85f).v (PID::highWidth, 1.50f)
            .v (PID::lowMonoFreq, 380.0f)
            .v (PID::breathAmount, 0.22f).v (PID::breathSpeed, 0.09f)
            .route (srcBreath, PID::oscPmAmount, 0.06f)
            .route (srcTouch, PID::oscCLevel, 0.20f)
            .route (srcWheel, PID::filter2Mix, 0.24f));
    }
}
