#include "PresetBuilder.h"
#include "Builders.h"

namespace nacar::presets::detail
{
    // ===============================================================
    //  TEXTURE
    // ===============================================================
    void buildTexture (std::vector<FactoryPreset>& out)
    {
        // The oscillators are nearly absent: this is the noise exciter, the
        // medium's own floor, and four generations of both.
        add (out, Build ("Tape Dust", "TEXTURE", "DIRTY",
                         "noise,floor,wear,bed",
                         "The sound of the tape between the songs, turned up until it is a song.")
            .at (40, 1, 0.70f, 7.0)
            .chain ("RETRO,CRUSH,FILTER,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.50f)
            .v (PID::driftAmount, 0.38f).v (PID::driftRate, 0.16f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.16f)
            .v (PID::oscBWave, ch::saw).v (PID::oscBLevel, 0.10f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, 13.0f)
            .v (PID::subLevel, 0.12f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.62f)
            .v (PID::noiseAttackOnly, 0.0f)
            .v (PID::bodyAmount, 0.34f).v (PID::densityAmount, 0.30f)
            .v (PID::preFilterDrive, 0.24f).v (PID::postSaturation, 0.26f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 2200.0f).v (PID::filterResonance, 0.20f)
            .v (PID::filterKeyTrack, 0.20f).v (PID::filterEnvAmount, 0.18f)
            .v (PID::ampAttack, 0.8f).v (PID::ampDecay, 3.0f)
            .v (PID::ampSustain, 0.90f).v (PID::ampRelease, 2.4f)
            .v (PID::ampVelocity, 0.25f)
            .v (PID::macroMemory, 0.70f).v (PID::memoryGen, ch::genIV)
            .v (PID::memoryBandwidth, 0.66f).v (PID::memoryWobble, 0.44f)
            .v (PID::memoryDiffusion, 0.40f).v (PID::memoryAsymmetry, 0.58f)
            .v (PID::macroCharacter, 0.70f).v (PID::macroMotion, 0.50f)
            .v (PID::macroWorld, 0.40f).v (PID::macroWeight, 0.26f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.30f)
            .v (PID::crushBits, 11.0f).v (PID::crushRate, 16000.0f)
            .v (PID::crushJitter, 0.30f).v (PID::crushTone, -0.12f)
            .v (PID::crushMix, 0.40f)
            .v (PID::retroEra, 0.24f).v (PID::retroAge, 0.74f)
            .v (PID::retroDrift, 0.52f).v (PID::retroWear, 0.66f)
            .v (PID::retroTone, -0.26f).v (PID::retroNoise, 0.46f)
            .v (PID::retroMix, 1.0f)
            .v (PID::fxFilterCutoff, 4400.0f).v (PID::fxFilterMotion, 0.26f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.40f)
            .v (PID::spaceSize, 0.46f).v (PID::spaceDecay, 3.0f)
            .v (PID::spaceFog, 0.54f).v (PID::spaceLight, -0.38f)
            .v (PID::spaceMix, 0.24f)
            .v (PID::auraSize, 0.44f).v (PID::auraDistance, 0.30f)
            .v (PID::auraFog, 0.58f).v (PID::auraDecay, 0.40f)
            .v (PID::auraLight, -0.30f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.26f)
            .v (PID::patinaNoise, 0.44f).v (PID::patinaWear, 0.58f)
            .v (PID::patinaDrift, 0.44f)
            .v (PID::synthWidth, 1.10f).v (PID::highWidth, 1.15f)
            .v (PID::breathAmount, 0.50f).v (PID::breathSpeed, 0.20f)
            .v (PID::breathRandom, 0.80f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.16f)
            .v (PID::lfo2Depth, 0.60f)
            .route (srcLfo2, PID::filterCutoff, 0.12f)
            .route (srcBreath, PID::retroNoise, 0.20f)
            .route (srcOrganic, PID::patinaWear, 0.16f));

        // Grain at maximum scatter over a METALLIC table, with feedback
        // bounded well short of the engine's own ceiling.
        add (out, Build ("Ground Glass", "TEXTURE", "COLD",
                         "granular,metallic,scatter,feedback",
                         "A metallic drone put through a mill and reassembled from the pieces.")
            .at (55, 1, 0.76f, 8.0)
            .chain ("FILTER,GRAIN,CRUSH,SPACE,RETRO,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.40f)
            .v (PID::driftAmount, 0.20f).v (PID::driftRate, 0.12f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tMetal)
            .v (PID::oscAWtPos, 0.60f).v (PID::oscALevel, 0.62f)
            .v (PID::oscAUnison, 3.0f).v (PID::oscADetune, 0.30f)
            .v (PID::oscASpread, 0.80f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tSpectral)
            .v (PID::oscBWtPos, 0.34f).v (PID::oscBLevel, 0.36f)
            .v (PID::oscBSemi, 5.0f).v (PID::oscBFine, 22.0f)
            .v (PID::subLevel, 0.06f)
            .v (PID::noiseType, ch::nWhite).v (PID::noiseLevel, 0.10f)
            .v (PID::bodyAmount, 0.10f).v (PID::densityAmount, 0.16f)
            .v (PID::postSaturation, 0.10f).v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1800.0f).v (PID::filterResonance, 0.36f)
            .v (PID::filterKeyTrack, 0.50f).v (PID::filterEnvAmount, 0.24f)
            .v (PID::ampAttack, 1.2f).v (PID::ampDecay, 4.0f)
            .v (PID::ampSustain, 0.86f).v (PID::ampRelease, 3.0f)
            .v (PID::ampVelocity, 0.30f)
            .v (PID::macroMemory, 0.26f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.30f).v (PID::memoryWobble, 0.24f)
            .v (PID::memoryDiffusion, 0.48f)
            .v (PID::macroCharacter, 0.36f).v (PID::macroMotion, 0.62f)
            .v (PID::macroWorld, 0.58f).v (PID::macroWeight, 0.24f)
            .v (PID::weightMode, ch::wAir).v (PID::weightHarmonics, 0.46f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.78f)
            .v (PID::grainSize, 34.0f).v (PID::grainDensity, 48.0f)
            .v (PID::grainPosition, 0.30f).v (PID::grainPitchMode, ch::gFifth)
            .v (PID::grainSpread, 0.85f).v (PID::grainJitter, 0.56f)
            .v (PID::grainDirection, 0.28f).v (PID::grainWindow, ch::wPercussive)
            .v (PID::grainFeedback, 0.36f).v (PID::grainMix, 0.66f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.24f)
            .v (PID::crushBits, 12.0f).v (PID::crushRate, 21000.0f)
            .v (PID::crushTone, 0.20f).v (PID::crushMix, 0.34f)
            .v (PID::retroEra, 0.90f).v (PID::retroAge, 0.16f)
            .v (PID::retroDrift, 0.12f).v (PID::retroWear, 0.10f)
            .v (PID::retroTone, 0.18f).v (PID::retroNoise, 0.08f)
            .v (PID::retroMix, 0.32f)
            .v (PID::fxFilterCutoff, 12500.0f).v (PID::fxFilterRes, 0.12f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.44f)
            .v (PID::spaceSize, 0.66f).v (PID::spaceDecay, 5.0f)
            .v (PID::spaceFog, 0.46f).v (PID::spaceLight, 0.28f)
            .v (PID::spaceMix, 0.34f)
            .v (PID::auraSize, 0.62f).v (PID::auraDistance, 0.36f)
            .v (PID::auraFog, 0.44f).v (PID::auraDecay, 0.56f)
            .v (PID::auraLight, 0.34f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.24f)
            .v (PID::patinaNoise, 0.18f).v (PID::patinaWear, 0.30f)
            .v (PID::patinaDrift, 0.20f)
            .v (PID::synthWidth, 1.30f).v (PID::highWidth, 1.40f)
            .v (PID::lowMonoFreq, 190.0f)
            .v (PID::breathAmount, 0.48f).v (PID::breathSpeed, 0.26f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Rate, 0.24f)
            .v (PID::lfo1Depth, 0.65f)
            .route (srcLfo1, PID::grainPosition, 0.36f)
            .route (srcBreath, PID::oscAWtPos, 0.24f)
            .route (srcMotion, PID::grainSpread, 0.18f));

        // FX filter MOTION at high depth over a COMB primary: a texture
        // whose whole identity is that the filter will not sit still.
        add (out, Build ("Magnetic Field", "TEXTURE", "MYSTERIOUS",
                         "motion,comb,sweeping,drone",
                         "A drone with a filter that has decided to wander on its own.")
            .at (43, 2, 0.72f, 9.0)
            .chain ("RETRO,FILTER,SPACE,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.54f)
            .v (PID::driftAmount, 0.44f).v (PID::driftRate, 0.05f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.58f)
            .v (PID::oscAUnison, 4.0f).v (PID::oscADetune, 0.36f)
            .v (PID::oscASpread, 0.86f).v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tAsym)
            .v (PID::oscBWtPos, 0.50f).v (PID::oscBLevel, 0.40f)
            .v (PID::oscBOctave, 0.0f).v (PID::oscBFine, -9.0f)
            .v (PID::oscCWave, ch::tri).v (PID::oscCLevel, 0.14f)
            .v (PID::oscCOctave, 1.0f).v (PID::oscCSemi, 7.0f)
            .v (PID::subLevel, 0.08f)
            .v (PID::noiseType, ch::nDark).v (PID::noiseLevel, 0.14f)
            .v (PID::bodyAmount, 0.30f).v (PID::densityAmount, 0.36f)
            .v (PID::preFilterDrive, 0.18f).v (PID::postSaturation, 0.16f)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1700.0f).v (PID::filterResonance, 0.48f)
            .v (PID::filterKeyTrack, 0.35f).v (PID::filterEnvAmount, 0.30f)
            .v (PID::ampAttack, 1.6f).v (PID::ampDecay, 5.0f)
            .v (PID::ampSustain, 0.84f).v (PID::ampRelease, 4.0f)
            .v (PID::ampVelocity, 0.28f)
            .v (PID::macroMemory, 0.44f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.50f).v (PID::memoryWobble, 0.42f)
            .v (PID::memoryDiffusion, 0.62f).v (PID::memoryAsymmetry, 0.44f)
            .v (PID::macroCharacter, 0.38f).v (PID::macroMotion, 0.84f)
            .v (PID::macroWorld, 0.60f).v (PID::macroWeight, 0.28f)
            .v (PID::retroEra, 0.58f).v (PID::retroAge, 0.34f)
            .v (PID::retroDrift, 0.44f).v (PID::retroWear, 0.22f)
            .v (PID::retroTone, -0.14f).v (PID::retroNoise, 0.18f)
            .v (PID::retroMix, 0.60f)
            .v (PID::fxFilterMode, ch::f2Bp).v (PID::fxFilterCutoff, 2400.0f)
            .v (PID::fxFilterRes, 0.44f).v (PID::fxFilterMorph, 0.55f)
            .v (PID::fxFilterMotion, 0.86f).v (PID::fxFilterDrive, 0.18f)
            .v (PID::fxFilterMix, 0.70f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.50f)
            .v (PID::spaceSize, 0.70f).v (PID::spaceDecay, 6.0f)
            .v (PID::spaceFog, 0.60f).v (PID::spaceLight, -0.18f)
            .v (PID::spaceMix, 0.38f)
            .v (PID::auraSize, 0.68f).v (PID::auraDistance, 0.42f)
            .v (PID::auraFog, 0.60f).v (PID::auraDecay, 0.62f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.08f)
            .v (PID::patinaNoise, 0.18f).v (PID::patinaWear, 0.34f)
            .v (PID::patinaDrift, 0.48f)
            .v (PID::synthWidth, 1.25f).v (PID::highWidth, 1.30f)
            .v (PID::breathAmount, 0.74f).v (PID::breathSpeed, 0.08f)
            .v (PID::breathRandom, 0.78f).v (PID::breathShape, 0.40f)
            .v (PID::lfo1Shape, ch::lfoTri).v (PID::lfo1Rate, 0.08f)
            .v (PID::lfo1Depth, 0.70f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.19f)
            .v (PID::lfo2Depth, 0.60f)
            .route (srcLfo1, PID::filterCutoff, 0.20f)
            .route (srcLfo2, PID::fxFilterCutoff, 0.22f)
            .route (srcBreath, PID::filterResonance, 0.14f));

        // DIGITAL noise, a notch that moves, and Rewind in DIVE mode, which
        // falls three octaves and is still moving when the window ends.
        add (out, Build ("Shortwave Static", "TEXTURE", "BROKEN",
                         "static,dive,notch,interference",
                         "Tuning across a band at night and catching the edge of something.")
            .at (46, 1, 0.80f, 7.0)
            .chain ("CRUSH,FILTER,REWIND,RETRO,GRAIN,SPACE")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.46f)
            .v (PID::driftAmount, 0.40f).v (PID::driftRate, 0.60f)
            .v (PID::oscAWave, ch::square).v (PID::oscALevel, 0.24f)
            .v (PID::oscAPulseWidth, 0.14f)
            .v (PID::oscBWave, ch::saw).v (PID::oscBLevel, 0.18f)
            .v (PID::oscBSemi, -7.0f).v (PID::oscBFine, 19.0f)
            .v (PID::oscRingMod, 0.34f)
            .v (PID::subLevel, 0.06f)
            .v (PID::noiseType, ch::nDigital).v (PID::noiseLevel, 0.56f)
            .v (PID::bodyAmount, 0.12f).v (PID::densityAmount, 0.18f)
            .v (PID::preFilterDrive, 0.22f).v (PID::postSaturation, 0.20f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::notch)
            .v (PID::filterCutoff, 2000.0f).v (PID::filterResonance, 0.46f)
            .v (PID::filterKeyTrack, 0.20f).v (PID::filterEnvAmount, 0.30f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Bp)
            .v (PID::filter2Cutoff, 3200.0f).v (PID::filter2Res, 0.52f)
            .v (PID::filter2Mix, 0.60f)
            .v (PID::ampAttack, 0.30f).v (PID::ampDecay, 2.0f)
            .v (PID::ampSustain, 0.88f).v (PID::ampRelease, 1.2f)
            .v (PID::ampVelocity, 0.30f)
            .v (PID::macroMemory, 0.58f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.60f).v (PID::memoryWobble, 0.54f)
            .v (PID::memoryDiffusion, 0.40f).v (PID::memoryAsymmetry, 0.62f)
            .v (PID::macroCharacter, 0.60f).v (PID::macroMotion, 0.76f)
            .v (PID::macroWorld, 0.32f).v (PID::macroWeight, 0.20f)
            .v (PID::macroAlter, 0.50f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.52f)
            .v (PID::crushBits, 7.0f).v (PID::crushRate, 11000.0f)
            .v (PID::crushJitter, 0.56f).v (PID::crushDrive, 0.26f)
            .v (PID::crushTone, 0.14f).v (PID::crushMix, 0.66f)
            .v (PID::rewindOn, 1.0f).v (PID::rewindMode, ch::rDive)
            .v (PID::rewindDivision, ch::rw2).v (PID::rewindSync, 1.0f)
            .v (PID::rewindCurve, 0.70f).v (PID::rewindSpeed, 1.4f)
            .v (PID::rewindTail, 0.44f).v (PID::rewindMix, 0.38f)
            .v (PID::retroEra, 0.82f).v (PID::retroAge, 0.50f)
            .v (PID::retroDrift, 0.40f).v (PID::retroWear, 0.60f)
            .v (PID::retroTone, -0.06f).v (PID::retroNoise, 0.32f)
            .v (PID::retroMix, 0.84f)
            .v (PID::fxFilterCutoff, 8200.0f).v (PID::fxFilterRes, 0.26f)
            .v (PID::fxFilterMotion, 0.44f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.46f)
            .v (PID::spaceSize, 0.50f).v (PID::spaceDecay, 3.6f)
            .v (PID::spaceFog, 0.56f).v (PID::spaceLight, -0.20f)
            .v (PID::spaceMix, 0.24f)
            .v (PID::auraSize, 0.48f).v (PID::auraDistance, 0.34f)
            .v (PID::auraFog, 0.58f).v (PID::auraDecay, 0.44f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaNoise, 0.34f)
            .v (PID::patinaWear, 0.54f).v (PID::patinaDrift, 0.50f)
            .v (PID::synthWidth, 1.20f).v (PID::highWidth, 1.30f)
            .v (PID::breathAmount, 0.66f).v (PID::breathSpeed, 0.60f)
            .v (PID::breathRandom, 0.90f).v (PID::breathShape, 0.75f)
            .v (PID::lfo2Shape, ch::lfoRandom).v (PID::lfo2Rate, 3.2f)
            .v (PID::lfo2Depth, 0.70f)
            .route (srcLfo2, PID::filterCutoff, 0.22f)
            .route (srcOrganic, PID::filter2Cutoff, 0.30f)
            .route (srcBreath, PID::noiseLevel, 0.20f));
    }
}
