#include "PresetBuilder.h"
#include "Builders.h"

namespace nacar::presets::detail
{
    // ===============================================================
    //  TEXTURE
    // ===============================================================
    void buildTexture (std::vector<FactoryPreset>& out)
    {
        // The oscillators are nearly absent: this is the noise exciter, the
        // medium's own floor, and four generations of both.
        add (out, Build ("Tape Dust", "TEXTURE", "DIRTY",
                         "noise,floor,wear,bed",
                         "The sound of the tape between the songs, turned up until it is a song.")
            .at (40, 1, 0.70f, 7.0)
            .chain ("RETRO,CRUSH,FILTER,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.50f)
            .v (PID::driftAmount, 0.38f).v (PID::driftRate, 0.16f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.16f)
            .v (PID::oscBWave, ch::saw).v (PID::oscBLevel, 0.10f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, 13.0f)
            .v (PID::subLevel, 0.12f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.62f)
            .v (PID::noiseAttackOnly, 0.0f)
            .v (PID::bodyAmount, 0.34f).v (PID::densityAmount, 0.30f)
            .v (PID::preFilterDrive, 0.24f).v (PID::postSaturation, 0.26f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 2200.0f).v (PID::filterResonance, 0.20f)
            .v (PID::filterKeyTrack, 0.20f).v (PID::filterEnvAmount, 0.18f)
            .v (PID::ampAttack, 0.8f).v (PID::ampDecay, 3.0f)
            .v (PID::ampSustain, 0.90f).v (PID::ampRelease, 2.4f)
            .v (PID::ampVelocity, 0.25f)
            .v (PID::macroMemory, 0.70f).v (PID::memoryGen, ch::genIV)
            .v (PID::memoryBandwidth, 0.66f).v (PID::memoryWobble, 0.44f)
            .v (PID::memoryDiffusion, 0.40f).v (PID::memoryAsymmetry, 0.58f)
            .v (PID::macroCharacter, 0.70f).v (PID::macroMotion, 0.50f)
            .v (PID::macroWorld, 0.40f).v (PID::macroWeight, 0.26f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.30f)
            .v (PID::crushBits, 11.0f).v (PID::crushRate, 16000.0f)
            .v (PID::crushJitter, 0.30f).v (PID::crushTone, -0.12f)
            .v (PID::crushMix, 0.40f)
            .v (PID::retroEra, 0.24f).v (PID::retroAge, 0.74f)
            .v (PID::retroDrift, 0.52f).v (PID::retroWear, 0.66f)
            .v (PID::retroTone, -0.26f).v (PID::retroNoise, 0.46f)
            .v (PID::retroMix, 1.0f)
            .v (PID::fxFilterCutoff, 4400.0f).v (PID::fxFilterMotion, 0.26f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.40f)
            .v (PID::spaceSize, 0.46f).v (PID::spaceDecay, 3.0f)
            .v (PID::spaceFog, 0.54f).v (PID::spaceLight, -0.38f)
            .v (PID::spaceMix, 0.24f)
            .v (PID::auraSize, 0.44f).v (PID::auraDistance, 0.30f)
            .v (PID::auraFog, 0.58f).v (PID::auraDecay, 0.40f)
            .v (PID::auraLight, -0.30f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.26f)
            .v (PID::patinaNoise, 0.44f).v (PID::patinaWear, 0.58f)
            .v (PID::patinaDrift, 0.44f)
            .v (PID::synthWidth, 1.10f).v (PID::highWidth, 1.15f)
            .v (PID::breathAmount, 0.50f).v (PID::breathSpeed, 0.20f)
            .v (PID::breathRandom, 0.80f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.16f)
            .v (PID::lfo2Depth, 0.60f)
            .route (srcLfo2, PID::filterCutoff, 0.12f)
            .route (srcBreath, PID::retroNoise, 0.20f)
            .route (srcOrganic, PID::patinaWear, 0.16f));

        // Grain at maximum scatter over a METALLIC table, with feedback
        // bounded well short of the engine's own ceiling.
        add (out, Build ("Ground Glass", "TEXTURE", "COLD",
                         "granular,metallic,scatter,feedback",
                         "A metallic drone put through a mill and reassembled from the pieces.")
            .at (55, 1, 0.76f, 8.0)
            .chain ("FILTER,GRAIN,CRUSH,SPACE,RETRO,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.40f)
            .v (PID::driftAmount, 0.20f).v (PID::driftRate, 0.12f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tMetal)
            .v (PID::oscAWtPos, 0.60f).v (PID::oscALevel, 0.62f)
            .v (PID::oscAUnison, 3.0f).v (PID::oscADetune, 0.30f)
            .v (PID::oscASpread, 0.80f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tSpectral)
            .v (PID::oscBWtPos, 0.34f).v (PID::oscBLevel, 0.36f)
            .v (PID::oscBSemi, 5.0f).v (PID::oscBFine, 22.0f)
            .v (PID::subLevel, 0.06f)
            .v (PID::noiseType, ch::nWhite).v (PID::noiseLevel, 0.10f)
            .v (PID::bodyAmount, 0.10f).v (PID::densityAmount, 0.16f)
            .v (PID::postSaturation, 0.10f).v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1800.0f).v (PID::filterResonance, 0.36f)
            .v (PID::filterKeyTrack, 0.50f).v (PID::filterEnvAmount, 0.24f)
            .v (PID::ampAttack, 1.2f).v (PID::ampDecay, 4.0f)
            .v (PID::ampSustain, 0.86f).v (PID::ampRelease, 3.0f)
            .v (PID::ampVelocity, 0.30f)
            .v (PID::macroMemory, 0.26f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.30f).v (PID::memoryWobble, 0.24f)
            .v (PID::memoryDiffusion, 0.48f)
            .v (PID::macroCharacter, 0.36f).v (PID::macroMotion, 0.62f)
            .v (PID::macroWorld, 0.58f).v (PID::macroWeight, 0.24f)
            .v (PID::weightMode, ch::wAir).v (PID::weightHarmonics, 0.46f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.78f)
            .v (PID::grainSize, 34.0f).v (PID::grainDensity, 48.0f)
            .v (PID::grainPosition, 0.30f).v (PID::grainPitchMode, ch::gFifth)
            .v (PID::grainSpread, 0.85f).v (PID::grainJitter, 0.56f)
            .v (PID::grainDirection, 0.28f).v (PID::grainWindow, ch::wPercussive)
            .v (PID::grainFeedback, 0.36f).v (PID::grainMix, 0.66f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.24f)
            .v (PID::crushBits, 12.0f).v (PID::crushRate, 21000.0f)
            .v (PID::crushTone, 0.20f).v (PID::crushMix, 0.34f)
            .v (PID::retroEra, 0.90f).v (PID::retroAge, 0.16f)
            .v (PID::retroDrift, 0.12f).v (PID::retroWear, 0.10f)
            .v (PID::retroTone, 0.18f).v (PID::retroNoise, 0.08f)
            .v (PID::retroMix, 0.32f)
            .v (PID::fxFilterCutoff, 12500.0f).v (PID::fxFilterRes, 0.12f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.44f)
            .v (PID::spaceSize, 0.66f).v (PID::spaceDecay, 5.0f)
            .v (PID::spaceFog, 0.46f).v (PID::spaceLight, 0.28f)
            .v (PID::spaceMix, 0.34f)
            .v (PID::auraSize, 0.62f).v (PID::auraDistance, 0.36f)
            .v (PID::auraFog, 0.44f).v (PID::auraDecay, 0.56f)
            .v (PID::auraLight, 0.34f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.24f)
            .v (PID::patinaNoise, 0.18f).v (PID::patinaWear, 0.30f)
            .v (PID::patinaDrift, 0.20f)
            .v (PID::synthWidth, 1.30f).v (PID::highWidth, 1.40f)
            .v (PID::lowMonoFreq, 190.0f)
            .v (PID::breathAmount, 0.48f).v (PID::breathSpeed, 0.26f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Rate, 0.24f)
            .v (PID::lfo1Depth, 0.65f)
            .route (srcLfo1, PID::grainPosition, 0.36f)
            .route (srcBreath, PID::oscAWtPos, 0.24f)
            .route (srcMotion, PID::grainSpread, 0.18f));

        // FX filter MOTION at high depth over a COMB primary: a texture
        // whose whole identity is that the filter will not sit still.
        add (out, Build ("Magnetic Field", "TEXTURE", "MYSTERIOUS",
                         "motion,comb,sweeping,drone",
                         "A drone with a filter that has decided to wander on its own.")
            .at (43, 2, 0.72f, 9.0)
            .chain ("RETRO,FILTER,SPACE,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.54f)
            .v (PID::driftAmount, 0.44f).v (PID::driftRate, 0.05f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.58f)
            .v (PID::oscAUnison, 4.0f).v (PID::oscADetune, 0.36f)
            .v (PID::oscASpread, 0.86f).v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tAsym)
            .v (PID::oscBWtPos, 0.50f).v (PID::oscBLevel, 0.40f)
            .v (PID::oscBOctave, 0.0f).v (PID::oscBFine, -9.0f)
            .v (PID::oscCWave, ch::tri).v (PID::oscCLevel, 0.14f)
            .v (PID::oscCOctave, 1.0f).v (PID::oscCSemi, 7.0f)
            .v (PID::subLevel, 0.08f)
            .v (PID::noiseType, ch::nDark).v (PID::noiseLevel, 0.14f)
            .v (PID::bodyAmount, 0.30f).v (PID::densityAmount, 0.36f)
            .v (PID::preFilterDrive, 0.18f).v (PID::postSaturation, 0.16f)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1700.0f).v (PID::filterResonance, 0.48f)
            .v (PID::filterKeyTrack, 0.35f).v (PID::filterEnvAmount, 0.30f)
            .v (PID::ampAttack, 1.6f).v (PID::ampDecay, 5.0f)
            .v (PID::ampSustain, 0.84f).v (PID::ampRelease, 4.0f)
            .v (PID::ampVelocity, 0.28f)
            .v (PID::macroMemory, 0.44f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.50f).v (PID::memoryWobble, 0.42f)
            .v (PID::memoryDiffusion, 0.62f).v (PID::memoryAsymmetry, 0.44f)
            .v (PID::macroCharacter, 0.38f).v (PID::macroMotion, 0.84f)
            .v (PID::macroWorld, 0.60f).v (PID::macroWeight, 0.28f)
            .v (PID::retroEra, 0.58f).v (PID::retroAge, 0.34f)
            .v (PID::retroDrift, 0.44f).v (PID::retroWear, 0.22f)
            .v (PID::retroTone, -0.14f).v (PID::retroNoise, 0.18f)
            .v (PID::retroMix, 0.60f)
            .v (PID::fxFilterMode, ch::f2Bp).v (PID::fxFilterCutoff, 2400.0f)
            .v (PID::fxFilterRes, 0.44f).v (PID::fxFilterMorph, 0.55f)
            .v (PID::fxFilterMotion, 0.86f).v (PID::fxFilterDrive, 0.18f)
            .v (PID::fxFilterMix, 0.70f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.50f)
            .v (PID::spaceSize, 0.70f).v (PID::spaceDecay, 6.0f)
            .v (PID::spaceFog, 0.60f).v (PID::spaceLight, -0.18f)
            .v (PID::spaceMix, 0.38f)
            .v (PID::auraSize, 0.68f).v (PID::auraDistance, 0.42f)
            .v (PID::auraFog, 0.60f).v (PID::auraDecay, 0.62f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.08f)
            .v (PID::patinaNoise, 0.18f).v (PID::patinaWear, 0.34f)
            .v (PID::patinaDrift, 0.48f)
            .v (PID::synthWidth, 1.25f).v (PID::highWidth, 1.30f)
            .v (PID::breathAmount, 0.74f).v (PID::breathSpeed, 0.08f)
            .v (PID::breathRandom, 0.78f).v (PID::breathShape, 0.40f)
            .v (PID::lfo1Shape, ch::lfoTri).v (PID::lfo1Rate, 0.08f)
            .v (PID::lfo1Depth, 0.70f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.19f)
            .v (PID::lfo2Depth, 0.60f)
            .route (srcLfo1, PID::filterCutoff, 0.20f)
            .route (srcLfo2, PID::fxFilterCutoff, 0.22f)
            .route (srcBreath, PID::filterResonance, 0.14f));

        // DIGITAL noise, a notch that moves, and Rewind in DIVE mode, which
        // falls three octaves and is still moving when the window ends.
        add (out, Build ("Shortwave Static", "TEXTURE", "BROKEN",
                         "static,dive,notch,interference",
                         "Tuning across a band at night and catching the edge of something.")
            .at (46, 1, 0.80f, 7.0)
            .chain ("CRUSH,FILTER,REWIND,RETRO,GRAIN,SPACE")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.46f)
            .v (PID::driftAmount, 0.40f).v (PID::driftRate, 0.60f)
            .v (PID::oscAWave, ch::square).v (PID::oscALevel, 0.24f)
            .v (PID::oscAPulseWidth, 0.14f)
            .v (PID::oscBWave, ch::saw).v (PID::oscBLevel, 0.18f)
            .v (PID::oscBSemi, -7.0f).v (PID::oscBFine, 19.0f)
            .v (PID::oscRingMod, 0.34f)
            .v (PID::subLevel, 0.06f)
            .v (PID::noiseType, ch::nDigital).v (PID::noiseLevel, 0.56f)
            .v (PID::bodyAmount, 0.12f).v (PID::densityAmount, 0.18f)
            .v (PID::preFilterDrive, 0.22f).v (PID::postSaturation, 0.20f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::notch)
            .v (PID::filterCutoff, 2000.0f).v (PID::filterResonance, 0.46f)
            .v (PID::filterKeyTrack, 0.20f).v (PID::filterEnvAmount, 0.30f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Bp)
            .v (PID::filter2Cutoff, 3200.0f).v (PID::filter2Res, 0.52f)
            .v (PID::filter2Mix, 0.60f)
            .v (PID::ampAttack, 0.30f).v (PID::ampDecay, 2.0f)
            .v (PID::ampSustain, 0.88f).v (PID::ampRelease, 1.2f)
            .v (PID::ampVelocity, 0.30f)
            .v (PID::macroMemory, 0.58f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.60f).v (PID::memoryWobble, 0.54f)
            .v (PID::memoryDiffusion, 0.40f).v (PID::memoryAsymmetry, 0.62f)
            .v (PID::macroCharacter, 0.60f).v (PID::macroMotion, 0.76f)
            .v (PID::macroWorld, 0.32f).v (PID::macroWeight, 0.20f)
            .v (PID::macroAlter, 0.50f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.52f)
            .v (PID::crushBits, 7.0f).v (PID::crushRate, 11000.0f)
            .v (PID::crushJitter, 0.56f).v (PID::crushDrive, 0.26f)
            .v (PID::crushTone, 0.14f).v (PID::crushMix, 0.66f)
            .v (PID::rewindOn, 1.0f).v (PID::rewindMode, ch::rDive)
            .v (PID::rewindDivision, ch::rw2).v (PID::rewindSync, 1.0f)
            .v (PID::rewindCurve, 0.70f).v (PID::rewindSpeed, 1.4f)
            .v (PID::rewindTail, 0.44f).v (PID::rewindMix, 0.38f)
            .v (PID::retroEra, 0.82f).v (PID::retroAge, 0.50f)
            .v (PID::retroDrift, 0.40f).v (PID::retroWear, 0.60f)
            .v (PID::retroTone, -0.06f).v (PID::retroNoise, 0.32f)
            .v (PID::retroMix, 0.84f)
            .v (PID::fxFilterCutoff, 8200.0f).v (PID::fxFilterRes, 0.26f)
            .v (PID::fxFilterMotion, 0.44f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.46f)
            .v (PID::spaceSize, 0.50f).v (PID::spaceDecay, 3.6f)
            .v (PID::spaceFog, 0.56f).v (PID::spaceLight, -0.20f)
            .v (PID::spaceMix, 0.24f)
            .v (PID::auraSize, 0.48f).v (PID::auraDistance, 0.34f)
            .v (PID::auraFog, 0.58f).v (PID::auraDecay, 0.44f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaNoise, 0.34f)
            .v (PID::patinaWear, 0.54f).v (PID::patinaDrift, 0.50f)
            .v (PID::synthWidth, 1.20f).v (PID::highWidth, 1.30f)
            .v (PID::breathAmount, 0.66f).v (PID::breathSpeed, 0.60f)
            .v (PID::breathRandom, 0.90f).v (PID::breathShape, 0.75f)
            .v (PID::lfo2Shape, ch::lfoRandom).v (PID::lfo2Rate, 3.2f)
            .v (PID::lfo2Depth, 0.70f)
            .route (srcLfo2, PID::filterCutoff, 0.22f)
            .route (srcOrganic, PID::filter2Cutoff, 0.30f)
            .route (srcBreath, PID::noiseLevel, 0.20f));

        // Earliest machine, deepest wear: RETRO generating the content and
        // Memory taking it round twice.
        add (out, Build ("Óxido de Cinta", "TEXTURE", "WARM",
                         "tape,oxide,wear,bed",
                         "Earliest-machine RETRO at high age and wear over a pink-noise bed, put through two generations of Memory, for laying under a mix.")
            .at (38, 1, 0.78f, 5.0)
            .chain ("RETRO,SPACE,FILTER,CRUSH,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.52f)
            .v (PID::driftAmount, 0.42f).v (PID::driftRate, 0.09f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.18f)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.12f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, 9.0f)
            .v (PID::subLevel, 0.14f).v (PID::subHarmonics, 0.22f)
            .v (PID::noiseType, ch::nPink).v (PID::noiseLevel, 0.72f)
            .v (PID::bodyAmount, 0.42f).v (PID::densityAmount, 0.34f)
            .v (PID::preFilterDrive, 0.26f).v (PID::postSaturation, 0.28f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1500.0f).v (PID::filterResonance, 0.22f)
            .v (PID::filterKeyTrack, 0.15f).v (PID::filterEnvAmount, 0.10f)
            .v (PID::ampAttack, 0.55f).v (PID::ampDecay, 2.6f)
            .v (PID::ampSustain, 0.92f).v (PID::ampRelease, 2.0f)
            .v (PID::ampVelocity, 0.20f)
            .v (PID::macroMemory, 0.54f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.72f).v (PID::memoryWobble, 0.50f)
            .v (PID::memoryDiffusion, 0.34f).v (PID::memoryAsymmetry, 0.46f)
            .v (PID::macroCharacter, 0.72f).v (PID::macroMotion, 0.46f)
            .v (PID::macroWorld, 0.30f).v (PID::macroWeight, 0.32f)
            .v (PID::retroEra, 0.08f).v (PID::retroAge, 0.88f)
            .v (PID::retroDrift, 0.60f).v (PID::retroWear, 0.72f)
            .v (PID::retroTone, -0.34f).v (PID::retroNoise, 0.58f)
            .v (PID::fxFilterCutoff, 3600.0f).v (PID::fxFilterRes, 0.10f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.34f)
            .v (PID::spaceSize, 0.40f).v (PID::spaceDecay, 2.4f)
            .v (PID::spaceFog, 0.50f).v (PID::spaceLight, -0.42f)
            .v (PID::spaceMix, 0.20f)
            .v (PID::auraSize, 0.38f).v (PID::auraDistance, 0.28f)
            .v (PID::auraFog, 0.54f).v (PID::auraDecay, 0.36f)
            .v (PID::auraLight, -0.34f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.30f)
            .v (PID::patinaNoise, 0.52f).v (PID::patinaWear, 0.62f)
            .v (PID::patinaDrift, 0.46f)
            .v (PID::synthWidth, 1.05f).v (PID::highWidth, 1.10f)
            .v (PID::breathAmount, 0.54f).v (PID::breathSpeed, 0.13f)
            .v (PID::breathRandom, 0.72f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.11f)
            .v (PID::lfo2Depth, 0.58f)
            .route (srcBreath, PID::retroWear, 0.18f)
            .route (srcLfo2, PID::memoryWobble, 0.14f)
            .route (srcOrganic, PID::retroNoise, 0.12f));

        // Vinyl surface: dust noise band-passed to a groove, PATINA on
        // CUSTOM doing the eroding, Memory left at the first copy.
        add (out, Build ("Surco Muerto", "TEXTURE", "NOSTALGIC",
                         "vinyl,surface,dust,crackle",
                         "Dust noise band-passed to a surface with PATINA on CUSTOM at high wear and RETRO held at the first generation.")
            .at (36, 1, 0.76f, 5.5)
            .chain ("FILTER,RETRO,GRAIN,SPACE,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 3.0f).v (PID::voiceVariation, 0.44f)
            .v (PID::driftAmount, 0.18f).v (PID::driftRate, 0.06f)
            .v (PID::oscAWave, ch::sine).v (PID::oscALevel, 0.20f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.10f)
            .v (PID::oscBFine, -11.0f)
            .v (PID::subLevel, 0.26f).v (PID::subHarmonics, 0.34f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.74f)
            .v (PID::bodyAmount, 0.46f).v (PID::bodyTilt, -0.24f)
            .v (PID::densityAmount, 0.30f)
            .v (PID::preFilterDrive, 0.20f).v (PID::postSaturation, 0.22f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 1250.0f).v (PID::filterResonance, 0.26f)
            .v (PID::filterKeyTrack, 0.10f).v (PID::filterEnvAmount, 0.08f)
            .v (PID::filterVelAmount, 0.12f)
            .v (PID::ampAttack, 0.40f).v (PID::ampDecay, 2.2f)
            .v (PID::ampSustain, 0.94f).v (PID::ampRelease, 1.6f)
            .v (PID::ampVelocity, 0.18f)
            .v (PID::macroMemory, 0.30f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.44f).v (PID::memoryWobble, 0.18f)
            .v (PID::memoryDiffusion, 0.22f).v (PID::memoryAsymmetry, 0.30f)
            .v (PID::macroCharacter, 0.64f).v (PID::macroMotion, 0.30f)
            .v (PID::macroWorld, 0.24f).v (PID::macroWeight, 0.40f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.40f)
            .v (PID::retroEra, 0.32f).v (PID::retroAge, 0.80f)
            .v (PID::retroDrift, 0.16f).v (PID::retroWear, 0.84f)
            .v (PID::retroTone, -0.20f).v (PID::retroNoise, 0.44f)
            .v (PID::retroMix, 0.88f)
            .v (PID::fxFilterMode, ch::f2Hp).v (PID::fxFilterCutoff, 38.0f)
            .v (PID::fxFilterRes, 0.08f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.26f)
            .v (PID::spaceSize, 0.30f).v (PID::spaceDecay, 1.4f)
            .v (PID::spaceFog, 0.36f).v (PID::spaceLight, -0.30f)
            .v (PID::spacePreDelay, 12.0f).v (PID::spaceMix, 0.16f)
            .v (PID::auraSize, 0.30f).v (PID::auraDistance, 0.22f)
            .v (PID::auraFog, 0.44f).v (PID::auraDecay, 0.28f)
            .v (PID::auraLight, -0.26f)
            .v (PID::patinaProfile, ch::pCustom).v (PID::patinaTone, -0.22f)
            .v (PID::patinaNoise, 0.60f).v (PID::patinaWear, 0.76f)
            .v (PID::patinaDrift, 0.18f)
            .v (PID::synthWidth, 0.90f).v (PID::lowMonoFreq, 150.0f)
            .v (PID::highWidth, 1.05f)
            .v (PID::breathAmount, 0.40f).v (PID::breathSpeed, 0.09f)
            .v (PID::breathRandom, 0.58f)
            .v (PID::lfo1Shape, ch::lfoRandom).v (PID::lfo1Rate, 5.5f)
            .v (PID::lfo1Depth, 0.45f)
            .route (srcLfo1, PID::patinaNoise, 0.16f)
            .route (srcOrganic, PID::retroWear, 0.20f)
            .route (srcBreath, PID::filterCutoff, 0.10f));

        // Wow and flutter promoted from artefact to content, with SPACE
        // ahead of RETRO so the tail is what gets dragged.
        add (out, Build ("Tercera Generación", "TEXTURE", "HAUNTED",
                         "tape,wow,flutter,generation",
                         "Wow and flutter as the content: RETRO drift and Memory wobble at generation III, with the reverb ahead of the tape so the tail ages too.")
            .at (43, 2, 0.74f, 6.0)
            .chain ("SPACE,RETRO,FILTER,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 5.0f).v (PID::voiceVariation, 0.58f)
            .v (PID::driftAmount, 0.56f).v (PID::driftRate, 0.22f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tHollow)
            .v (PID::oscAWtPos, 0.38f).v (PID::oscALevel, 0.34f)
            .v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.22f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, 14.0f)
            .v (PID::subLevel, 0.10f)
            .v (PID::noiseType, ch::nTexture).v (PID::noiseLevel, 0.58f)
            .v (PID::bodyAmount, 0.36f).v (PID::densityAmount, 0.38f)
            .v (PID::preFilterDrive, 0.22f).v (PID::postSaturation, 0.24f)
            .v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 2600.0f).v (PID::filterResonance, 0.18f)
            .v (PID::filterKeyTrack, 0.25f)
            .v (PID::ampAttack, 0.9f).v (PID::ampDecay, 3.4f)
            .v (PID::ampSustain, 0.90f).v (PID::ampRelease, 2.8f)
            .v (PID::ampVelocity, 0.22f)
            .v (PID::macroMemory, 0.76f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.78f).v (PID::memoryWobble, 0.82f)
            .v (PID::memoryDiffusion, 0.56f).v (PID::memoryAsymmetry, 0.66f)
            .v (PID::macroCharacter, 0.62f).v (PID::macroMotion, 0.80f)
            .v (PID::macroWorld, 0.46f).v (PID::macroWeight, 0.26f)
            .v (PID::retroEra, 0.46f).v (PID::retroAge, 0.62f)
            .v (PID::retroDrift, 0.86f).v (PID::retroWear, 0.48f)
            .v (PID::retroTone, -0.22f).v (PID::retroNoise, 0.36f)
            .v (PID::fxFilterCutoff, 5200.0f).v (PID::fxFilterMotion, 0.34f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.48f)
            .v (PID::spaceSize, 0.62f).v (PID::spaceDecay, 4.2f)
            .v (PID::spaceFog, 0.62f).v (PID::spaceLight, -0.24f)
            .v (PID::spacePreDelay, 34.0f).v (PID::spaceMix, 0.40f)
            .v (PID::auraSize, 0.56f).v (PID::auraDistance, 0.38f)
            .v (PID::auraFog, 0.62f).v (PID::auraDecay, 0.54f)
            .v (PID::auraLight, -0.20f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.18f)
            .v (PID::patinaNoise, 0.34f).v (PID::patinaWear, 0.44f)
            .v (PID::patinaDrift, 0.66f)
            .v (PID::synthWidth, 1.20f).v (PID::highWidth, 1.25f)
            .v (PID::breathAmount, 0.68f).v (PID::breathSpeed, 0.17f)
            .v (PID::breathRandom, 0.74f).v (PID::breathShape, 0.42f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.45f)
            .v (PID::lfo1Depth, 0.60f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.07f)
            .v (PID::lfo2Depth, 0.66f)
            .route (srcLfo1, PID::memoryWobble, 0.22f)
            .route (srcLfo2, PID::retroDrift, 0.20f)
            .route (srcBreath, PID::oscAWtPos, 0.26f)
            .route (srcOrganic, PID::retroAge, 0.14f));

        // The gentle end of CRUSH: ten bits, a trace of jitter, and the
        // bottom taken off so it will sit over anything.
        add (out, Build ("Polvo de Bits", "TEXTURE", "MINIMAL",
                         "crush,digital,dust,minimal",
                         "Ten-bit CRUSH with a trace of jitter over DIGITAL noise, band-passed narrow and high-passed at 260 Hz.")
            .at (48, 1, 0.76f, 4.5)
            .chain ("CRUSH,RETRO,FILTER,GRAIN,SPACE,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.34f)
            .v (PID::driftAmount, 0.16f).v (PID::driftRate, 0.20f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tDark)
            .v (PID::oscAWtPos, 0.22f).v (PID::oscALevel, 0.30f)
            .v (PID::oscBWave, ch::square).v (PID::oscBLevel, 0.14f)
            .v (PID::oscBPulseWidth, 0.30f).v (PID::oscBOctave, 1.0f)
            .v (PID::subLevel, 0.08f)
            .v (PID::noiseType, ch::nDigital).v (PID::noiseLevel, 0.62f)
            .v (PID::bodyAmount, 0.18f).v (PID::densityAmount, 0.20f)
            .v (PID::postSaturation, 0.10f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 3000.0f).v (PID::filterResonance, 0.28f)
            .v (PID::filterKeyTrack, 0.30f)
            .v (PID::ampAttack, 0.25f).v (PID::ampDecay, 1.8f)
            .v (PID::ampSustain, 0.90f).v (PID::ampRelease, 1.2f)
            .v (PID::ampVelocity, 0.20f)
            .v (PID::macroMemory, 0.18f).v (PID::memoryBandwidth, 0.30f)
            .v (PID::macroCharacter, 0.26f).v (PID::macroMotion, 0.32f)
            .v (PID::macroWorld, 0.22f).v (PID::macroWeight, 0.18f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.34f)
            .v (PID::crushBits, 10.0f).v (PID::crushRate, 18000.0f)
            .v (PID::crushJitter, 0.14f).v (PID::crushDrive, 0.16f)
            .v (PID::crushTone, 0.10f).v (PID::crushMix, 0.72f)
            .v (PID::retroEra, 0.94f).v (PID::retroAge, 0.12f)
            .v (PID::retroDrift, 0.08f).v (PID::retroWear, 0.08f)
            .v (PID::retroTone, 0.06f).v (PID::retroNoise, 0.06f)
            .v (PID::retroMix, 0.30f)
            .v (PID::fxFilterMode, ch::f2Hp).v (PID::fxFilterCutoff, 260.0f)
            .v (PID::fxFilterRes, 0.14f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.24f)
            .v (PID::spaceSize, 0.28f).v (PID::spaceDecay, 1.2f)
            .v (PID::spaceFog, 0.30f).v (PID::spaceLight, 0.12f)
            .v (PID::spaceMix, 0.14f)
            .v (PID::auraSize, 0.26f).v (PID::auraDistance, 0.20f)
            .v (PID::auraFog, 0.26f).v (PID::auraDecay, 0.24f)
            .v (PID::auraLight, 0.10f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.14f)
            .v (PID::patinaNoise, 0.12f).v (PID::patinaWear, 0.14f)
            .v (PID::patinaDrift, 0.10f)
            .v (PID::synthWidth, 1.15f).v (PID::highWidth, 1.25f)
            .v (PID::masterGain, 1.5f)
            .v (PID::breathAmount, 0.28f).v (PID::breathSpeed, 0.34f)
            .v (PID::lfo2Shape, ch::lfoRandom).v (PID::lfo2Rate, 2.2f)
            .v (PID::lfo2Depth, 0.40f)
            .route (srcLfo2, PID::crushRate, 0.18f)
            .route (srcOrganic, PID::crushJitter, 0.16f)
            .route (srcBreath, PID::filterCutoff, 0.12f));

        // CRUSH used for its sample rate rather than its bits: the chain
        // filter puts a band at 3.4 kHz in front of a 4.2 kHz decimator,
        // so what comes back is the fold, not the band.
        add (out, Build ("Lija Fina", "TEXTURE", "COLD",
                         "crush,aliasing,rate,surface",
                         "CRUSH working on the sample rate rather than the bits - white noise band-passed at 3.4 kHz and then decimated to 4.2 kHz.")
            .at (52, 1, 0.78f, 4.5)
            .chain ("FILTER,CRUSH,RETRO,GRAIN,SPACE,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.30f)
            .v (PID::driftAmount, 0.14f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.26f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.18f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tSpectral)
            .v (PID::oscBWtPos, 0.72f).v (PID::oscBLevel, 0.20f)
            .v (PID::oscBSemi, 7.0f)
            .v (PID::noiseType, ch::nWhite).v (PID::noiseLevel, 0.68f)
            .v (PID::bodyAmount, 0.12f).v (PID::densityAmount, 0.18f)
            .v (PID::preFilterDrive, 0.14f)
            .v (PID::postSaturation, 0.14f).v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::hp)
            .v (PID::filterCutoff, 900.0f).v (PID::filterResonance, 0.30f)
            .v (PID::filterKeyTrack, 0.20f)
            .v (PID::ampAttack, 0.18f).v (PID::ampDecay, 1.6f)
            .v (PID::ampSustain, 0.92f).v (PID::ampRelease, 0.9f)
            .v (PID::ampVelocity, 0.18f)
            .v (PID::macroMemory, 0.20f).v (PID::memoryBandwidth, 0.26f)
            .v (PID::macroCharacter, 0.44f).v (PID::macroMotion, 0.36f)
            .v (PID::macroWorld, 0.20f).v (PID::macroWeight, 0.14f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.62f)
            .v (PID::crushBits, 14.0f).v (PID::crushRate, 4200.0f)
            .v (PID::crushJitter, 0.24f).v (PID::crushDrive, 0.22f)
            .v (PID::crushTone, 0.32f).v (PID::crushMix, 0.84f)
            .v (PID::retroEra, 0.86f).v (PID::retroAge, 0.20f)
            .v (PID::retroDrift, 0.10f).v (PID::retroWear, 0.14f)
            .v (PID::retroTone, 0.10f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.26f)
            .v (PID::fxFilterMode, ch::f2Bp).v (PID::fxFilterCutoff, 3400.0f)
            .v (PID::fxFilterRes, 0.22f).v (PID::fxFilterMorph, 0.30f)
            .v (PID::fxFilterMix, 0.80f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.36f)
            .v (PID::spaceSize, 0.34f).v (PID::spaceDecay, 1.8f)
            .v (PID::spaceFog, 0.34f).v (PID::spaceLight, 0.24f)
            .v (PID::spaceMix, 0.18f)
            .v (PID::auraSize, 0.32f).v (PID::auraDistance, 0.26f)
            .v (PID::auraFog, 0.28f).v (PID::auraDecay, 0.30f)
            .v (PID::auraLight, 0.26f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.22f)
            .v (PID::patinaNoise, 0.14f).v (PID::patinaWear, 0.20f)
            .v (PID::patinaDrift, 0.12f)
            .v (PID::synthWidth, 1.25f).v (PID::highWidth, 1.35f)
            .v (PID::lowMonoFreq, 200.0f)
            .v (PID::breathAmount, 0.30f).v (PID::breathSpeed, 0.50f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Rate, 0.35f)
            .v (PID::lfo1Depth, 0.55f)
            .route (srcLfo1, PID::crushRate, 0.26f)
            .route (srcBreath, PID::fxFilterCutoff, 0.16f)
            .route (srcOrganic, PID::oscBWtPos, 0.18f));

        // The destroyed end: three bits driven hard, with REWIND on STOP
        // immediately behind the quantiser rather than at the end.
        add (out, Build ("Tela Quemada", "TEXTURE", "AGGRESSIVE",
                         "crush,destroyed,glitch,broken",
                         "Three-bit CRUSH driven hard, REWIND on STOP behind it and Memory at generation IV: a destroyed digital surface.")
            .at (40, 1, 0.82f, 4.5)
            .chain ("CRUSH,REWIND,FILTER,RETRO,SPACE,GRAIN")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::mono)
            .v (PID::voiceVariation, 0.50f)
            .v (PID::driftAmount, 0.30f).v (PID::driftRate, 0.80f)
            .v (PID::oscAWave, ch::square).v (PID::oscALevel, 0.44f)
            .v (PID::oscAPulseWidth, 0.18f).v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::saw).v (PID::oscBLevel, 0.30f)
            .v (PID::oscBSemi, -5.0f).v (PID::oscBFine, 27.0f)
            .v (PID::oscRingMod, 0.42f).v (PID::oscSync, 0.30f)
            .v (PID::noiseType, ch::nDigital).v (PID::noiseLevel, 0.46f)
            .v (PID::bodyAmount, 0.20f).v (PID::densityAmount, 0.24f)
            .v (PID::preFilterDrive, 0.36f)
            .v (PID::postSaturation, 0.34f).v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 3200.0f).v (PID::filterResonance, 0.34f)
            .v (PID::filterDrive, 0.42f).v (PID::filterKeyTrack, 0.20f)
            .v (PID::ampAttack, 0.02f).v (PID::ampDecay, 1.4f)
            .v (PID::ampSustain, 0.86f).v (PID::ampRelease, 0.6f)
            .v (PID::ampVelocity, 0.24f)
            .v (PID::macroMemory, 0.66f).v (PID::memoryGen, ch::genIV)
            .v (PID::memoryBandwidth, 0.58f).v (PID::memoryWobble, 0.62f)
            .v (PID::memoryDiffusion, 0.36f).v (PID::memoryAsymmetry, 0.70f)
            .v (PID::macroCharacter, 0.84f).v (PID::macroMotion, 0.72f)
            .v (PID::macroWorld, 0.26f).v (PID::macroWeight, 0.30f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.90f)
            .v (PID::crushBits, 3.0f).v (PID::crushRate, 1400.0f)
            .v (PID::crushJitter, 0.62f).v (PID::crushDrive, 0.70f)
            .v (PID::crushTone, -0.10f).v (PID::crushMix, 1.0f)
            .v (PID::rewindOn, 1.0f).v (PID::rewindMode, ch::rStop)
            .v (PID::rewindDivision, ch::rw8).v (PID::rewindCurve, 0.30f)
            .v (PID::rewindSpeed, 0.6f).v (PID::rewindTail, 0.56f)
            .v (PID::rewindMix, 0.50f)
            .v (PID::retroEra, 0.70f).v (PID::retroAge, 0.56f)
            .v (PID::retroDrift, 0.34f).v (PID::retroWear, 0.62f)
            .v (PID::retroTone, -0.12f).v (PID::retroNoise, 0.24f)
            .v (PID::retroMix, 0.66f)
            .v (PID::fxFilterCutoff, 6000.0f).v (PID::fxFilterRes, 0.20f)
            .v (PID::fxFilterDrive, 0.26f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.22f)
            .v (PID::spaceSize, 0.26f).v (PID::spaceDecay, 1.0f)
            .v (PID::spaceFog, 0.28f).v (PID::spaceLight, -0.10f)
            .v (PID::spaceMix, 0.12f)
            .v (PID::auraSize, 0.24f).v (PID::auraDistance, 0.18f)
            .v (PID::auraFog, 0.30f).v (PID::auraDecay, 0.22f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.16f)
            .v (PID::patinaNoise, 0.26f).v (PID::patinaWear, 0.50f)
            .v (PID::patinaDrift, 0.34f)
            .v (PID::synthWidth, 1.05f).v (PID::masterGain, -4.0f)
            .v (PID::breathAmount, 0.44f).v (PID::breathSpeed, 1.1f)
            .v (PID::breathRandom, 0.88f).v (PID::breathShape, 0.82f)
            .v (PID::lfo2Shape, ch::lfoRandom).v (PID::lfo2Rate, 7.0f)
            .v (PID::lfo2Depth, 0.72f)
            .route (srcLfo2, PID::crushBits, -0.24f)
            .route (srcOrganic, PID::crushRate, 0.30f)
            .route (srcBreath, PID::rewindSpeed, 0.20f)
            .route (srcMemory, PID::filterCutoff, -0.18f));

        // Nine-millisecond grains at seventy a second: the grain train is
        // the whole source, and a FORMANT chain filter sits after it.
        add (out, Build ("Grano Fino", "TEXTURE", "AIRY",
                         "granular,hann,dense,surface",
                         "GRAIN at 9 ms and 70 grains a second through a HANN window over AIR noise, with a FORMANT chain filter after it.")
            .at (55, 1, 0.76f, 5.0)
            .chain ("GRAIN,FILTER,RETRO,CRUSH,SPACE,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 5.0f).v (PID::voiceVariation, 0.38f)
            .v (PID::driftAmount, 0.22f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tSpectral)
            .v (PID::oscAWtPos, 0.44f).v (PID::oscALevel, 0.42f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.20f)
            .v (PID::oscASpread, 0.70f)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.18f)
            .v (PID::oscBOctave, 1.0f)
            .v (PID::noiseType, ch::nAir).v (PID::noiseLevel, 0.52f)
            .v (PID::bodyAmount, 0.14f).v (PID::densityAmount, 0.22f)
            .v (PID::postSaturation, 0.10f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 4200.0f).v (PID::filterResonance, 0.20f)
            .v (PID::filterKeyTrack, 0.40f)
            .v (PID::ampAttack, 0.35f).v (PID::ampDecay, 2.4f)
            .v (PID::ampSustain, 0.92f).v (PID::ampRelease, 1.8f)
            .v (PID::ampVelocity, 0.20f)
            .v (PID::macroMemory, 0.24f).v (PID::memoryBandwidth, 0.34f)
            .v (PID::macroCharacter, 0.28f).v (PID::macroMotion, 0.66f)
            .v (PID::macroWorld, 0.48f).v (PID::macroWeight, 0.16f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.70f)
            .v (PID::grainSize, 9.0f).v (PID::grainDensity, 70.0f)
            .v (PID::grainPosition, 0.18f).v (PID::grainPitchMode, ch::gRoot)
            .v (PID::grainSpread, 0.78f).v (PID::grainJitter, 0.40f)
            .v (PID::grainDirection, 0.10f).v (PID::grainWindow, ch::wHann)
            .v (PID::grainFeedback, 0.22f).v (PID::grainMix, 0.82f)
            .v (PID::retroEra, 0.74f).v (PID::retroAge, 0.24f)
            .v (PID::retroDrift, 0.18f).v (PID::retroWear, 0.12f)
            .v (PID::retroTone, 0.08f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.28f)
            .v (PID::fxFilterMode, ch::f2Formant).v (PID::fxFilterCutoff, 1800.0f)
            .v (PID::fxFilterRes, 0.28f).v (PID::fxFilterMorph, 0.35f)
            .v (PID::fxFilterMix, 0.55f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.42f)
            .v (PID::spaceSize, 0.54f).v (PID::spaceDecay, 3.0f)
            .v (PID::spaceFog, 0.44f).v (PID::spaceLight, 0.30f)
            .v (PID::spacePreDelay, 18.0f).v (PID::spaceMix, 0.26f)
            .v (PID::auraSize, 0.52f).v (PID::auraDistance, 0.34f)
            .v (PID::auraFog, 0.36f).v (PID::auraDecay, 0.44f)
            .v (PID::auraLight, 0.30f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, 0.10f)
            .v (PID::patinaNoise, 0.14f).v (PID::patinaWear, 0.16f)
            .v (PID::patinaDrift, 0.16f)
            .v (PID::synthWidth, 1.30f).v (PID::highWidth, 1.40f)
            .v (PID::lowMonoFreq, 180.0f)
            .v (PID::breathAmount, 0.44f).v (PID::breathSpeed, 0.30f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Rate, 0.30f)
            .v (PID::lfo1Depth, 0.60f)
            .route (srcLfo1, PID::grainPosition, 0.30f)
            .route (srcBreath, PID::grainSize, 0.18f)
            .route (srcOrganic, PID::grainJitter, 0.20f));

        // The same idea through a GAUSS window, and granulated before the
        // reverb rather than after it.
        add (out, Build ("Arena Suspendida", "TEXTURE", "DREAMY",
                         "granular,gauss,suspended,bed",
                         "GRAIN through a GAUSS window at 16 ms, spread wide with heavy jitter, granulated before the reverb rather than after.")
            .at (50, 2, 0.74f, 6.0)
            .chain ("GRAIN,SPACE,FILTER,RETRO,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.46f)
            .v (PID::driftAmount, 0.30f).v (PID::driftRate, 0.08f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tSoft)
            .v (PID::oscAWtPos, 0.30f).v (PID::oscALevel, 0.46f)
            .v (PID::oscAUnison, 3.0f).v (PID::oscADetune, 0.24f)
            .v (PID::oscASpread, 0.72f).v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.24f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, 11.0f)
            .v (PID::subLevel, 0.10f)
            .v (PID::noiseType, ch::nAir).v (PID::noiseLevel, 0.40f)
            .v (PID::bodyAmount, 0.26f).v (PID::densityAmount, 0.30f)
            .v (PID::postSaturation, 0.12f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 3400.0f).v (PID::filterResonance, 0.16f)
            .v (PID::filterKeyTrack, 0.30f)
            .v (PID::ampAttack, 1.0f).v (PID::ampDecay, 3.0f)
            .v (PID::ampSustain, 0.92f).v (PID::ampRelease, 3.2f)
            .v (PID::ampVelocity, 0.20f)
            .v (PID::macroMemory, 0.34f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.42f).v (PID::memoryWobble, 0.30f)
            .v (PID::memoryDiffusion, 0.58f)
            .v (PID::macroCharacter, 0.30f).v (PID::macroMotion, 0.58f)
            .v (PID::macroWorld, 0.62f).v (PID::macroWeight, 0.22f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.62f)
            .v (PID::grainSize, 16.0f).v (PID::grainDensity, 62.0f)
            .v (PID::grainPosition, 0.44f).v (PID::grainPitchMode, ch::gOctave)
            .v (PID::grainSpread, 0.88f).v (PID::grainJitter, 0.62f)
            .v (PID::grainDirection, 0.34f).v (PID::grainWindow, ch::wGauss)
            .v (PID::grainFeedback, 0.30f).v (PID::grainMix, 0.74f)
            .v (PID::retroEra, 0.52f).v (PID::retroAge, 0.30f)
            .v (PID::retroDrift, 0.26f).v (PID::retroWear, 0.16f)
            .v (PID::retroTone, -0.10f).v (PID::retroNoise, 0.16f)
            .v (PID::retroMix, 0.40f)
            .v (PID::fxFilterCutoff, 7000.0f).v (PID::fxFilterRes, 0.10f)
            .v (PID::fxFilterMotion, 0.22f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.56f)
            .v (PID::spaceSize, 0.74f).v (PID::spaceDecay, 6.5f)
            .v (PID::spaceFog, 0.66f).v (PID::spaceLight, 0.10f)
            .v (PID::spacePreDelay, 40.0f).v (PID::spaceMix, 0.42f)
            .v (PID::auraSize, 0.70f).v (PID::auraDistance, 0.44f)
            .v (PID::auraFog, 0.56f).v (PID::auraDecay, 0.66f)
            .v (PID::auraLight, 0.14f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.06f)
            .v (PID::patinaNoise, 0.18f).v (PID::patinaWear, 0.20f)
            .v (PID::patinaDrift, 0.30f)
            .v (PID::synthWidth, 1.35f).v (PID::highWidth, 1.45f)
            .v (PID::lowMonoFreq, 170.0f)
            .v (PID::breathAmount, 0.58f).v (PID::breathSpeed, 0.12f)
            .v (PID::breathRandom, 0.66f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.06f)
            .v (PID::lfo2Depth, 0.70f)
            .route (srcLfo2, PID::grainPosition, 0.34f)
            .route (srcBreath, PID::grainSpread, 0.20f)
            .route (srcOrganic, PID::grainDirection, 0.18f)
            .route (srcMotion, PID::oscAWtPos, 0.16f));

        // Seven-millisecond grains off an EXPO window, taken from dust
        // noise that has already been driven into the COMB model.
        add (out, Build ("Astilla", "TEXTURE", "BROKEN",
                         "granular,expo,comb,splinter",
                         "Seven-millisecond grains through an EXPO window, taken from dust noise driven into the COMB filter model.")
            .at (44, 1, 0.80f, 4.5)
            .chain ("FILTER,GRAIN,RETRO,CRUSH,REWIND,SPACE")
            .v (PID::synthCharacter, ch::mirage)
                .v (PID::masterGain, -2.3f)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.48f)
            .v (PID::driftAmount, 0.26f).v (PID::driftRate, 0.40f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.22f)
            .v (PID::oscBWave, ch::square).v (PID::oscBLevel, 0.14f)
            .v (PID::oscBPulseWidth, 0.22f).v (PID::oscBOctave, 1.0f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.70f)
            .v (PID::bodyAmount, 0.16f).v (PID::densityAmount, 0.20f)
            .v (PID::preFilterDrive, 0.24f)
            .v (PID::postSaturation, 0.18f).v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 1100.0f).v (PID::filterResonance, 0.66f)
            .v (PID::filterDrive, 0.30f).v (PID::filterKeyTrack, 0.60f)
            .v (PID::ampAttack, 0.06f).v (PID::ampDecay, 1.8f)
            .v (PID::ampSustain, 0.88f).v (PID::ampRelease, 0.8f)
            .v (PID::ampVelocity, 0.24f)
            .v (PID::macroMemory, 0.40f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.46f).v (PID::memoryWobble, 0.48f)
            .v (PID::memoryAsymmetry, 0.54f)
            .v (PID::macroCharacter, 0.48f).v (PID::macroMotion, 0.78f)
            .v (PID::macroWorld, 0.30f).v (PID::macroWeight, 0.20f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.84f)
            .v (PID::grainSize, 7.0f).v (PID::grainDensity, 76.0f)
            .v (PID::grainPosition, 0.22f).v (PID::grainPitchMode, ch::gThird)
            .v (PID::grainSpread, 0.66f).v (PID::grainJitter, 0.72f)
            .v (PID::grainDirection, 0.42f).v (PID::grainWindow, ch::wExpo)
            .v (PID::grainFeedback, 0.44f).v (PID::grainMix, 0.78f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.44f)
            .v (PID::crushBits, 8.0f).v (PID::crushRate, 12500.0f)
            .v (PID::crushJitter, 0.38f).v (PID::crushTone, 0.16f)
            .v (PID::crushMix, 0.52f)
            .v (PID::retroEra, 0.64f).v (PID::retroAge, 0.42f)
            .v (PID::retroDrift, 0.30f).v (PID::retroWear, 0.44f)
            .v (PID::retroTone, -0.08f).v (PID::retroNoise, 0.22f)
            .v (PID::retroMix, 0.54f)
            .v (PID::fxFilterMode, ch::f2Notch).v (PID::fxFilterCutoff, 2600.0f)
            .v (PID::fxFilterRes, 0.34f).v (PID::fxFilterMotion, 0.40f)
            .v (PID::fxFilterMix, 0.66f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.34f)
            .v (PID::spaceSize, 0.44f).v (PID::spaceDecay, 2.6f)
            .v (PID::spaceFog, 0.42f).v (PID::spaceLight, 0.06f)
            .v (PID::spaceMix, 0.22f)
            .v (PID::auraSize, 0.40f).v (PID::auraDistance, 0.28f)
            .v (PID::auraFog, 0.40f).v (PID::auraDecay, 0.34f)
            .v (PID::patinaProfile, ch::pCustom).v (PID::patinaTone, 0.06f)
            .v (PID::patinaNoise, 0.28f).v (PID::patinaWear, 0.48f)
            .v (PID::patinaDrift, 0.38f)
            .v (PID::synthWidth, 1.20f).v (PID::highWidth, 1.30f)
            .v (PID::breathAmount, 0.60f).v (PID::breathSpeed, 0.70f)
            .v (PID::breathRandom, 0.86f).v (PID::breathShape, 0.70f)
            .v (PID::lfo2Shape, ch::lfoRandom).v (PID::lfo2Rate, 4.5f)
            .v (PID::lfo2Depth, 0.64f)
            .route (srcLfo2, PID::grainSize, 0.22f)
            .route (srcOrganic, PID::grainPosition, 0.28f)
            .route (srcBreath, PID::filterCutoff, 0.18f));

        // A TUKEY window over an already-aged bed, with the grains mixed
        // under half: an under-layer with no transients of its own.
        add (out, Build ("Muselina", "TEXTURE", "ROMANTIC",
                         "granular,tukey,soft,bed",
                         "GRAIN through a TUKEY window at 22 ms over an aged, dark-filtered bed, for an under-layer with no transients of its own.")
            .at (47, 2, 0.70f, 6.0)
            .chain ("RETRO,GRAIN,FILTER,SPACE,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.40f)
            .v (PID::driftAmount, 0.28f).v (PID::driftRate, 0.07f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tSoft)
            .v (PID::oscAWtPos, 0.18f).v (PID::oscALevel, 0.52f)
            .v (PID::oscAUnison, 3.0f).v (PID::oscADetune, 0.20f)
            .v (PID::oscASpread, 0.62f)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.26f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, 6.0f)
            .v (PID::subLevel, 0.20f).v (PID::subHarmonics, 0.26f)
            .v (PID::noiseType, ch::nPink).v (PID::noiseLevel, 0.34f)
            .v (PID::bodyAmount, 0.44f).v (PID::bodyTilt, -0.18f)
            .v (PID::densityAmount, 0.36f)
            .v (PID::preFilterDrive, 0.16f)
            .v (PID::postSaturation, 0.20f).v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1900.0f).v (PID::filterResonance, 0.14f)
            .v (PID::filterKeyTrack, 0.30f).v (PID::filterEnvAmount, 0.12f)
            .v (PID::ampAttack, 1.1f).v (PID::ampDecay, 3.2f)
            .v (PID::ampSustain, 0.94f).v (PID::ampRelease, 3.0f)
            .v (PID::ampVelocity, 0.18f)
            .v (PID::macroMemory, 0.44f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.60f).v (PID::memoryWobble, 0.28f)
            .v (PID::memoryDiffusion, 0.50f).v (PID::memoryAsymmetry, 0.34f)
            .v (PID::macroCharacter, 0.46f).v (PID::macroMotion, 0.44f)
            .v (PID::macroWorld, 0.44f).v (PID::macroWeight, 0.38f)
            .v (PID::weightHarmonics, 0.36f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.52f)
            .v (PID::grainSize, 22.0f).v (PID::grainDensity, 55.0f)
            .v (PID::grainPosition, 0.26f).v (PID::grainPitchMode, ch::gRoot)
            .v (PID::grainSpread, 0.60f).v (PID::grainJitter, 0.34f)
            .v (PID::grainDirection, 0.12f).v (PID::grainWindow, ch::wTukey)
            .v (PID::grainFeedback, 0.18f).v (PID::grainMix, 0.56f)
            .v (PID::retroEra, 0.36f).v (PID::retroAge, 0.48f)
            .v (PID::retroDrift, 0.30f).v (PID::retroWear, 0.22f)
            .v (PID::retroTone, -0.28f).v (PID::retroNoise, 0.22f)
            .v (PID::retroMix, 0.72f)
            .v (PID::fxFilterCutoff, 4800.0f).v (PID::fxFilterRes, 0.06f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.40f)
            .v (PID::spaceSize, 0.56f).v (PID::spaceDecay, 3.4f)
            .v (PID::spaceFog, 0.54f).v (PID::spaceLight, -0.24f)
            .v (PID::spacePreDelay, 26.0f).v (PID::spaceMix, 0.28f)
            .v (PID::auraSize, 0.50f).v (PID::auraDistance, 0.32f)
            .v (PID::auraFog, 0.50f).v (PID::auraDecay, 0.48f)
            .v (PID::auraLight, -0.18f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.20f)
            .v (PID::patinaNoise, 0.22f).v (PID::patinaWear, 0.26f)
            .v (PID::patinaDrift, 0.26f)
            .v (PID::synthWidth, 1.15f).v (PID::highWidth, 1.20f)
            .v (PID::masterGain, 2.0f)
            .v (PID::breathAmount, 0.46f).v (PID::breathSpeed, 0.10f)
            .v (PID::breathRandom, 0.60f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Rate, 0.09f)
            .v (PID::lfo1Depth, 0.50f)
            .route (srcLfo1, PID::oscAWtPos, 0.20f)
            .route (srcBreath, PID::filterCutoff, 0.12f)
            .route (srcOrganic, PID::grainPosition, 0.16f));

        // Oscillator B switched off entirely: AIR noise is the exciter and
        // the COMB model is the instrument, with a second comb after it.
        add (out, Build ("Hilo de Cobre", "TEXTURE", "MYSTERIOUS",
                         "comb,metallic,resonant,noise",
                         "AIR noise into the COMB filter model at high resonance and drive, then a second comb in the chain filter.")
            .at (41, 1, 0.78f, 5.5)
            .chain ("FILTER,SPACE,RETRO,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.42f)
            .v (PID::driftAmount, 0.24f).v (PID::driftRate, 0.10f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.10f)
            .v (PID::oscBLevel, 0.0f)
            .v (PID::noiseType, ch::nAir).v (PID::noiseLevel, 0.78f)
            .v (PID::bodyAmount, 0.20f).v (PID::densityAmount, 0.24f)
            .v (PID::preFilterDrive, 0.28f)
            .v (PID::postSaturation, 0.16f).v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 820.0f).v (PID::filterResonance, 0.74f)
            .v (PID::filterDrive, 0.34f).v (PID::filterKeyTrack, 1.0f)
            .v (PID::filterEnvAmount, 0.16f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Bp)
            .v (PID::filter2Cutoff, 2700.0f).v (PID::filter2Res, 0.40f)
            .v (PID::filter2Mix, 0.44f)
            .v (PID::ampAttack, 0.5f).v (PID::ampDecay, 2.8f)
            .v (PID::ampSustain, 0.90f).v (PID::ampRelease, 2.2f)
            .v (PID::ampVelocity, 0.22f)
            .v (PID::macroMemory, 0.28f).v (PID::memoryBandwidth, 0.32f)
            .v (PID::memoryDiffusion, 0.44f)
            .v (PID::macroCharacter, 0.40f).v (PID::macroMotion, 0.62f)
            .v (PID::macroWorld, 0.52f).v (PID::macroWeight, 0.22f)
            .v (PID::weightMode, ch::wAir).v (PID::weightHarmonics, 0.42f)
            .v (PID::retroEra, 0.68f).v (PID::retroAge, 0.26f)
            .v (PID::retroDrift, 0.22f).v (PID::retroWear, 0.18f)
            .v (PID::retroTone, 0.14f).v (PID::retroNoise, 0.14f)
            .v (PID::retroMix, 0.36f)
            .v (PID::fxFilterMode, ch::f2Comb).v (PID::fxFilterCutoff, 1450.0f)
            .v (PID::fxFilterRes, 0.58f).v (PID::fxFilterDrive, 0.20f)
            .v (PID::fxFilterMix, 0.62f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.46f)
            .v (PID::spaceSize, 0.60f).v (PID::spaceDecay, 4.6f)
            .v (PID::spaceFog, 0.48f).v (PID::spaceLight, 0.22f)
            .v (PID::spacePreDelay, 30.0f).v (PID::spaceMix, 0.32f)
            .v (PID::auraSize, 0.58f).v (PID::auraDistance, 0.36f)
            .v (PID::auraFog, 0.42f).v (PID::auraDecay, 0.58f)
            .v (PID::auraLight, 0.26f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.18f)
            .v (PID::patinaNoise, 0.16f).v (PID::patinaWear, 0.28f)
            .v (PID::patinaDrift, 0.24f)
            .v (PID::synthWidth, 1.28f).v (PID::highWidth, 1.36f)
            .v (PID::lowMonoFreq, 160.0f)
            .v (PID::breathAmount, 0.52f).v (PID::breathSpeed, 0.24f)
            .v (PID::breathRandom, 0.68f)
            .v (PID::lfo1Shape, ch::lfoTri).v (PID::lfo1Rate, 0.14f)
            .v (PID::lfo1Depth, 0.62f)
            .route (srcLfo1, PID::filterCutoff, 0.18f)
            .route (srcBreath, PID::fxFilterCutoff, 0.20f)
            .route (srcOrganic, PID::filter2Cutoff, 0.22f)
            .route (srcMotion, PID::filterResonance, 0.12f));

        // Two combs stacked - the creative filter and the chain filter -
        // with RETRO ahead of both so the corrosion is on the source.
        add (out, Build ("Pátina Verde", "TEXTURE", "DARK",
                         "comb,corrosion,resonant,drone",
                         "TEXTURE noise into a COMB creative filter at high feedback, with RETRO ahead of everything so the corrosion is on the source.")
            .at (39, 1, 0.76f, 5.5)
            .chain ("RETRO,FILTER,CRUSH,GRAIN,SPACE,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 4.0f).v (PID::voiceVariation, 0.46f)
            .v (PID::driftAmount, 0.32f).v (PID::driftRate, 0.07f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tMetal)
            .v (PID::oscAWtPos, 0.16f).v (PID::oscALevel, 0.24f)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.12f)
            .v (PID::oscBOctave, -1.0f)
            .v (PID::subLevel, 0.16f)
            .v (PID::noiseType, ch::nTexture).v (PID::noiseLevel, 0.72f)
            .v (PID::bodyAmount, 0.34f).v (PID::bodyTilt, 0.22f)
            .v (PID::densityAmount, 0.28f)
            .v (PID::preFilterDrive, 0.30f)
            .v (PID::postSaturation, 0.24f).v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1400.0f).v (PID::filterResonance, 0.28f)
            .v (PID::filterDrive, 0.30f).v (PID::filterKeyTrack, 0.25f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Comb)
            .v (PID::filter2Cutoff, 640.0f).v (PID::filter2Res, 0.78f)
            .v (PID::filter2Mix, 0.68f)
            .v (PID::ampAttack, 0.7f).v (PID::ampDecay, 3.0f)
            .v (PID::ampSustain, 0.90f).v (PID::ampRelease, 2.4f)
            .v (PID::ampVelocity, 0.20f)
            .v (PID::macroMemory, 0.48f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.64f).v (PID::memoryWobble, 0.40f)
            .v (PID::memoryDiffusion, 0.42f).v (PID::memoryAsymmetry, 0.52f)
            .v (PID::macroCharacter, 0.66f).v (PID::macroMotion, 0.54f)
            .v (PID::macroWorld, 0.34f).v (PID::macroWeight, 0.36f)
            .v (PID::weightHarmonics, 0.44f)
            .v (PID::retroEra, 0.20f).v (PID::retroAge, 0.66f)
            .v (PID::retroDrift, 0.38f).v (PID::retroWear, 0.54f)
            .v (PID::retroTone, -0.30f).v (PID::retroNoise, 0.38f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.28f)
            .v (PID::crushBits, 9.0f).v (PID::crushRate, 14000.0f)
            .v (PID::crushJitter, 0.20f).v (PID::crushTone, -0.20f)
            .v (PID::crushMix, 0.38f)
            .v (PID::fxFilterMode, ch::f2Comb).v (PID::fxFilterCutoff, 320.0f)
            .v (PID::fxFilterRes, 0.66f).v (PID::fxFilterDrive, 0.24f)
            .v (PID::fxFilterMix, 0.54f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.44f)
            .v (PID::spaceSize, 0.58f).v (PID::spaceDecay, 5.2f)
            .v (PID::spaceFog, 0.62f).v (PID::spaceLight, -0.44f)
            .v (PID::spaceMix, 0.30f)
            .v (PID::auraSize, 0.54f).v (PID::auraDistance, 0.34f)
            .v (PID::auraFog, 0.60f).v (PID::auraDecay, 0.56f)
            .v (PID::auraLight, -0.36f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.34f)
            .v (PID::patinaNoise, 0.40f).v (PID::patinaWear, 0.60f)
            .v (PID::patinaDrift, 0.34f)
            .v (PID::synthWidth, 1.12f).v (PID::highWidth, 1.18f)
            .v (PID::lowMonoFreq, 145.0f)
            .v (PID::breathAmount, 0.56f).v (PID::breathSpeed, 0.11f)
            .v (PID::breathRandom, 0.70f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.05f)
            .v (PID::lfo2Depth, 0.64f)
            .route (srcLfo2, PID::filter2Cutoff, 0.24f)
            .route (srcBreath, PID::filter2Res, 0.12f)
            .route (srcOrganic, PID::fxFilterCutoff, 0.20f)
            .route (srcMemory, PID::patinaWear, 0.14f));

        // REWIND first in the chain, generation IV behind it, and ORGANIC
        // RANDOM on the transport speed so the gesture never lands twice
        // in the same place.
        add (out, Build ("Carrete Roto", "TEXTURE", "BROKEN",
                         "rewind,glitch,transport,broken",
                         "REWIND in REVERSE with Memory at generation IV and ORGANIC RANDOM on the transport, so no two passes are the same.")
            .at (45, 1, 0.80f, 5.5)
            .chain ("REWIND,RETRO,CRUSH,FILTER,GRAIN,SPACE")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 3.0f).v (PID::voiceVariation, 0.62f)
            .v (PID::driftAmount, 0.50f).v (PID::driftRate, 0.34f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tVocal)
            .v (PID::oscAWtPos, 0.56f).v (PID::oscALevel, 0.40f)
            .v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.22f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, -17.0f)
            .v (PID::subLevel, 0.10f)
            .v (PID::noiseType, ch::nTexture).v (PID::noiseLevel, 0.50f)
            .v (PID::bodyAmount, 0.28f).v (PID::densityAmount, 0.26f)
            .v (PID::preFilterDrive, 0.26f)
            .v (PID::postSaturation, 0.22f).v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 1100.0f).v (PID::filterResonance, 0.30f)
            .v (PID::filterKeyTrack, 0.15f).v (PID::filterEnvAmount, 0.24f)
            .v (PID::ampAttack, 0.12f).v (PID::ampDecay, 2.0f)
            .v (PID::ampSustain, 0.88f).v (PID::ampRelease, 1.4f)
            .v (PID::ampVelocity, 0.26f)
            .v (PID::macroMemory, 0.82f).v (PID::memoryGen, ch::genIV)
            .v (PID::memoryBandwidth, 0.74f).v (PID::memoryWobble, 0.70f)
            .v (PID::memoryDiffusion, 0.52f).v (PID::memoryAsymmetry, 0.74f)
            .v (PID::macroCharacter, 0.68f).v (PID::macroMotion, 0.88f)
            .v (PID::macroWorld, 0.36f).v (PID::macroWeight, 0.24f)
            .v (PID::macroAlter, 0.40f).v (PID::randomAmount, 0.55f)
            .v (PID::rewindOn, 1.0f).v (PID::rewindMode, ch::rReverse)
            .v (PID::rewindDivision, ch::rw4).v (PID::rewindCurve, 0.62f)
            .v (PID::rewindSpeed, 0.8f).v (PID::rewindTail, 0.62f)
            .v (PID::rewindMix, 0.62f)
            .v (PID::retroEra, 0.30f).v (PID::retroAge, 0.70f)
            .v (PID::retroDrift, 0.66f).v (PID::retroWear, 0.68f)
            .v (PID::retroTone, -0.24f).v (PID::retroNoise, 0.40f)
            .v (PID::retroMix, 0.90f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.36f)
            .v (PID::crushBits, 8.0f).v (PID::crushRate, 9500.0f)
            .v (PID::crushJitter, 0.48f).v (PID::crushTone, -0.06f)
            .v (PID::crushMix, 0.46f)
            .v (PID::fxFilterCutoff, 5600.0f).v (PID::fxFilterRes, 0.24f)
            .v (PID::fxFilterMotion, 0.52f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.50f)
            .v (PID::spaceSize, 0.52f).v (PID::spaceDecay, 3.8f)
            .v (PID::spaceFog, 0.58f).v (PID::spaceLight, -0.26f)
            .v (PID::spacePreDelay, 46.0f).v (PID::spaceMix, 0.30f)
            .v (PID::auraSize, 0.48f).v (PID::auraDistance, 0.38f)
            .v (PID::auraFog, 0.58f).v (PID::auraDecay, 0.46f)
            .v (PID::auraLight, -0.22f)
            .v (PID::shadowOn, 1.0f).v (PID::shadowLength, 0.46f)
            .v (PID::shadowDistance, 0.60f).v (PID::shadowBlur, 0.64f)
            .v (PID::shadowPitch, -12.0f).v (PID::shadowLevel, 0.26f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.20f)
            .v (PID::patinaNoise, 0.36f).v (PID::patinaWear, 0.64f)
            .v (PID::patinaDrift, 0.58f)
            .v (PID::synthWidth, 1.22f).v (PID::highWidth, 1.28f)
            .v (PID::breathAmount, 0.70f).v (PID::breathSpeed, 0.44f)
            .v (PID::breathRandom, 0.92f).v (PID::breathShape, 0.66f)
            .v (PID::lfo2Shape, ch::lfoRandom).v (PID::lfo2Rate, 1.8f)
            .v (PID::lfo2Depth, 0.68f)
            .route (srcOrganic, PID::rewindSpeed, 0.30f)
            .route (srcOrganic, PID::retroDrift, 0.22f)
            .route (srcLfo2, PID::filterCutoff, 0.22f)
            .route (srcBreath, PID::memoryWobble, 0.18f));

        // The quietest idea in the file, built at full level: DARK noise
        // and a triangle pair under a low MASS filter, meant to go a long
        // way down in a mix by the user's hand and not by the preset's.
        add (out, Build ("Fieltro Húmedo", "TEXTURE", "INTIMATE",
                         "felt,dark,warm,bed",
                         "DARK noise and a triangle pair under a low MASS filter with WARM saturation and PATINA on SOFT: a bed meant to sit far down in a mix.")
            .at (36, 2, 0.72f, 6.0)
            .chain ("RETRO,FILTER,GRAIN,CRUSH,SPACE,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::polyphony, 5.0f).v (PID::voiceVariation, 0.36f)
            .v (PID::driftAmount, 0.24f).v (PID::driftRate, 0.05f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.46f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.14f)
            .v (PID::oscASpread, 0.40f)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.30f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, 5.0f)
            .v (PID::subLevel, 0.34f).v (PID::subHarmonics, 0.40f)
            .v (PID::noiseType, ch::nDark).v (PID::noiseLevel, 0.56f)
            .v (PID::bodyAmount, 0.52f).v (PID::bodyTilt, -0.30f)
            .v (PID::densityAmount, 0.40f)
            .v (PID::preFilterDrive, 0.18f)
            .v (PID::postSaturation, 0.26f).v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 780.0f).v (PID::filterResonance, 0.20f)
            .v (PID::filterKeyTrack, 0.20f).v (PID::filterEnvAmount, 0.10f)
            .v (PID::ampAttack, 1.2f).v (PID::ampDecay, 4.0f)
            .v (PID::ampSustain, 0.95f).v (PID::ampRelease, 3.6f)
            .v (PID::ampVelocity, 0.14f)
            .v (PID::macroMemory, 0.38f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.68f).v (PID::memoryWobble, 0.22f)
            .v (PID::memoryDiffusion, 0.46f).v (PID::memoryAsymmetry, 0.28f)
            .v (PID::macroCharacter, 0.42f).v (PID::macroMotion, 0.34f)
            .v (PID::macroWorld, 0.28f).v (PID::macroWeight, 0.46f)
            .v (PID::weightHarmonics, 0.48f).v (PID::weightCompress, 0.36f)
            .v (PID::retroEra, 0.26f).v (PID::retroAge, 0.52f)
            .v (PID::retroDrift, 0.28f).v (PID::retroWear, 0.20f)
            .v (PID::retroTone, -0.40f).v (PID::retroNoise, 0.26f)
            .v (PID::retroMix, 0.78f)
            .v (PID::fxFilterCutoff, 2600.0f).v (PID::fxFilterRes, 0.06f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.30f)
            .v (PID::spaceSize, 0.42f).v (PID::spaceDecay, 2.8f)
            .v (PID::spaceFog, 0.58f).v (PID::spaceLight, -0.52f)
            .v (PID::spaceMix, 0.18f)
            .v (PID::auraSize, 0.40f).v (PID::auraDistance, 0.26f)
            .v (PID::auraFog, 0.56f).v (PID::auraDecay, 0.42f)
            .v (PID::auraLight, -0.42f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.36f)
            .v (PID::patinaNoise, 0.24f).v (PID::patinaWear, 0.22f)
            .v (PID::patinaDrift, 0.22f)
            .v (PID::synthWidth, 1.00f).v (PID::lowMonoFreq, 120.0f)
            .v (PID::highWidth, 1.10f).v (PID::masterGain, 3.0f)
            .v (PID::breathAmount, 0.40f).v (PID::breathSpeed, 0.07f)
            .v (PID::breathRandom, 0.52f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Rate, 0.06f)
            .v (PID::lfo1Depth, 0.45f)
            .route (srcLfo1, PID::filterCutoff, 0.14f)
            .route (srcBreath, PID::bodyAmount, 0.12f)
            .route (srcOrganic, PID::patinaDrift, 0.12f));
    }
}
