#include "PresetBuilder.h"
#include "Builders.h"

namespace nacar::presets::detail
{
    // ===============================================================
    //  VOCAL-LIKE
    // ===============================================================
    void buildVocal (std::vector<FactoryPreset>& out)
    {
        // The VOCAL wavetable through the FORMANT filter model, which puts
        // formants at ratios of the cutoff rather than at fixed frequencies.
        add (out, Build ("Salt Choir", "VOCAL-LIKE", "HAUNTED",
                         "choir,formant,generation iii,shadow",
                         "Voices that have been through the medium more times than the words have.")
            .at (48, 4, 0.66f, 8.0)
            .chain ("RETRO,FILTER,SPACE,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::masterGain, 4.0f)
            .v (PID::polyphony, 12.0f).v (PID::voiceVariation, 0.62f)
            .v (PID::driftAmount, 0.42f).v (PID::driftRate, 0.07f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tVocal)
            .v (PID::oscAWtPos, 0.28f).v (PID::oscALevel, 0.86f)
            .v (PID::oscAUnison, 4.0f).v (PID::oscADetune, 0.16f)
            .v (PID::oscASpread, 0.52f).v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tVocal)
            .v (PID::oscBWtPos, 0.74f).v (PID::oscBLevel, 0.34f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, 6.0f)
            .v (PID::subLevel, 0.14f)
            .v (PID::noiseType, ch::nTexture).v (PID::noiseLevel, 0.10f)
            .v (PID::bodyAmount, 0.28f).v (PID::densityAmount, 0.30f)
            .v (PID::postSaturation, 0.12f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 640.0f).v (PID::filterResonance, 0.38f)
            .v (PID::filterKeyTrack, 0.15f).v (PID::filterEnvAmount, 0.26f)
            .v (PID::filterVelAmount, 0.30f)
            .v (PID::ampAttack, 0.9f).v (PID::ampDecay, 3.4f)
            .v (PID::ampSustain, 0.80f).v (PID::ampRelease, 3.8f)
            .v (PID::ampVelocity, 0.40f)
            .v (PID::macroMemory, 0.56f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.66f).v (PID::memoryWobble, 0.50f)
            .v (PID::memoryDiffusion, 0.60f).v (PID::memoryAsymmetry, 0.40f)
            .v (PID::macroCharacter, 0.40f).v (PID::macroMotion, 0.60f)
            .v (PID::macroWorld, 0.44f).v (PID::macroWeight, 0.24f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::retroEra, 0.44f).v (PID::retroAge, 0.46f)
            .v (PID::retroDrift, 0.42f).v (PID::retroWear, 0.30f)
            .v (PID::retroTone, -0.18f).v (PID::retroNoise, 0.20f)
            .v (PID::retroMix, 0.74f)
            .v (PID::fxFilterMode, ch::f2Bp).v (PID::fxFilterCutoff, 1400.0f)
            .v (PID::fxFilterRes, 0.24f).v (PID::fxFilterMotion, 0.40f)
            .v (PID::fxFilterMix, 0.50f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.44f)
            .v (PID::spaceSize, 0.74f).v (PID::spaceDecay, 7.0f)
            .v (PID::spaceFog, 0.64f).v (PID::spaceLight, -0.26f)
            .v (PID::spacePreDelay, 20.0f).v (PID::spaceMix, 0.26f)
            .v (PID::shadowOn, 1.0f).v (PID::shadowLength, 0.46f)
            .v (PID::shadowDistance, 0.64f).v (PID::shadowBlur, 0.52f)
            .v (PID::shadowPitch, -5.0f).v (PID::shadowLevel, 0.22f)
            .v (PID::auraSize, 0.70f).v (PID::auraDistance, 0.32f)
            .v (PID::auraFog, 0.50f).v (PID::auraDecay, 0.68f)
            .v (PID::auraLight, -0.18f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.16f)
            .v (PID::patinaNoise, 0.20f).v (PID::patinaWear, 0.38f)
            .v (PID::patinaDrift, 0.38f)
            .v (PID::synthWidth, 1.00f).v (PID::highWidth, 1.10f)
            .v (PID::breathAmount, 0.64f).v (PID::breathSpeed, 0.09f)
            .v (PID::breathRandom, 0.70f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Rate, 0.11f)
            .v (PID::lfo1Depth, 0.65f)
            .route (srcLfo1, PID::filterCutoff, 0.18f)
            .route (srcBreath, PID::oscAWtPos, 0.24f)
            .route (srcMotion, PID::shadowLength, 0.16f));

        // Band-limited hard, crushed, and mixed almost entirely wet: the
        // preset is the transmission, not the singer.
        add (out, Build ("Radio Breath", "VOCAL-LIKE", "NOSTALGIC",
                         "am radio,band-limited,crush,close",
                         "A voice on longwave, with more of the radio in it than the voice.")
            .at (57, 2, 0.74f, 5.0)
            .chain ("FILTER,CRUSH,RETRO,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.36f)
            .v (PID::driftAmount, 0.30f).v (PID::driftRate, 0.28f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tVocal)
            .v (PID::oscAWtPos, 0.52f).v (PID::oscALevel, 0.74f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.14f)
            .v (PID::oscBWave, ch::saw).v (PID::oscBLevel, 0.22f)
            .v (PID::oscBFine, -12.0f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nPink).v (PID::noiseLevel, 0.12f)
            .v (PID::bodyAmount, 0.20f).v (PID::densityAmount, 0.22f)
            .v (PID::preFilterDrive, 0.26f).v (PID::postSaturation, 0.22f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 1250.0f).v (PID::filterResonance, 0.42f)
            .v (PID::filterKeyTrack, 0.25f).v (PID::filterEnvAmount, 0.20f)
            .v (PID::ampAttack, 0.05f).v (PID::ampDecay, 1.2f)
            .v (PID::ampSustain, 0.76f).v (PID::ampRelease, 0.6f)
            .v (PID::ampVelocity, 0.52f)
            .v (PID::macroMemory, 0.52f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.80f).v (PID::memoryWobble, 0.46f)
            .v (PID::memoryDiffusion, 0.32f).v (PID::memoryAsymmetry, 0.50f)
            .v (PID::macroCharacter, 0.56f).v (PID::macroMotion, 0.44f)
            .v (PID::macroWorld, 0.26f).v (PID::macroWeight, 0.20f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.46f)
            .v (PID::crushBits, 8.0f).v (PID::crushRate, 9000.0f)
            .v (PID::crushJitter, 0.26f).v (PID::crushDrive, 0.24f)
            .v (PID::crushTone, -0.16f).v (PID::crushMix, 0.62f)
            .v (PID::retroEra, 0.06f).v (PID::retroAge, 0.56f)
            .v (PID::retroDrift, 0.38f).v (PID::retroWear, 0.42f)
            .v (PID::retroTone, -0.20f).v (PID::retroNoise, 0.30f)
            .v (PID::retroMix, 0.90f)
            .v (PID::fxFilterMode, ch::f2Bp).v (PID::fxFilterCutoff, 1700.0f)
            .v (PID::fxFilterRes, 0.30f).v (PID::fxFilterMorph, 0.20f)
            .v (PID::fxFilterMix, 0.85f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.30f)
            .v (PID::spaceSize, 0.26f).v (PID::spaceDecay, 1.0f)
            .v (PID::spaceFog, 0.30f).v (PID::spaceLight, -0.30f)
            .v (PID::spaceMix, 0.18f)
            .v (PID::auraSize, 0.28f).v (PID::auraDistance, 0.20f)
            .v (PID::auraFog, 0.40f).v (PID::auraDecay, 0.24f)
            .v (PID::auraLight, -0.24f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.20f)
            .v (PID::patinaNoise, 0.30f).v (PID::patinaWear, 0.40f)
            .v (PID::patinaDrift, 0.30f)
            .v (PID::synthWidth, 0.70f).v (PID::highWidth, 0.80f)
            .v (PID::breathAmount, 0.50f).v (PID::breathSpeed, 0.30f)
            .v (PID::breathRandom, 0.70f).v (PID::breathShape, 0.60f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.42f)
            .v (PID::lfo2Depth, 0.55f)
            .route (srcLfo2, PID::fxFilterCutoff, 0.14f)
            .route (srcBreath, PID::retroWear, 0.20f)
            .route (srcOrganic, PID::crushRate, -0.14f));

        // Generation IV plus a dense short-grain cloud in the chain: the
        // syllables are grains, and they do not come back in order.
        add (out, Build ("Memory Vocoder", "VOCAL-LIKE", "BROKEN",
                         "granular,generation iv,stutter,glitch",
                         "A vocal reassembled out of its own recent past, in the wrong order.")
            .at (53, 3, 0.80f, 6.0)
            .chain ("RETRO,GRAIN,CRUSH,FILTER,SPACE,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.50f)
            .v (PID::driftAmount, 0.28f).v (PID::driftRate, 0.40f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tVocal)
            .v (PID::oscAWtPos, 0.36f).v (PID::oscALevel, 0.72f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tAsym)
            .v (PID::oscBWtPos, 0.46f).v (PID::oscBLevel, 0.30f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, -16.0f)
            .v (PID::oscRingMod, 0.14f)
            .v (PID::subLevel, 0.10f)
            .v (PID::noiseType, ch::nDigital).v (PID::noiseLevel, 0.08f)
            .v (PID::bodyAmount, 0.18f).v (PID::densityAmount, 0.20f)
            .v (PID::preFilterDrive, 0.20f).v (PID::postSaturation, 0.16f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 4200.0f).v (PID::filterResonance, 0.22f)
            .v (PID::filterKeyTrack, 0.40f).v (PID::filterEnvAmount, 0.30f)
            .v (PID::ampAttack, 0.02f).v (PID::ampDecay, 1.6f)
            .v (PID::ampSustain, 0.70f).v (PID::ampRelease, 1.0f)
            .v (PID::macroMemory, 0.78f).v (PID::memoryGen, ch::genIV)
            .v (PID::memoryBandwidth, 0.70f).v (PID::memoryWobble, 0.56f)
            .v (PID::memoryDiffusion, 0.58f).v (PID::memoryAsymmetry, 0.54f)
            .v (PID::macroCharacter, 0.50f).v (PID::macroMotion, 0.70f)
            .v (PID::macroWorld, 0.46f).v (PID::macroWeight, 0.22f)
            .v (PID::macroAlter, 0.35f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.62f)
            .v (PID::grainSize, 42.0f).v (PID::grainDensity, 34.0f)
            .v (PID::grainPosition, 0.24f).v (PID::grainPitchMode, ch::gScale)
            .v (PID::grainSpread, 0.66f).v (PID::grainJitter, 0.62f)
            .v (PID::grainDirection, 0.34f).v (PID::grainWindow, ch::wTukey)
            .v (PID::grainFeedback, 0.18f).v (PID::grainMix, 0.58f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.36f)
            .v (PID::crushBits, 9.0f).v (PID::crushRate, 15000.0f)
            .v (PID::crushJitter, 0.40f).v (PID::crushMix, 0.44f)
            .v (PID::retroEra, 0.86f).v (PID::retroAge, 0.42f)
            .v (PID::retroDrift, 0.34f).v (PID::retroWear, 0.50f)
            .v (PID::retroNoise, 0.18f).v (PID::retroMix, 0.72f)
            .v (PID::fxFilterCutoff, 7600.0f).v (PID::fxFilterRes, 0.18f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.42f)
            .v (PID::spaceSize, 0.54f).v (PID::spaceDecay, 3.2f)
            .v (PID::spaceFog, 0.50f).v (PID::spaceMix, 0.30f)
            .v (PID::auraSize, 0.52f).v (PID::auraDistance, 0.34f)
            .v (PID::auraFog, 0.56f).v (PID::auraDecay, 0.46f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaNoise, 0.24f)
            .v (PID::patinaWear, 0.46f).v (PID::patinaDrift, 0.40f)
            .v (PID::synthWidth, 1.15f).v (PID::highWidth, 1.25f)
            .v (PID::breathAmount, 0.60f).v (PID::breathSpeed, 0.55f)
            .v (PID::breathRandom, 0.85f).v (PID::breathShape, 0.80f)
            .v (PID::lfo2Shape, ch::lfoRandom).v (PID::lfo2Rate, 2.6f)
            .v (PID::lfo2Depth, 0.60f)
            .route (srcLfo2, PID::grainPosition, 0.44f)
            .route (srcBreath, PID::grainSize, 0.30f)
            .route (srcOrganic, PID::grainDirection, 0.26f));

        // Shadow an octave up behind a soft vocal table, and the widest
        // Aura in the library.  Nothing dirty anywhere in the chain.
        add (out, Build ("Distant Aria", "VOCAL-LIKE", "ROMANTIC",
                         "soprano,shadow,octave,far",
                         "A soprano at the other end of the building, with her own echo an octave up.")
            .at (60, 3, 0.62f, 9.0)
            .chain ("FILTER,SPACE,RETRO,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::masterGain, 4.0f)
            .v (PID::polyphony, 10.0f).v (PID::voiceVariation, 0.42f)
            .v (PID::driftAmount, 0.30f).v (PID::driftRate, 0.06f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tVocal)
            .v (PID::oscAWtPos, 0.16f).v (PID::oscALevel, 0.70f)
            .v (PID::oscAUnison, 3.0f).v (PID::oscADetune, 0.14f)
            .v (PID::oscASpread, 0.48f)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.26f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, 7.0f)
            .v (PID::subLevel, 0.08f)
            .v (PID::noiseType, ch::nAir).v (PID::noiseLevel, 0.10f)
            .v (PID::bodyAmount, 0.18f).v (PID::densityAmount, 0.24f)
            .v (PID::postSaturation, 0.08f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 3600.0f).v (PID::filterResonance, 0.12f)
            .v (PID::filterKeyTrack, 0.60f).v (PID::filterEnvAmount, 0.24f)
            .v (PID::filterVelAmount, 0.40f)
            .v (PID::ampAttack, 0.55f).v (PID::ampDecay, 3.0f)
            .v (PID::ampSustain, 0.82f).v (PID::ampRelease, 3.6f)
            .v (PID::ampVelocity, 0.44f)
            .v (PID::macroMemory, 0.30f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.36f).v (PID::memoryWobble, 0.30f)
            .v (PID::memoryDiffusion, 0.48f)
            .v (PID::macroCharacter, 0.22f).v (PID::macroMotion, 0.52f)
            .v (PID::macroWorld, 0.58f).v (PID::macroWeight, 0.22f)
            .v (PID::weightMode, ch::wAir).v (PID::weightHarmonics, 0.44f)
            .v (PID::retroEra, 0.50f).v (PID::retroAge, 0.18f)
            .v (PID::retroDrift, 0.24f).v (PID::retroWear, 0.08f)
            .v (PID::retroNoise, 0.08f).v (PID::retroMix, 0.36f)
            .v (PID::fxFilterCutoff, 10000.0f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.68f)
            .v (PID::spaceSize, 0.82f).v (PID::spaceDecay, 8.5f)
            .v (PID::spaceFog, 0.58f).v (PID::spaceLight, -0.06f)
            .v (PID::spacePreDelay, 16.0f).v (PID::spaceMix, 0.38f)
            .v (PID::shadowOn, 1.0f).v (PID::shadowLength, 0.56f)
            .v (PID::shadowDistance, 0.60f).v (PID::shadowBlur, 0.48f)
            .v (PID::shadowPitch, 12.0f).v (PID::shadowLevel, 0.32f)
            .v (PID::auraSize, 0.84f).v (PID::auraDistance, 0.40f)
            .v (PID::auraFog, 0.56f).v (PID::auraDecay, 0.76f)
            .v (PID::auraLight, 0.10f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, 0.04f)
            .v (PID::patinaNoise, 0.10f).v (PID::patinaWear, 0.16f)
            .v (PID::patinaDrift, 0.30f)
            .v (PID::synthWidth, 1.05f).v (PID::highWidth, 1.15f)
            .v (PID::breathAmount, 0.60f).v (PID::breathSpeed, 0.10f)
            .v (PID::modWheelDepth, 0.60f).v (PID::vibratoDepth, 0.26f)
            .v (PID::vibratoRate, 5.0f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.13f)
            .v (PID::lfo1Depth, 0.60f)
            .route (srcLfo1, PID::oscAWtPos, 0.16f)
            .route (srcBreath, PID::shadowDistance, 0.16f)
            .route (srcWorld, PID::auraSize, 0.12f));

        // ---------------------------------------------------------------
        //  CHOIRS AND VOCAL PADS
        // ---------------------------------------------------------------

        // Two VOCAL tables, unison on both, and the FORMANT filter with its
        // key track at zero so the resonances stay put while the chord moves.
        add (out, Build ("Coro de Aliento", "VOCAL-LIKE", "LUSH",
                         "choir,formant,breath,aahs",
                         "A vocal-table stack through the FORMANT filter with key track at zero, a pink noise breath layer under it, for sustained aah beds.")
            .at (53, 4, 0.60f, 6.0)
            .chain ("FILTER,RETRO,SPACE,CRUSH,REWIND,GRAIN")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::masterGain, 3.0f)
            .v (PID::polyphony, 16.0f).v (PID::voiceVariation, 0.55f)
            .v (PID::driftAmount, 0.34f).v (PID::driftRate, 0.08f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tVocal)
            .v (PID::oscAWtPos, 0.22f).v (PID::oscALevel, 0.78f)
            .v (PID::oscAUnison, 5.0f).v (PID::oscADetune, 0.18f)
            .v (PID::oscASpread, 0.60f).v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tVocal)
            .v (PID::oscBWtPos, 0.62f).v (PID::oscBLevel, 0.40f)
            .v (PID::oscBFine, 9.0f).v (PID::oscBUnison, 3.0f)
            .v (PID::oscBDetune, 0.14f).v (PID::oscBSpread, 0.55f)
            .v (PID::oscBPhase, ch::phaseRandom)
            .v (PID::subLevel, 0.06f)
            .v (PID::noiseType, ch::nPink).v (PID::noiseLevel, 0.16f)
            .v (PID::bodyAmount, 0.30f).v (PID::densityAmount, 0.34f)
            .v (PID::postSaturation, 0.10f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 520.0f).v (PID::filterResonance, 0.44f)
            .v (PID::filterKeyTrack, 0.0f).v (PID::filterEnvAmount, 0.30f)
            .v (PID::filterVelAmount, 0.25f)
            .v (PID::env1Attack, 1.8f).v (PID::env1Decay, 4.0f)
            .v (PID::env1Sustain, 0.55f).v (PID::env1Release, 3.0f)
            .v (PID::ampAttack, 1.1f).v (PID::ampDecay, 3.0f)
            .v (PID::ampSustain, 0.85f).v (PID::ampRelease, 4.0f)
            .v (PID::ampVelocity, 0.35f)
            .v (PID::macroMemory, 0.20f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.30f).v (PID::memoryDiffusion, 0.45f)
            .v (PID::macroCharacter, 0.24f).v (PID::macroMotion, 0.62f)
            .v (PID::macroWorld, 0.62f).v (PID::macroWeight, 0.22f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::retroEra, 0.55f).v (PID::retroAge, 0.16f)
            .v (PID::retroDrift, 0.22f).v (PID::retroWear, 0.06f)
            .v (PID::retroNoise, 0.08f).v (PID::retroMix, 0.30f)
            .v (PID::fxFilterCutoff, 9000.0f).v (PID::fxFilterRes, 0.10f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.46f)
            .v (PID::spaceSize, 0.80f).v (PID::spaceDecay, 9.0f)
            .v (PID::spaceFog, 0.60f).v (PID::spaceLight, -0.10f)
            .v (PID::spacePreDelay, 34.0f).v (PID::spaceMix, 0.40f)
            .v (PID::auraSize, 0.78f).v (PID::auraDistance, 0.38f)
            .v (PID::auraFog, 0.52f).v (PID::auraDecay, 0.72f)
            .v (PID::auraLight, 0.04f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.06f)
            .v (PID::patinaNoise, 0.12f).v (PID::patinaWear, 0.14f)
            .v (PID::patinaDrift, 0.26f)
            .v (PID::synthWidth, 1.20f).v (PID::highWidth, 1.30f)
            .v (PID::lowMonoFreq, 150.0f)
            .v (PID::breathAmount, 0.70f).v (PID::breathSpeed, 0.08f)
            .v (PID::breathRandom, 0.60f).v (PID::breathShape, 0.30f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Rate, 0.09f)
            .v (PID::lfo1Depth, 0.70f)
            .v (PID::lfo2Shape, ch::lfoSine).v (PID::lfo2Rate, 0.16f)
            .v (PID::lfo2Depth, 0.50f)
            .route (srcLfo1, PID::filterCutoff, 0.22f)
            .route (srcLfo2, PID::oscBWtPos, 0.20f)
            .route (srcBreath, PID::oscAWtPos, 0.22f)
            .route (srcWorld, PID::spaceSize, 0.12f));

        // No formant in the voice at all: triangle and sine carry the pitch and
        // the creative filter in FORMANT is the only thing making a vowel.
        add (out, Build ("Coro de Vigilia", "VOCAL-LIKE", "DREAMY",
                         "choir,oohs,second filter,long reverb",
                         "Triangle and sine voices whose vowel is made entirely by the creative filter in FORMANT, an air noise layer over them and an INFINITE reverb behind.")
            .at (50, 4, 0.55f, 6.0)
            .chain ("SPACE,FILTER,GRAIN,RETRO,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::masterGain, 4.0f)
            .v (PID::polyphony, 14.0f).v (PID::voiceVariation, 0.48f)
            .v (PID::driftAmount, 0.38f).v (PID::driftRate, 0.05f)
            .v (PID::oscAWave, ch::tri).v (PID::oscALevel, 0.72f)
            .v (PID::oscAUnison, 4.0f).v (PID::oscADetune, 0.15f)
            .v (PID::oscASpread, 0.62f).v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.44f)
            .v (PID::oscBFine, -8.0f).v (PID::oscBUnison, 2.0f)
            .v (PID::oscBDetune, 0.10f).v (PID::oscBSpread, 0.50f)
            .v (PID::oscCWave, ch::wt).v (PID::oscCWtTable, ch::tVocal)
            .v (PID::oscCWtPos, 0.34f).v (PID::oscCLevel, 0.18f)
            .v (PID::oscCOctave, 1.0f)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.10f)
            .v (PID::noiseType, ch::nAir).v (PID::noiseLevel, 0.14f)
            .v (PID::bodyAmount, 0.26f).v (PID::densityAmount, 0.30f)
            .v (PID::postSaturation, 0.06f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 3000.0f).v (PID::filterResonance, 0.10f)
            .v (PID::filterKeyTrack, 0.30f).v (PID::filterEnvAmount, 0.18f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Formant)
            .v (PID::filter2Cutoff, 420.0f).v (PID::filter2Res, 0.46f)
            .v (PID::filter2Mix, 0.72f)
            .v (PID::ampAttack, 1.6f).v (PID::ampDecay, 4.0f)
            .v (PID::ampSustain, 0.88f).v (PID::ampRelease, 5.0f)
            .v (PID::ampVelocity, 0.30f)
            .v (PID::macroMemory, 0.18f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.26f).v (PID::memoryDiffusion, 0.50f)
            .v (PID::macroCharacter, 0.18f).v (PID::macroMotion, 0.58f)
            .v (PID::macroWorld, 0.70f).v (PID::macroWeight, 0.20f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::retroEra, 0.60f).v (PID::retroAge, 0.12f)
            .v (PID::retroDrift, 0.20f).v (PID::retroWear, 0.05f)
            .v (PID::retroNoise, 0.06f).v (PID::retroMix, 0.24f)
            .v (PID::fxFilterCutoff, 11000.0f)
            .v (PID::spaceCharacter, ch::sInfinite).v (PID::spaceDistance, 0.56f)
            .v (PID::spaceSize, 0.88f).v (PID::spaceDecay, 16.0f)
            .v (PID::spaceFog, 0.70f).v (PID::spaceLight, -0.04f)
            .v (PID::spacePreDelay, 40.0f).v (PID::spaceMix, 0.44f)
            .v (PID::auraSize, 0.86f).v (PID::auraDistance, 0.44f)
            .v (PID::auraFog, 0.60f).v (PID::auraDecay, 0.82f)
            .v (PID::auraLight, 0.06f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaNoise, 0.10f)
            .v (PID::patinaWear, 0.12f).v (PID::patinaDrift, 0.24f)
            .v (PID::synthWidth, 1.25f).v (PID::highWidth, 1.35f)
            .v (PID::lowMonoFreq, 160.0f)
            .v (PID::breathAmount, 0.68f).v (PID::breathSpeed, 0.06f)
            .v (PID::breathRandom, 0.55f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.07f)
            .v (PID::lfo1Depth, 0.65f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.12f)
            .v (PID::lfo2Depth, 0.55f)
            .route (srcLfo1, PID::filter2Cutoff, 0.26f)
            .route (srcLfo2, PID::filter2Res, 0.14f)
            .route (srcBreath, PID::oscCLevel, 0.16f)
            .route (srcWorld, PID::auraSize, 0.12f));

        // ---------------------------------------------------------------
        //  SOLO VOCAL-ADJACENT LEADS
        // ---------------------------------------------------------------

        // One legato voice with performance vibrato, and envelope 1 walking
        // the formant upward for as long as the note is held down.
        add (out, Build ("La Garganta", "VOCAL-LIKE", "INTIMATE",
                         "lead,throat,formant,legato",
                         "A saw and a VOCAL table through the FORMANT filter off key track, dark noise for the throat, with envelope 1 opening the formant across the held note.")
            .at (62, 1, 0.78f, 4.5)
            .chain ("FILTER,RETRO,CRUSH,SPACE,REWIND,GRAIN")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::voiceMode, ch::legato).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.09f)
            .v (PID::voiceVariation, 0.20f)
            .v (PID::driftAmount, 0.22f).v (PID::driftRate, 0.18f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.62f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.10f)
            .v (PID::oscASpread, 0.25f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tVocal)
            .v (PID::oscBWtPos, 0.44f).v (PID::oscBLevel, 0.46f)
            .v (PID::oscBFine, 5.0f)
            .v (PID::subLevel, 0.10f).v (PID::subHarmonics, 0.20f)
            .v (PID::noiseType, ch::nDark).v (PID::noiseLevel, 0.20f)
            .v (PID::noiseAttackOnly, 0.25f)
            .v (PID::bodyAmount, 0.38f).v (PID::bodyTilt, 0.15f)
            .v (PID::densityAmount, 0.28f).v (PID::preFilterDrive, 0.22f)
            .v (PID::postSaturation, 0.16f).v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 700.0f).v (PID::filterResonance, 0.52f)
            .v (PID::filterKeyTrack, 0.0f).v (PID::filterEnvAmount, 0.45f)
            .v (PID::filterVelAmount, 0.40f).v (PID::filterDrive, 0.26f)
            .v (PID::env1Attack, 0.35f).v (PID::env1Decay, 2.4f)
            .v (PID::env1Sustain, 0.62f).v (PID::env1Release, 1.2f)
            .v (PID::ampAttack, 0.06f).v (PID::ampDecay, 1.4f)
            .v (PID::ampSustain, 0.86f).v (PID::ampRelease, 0.8f)
            .v (PID::ampVelocity, 0.50f)
            .v (PID::macroMemory, 0.22f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.34f).v (PID::memoryWobble, 0.30f)
            .v (PID::macroCharacter, 0.34f).v (PID::macroMotion, 0.50f)
            .v (PID::macroWorld, 0.30f).v (PID::macroWeight, 0.34f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::retroEra, 0.48f).v (PID::retroAge, 0.24f)
            .v (PID::retroDrift, 0.30f).v (PID::retroWear, 0.12f)
            .v (PID::retroTone, -0.10f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.40f)
            .v (PID::fxFilterMode, ch::f2Bp).v (PID::fxFilterCutoff, 2600.0f)
            .v (PID::fxFilterRes, 0.20f).v (PID::fxFilterMix, 0.45f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.28f)
            .v (PID::spaceSize, 0.40f).v (PID::spaceDecay, 1.8f)
            .v (PID::spaceFog, 0.36f).v (PID::spaceLight, -0.12f)
            .v (PID::spacePreDelay, 26.0f).v (PID::spaceMix, 0.22f)
            .v (PID::auraSize, 0.40f).v (PID::auraDistance, 0.24f)
            .v (PID::auraFog, 0.34f).v (PID::auraDecay, 0.36f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.08f)
            .v (PID::patinaNoise, 0.14f).v (PID::patinaWear, 0.22f)
            .v (PID::patinaDrift, 0.24f)
            .v (PID::synthWidth, 0.80f).v (PID::highWidth, 0.90f)
            .v (PID::vibratoRate, 5.4f).v (PID::vibratoDepth, 0.34f)
            .v (PID::modWheelDepth, 0.70f).v (PID::aftertouchDepth, 0.60f)
            .v (PID::breathAmount, 0.55f).v (PID::breathSpeed, 0.35f)
            .v (PID::breathRandom, 0.50f).v (PID::breathShape, 0.35f)
            .v (PID::lfo1Shape, ch::lfoTri).v (PID::lfo1Rate, 0.80f)
            .v (PID::lfo1Depth, 0.45f)
            .route (srcTouch, PID::filterCutoff, 0.30f)
            .route (srcWheel, PID::filterResonance, 0.20f)
            .route (srcLfo1, PID::oscBWtPos, 0.18f)
            .route (srcBreath, PID::noiseLevel, 0.18f));

        // The vowel here is the wavetable and nothing else: two VOCAL tables
        // sweeping position against a plain MASS low pass.
        add (out, Build ("Lengua de Plata", "VOCAL-LIKE", "MYSTERIOUS",
                         "lead,vocal table,mono,glide",
                         "The vowel comes from the VOCAL wavetable alone, two tables sweeping position behind a MASS low pass, with dark noise under them and glide between notes.")
            .at (64, 1, 0.74f, 4.0)
            .chain ("GRAIN,FILTER,RETRO,SPACE,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.14f)
            .v (PID::voiceVariation, 0.24f)
            .v (PID::driftAmount, 0.26f).v (PID::driftRate, 0.22f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tVocal)
            .v (PID::oscAWtPos, 0.18f).v (PID::oscALevel, 0.74f)
            .v (PID::oscAUnison, 3.0f).v (PID::oscADetune, 0.12f)
            .v (PID::oscASpread, 0.40f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tVocal)
            .v (PID::oscBWtPos, 0.82f).v (PID::oscBLevel, 0.42f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, -6.0f)
            .v (PID::oscPmAmount, 0.10f)
            .v (PID::subLevel, 0.14f).v (PID::subHarmonics, 0.22f)
            .v (PID::noiseType, ch::nDark).v (PID::noiseLevel, 0.12f)
            .v (PID::bodyAmount, 0.34f).v (PID::densityAmount, 0.26f)
            .v (PID::preFilterDrive, 0.18f).v (PID::postSaturation, 0.14f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 2800.0f).v (PID::filterResonance, 0.28f)
            .v (PID::filterKeyTrack, 0.55f).v (PID::filterEnvAmount, 0.34f)
            .v (PID::filterDrive, 0.22f)
            .v (PID::env1Attack, 0.20f).v (PID::env1Decay, 1.8f)
            .v (PID::env1Sustain, 0.45f).v (PID::env1Release, 1.0f)
            .v (PID::ampAttack, 0.04f).v (PID::ampDecay, 1.6f)
            .v (PID::ampSustain, 0.82f).v (PID::ampRelease, 1.1f)
            .v (PID::ampVelocity, 0.48f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.24f)
            .v (PID::grainSize, 110.0f).v (PID::grainDensity, 10.0f)
            .v (PID::grainPosition, 0.18f).v (PID::grainPitchMode, ch::gRoot)
            .v (PID::grainSpread, 0.40f).v (PID::grainJitter, 0.24f)
            .v (PID::grainDirection, 0.10f).v (PID::grainWindow, ch::wGauss)
            .v (PID::grainMix, 0.24f)
            .v (PID::macroMemory, 0.26f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.38f).v (PID::memoryWobble, 0.34f)
            .v (PID::macroCharacter, 0.32f).v (PID::macroMotion, 0.56f)
            .v (PID::macroWorld, 0.38f).v (PID::macroWeight, 0.32f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::retroEra, 0.66f).v (PID::retroAge, 0.22f)
            .v (PID::retroDrift, 0.28f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.38f)
            .v (PID::fxFilterMode, ch::f2Hp).v (PID::fxFilterCutoff, 160.0f)
            .v (PID::fxFilterRes, 0.14f).v (PID::fxFilterMix, 0.60f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.34f)
            .v (PID::spaceSize, 0.52f).v (PID::spaceDecay, 3.0f)
            .v (PID::spaceFog, 0.44f).v (PID::spaceLight, -0.08f)
            .v (PID::spacePreDelay, 30.0f).v (PID::spaceMix, 0.26f)
            .v (PID::auraSize, 0.50f).v (PID::auraDistance, 0.28f)
            .v (PID::auraFog, 0.40f).v (PID::auraDecay, 0.46f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.06f)
            .v (PID::patinaNoise, 0.10f).v (PID::patinaWear, 0.18f)
            .v (PID::patinaDrift, 0.22f)
            .v (PID::synthWidth, 0.90f).v (PID::highWidth, 1.05f)
            .v (PID::vibratoRate, 5.8f).v (PID::vibratoDepth, 0.28f)
            .v (PID::modWheelDepth, 0.65f)
            .v (PID::breathAmount, 0.52f).v (PID::breathSpeed, 0.30f)
            .v (PID::breathRandom, 0.55f)
            .v (PID::lfo1Shape, ch::lfoTri).v (PID::lfo1Rate, 0.45f)
            .v (PID::lfo1Depth, 0.60f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.90f)
            .v (PID::lfo2Depth, 0.45f)
            .route (srcLfo1, PID::oscAWtPos, 0.34f)
            .route (srcLfo2, PID::oscBWtPos, 0.28f)
            .route (srcWheel, PID::filterCutoff, 0.25f)
            .route (srcBreath, PID::grainPosition, 0.20f));

        // ---------------------------------------------------------------
        //  TALKBOX AND VOCODER-ADJACENT
        // ---------------------------------------------------------------

        // A pulse-width square and a synced saw into the FORMANT filter, with
        // PULSE on the quarter note moving the formant on the grid.
        add (out, Build ("Talkbox Prayer", "VOCAL-LIKE", "WARM",
                         "talkbox,pulse,formant,speech",
                         "A pulse-width square and a hard-synced saw through the FORMANT filter, with PULSE on the quarter note driving the formant so the vowel changes on the grid.")
            .at (55, 1, 0.82f, 4.0)
            .chain ("CRUSH,FILTER,SPACE,RETRO,REWIND,GRAIN")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::masterGain, -2.0f)
            .v (PID::voiceMode, ch::mono).v (PID::polyphony, 1.0f)
            .v (PID::glideTime, 0.05f)
            .v (PID::voiceVariation, 0.22f)
            .v (PID::driftAmount, 0.20f).v (PID::driftRate, 0.30f)
            .v (PID::oscAWave, ch::square).v (PID::oscAPulseWidth, 0.34f)
            .v (PID::oscALevel, 0.70f).v (PID::oscAUnison, 2.0f)
            .v (PID::oscADetune, 0.08f).v (PID::oscASpread, 0.20f)
            .v (PID::oscBWave, ch::saw).v (PID::oscBLevel, 0.40f)
            .v (PID::oscBFine, 6.0f)
            .v (PID::oscSync, 0.18f)
            .v (PID::subLevel, 0.16f).v (PID::subHarmonics, 0.28f)
            .v (PID::noiseType, ch::nWhite).v (PID::noiseLevel, 0.10f)
            .v (PID::noiseAttackOnly, 0.40f)
            .v (PID::bodyAmount, 0.34f).v (PID::densityAmount, 0.30f)
            .v (PID::preFilterDrive, 0.30f).v (PID::postSaturation, 0.20f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 820.0f).v (PID::filterResonance, 0.58f)
            .v (PID::filterKeyTrack, 0.0f).v (PID::filterEnvAmount, 0.30f)
            .v (PID::filterVelAmount, 0.35f).v (PID::filterDrive, 0.30f)
            .v (PID::env1Attack, 0.01f).v (PID::env1Decay, 0.50f)
            .v (PID::env1Sustain, 0.40f).v (PID::env1Release, 0.40f)
            .v (PID::ampAttack, 0.01f).v (PID::ampDecay, 0.90f)
            .v (PID::ampSustain, 0.84f).v (PID::ampRelease, 0.50f)
            .v (PID::ampVelocity, 0.55f)
            .v (PID::pulseOn, 1.0f).v (PID::pulseSource, ch::pClock)
            .v (PID::pulseDivision, ch::p4).v (PID::pulseDepth, 0.62f)
            .v (PID::pulseAttack, 0.004f).v (PID::pulseRelease, 0.18f)
            .v (PID::pulseSmooth, 0.35f).v (PID::pulseToVolume, 0.45f)
            .v (PID::pulseToFilter, 0.70f).v (PID::pulseToSpace, 0.25f)
            .v (PID::pulseToWidth, 0.15f)
            .v (PID::macroMemory, 0.24f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.36f)
            .v (PID::macroCharacter, 0.44f).v (PID::macroMotion, 0.60f)
            .v (PID::macroWorld, 0.30f).v (PID::macroWeight, 0.36f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.40f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.22f)
            .v (PID::crushBits, 11.0f).v (PID::crushRate, 20000.0f)
            .v (PID::crushDrive, 0.18f).v (PID::crushTone, 0.06f)
            .v (PID::crushMix, 0.35f)
            .v (PID::retroEra, 0.52f).v (PID::retroAge, 0.20f)
            .v (PID::retroDrift, 0.20f).v (PID::retroNoise, 0.08f)
            .v (PID::retroMix, 0.36f)
            .v (PID::fxFilterMode, ch::f2Bp).v (PID::fxFilterCutoff, 2000.0f)
            .v (PID::fxFilterRes, 0.22f).v (PID::fxFilterMix, 0.50f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.24f)
            .v (PID::spaceSize, 0.34f).v (PID::spaceDecay, 1.4f)
            .v (PID::spaceFog, 0.30f).v (PID::spacePreDelay, 18.0f)
            .v (PID::spaceMix, 0.18f)
            .v (PID::auraSize, 0.34f).v (PID::auraDistance, 0.20f)
            .v (PID::auraFog, 0.30f).v (PID::auraDecay, 0.30f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaNoise, 0.12f)
            .v (PID::patinaWear, 0.20f).v (PID::patinaDrift, 0.18f)
            .v (PID::synthWidth, 0.85f).v (PID::highWidth, 0.95f)
            .v (PID::breathAmount, 0.40f).v (PID::breathSpeed, 0.60f)
            .v (PID::breathRandom, 0.45f)
            .v (PID::lfo1Sync, 1.0f).v (PID::lfo1Shape, ch::lfoSquare)
            .v (PID::lfo1Division, ch::d8).v (PID::lfo1Depth, 0.50f)
            .route (srcPulse, PID::filterCutoff, 0.45f)
            .route (srcLfo1, PID::oscAPulseWidth, 0.24f)
            .route (srcBreath, PID::filterResonance, 0.16f)
            .route (srcWheel, PID::fxFilterCutoff, 0.25f));

        // The vowel is made in the chain rather than in the voice: the FX
        // filter in FORMANT, stepped by a random LFO locked to sixteenths.
        add (out, Build ("Wire Throat", "VOCAL-LIKE", "DIRTY",
                         "talkbox,chain filter,sixteenths,formant",
                         "A saw and square pair given their vowel by the FX filter set to FORMANT, its cutoff stepped by LFO 1 locked to sixteenths and bit-reduced first.")
            .at (57, 1, 0.80f, 4.0)
            .chain ("CRUSH,FILTER,RETRO,REWIND,GRAIN,SPACE")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::masterGain, -3.0f)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.30f)
            .v (PID::driftAmount, 0.22f).v (PID::driftRate, 0.40f)
            .v (PID::oscAWave, ch::saw).v (PID::oscALevel, 0.68f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.12f)
            .v (PID::oscASpread, 0.30f)
            .v (PID::oscBWave, ch::square).v (PID::oscBPulseWidth, 0.42f)
            .v (PID::oscBLevel, 0.42f).v (PID::oscBFine, -7.0f)
            .v (PID::oscRingMod, 0.10f)
            .v (PID::subLevel, 0.12f)
            .v (PID::noiseType, ch::nDigital).v (PID::noiseLevel, 0.10f)
            .v (PID::bodyAmount, 0.24f).v (PID::densityAmount, 0.26f)
            .v (PID::preFilterDrive, 0.26f).v (PID::postSaturation, 0.22f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 6000.0f).v (PID::filterResonance, 0.18f)
            .v (PID::filterKeyTrack, 0.45f).v (PID::filterEnvAmount, 0.22f)
            .v (PID::ampAttack, 0.01f).v (PID::ampDecay, 1.0f)
            .v (PID::ampSustain, 0.80f).v (PID::ampRelease, 0.50f)
            .v (PID::ampVelocity, 0.50f)
            .v (PID::fxFilterOn, 1.0f).v (PID::fxFilterMode, ch::f2Formant)
            .v (PID::fxFilterCutoff, 900.0f).v (PID::fxFilterRes, 0.52f)
            .v (PID::fxFilterDrive, 0.22f).v (PID::fxFilterMorph, 0.12f)
            .v (PID::fxFilterMotion, 0.30f).v (PID::fxFilterMix, 0.88f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.34f)
            .v (PID::crushBits, 10.0f).v (PID::crushRate, 16000.0f)
            .v (PID::crushJitter, 0.18f).v (PID::crushDrive, 0.22f)
            .v (PID::crushTone, 0.05f).v (PID::crushMix, 0.48f)
            .v (PID::rewindOn, 1.0f).v (PID::rewindMode, ch::rStop)
            .v (PID::rewindDivision, ch::rw16).v (PID::rewindCurve, 0.40f)
            .v (PID::rewindTail, 0.22f).v (PID::rewindMix, 0.35f)
            .v (PID::macroMemory, 0.30f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.44f).v (PID::memoryWobble, 0.30f)
            .v (PID::macroCharacter, 0.52f).v (PID::macroMotion, 0.66f)
            .v (PID::macroWorld, 0.28f).v (PID::macroWeight, 0.28f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::retroEra, 0.80f).v (PID::retroAge, 0.28f)
            .v (PID::retroDrift, 0.20f).v (PID::retroWear, 0.18f)
            .v (PID::retroNoise, 0.12f).v (PID::retroMix, 0.46f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.26f)
            .v (PID::spaceSize, 0.32f).v (PID::spaceDecay, 1.2f)
            .v (PID::spaceFog, 0.28f).v (PID::spaceLight, -0.05f)
            .v (PID::spacePreDelay, 14.0f).v (PID::spaceMix, 0.16f)
            .v (PID::auraSize, 0.32f).v (PID::auraDistance, 0.18f)
            .v (PID::auraFog, 0.28f).v (PID::auraDecay, 0.26f)
            .v (PID::patinaProfile, ch::pChrome).v (PID::patinaTone, 0.08f)
            .v (PID::patinaNoise, 0.12f).v (PID::patinaWear, 0.22f)
            .v (PID::patinaDrift, 0.16f)
            .v (PID::synthWidth, 0.95f).v (PID::highWidth, 1.05f)
            .v (PID::breathAmount, 0.34f).v (PID::breathSpeed, 0.90f)
            .v (PID::lfo1Sync, 1.0f).v (PID::lfo1Shape, ch::lfoRandom)
            .v (PID::lfo1Division, ch::d16).v (PID::lfo1Depth, 0.75f)
            .v (PID::lfo2Sync, 1.0f).v (PID::lfo2Shape, ch::lfoSquare)
            .v (PID::lfo2Division, ch::d8).v (PID::lfo2Depth, 0.45f)
            .route (srcLfo1, PID::fxFilterCutoff, 0.55f)
            .route (srcLfo2, PID::fxFilterRes, 0.22f)
            .route (srcBreath, PID::fxFilterMorph, 0.18f)
            .route (srcOrganic, PID::crushRate, -0.16f));

        // Vocoder-adjacent: the creative filter in FORMANT switched on eighths
        // by a square LFO, then bit-reduced and granulated.
        add (out, Build ("Lengua Rota", "VOCAL-LIKE", "BROKEN",
                         "vocoder,second filter,eighths,granular",
                         "A VOCAL table and an ASYMMETRIC table into the creative filter in FORMANT, its cutoff switched on eighths by a square LFO, then bit-reduced and granulated.")
            .at (52, 2, 0.76f, 5.0)
            .chain ("CRUSH,FILTER,GRAIN,RETRO,SPACE,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::masterGain, -5.8f)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.44f)
            .v (PID::driftAmount, 0.30f).v (PID::driftRate, 0.35f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tVocal)
            .v (PID::oscAWtPos, 0.40f).v (PID::oscALevel, 0.72f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tAsym)
            .v (PID::oscBWtPos, 0.55f).v (PID::oscBLevel, 0.34f)
            .v (PID::oscBFine, 11.0f)
            .v (PID::subLevel, 0.10f)
            .v (PID::noiseType, ch::nDigital).v (PID::noiseLevel, 0.12f)
            .v (PID::bodyAmount, 0.22f).v (PID::densityAmount, 0.24f)
            .v (PID::preFilterDrive, 0.20f).v (PID::postSaturation, 0.18f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 2400.0f).v (PID::filterResonance, 0.24f)
            .v (PID::filterKeyTrack, 0.35f).v (PID::filterEnvAmount, 0.26f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Formant)
            .v (PID::filter2Cutoff, 640.0f).v (PID::filter2Res, 0.56f)
            .v (PID::filter2Mix, 0.80f)
            .v (PID::ampAttack, 0.02f).v (PID::ampDecay, 1.3f)
            .v (PID::ampSustain, 0.74f).v (PID::ampRelease, 0.70f)
            .v (PID::ampVelocity, 0.45f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.44f)
            .v (PID::crushBits, 7.0f).v (PID::crushRate, 11000.0f)
            .v (PID::crushJitter, 0.30f).v (PID::crushDrive, 0.22f)
            .v (PID::crushTone, -0.08f).v (PID::crushMix, 0.56f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.40f)
            .v (PID::grainSize, 60.0f).v (PID::grainDensity, 20.0f)
            .v (PID::grainPosition, 0.22f).v (PID::grainPitchMode, ch::gChromatic)
            .v (PID::grainSpread, 0.55f).v (PID::grainJitter, 0.45f)
            .v (PID::grainDirection, 0.22f).v (PID::grainWindow, ch::wTukey)
            .v (PID::grainMix, 0.36f)
            .v (PID::macroMemory, 0.46f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.56f).v (PID::memoryWobble, 0.48f)
            .v (PID::memoryDiffusion, 0.40f).v (PID::memoryAsymmetry, 0.44f)
            .v (PID::macroCharacter, 0.58f).v (PID::macroMotion, 0.68f)
            .v (PID::macroWorld, 0.34f).v (PID::macroWeight, 0.24f)
            .v (PID::retroEra, 0.88f).v (PID::retroAge, 0.34f)
            .v (PID::retroDrift, 0.30f).v (PID::retroWear, 0.30f)
            .v (PID::retroNoise, 0.16f).v (PID::retroMix, 0.58f)
            .v (PID::fxFilterMode, ch::f2Notch).v (PID::fxFilterCutoff, 3200.0f)
            .v (PID::fxFilterRes, 0.20f).v (PID::fxFilterMix, 0.40f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.34f)
            .v (PID::spaceSize, 0.46f).v (PID::spaceDecay, 2.4f)
            .v (PID::spaceFog, 0.44f).v (PID::spaceLight, -0.14f)
            .v (PID::spacePreDelay, 22.0f).v (PID::spaceMix, 0.24f)
            .v (PID::auraSize, 0.44f).v (PID::auraDistance, 0.26f)
            .v (PID::auraFog, 0.42f).v (PID::auraDecay, 0.38f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaNoise, 0.22f)
            .v (PID::patinaWear, 0.38f).v (PID::patinaDrift, 0.34f)
            .v (PID::synthWidth, 1.05f).v (PID::highWidth, 1.15f)
            .v (PID::breathAmount, 0.48f).v (PID::breathSpeed, 0.70f)
            .v (PID::breathRandom, 0.75f).v (PID::breathShape, 0.75f)
            .v (PID::lfo1Shape, ch::lfoRandom).v (PID::lfo1Rate, 3.2f)
            .v (PID::lfo1Depth, 0.50f)
            .v (PID::lfo2Sync, 1.0f).v (PID::lfo2Shape, ch::lfoSquare)
            .v (PID::lfo2Division, ch::d8).v (PID::lfo2Depth, 0.70f)
            .route (srcLfo2, PID::filter2Cutoff, 0.50f)
            .route (srcLfo1, PID::grainPosition, 0.30f)
            .route (srcMemory, PID::filter2Res, 0.18f)
            .route (srcBreath, PID::crushBits, -0.20f));

        // ---------------------------------------------------------------
        //  WHISPERS AND BREATH TEXTURES
        // ---------------------------------------------------------------

        // Noise carries almost the whole signal; the oscillators are there to
        // give the FORMANT filter something tuned to sit against.
        add (out, Build ("Susurro", "VOCAL-LIKE", "MINIMAL",
                         "whisper,noise,formant,close",
                         "Air noise at three quarters level with only a trace of oscillator under it, the FORMANT filter off key track supplying the vowel and envelope 1 moving it while the note is held.")
            .at (60, 2, 0.50f, 5.0)
            .chain ("FILTER,GRAIN,SPACE,CRUSH,RETRO,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::masterGain, 6.0f)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.40f)
            .v (PID::driftAmount, 0.30f).v (PID::driftRate, 0.10f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tVocal)
            .v (PID::oscAWtPos, 0.30f).v (PID::oscALevel, 0.10f)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.06f)
            .v (PID::oscBOctave, -1.0f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nAir).v (PID::noiseLevel, 0.78f)
            .v (PID::bodyAmount, 0.14f).v (PID::densityAmount, 0.16f)
            .v (PID::postSaturation, 0.06f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 1050.0f).v (PID::filterResonance, 0.62f)
            .v (PID::filterKeyTrack, 0.0f).v (PID::filterEnvAmount, 0.38f)
            .v (PID::filterVelAmount, 0.30f)
            .v (PID::env1Attack, 0.90f).v (PID::env1Decay, 3.0f)
            .v (PID::env1Sustain, 0.50f).v (PID::env1Release, 2.0f)
            .v (PID::ampAttack, 0.35f).v (PID::ampDecay, 2.2f)
            .v (PID::ampSustain, 0.78f).v (PID::ampRelease, 2.2f)
            .v (PID::ampVelocity, 0.40f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.26f)
            .v (PID::grainSize, 140.0f).v (PID::grainDensity, 8.0f)
            .v (PID::grainPosition, 0.30f).v (PID::grainPitchMode, ch::gRoot)
            .v (PID::grainSpread, 0.62f).v (PID::grainJitter, 0.30f)
            .v (PID::grainDirection, 0.14f).v (PID::grainWindow, ch::wGauss)
            .v (PID::grainMix, 0.28f)
            .v (PID::macroMemory, 0.18f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.24f)
            .v (PID::macroCharacter, 0.20f).v (PID::macroMotion, 0.56f)
            .v (PID::macroWorld, 0.48f).v (PID::macroWeight, 0.12f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::retroEra, 0.46f).v (PID::retroAge, 0.14f)
            .v (PID::retroDrift, 0.18f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.26f)
            .v (PID::fxFilterMode, ch::f2Hp).v (PID::fxFilterCutoff, 220.0f)
            .v (PID::fxFilterRes, 0.10f).v (PID::fxFilterMix, 0.70f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.50f)
            .v (PID::spaceSize, 0.60f).v (PID::spaceDecay, 4.0f)
            .v (PID::spaceFog, 0.56f).v (PID::spaceLight, 0.02f)
            .v (PID::spacePreDelay, 24.0f).v (PID::spaceMix, 0.30f)
            .v (PID::auraSize, 0.60f).v (PID::auraDistance, 0.36f)
            .v (PID::auraFog, 0.48f).v (PID::auraDecay, 0.52f)
            .v (PID::auraLight, 0.08f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaNoise, 0.16f)
            .v (PID::patinaWear, 0.14f).v (PID::patinaDrift, 0.22f)
            .v (PID::synthWidth, 1.15f).v (PID::highWidth, 1.25f)
            .v (PID::breathAmount, 0.80f).v (PID::breathSpeed, 0.18f)
            .v (PID::breathRandom, 0.65f).v (PID::breathShape, 0.40f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Rate, 0.20f)
            .v (PID::lfo1Depth, 0.70f)
            .route (srcBreath, PID::filterCutoff, 0.34f)
            .route (srcLfo1, PID::filterResonance, 0.20f)
            .route (srcOrganic, PID::noiseLevel, -0.14f)
            .route (srcWorld, PID::spaceDistance, 0.14f));

        // Texture noise granulated first and given its vowel last: FILTER sits
        // at the end of the chain, in FORMANT, over the grain cloud.
        add (out, Build ("Sin Palabras", "VOCAL-LIKE", "AIRY",
                         "breath,texture,chain filter,granular",
                         "Texture noise with a trace of the VOCAL table, granulated and reverberated first and only then given a vowel by the FX filter in FORMANT at the end of the chain.")
            .at (58, 3, 0.48f, 6.0)
            .chain ("REWIND,GRAIN,SPACE,RETRO,CRUSH,FILTER")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::masterGain, 6.0f)
            .v (PID::polyphony, 10.0f).v (PID::voiceVariation, 0.46f)
            .v (PID::driftAmount, 0.34f).v (PID::driftRate, 0.09f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tVocal)
            .v (PID::oscAWtPos, 0.66f).v (PID::oscALevel, 0.14f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.14f)
            .v (PID::oscASpread, 0.55f)
            .v (PID::oscBWave, ch::tri).v (PID::oscBLevel, 0.08f)
            .v (PID::oscBOctave, -1.0f)
            .v (PID::subLevel, 0.04f)
            .v (PID::noiseType, ch::nTexture).v (PID::noiseLevel, 0.72f)
            .v (PID::bodyAmount, 0.12f).v (PID::densityAmount, 0.18f)
            .v (PID::postSaturation, 0.05f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 1800.0f).v (PID::filterResonance, 0.16f)
            .v (PID::filterKeyTrack, 0.20f)
            .v (PID::ampAttack, 1.2f).v (PID::ampDecay, 3.4f)
            .v (PID::ampSustain, 0.82f).v (PID::ampRelease, 3.2f)
            .v (PID::ampVelocity, 0.32f)
            .v (PID::fxFilterOn, 1.0f).v (PID::fxFilterMode, ch::f2Formant)
            .v (PID::fxFilterCutoff, 760.0f).v (PID::fxFilterRes, 0.50f)
            .v (PID::fxFilterMorph, 0.18f).v (PID::fxFilterMotion, 0.35f)
            .v (PID::fxFilterMix, 0.85f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.48f)
            .v (PID::grainSize, 170.0f).v (PID::grainDensity, 12.0f)
            .v (PID::grainPosition, 0.36f).v (PID::grainPitchMode, ch::gFifth)
            .v (PID::grainSpread, 0.70f).v (PID::grainJitter, 0.40f)
            .v (PID::grainDirection, 0.26f).v (PID::grainWindow, ch::wGauss)
            .v (PID::grainFeedback, 0.14f).v (PID::grainMix, 0.46f)
            .v (PID::macroMemory, 0.24f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.30f).v (PID::memoryDiffusion, 0.48f)
            .v (PID::macroCharacter, 0.22f).v (PID::macroMotion, 0.62f)
            .v (PID::macroWorld, 0.66f).v (PID::macroWeight, 0.14f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::retroEra, 0.42f).v (PID::retroAge, 0.16f)
            .v (PID::retroDrift, 0.22f).v (PID::retroNoise, 0.12f)
            .v (PID::retroMix, 0.28f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.58f)
            .v (PID::spaceSize, 0.78f).v (PID::spaceDecay, 7.5f)
            .v (PID::spaceFog, 0.66f).v (PID::spacePreDelay, 36.0f)
            .v (PID::spaceMix, 0.38f)
            .v (PID::auraSize, 0.80f).v (PID::auraDistance, 0.44f)
            .v (PID::auraFog, 0.58f).v (PID::auraDecay, 0.74f)
            .v (PID::auraLight, 0.10f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaNoise, 0.20f)
            .v (PID::patinaWear, 0.20f).v (PID::patinaDrift, 0.28f)
            .v (PID::synthWidth, 1.25f).v (PID::highWidth, 1.35f)
            .v (PID::breathAmount, 0.78f).v (PID::breathSpeed, 0.12f)
            .v (PID::breathRandom, 0.70f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Rate, 0.10f)
            .v (PID::lfo1Depth, 0.65f)
            .v (PID::lfo2Shape, ch::lfoSine).v (PID::lfo2Rate, 0.05f)
            .v (PID::lfo2Depth, 0.50f)
            .route (srcLfo1, PID::fxFilterCutoff, 0.30f)
            .route (srcLfo2, PID::grainPosition, 0.26f)
            .route (srcBreath, PID::fxFilterRes, 0.16f)
            .route (srcMotion, PID::grainSize, 0.20f));

        // ---------------------------------------------------------------
        //  URBANO VOCAL BEDS
        // ---------------------------------------------------------------

        // Grain and rewind both sit ahead of the reverb, so what the room
        // receives is already chopped and already running backwards.
        add (out, Build ("Voz Cortada", "VOCAL-LIKE", "NOSTALGIC",
                         "urbano,vocal chop,granular,rewind",
                         "A sustained VOCAL table vowel through the FORMANT filter, cut into octave grains and reversed by REWIND on eighths before the reverb ever receives it.")
            .at (55, 2, 0.72f, 5.0)
            .chain ("RETRO,FILTER,GRAIN,REWIND,SPACE,CRUSH")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::masterGain, -1.0f)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.42f)
            .v (PID::driftAmount, 0.30f).v (PID::driftRate, 0.16f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tVocal)
            .v (PID::oscAWtPos, 0.34f).v (PID::oscALevel, 0.76f)
            .v (PID::oscAUnison, 3.0f).v (PID::oscADetune, 0.14f)
            .v (PID::oscASpread, 0.45f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tOrganic)
            .v (PID::oscBWtPos, 0.48f).v (PID::oscBLevel, 0.30f)
            .v (PID::oscBFine, -9.0f)
            .v (PID::subLevel, 0.12f).v (PID::subHarmonics, 0.20f)
            .v (PID::noiseType, ch::nPink).v (PID::noiseLevel, 0.12f)
            .v (PID::bodyAmount, 0.26f).v (PID::densityAmount, 0.28f)
            .v (PID::preFilterDrive, 0.16f).v (PID::postSaturation, 0.14f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 760.0f).v (PID::filterResonance, 0.46f)
            .v (PID::filterKeyTrack, 0.05f).v (PID::filterEnvAmount, 0.28f)
            .v (PID::filterVelAmount, 0.30f)
            .v (PID::env1Attack, 0.15f).v (PID::env1Decay, 1.6f)
            .v (PID::env1Sustain, 0.50f).v (PID::env1Release, 1.0f)
            .v (PID::ampAttack, 0.03f).v (PID::ampDecay, 1.8f)
            .v (PID::ampSustain, 0.80f).v (PID::ampRelease, 1.4f)
            .v (PID::ampVelocity, 0.42f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.56f)
            .v (PID::grainSize, 55.0f).v (PID::grainDensity, 24.0f)
            .v (PID::grainPosition, 0.28f).v (PID::grainPitchMode, ch::gOctave)
            .v (PID::grainSpread, 0.62f).v (PID::grainJitter, 0.50f)
            .v (PID::grainDirection, 0.40f).v (PID::grainWindow, ch::wTukey)
            .v (PID::grainFeedback, 0.16f).v (PID::grainMix, 0.52f)
            .v (PID::rewindOn, 1.0f).v (PID::rewindMode, ch::rReverse)
            .v (PID::rewindDivision, ch::rw8).v (PID::rewindCurve, 0.55f)
            .v (PID::rewindTail, 0.40f).v (PID::rewindMix, 0.58f)
            .v (PID::macroMemory, 0.44f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.50f).v (PID::memoryWobble, 0.42f)
            .v (PID::memoryDiffusion, 0.40f)
            .v (PID::macroCharacter, 0.40f).v (PID::macroMotion, 0.70f)
            .v (PID::macroWorld, 0.44f).v (PID::macroWeight, 0.26f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::retroEra, 0.36f).v (PID::retroAge, 0.34f)
            .v (PID::retroDrift, 0.34f).v (PID::retroWear, 0.22f)
            .v (PID::retroTone, -0.12f).v (PID::retroNoise, 0.16f)
            .v (PID::retroMix, 0.58f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.20f)
            .v (PID::crushBits, 12.0f).v (PID::crushRate, 18000.0f)
            .v (PID::crushMix, 0.30f)
            .v (PID::fxFilterCutoff, 8000.0f).v (PID::fxFilterRes, 0.12f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.40f)
            .v (PID::spaceSize, 0.56f).v (PID::spaceDecay, 3.4f)
            .v (PID::spaceFog, 0.50f).v (PID::spaceLight, -0.10f)
            .v (PID::spacePreDelay, 28.0f).v (PID::spaceMix, 0.32f)
            .v (PID::auraSize, 0.56f).v (PID::auraDistance, 0.32f)
            .v (PID::auraFog, 0.46f).v (PID::auraDecay, 0.50f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.10f)
            .v (PID::patinaNoise, 0.18f).v (PID::patinaWear, 0.30f)
            .v (PID::patinaDrift, 0.30f)
            .v (PID::synthWidth, 1.10f).v (PID::highWidth, 1.20f)
            .v (PID::breathAmount, 0.56f).v (PID::breathSpeed, 0.26f)
            .v (PID::breathRandom, 0.62f)
            .v (PID::lfo1Sync, 1.0f).v (PID::lfo1Shape, ch::lfoSawDown)
            .v (PID::lfo1Division, ch::d16).v (PID::lfo1Depth, 0.60f)
            .route (srcLfo1, PID::grainPosition, 0.36f)
            .route (srcBreath, PID::filterCutoff, 0.22f)
            .route (srcOrganic, PID::grainDirection, 0.24f)
            .route (srcMotion, PID::rewindMix, 0.18f));

        // The opposite order to Voz Cortada: SPACE is built first and GRAIN
        // takes the finished reverb apart, with the vowel applied after that.
        add (out, Build ("Rezo Invertido", "VOCAL-LIKE", "HAUNTED",
                         "urbano,reverse,granular,reverb",
                         "An INFINITE reverb built before the grain engine rather than after it, so the cloud is made out of tail, with the FX filter in FORMANT holding one vowel over the result.")
            .at (56, 2, 0.68f, 5.0)
            .chain ("RETRO,SPACE,GRAIN,FILTER,REWIND,CRUSH")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::masterGain, 2.0f)
            .v (PID::polyphony, 10.0f).v (PID::voiceVariation, 0.50f)
            .v (PID::driftAmount, 0.36f).v (PID::driftRate, 0.08f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tVocal)
            .v (PID::oscAWtPos, 0.56f).v (PID::oscALevel, 0.70f)
            .v (PID::oscAUnison, 3.0f).v (PID::oscADetune, 0.16f)
            .v (PID::oscASpread, 0.55f).v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tHollow)
            .v (PID::oscBWtPos, 0.38f).v (PID::oscBLevel, 0.32f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, 8.0f)
            .v (PID::subLevel, 0.10f)
            .v (PID::noiseType, ch::nTexture).v (PID::noiseLevel, 0.16f)
            .v (PID::bodyAmount, 0.24f).v (PID::densityAmount, 0.30f)
            .v (PID::postSaturation, 0.10f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 3400.0f).v (PID::filterResonance, 0.16f)
            .v (PID::filterKeyTrack, 0.30f).v (PID::filterEnvAmount, 0.22f)
            .v (PID::ampAttack, 0.70f).v (PID::ampDecay, 2.6f)
            .v (PID::ampSustain, 0.82f).v (PID::ampRelease, 3.0f)
            .v (PID::ampVelocity, 0.36f)
            .v (PID::fxFilterOn, 1.0f).v (PID::fxFilterMode, ch::f2Formant)
            .v (PID::fxFilterCutoff, 560.0f).v (PID::fxFilterRes, 0.54f)
            .v (PID::fxFilterMorph, 0.10f).v (PID::fxFilterMotion, 0.28f)
            .v (PID::fxFilterMix, 0.80f)
            .v (PID::spaceCharacter, ch::sInfinite).v (PID::spaceDistance, 0.54f)
            .v (PID::spaceSize, 0.86f).v (PID::spaceDecay, 14.0f)
            .v (PID::spaceFog, 0.72f).v (PID::spaceLight, -0.16f)
            .v (PID::spacePreDelay, 44.0f).v (PID::spaceMix, 0.52f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.66f)
            .v (PID::grainSize, 90.0f).v (PID::grainDensity, 18.0f)
            .v (PID::grainPosition, 0.44f).v (PID::grainPitchMode, ch::gFifth)
            .v (PID::grainSpread, 0.72f).v (PID::grainJitter, 0.56f)
            .v (PID::grainDirection, 0.62f).v (PID::grainWindow, ch::wExpo)
            .v (PID::grainFeedback, 0.22f).v (PID::grainMix, 0.60f)
            .v (PID::rewindOn, 1.0f).v (PID::rewindMode, ch::rReverse)
            .v (PID::rewindDivision, ch::rw4).v (PID::rewindCurve, 0.62f)
            .v (PID::rewindSpeed, 0.8f).v (PID::rewindTail, 0.46f)
            .v (PID::rewindMix, 0.50f)
            .v (PID::macroMemory, 0.50f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.58f).v (PID::memoryWobble, 0.48f)
            .v (PID::memoryDiffusion, 0.56f).v (PID::memoryAsymmetry, 0.44f)
            .v (PID::macroCharacter, 0.36f).v (PID::macroMotion, 0.72f)
            .v (PID::macroWorld, 0.68f).v (PID::macroWeight, 0.20f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::retroEra, 0.40f).v (PID::retroAge, 0.38f)
            .v (PID::retroDrift, 0.36f).v (PID::retroWear, 0.24f)
            .v (PID::retroTone, -0.18f).v (PID::retroNoise, 0.16f)
            .v (PID::retroMix, 0.56f)
            .v (PID::shadowOn, 1.0f).v (PID::shadowLength, 0.52f)
            .v (PID::shadowDistance, 0.66f).v (PID::shadowBlur, 0.60f)
            .v (PID::shadowPitch, -12.0f).v (PID::shadowLevel, 0.24f)
            .v (PID::auraSize, 0.82f).v (PID::auraDistance, 0.46f)
            .v (PID::auraFog, 0.62f).v (PID::auraDecay, 0.78f)
            .v (PID::auraLight, -0.10f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.14f)
            .v (PID::patinaNoise, 0.22f).v (PID::patinaWear, 0.36f)
            .v (PID::patinaDrift, 0.36f)
            .v (PID::synthWidth, 1.20f).v (PID::highWidth, 1.30f)
            .v (PID::breathAmount, 0.66f).v (PID::breathSpeed, 0.10f)
            .v (PID::breathRandom, 0.72f)
            .v (PID::lfo2Sync, 1.0f).v (PID::lfo2Shape, ch::lfoSawDown)
            .v (PID::lfo2Division, ch::d2).v (PID::lfo2Depth, 0.60f)
            .route (srcLfo2, PID::grainPosition, 0.40f)
            .route (srcBreath, PID::fxFilterCutoff, 0.26f)
            .route (srcMemory, PID::grainDirection, 0.24f)
            .route (srcWorld, PID::spaceSize, 0.14f));

        // No formant filter anywhere: PULSE on sixteenths drags the VOCAL
        // table's own position, and REWIND in RETURN puts each chop back.
        add (out, Build ("Coro de Barrio", "VOCAL-LIKE", "ROMANTIC",
                         "urbano,vocal table,pulse,chop",
                         "The vowel is the VOCAL table position itself, dragged by PULSE on sixteenths, with REWIND set to RETURN so each chop lands back on the note.")
            .at (57, 3, 0.70f, 5.0)
            .chain ("FILTER,REWIND,CRUSH,GRAIN,RETRO,SPACE")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.46f)
            .v (PID::driftAmount, 0.28f).v (PID::driftRate, 0.20f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tVocal)
            .v (PID::oscAWtPos, 0.24f).v (PID::oscALevel, 0.76f)
            .v (PID::oscAUnison, 4.0f).v (PID::oscADetune, 0.18f)
            .v (PID::oscASpread, 0.58f).v (PID::oscAPhase, ch::phaseReset)
            .v (PID::oscAPhaseOffset, 0.12f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tVocal)
            .v (PID::oscBWtPos, 0.70f).v (PID::oscBLevel, 0.38f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, -10.0f)
            .v (PID::oscCWave, ch::sine).v (PID::oscCLevel, 0.12f)
            .v (PID::oscCOctave, -1.0f)
            .v (PID::subLevel, 0.18f).v (PID::subOctave, ch::subMinus1)
            .v (PID::subHarmonics, 0.26f)
            .v (PID::noiseType, ch::nPink).v (PID::noiseLevel, 0.10f)
            .v (PID::bodyAmount, 0.30f).v (PID::densityAmount, 0.30f)
            .v (PID::preFilterDrive, 0.14f).v (PID::postSaturation, 0.12f)
            .v (PID::postSatMode, ch::satWarm)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 3200.0f).v (PID::filterResonance, 0.24f)
            .v (PID::filterKeyTrack, 0.50f).v (PID::filterEnvAmount, 0.30f)
            .v (PID::filterVelAmount, 0.35f)
            .v (PID::ampAttack, 0.02f).v (PID::ampDecay, 1.6f)
            .v (PID::ampSustain, 0.78f).v (PID::ampRelease, 1.2f)
            .v (PID::ampVelocity, 0.46f)
            .v (PID::pulseOn, 1.0f).v (PID::pulseSource, ch::pClock)
            .v (PID::pulseDivision, ch::p16).v (PID::pulseDepth, 0.58f)
            .v (PID::pulseAttack, 0.003f).v (PID::pulseRelease, 0.10f)
            .v (PID::pulseSmooth, 0.45f).v (PID::pulseToVolume, 0.72f)
            .v (PID::pulseToFilter, 0.30f).v (PID::pulseToSpace, 0.30f)
            .v (PID::pulseToWidth, 0.20f)
            .v (PID::rewindOn, 1.0f).v (PID::rewindMode, ch::rReturn)
            .v (PID::rewindDivision, ch::rw16).v (PID::rewindCurve, 0.45f)
            .v (PID::rewindSpeed, 1.4f).v (PID::rewindTail, 0.26f)
            .v (PID::rewindMix, 0.44f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.36f)
            .v (PID::grainSize, 70.0f).v (PID::grainDensity, 16.0f)
            .v (PID::grainPosition, 0.20f).v (PID::grainPitchMode, ch::gOctave)
            .v (PID::grainSpread, 0.50f).v (PID::grainJitter, 0.34f)
            .v (PID::grainDirection, 0.18f).v (PID::grainWindow, ch::wHann)
            .v (PID::grainMix, 0.34f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.24f)
            .v (PID::crushBits, 12.0f).v (PID::crushRate, 21000.0f)
            .v (PID::crushTone, 0.04f).v (PID::crushMix, 0.32f)
            .v (PID::macroMemory, 0.34f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.42f).v (PID::memoryWobble, 0.36f)
            .v (PID::macroCharacter, 0.34f).v (PID::macroMotion, 0.64f)
            .v (PID::macroWorld, 0.42f).v (PID::macroWeight, 0.30f)
            .v (PID::weightMode, ch::wBody).v (PID::weightHarmonics, 0.36f)
            .v (PID::retroEra, 0.34f).v (PID::retroAge, 0.26f)
            .v (PID::retroDrift, 0.26f).v (PID::retroWear, 0.14f)
            .v (PID::retroNoise, 0.12f).v (PID::retroMix, 0.44f)
            .v (PID::fxFilterMode, ch::f2Hp).v (PID::fxFilterCutoff, 120.0f)
            .v (PID::fxFilterRes, 0.10f).v (PID::fxFilterMix, 0.65f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.38f)
            .v (PID::spaceSize, 0.60f).v (PID::spaceDecay, 3.6f)
            .v (PID::spaceFog, 0.48f).v (PID::spaceLight, -0.08f)
            .v (PID::spacePreDelay, 30.0f).v (PID::spaceMix, 0.34f)
            .v (PID::auraSize, 0.58f).v (PID::auraDistance, 0.32f)
            .v (PID::auraFog, 0.44f).v (PID::auraDecay, 0.54f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaNoise, 0.14f)
            .v (PID::patinaWear, 0.24f).v (PID::patinaDrift, 0.26f)
            .v (PID::synthWidth, 1.10f).v (PID::highWidth, 1.22f)
            .v (PID::lowMonoFreq, 140.0f)
            .v (PID::breathAmount, 0.50f).v (PID::breathSpeed, 0.24f)
            .v (PID::breathRandom, 0.58f)
            .v (PID::lfo1Sync, 1.0f).v (PID::lfo1Shape, ch::lfoTri)
            .v (PID::lfo1Division, ch::d4).v (PID::lfo1Depth, 0.60f)
            .route (srcPulse, PID::oscAWtPos, 0.42f)
            .route (srcLfo1, PID::oscBWtPos, 0.26f)
            .route (srcBreath, PID::grainPosition, 0.20f)
            .route (srcMotion, PID::rewindTail, 0.16f));

        // ---------------------------------------------------------------
        //  DARK, HAUNTED AND INHUMAN VOICES
        // ---------------------------------------------------------------

        // The FORMANT filter parked at 190 Hz, below where a first formant can
        // sit on a human throat, with Generation IV and a worn medium on top.
        add (out, Build ("Garganta de Hierro", "VOCAL-LIKE", "DARK",
                         "inhuman,formant,generation iv,worn",
                         "The FORMANT filter parked far below where a throat can put a first formant, key track at zero, with Generation IV memory and a heavily worn medium over it.")
            .at (48, 2, 0.70f, 5.0)
            .chain ("RETRO,FILTER,CRUSH,GRAIN,REWIND,SPACE")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::masterGain, -2.0f)
            .v (PID::polyphony, 6.0f).v (PID::voiceVariation, 0.52f)
            .v (PID::driftAmount, 0.40f).v (PID::driftRate, 0.06f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tVocal)
            .v (PID::oscAWtPos, 0.86f).v (PID::oscALevel, 0.72f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.20f)
            .v (PID::oscASpread, 0.35f)
            .v (PID::oscBWave, ch::saw).v (PID::oscBLevel, 0.36f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, -14.0f)
            .v (PID::oscBUnison, 2.0f).v (PID::oscBDetune, 0.24f)
            .v (PID::oscRingMod, 0.16f)
            .v (PID::subWave, ch::subTri).v (PID::subLevel, 0.22f)
            .v (PID::subOctave, ch::subMinus1).v (PID::subHarmonics, 0.30f)
            .v (PID::noiseType, ch::nDark).v (PID::noiseLevel, 0.18f)
            .v (PID::bodyAmount, 0.42f).v (PID::bodyTilt, -0.25f)
            .v (PID::densityAmount, 0.32f).v (PID::preFilterDrive, 0.28f)
            .v (PID::postSaturation, 0.22f).v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 190.0f).v (PID::filterResonance, 0.70f)
            .v (PID::filterKeyTrack, 0.0f).v (PID::filterEnvAmount, -0.30f)
            .v (PID::filterVelAmount, 0.25f).v (PID::filterDrive, 0.34f)
            .v (PID::env1Attack, 1.4f).v (PID::env1Decay, 5.0f)
            .v (PID::env1Sustain, 0.40f).v (PID::env1Release, 2.4f)
            .v (PID::ampAttack, 0.30f).v (PID::ampDecay, 2.6f)
            .v (PID::ampSustain, 0.80f).v (PID::ampRelease, 2.6f)
            .v (PID::ampVelocity, 0.40f)
            .v (PID::macroMemory, 0.82f).v (PID::memoryGen, ch::genIV)
            .v (PID::memoryBandwidth, 0.72f).v (PID::memoryWobble, 0.58f)
            .v (PID::memoryDiffusion, 0.62f).v (PID::memoryAsymmetry, 0.56f)
            .v (PID::macroCharacter, 0.62f).v (PID::macroMotion, 0.58f)
            .v (PID::macroWorld, 0.40f).v (PID::macroWeight, 0.44f)
            .v (PID::weightMode, ch::wSub).v (PID::weightHarmonics, 0.46f)
            .v (PID::weightCompress, 0.35f)
            .v (PID::retroEra, 0.20f).v (PID::retroAge, 0.62f)
            .v (PID::retroDrift, 0.46f).v (PID::retroWear, 0.48f)
            .v (PID::retroTone, -0.30f).v (PID::retroNoise, 0.24f)
            .v (PID::retroMix, 0.82f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.30f)
            .v (PID::crushBits, 8.0f).v (PID::crushRate, 12000.0f)
            .v (PID::crushJitter, 0.22f).v (PID::crushDrive, 0.20f)
            .v (PID::crushTone, -0.14f).v (PID::crushMix, 0.40f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.30f)
            .v (PID::grainSize, 200.0f).v (PID::grainDensity, 6.0f)
            .v (PID::grainPosition, 0.40f).v (PID::grainPitchMode, ch::gRoot)
            .v (PID::grainSpread, 0.40f).v (PID::grainJitter, 0.30f)
            .v (PID::grainDirection, 0.20f).v (PID::grainWindow, ch::wExpo)
            .v (PID::grainMix, 0.30f)
            .v (PID::fxFilterCutoff, 3000.0f).v (PID::fxFilterRes, 0.16f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.48f)
            .v (PID::spaceSize, 0.70f).v (PID::spaceDecay, 6.0f)
            .v (PID::spaceFog, 0.66f).v (PID::spaceLight, -0.40f)
            .v (PID::spacePreDelay, 30.0f).v (PID::spaceMix, 0.30f)
            .v (PID::shadowOn, 1.0f).v (PID::shadowLength, 0.50f)
            .v (PID::shadowDistance, 0.58f).v (PID::shadowBlur, 0.56f)
            .v (PID::shadowPitch, -7.0f).v (PID::shadowLevel, 0.26f)
            .v (PID::auraSize, 0.66f).v (PID::auraDistance, 0.36f)
            .v (PID::auraFog, 0.58f).v (PID::auraDecay, 0.62f)
            .v (PID::auraLight, -0.30f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaTone, -0.28f)
            .v (PID::patinaNoise, 0.24f).v (PID::patinaWear, 0.44f)
            .v (PID::patinaDrift, 0.36f)
            .v (PID::synthWidth, 0.95f).v (PID::highWidth, 1.00f)
            .v (PID::lowMonoFreq, 170.0f)
            .v (PID::breathAmount, 0.58f).v (PID::breathSpeed, 0.07f)
            .v (PID::breathRandom, 0.66f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Rate, 0.06f)
            .v (PID::lfo1Depth, 0.70f)
            .route (srcLfo1, PID::filterCutoff, 0.28f)
            .route (srcBreath, PID::filterResonance, 0.18f)
            .route (srcMemory, PID::retroWear, 0.22f)
            .route (srcOrganic, PID::shadowPitch, -0.16f));

        // Two resonance sets that do not agree: a COMB tuned away from the note
        // feeding a FORMANT creative filter placed an octave and a half above.
        add (out, Build ("Lengua Muerta", "VOCAL-LIKE", "COLD",
                         "inhuman,comb,second filter,dive",
                         "A COMB filter tuned away from the note feeding the creative filter in FORMANT, the two resonance sets placed at unrelated frequencies, with REWIND in DIVE under them.")
            .at (51, 2, 0.66f, 5.0)
            .chain ("FILTER,CRUSH,GRAIN,REWIND,RETRO,SPACE")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::masterGain, 1.0f)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.48f)
            .v (PID::driftAmount, 0.32f).v (PID::driftRate, 0.12f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tHollow)
            .v (PID::oscAWtPos, 0.42f).v (PID::oscALevel, 0.66f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.16f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tVocal)
            .v (PID::oscBWtPos, 0.64f).v (PID::oscBLevel, 0.34f)
            .v (PID::oscBFine, 13.0f)
            .v (PID::oscSync, 0.12f)
            .v (PID::subLevel, 0.08f)
            .v (PID::noiseType, ch::nDust).v (PID::noiseLevel, 0.14f)
            .v (PID::bodyAmount, 0.20f).v (PID::densityAmount, 0.22f)
            .v (PID::postSaturation, 0.12f).v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fComb).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 330.0f).v (PID::filterResonance, 0.58f)
            .v (PID::filterKeyTrack, 0.0f).v (PID::filterEnvAmount, 0.24f)
            .v (PID::filterDrive, 0.20f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Formant)
            .v (PID::filter2Cutoff, 1450.0f).v (PID::filter2Res, 0.60f)
            .v (PID::filter2Mix, 0.66f)
            .v (PID::env1Attack, 0.80f).v (PID::env1Decay, 3.4f)
            .v (PID::env1Sustain, 0.45f).v (PID::env1Release, 1.8f)
            .v (PID::ampAttack, 0.45f).v (PID::ampDecay, 2.4f)
            .v (PID::ampSustain, 0.76f).v (PID::ampRelease, 2.2f)
            .v (PID::ampVelocity, 0.38f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.28f)
            .v (PID::crushBits, 9.0f).v (PID::crushRate, 14000.0f)
            .v (PID::crushJitter, 0.24f).v (PID::crushTone, -0.10f)
            .v (PID::crushMix, 0.38f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.34f)
            .v (PID::grainSize, 120.0f).v (PID::grainDensity, 9.0f)
            .v (PID::grainPosition, 0.50f).v (PID::grainPitchMode, ch::gThird)
            .v (PID::grainSpread, 0.58f).v (PID::grainJitter, 0.40f)
            .v (PID::grainDirection, 0.30f).v (PID::grainWindow, ch::wGauss)
            .v (PID::grainMix, 0.32f)
            .v (PID::rewindOn, 1.0f).v (PID::rewindMode, ch::rDive)
            .v (PID::rewindDivision, ch::rw2).v (PID::rewindCurve, 0.70f)
            .v (PID::rewindSpeed, 0.6f).v (PID::rewindTail, 0.34f)
            .v (PID::rewindMix, 0.40f)
            .v (PID::macroMemory, 0.54f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.60f).v (PID::memoryWobble, 0.50f)
            .v (PID::memoryDiffusion, 0.52f).v (PID::memoryAsymmetry, 0.48f)
            .v (PID::macroCharacter, 0.42f).v (PID::macroMotion, 0.60f)
            .v (PID::macroWorld, 0.46f).v (PID::macroWeight, 0.18f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::retroEra, 0.72f).v (PID::retroAge, 0.44f)
            .v (PID::retroDrift, 0.38f).v (PID::retroWear, 0.32f)
            .v (PID::retroTone, -0.22f).v (PID::retroNoise, 0.18f)
            .v (PID::retroMix, 0.60f)
            .v (PID::fxFilterMode, ch::f2Notch).v (PID::fxFilterCutoff, 2400.0f)
            .v (PID::fxFilterRes, 0.22f).v (PID::fxFilterMix, 0.45f)
            .v (PID::spaceCharacter, ch::sDark).v (PID::spaceDistance, 0.50f)
            .v (PID::spaceSize, 0.72f).v (PID::spaceDecay, 8.0f)
            .v (PID::spaceFog, 0.68f).v (PID::spaceLight, -0.34f)
            .v (PID::spacePreDelay, 34.0f).v (PID::spaceMix, 0.34f)
            .v (PID::auraSize, 0.70f).v (PID::auraDistance, 0.40f)
            .v (PID::auraFog, 0.58f).v (PID::auraDecay, 0.66f)
            .v (PID::auraLight, -0.24f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.20f)
            .v (PID::patinaNoise, 0.20f).v (PID::patinaWear, 0.34f)
            .v (PID::patinaDrift, 0.34f)
            .v (PID::synthWidth, 1.10f).v (PID::highWidth, 1.18f)
            .v (PID::breathAmount, 0.62f).v (PID::breathSpeed, 0.14f)
            .v (PID::breathRandom, 0.68f).v (PID::breathShape, 0.55f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Rate, 0.16f)
            .v (PID::lfo1Depth, 0.60f)
            .v (PID::lfo2Shape, ch::lfoRandom).v (PID::lfo2Rate, 0.80f)
            .v (PID::lfo2Depth, 0.45f)
            .route (srcLfo1, PID::filter2Cutoff, 0.30f)
            .route (srcLfo2, PID::filterCutoff, 0.20f)
            .route (srcBreath, PID::filter2Res, 0.16f)
            .route (srcMemory, PID::grainPosition, 0.22f));

        // ---------------------------------------------------------------
        //  CINEMATIC VOCAL SWELLS
        // ---------------------------------------------------------------

        // A slow amplitude swell with envelope 1 opening the formant over the
        // same span, into the longest reverb in this file.
        add (out, Build ("Prayer at Altitude", "VOCAL-LIKE", "CINEMATIC",
                         "cinematic,swell,choir,formant",
                         "A slow amplitude swell on a six-voice unison VOCAL stack with envelope 1 opening the FORMANT filter across it, into a twenty-two second INFINITE reverb.")
            .at (54, 4, 0.68f, 6.0)
            .chain ("FILTER,RETRO,GRAIN,SPACE,REWIND,CRUSH")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::masterGain, 5.0f)
            .v (PID::polyphony, 16.0f).v (PID::voiceVariation, 0.56f)
            .v (PID::driftAmount, 0.38f).v (PID::driftRate, 0.05f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tVocal)
            .v (PID::oscAWtPos, 0.20f).v (PID::oscALevel, 0.78f)
            .v (PID::oscAUnison, 6.0f).v (PID::oscADetune, 0.20f)
            .v (PID::oscASpread, 0.66f).v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tSpectral)
            .v (PID::oscBWtPos, 0.34f).v (PID::oscBLevel, 0.36f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, -6.0f)
            .v (PID::oscBUnison, 2.0f).v (PID::oscBDetune, 0.14f)
            .v (PID::oscBSpread, 0.50f)
            .v (PID::oscCWave, ch::wt).v (PID::oscCWtTable, ch::tSoft)
            .v (PID::oscCLevel, 0.14f).v (PID::oscCOctave, -1.0f)
            .v (PID::subLevel, 0.12f).v (PID::subHarmonics, 0.24f)
            .v (PID::noiseType, ch::nAir).v (PID::noiseLevel, 0.20f)
            .v (PID::bodyAmount, 0.32f).v (PID::densityAmount, 0.36f)
            .v (PID::postSaturation, 0.10f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 480.0f).v (PID::filterResonance, 0.42f)
            .v (PID::filterKeyTrack, 0.0f).v (PID::filterEnvAmount, 0.55f)
            .v (PID::filterVelAmount, 0.25f)
            .v (PID::env1Attack, 2.4f).v (PID::env1Decay, 6.0f)
            .v (PID::env1Sustain, 0.70f).v (PID::env1Release, 4.0f)
            .v (PID::ampAttack, 2.6f).v (PID::ampDecay, 5.0f)
            .v (PID::ampSustain, 0.90f).v (PID::ampRelease, 6.0f)
            .v (PID::ampVelocity, 0.30f)
            .v (PID::macroMemory, 0.26f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.32f).v (PID::memoryDiffusion, 0.52f)
            .v (PID::macroCharacter, 0.26f).v (PID::macroMotion, 0.62f)
            .v (PID::macroWorld, 0.80f).v (PID::macroWeight, 0.30f)
            .v (PID::weightMode, ch::wAir).v (PID::weightHarmonics, 0.42f)
            .v (PID::retroEra, 0.58f).v (PID::retroAge, 0.14f)
            .v (PID::retroDrift, 0.22f).v (PID::retroNoise, 0.08f)
            .v (PID::retroMix, 0.28f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.28f)
            .v (PID::grainSize, 220.0f).v (PID::grainDensity, 7.0f)
            .v (PID::grainPosition, 0.34f).v (PID::grainPitchMode, ch::gOctave)
            .v (PID::grainSpread, 0.70f).v (PID::grainJitter, 0.26f)
            .v (PID::grainDirection, 0.12f).v (PID::grainWindow, ch::wGauss)
            .v (PID::grainMix, 0.30f)
            .v (PID::fxFilterCutoff, 11000.0f).v (PID::fxFilterRes, 0.10f)
            .v (PID::spaceCharacter, ch::sInfinite).v (PID::spaceDistance, 0.60f)
            .v (PID::spaceSize, 0.92f).v (PID::spaceDecay, 22.0f)
            .v (PID::spaceFog, 0.74f).v (PID::spaceLight, -0.06f)
            .v (PID::spacePreDelay, 50.0f).v (PID::spaceMix, 0.46f)
            .v (PID::shadowOn, 1.0f).v (PID::shadowLength, 0.60f)
            .v (PID::shadowDistance, 0.70f).v (PID::shadowBlur, 0.62f)
            .v (PID::shadowPitch, 7.0f).v (PID::shadowLevel, 0.24f)
            .v (PID::auraSize, 0.90f).v (PID::auraDistance, 0.48f)
            .v (PID::auraFog, 0.62f).v (PID::auraDecay, 0.86f)
            .v (PID::auraLight, 0.08f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, -0.04f)
            .v (PID::patinaNoise, 0.12f).v (PID::patinaWear, 0.16f)
            .v (PID::patinaDrift, 0.28f)
            .v (PID::synthWidth, 1.30f).v (PID::highWidth, 1.40f)
            .v (PID::lowMonoFreq, 160.0f)
            .v (PID::breathAmount, 0.72f).v (PID::breathSpeed, 0.06f)
            .v (PID::breathRandom, 0.58f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.05f)
            .v (PID::lfo1Depth, 0.70f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.09f)
            .v (PID::lfo2Depth, 0.55f)
            .route (srcLfo1, PID::filterCutoff, 0.24f)
            .route (srcLfo2, PID::oscAWtPos, 0.22f)
            .route (srcBreath, PID::spaceSize, 0.14f)
            .route (srcWorld, PID::auraDistance, 0.16f)
            .route (srcMotion, PID::shadowLength, 0.14f));

        // Eight unison sub-voices per oscillator with the creative filter in
        // FORMANT as one fixed throat over the whole mass.
        add (out, Build ("Ten Thousand Throats", "VOCAL-LIKE", "CINEMATIC",
                         "cinematic,choir,second filter,swell",
                         "Eight unison sub-voices of the VOCAL table with the creative filter in FORMANT as the one fixed throat over all of them, Weight on AIR and a twenty second tail.")
            .at (49, 4, 0.72f, 6.0)
            .chain ("SPACE,FILTER,RETRO,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::mass)
            .v (PID::masterGain, 3.0f)
            .v (PID::polyphony, 16.0f).v (PID::voiceVariation, 0.60f)
            .v (PID::driftAmount, 0.44f).v (PID::driftRate, 0.06f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tVocal)
            .v (PID::oscAWtPos, 0.46f).v (PID::oscALevel, 0.74f)
            .v (PID::oscAUnison, 8.0f).v (PID::oscADetune, 0.26f)
            .v (PID::oscASpread, 0.70f).v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tVocal)
            .v (PID::oscBWtPos, 0.12f).v (PID::oscBLevel, 0.40f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, 11.0f)
            .v (PID::oscBUnison, 4.0f).v (PID::oscBDetune, 0.20f)
            .v (PID::oscBSpread, 0.60f).v (PID::oscBPhase, ch::phaseRandom)
            .v (PID::subWave, ch::subSine).v (PID::subLevel, 0.16f)
            .v (PID::subHarmonics, 0.28f)
            .v (PID::noiseType, ch::nPink).v (PID::noiseLevel, 0.18f)
            .v (PID::bodyAmount, 0.38f).v (PID::densityAmount, 0.40f)
            .v (PID::preFilterDrive, 0.18f).v (PID::postSaturation, 0.14f)
            .v (PID::postSatMode, ch::satDense)
            .v (PID::filterModel, ch::fMass).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 4200.0f).v (PID::filterResonance, 0.18f)
            .v (PID::filterKeyTrack, 0.40f).v (PID::filterEnvAmount, 0.30f)
            .v (PID::filterVelAmount, 0.28f)
            .v (PID::filter2On, 1.0f).v (PID::filter2Type, ch::f2Formant)
            .v (PID::filter2Cutoff, 580.0f).v (PID::filter2Res, 0.52f)
            .v (PID::filter2Mix, 0.76f)
            .v (PID::env1Attack, 1.8f).v (PID::env1Decay, 5.5f)
            .v (PID::env1Sustain, 0.60f).v (PID::env1Release, 3.5f)
            .v (PID::ampAttack, 1.9f).v (PID::ampDecay, 4.5f)
            .v (PID::ampSustain, 0.88f).v (PID::ampRelease, 5.5f)
            .v (PID::ampVelocity, 0.32f)
            .v (PID::macroMemory, 0.34f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.42f).v (PID::memoryWobble, 0.34f)
            .v (PID::memoryDiffusion, 0.56f)
            .v (PID::macroCharacter, 0.34f).v (PID::macroMotion, 0.66f)
            .v (PID::macroWorld, 0.78f).v (PID::macroWeight, 0.42f)
            .v (PID::weightMode, ch::wAir).v (PID::weightHarmonics, 0.48f)
            .v (PID::weightCompress, 0.34f)
            .v (PID::retroEra, 0.50f).v (PID::retroAge, 0.22f)
            .v (PID::retroDrift, 0.26f).v (PID::retroWear, 0.10f)
            .v (PID::retroTone, -0.10f).v (PID::retroNoise, 0.10f)
            .v (PID::retroMix, 0.38f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.32f)
            .v (PID::grainSize, 260.0f).v (PID::grainDensity, 6.0f)
            .v (PID::grainPosition, 0.42f).v (PID::grainPitchMode, ch::gFifth)
            .v (PID::grainSpread, 0.74f).v (PID::grainJitter, 0.30f)
            .v (PID::grainDirection, 0.16f).v (PID::grainWindow, ch::wGauss)
            .v (PID::grainFeedback, 0.12f).v (PID::grainMix, 0.34f)
            .v (PID::fxFilterCutoff, 9500.0f).v (PID::fxFilterRes, 0.12f)
            .v (PID::spaceCharacter, ch::sInfinite).v (PID::spaceDistance, 0.58f)
            .v (PID::spaceSize, 0.90f).v (PID::spaceDecay, 20.0f)
            .v (PID::spaceFog, 0.72f).v (PID::spaceLight, -0.12f)
            .v (PID::spacePreDelay, 46.0f).v (PID::spaceMix, 0.48f)
            .v (PID::shadowOn, 1.0f).v (PID::shadowLength, 0.58f)
            .v (PID::shadowDistance, 0.68f).v (PID::shadowBlur, 0.64f)
            .v (PID::shadowPitch, -12.0f).v (PID::shadowLevel, 0.28f)
            .v (PID::auraSize, 0.88f).v (PID::auraDistance, 0.46f)
            .v (PID::auraFog, 0.64f).v (PID::auraDecay, 0.84f)
            .v (PID::auraLight, -0.04f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.12f)
            .v (PID::patinaNoise, 0.16f).v (PID::patinaWear, 0.22f)
            .v (PID::patinaDrift, 0.32f)
            .v (PID::synthWidth, 1.28f).v (PID::highWidth, 1.38f)
            .v (PID::lowMonoFreq, 170.0f)
            .v (PID::breathAmount, 0.70f).v (PID::breathSpeed, 0.05f)
            .v (PID::breathRandom, 0.62f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Rate, 0.04f)
            .v (PID::lfo1Depth, 0.75f)
            .v (PID::lfo2Shape, ch::lfoSine).v (PID::lfo2Rate, 0.11f)
            .v (PID::lfo2Depth, 0.50f)
            .route (srcLfo1, PID::filter2Cutoff, 0.28f)
            .route (srcLfo2, PID::filter2Res, 0.16f)
            .route (srcBreath, PID::oscBWtPos, 0.20f)
            .route (srcWorld, PID::spaceDecay, 0.14f)
            .route (srcMotion, PID::grainPosition, 0.18f));
    }
}
