#include "PresetBuilder.h"
#include "Builders.h"

namespace nacar::presets::detail
{
    // ===============================================================
    //  VOCAL-LIKE
    // ===============================================================
    void buildVocal (std::vector<FactoryPreset>& out)
    {
        // The VOCAL wavetable through the FORMANT filter model, which puts
        // formants at ratios of the cutoff rather than at fixed frequencies.
        add (out, Build ("Salt Choir", "VOCAL-LIKE", "HAUNTED",
                         "choir,formant,generation iii,shadow",
                         "Voices that have been through the medium more times than the words have.")
            .at (48, 4, 0.66f, 8.0)
            .chain ("RETRO,FILTER,SPACE,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::masterGain, 4.0f)
            .v (PID::polyphony, 12.0f).v (PID::voiceVariation, 0.62f)
            .v (PID::driftAmount, 0.42f).v (PID::driftRate, 0.07f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tVocal)
            .v (PID::oscAWtPos, 0.28f).v (PID::oscALevel, 0.86f)
            .v (PID::oscAUnison, 4.0f).v (PID::oscADetune, 0.16f)
            .v (PID::oscASpread, 0.52f).v (PID::oscAPhase, ch::phaseRandom)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tVocal)
            .v (PID::oscBWtPos, 0.74f).v (PID::oscBLevel, 0.34f)
            .v (PID::oscBOctave, -1.0f).v (PID::oscBFine, 6.0f)
            .v (PID::subLevel, 0.14f)
            .v (PID::noiseType, ch::nTexture).v (PID::noiseLevel, 0.10f)
            .v (PID::bodyAmount, 0.28f).v (PID::densityAmount, 0.30f)
            .v (PID::postSaturation, 0.12f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fFormant).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 640.0f).v (PID::filterResonance, 0.38f)
            .v (PID::filterKeyTrack, 0.15f).v (PID::filterEnvAmount, 0.26f)
            .v (PID::filterVelAmount, 0.30f)
            .v (PID::ampAttack, 0.9f).v (PID::ampDecay, 3.4f)
            .v (PID::ampSustain, 0.80f).v (PID::ampRelease, 3.8f)
            .v (PID::ampVelocity, 0.40f)
            .v (PID::macroMemory, 0.56f).v (PID::memoryGen, ch::genIII)
            .v (PID::memoryBandwidth, 0.66f).v (PID::memoryWobble, 0.50f)
            .v (PID::memoryDiffusion, 0.60f).v (PID::memoryAsymmetry, 0.40f)
            .v (PID::macroCharacter, 0.40f).v (PID::macroMotion, 0.60f)
            .v (PID::macroWorld, 0.44f).v (PID::macroWeight, 0.24f)
            .v (PID::weightMode, ch::wAir)
            .v (PID::retroEra, 0.44f).v (PID::retroAge, 0.46f)
            .v (PID::retroDrift, 0.42f).v (PID::retroWear, 0.30f)
            .v (PID::retroTone, -0.18f).v (PID::retroNoise, 0.20f)
            .v (PID::retroMix, 0.74f)
            .v (PID::fxFilterMode, ch::f2Bp).v (PID::fxFilterCutoff, 1400.0f)
            .v (PID::fxFilterRes, 0.24f).v (PID::fxFilterMotion, 0.40f)
            .v (PID::fxFilterMix, 0.50f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.44f)
            .v (PID::spaceSize, 0.74f).v (PID::spaceDecay, 7.0f)
            .v (PID::spaceFog, 0.64f).v (PID::spaceLight, -0.26f)
            .v (PID::spacePreDelay, 20.0f).v (PID::spaceMix, 0.26f)
            .v (PID::shadowOn, 1.0f).v (PID::shadowLength, 0.46f)
            .v (PID::shadowDistance, 0.64f).v (PID::shadowBlur, 0.52f)
            .v (PID::shadowPitch, -5.0f).v (PID::shadowLevel, 0.22f)
            .v (PID::auraSize, 0.70f).v (PID::auraDistance, 0.32f)
            .v (PID::auraFog, 0.50f).v (PID::auraDecay, 0.68f)
            .v (PID::auraLight, -0.18f)
            .v (PID::patinaProfile, ch::pHaze).v (PID::patinaTone, -0.16f)
            .v (PID::patinaNoise, 0.20f).v (PID::patinaWear, 0.38f)
            .v (PID::patinaDrift, 0.38f)
            .v (PID::synthWidth, 1.00f).v (PID::highWidth, 1.10f)
            .v (PID::breathAmount, 0.64f).v (PID::breathSpeed, 0.09f)
            .v (PID::breathRandom, 0.70f)
            .v (PID::lfo1Shape, ch::lfoSmooth).v (PID::lfo1Rate, 0.11f)
            .v (PID::lfo1Depth, 0.65f)
            .route (srcLfo1, PID::filterCutoff, 0.18f)
            .route (srcBreath, PID::oscAWtPos, 0.24f)
            .route (srcMotion, PID::shadowLength, 0.16f));

        // Band-limited hard, crushed, and mixed almost entirely wet: the
        // preset is the transmission, not the singer.
        add (out, Build ("Radio Breath", "VOCAL-LIKE", "NOSTALGIC",
                         "am radio,band-limited,crush,close",
                         "A voice on longwave, with more of the radio in it than the voice.")
            .at (57, 2, 0.74f, 5.0)
            .chain ("FILTER,CRUSH,RETRO,SPACE,GRAIN,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.36f)
            .v (PID::driftAmount, 0.30f).v (PID::driftRate, 0.28f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tVocal)
            .v (PID::oscAWtPos, 0.52f).v (PID::oscALevel, 0.74f)
            .v (PID::oscAUnison, 2.0f).v (PID::oscADetune, 0.14f)
            .v (PID::oscBWave, ch::saw).v (PID::oscBLevel, 0.22f)
            .v (PID::oscBFine, -12.0f)
            .v (PID::subLevel, 0.0f)
            .v (PID::noiseType, ch::nPink).v (PID::noiseLevel, 0.12f)
            .v (PID::bodyAmount, 0.20f).v (PID::densityAmount, 0.22f)
            .v (PID::preFilterDrive, 0.26f).v (PID::postSaturation, 0.22f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::bp)
            .v (PID::filterCutoff, 1250.0f).v (PID::filterResonance, 0.42f)
            .v (PID::filterKeyTrack, 0.25f).v (PID::filterEnvAmount, 0.20f)
            .v (PID::ampAttack, 0.05f).v (PID::ampDecay, 1.2f)
            .v (PID::ampSustain, 0.76f).v (PID::ampRelease, 0.6f)
            .v (PID::ampVelocity, 0.52f)
            .v (PID::macroMemory, 0.52f).v (PID::memoryGen, ch::genII)
            .v (PID::memoryBandwidth, 0.80f).v (PID::memoryWobble, 0.46f)
            .v (PID::memoryDiffusion, 0.32f).v (PID::memoryAsymmetry, 0.50f)
            .v (PID::macroCharacter, 0.56f).v (PID::macroMotion, 0.44f)
            .v (PID::macroWorld, 0.26f).v (PID::macroWeight, 0.20f)
            .v (PID::weightMode, ch::wBody)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.46f)
            .v (PID::crushBits, 8.0f).v (PID::crushRate, 9000.0f)
            .v (PID::crushJitter, 0.26f).v (PID::crushDrive, 0.24f)
            .v (PID::crushTone, -0.16f).v (PID::crushMix, 0.62f)
            .v (PID::retroEra, 0.06f).v (PID::retroAge, 0.56f)
            .v (PID::retroDrift, 0.38f).v (PID::retroWear, 0.42f)
            .v (PID::retroTone, -0.20f).v (PID::retroNoise, 0.30f)
            .v (PID::retroMix, 0.90f)
            .v (PID::fxFilterMode, ch::f2Bp).v (PID::fxFilterCutoff, 1700.0f)
            .v (PID::fxFilterRes, 0.30f).v (PID::fxFilterMorph, 0.20f)
            .v (PID::fxFilterMix, 0.85f)
            .v (PID::spaceCharacter, ch::sRoom).v (PID::spaceDistance, 0.30f)
            .v (PID::spaceSize, 0.26f).v (PID::spaceDecay, 1.0f)
            .v (PID::spaceFog, 0.30f).v (PID::spaceLight, -0.30f)
            .v (PID::spaceMix, 0.18f)
            .v (PID::auraSize, 0.28f).v (PID::auraDistance, 0.20f)
            .v (PID::auraFog, 0.40f).v (PID::auraDecay, 0.24f)
            .v (PID::auraLight, -0.24f)
            .v (PID::patinaProfile, ch::pVintage).v (PID::patinaTone, -0.20f)
            .v (PID::patinaNoise, 0.30f).v (PID::patinaWear, 0.40f)
            .v (PID::patinaDrift, 0.30f)
            .v (PID::synthWidth, 0.70f).v (PID::highWidth, 0.80f)
            .v (PID::breathAmount, 0.50f).v (PID::breathSpeed, 0.30f)
            .v (PID::breathRandom, 0.70f).v (PID::breathShape, 0.60f)
            .v (PID::lfo2Shape, ch::lfoSmooth).v (PID::lfo2Rate, 0.42f)
            .v (PID::lfo2Depth, 0.55f)
            .route (srcLfo2, PID::fxFilterCutoff, 0.14f)
            .route (srcBreath, PID::retroWear, 0.20f)
            .route (srcOrganic, PID::crushRate, -0.14f));

        // Generation IV plus a dense short-grain cloud in the chain: the
        // syllables are grains, and they do not come back in order.
        add (out, Build ("Memory Vocoder", "VOCAL-LIKE", "BROKEN",
                         "granular,generation iv,stutter,glitch",
                         "A vocal reassembled out of its own recent past, in the wrong order.")
            .at (53, 3, 0.80f, 6.0)
            .chain ("RETRO,GRAIN,CRUSH,FILTER,SPACE,REWIND")
            .v (PID::synthCharacter, ch::mirage)
            .v (PID::polyphony, 8.0f).v (PID::voiceVariation, 0.50f)
            .v (PID::driftAmount, 0.28f).v (PID::driftRate, 0.40f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tVocal)
            .v (PID::oscAWtPos, 0.36f).v (PID::oscALevel, 0.72f)
            .v (PID::oscBWave, ch::wt).v (PID::oscBWtTable, ch::tAsym)
            .v (PID::oscBWtPos, 0.46f).v (PID::oscBLevel, 0.30f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, -16.0f)
            .v (PID::oscRingMod, 0.14f)
            .v (PID::subLevel, 0.10f)
            .v (PID::noiseType, ch::nDigital).v (PID::noiseLevel, 0.08f)
            .v (PID::bodyAmount, 0.18f).v (PID::densityAmount, 0.20f)
            .v (PID::preFilterDrive, 0.20f).v (PID::postSaturation, 0.16f)
            .v (PID::postSatMode, ch::satEdge)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 4200.0f).v (PID::filterResonance, 0.22f)
            .v (PID::filterKeyTrack, 0.40f).v (PID::filterEnvAmount, 0.30f)
            .v (PID::ampAttack, 0.02f).v (PID::ampDecay, 1.6f)
            .v (PID::ampSustain, 0.70f).v (PID::ampRelease, 1.0f)
            .v (PID::macroMemory, 0.78f).v (PID::memoryGen, ch::genIV)
            .v (PID::memoryBandwidth, 0.70f).v (PID::memoryWobble, 0.56f)
            .v (PID::memoryDiffusion, 0.58f).v (PID::memoryAsymmetry, 0.54f)
            .v (PID::macroCharacter, 0.50f).v (PID::macroMotion, 0.70f)
            .v (PID::macroWorld, 0.46f).v (PID::macroWeight, 0.22f)
            .v (PID::macroAlter, 0.35f)
            .v (PID::grainFxOn, 1.0f).v (PID::grainScatter, 0.62f)
            .v (PID::grainSize, 42.0f).v (PID::grainDensity, 34.0f)
            .v (PID::grainPosition, 0.24f).v (PID::grainPitchMode, ch::gScale)
            .v (PID::grainSpread, 0.66f).v (PID::grainJitter, 0.62f)
            .v (PID::grainDirection, 0.34f).v (PID::grainWindow, ch::wTukey)
            .v (PID::grainFeedback, 0.18f).v (PID::grainMix, 0.58f)
            .v (PID::crushOn, 1.0f).v (PID::crushAmount, 0.36f)
            .v (PID::crushBits, 9.0f).v (PID::crushRate, 15000.0f)
            .v (PID::crushJitter, 0.40f).v (PID::crushMix, 0.44f)
            .v (PID::retroEra, 0.86f).v (PID::retroAge, 0.42f)
            .v (PID::retroDrift, 0.34f).v (PID::retroWear, 0.50f)
            .v (PID::retroNoise, 0.18f).v (PID::retroMix, 0.72f)
            .v (PID::fxFilterCutoff, 7600.0f).v (PID::fxFilterRes, 0.18f)
            .v (PID::spaceCharacter, ch::sChamber).v (PID::spaceDistance, 0.42f)
            .v (PID::spaceSize, 0.54f).v (PID::spaceDecay, 3.2f)
            .v (PID::spaceFog, 0.50f).v (PID::spaceMix, 0.30f)
            .v (PID::auraSize, 0.52f).v (PID::auraDistance, 0.34f)
            .v (PID::auraFog, 0.56f).v (PID::auraDecay, 0.46f)
            .v (PID::patinaProfile, ch::pSmoke).v (PID::patinaNoise, 0.24f)
            .v (PID::patinaWear, 0.46f).v (PID::patinaDrift, 0.40f)
            .v (PID::synthWidth, 1.15f).v (PID::highWidth, 1.25f)
            .v (PID::breathAmount, 0.60f).v (PID::breathSpeed, 0.55f)
            .v (PID::breathRandom, 0.85f).v (PID::breathShape, 0.80f)
            .v (PID::lfo2Shape, ch::lfoRandom).v (PID::lfo2Rate, 2.6f)
            .v (PID::lfo2Depth, 0.60f)
            .route (srcLfo2, PID::grainPosition, 0.44f)
            .route (srcBreath, PID::grainSize, 0.30f)
            .route (srcOrganic, PID::grainDirection, 0.26f));

        // Shadow an octave up behind a soft vocal table, and the widest
        // Aura in the library.  Nothing dirty anywhere in the chain.
        add (out, Build ("Distant Aria", "VOCAL-LIKE", "ROMANTIC",
                         "soprano,shadow,octave,far",
                         "A soprano at the other end of the building, with her own echo an octave up.")
            .at (60, 3, 0.62f, 9.0)
            .chain ("FILTER,SPACE,RETRO,GRAIN,CRUSH,REWIND")
            .v (PID::synthCharacter, ch::haze)
            .v (PID::masterGain, 4.0f)
            .v (PID::polyphony, 10.0f).v (PID::voiceVariation, 0.42f)
            .v (PID::driftAmount, 0.30f).v (PID::driftRate, 0.06f)
            .v (PID::oscAWave, ch::wt).v (PID::oscAWtTable, ch::tVocal)
            .v (PID::oscAWtPos, 0.16f).v (PID::oscALevel, 0.70f)
            .v (PID::oscAUnison, 3.0f).v (PID::oscADetune, 0.14f)
            .v (PID::oscASpread, 0.48f)
            .v (PID::oscBWave, ch::sine).v (PID::oscBLevel, 0.26f)
            .v (PID::oscBOctave, 1.0f).v (PID::oscBFine, 7.0f)
            .v (PID::subLevel, 0.08f)
            .v (PID::noiseType, ch::nAir).v (PID::noiseLevel, 0.10f)
            .v (PID::bodyAmount, 0.18f).v (PID::densityAmount, 0.24f)
            .v (PID::postSaturation, 0.08f).v (PID::postSatMode, ch::satSoft)
            .v (PID::filterModel, ch::fHaze).v (PID::filterType, ch::lp)
            .v (PID::filterCutoff, 3600.0f).v (PID::filterResonance, 0.12f)
            .v (PID::filterKeyTrack, 0.60f).v (PID::filterEnvAmount, 0.24f)
            .v (PID::filterVelAmount, 0.40f)
            .v (PID::ampAttack, 0.55f).v (PID::ampDecay, 3.0f)
            .v (PID::ampSustain, 0.82f).v (PID::ampRelease, 3.6f)
            .v (PID::ampVelocity, 0.44f)
            .v (PID::macroMemory, 0.30f).v (PID::memoryGen, ch::genI)
            .v (PID::memoryBandwidth, 0.36f).v (PID::memoryWobble, 0.30f)
            .v (PID::memoryDiffusion, 0.48f)
            .v (PID::macroCharacter, 0.22f).v (PID::macroMotion, 0.52f)
            .v (PID::macroWorld, 0.58f).v (PID::macroWeight, 0.22f)
            .v (PID::weightMode, ch::wAir).v (PID::weightHarmonics, 0.44f)
            .v (PID::retroEra, 0.50f).v (PID::retroAge, 0.18f)
            .v (PID::retroDrift, 0.24f).v (PID::retroWear, 0.08f)
            .v (PID::retroNoise, 0.08f).v (PID::retroMix, 0.36f)
            .v (PID::fxFilterCutoff, 10000.0f)
            .v (PID::spaceCharacter, ch::sDistant).v (PID::spaceDistance, 0.68f)
            .v (PID::spaceSize, 0.82f).v (PID::spaceDecay, 8.5f)
            .v (PID::spaceFog, 0.58f).v (PID::spaceLight, -0.06f)
            .v (PID::spacePreDelay, 16.0f).v (PID::spaceMix, 0.38f)
            .v (PID::shadowOn, 1.0f).v (PID::shadowLength, 0.56f)
            .v (PID::shadowDistance, 0.60f).v (PID::shadowBlur, 0.48f)
            .v (PID::shadowPitch, 12.0f).v (PID::shadowLevel, 0.32f)
            .v (PID::auraSize, 0.84f).v (PID::auraDistance, 0.40f)
            .v (PID::auraFog, 0.56f).v (PID::auraDecay, 0.76f)
            .v (PID::auraLight, 0.10f)
            .v (PID::patinaProfile, ch::pSoft).v (PID::patinaTone, 0.04f)
            .v (PID::patinaNoise, 0.10f).v (PID::patinaWear, 0.16f)
            .v (PID::patinaDrift, 0.30f)
            .v (PID::synthWidth, 1.05f).v (PID::highWidth, 1.15f)
            .v (PID::breathAmount, 0.60f).v (PID::breathSpeed, 0.10f)
            .v (PID::modWheelDepth, 0.60f).v (PID::vibratoDepth, 0.26f)
            .v (PID::vibratoRate, 5.0f)
            .v (PID::lfo1Shape, ch::lfoSine).v (PID::lfo1Rate, 0.13f)
            .v (PID::lfo1Depth, 0.60f)
            .route (srcLfo1, PID::oscAWtPos, 0.16f)
            .route (srcBreath, PID::shadowDistance, 0.16f)
            .route (srcWorld, PID::auraSize, 0.12f));
    }
}
